redhat-openshift-ecosystem/community-operators-prod

operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.66.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.66.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.66.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.66.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.66.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.66.0)

operators/awx-operator/1.0.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/1.0.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/1.0.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/1.0.0/manifests/awx-operator.v1.0.0.clusterserviceversion.yaml, operators/awx-operator/1.0.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/1.0.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/1.0.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/1.0.0/metadata/annotations.yaml, operators/awx-operator/1.0.0/tests/scorecard/config.yaml
=> operator awx-operator (1.0.0)

operators/kiali/1.60.0/bundle.Dockerfile, operators/kiali/1.60.0/manifests/kiali.crd.yaml, operators/kiali/1.60.0/manifests/kiali.v1.60.0.clusterserviceversion.yaml, operators/kiali/1.60.0/metadata/annotations.yaml
=> operator kiali (1.60.0)

operators/koku-metrics-operator/1.1.9/Dockerfile, operators/koku-metrics-operator/1.1.9/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.9/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.9/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.9/tests/scorecard/config.yaml
Signed-off-by: maskarb <mskarbek@redhat.com>
--
=> operator koku-metrics-operator (1.1.9)

operators/gitwebhook-operator/0.1.0/Dockerfile, operators/gitwebhook-operator/0.1.0/manifests/gitwebhook-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/gitwebhook-operator/0.1.0/manifests/gitwebhook-operator-controller-manager-metrics-service_v1_service.yaml, operators/gitwebhook-operator/0.1.0/manifests/gitwebhook-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitwebhook-operator/0.1.0/manifests/gitwebhook-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/gitwebhook-operator/0.1.0/manifests/gitwebhook-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitwebhook-operator/0.1.0/manifests/gitwebhook-operator-webhook-service_v1_service.yaml, operators/gitwebhook-operator/0.1.0/manifests/gitwebhook-operator.clusterserviceversion.yaml, operators/gitwebhook-operator/0.1.0/manifests/redhatcop.redhat.io_gitwebhooks.yaml, operators/gitwebhook-operator/0.1.0/metadata/annotations.yaml, operators/gitwebhook-operator/0.1.0/tests/scorecard/config.yaml, operators/gitwebhook-operator/ci.yaml
=> operator [N] [CI] gitwebhook-operator (0.1.0)

ci/pipeline-config-ocp.yaml
=> Disable v4.12

operators/grafana-operator/4.8.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.8.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.8.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.8.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.8.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.8.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.8.0/integreatly.org_grafanafolders.yaml, operators/grafana-operator/4.8.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.8.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.8.0)

operators/awx-operator/1.1.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/1.1.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/1.1.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/1.1.0/manifests/awx-operator.v1.1.0.clusterserviceversion.yaml, operators/awx-operator/1.1.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/1.1.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/1.1.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/1.1.0/metadata/annotations.yaml, operators/awx-operator/1.1.0/tests/scorecard/config.yaml
=> operator awx-operator (1.1.0)

operators/portworx-essentials/1.10.1/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.10.1/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.10.1/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
Signed-off-by: CNBU Jenkins <cnbu-jenkins@purestorage.com>
--
=> operator portworx-essentials (1.10.1)

operators/mongodb-atlas-kubernetes/1.5.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.5.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.5.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.5.0/tests/scorecard/config.yaml
Signed-off-by: fabritsius <antonfabritsius@gmail.com>
1. [xx] Description of the managed Application and where to find more information
--
=> operator mongodb-atlas-kubernetes (1.5.0)

operators/netobserv-operator/0.2.1/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/0.2.1/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/0.2.1/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/0.2.1/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/0.2.1/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/0.2.1/metadata/annotations.yaml
=> operator netobserv-operator (0.2.1)

operators/ack-cloudtrail-controller/ci.yaml
=> operator [CI] ack-cloudtrail-controller

operators/project-quay/3.8.0/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.0/quayecosystems.crd.yaml, operators/project-quay/3.8.0/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.8.0 to community operators
=> operator project-quay (3.8.0)

operators/project-quay/3.9.0-nightly.1/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.1/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.9.0-nightly.1 to community operators
=> operator project-quay (3.9.0-nightly.1)

operators/annotationlab/4.4.1/bundle.Dockerfile, operators/annotationlab/4.4.1/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.4.1/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.4.1/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.4.1/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.4.1/metadata/annotations.yaml, operators/annotationlab/4.4.1/tests/scorecard/config.yaml
=> operator annotationlab (4.4.1)

operators/annotationlab/4.4.1/manifests/annotationlab.clusterserviceversion.yaml
=> operator [O] annotationlab (4.4.1)

operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsarbrokers.yaml
=> operator [O] pulsar-operator (0.11.5)

operators/aqua/2022.4.7/bundle.Dockerfile, operators/aqua/2022.4.7/manifests/aqua-operator.v2022.4.7.clusterserviceversion.yaml, operators/aqua/2022.4.7/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.7/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.7/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.7/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.7/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.7/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.7/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.7/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.7/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.7/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.7/metadata/annotations.yaml, operators/aqua/ci.yaml
Signed-off-by: Baruch Bilanski <baruch.bilanski@aquasec.com>
--
=> operator [CI] aqua (2022.4.7)

operators/project-quay/3.9.0-nightly.2022.12.11/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.11/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.11 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.11)

operators/vault-config-operator/0.8.3/metadata/annotations.yaml
After red PR  #1920  was merged the pipeline was broken, applying the label to fix it.
=> operator [O] vault-config-operator (0.8.3)

operators/awx-operator/1.1.2/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/1.1.2/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/1.1.2/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/1.1.2/manifests/awx-operator.v1.1.2.clusterserviceversion.yaml, operators/awx-operator/1.1.2/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/1.1.2/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/1.1.2/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/1.1.2/metadata/annotations.yaml, operators/awx-operator/1.1.2/tests/scorecard/config.yaml
Signed-off-by: Christian M. Adams <chadams@redhat.com>
--
=> operator awx-operator (1.1.2)

operators/dynatrace-operator/0.10.0/Dockerfile, operators/dynatrace-operator/0.10.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.10.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.10.0/metadata/annotations.yaml
=> operator dynatrace-operator (0.10.0)

operators/project-quay/3.9.0-nightly.2022.12.13/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.13/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.13 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.13)

operators/percona-xtradb-cluster-operator/1.12.0/manifests/percona-xtradb-cluster-operator.v1.12.0.clusterserviceversion.yaml, operators/percona-xtradb-cluster-operator/1.12.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.12.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.12.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.12.0/metadata/annotations.yaml, operators/percona-xtradb-cluster-operator/ci.yaml
=> operator [CI] percona-xtradb-cluster-operator (1.12.0)

operators/gitlab-operator-kubernetes/0.14.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.14.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.14.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.14.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.14.2)

operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml, operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml, operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml, operators/beegfs-csi-driver-operator/1.4.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml, operators/beegfs-csi-driver-operator/1.4.0/metadata/annotations.yaml, operators/beegfs-csi-driver-operator/1.4.0/tests/scorecard/config.yaml
Signed-off-by: Weber, Eric <Eric.Weber2@netapp.com>
--
=> operator beegfs-csi-driver-operator (1.4.0)

operators/camel-k/1.11.0/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.11.0/manifests/camel-k.v1.11.0.clusterserviceversion.yaml, operators/camel-k/1.11.0/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.11.0/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.11.0/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.11.0/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.11.0/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.11.0/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.11.0/metadata/annotations.yaml, operators/camel-k/1.11.0/tests/scorecard/config.yaml
=> operator camel-k (1.11.0)

operators/project-quay/3.9.0-nightly.2022.12.14/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.14/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.14 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.14)

operators/app-director-operator/0.9.1/Dockerfile, operators/app-director-operator/0.9.1/manifests/app-director-controller-manager-metrics-service_v1_service.yaml, operators/app-director-operator/0.9.1/manifests/app-director-manager-config_v1_configmap.yaml, operators/app-director-operator/0.9.1/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/app-director-operator/0.9.1/manifests/app-director-operator.clusterserviceversion.yaml, operators/app-director-operator/0.9.1/manifests/appdirector.randoli.ca_appdirectoragents.yaml, operators/app-director-operator/0.9.1/manifests/appdirector.randoli.ca_clusterwideappdirectoragents.yaml, operators/app-director-operator/0.9.1/metadata/annotations.yaml, operators/app-director-operator/0.9.1/tests/scorecard/config.yaml
=> operator app-director-operator (0.9.1)

operators/project-quay/3.9.0-nightly.2022.12.15/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.15/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.15 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.15)

operators/seldon-operator/1.15.0/manifests/machinelearning.seldon.io_seldondeployments.yaml, operators/seldon-operator/1.15.0/manifests/seldon-operator.clusterserviceversion.yaml, operators/seldon-operator/1.15.0/metadata/annotations.yaml, operators/seldon-operator/1.15.0/tests/scorecard/config.yaml
=> operator seldon-operator (1.15.0)

operators/hyperfoil-bundle/0.21.0/hyperfoil-operator.v0.21.0.clusterserviceversion.yaml, operators/hyperfoil-bundle/0.21.0/hyperfoil.io_hyperfoils_crd.yaml, operators/hyperfoil-bundle/ci.yaml, operators/hyperfoil-bundle/hyperfoil-bundle.package.yaml
=> operator hyperfoil-bundle (0.21.0)

operators/authorino-operator/0.5.0/bundle.Dockerfile, operators/authorino-operator/0.5.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.5.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.5.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.5.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.5.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.5.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml, operators/authorino-operator/0.5.0/manifests/authorino-operator-manager-config_v1_configmap.yaml, operators/authorino-operator/0.5.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.5.0/manifests/authorino-operator.clusterserviceversion.yaml, operators/authorino-operator/0.5.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.5.0/manifests/authorino.kuadrant.io_authconfigs.yaml, operators/authorino-operator/0.5.0/manifests/manager-config_v1_configmap.yaml, operators/authorino-operator/0.5.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml, operators/authorino-operator/0.5.0/metadata/annotations.yaml, operators/authorino-operator/0.5.0/tests/scorecard/config.yaml
Signed-off-by: Guilherme Cassolato <guicassolato@gmail.com>
--
=> operator authorino-operator (0.5.0)

operators/project-quay/3.9.0-nightly.2022.12.17/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.17/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.17 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.17)

operators/project-quay/3.9.0-nightly.2022.12.18/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.18/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.18 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.18)

operators/project-quay/3.9.0-nightly.2022.12.19/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.19/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.19 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.19)

operators/netobserv-operator/0.2.2/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/0.2.2/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/0.2.2/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/0.2.2/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/0.2.2/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/0.2.2/metadata/annotations.yaml
=> operator netobserv-operator (0.2.2)

operators/limitador-operator/0.4.0/bundle.Dockerfile, operators/limitador-operator/0.4.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml, operators/limitador-operator/0.4.0/manifests/limitador-operator-manager-config_v1_configmap.yaml, operators/limitador-operator/0.4.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/limitador-operator/0.4.0/manifests/limitador-operator.clusterserviceversion.yaml, operators/limitador-operator/0.4.0/manifests/limitador.kuadrant.io_limitadors.yaml, operators/limitador-operator/0.4.0/metadata/annotations.yaml, operators/limitador-operator/0.4.0/tests/scorecard/config.yaml
* [X ] Example templates for all Custom Resource Definitions intended to be used
=> operator limitador-operator (0.4.0)

operators/group-sync-operator/0.0.21/Dockerfile, operators/group-sync-operator/0.0.21/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.21/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.21/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.21/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.21/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.21/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.21/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.21/metadata/annotations.yaml, operators/group-sync-operator/0.0.21/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.21)

operators/horreum-operator/0.2.0/horreum-operator.v0.2.0.clusterserviceversion.yaml, operators/horreum-operator/0.2.0/hyperfoil.io_horreums_crd.yaml, operators/horreum-operator/ci.yaml, operators/horreum-operator/horreum-operator.package.yaml
=> operator [CI] horreum-operator (0.2.0)

operators/nfs-provisioner-operator/0.0.7/Dockerfile, operators/nfs-provisioner-operator/0.0.7/manifests/cache.jhouse.com_nfsprovisioners.yaml, operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml, operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator.clusterserviceversion.yaml, operators/nfs-provisioner-operator/0.0.7/metadata/annotations.yaml, operators/nfs-provisioner-operator/0.0.7/tests/scorecard/config.yaml
=> operator nfs-provisioner-operator (0.0.7)

operators/project-quay/3.9.0-nightly.2022.12.20/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.20/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.20 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.20)

operators/mongodb-atlas-kubernetes/1.5.1/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.5.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.5.1/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.5.1/tests/scorecard/config.yaml
Signed-off-by: Timur_Akhmadiev <Timur_Akhmadiev@epam.com>
--
=> operator mongodb-atlas-kubernetes (1.5.1)

operators/group-sync-operator/0.0.22/Dockerfile, operators/group-sync-operator/0.0.22/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.22/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.22/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.22/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.22/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.22/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.22/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.22/metadata/annotations.yaml, operators/group-sync-operator/0.0.22/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.22)

operators/dell-csi-operator/1.10.0/csiisilons.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.10.0/csipowermaxes.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.10.0/csipowermaxrevproxies.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.10.0/csipowerstores.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.10.0/csiunities.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.10.0/csivxflexoses.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.10.0/dell-csi-operator.v1.10.0.clusterserviceversion.yaml, operators/dell-csi-operator/dell-csi-operator.package.yaml
=> operator dell-csi-operator (1.10.0)

operators/project-quay/3.9.0-nightly.2022.12.21/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.21/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.21 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.21)

operators/kuadrant-operator/0.2.0/bundle.Dockerfile, operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml, operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml, operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kuadrant-operator/0.2.0/manifests/kuadrant-operator.clusterserviceversion.yaml, operators/kuadrant-operator/0.2.0/manifests/kuadrant.io_authpolicies.yaml, operators/kuadrant-operator/0.2.0/manifests/kuadrant.io_kuadrants.yaml, operators/kuadrant-operator/0.2.0/manifests/kuadrant.io_ratelimitpolicies.yaml, operators/kuadrant-operator/0.2.0/metadata/annotations.yaml, operators/kuadrant-operator/0.2.0/metadata/dependencies.yaml, operators/kuadrant-operator/0.2.0/tests/scorecard/config.yaml, operators/kuadrant-operator/ci.yaml
=> operator [N] [CI] kuadrant-operator (0.2.0)

operators/dell-csm-operator/1.0.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml, operators/dell-csm-operator/1.0.0/manifests/dell-csm-operator.v1.0.0.clusterserviceversion.yaml, operators/dell-csm-operator/1.0.0/metadata/annotations.yaml, operators/dell-csm-operator/1.0.0/tests/scorecard/config.yaml
=> operator dell-csm-operator (1.0.0)

operators/gitlab-runner-operator/1.11.0/manifests/apps.gitlab.com_runners.yaml, operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml, operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml, operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml, operators/gitlab-runner-operator/1.11.0/manifests/gitlab-runner-webhook-service_v1_service.yaml, operators/gitlab-runner-operator/1.11.0/metadata/annotations.yaml, operators/gitlab-runner-operator/1.11.0/tests/scorecard/config.yaml
Signed-off-by: Georgi N. Georgiev <ggeorgiev@gitlab.com>
--
=> operator gitlab-runner-operator (1.11.0)

operators/project-quay/3.9.0-nightly.2022.12.22/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.22/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.22 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.22)

operators/netobserv-operator/0.1.0/metadata/annotations.yaml, operators/netobserv-operator/0.1.1/metadata/annotations.yaml, operators/netobserv-operator/0.1.2/metadata/annotations.yaml, operators/netobserv-operator/0.1.3/metadata/annotations.yaml, operators/netobserv-operator/0.1.4/metadata/annotations.yaml, operators/netobserv-operator/0.2.0/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/0.2.0/metadata/annotations.yaml, operators/netobserv-operator/0.2.1/metadata/annotations.yaml, operators/netobserv-operator/0.2.2/metadata/annotations.yaml
As part of https://issues.redhat.com/browse/NETOBSERV-749 JIRA issue, the Netobserv team would like to remove the
"alpha" channel, which is generating confusion in our customers, and add a "latest" channel which will be independent from the latest version.
So, from now on, the `v0.2.x` and `latest` channel will coexist.
--
<sup>1</sup> If you feel your Operator does not fit any of the …
=> operator [R] netobserv-operator (0.1.0 0.1.1 0.1.2 0.1.3 0.1.4 0.2.0 0.2.1 0.2.2)

operators/group-sync-operator/0.0.23/Dockerfile, operators/group-sync-operator/0.0.23/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.23/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.23/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.23/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.23/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.23/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.23/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.23/metadata/annotations.yaml, operators/group-sync-operator/0.0.23/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.23)

operators/project-quay/3.9.0-nightly.2022.12.23/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.23/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.23 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.23)

operators/external-secrets-operator/0.7.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.7.0/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.7.0/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.7.0/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.7.0/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.7.0/metadata/annotations.yaml, operators/external-secrets-operator/0.7.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.7.0
=> operator external-secrets-operator (0.7.0)

operators/patterns-operator/0.0.8/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.8/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.8/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.8/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.8/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.8/metadata/annotations.yaml, operators/patterns-operator/0.0.8/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.8)

operators/project-quay/3.9.0-nightly.2022.12.24/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.24/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.24 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.24)

operators/project-quay/3.9.0-nightly.2022.12.25/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.25/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.25 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.25)

operators/project-quay/3.9.0-nightly.2022.12.26/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.26/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.26 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.26)

operators/project-quay/3.9.0-nightly.2022.12.27/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.27/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.27 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.27)

operators/edp-keycloak-operator/1.14.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml, operators/edp-keycloak-operator/1.14.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakclients.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealms.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, operators/edp-keycloak-operator/1.14.0/manifests/v1.edp.epam.com_keycloaks.yaml, operators/edp-keycloak-operator/1.14.0/metadata/annotations.yaml, operators/edp-keycloak-operator/1.14.0/tests/scorecard/config.yaml
Signed-off-by: Sergiy Kulanov <sergiy_kulanov@epam.com>
--
=> operator edp-keycloak-operator (1.14.0)

operators/project-quay/3.9.0-nightly.2022.12.29/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.29/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.29 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.29)

operators/project-quay/3.9.0-nightly.2022.12.30/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.30/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.30 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.30)

operators/project-quay/3.9.0-nightly.2022.12.31/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.2022.12.31/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.2022.12.31 to community operators
=> operator project-quay (3.9.0-nightly.2022.12.31)

operators/annotationlab/4.5.0/bundle.Dockerfile, operators/annotationlab/4.5.0/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.5.0/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.5.0/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.5.0/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.5.0/metadata/annotations.yaml, operators/annotationlab/4.5.0/tests/scorecard/config.yaml
=> operator annotationlab (4.5.0)

operators/annotationlab/4.5.1/bundle.Dockerfile, operators/annotationlab/4.5.1/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.5.1/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.5.1/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.5.1/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.5.1/metadata/annotations.yaml, operators/annotationlab/4.5.1/tests/scorecard/config.yaml
=> operator annotationlab (4.5.1)

operators/annotationlab/ci.yaml
=> operator [CI] annotationlab

operators/annotationlab/4.5.1/manifests/annotationlab.clusterserviceversion.yaml
=> operator [O] annotationlab (4.5.1)

operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.5/manifests/pulp-operator.1.0.0-alpha.5.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-alpha.5/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-alpha.5/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-alpha.5/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-alpha.5/metadata/annotations.yaml, operators/pulp-operator/1.0.0-alpha.5/tests/scorecard/config.yaml
=> operator pulp-operator (1.0.0-alpha.5)

operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.0.4/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.0.4/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.0.4/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.0.4/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.0.4/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.0.4/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.0.4/metadata/annotations.yaml, operators/cluster-aas-operator/0.0.4/metadata/dependencies.yaml, operators/cluster-aas-operator/0.0.4/tests/scorecard/config.yaml
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--
=> operator cluster-aas-operator (0.0.4)

operators/external-secrets-operator/0.7.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.7.1/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.7.1/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.7.1/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.7.1/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.7.1/metadata/annotations.yaml, operators/external-secrets-operator/0.7.1/tests/scorecard/config.yaml
bump external-secrets-operator 0.7.1
=> operator external-secrets-operator (0.7.1)

operators/nfs-provisioner-operator/0.0.7/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
=> operator [O] nfs-provisioner-operator (0.0.7)

operators/ack-kafka-controller/ci.yaml
=> operator [CI] ack-kafka-controller

operators/ack-eventbridge-controller/ci.yaml
=> operator [CI] ack-eventbridge-controller

operators/rabbitmq-cluster-operator/2.1.0/bundle.Dockerfile, operators/rabbitmq-cluster-operator/2.1.0/manifests/crds.yaml, operators/rabbitmq-cluster-operator/2.1.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-cluster-operator/2.1.0/metadata/annotations.yaml
Signed-off-by: DanielePalaia <dpalaia@vmware.com>
--
=> operator rabbitmq-cluster-operator (2.1.0)

operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.67.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.67.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.67.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.67.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.67.0/tests/scorecard/config.yaml
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
--
=> operator opentelemetry-operator (0.67.0)

operators/percona-server-mongodb-operator/1.13.1/manifests/percona-server-mongodb-operator.v1.13.0.clusterserviceversion.yaml, operators/percona-server-mongodb-operator/1.13.1/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.13.1/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.13.1/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.13.1/metadata/annotations.yaml
Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>
--
=> operator percona-server-mongodb-operator (1.13.1)

operators/awx-operator/1.1.3/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/1.1.3/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/1.1.3/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/1.1.3/manifests/awx-operator.v1.1.3.clusterserviceversion.yaml, operators/awx-operator/1.1.3/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/1.1.3/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/1.1.3/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/1.1.3/metadata/annotations.yaml, operators/awx-operator/1.1.3/tests/scorecard/config.yaml
Signed-off-by: Christian M. Adams <chadams@redhat.com>
--
=> operator awx-operator (1.1.3)

operators/patterns-operator/0.0.9/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.9/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.9/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.9/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.9/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.9/metadata/annotations.yaml, operators/patterns-operator/0.0.9/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.9)

operators/dynatrace-operator/0.10.2/Dockerfile, operators/dynatrace-operator/0.10.2/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.10.2/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.10.2/metadata/annotations.yaml
=> operator dynatrace-operator (0.10.2)

operators/datadog-operator/0.8.4/manifests/datadog-operator.clusterserviceversion.yaml, operators/datadog-operator/0.8.4/manifests/datadoghq.com_datadogagents.yaml, operators/datadog-operator/0.8.4/manifests/datadoghq.com_datadogmetrics.yaml, operators/datadog-operator/0.8.4/manifests/datadoghq.com_datadogmonitors.yaml, operators/datadog-operator/0.8.4/metadata/annotations.yaml, operators/datadog-operator/0.8.4/tests/scorecard/config.yaml
Signed-off-by: khewonc <39867936+khewonc@users.noreply.github.com>
--
=> operator datadog-operator (0.8.4)

operators/gitlab-operator-kubernetes/0.15.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.15.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.15.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.15.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.15.2)

operators/gitlab-operator-kubernetes/0.15.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.15.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.15.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.15.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.15.1)

operators/loki-operator/0.1.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml, operators/loki-operator/0.1.0/manifests/loki-operator-manager-config_v1_configmap.yaml, operators/loki-operator/0.1.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/loki-operator/0.1.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/loki-operator/0.1.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/loki-operator/0.1.0/manifests/loki-operator-webhook-service_v1_service.yaml, operators/loki-operator/0.1.0/manifests/loki-operator.clusterserviceversion.yaml, operators/loki-operator/0.1.0/manifests/loki.grafana.com_alertingrules.yaml, operators/loki-operator/0.1.0/manifests/loki.grafana.com_lokistacks.yaml, operators/loki-operator/0.1.0/manifests/loki.grafana.com_recordingrules.yaml, operators/loki-operator/0.1.0/manifests/loki.grafana.com_rulerconfigs.yaml, operators/loki-operator/0.1.0/metadata/annotations.yaml, operators/loki-operator/0.1.0/tests/scorecard/config.yaml, operators/loki-operator/ci.yaml
Signed-off-by: Periklis Tsirakidis <periklis@redhat.com>
--
=> operator [N] [CI] loki-operator (0.1.0)

operators/neuvector-community-operator/1.3.7/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.7/neuvector-operator.v1.3.7.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operator neuvector-community-operator (1.3.7)

operators/aerospike-kubernetes-operator/2.4.0/bundle.Dockerfile, operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml, operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml, operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.4.0/manifests/aerospike-operator-webhook-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.4.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml, operators/aerospike-kubernetes-operator/2.4.0/metadata/annotations.yaml, operators/aerospike-kubernetes-operator/2.4.0/tests/scorecard/config.yaml, operators/aerospike-kubernetes-operator/ci.yaml
Signed-off-by: Sudhanshu Ranjan <sudhanshu@aerospike.com>
--
=> operator [CI] aerospike-kubernetes-operator (2.4.0)

operators/group-sync-operator/0.0.24/Dockerfile, operators/group-sync-operator/0.0.24/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.24/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.24/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.24/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.24/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.24/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.24/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.24/metadata/annotations.yaml, operators/group-sync-operator/0.0.24/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.24)

operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml, operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator-webhook-service_v1_service.yaml, operators/node-maintenance-operator/0.14.0/manifests/node-maintenance-operator.clusterserviceversion.yaml, operators/node-maintenance-operator/0.14.0/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml, operators/node-maintenance-operator/0.14.0/metadata/annotations.yaml, operators/node-maintenance-operator/0.14.0/tests/scorecard/config.yaml
Signed-off-by: razo7 <oraz@redhat.com>
--
=> operator node-maintenance-operator (0.14.0)

operators/ndmspc-operator/0.1.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.1.3/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.1.3/metadata/annotations.yaml, operators/ndmspc-operator/0.1.3/tests/scorecard/config.yaml, operators/ndmspc-operator/ci.yaml
=> operator [N] [CI] ndmspc-operator (0.1.3)

operators/koku-metrics-operator/1.2.0/Dockerfile, operators/koku-metrics-operator/1.2.0/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.2.0/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.2.0/metadata/annotations.yaml, operators/koku-metrics-operator/1.2.0/tests/scorecard/config.yaml
=> operator koku-metrics-operator (1.2.0)

operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml, operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml, operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kuadrant-operator/0.2.1/manifests/kuadrant-operator.clusterserviceversion.yaml, operators/kuadrant-operator/0.2.1/manifests/kuadrant.io_authpolicies.yaml, operators/kuadrant-operator/0.2.1/manifests/kuadrant.io_kuadrants.yaml, operators/kuadrant-operator/0.2.1/manifests/kuadrant.io_ratelimitpolicies.yaml, operators/kuadrant-operator/0.2.1/metadata/annotations.yaml, operators/kuadrant-operator/0.2.1/metadata/dependencies.yaml, operators/kuadrant-operator/0.2.1/tests/scorecard/config.yaml
=> operator kuadrant-operator (0.2.1)

operators/yaks/0.12.2/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.12.2/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.12.2/yaks.v0.12.2.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operator yaks (0.12.2)

operators/kubernetes-imagepuller-operator/1.0.4/che.eclipse.org_kubernetesimagepullers_crd.yaml, operators/kubernetes-imagepuller-operator/1.0.4/controller-manager-metrics-service_v1_service.yaml, operators/kubernetes-imagepuller-operator/1.0.4/kubernetes-imagepuller-operator.v1.0.4.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/1.0.4/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
--
=> operator kubernetes-imagepuller-operator (1.0.4)

operators/aqua/6.5.9/bundle.Dockerfile, operators/aqua/6.5.9/manifests/aqua-operator.v6.5.9.clusterserviceversion.yaml, operators/aqua/6.5.9/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/6.5.9/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/6.5.9/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.9/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/6.5.9/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.9/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/6.5.9/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.9/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.9/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.9/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.9/metadata/annotations.yaml
Signed-off-by: Baruch Bilanski <baruch.bilanski@aquasec.com>
--
=> operator aqua (6.5.9)

operators/gitlab-operator-kubernetes/0.11.4/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.11.4/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.11.4/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.11.4/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.11.4)

operators/ndmspc-operator/0.2.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.0/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.0/metadata/annotations.yaml, operators/ndmspc-operator/0.2.0/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.0)

operators/rhoas-operator/0.12.0/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.12.0/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.12.0/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.12.0/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.12.0/manifests/rhoas-operator.serviceregistryconnections.crd.yaml, operators/rhoas-operator/0.12.0/manifests/service-binding.clusterrole.yaml, operators/rhoas-operator/0.12.0/metadata/annotations.yaml
Signed-off-by: Andrea Peruffo <andrea.peruffo1982@gmail.com>
--
=> operator rhoas-operator (0.12.0)

operators/gitlab-operator-kubernetes/0.11.3/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.11.3/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.11.3/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.11.3/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.11.3)

operators/rhoas-operator/0.13.0/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.13.0/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.13.0/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.13.0/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.13.0/manifests/rhoas-operator.serviceregistryconnections.crd.yaml, operators/rhoas-operator/0.13.0/manifests/service-binding.clusterrole.yaml, operators/rhoas-operator/0.13.0/metadata/annotations.yaml
Signed-off-by: Andrea Peruffo <andrea.peruffo1982@gmail.com>
--
=> operator rhoas-operator (0.13.0)

operators/self-node-remediation/0.5.0/manifests/self-node-remediation.clusterserviceversion.yaml, operators/self-node-remediation/0.5.0/metadata/annotations.yaml
=> operator [O] self-node-remediation (0.5.0)

operators/ndmspc-operator/0.2.1/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.1/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.1/metadata/annotations.yaml, operators/ndmspc-operator/0.2.1/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.1)

operators/ack-acm-controller/ci.yaml
=> operator [CI] ack-acm-controller

operators/ndmspc-operator/0.2.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.2/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.2/metadata/annotations.yaml, operators/ndmspc-operator/0.2.2/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.2)

operators/mongodb-atlas-kubernetes/1.6.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.6.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.6.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.6.0/tests/scorecard/config.yaml
Signed-off-by: Igor Karpukhin <karpukhinigor@gmail.com>
--
=> operator mongodb-atlas-kubernetes (1.6.0)

operators/community-windows-machine-config-operator/7.0.0/manifests/community-windows-machine-config-operator.7.0.0.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/windows-instance-config-daemon_v1_serviceaccount.yaml, operators/community-windows-machine-config-operator/7.0.0/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/7.0.0/metadata/annotations.yaml
Signed-off-by: Alina Ryan <aliryan@redhat.com>
--
=> operator community-windows-machine-config-operator (7.0.0)

operators/project-quay/3.8.1/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.1/quayecosystems.crd.yaml, operators/project-quay/3.8.1/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.1 to community operators
=> operator project-quay (3.8.1)

operators/opendatahub-operator/1.4.1/manifests/kfdef.apps.kubeflow.org.crd.yaml, operators/opendatahub-operator/1.4.1/manifests/odhapplications.dashboard.opendatahub.io.crd.yaml, operators/opendatahub-operator/1.4.1/manifests/odhdashboardconfigs.opendatahub.io.crd.yaml, operators/opendatahub-operator/1.4.1/manifests/odhdocuments.dashboard.opendatahub.io.crd.yaml, operators/opendatahub-operator/1.4.1/manifests/odhquickstarts.console.openshift.io.crd.yaml, operators/opendatahub-operator/1.4.1/manifests/opendatahub-operator.v1.4.1.clusterserviceversion.yaml, operators/opendatahub-operator/1.4.1/metadata/annotations.yaml
=> operator opendatahub-operator (1.4.1)

operators/kubecost/1.99.0/bundle.Dockerfile, operators/kubecost/1.99.0/manifests/charts.kubecost.com_costanalyzers.yaml, operators/kubecost/1.99.0/manifests/kubecost-controller-manager-metrics-service_v1_service.yaml, operators/kubecost/1.99.0/manifests/kubecost-manager-config_v1_configmap.yaml, operators/kubecost/1.99.0/manifests/kubecost-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubecost/1.99.0/manifests/kubecost.clusterserviceversion.yaml, operators/kubecost/1.99.0/metadata/annotations.yaml, operators/kubecost/1.99.0/tests/scorecard/config.yaml
Signed-off-by: Linh Lam <linh@kubecost.com>
Update Kubecost operator to v1.99.0
--
=> operator kubecost (1.99.0)

operators/portworx-essentials/1.10.2/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.10.2/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.10.2/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/ci.yaml, operators/portworx-essentials/portworx.package.yaml
=> operator [CI] portworx-essentials (1.10.2)

operators/awx-operator/1.1.4/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/1.1.4/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/1.1.4/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/1.1.4/manifests/awx-operator.v1.1.4.clusterserviceversion.yaml, operators/awx-operator/1.1.4/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/1.1.4/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/1.1.4/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/1.1.4/metadata/annotations.yaml, operators/awx-operator/1.1.4/tests/scorecard/config.yaml
Signed-off-by: Christian M. Adams <chadams@redhat.com>
--
=> operator awx-operator (1.1.4)

operators/netobserv-operator/1.0.1/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/1.0.1/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/1.0.1/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/1.0.1/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/1.0.1/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/1.0.1/metadata/annotations.yaml
=> operator netobserv-operator (1.0.1)

operators/patterns-operator/0.0.10/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.10/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.10/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.10/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.10/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.10/metadata/annotations.yaml, operators/patterns-operator/0.0.10/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.10)

operators/ndmspc-operator/0.2.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.3/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.3/metadata/annotations.yaml, operators/ndmspc-operator/0.2.3/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.3)

operators/flux/0.38.3/manifests/alert.crd.yaml, operators/flux/0.38.3/manifests/bucket.crd.yaml, operators/flux/0.38.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.38.3/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.38.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.38.3/manifests/flux.v0.38.3.clusterserviceversion.yaml, operators/flux/0.38.3/manifests/gitrepository.crd.yaml, operators/flux/0.38.3/manifests/helmchart.crd.yaml, operators/flux/0.38.3/manifests/helmrelease.crd.yaml, operators/flux/0.38.3/manifests/helmrepository.crd.yaml, operators/flux/0.38.3/manifests/imagepolicy.crd.yaml, operators/flux/0.38.3/manifests/imagerepository.crd.yaml, operators/flux/0.38.3/manifests/imageupdateautomation.crd.yaml, operators/flux/0.38.3/manifests/kustomization.crd.yaml, operators/flux/0.38.3/manifests/notification-controller.service.yaml, operators/flux/0.38.3/manifests/ocirepository.crd.yaml, operators/flux/0.38.3/manifests/provider.crd.yaml, operators/flux/0.38.3/manifests/receiver.crd.yaml, operators/flux/0.38.3/manifests/source-controller.service.yaml, operators/flux/0.38.3/manifests/webhook-receiver.service.yaml, operators/flux/0.38.3/metadata/annotations.yaml
* [x} Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
=> operator flux (0.38.3)

operators/portworx-essentials/1.10.3/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.10.3/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.10.3/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operator portworx-essentials (1.10.3)

operators/mariadb-operator/0.6.4/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.6.4/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.6.4/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.6.4/metadata/annotations.yaml, operators/mariadb-operator/0.6.4/tests/scorecard/config.yaml, operators/mariadb-operator/ci.yaml
Signed-off-by: Martin Montes <martin11lrx@gmail.com>
--
=> operator [N] [CI] mariadb-operator (0.6.4)

operators/mongodb-atlas-kubernetes/1.6.1/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.6.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.6.1/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.6.1/tests/scorecard/config.yaml
Signed-off-by: fabritsius <antonfabritsius@gmail.com>
--
=> operator mongodb-atlas-kubernetes (1.6.1)

operators/camel-k/1.10.4/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.10.4/manifests/camel-k.v1.10.4.clusterserviceversion.yaml, operators/camel-k/1.10.4/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.10.4/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.10.4/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.10.4/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.10.4/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.10.4/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.10.4/metadata/annotations.yaml, operators/camel-k/1.10.4/tests/scorecard/config.yaml
=> operator [R] camel-k (1.10.4 1.11.0)

operators/gitlab-operator-kubernetes/ci.yaml
=> operator [CI] gitlab-operator-kubernetes

operators/opendatahub-operator/1.4.1/manifests/odhdashboardconfigs.opendatahub.io.crd.yaml, operators/opendatahub-operator/1.4.1/manifests/opendatahub-operator.v1.4.1.clusterserviceversion.yaml
Update CSV description in ODH 1.4.1 release
--
=> operator [O] opendatahub-operator (1.4.1)

operators/camel-k/1.11.1/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.11.1/manifests/camel-k.v1.11.1.clusterserviceversion.yaml, operators/camel-k/1.11.1/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.11.1/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.11.1/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.11.1/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.11.1/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.11.1/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.11.1/metadata/annotations.yaml, operators/camel-k/1.11.1/tests/scorecard/config.yaml
=> operator camel-k (1.11.1)

operators/seldon-operator/ci.yaml
=> operator [CI] seldon-operator

operators/multi-nic-cni-operator/1.0.3/bundle.Dockerfile, operators/multi-nic-cni-operator/1.0.3/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multi-nic-cni-operator.clusterserviceversion.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multinic.fms.io_cidrs.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multinic.fms.io_configs.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multinic.fms.io_deviceclasses.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multinic.fms.io_hostinterfaces.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multinic.fms.io_ippools.yaml, operators/multi-nic-cni-operator/1.0.3/manifests/multinic.fms.io_multinicnetworks.yaml, operators/multi-nic-cni-operator/1.0.3/metadata/annotations.yaml, operators/multi-nic-cni-operator/1.0.3/tests/scorecard/config.yaml
Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
--
=> operator multi-nic-cni-operator (1.0.3)

operators/project-quay/3.9.0-nightly.20230202/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230202/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230202 to community operators
=> operator project-quay (3.9.0-nightly.20230202)

operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.68.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.68.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.68.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.68.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.68.0/tests/scorecard/config.yaml
Signed-off-by: Israel Blancas <iblancasa@gmail.com>
Based on https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.68.0
https://github.com/open-telemetry/opentelemetry-operator/issues/1390
=> operator opentelemetry-operator (0.68.0)

operators/tackle-operator/2.1.3/manifests/tackle-operator.clusterserviceversion.yaml, operators/tackle-operator/2.1.3/manifests/tackle.konveyor.io_addons.yaml, operators/tackle-operator/2.1.3/manifests/tackle.konveyor.io_tackles.yaml, operators/tackle-operator/2.1.3/metadata/annotations.yaml
=> operator tackle-operator (2.1.3)

operators/project-quay/3.9.0-nightly.20230203/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230203/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230203 to community operators
=> operator project-quay (3.9.0-nightly.20230203)

operators/yaks/0.13.0/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.13.0/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.13.0/yaks.v0.13.0.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operator yaks (0.13.0)

operators/project-quay/3.9.0-nightly.20230205/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230205/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230205 to community operators
=> operator project-quay (3.9.0-nightly.20230205)

operators/mariadb-operator/0.6.5/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.6.5/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.6.5/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.6.5/metadata/annotations.yaml, operators/mariadb-operator/0.6.5/tests/scorecard/config.yaml
Add operator mariadb-operator (0.6.5) to community operators
=> operator mariadb-operator (0.6.5)

operators/project-quay/3.9.0-nightly.20230206/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230206/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230206 to community operators
=> operator project-quay (3.9.0-nightly.20230206)

operators/mariadb-operator/0.6.6/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.6.6/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.6.6/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.6.6/metadata/annotations.yaml, operators/mariadb-operator/0.6.6/tests/scorecard/config.yaml
Add operator mariadb-operator (0.6.6) to community operators
=> operator mariadb-operator (0.6.6)

operators/flux/0.39.0/manifests/alert.crd.yaml, operators/flux/0.39.0/manifests/bucket.crd.yaml, operators/flux/0.39.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.39.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.39.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.39.0/manifests/flux.v0.39.0.clusterserviceversion.yaml, operators/flux/0.39.0/manifests/gitrepository.crd.yaml, operators/flux/0.39.0/manifests/helmchart.crd.yaml, operators/flux/0.39.0/manifests/helmrelease.crd.yaml, operators/flux/0.39.0/manifests/helmrepository.crd.yaml, operators/flux/0.39.0/manifests/imagepolicy.crd.yaml, operators/flux/0.39.0/manifests/imagerepository.crd.yaml, operators/flux/0.39.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.39.0/manifests/kustomization.crd.yaml, operators/flux/0.39.0/manifests/notification-controller.service.yaml, operators/flux/0.39.0/manifests/ocirepository.crd.yaml, operators/flux/0.39.0/manifests/provider.crd.yaml, operators/flux/0.39.0/manifests/receiver.crd.yaml, operators/flux/0.39.0/manifests/source-controller.service.yaml, operators/flux/0.39.0/manifests/webhook-receiver.service.yaml, operators/flux/0.39.0/metadata/annotations.yaml
=> operator flux (0.39.0)

operators/project-quay/3.9.0-nightly.20230207/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230207/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230207 to community operators
=> operator project-quay (3.9.0-nightly.20230207)

operators/project-quay/3.9.0-nightly.20230208/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230208/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230208 to community operators
=> operator project-quay (3.9.0-nightly.20230208)

operators/rabbitmq-messaging-topology-operator/1.10.1/bundle.Dockerfile, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_bindings.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_exchanges.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_federations.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_permissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_policies.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_queues.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_schemareplications.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_shovels.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_superstreams.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_topicpermissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_users.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.com_vhosts.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-messaging-topology-operator/1.10.1/metadata/annotations.yaml
Signed-off-by: DanielePalaia <dpalaia@vmware.com>
* [X ] Links to the maintainer, source code and documentation
--
=> operator rabbitmq-messaging-topology-operator (1.10.1)

operators/project-quay/3.9.0-nightly.20230209/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230209/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230209 to community operators
=> operator project-quay (3.9.0-nightly.20230209)

operators/patterns-operator/0.0.11/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.11/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.11/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.11/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.11/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.11/metadata/annotations.yaml, operators/patterns-operator/0.0.11/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.11)

operators/ndmspc-operator/0.2.5/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.5/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.5/metadata/annotations.yaml, operators/ndmspc-operator/0.2.5/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.5)

operators/ack-route53-controller/ci.yaml
=> operator [CI] ack-route53-controller

operators/project-quay/3.9.0-nightly.20230210/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230210/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230210 to community operators
=> operator project-quay (3.9.0-nightly.20230210)

operators/mariadb-operator/0.6.7/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.6.7/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.6.7/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.6.7/metadata/annotations.yaml, operators/mariadb-operator/0.6.7/tests/scorecard/config.yaml
Add operator mariadb-operator (0.6.7) to community operators
=> operator mariadb-operator (0.6.7)

operators/project-quay/3.9.0-nightly.20230211/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230211/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230211 to community operators
=> operator project-quay (3.9.0-nightly.20230211)

operators/grafana-operator/4.9.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.9.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.9.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.9.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.9.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.9.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.9.0/integreatly.org_grafanafolders.yaml, operators/grafana-operator/4.9.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.9.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.9.0)

operators/project-quay/3.9.0-nightly.20230213/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230213/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230213 to community operators
=> operator project-quay (3.9.0-nightly.20230213)

operators/yaks/0.14.1/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.14.1/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.14.1/yaks.v0.14.1.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operator yaks (0.14.1)

operators/ack-ssm-controller/ci.yaml
=> operator [CI] ack-ssm-controller

operators/hive-operator/ci.yaml
Adding jstuever and lleshchi to hive-operator ci.yaml.
=> operator [CI] hive-operator

operators/project-quay/3.9.0-nightly.20230215/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230215/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230215 to community operators
=> operator project-quay (3.9.0-nightly.20230215)

operators/opentelemetry-operator/0.69.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.69.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.69.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.69.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.69.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.69.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.69.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.69.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.69.0)

operators/gitlab-runner-operator/1.12.0/manifests/apps.gitlab.com_runners.yaml, operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml, operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml, operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml, operators/gitlab-runner-operator/1.12.0/manifests/gitlab-runner-webhook-service_v1_service.yaml, operators/gitlab-runner-operator/1.12.0/metadata/annotations.yaml, operators/gitlab-runner-operator/1.12.0/tests/scorecard/config.yaml
Signed-off-by: Georgi N. Georgiev ggeorgiev@gitlab.com
--
=> operator gitlab-runner-operator (1.12.0)

operators/project-quay/3.9.0-nightly.20230216/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230216/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230216 to community operators
=> operator project-quay (3.9.0-nightly.20230216)

operators/github-arc-operator/1.0.4/bundle.Dockerfile, operators/github-arc-operator/1.0.4/manifests/github-arc-operator-controller-manager-metrics-service_v1_service.yaml, operators/github-arc-operator/1.0.4/manifests/github-arc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/github-arc-operator/1.0.4/manifests/github-arc-operator.clusterserviceversion.yaml, operators/github-arc-operator/1.0.4/manifests/github-practice.boxboat.com_actionsrunnercontrollers.yaml, operators/github-arc-operator/1.0.4/metadata/annotations.yaml, operators/github-arc-operator/1.0.4/tests/scorecard/config.yaml
Signed-off-by: mbmcmullen27 <mbmcmullen27@gmail.com>
--
=> operator [N] github-arc-operator (1.0.4)

operators/awx-operator/ci.yaml
=> operator [CI] awx-operator

operators/project-quay/3.9.0-nightly.20230217/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230217/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230217 to community operators
=> operator project-quay (3.9.0-nightly.20230217)

operators/cass-operator-community/1.14.0/manifests/cass-operator-manager-config_v1_configmap.yaml, operators/cass-operator-community/1.14.0/manifests/cass-operator-webhook-service_v1_service.yaml, operators/cass-operator-community/1.14.0/manifests/cass-operator.clusterserviceversion.yaml, operators/cass-operator-community/1.14.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml, operators/cass-operator-community/1.14.0/manifests/control.k8ssandra.io_cassandratasks.yaml, operators/cass-operator-community/1.14.0/metadata/annotations.yaml, operators/cass-operator-community/1.14.0/tests/scorecard/config.yaml
=> operator cass-operator-community (1.14.0)

operators/awx-operator/1.2.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/1.2.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/1.2.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/1.2.0/manifests/awx-operator.v1.2.0.clusterserviceversion.yaml, operators/awx-operator/1.2.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/1.2.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/1.2.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/1.2.0/metadata/annotations.yaml, operators/awx-operator/1.2.0/tests/scorecard/config.yaml
=> operator awx-operator (1.2.0)

operators/neuvector-community-operator/1.3.8/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.8/neuvector-operator.v1.3.8.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operator neuvector-community-operator (1.3.8)

operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.70.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.70.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.70.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.70.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.70.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.70.0)

operators/kube-green/0.5.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.5.0/manifests/kube-green-manager-config_v1_configmap.yaml, operators/kube-green/0.5.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.5.0/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.5.0/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.5.0/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.5.0/metadata/annotations.yaml, operators/kube-green/0.5.0/tests/scorecard/config.yaml
=> operator kube-green (0.5.0)

operators/cluster-manager/0.10.0/cluster-manager.clusterserviceversion.yaml, operators/cluster-manager/0.10.0/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/cluster-manger.package.yaml
=> operator cluster-manager (0.10.0)

operators/klusterlet/0.10.0/klusterlet.clusterserviceversion.yaml, operators/klusterlet/0.10.0/operator.open-cluster-management.io_klusterlets.yaml, operators/klusterlet/klusterlet.package.yaml
=> operator klusterlet (0.10.0)

operators/project-quay/3.9.0-nightly.20230220/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230220/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230220 to community operators
=> operator project-quay (3.9.0-nightly.20230220)

operators/kiali/1.64.0/bundle.Dockerfile, operators/kiali/1.64.0/manifests/kiali.crd.yaml, operators/kiali/1.64.0/manifests/kiali.v1.64.0.clusterserviceversion.yaml, operators/kiali/1.64.0/metadata/annotations.yaml
=> operator kiali (1.64.0)

operators/project-quay/3.9.0-nightly.20230221/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230221/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230221 to community operators
=> operator project-quay (3.9.0-nightly.20230221)

operators/netobserv-operator/1.0.2/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/1.0.2/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/1.0.2/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/1.0.2/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/1.0.2/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/1.0.2/manifests/netobserv-webhook-service_v1_service.yaml, operators/netobserv-operator/1.0.2/metadata/annotations.yaml
=> operator netobserv-operator (1.0.2)

operators/project-quay/3.8.2/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.2/quayecosystems.crd.yaml, operators/project-quay/3.8.2/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.2 to community operators
=> operator project-quay (3.8.2)

operators/mariadb-operator/0.7.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.7.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.7.0/metadata/annotations.yaml, operators/mariadb-operator/0.7.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.7.0) to community operators
=> operator mariadb-operator (0.7.0)

operators/project-quay/3.7.11/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.11/quayecosystems.crd.yaml, operators/project-quay/3.7.11/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.7.11 to community operators
=> operator project-quay (3.7.11)

operators/ndmspc-operator/0.2.6/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.6/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.6/metadata/annotations.yaml, operators/ndmspc-operator/0.2.6/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.6)

operators/portworx-essentials/1.10.4/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.10.4/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.10.4/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operator portworx-essentials (1.10.4)

operators/project-quay/3.9.0-nightly.20230223/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230223/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230223 to community operators
=> operator project-quay (3.9.0-nightly.20230223)

operators/project-quay/3.9.0-nightly.20230224/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230224/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230224 to community operators
=> operator project-quay (3.9.0-nightly.20230224)

operators/multicluster-global-hub-operator/0.7.0-dev/multicluster-global-hub-operator.clusterserviceversion.yaml, operators/multicluster-global-hub-operator/0.7.0-dev/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
=> operator [O] multicluster-global-hub-operator (0.7.0-dev)

operators/mariadb-operator/0.7.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.7.1/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.7.1/metadata/annotations.yaml, operators/mariadb-operator/0.7.1/tests/scorecard/config.yaml
Add operator mariadb-operator (0.7.1) to community operators
=> operator mariadb-operator (0.7.1)

operators/project-quay/3.9.0-nightly.20230226/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230226/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230226 to community operators
=> operator project-quay (3.9.0-nightly.20230226)

operators/mariadb-operator/0.8.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.8.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.8.0/metadata/annotations.yaml, operators/mariadb-operator/0.8.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.8.0) to community operators
=> operator mariadb-operator (0.8.0)

operators/camel-k/1.12.0/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.12.0/manifests/camel-k.v1.12.0.clusterserviceversion.yaml, operators/camel-k/1.12.0/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.12.0/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.12.0/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.12.0/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.12.0/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.12.0/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.12.0/metadata/annotations.yaml, operators/camel-k/1.12.0/tests/scorecard/config.yaml
=> operator camel-k (1.12.0)

operators/windup-operator/0.0.12/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.12/manifests/windup.crd.yaml, operators/windup-operator/0.0.12/metadata/annotations.yaml
=> operator windup-operator (0.0.12)

operators/yaks/0.14.2/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.14.2/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.14.2/yaks.v0.14.2.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operator yaks (0.14.2)

operators/pelorus-operator/0.0.3/manifests/charts.pelorus.konveyor.io_pelorus.yaml, operators/pelorus-operator/0.0.3/manifests/pelorus-operator-controller-manager-metrics-service_v1_service.yaml, operators/pelorus-operator/0.0.3/manifests/pelorus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pelorus-operator/0.0.3/manifests/pelorus-operator.clusterserviceversion.yaml, operators/pelorus-operator/0.0.3/metadata/annotations.yaml, operators/pelorus-operator/0.0.3/metadata/properties.yaml, operators/pelorus-operator/0.0.3/tests/scorecard/config.yaml
=> operator pelorus-operator (0.0.3)

operators/project-quay/3.8.3/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.3/quayecosystems.crd.yaml, operators/project-quay/3.8.3/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.3 to community operators
=> operator project-quay (3.8.3)

operators/project-quay/3.9.0-nightly.20230302/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230302/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230302 to community operators
=> operator project-quay (3.9.0-nightly.20230302)

operators/verticadb-operator/1.10.0/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.10.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.10.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.10.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/verticadb-operator/1.10.0/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.10.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.10.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.10.0/metadata/annotations.yaml, operators/verticadb-operator/1.10.0/tests/scorecard/config.yaml
=> operator verticadb-operator (1.10.0)

operators/project-quay/3.9.0-nightly.20230303/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230303/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230303 to community operators
=> operator project-quay (3.9.0-nightly.20230303)

operators/ndmspc-operator/0.2.7/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.7/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.7/metadata/annotations.yaml, operators/ndmspc-operator/0.2.7/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.7)

operators/mariadb-operator/0.9.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.9.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.9.0/metadata/annotations.yaml, operators/mariadb-operator/0.9.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.9.0) to community operators
=> operator mariadb-operator (0.9.0)

operators/project-quay/3.9.0-nightly.20230305/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230305/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230305 to community operators
=> operator project-quay (3.9.0-nightly.20230305)

operators/aqua/2022.4.9/bundle.Dockerfile, operators/aqua/2022.4.9/manifests/aqua-operator.v2022.4.9.clusterserviceversion.yaml, operators/aqua/2022.4.9/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.9/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.9/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.9/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.9/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.9/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.9/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.9/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.9/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.9/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.9/metadata/annotations.yaml
=> operator aqua (2022.4.9)

operators/github-arc-operator/1.1.0/bundle.Dockerfile, operators/github-arc-operator/1.1.0/manifests/github-arc-operator-controller-manager-metrics-service_v1_service.yaml, operators/github-arc-operator/1.1.0/manifests/github-arc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/github-arc-operator/1.1.0/manifests/github-arc-operator.clusterserviceversion.yaml, operators/github-arc-operator/1.1.0/manifests/github-practice.boxboat.com_actionsrunnercontrollers.yaml, operators/github-arc-operator/1.1.0/metadata/annotations.yaml, operators/github-arc-operator/1.1.0/tests/scorecard/config.yaml
=> operator github-arc-operator (1.1.0)

operators/aqua/6.5.10/bundle.Dockerfile, operators/aqua/6.5.10/manifests/aqua-operator.v6.5.10.clusterserviceversion.yaml, operators/aqua/6.5.10/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/6.5.10/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/6.5.10/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.10/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/6.5.10/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.10/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/6.5.10/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.10/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.10/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.10/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.10/metadata/annotations.yaml
=> operator aqua (6.5.10)

operators/awx-operator/1.3.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/1.3.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/1.3.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/1.3.0/manifests/awx-operator.v1.3.0.clusterserviceversion.yaml, operators/awx-operator/1.3.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/1.3.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/1.3.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/1.3.0/metadata/annotations.yaml, operators/awx-operator/1.3.0/tests/scorecard/config.yaml
=> operator awx-operator (1.3.0)

operators/project-quay/3.9.0-nightly.20230307/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230307/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230307 to community operators
=> operator project-quay (3.9.0-nightly.20230307)

operators/portworx-essentials/1.10.5/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.10.5/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.10.5/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operator portworx-essentials (1.10.5)

operators/project-quay/3.9.0-nightly.20230308/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230308/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230308 to community operators
=> operator project-quay (3.9.0-nightly.20230308)

operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.71.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.71.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.71.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.71.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.71.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.71.0)

operators/project-quay/3.9.0-nightly.20230309/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230309/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230309 to community operators
=> operator project-quay (3.9.0-nightly.20230309)

operators/microcks/1.7.0/microcks-operator.v1.7.0.clusterserviceversion.yaml, operators/microcks/1.7.0/microcksinstall.crd.yaml, operators/microcks/microcks.package.yaml
=> operator microcks (1.7.0)

operators/project-quay/3.9.0-nightly.20230310/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230310/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230310 to community operators
=> operator project-quay (3.9.0-nightly.20230310)

operators/codeflare-operator/0.0.1/manifests/codeflare-operator-controller-manager-metrics-service_v1_service.yaml, operators/codeflare-operator/0.0.1/manifests/codeflare-operator-manager-config_v1_configmap.yaml, operators/codeflare-operator/0.0.1/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/0.0.1/manifests/codeflare-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/codeflare-operator/0.0.1/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/0.0.1/manifests/codeflare.codeflare.dev_instascales.yaml, operators/codeflare-operator/0.0.1/manifests/codeflare.codeflare.dev_mcads.yaml, operators/codeflare-operator/0.0.1/manifests/mcad.ibm.com_appwrappers.yaml, operators/codeflare-operator/0.0.1/manifests/mcad.ibm.com_queuejobs.yaml, operators/codeflare-operator/0.0.1/manifests/mcad.ibm.com_schedulingspecs.yaml, operators/codeflare-operator/0.0.1/metadata/annotations.yaml, operators/codeflare-operator/0.0.1/tests/scorecard/config.yaml, operators/codeflare-operator/ci.yaml
=> operator [N] [CI] codeflare-operator (0.0.1)

operators/mariadb-operator/0.9.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.9.1/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.9.1/metadata/annotations.yaml, operators/mariadb-operator/0.9.1/tests/scorecard/config.yaml
Add operator mariadb-operator (0.9.1) to community operators
=> operator mariadb-operator (0.9.1)

operators/mariadb-operator/0.10.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.10.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.10.0/metadata/annotations.yaml, operators/mariadb-operator/0.10.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.10.0) to community operators
=> operator mariadb-operator (0.10.0)

operators/project-quay/3.9.0-nightly.20230311/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230311/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230311 to community operators
=> operator project-quay (3.9.0-nightly.20230311)

operators/ndmspc-operator/0.2.8/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.2.8/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.2.8/metadata/annotations.yaml, operators/ndmspc-operator/0.2.8/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.2.8)

operators/project-quay/3.9.0-nightly.20230312/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230312/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230312 to community operators
=> operator project-quay (3.9.0-nightly.20230312)

operators/pelorus-operator/0.0.5/manifests/charts.pelorus.konveyor.io_pelorus.yaml, operators/pelorus-operator/0.0.5/manifests/pelorus-operator-controller-manager-metrics-service_v1_service.yaml, operators/pelorus-operator/0.0.5/manifests/pelorus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pelorus-operator/0.0.5/manifests/pelorus-operator.clusterserviceversion.yaml, operators/pelorus-operator/0.0.5/metadata/annotations.yaml, operators/pelorus-operator/0.0.5/metadata/properties.yaml, operators/pelorus-operator/0.0.5/tests/scorecard/config.yaml
=> operator pelorus-operator (0.0.5)

operators/forklift-operator/2.3.3/metadata/annotations.yaml, operators/forklift-operator/2.3.4/metadata/annotations.yaml, operators/forklift-operator/2.4.0/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.4.0/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.4.0/metadata/annotations.yaml
=> operator [R] forklift-operator (2.3.2 2.3.3 2.3.4 2.4.0)

ci/pipeline-config-ocp.yaml
=> Change pull secret

operators/project-quay/3.9.0-nightly.20230314/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230314/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230314 to community operators
=> operator project-quay (3.9.0-nightly.20230314)

operators/forklift-operator/2.3.4/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.3.4/metadata/annotations.yaml, operators/forklift-operator/2.4.0/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.4.0/metadata/annotations.yaml
=> operator [R] forklift-operator (2.3.4 2.4.0)

operators/stolostron/ci.yaml
Change one operator at a time
Add ci config to stolostron
--
=> operator [CI] stolostron

operators/stolostron-engine/ci.yaml
=> operator [CI] stolostron-engine

operators/grafana-operator/4.10.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.10.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.10.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.10.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.10.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.10.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.10.0/integreatly.org_grafanafolders.yaml, operators/grafana-operator/4.10.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.10.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.10.0)

operators/verticadb-operator/1.10.1/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.10.1/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.10.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.10.1/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/verticadb-operator/1.10.1/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.10.1/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.10.1/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.10.1/metadata/annotations.yaml, operators/verticadb-operator/1.10.1/tests/scorecard/config.yaml
=> operator verticadb-operator (1.10.1)

operators/project-quay/3.9.0-nightly.20230315/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230315/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230315 to community operators
=> operator project-quay (3.9.0-nightly.20230315)

operators/stolostron-engine/0.1.1/manifests/stolostron-engine.v0.1.1.clusterserviceversion.yaml, operators/stolostron-engine/ci.yaml
=> operator [O] [CI] stolostron-engine

operators/stolostron/0.1.1/manifests/stolostron.v0.1.1.clusterserviceversion.yaml, operators/stolostron/ci.yaml
=> operator [O] [CI] stolostron

operators/opentelemetry-operator/0.72.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.72.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.72.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.72.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.72.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.72.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.72.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.72.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.72.0)

operators/opendatahub-operator/1.4.2/manifests/kfdef.apps.kubeflow.org.crd.yaml, operators/opendatahub-operator/1.4.2/manifests/odhapplications.dashboard.opendatahub.io.crd.yaml, operators/opendatahub-operator/1.4.2/manifests/odhdashboardconfigs.opendatahub.io.crd.yaml, operators/opendatahub-operator/1.4.2/manifests/odhdocuments.dashboard.opendatahub.io.crd.yaml, operators/opendatahub-operator/1.4.2/manifests/odhquickstarts.console.openshift.io.crd.yaml, operators/opendatahub-operator/1.4.2/manifests/opendatahub-operator.v1.4.2.clusterserviceversion.yaml, operators/opendatahub-operator/1.4.2/metadata/annotations.yaml
Release of the ODH 1.4.2 bundle
--
=> operator opendatahub-operator (1.4.2)

operators/rabbitmq-cluster-operator/2.2.0/bundle.Dockerfile, operators/rabbitmq-cluster-operator/2.2.0/manifests/crds.yaml, operators/rabbitmq-cluster-operator/2.2.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-cluster-operator/2.2.0/metadata/annotations.yaml
=> operator rabbitmq-cluster-operator (2.2.0)

operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.32.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.32.0/victoriametrics-operator.0.32.0.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operator victoriametrics-operator (0.32.0)

operators/kiali/1.65.0/bundle.Dockerfile, operators/kiali/1.65.0/manifests/kiali.crd.yaml, operators/kiali/1.65.0/manifests/kiali.v1.65.0.clusterserviceversion.yaml, operators/kiali/1.65.0/metadata/annotations.yaml
=> operator kiali (1.65.0)

operators/3scale-community-operator/0.10.1/bundle.Dockerfile, operators/3scale-community-operator/0.10.1/manifests/3scale-operator.clusterserviceversion.yaml, operators/3scale-community-operator/0.10.1/manifests/apps.3scale.net_apimanagerbackups.yaml, operators/3scale-community-operator/0.10.1/manifests/apps.3scale.net_apimanagerrestores.yaml, operators/3scale-community-operator/0.10.1/manifests/apps.3scale.net_apimanagers.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_activedocs.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_backends.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_custompolicydefinitions.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_developeraccounts.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_developerusers.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_openapis.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_products.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_proxyconfigpromotes.yaml, operators/3scale-community-operator/0.10.1/manifests/capabilities.3scale.net_tenants.yaml, operators/3scale-community-operator/0.10.1/manifests/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/3scale-community-operator/0.10.1/manifests/threescale-operator-controller-manager-metrics-service_v1_service.yaml, operators/3scale-community-operator/0.10.1/metadata/annotations.yaml, operators/3scale-community-operator/0.10.1/tests/scorecard/config.yaml
=> operator 3scale-community-operator (0.10.1)

operators/project-quay/3.8.4/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.4/quayecosystems.crd.yaml, operators/project-quay/3.8.4/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.4 to community operators
=> operator project-quay (3.8.4)

operators/external-secrets-operator/0.8.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.0/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.0/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.0/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.0/metadata/annotations.yaml, operators/external-secrets-operator/0.8.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.0
=> operator external-secrets-operator (0.8.0)

operators/percona-server-mongodb-operator/1.14.0/manifests/percona-server-mongodb-operator.v1.14.0.clusterserviceversion.yaml, operators/percona-server-mongodb-operator/1.14.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.14.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.14.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.14.0/metadata/annotations.yaml
=> operator percona-server-mongodb-operator (1.14.0)

operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.32.1/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.32.1/victoriametrics-operator.0.32.1.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operator victoriametrics-operator (0.32.1)

operators/cluster-aas-operator/0.0.5/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.0.5/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.0.5/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.0.5/manifests/cluster-aas-operator-repo-bridge.yaml, operators/cluster-aas-operator/0.0.5/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.0.5/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.0.5/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.0.5/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.0.5/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.0.5/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.0.5/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.0.5/metadata/annotations.yaml, operators/cluster-aas-operator/0.0.5/metadata/dependencies.yaml, operators/cluster-aas-operator/0.0.5/tests/scorecard/config.yaml, operators/cluster-aas-operator/ci.yaml
=> operator [CI] cluster-aas-operator (0.0.5)

operators/forklift-operator/2.4.0/manifests/forklift-operator.clusterserviceversion.yaml
=> operator [O] forklift-operator (2.4.0)

operators/external-secrets-operator/0.8.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.1/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.1/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.1/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.1/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.1/metadata/annotations.yaml, operators/external-secrets-operator/0.8.1/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.1
=> operator external-secrets-operator (0.8.1)

operators/mariadb-operator/0.11.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.11.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.11.0/metadata/annotations.yaml, operators/mariadb-operator/0.11.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.11.0) to community operators
=> operator mariadb-operator (0.11.0)

operators/project-quay/3.9.0-nightly.20230319/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230319/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230319 to community operators
=> operator project-quay (3.9.0-nightly.20230319)

operators/project-quay/3.9.0-nightly.20230320/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230320/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230320 to community operators
=> operator project-quay (3.9.0-nightly.20230320)

operators/app-director-operator/1.0.0/Dockerfile, operators/app-director-operator/1.0.0/manifests/app-director-controller-manager-metrics-service_v1_service.yaml, operators/app-director-operator/1.0.0/manifests/app-director-manager-config_v1_configmap.yaml, operators/app-director-operator/1.0.0/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/app-director-operator/1.0.0/manifests/app-director-operator.clusterserviceversion.yaml, operators/app-director-operator/1.0.0/manifests/appdirector.randoli.ca_appdirectoragents.yaml, operators/app-director-operator/1.0.0/manifests/appdirector.randoli.ca_clusterwideappdirectoragents.yaml, operators/app-director-operator/1.0.0/metadata/annotations.yaml, operators/app-director-operator/1.0.0/tests/scorecard/config.yaml, operators/app-director-operator/ci.yaml
=> operator [CI] app-director-operator (1.0.0)

operators/cluster-aas-operator/0.0.6/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.0.6/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.0.6/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.0.6/manifests/cluster-aas-operator-repo-bridge.yaml, operators/cluster-aas-operator/0.0.6/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.0.6/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.0.6/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.0.6/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.0.6/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.0.6/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.0.6/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.0.6/metadata/annotations.yaml, operators/cluster-aas-operator/0.0.6/metadata/dependencies.yaml, operators/cluster-aas-operator/0.0.6/tests/scorecard/config.yaml
=> operator cluster-aas-operator (0.0.6)

operators/project-quay/3.9.0-nightly.20230321/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230321/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230321 to community operators
=> operator project-quay (3.9.0-nightly.20230321)

operators/gitlab-operator-kubernetes/0.18.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.18.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.18.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.18.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.18.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.18.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.18.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.18.0)

operators/rabbitmq-messaging-topology-operator/1.10.2/bundle.Dockerfile, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_bindings.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_exchanges.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_federations.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_permissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_policies.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_queues.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_schemareplications.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_shovels.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_superstreams.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_topicpermissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_users.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.com_vhosts.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-messaging-topology-operator/1.10.2/metadata/annotations.yaml
=> operator rabbitmq-messaging-topology-operator (1.10.2)

operators/loki-operator/0.2.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml, operators/loki-operator/0.2.0/manifests/loki-operator-manager-config_v1_configmap.yaml, operators/loki-operator/0.2.0/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/loki-operator/0.2.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/loki-operator/0.2.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/loki-operator/0.2.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/loki-operator/0.2.0/manifests/loki-operator-webhook-service_v1_service.yaml, operators/loki-operator/0.2.0/manifests/loki-operator.clusterserviceversion.yaml, operators/loki-operator/0.2.0/manifests/loki.grafana.com_alertingrules.yaml, operators/loki-operator/0.2.0/manifests/loki.grafana.com_lokistacks.yaml, operators/loki-operator/0.2.0/manifests/loki.grafana.com_recordingrules.yaml, operators/loki-operator/0.2.0/manifests/loki.grafana.com_rulerconfigs.yaml, operators/loki-operator/0.2.0/metadata/annotations.yaml, operators/loki-operator/0.2.0/tests/scorecard/config.yaml
=> operator loki-operator (0.2.0)

operators/group-sync-operator/0.0.25/Dockerfile, operators/group-sync-operator/0.0.25/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.25/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.25/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.25/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.25/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.25/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.25/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.25/metadata/annotations.yaml, operators/group-sync-operator/0.0.25/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.25)

operators/yaks/0.14.3/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.14.3/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.14.3/yaks.v0.14.3.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operator yaks (0.14.3)

operators/project-quay/3.9.0-nightly.20230328/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230328/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230328 to community operators
=> operator project-quay (3.9.0-nightly.20230328)

operators/project-quay/3.9.0-nightly.20230329/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230329/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230329 to community operators
=> operator project-quay (3.9.0-nightly.20230329)

operators/mongodb-atlas-kubernetes/1.7.1/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.7.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.7.1/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.7.1/tests/scorecard/config.yaml
=> operator mongodb-atlas-kubernetes (1.7.1)

operators/patterns-operator/0.0.12/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.12/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.12/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.12/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.12/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.12/metadata/annotations.yaml, operators/patterns-operator/0.0.12/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.12)

operators/koku-metrics-operator/2.0.0/Dockerfile, operators/koku-metrics-operator/2.0.0/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/2.0.0/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/2.0.0/metadata/annotations.yaml, operators/koku-metrics-operator/2.0.0/tests/scorecard/config.yaml
=> operator koku-metrics-operator (2.0.0)

operators/portworx-essentials/23.3.1/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/23.3.1/core_v1_storagenode_crd.yaml, operators/portworx-essentials/23.3.1/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operator portworx-essentials (23.3.1)

operators/project-quay/3.8.5/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.5/quayecosystems.crd.yaml, operators/project-quay/3.8.5/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.5 to community operators
=> operator project-quay (3.8.5)

operators/flux/0.41.2/manifests/alert.crd.yaml, operators/flux/0.41.2/manifests/bucket.crd.yaml, operators/flux/0.41.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.41.2/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.41.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.41.2/manifests/flux-edit-flux-system.clusterrole.yaml, operators/flux/0.41.2/manifests/flux-view-flux-system.clusterrole.yaml, operators/flux/0.41.2/manifests/flux.v0.41.2.clusterserviceversion.yaml, operators/flux/0.41.2/manifests/gitrepository.crd.yaml, operators/flux/0.41.2/manifests/helmchart.crd.yaml, operators/flux/0.41.2/manifests/helmrelease.crd.yaml, operators/flux/0.41.2/manifests/helmrepository.crd.yaml, operators/flux/0.41.2/manifests/imagepolicy.crd.yaml, operators/flux/0.41.2/manifests/imagerepository.crd.yaml, operators/flux/0.41.2/manifests/imageupdateautomation.crd.yaml, operators/flux/0.41.2/manifests/kustomization.crd.yaml, operators/flux/0.41.2/manifests/notification-controller.service.yaml, operators/flux/0.41.2/manifests/ocirepository.crd.yaml, operators/flux/0.41.2/manifests/provider.crd.yaml, operators/flux/0.41.2/manifests/receiver.crd.yaml, operators/flux/0.41.2/manifests/source-controller.service.yaml, operators/flux/0.41.2/manifests/webhook-receiver.service.yaml, operators/flux/0.41.2/metadata/annotations.yaml
=> operator flux (0.41.2)

operators/project-quay/3.9.0-nightly.20230401/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230401/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230401 to community operators
=> operator project-quay (3.9.0-nightly.20230401)

operators/project-quay/3.9.0-nightly.20230402/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230402/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230402 to community operators
=> operator project-quay (3.9.0-nightly.20230402)

operators/edp-keycloak-operator/1.15.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml, operators/edp-keycloak-operator/1.15.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakclients.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealms.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, operators/edp-keycloak-operator/1.15.0/manifests/v1.edp.epam.com_keycloaks.yaml, operators/edp-keycloak-operator/1.15.0/metadata/annotations.yaml, operators/edp-keycloak-operator/1.15.0/tests/scorecard/config.yaml
=> operator edp-keycloak-operator (1.15.0)

operators/aqua/2022.4.11/bundle.Dockerfile, operators/aqua/2022.4.11/manifests/aqua-operator.v2022.4.11.clusterserviceversion.yaml, operators/aqua/2022.4.11/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aqualightnings.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.11/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.11/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.11/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.11/metadata/annotations.yaml
=> operator aqua (2022.4.11)

operators/dell-csi-operator/1.11.0/csiisilons.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.11.0/csipowermaxes.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.11.0/csipowermaxrevproxies.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.11.0/csipowerstores.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.11.0/csiunities.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.11.0/csivxflexoses.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.11.0/dell-csi-operator.v1.11.0.clusterserviceversion.yaml, operators/dell-csi-operator/dell-csi-operator.package.yaml
=> operator dell-csi-operator (1.11.0)

operators/dell-csm-operator/1.1.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml, operators/dell-csm-operator/1.1.0/manifests/dell-csm-operator.v1.1.0.clusterserviceversion.yaml, operators/dell-csm-operator/1.1.0/metadata/annotations.yaml, operators/dell-csm-operator/1.1.0/tests/scorecard/config.yaml
=> operator dell-csm-operator (1.1.0)

operators/patterns-operator/0.0.13/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.13/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.13/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.13/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.13/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.13/metadata/annotations.yaml, operators/patterns-operator/0.0.13/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.13)

operators/percona-postgresql-operator/1.4.0/manifests/percona-postgresql-operator.v1.4.0.clusterserviceversion.yaml, operators/percona-postgresql-operator/1.4.0/manifests/perconapgclusters.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.4.0/manifests/pgclusters.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.4.0/manifests/pgpolicies.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.4.0/manifests/pgreplicas.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.4.0/manifests/pgtasks.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.4.0/metadata/annotations.yaml
=> operator percona-postgresql-operator (1.4.0)

operators/cluster-aas-operator/0.0.6/manifests/cluster-aas-operator.clusterserviceversion.yaml
=> operator [O] cluster-aas-operator (0.0.6)

operators/pelorus-operator/0.0.6/manifests/charts.pelorus.dora-metrics.io_peloruses.yaml, operators/pelorus-operator/0.0.6/manifests/pelorus-operator-controller-manager-metrics-service_v1_service.yaml, operators/pelorus-operator/0.0.6/manifests/pelorus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pelorus-operator/0.0.6/manifests/pelorus-operator.clusterserviceversion.yaml, operators/pelorus-operator/0.0.6/metadata/annotations.yaml, operators/pelorus-operator/0.0.6/metadata/properties.yaml, operators/pelorus-operator/0.0.6/tests/scorecard/config.yaml
=> operator pelorus-operator (0.0.6)

operators/opendatahub-operator/1.5.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/1.5.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/1.5.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/1.5.0/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/1.5.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/1.5.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/1.5.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/1.5.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/1.5.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/1.5.0/metadata/annotations.yaml, operators/opendatahub-operator/1.5.0/tests/scorecard/config.yaml
Release of the ODH 1.5 bundle
--
=> operator opendatahub-operator (1.5.0)

operators/annotationlab/4.8.3/bundle.Dockerfile, operators/annotationlab/4.8.3/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.8.3/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.8.3/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.8.3/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.8.3/metadata/annotations.yaml, operators/annotationlab/4.8.3/tests/scorecard/config.yaml
=> operator annotationlab (4.8.3)

operators/tempo-operator/0.1.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, operators/tempo-operator/0.1.0/manifests/tempo-operator-manager-config_v1_configmap.yaml, operators/tempo-operator/0.1.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tempo-operator/0.1.0/manifests/tempo-operator-webhook-service_v1_service.yaml, operators/tempo-operator/0.1.0/manifests/tempo-operator.clusterserviceversion.yaml, operators/tempo-operator/0.1.0/manifests/tempo.grafana.com_tempostacks.yaml, operators/tempo-operator/0.1.0/metadata/annotations.yaml, operators/tempo-operator/0.1.0/tests/scorecard/config.yaml, operators/tempo-operator/ci.yaml
=> operator [N] [CI] tempo-operator (0.1.0)

operators/dbaas-operator/0.5.0/manifests/dbaas-operator-controller-manager-metrics-service_v1_service.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaas-service-binding-controller-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaasconnection-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaasinventory-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaasinventory-viewer_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaaspolicy-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaaspolicy-viewer_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaasprovider-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-dbaasprovider-viewers_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-edit-dedicated-admins_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-manager-config_v1_configmap.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator-webhook-service_v1_service.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas-operator.clusterserviceversion.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas.redhat.com_dbaasconnections.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas.redhat.com_dbaasinstances.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas.redhat.com_dbaasinventories.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas.redhat.com_dbaasplatforms.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas.redhat.com_dbaaspolicies.yaml, operators/dbaas-operator/0.5.0/manifests/dbaas.redhat.com_dbaasproviders.yaml, operators/dbaas-operator/0.5.0/metadata/annotations.yaml, operators/dbaas-operator/0.5.0/metadata/dependencies.yaml, operators/dbaas-operator/0.5.0/tests/scorecard/config.yaml, operators/dbaas-operator/ci.yaml
=> operator [N] [CI] dbaas-operator (0.5.0)

operators/ecr-secret-operator/0.4.1/ecr-secret-operator-controller-manager-metrics-service_v1_service.yaml, operators/ecr-secret-operator/0.4.1/ecr-secret-operator-manager-config_v1_configmap.yaml, operators/ecr-secret-operator/0.4.1/ecr-secret-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ecr-secret-operator/0.4.1/ecr-secret-operator.clusterserviceversion.yaml, operators/ecr-secret-operator/0.4.1/ecr-secret-sample_ecr.mobb.redhat.com_v1alpha1_secret.yaml, operators/ecr-secret-operator/0.4.1/ecr-secret_ecr.mobb.redhat.com_v1alpha1_secret.yaml, operators/ecr-secret-operator/0.4.1/ecr.mobb.redhat.com_argohelmreposecrets.yaml, operators/ecr-secret-operator/0.4.1/ecr.mobb.redhat.com_secrets.yaml, operators/ecr-secret-operator/ci.yaml, operators/ecr-secret-operator/ecr-secret-operator.package.yaml
=> operator [CI] ecr-secret-operator (0.4.1)

operators/windup-operator/0.0.13/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.13/manifests/windup.crd.yaml, operators/windup-operator/0.0.13/metadata/annotations.yaml
=> operator windup-operator (0.0.13)

operators/mongodb-atlas-kubernetes/1.7.2/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.7.2/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.7.2/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.7.2/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.7.2/tests/scorecard/config.yaml
=> operator mongodb-atlas-kubernetes (1.7.2)

operators/verticadb-operator/1.10.2/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.10.2/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.10.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.10.2/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/verticadb-operator/1.10.2/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.10.2/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.10.2/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.10.2/metadata/annotations.yaml, operators/verticadb-operator/1.10.2/tests/scorecard/config.yaml
=> operator verticadb-operator (1.10.2)

operators/confluent-for-kubernetes/2.3.4/manifests/confluent-for-kubernetes.clusterserviceversion.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/confluent-operator-service_v1_service.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_clusterlinks.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_confluentrolebindings.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_connectors.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_connects.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_controlcenters.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_kafkarestclasses.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_kafkarestproxies.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_kafkas.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_kafkatopics.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_ksqldbs.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_migrationjobs.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_schemaexporters.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_schemaregistries.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_schemas.yaml, operators/confluent-for-kubernetes/2.3.4/manifests/platform.confluent.io_zookeepers.yaml, operators/confluent-for-kubernetes/2.3.4/metadata/annotations.yaml, operators/confluent-for-kubernetes/ci.yaml
This is kind of a hack to "support" the Confluent For Kubernetes operator on OpenShift 4.7 and 4.8.
The [CFK Operator](https://github.com/redhat-openshift-ecosystem/certified-operators/tree/main/operators/confluent-for-kubernetes/2.3.4) is too big (~2.4 MB) to work with OLM < 4.9 due to a [bundle size limitation](https://github.com/redhat-openshift-ecosystem/certified-operators/issues/552).
This is almost the exact same operator as the [CFK 2.3.4 operator](https://github.com/redhat-openshift-ecosystem/certified-operators/tree/main/operators/confluent-for-kubernetes/2.3.4), with these changes:
* All descriptions removed (detailed field descriptions can be found in the Confluent [documentation](https://docs.confluent.io/operator/2.3/co-api.html))
* Less-commonly-used CRDs …
=> operator [N] [CI] confluent-for-kubernetes (2.3.4)

operators/ibm-security-verify-access-operator/23.3.0/manifests/ibm-security-verify-access-operator.clusterserviceversion.yaml, operators/ibm-security-verify-access-operator/23.3.0/manifests/ibm.com_ibmsecurityverifyaccesses.yaml, operators/ibm-security-verify-access-operator/23.3.0/manifests/verify-access-operator-controller-manager-metrics-service_v1_service.yaml, operators/ibm-security-verify-access-operator/23.3.0/manifests/verify-access-operator-controller-manager-snapshot-service_v1_service.yaml, operators/ibm-security-verify-access-operator/23.3.0/manifests/verify-access-operator-manager-config_v1_configmap.yaml, operators/ibm-security-verify-access-operator/23.3.0/manifests/verify-access-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ibm-security-verify-access-operator/23.3.0/metadata/annotations.yaml, operators/ibm-security-verify-access-operator/23.3.0/tests/scorecard/config.yaml, operators/ibm-security-verify-access-operator/ci.yaml
=> operator [CI] ibm-security-verify-access-operator (23.3.0)

operators/loki-operator/0.3.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml, operators/loki-operator/0.3.0/manifests/loki-operator-manager-config_v1_configmap.yaml, operators/loki-operator/0.3.0/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/loki-operator/0.3.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/loki-operator/0.3.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/loki-operator/0.3.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/loki-operator/0.3.0/manifests/loki-operator-webhook-service_v1_service.yaml, operators/loki-operator/0.3.0/manifests/loki-operator.clusterserviceversion.yaml, operators/loki-operator/0.3.0/manifests/loki.grafana.com_alertingrules.yaml, operators/loki-operator/0.3.0/manifests/loki.grafana.com_lokistacks.yaml, operators/loki-operator/0.3.0/manifests/loki.grafana.com_recordingrules.yaml, operators/loki-operator/0.3.0/manifests/loki.grafana.com_rulerconfigs.yaml, operators/loki-operator/0.3.0/metadata/annotations.yaml, operators/loki-operator/0.3.0/tests/scorecard/config.yaml
=> operator loki-operator (0.3.0)

operators/dynatrace-operator/0.11.0/Dockerfile, operators/dynatrace-operator/0.11.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.11.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.11.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.11.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.11.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.11.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.11.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.11.0/metadata/annotations.yaml
=> operator dynatrace-operator (0.11.0)

operators/community-windows-machine-config-operator/8.0.0/manifests/community-windows-machine-config-operator.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/windows-instance-config-daemon_v1_serviceaccount.yaml, operators/community-windows-machine-config-operator/8.0.0/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/8.0.0/metadata/annotations.yaml
=> operator community-windows-machine-config-operator (8.0.0)

ci/pipeline-config-ocp.yaml
updates for https://redhat-openshift-ecosystem.github.io/community-operators-pipeline/project/ocp/#release-process
=> ISV-3506: add 4.13 index version

operators/project-quay/3.8.6/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.6/quayecosystems.crd.yaml, operators/project-quay/3.8.6/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.6 to community operators
=> operator project-quay (3.8.6)

operators/gitlab-operator-kubernetes/0.19.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.19.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.19.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.19.0)

operators/pulp-operator/ci.yaml
=> operator [CI] pulp-operator

operators/cert-utils-operator/1.3.11/Dockerfile, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator-certificate-rule-alerts_monitoring.coreos.com_v1_prometheusrule.yaml, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator-controller-manager-metrics-service_v1_service.yaml, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/cert-utils-operator/1.3.11/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.11/metadata/annotations.yaml, operators/cert-utils-operator/1.3.11/tests/scorecard/config.yaml
=> operator cert-utils-operator (1.3.11)

operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.6/manifests/pulp-operator.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-alpha.6/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-alpha.6/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-alpha.6/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-alpha.6/metadata/annotations.yaml, operators/pulp-operator/1.0.0-alpha.6/tests/scorecard/config.yaml
=> operator pulp-operator (1.0.0-alpha.6)

operators/codeflare-operator/0.0.2/manifests/codeflare-operator-controller-manager-metrics-service_v1_service.yaml, operators/codeflare-operator/0.0.2/manifests/codeflare-operator-manager-config_v1_configmap.yaml, operators/codeflare-operator/0.0.2/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/0.0.2/manifests/codeflare-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/codeflare-operator/0.0.2/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/0.0.2/manifests/codeflare.codeflare.dev_instascales.yaml, operators/codeflare-operator/0.0.2/manifests/codeflare.codeflare.dev_mcads.yaml, operators/codeflare-operator/0.0.2/manifests/mcad.ibm.com_appwrappers.yaml, operators/codeflare-operator/0.0.2/manifests/mcad.ibm.com_queuejobs.yaml, operators/codeflare-operator/0.0.2/manifests/mcad.ibm.com_schedulingspecs.yaml, operators/codeflare-operator/0.0.2/metadata/annotations.yaml, operators/codeflare-operator/0.0.2/tests/scorecard/config.yaml
=> operator codeflare-operator (0.0.2)

operators/rabbitmq-messaging-topology-operator/1.10.3/bundle.Dockerfile, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_bindings.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_exchanges.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_federations.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_permissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_policies.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_queues.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_schemareplications.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_shovels.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_superstreams.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_topicpermissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_users.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.com_vhosts.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-messaging-topology-operator/1.10.3/metadata/annotations.yaml
=> operator rabbitmq-messaging-topology-operator (1.10.3)

operators/dynatrace-operator/0.11.1/Dockerfile, operators/dynatrace-operator/0.11.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.11.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.11.1/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.11.1/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.11.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.11.1/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.11.1/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.11.1/metadata/annotations.yaml
=> operator dynatrace-operator (0.11.1)

operators/portworx-essentials/23.4.0/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/23.4.0/core_v1_storagenode_crd.yaml, operators/portworx-essentials/23.4.0/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operator portworx-essentials (23.4.0)

operators/aerospike-kubernetes-operator/2.5.0/bundle.Dockerfile, operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml, operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml, operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.5.0/manifests/aerospike-operator-webhook-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.5.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml, operators/aerospike-kubernetes-operator/2.5.0/metadata/annotations.yaml, operators/aerospike-kubernetes-operator/2.5.0/tests/scorecard/config.yaml
=> operator aerospike-kubernetes-operator (2.5.0)

operators/windup-operator/0.0.14/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.14/manifests/windup.crd.yaml, operators/windup-operator/0.0.14/metadata/annotations.yaml
=> operator windup-operator (0.0.14)

operators/node-maintenance-operator/0.15.0/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml, operators/node-maintenance-operator/0.15.0/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-maintenance-operator/0.15.0/manifests/node-maintenance-operator-webhook-service_v1_service.yaml, operators/node-maintenance-operator/0.15.0/manifests/node-maintenance-operator.clusterserviceversion.yaml, operators/node-maintenance-operator/0.15.0/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml, operators/node-maintenance-operator/0.15.0/metadata/annotations.yaml, operators/node-maintenance-operator/0.15.0/tests/scorecard/config.yaml, operators/node-maintenance-operator/ci.yaml
Let NMO v0.15.0 be available on OCP and OKD
--
=> operator [CI] node-maintenance-operator (0.15.0)

operators/OWNERS
=> [ISV-3572] Update GitHub reviewers/assignees.

operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-create-user-job_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-migrate-database-job_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-pod-launcher-role_Role.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-pod-launcher-rolebinding_RoleBinding.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-pod-log-reader-role_Role.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-pod-log-reader-rolebinding_RoleBinding.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-postgresql_Role.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-postgresql_RoleBinding.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-postgresql_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-redis_Role.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-redis_RoleBinding.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-redis_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-scc-rolebinding_RoleBinding.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-scheduler_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-statsd_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-triggerer_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-webserver_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-helm-worker_ServiceAccount.yml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-hybrid-operator-controller-manager-metrics-service_v1_service.yaml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-hybrid-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/airflow-hybrid-operator/0.2.5/manifests/airflow-hybrid-operator.clusterserviceversion.yaml, operators/airflow-hybrid-operator/0.2.5/manifests/workflow.apache.org_airflows.yaml, operators/airflow-hybrid-operator/0.2.5/metadata/annotations.yaml, operators/airflow-hybrid-operator/0.2.5/tests/scorecard/config.yaml, operators/airflow-hybrid-operator/ci.yaml
=> operator [N] [CI] airflow-hybrid-operator (0.2.5)

operators/self-node-remediation/0.6.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation-webhook-service_v1_service.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation.clusterserviceversion.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml, operators/self-node-remediation/0.6.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, operators/self-node-remediation/0.6.0/metadata/annotations.yaml, operators/self-node-remediation/0.6.0/tests/scorecard/config.yaml, operators/self-node-remediation/ci.yaml
=> operator [CI] self-node-remediation (0.6.0)

operators/seldon-operator/1.16.0/manifests/machinelearning.seldon.io_seldondeployments.yaml, operators/seldon-operator/1.16.0/manifests/seldon-operator.clusterserviceversion.yaml, operators/seldon-operator/1.16.0/metadata/annotations.yaml, operators/seldon-operator/1.16.0/tests/scorecard/config.yaml
=> operator seldon-operator (1.16.0)

ci/pipeline-config-ocp.yaml
Support OpenShift 4.13 in community operator repository.
JIRA: ISV-3603
--
=> OpenShift 4.13 release

operators/project-quay/3.9.0-nightly.20230513/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230513/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230513 to community operators
=> operator project-quay (3.9.0-nightly.20230513)

operators/windup-operator/0.0.15/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.15/manifests/windup.crd.yaml, operators/windup-operator/0.0.15/metadata/annotations.yaml
=> operator windup-operator (0.0.15)

operators/project-quay/3.9.0-nightly.20230514/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230514/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230514 to community operators
=> operator project-quay (3.9.0-nightly.20230514)

operators/multi-nic-cni-operator/1.0.4/bundle.Dockerfile, operators/multi-nic-cni-operator/1.0.4/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multi-nic-cni-operator.clusterserviceversion.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multinic.fms.io_cidrs.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multinic.fms.io_configs.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multinic.fms.io_deviceclasses.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multinic.fms.io_hostinterfaces.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multinic.fms.io_ippools.yaml, operators/multi-nic-cni-operator/1.0.4/manifests/multinic.fms.io_multinicnetworks.yaml, operators/multi-nic-cni-operator/1.0.4/metadata/annotations.yaml, operators/multi-nic-cni-operator/1.0.4/tests/scorecard/config.yaml, operators/multi-nic-cni-operator/1.1.0/bundle.Dockerfile, operators/multi-nic-cni-operator/1.1.0/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multi-nic-cni-operator.clusterserviceversion.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multinic.fms.io_cidrs.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multinic.fms.io_configs.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multinic.fms.io_deviceclasses.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multinic.fms.io_hostinterfaces.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multinic.fms.io_ippools.yaml, operators/multi-nic-cni-operator/1.1.0/manifests/multinic.fms.io_multinicnetworks.yaml, operators/multi-nic-cni-operator/1.1.0/metadata/annotations.yaml, operators/multi-nic-cni-operator/1.1.0/tests/scorecard/config.yaml
=> operator [R] multi-nic-cni-operator (1.0.4 1.1.0)

operators/forklift-operator/2.4.1/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.4.1/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.4.1/metadata/annotations.yaml
=> operator forklift-operator (2.4.1)

operators/mongodb-atlas-kubernetes/1.7.3/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.7.3/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.7.3/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.7.3/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.7.3/tests/scorecard/config.yaml
=> operator mongodb-atlas-kubernetes (1.7.3)

operators/gitlab-operator-kubernetes/0.19.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.19.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.19.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.19.1)

operators/awx-operator/2.0.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.0.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.0.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.0.1/manifests/awx-operator.v2.0.1.clusterserviceversion.yaml, operators/awx-operator/2.0.1/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.0.1/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.0.1/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.0.1/metadata/annotations.yaml, operators/awx-operator/2.0.1/tests/scorecard/config.yaml
=> operator awx-operator (2.0.1)

operators/project-quay/3.9.0-nightly.20230515/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230515/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230515 to community operators
=> operator project-quay (3.9.0-nightly.20230515)

operators/ndmspc-operator/0.3.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.3.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.3.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.3.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.3.0/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.3.0/metadata/annotations.yaml, operators/ndmspc-operator/0.3.0/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.3.0)

operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.33.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.33.0/victoriametrics-operator.0.33.0.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operator victoriametrics-operator (0.33.0)

operators/hyperfoil-bundle/0.24.2/hyperfoil-operator.v0.24.2.clusterserviceversion.yaml, operators/hyperfoil-bundle/0.24.2/hyperfoil.io_hyperfoils_crd.yaml, operators/hyperfoil-bundle/ci.yaml, operators/hyperfoil-bundle/hyperfoil-bundle.package.yaml
=> operator [CI] hyperfoil-bundle (0.24.2)

operators/awx-operator/2.1.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.1.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.1.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.1.0/manifests/awx-operator.v2.1.0.clusterserviceversion.yaml, operators/awx-operator/2.1.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.1.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.1.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.1.0/metadata/annotations.yaml, operators/awx-operator/2.1.0/tests/scorecard/config.yaml
=> operator awx-operator (2.1.0)

operators/authorino-operator/0.7.0/bundle.Dockerfile, operators/authorino-operator/0.7.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.7.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.7.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.7.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.7.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.7.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml, operators/authorino-operator/0.7.0/manifests/authorino-operator-manager-config_v1_configmap.yaml, operators/authorino-operator/0.7.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.7.0/manifests/authorino-operator.clusterserviceversion.yaml, operators/authorino-operator/0.7.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.7.0/manifests/authorino.kuadrant.io_authconfigs.yaml, operators/authorino-operator/0.7.0/manifests/manager-config_v1_configmap.yaml, operators/authorino-operator/0.7.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml, operators/authorino-operator/0.7.0/metadata/annotations.yaml, operators/authorino-operator/0.7.0/tests/scorecard/config.yaml
=> operator authorino-operator (0.7.0)

operators/patterns-operator/0.0.14/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.14/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.14/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.14/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.14/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.14/metadata/annotations.yaml, operators/patterns-operator/0.0.14/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.14)

operators/gitlab-operator-kubernetes/0.19.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.19.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.19.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.19.2)

operators/limitador-operator/0.5.0/bundle.Dockerfile, operators/limitador-operator/0.5.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml, operators/limitador-operator/0.5.0/manifests/limitador-operator-manager-config_v1_configmap.yaml, operators/limitador-operator/0.5.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/limitador-operator/0.5.0/manifests/limitador-operator.clusterserviceversion.yaml, operators/limitador-operator/0.5.0/manifests/limitador.kuadrant.io_limitadors.yaml, operators/limitador-operator/0.5.0/metadata/annotations.yaml, operators/limitador-operator/0.5.0/tests/scorecard/config.yaml
=> operator limitador-operator (0.5.0)

operators/external-secrets-operator/0.8.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.2/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.2/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.2/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.2/metadata/annotations.yaml, operators/external-secrets-operator/0.8.2/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.2
=> operator external-secrets-operator (0.8.2)

operators/mariadb-operator/0.15.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.15.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.15.0/metadata/annotations.yaml, operators/mariadb-operator/0.15.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.15.0) to community operators
=> operator mariadb-operator (0.15.0)

operators/verticadb-operator/1.11.0/manifests/vertica.com_eventtriggers.yaml, operators/verticadb-operator/1.11.0/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.11.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.11.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.11.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/verticadb-operator/1.11.0/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.11.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.11.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.11.0/metadata/annotations.yaml, operators/verticadb-operator/1.11.0/tests/scorecard/config.yaml
=> operator verticadb-operator (1.11.0)

operators/bpfd-operator/0.2.0/bundle.Dockerfile, operators/bpfd-operator/0.2.0/manifests/bpfd-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-config_v1_configmap.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-controller-manager-metrics-service_v1_service.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-daemon_v1_serviceaccount.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-operator.clusterserviceversion.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd.io_bpfprograms.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd.io_tcprograms.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd.io_tracepointprograms.yaml, operators/bpfd-operator/0.2.0/manifests/bpfd.io_xdpprograms.yaml, operators/bpfd-operator/0.2.0/metadata/annotations.yaml, operators/bpfd-operator/0.2.0/tests/scorecard/config.yaml
Add the bpfd operator to the Openshift operator catalog.  This commit adds the version v0.2.0 manifests.
Please see [our website](https://bpfd.netlify.app/) for more information or reach out to [#bpfd](https://kubernetes.slack.com/archives/C04UJBW2553) in K8s slack with any questions.
-- …
=> operator bpfd-operator (0.2.0)

operators/neuvector-community-operator/1.3.9/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.9/neuvector-operator.v1.3.9.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
* [xHave you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
-- …
=> operator neuvector-community-operator (1.3.9)

operators/deployment-validation-operator/0.5.0/manifests/deploymentvalidationoperator-service.yaml, operators/deployment-validation-operator/0.5.0/manifests/deploymentvalidationoperator.0.5.0.clusterserviceversion.yaml, operators/deployment-validation-operator/0.5.0/metadata/annotations.yaml, operators/deployment-validation-operator/0.5.0/tests/scorecard/config.yaml
=> operator deployment-validation-operator (0.5.0)

operators/project-quay/3.9.0-nightly.20230524/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230524/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230524 to community operators
=> operator project-quay (3.9.0-nightly.20230524)

operators/project-quay/3.9.0-nightly.20230525/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230525/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230525 to community operators
=> operator project-quay (3.9.0-nightly.20230525)

operators/gitlab-operator-kubernetes/0.19.3/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.19.3/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.3/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.19.3/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.19.3)

operators/cluster-manager/0.11.0/cluster-manager.clusterserviceversion.yaml, operators/cluster-manager/0.11.0/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/cluster-manger.package.yaml
=> operator cluster-manager (0.11.0)

operators/external-secrets-operator/0.8.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.3/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.3/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.3/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.3/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.3/metadata/annotations.yaml, operators/external-secrets-operator/0.8.3/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.3
=> operator external-secrets-operator (0.8.3)

operators/project-quay/3.9.0-nightly.20230526/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230526/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230526 to community operators
=> operator project-quay (3.9.0-nightly.20230526)

operators/project-quay/3.8.7/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.7/quayecosystems.crd.yaml, operators/project-quay/3.8.7/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.7 to community operators
=> operator project-quay (3.8.7)

operators/project-quay/3.9.0-nightly.20230527/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230527/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230527 to community operators
=> operator project-quay (3.9.0-nightly.20230527)

operators/project-quay/3.9.0-nightly.20230528/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230528/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230528 to community operators
=> operator project-quay (3.9.0-nightly.20230528)

operators/mariadb-operator/0.15.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.15.1/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.15.1/metadata/annotations.yaml, operators/mariadb-operator/0.15.1/tests/scorecard/config.yaml
Add operator mariadb-operator (0.15.1) to community operators
=> operator mariadb-operator (0.15.1)

operators/project-quay/3.8.8/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.8/quayecosystems.crd.yaml, operators/project-quay/3.8.8/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.8.8 to community operators
=> operator project-quay (3.8.8)

operators/gitlab-operator-kubernetes/0.19.4/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.19.4/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.19.4/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.19.4/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.19.4)

operators/project-quay/3.9.0-nightly.20230529/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230529/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230529 to community operators
=> operator project-quay (3.9.0-nightly.20230529)

operators/project-quay/3.9.0-nightly.20230530/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230530/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230530 to community operators
=> operator project-quay (3.9.0-nightly.20230530)

operators/project-quay/3.9.0-nightly.20230531/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230531/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230531 to community operators
=> operator project-quay (3.9.0-nightly.20230531)

operators/kuadrant-operator/0.3.0/bundle.Dockerfile, operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml, operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml, operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kuadrant-operator/0.3.0/manifests/kuadrant-operator.clusterserviceversion.yaml, operators/kuadrant-operator/0.3.0/manifests/kuadrant.io_authpolicies.yaml, operators/kuadrant-operator/0.3.0/manifests/kuadrant.io_kuadrants.yaml, operators/kuadrant-operator/0.3.0/manifests/kuadrant.io_ratelimitpolicies.yaml, operators/kuadrant-operator/0.3.0/metadata/annotations.yaml, operators/kuadrant-operator/0.3.0/metadata/dependencies.yaml, operators/kuadrant-operator/0.3.0/tests/scorecard/config.yaml
=> operator kuadrant-operator (0.3.0)

operators/patterns-operator/0.0.15/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.15/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.15/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.15/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.15/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.15/metadata/annotations.yaml, operators/patterns-operator/0.0.15/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.15)

operators/patterns-operator/0.0.16/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.16/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.16/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.16/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.16/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.16/metadata/annotations.yaml, operators/patterns-operator/0.0.16/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.16)

operators/project-quay/3.9.0-nightly.20230602/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230602/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230602 to community operators
=> operator project-quay (3.9.0-nightly.20230602)

operators/kuadrant-operator/0.3.1/bundle.Dockerfile, operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml, operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml, operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kuadrant-operator/0.3.1/manifests/kuadrant-operator.clusterserviceversion.yaml, operators/kuadrant-operator/0.3.1/manifests/kuadrant.io_authpolicies.yaml, operators/kuadrant-operator/0.3.1/manifests/kuadrant.io_kuadrants.yaml, operators/kuadrant-operator/0.3.1/manifests/kuadrant.io_ratelimitpolicies.yaml, operators/kuadrant-operator/0.3.1/metadata/annotations.yaml, operators/kuadrant-operator/0.3.1/metadata/dependencies.yaml, operators/kuadrant-operator/0.3.1/tests/scorecard/config.yaml
=> operator kuadrant-operator (0.3.1)

operators/kube-green/0.5.1/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.5.1/manifests/kube-green-manager-config_v1_configmap.yaml, operators/kube-green/0.5.1/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.5.1/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.5.1/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.5.1/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.5.1/metadata/annotations.yaml, operators/kube-green/0.5.1/tests/scorecard/config.yaml
upgrade kube-green to version 0.5.1
=> operator kube-green (0.5.1)

operators/project-quay/3.9.0-nightly.20230603/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230603/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230603 to community operators
=> operator project-quay (3.9.0-nightly.20230603)

operators/rabbitmq-messaging-topology-operator/1.11.0/bundle.Dockerfile, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_bindings.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_exchanges.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_federations.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_permissions.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_policies.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_queues.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_schemareplications.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_shovels.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_superstreams.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_topicpermissions.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_users.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.com_vhosts.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-messaging-topology-operator/1.11.0/metadata/annotations.yaml
=> operator rabbitmq-messaging-topology-operator (1.11.0)

operators/project-quay/3.9.0-nightly.20230605/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230605/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230605 to community operators
=> operator project-quay (3.9.0-nightly.20230605)

operators/tempo-operator/0.2.0/bundle.Dockerfile, operators/tempo-operator/0.2.0/manifests/tempo-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/tempo-operator/0.2.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, operators/tempo-operator/0.2.0/manifests/tempo-operator-manager-config_v1_configmap.yaml, operators/tempo-operator/0.2.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tempo-operator/0.2.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/tempo-operator/0.2.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/tempo-operator/0.2.0/manifests/tempo-operator-webhook-service_v1_service.yaml, operators/tempo-operator/0.2.0/manifests/tempo-operator.clusterserviceversion.yaml, operators/tempo-operator/0.2.0/manifests/tempo.grafana.com_tempostacks.yaml, operators/tempo-operator/0.2.0/metadata/annotations.yaml, operators/tempo-operator/0.2.0/tests/scorecard/config.yaml, operators/tempo-operator/ci.yaml
=> operator [CI] tempo-operator (0.2.0)

operators/tempo-operator/ci.yaml
=> operator [CI] tempo-operator

operators/pelorus-operator/0.0.7/manifests/charts.pelorus.dora-metrics.io_peloruses.yaml, operators/pelorus-operator/0.0.7/manifests/pelorus-operator-controller-manager-metrics-service_v1_service.yaml, operators/pelorus-operator/0.0.7/manifests/pelorus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pelorus-operator/0.0.7/manifests/pelorus-operator.clusterserviceversion.yaml, operators/pelorus-operator/0.0.7/metadata/annotations.yaml, operators/pelorus-operator/0.0.7/metadata/properties.yaml, operators/pelorus-operator/0.0.7/tests/scorecard/config.yaml
This pull request was created automatically after merging new version of [Pelorus](https://github.com/dora-metrics/pelorus)
Please review it
- @etsauer
- @KevinMGranger
- @mateusoliveira43
- @mpryc
- @weshayutin
After review, comment `/unhold` in This PR to merge it.
=> operator pelorus-operator (0.0.7)

operators/netobserv-operator/1.0.3/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/1.0.3/manifests/netobserv-webhook-service_v1_service.yaml, operators/netobserv-operator/1.0.3/metadata/annotations.yaml, operators/netobserv-operator/ci.yaml
=> operator [CI] netobserv-operator (1.0.3)

operators/project-quay/3.9.0-nightly.20230609/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230609/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230609 to community operators
=> operator project-quay (3.9.0-nightly.20230609)

operators/gitlab-operator-kubernetes/0.20.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.20.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.20.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.20.0)

operators/gitlab-operator-kubernetes/0.20.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.20.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.20.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.20.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.20.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.20.1)

operators/cockroachdb/6.0.0/bundle.Dockerfile, operators/cockroachdb/6.0.0/manifests/charts.operatorhub.io_cockroachdbs.yaml, operators/cockroachdb/6.0.0/manifests/cockroachdb-controller-manager-metrics-service_v1_service.yaml, operators/cockroachdb/6.0.0/manifests/cockroachdb-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cockroachdb/6.0.0/manifests/cockroachdb.clusterserviceversion.yaml, operators/cockroachdb/6.0.0/metadata/annotations.yaml, operators/cockroachdb/6.0.0/tests/scorecard/config.yaml
=> operator cockroachdb (6.0.0)

operators/eclipse-amlen-operator/1.0.1/bundle.Dockerfile, operators/eclipse-amlen-operator/1.0.1/manifests/amlen-controller-manager-metrics-service_v1_service.yaml, operators/eclipse-amlen-operator/1.0.1/manifests/amlen-manager-config_v1_configmap.yaml, operators/eclipse-amlen-operator/1.0.1/manifests/amlen-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/eclipse-amlen-operator/1.0.1/manifests/eclipse-amlen-operator.clusterserviceversion.yaml, operators/eclipse-amlen-operator/1.0.1/manifests/eclipse.org_amlens.yaml, operators/eclipse-amlen-operator/1.0.1/metadata/annotations.yaml, operators/eclipse-amlen-operator/1.0.1/tests/scorecard/config.yaml
N/A
<s>* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?</s> ci.yaml already exists
-- …
=> operator eclipse-amlen-operator (1.0.1)

operators/codeflare-operator/0.0.4/manifests/codeflare-operator-controller-manager-metrics-service_v1_service.yaml, operators/codeflare-operator/0.0.4/manifests/codeflare-operator-manager-config_v1_configmap.yaml, operators/codeflare-operator/0.0.4/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/0.0.4/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/0.0.4/manifests/codeflare-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/codeflare-operator/0.0.4/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/0.0.4/manifests/codeflare.codeflare.dev_instascales.yaml, operators/codeflare-operator/0.0.4/manifests/codeflare.codeflare.dev_mcads.yaml, operators/codeflare-operator/0.0.4/manifests/ibm.com_quotasubtrees.yaml, operators/codeflare-operator/0.0.4/manifests/mcad.ibm.com_appwrappers.yaml, operators/codeflare-operator/0.0.4/manifests/mcad.ibm.com_queuejobs.yaml, operators/codeflare-operator/0.0.4/manifests/mcad.ibm.com_schedulingspecs.yaml, operators/codeflare-operator/0.0.4/metadata/annotations.yaml, operators/codeflare-operator/0.0.4/tests/scorecard/config.yaml
=> operator codeflare-operator (0.0.4)

operators/project-quay/3.9.0-nightly.20230610/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230610/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230610 to community operators
=> operator project-quay (3.9.0-nightly.20230610)

operators/rabbitmq-cluster-operator/2.3.0/bundle.Dockerfile, operators/rabbitmq-cluster-operator/2.3.0/manifests/crds.yaml, operators/rabbitmq-cluster-operator/2.3.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-cluster-operator/2.3.0/metadata/annotations.yaml
=> operator rabbitmq-cluster-operator (2.3.0)

operators/project-quay/3.9.0-nightly.20230611/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230611/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230611 to community operators
=> operator project-quay (3.9.0-nightly.20230611)

operators/camel-k/1.12.1/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.12.1/manifests/camel-k.v1.12.1.clusterserviceversion.yaml, operators/camel-k/1.12.1/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.12.1/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.12.1/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.12.1/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.12.1/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.12.1/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.12.1/metadata/annotations.yaml, operators/camel-k/1.12.1/tests/scorecard/config.yaml
=> operator camel-k (1.12.1)

operators/gitlab-operator-kubernetes/0.20.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.20.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.20.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.20.2)

operators/gitlab-operator-kubernetes/0.20.3/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.20.3/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.3/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.20.3/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.20.3)

operators/gitlab-operator-kubernetes/0.20.4/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.20.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.20.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.20.4/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.4/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.20.4/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.20.4)

operators/project-quay/3.9.0-nightly.20230613/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230613/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230613 to community operators
=> operator project-quay (3.9.0-nightly.20230613)

operators/portworx-essentials/23.5.0/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/23.5.0/core_v1_storagenode_crd.yaml, operators/portworx-essentials/23.5.0/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operator portworx-essentials (23.5.0)

operators/sap-data-intelligence-observer-operator/0.0.4/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml, operators/sap-data-intelligence-observer-operator/0.0.4/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-data-intelligence-observer-operator/0.0.4/manifests/observer-operator.clusterserviceversion.yaml, operators/sap-data-intelligence-observer-operator/0.0.4/manifests/sdi.sap-redhat.io_sdiobservers.yaml, operators/sap-data-intelligence-observer-operator/0.0.4/metadata/annotations.yaml
=> operator sap-data-intelligence-observer-operator (0.0.4)

operators/ack-pipes-controller/ci.yaml
=> operator [CI] ack-pipes-controller

operators/project-quay/3.9.0-nightly.20230615/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230615/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add 3.9.0-nightly.20230615 to community operators
=> operator project-quay (3.9.0-nightly.20230615)

operators/maistraoperator/ci.yaml
And fix Daniel's username. Shame on you Daniel!
--
=> operator [CI] maistraoperator

operators/edp-keycloak-operator/1.16.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml, operators/edp-keycloak-operator/1.16.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakclients.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealms.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, operators/edp-keycloak-operator/1.16.0/manifests/v1.edp.epam.com_keycloaks.yaml, operators/edp-keycloak-operator/1.16.0/metadata/annotations.yaml, operators/edp-keycloak-operator/1.16.0/tests/scorecard/config.yaml
=> operator edp-keycloak-operator (1.16.0)

operators/cluster-aas-operator/0.1.0/manifests/cluster-aas-operator.clusterserviceversion.yaml
=> operator [O] cluster-aas-operator (0.1.0)

operators/windup-operator/0.0.16/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.16/manifests/windup.crd.yaml, operators/windup-operator/0.0.16/metadata/annotations.yaml
=> operator windup-operator (0.0.16)

operators/sap-data-intelligence-observer-operator/0.0.5/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml, operators/sap-data-intelligence-observer-operator/0.0.5/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-data-intelligence-observer-operator/0.0.5/manifests/observer-operator.clusterserviceversion.yaml, operators/sap-data-intelligence-observer-operator/0.0.5/manifests/sdi.sap-redhat.io_sdiobservers.yaml, operators/sap-data-intelligence-observer-operator/0.0.5/metadata/annotations.yaml
=> operator [R] sap-data-intelligence-observer-operator (0.0.5)

operators/sap-data-intelligence-observer-operator/0.0.4/manifests/observer-operator.clusterserviceversion.yaml
=> operator [O] sap-data-intelligence-observer-operator (0.0.4)

operators/multicluster-global-hub-operator/0.5.0/metadata/annotations.yaml, operators/multicluster-global-hub-operator/0.7.0-dev/metadata/annotations.yaml
=> operator [R] multicluster-global-hub-operator (0.5.0 0.7.0-dev)

operators/microcks/1.7.1/manifests/microcks-operator.v1.7.1.clusterserviceversion.yaml, operators/microcks/1.7.1/manifests/microcksinstall.crd.yaml, operators/microcks/1.7.1/metadata/annotations.yaml
=> operator microcks (1.7.1)

operators/verticadb-operator/1.11.1/manifests/vertica.com_eventtriggers.yaml, operators/verticadb-operator/1.11.1/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.11.1/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.11.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.11.1/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/verticadb-operator/1.11.1/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.11.1/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.11.1/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.11.1/metadata/annotations.yaml, operators/verticadb-operator/1.11.1/tests/scorecard/config.yaml
=> operator verticadb-operator (1.11.1)

operators/sap-data-intelligence-observer-operator/0.0.5/manifests/observer-operator.clusterserviceversion.yaml
=> operator [O] sap-data-intelligence-observer-operator (0.0.5)

operators/gitlab-operator-kubernetes/0.20.6/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.20.6/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.6/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.20.6/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.20.6)

operators/grafana-operator/5.0.0/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.0.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.0.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.0.0/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.0.0/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.0.0/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.0.0/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.0.0/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.0.0/metadata/annotations.yaml
=> operator grafana-operator (5.0.0)

operators/grafana-operator/5.0.1/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.0.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.0.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.0.1/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.0.1/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.0.1/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.0.1/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.0.1/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.0.1/metadata/annotations.yaml
=> operator grafana-operator (5.0.1)

operators/self-node-remediation/0.6.1/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation-manager-config_v1_configmap.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation-webhook-service_v1_service.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation.clusterserviceversion.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml, operators/self-node-remediation/0.6.1/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, operators/self-node-remediation/0.6.1/metadata/annotations.yaml, operators/self-node-remediation/0.6.1/tests/scorecard/config.yaml
=> operator self-node-remediation (0.6.1)

operators/gitlab-operator-kubernetes/0.20.5/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.20.5/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.20.5/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.20.5/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.20.5)

operators/external-secrets-operator/0.8.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.4/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.4/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.4/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.4/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.4/metadata/annotations.yaml, operators/external-secrets-operator/0.8.4/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.4
towards https://github.com/external-secrets/external-secrets/issues/2440
=> operator external-secrets-operator (0.8.4)

operators/external-secrets-operator/0.9.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.0/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.0/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.0/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.0/metadata/annotations.yaml, operators/external-secrets-operator/0.9.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.0
towards https://github.com/external-secrets/external-secrets/issues/2440
=> operator external-secrets-operator (0.9.0)

operators/gitlab-operator-kubernetes/0.21.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.21.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.21.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.21.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.21.0)

operators/cluster-relocation-operator/0.9.0/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.0/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.0/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.0/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.0/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.0/tests/scorecard/config.yaml, operators/cluster-relocation-operator/ci.yaml
=> operator [N] [CI] cluster-relocation-operator (0.9.0)

operators/dynatrace-operator/0.12.0/Dockerfile, operators/dynatrace-operator/0.12.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.12.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.12.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.12.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.12.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.12.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.12.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.12.0/metadata/annotations.yaml
=> operator dynatrace-operator (0.12.0)

operators/group-sync-operator/0.0.26/Dockerfile, operators/group-sync-operator/0.0.26/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.26/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.26/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.26/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.26/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.26/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.26/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.26/metadata/annotations.yaml, operators/group-sync-operator/0.0.26/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.26)

operators/grafana-operator/5.0.2/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.0.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.0.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.0.2/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.0.2/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.0.2/metadata/annotations.yaml
=> operator grafana-operator (5.0.2)

operators/cluster-aas-operator/0.1.1/manifests/argo_cd_cluser_rb.yaml, operators/cluster-aas-operator/0.1.1/manifests/argo_cd_cluster_role.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster-aas-operator-repo-bridge.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.1.1/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.1.1/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.1.1/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.1.1/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.1.1/manifests/clustertemplate.openshift.io_clustertemplatesetup.yaml, operators/cluster-aas-operator/0.1.1/manifests/clustertemplate.openshift.io_config.yaml, operators/cluster-aas-operator/0.1.1/metadata/annotations.yaml, operators/cluster-aas-operator/0.1.1/metadata/dependencies.yaml, operators/cluster-aas-operator/0.1.1/tests/scorecard/config.yaml
=> operator cluster-aas-operator (0.1.1)

operators/sap-data-intelligence-observer-operator/1.0.2/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml, operators/sap-data-intelligence-observer-operator/1.0.2/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-data-intelligence-observer-operator/1.0.2/manifests/observer-operator.clusterserviceversion.yaml, operators/sap-data-intelligence-observer-operator/1.0.2/manifests/sdi.sap-redhat.io_sdiobservers.yaml, operators/sap-data-intelligence-observer-operator/1.0.2/metadata/annotations.yaml
=> operator sap-data-intelligence-observer-operator (1.0.2)

operators/cluster-relocation-operator/0.9.1/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.1/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.1/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.1/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.1/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.1/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.1)

ci/pipeline-config-ocp.yaml
=> [ISV-3609] Disbale the package manifest format support.

operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-create-user-job_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-migrate-database-job_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-operator-controller-manager-metrics-service_v1_service.yaml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-operator.clusterserviceversion.yaml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-launcher-role_Role.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-launcher-rolebinding_RoleBinding.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-log-reader-role_Role.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-pod-log-reader-rolebinding_RoleBinding.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-postgresql_Role.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-postgresql_RoleBinding.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-postgresql_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-redis_Role.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-redis_RoleBinding.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-redis_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-scc-rolebinding_RoleBinding.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-scheduler_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-statsd_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-triggerer_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-webserver_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/airflow-helm-worker_ServiceAccount.yml, operators/airflow-helm-operator/0.0.1/manifests/workflow.apache.org_airflows.yaml, operators/airflow-helm-operator/0.0.1/metadata/annotations.yaml, operators/airflow-helm-operator/0.0.1/tests/scorecard/config.yaml, operators/airflow-helm-operator/ci.yaml
=> operator [N] [CI] airflow-helm-operator (0.0.1)

operators/cass-operator-community/1.16.0/manifests/cass-operator-manager-config_v1_configmap.yaml, operators/cass-operator-community/1.16.0/manifests/cass-operator-webhook-service_v1_service.yaml, operators/cass-operator-community/1.16.0/manifests/cass-operator.clusterserviceversion.yaml, operators/cass-operator-community/1.16.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml, operators/cass-operator-community/1.16.0/manifests/control.k8ssandra.io_cassandratasks.yaml, operators/cass-operator-community/1.16.0/metadata/annotations.yaml, operators/cass-operator-community/1.16.0/tests/scorecard/config.yaml
=> operator cass-operator-community (1.16.0)

operators/dell-csm-operator/1.2.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml, operators/dell-csm-operator/1.2.0/manifests/dell-csm-operator.v1.2.0.clusterserviceversion.yaml, operators/dell-csm-operator/1.2.0/metadata/annotations.yaml, operators/dell-csm-operator/1.2.0/tests/scorecard/config.yaml
=> operator dell-csm-operator (1.2.0)

operators/cluster-aas-operator/0.1.2/manifests/argo_cd_cluser_rb.yaml, operators/cluster-aas-operator/0.1.2/manifests/argo_cd_cluster_role.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster-aas-operator-repo-bridge.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.1.2/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.1.2/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.1.2/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.1.2/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.1.2/manifests/clustertemplate.openshift.io_clustertemplatesetup.yaml, operators/cluster-aas-operator/0.1.2/manifests/clustertemplate.openshift.io_config.yaml, operators/cluster-aas-operator/0.1.2/metadata/annotations.yaml, operators/cluster-aas-operator/0.1.2/metadata/dependencies.yaml, operators/cluster-aas-operator/0.1.2/tests/scorecard/config.yaml
=> operator cluster-aas-operator (0.1.2)

operators/gitlab-operator-kubernetes/0.21.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.21.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.21.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.21.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.21.1)

operators/dell-csi-operator/1.12.0/manifests/csiisilons.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.12.0/manifests/csipowermaxes.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.12.0/manifests/csipowermaxrevproxies.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.12.0/manifests/csipowerstores.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.12.0/manifests/csiunities.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.12.0/manifests/csivxflexoses.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.12.0/manifests/dell-csi-operator.v1.12.0.clusterserviceversion.yaml, operators/dell-csi-operator/1.12.0/metadata/annotations.yaml, operators/dell-csi-operator/1.12.0/tests/scorecard/config.yaml
=> operator dell-csi-operator (1.12.0)

operators/opendatahub-operator/1.7.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/1.7.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/1.7.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/1.7.0/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/1.7.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/1.7.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/1.7.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/1.7.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/1.7.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/1.7.0/metadata/annotations.yaml, operators/opendatahub-operator/1.7.0/tests/scorecard/config.yaml
=> operator opendatahub-operator (1.7.0)

operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-builder-config_v1_configmap.yaml, operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml, operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-manager-config_v1_configmap.yaml, operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sonataflow-operator/1.40.0/manifests/sonataflow-operator.clusterserviceversion.yaml, operators/sonataflow-operator/1.40.0/manifests/sonataflow.org_sonataflowbuilds.yaml, operators/sonataflow-operator/1.40.0/manifests/sonataflow.org_sonataflowplatforms.yaml, operators/sonataflow-operator/1.40.0/manifests/sonataflow.org_sonataflows.yaml, operators/sonataflow-operator/1.40.0/metadata/annotations.yaml, operators/sonataflow-operator/1.40.0/tests/scorecard/config.yaml
=> operator [N] sonataflow-operator (1.40.0)

operators/cluster-relocation-operator/0.9.2/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.2/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.2/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.2/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.2/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.2/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.2)

operators/external-secrets-operator/0.8.5/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.5/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.5/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.5/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.5/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.5/metadata/annotations.yaml, operators/external-secrets-operator/0.8.5/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.5
=> operator external-secrets-operator (0.8.5)

operators/external-secrets-operator/0.9.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.1/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.1/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.1/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.1/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.1/metadata/annotations.yaml, operators/external-secrets-operator/0.9.1/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.1
=> operator external-secrets-operator (0.9.1)

operators/codeflare-operator/0.0.5/manifests/codeflare-operator-manager-config_v1_configmap.yaml, operators/codeflare-operator/0.0.5/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/0.0.5/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/0.0.5/manifests/codeflare-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/codeflare-operator/0.0.5/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/0.0.5/manifests/codeflare.codeflare.dev_instascales.yaml, operators/codeflare-operator/0.0.5/manifests/codeflare.codeflare.dev_mcads.yaml, operators/codeflare-operator/0.0.5/manifests/ibm.com_quotasubtrees.yaml, operators/codeflare-operator/0.0.5/manifests/mcad.ibm.com_appwrappers.yaml, operators/codeflare-operator/0.0.5/manifests/mcad.ibm.com_queuejobs.yaml, operators/codeflare-operator/0.0.5/manifests/mcad.ibm.com_schedulingspecs.yaml, operators/codeflare-operator/0.0.5/metadata/annotations.yaml, operators/codeflare-operator/0.0.5/tests/scorecard/config.yaml
=> operator codeflare-operator (0.0.5)

operators/gitlab-operator-kubernetes/0.21.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.21.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.21.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.21.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.21.2)

operators/grafana-operator/5.1.0/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.1.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.1.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.1.0/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.1.0/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.1.0/metadata/annotations.yaml
=> operator grafana-operator (5.1.0)

operators/codeflare-operator/0.0.6/manifests/codeflare-operator-manager-config_v1_configmap.yaml, operators/codeflare-operator/0.0.6/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/0.0.6/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/0.0.6/manifests/codeflare-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/codeflare-operator/0.0.6/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/0.0.6/manifests/codeflare.codeflare.dev_instascales.yaml, operators/codeflare-operator/0.0.6/manifests/codeflare.codeflare.dev_mcads.yaml, operators/codeflare-operator/0.0.6/manifests/ibm.com_quotasubtrees.yaml, operators/codeflare-operator/0.0.6/manifests/mcad.ibm.com_appwrappers.yaml, operators/codeflare-operator/0.0.6/manifests/mcad.ibm.com_queuejobs.yaml, operators/codeflare-operator/0.0.6/manifests/mcad.ibm.com_schedulingspecs.yaml, operators/codeflare-operator/0.0.6/metadata/annotations.yaml, operators/codeflare-operator/0.0.6/tests/scorecard/config.yaml
=> operator codeflare-operator (0.0.6)

operators/cluster-relocation-operator/0.9.3/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.3/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.3/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.3/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.3/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.3/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.3)

operators/forklift-operator/2.4.2/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.4.2/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.4.2/metadata/annotations.yaml
=> operator forklift-operator (2.4.2)

operators/authorino-operator/0.8.0/bundle.Dockerfile, operators/authorino-operator/0.8.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.8.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.8.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.8.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.8.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.8.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml, operators/authorino-operator/0.8.0/manifests/authorino-operator-manager-config_v1_configmap.yaml, operators/authorino-operator/0.8.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.8.0/manifests/authorino-operator.clusterserviceversion.yaml, operators/authorino-operator/0.8.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.8.0/manifests/authorino.kuadrant.io_authconfigs.yaml, operators/authorino-operator/0.8.0/manifests/manager-config_v1_configmap.yaml, operators/authorino-operator/0.8.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml, operators/authorino-operator/0.8.0/metadata/annotations.yaml, operators/authorino-operator/0.8.0/tests/scorecard/config.yaml
=> operator authorino-operator (0.8.0)

operators/project-quay/3.9.0-nightly.20230711/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230711/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230711/metadata/annotations.yaml
Add 3.9.0-nightly.20230711 to community operators
=> operator project-quay (3.9.0-nightly.20230711)

operators/portworx-essentials/23.5.1/manifests/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/23.5.1/manifests/core_v1_storagenode_crd.yaml, operators/portworx-essentials/23.5.1/manifests/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/23.5.1/metadata/annotations.yaml
=> operator portworx-essentials (23.5.1)

operators/project-quay/3.9.0-nightly.20230712/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230712/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230712/metadata/annotations.yaml
Add 3.9.0-nightly.20230712 to community operators
=> operator project-quay (3.9.0-nightly.20230712)

operators/forklift-operator/2.4.2/manifests/forklift-operator.clusterserviceversion.yaml
=> operator [O] forklift-operator (2.4.2)

operators/grafana-operator/5.2.0/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.2.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.2.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.2.0/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.2.0/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.2.0/metadata/annotations.yaml
=> operator grafana-operator (5.2.0)

operators/project-quay/3.8.10/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.10/manifests/quayecosystems.crd.yaml, operators/project-quay/3.8.10/manifests/quayregistries.crd.yaml, operators/project-quay/3.8.10/metadata/annotations.yaml
Add 3.8.10 to community operators
=> operator project-quay (3.8.10)

operators/pubsubplus-eventbroker-operator/1.0.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml, operators/pubsubplus-eventbroker-operator/1.0.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml, operators/pubsubplus-eventbroker-operator/1.0.0/metadata/annotations.yaml, operators/pubsubplus-eventbroker-operator/1.0.0/tests/scorecard/config.yaml, operators/pubsubplus-eventbroker-operator/ci.yaml
=> operator [N] [CI] pubsubplus-eventbroker-operator (1.0.0)

operators/mariadb-operator/0.16.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.16.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.16.0/metadata/annotations.yaml, operators/mariadb-operator/0.16.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.16.0) to community operators
=> operator mariadb-operator (0.16.0)

operators/mariadb-operator/0.16.0/manifests/mariadb-operator.clusterserviceversion.yaml
Add operator mariadb-operator (0.16.0) to community operators
=> operator [O] mariadb-operator (0.16.0)

operators/project-quay/3.9.0-nightly.20230714/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230714/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230714/metadata/annotations.yaml
Add 3.9.0-nightly.20230714 to community operators
=> operator project-quay (3.9.0-nightly.20230714)

operators/spark-helm-operator/0.0.1/manifests/apachespark.apache.org_sparks.yaml, operators/spark-helm-operator/0.0.1/manifests/spark-helm-operator-controller-manager-metrics-service_v1_service.yaml, operators/spark-helm-operator/0.0.1/manifests/spark-helm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/spark-helm-operator/0.0.1/manifests/spark-helm-operator.clusterserviceversion.yaml, operators/spark-helm-operator/0.0.1/manifests/sparkoperator.k8s.io_scheduledsparkapplications.yaml, operators/spark-helm-operator/0.0.1/manifests/sparkoperator.k8s.io_sparkapplications.yaml, operators/spark-helm-operator/0.0.1/metadata/annotations.yaml, operators/spark-helm-operator/0.0.1/tests/scorecard/config.yaml, operators/spark-helm-operator/ci.yaml
Signed-off-by: Sid Kattoju <skattoju@redhat.com>
--
=> operator [N] [CI] spark-helm-operator (0.0.1)

operators/cluster-relocation-operator/0.9.5/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.5/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.5/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.5/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.5/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.5/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.5)

operators/loki-helm-operator/0.0.1/manifests/charts.example.com_lokis.yaml, operators/loki-helm-operator/0.0.1/manifests/loki-helm-operator-controller-manager-metrics-service_v1_service.yaml, operators/loki-helm-operator/0.0.1/manifests/loki-helm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/loki-helm-operator/0.0.1/manifests/loki-helm-operator.clusterserviceversion.yaml, operators/loki-helm-operator/0.0.1/metadata/annotations.yaml, operators/loki-helm-operator/0.0.1/tests/scorecard/config.yaml, operators/loki-helm-operator/ci.yaml
Signed-off-by: Sid Kattoju <skattoju@redhat.com>
--
=> operator [N] [CI] loki-helm-operator (0.0.1)

operators/spark-helm-operator/0.0.2/manifests/apachespark.apache.org_sparks.yaml, operators/spark-helm-operator/0.0.2/manifests/spark-helm-operator-controller-manager-metrics-service_v1_service.yaml, operators/spark-helm-operator/0.0.2/manifests/spark-helm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/spark-helm-operator/0.0.2/manifests/spark-helm-operator.clusterserviceversion.yaml, operators/spark-helm-operator/0.0.2/manifests/sparkoperator.k8s.io_scheduledsparkapplications.yaml, operators/spark-helm-operator/0.0.2/manifests/sparkoperator.k8s.io_sparkapplications.yaml, operators/spark-helm-operator/0.0.2/metadata/annotations.yaml, operators/spark-helm-operator/0.0.2/tests/scorecard/config.yaml
Signed-off-by: Sid Kattoju <skattoju@redhat.com>
--
=> operator [R] spark-helm-operator (0.0.2)

operators/ack-secretsmanager-controller/ci.yaml
=> operator [CI] ack-secretsmanager-controller

operators/sap-data-intelligence-observer-operator/1.0.3/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml, operators/sap-data-intelligence-observer-operator/1.0.3/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-data-intelligence-observer-operator/1.0.3/manifests/observer-operator.clusterserviceversion.yaml, operators/sap-data-intelligence-observer-operator/1.0.3/manifests/sdi.sap-redhat.io_sdiobservers.yaml, operators/sap-data-intelligence-observer-operator/1.0.3/metadata/annotations.yaml
=> operator sap-data-intelligence-observer-operator (1.0.3)

operators/project-quay/3.9.0-nightly.20230715/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230715/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230715/metadata/annotations.yaml
Add 3.9.0-nightly.20230715 to community operators
=> operator project-quay (3.9.0-nightly.20230715)

operators/project-quay/3.9.0-nightly.20230716/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230716/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230716/metadata/annotations.yaml
Add 3.9.0-nightly.20230716 to community operators
=> operator project-quay (3.9.0-nightly.20230716)

operators/mariadb-operator/0.17.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.17.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.17.0/metadata/annotations.yaml, operators/mariadb-operator/0.17.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.17.0) to community operators
=> operator mariadb-operator (0.17.0)

operators/sap-hana-express-operator/1.0.2/manifests/db.sap-redhat.io_hanaexpresses.yaml, operators/sap-hana-express-operator/1.0.2/manifests/sap-hana-express-operator-controller-manager-metrics-service_v1_service.yaml, operators/sap-hana-express-operator/1.0.2/manifests/sap-hana-express-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-hana-express-operator/1.0.2/manifests/sap-hana-express-operator.clusterserviceversion.yaml, operators/sap-hana-express-operator/1.0.2/metadata/annotations.yaml
=> operator [N] sap-hana-express-operator (1.0.2)

operators/project-quay/3.9.0-nightly.20230717/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230717/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230717/metadata/annotations.yaml
Add 3.9.0-nightly.20230717 to community operators
=> operator project-quay (3.9.0-nightly.20230717)

operators/cluster-relocation-operator/0.9.6/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.6/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.6/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.6/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.6/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.6/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.6)

operators/flux/2.0.1/manifests/alert.crd.yaml, operators/flux/2.0.1/manifests/bucket.crd.yaml, operators/flux/2.0.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/2.0.1/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/2.0.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/2.0.1/manifests/flux-edit-flux-system.clusterrole.yaml, operators/flux/2.0.1/manifests/flux-view-flux-system.clusterrole.yaml, operators/flux/2.0.1/manifests/flux.v2.0.1.clusterserviceversion.yaml, operators/flux/2.0.1/manifests/gitrepository.crd.yaml, operators/flux/2.0.1/manifests/helmchart.crd.yaml, operators/flux/2.0.1/manifests/helmrelease.crd.yaml, operators/flux/2.0.1/manifests/helmrepository.crd.yaml, operators/flux/2.0.1/manifests/imagepolicy.crd.yaml, operators/flux/2.0.1/manifests/imagerepository.crd.yaml, operators/flux/2.0.1/manifests/imageupdateautomation.crd.yaml, operators/flux/2.0.1/manifests/kustomization.crd.yaml, operators/flux/2.0.1/manifests/notification-controller.service.yaml, operators/flux/2.0.1/manifests/ocirepository.crd.yaml, operators/flux/2.0.1/manifests/provider.crd.yaml, operators/flux/2.0.1/manifests/receiver.crd.yaml, operators/flux/2.0.1/manifests/source-controller.service.yaml, operators/flux/2.0.1/manifests/webhook-receiver.service.yaml, operators/flux/2.0.1/metadata/annotations.yaml, operators/flux/ci.yaml
=> operator [CI] flux (2.0.1)

operators/patterns-operator/0.0.17/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.17/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.17/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.17/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.17/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.17/metadata/annotations.yaml, operators/patterns-operator/0.0.17/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.17)

operators/percona-xtradb-cluster-operator/1.13.0/manifests/percona-xtradb-cluster-operator.v1.13.0.clusterserviceversion.yaml, operators/percona-xtradb-cluster-operator/1.13.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.13.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.13.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.13.0/metadata/annotations.yaml
=> operator percona-xtradb-cluster-operator (1.13.0)

operators/cluster-aas-operator/0.1.3/manifests/argo_cd_cluser_rb.yaml, operators/cluster-aas-operator/0.1.3/manifests/argo_cd_cluster_role.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster-aas-operator-repo-bridge.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.1.3/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.1.3/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.1.3/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.1.3/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.1.3/manifests/clustertemplate.openshift.io_clustertemplatesetup.yaml, operators/cluster-aas-operator/0.1.3/manifests/clustertemplate.openshift.io_config.yaml, operators/cluster-aas-operator/0.1.3/metadata/annotations.yaml, operators/cluster-aas-operator/0.1.3/metadata/dependencies.yaml, operators/cluster-aas-operator/0.1.3/tests/scorecard/config.yaml
=> operator cluster-aas-operator (0.1.3)

operators/multicluster-global-hub-operator/0.7.0/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml, operators/multicluster-global-hub-operator/1.0.0-dev/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
=> operator [R] multicluster-global-hub-operator (0.7.0 1.0.0-dev)

operators/multicluster-global-hub-operator/1.0.0-dev/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
=> operator [O] multicluster-global-hub-operator (1.0.0-dev)

operators/opendatahub-operator/ci.yaml
=> operator [CI] opendatahub-operator

operators/project-quay/3.9.0-nightly.20230721/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230721/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230721/metadata/annotations.yaml
Add 3.9.0-nightly.20230721 to community operators
=> operator project-quay (3.9.0-nightly.20230721)

operators/mariadb-operator/0.18.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.18.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.18.0/metadata/annotations.yaml, operators/mariadb-operator/0.18.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.18.0) to community operators
=> operator mariadb-operator (0.18.0)

operators/kaoto-operator/0.0.6/manifests/designer.kaoto.io_kaotoes.yaml, operators/kaoto-operator/0.0.6/manifests/kaoto-backend_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kaoto-operator/0.0.6/manifests/kaoto-operator.v0.0.6.clusterserviceversion.yaml, operators/kaoto-operator/0.0.6/metadata/annotations.yaml, operators/kaoto-operator/0.0.6/tests/scorecard/config.yaml, operators/kaoto-operator/ci.yaml
=> operator [N] [CI] kaoto-operator (0.0.6)

operators/project-quay/3.9.0-nightly.20230722/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230722/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230722/metadata/annotations.yaml
Add 3.9.0-nightly.20230722 to community operators
=> operator project-quay (3.9.0-nightly.20230722)

operators/project-quay/3.9.0-nightly.20230723/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230723/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230723/metadata/annotations.yaml
Add 3.9.0-nightly.20230723 to community operators
=> operator project-quay (3.9.0-nightly.20230723)

operators/rabbitmq-cluster-operator/2.4.0/bundle.Dockerfile, operators/rabbitmq-cluster-operator/2.4.0/manifests/crds.yaml, operators/rabbitmq-cluster-operator/2.4.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-cluster-operator/2.4.0/metadata/annotations.yaml
=> operator rabbitmq-cluster-operator (2.4.0)

operators/gitlab-operator-kubernetes/0.22.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.22.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.22.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.22.0)

operators/project-quay/3.9.0-nightly.20230724/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230724/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230724/metadata/annotations.yaml
Add 3.9.0-nightly.20230724 to community operators
=> operator project-quay (3.9.0-nightly.20230724)

operators/opendatahub-operator/2.0.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/2.0.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/2.0.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/2.0.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, operators/opendatahub-operator/2.0.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, operators/opendatahub-operator/2.0.0/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/2.0.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/2.0.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/2.0.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/2.0.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/2.0.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/2.0.0/metadata/annotations.yaml, operators/opendatahub-operator/2.0.0/tests/scorecard/config.yaml
=> operator opendatahub-operator (2.0.0)

operators/opendatahub-operator/1.8.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/1.8.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/1.8.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/1.8.0/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/1.8.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/1.8.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/1.8.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/1.8.0/metadata/annotations.yaml, operators/opendatahub-operator/1.8.0/tests/scorecard/config.yaml
=> operator opendatahub-operator (1.8.0)

operators/kaoto-operator/0.0.7/manifests/designer.kaoto.io_kaotoes.yaml, operators/kaoto-operator/0.0.7/manifests/kaoto-backend_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kaoto-operator/0.0.7/manifests/kaoto-operator.0.0.7.clusterserviceversion.yaml, operators/kaoto-operator/0.0.7/metadata/annotations.yaml, operators/kaoto-operator/0.0.7/tests/scorecard/config.yaml
=> operator kaoto-operator (0.0.7)

operators/sailoperator/3.0.0-nightly-2023-01-01/manifests/istio-operator-metrics-service_v1_service.yaml, operators/sailoperator/3.0.0-nightly-2023-01-01/manifests/maistra.io_istiohelminstalls.yaml, operators/sailoperator/3.0.0-nightly-2023-01-01/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sailoperator/3.0.0-nightly-2023-01-01/manifests/sailoperator.clusterserviceversion.yaml, operators/sailoperator/3.0.0-nightly-2023-01-01/metadata/annotations.yaml, operators/sailoperator/3.0.0-nightly-2023-01-01/tests/scorecard/config.yaml, operators/sailoperator/ci.yaml
=> operator [N] [CI] sailoperator (3.0.0-nightly-2023-01-01)

operators/neuvector-community-operator/1.4.0/manifests/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.4.0/manifests/neuvector-operator.v1.4.0.clusterserviceversion.yaml, operators/neuvector-community-operator/1.4.0/metadata/annotations.yaml
=> operator neuvector-community-operator (1.4.0)

operators/grafana-operator/5.3.0/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.3.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.3.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.3.0/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.3.0/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.3.0/metadata/annotations.yaml
=> operator grafana-operator (5.3.0)

operators/deployment-validation-operator/0.6.0/manifests/deploymentvalidationoperator-service.yaml, operators/deployment-validation-operator/0.6.0/manifests/deploymentvalidationoperator.0.6.0.clusterserviceversion.yaml, operators/deployment-validation-operator/0.6.0/metadata/annotations.yaml, operators/deployment-validation-operator/0.6.0/tests/scorecard/config.yaml
=> operator deployment-validation-operator (0.6.0)

operators/dynatrace-operator/0.12.1/Dockerfile, operators/dynatrace-operator/0.12.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.12.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.12.1/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.12.1/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.12.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.12.1/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.12.1/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.12.1/metadata/annotations.yaml
=> operator dynatrace-operator (0.12.1)

operators/gitlab-operator-kubernetes/0.22.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.22.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.22.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.22.1)

operators/mariadb-operator/0.19.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.19.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.19.0/metadata/annotations.yaml, operators/mariadb-operator/0.19.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.19.0) to community operators
=> operator mariadb-operator (0.19.0)

operators/cluster-relocation-operator/0.9.7/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.7/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.7/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.7/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.7/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.7/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.7)

operators/ack-cloudwatch-controller/ci.yaml
=> operator [CI] ack-cloudwatch-controller

operators/loki-operator/0.4.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml, operators/loki-operator/0.4.0/manifests/loki-operator-manager-config_v1_configmap.yaml, operators/loki-operator/0.4.0/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/loki-operator/0.4.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/loki-operator/0.4.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/loki-operator/0.4.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/loki-operator/0.4.0/manifests/loki-operator-webhook-service_v1_service.yaml, operators/loki-operator/0.4.0/manifests/loki-operator.clusterserviceversion.yaml, operators/loki-operator/0.4.0/manifests/loki.grafana.com_alertingrules.yaml, operators/loki-operator/0.4.0/manifests/loki.grafana.com_lokistacks.yaml, operators/loki-operator/0.4.0/manifests/loki.grafana.com_recordingrules.yaml, operators/loki-operator/0.4.0/manifests/loki.grafana.com_rulerconfigs.yaml, operators/loki-operator/0.4.0/metadata/annotations.yaml, operators/loki-operator/0.4.0/tests/scorecard/config.yaml
=> operator loki-operator (0.4.0)

operators/bpfd-operator/ci.yaml
=> operator [CI] bpfd-operator

operators/windup-operator/0.0.17/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.17/manifests/windup.crd.yaml, operators/windup-operator/0.0.17/metadata/annotations.yaml
=> operator windup-operator (0.0.17)

operators/windup-operator/0.0.18/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.18/manifests/windup.crd.yaml, operators/windup-operator/0.0.18/metadata/annotations.yaml
=> operator windup-operator (0.0.18)

operators/windup-operator/0.0.19/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.19/manifests/windup.crd.yaml, operators/windup-operator/0.0.19/metadata/annotations.yaml
=> operator windup-operator (0.0.19)

operators/tempo-operator/0.3.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, operators/tempo-operator/0.3.0/manifests/tempo-operator-manager-config_v1_configmap.yaml, operators/tempo-operator/0.3.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tempo-operator/0.3.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/tempo-operator/0.3.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/tempo-operator/0.3.0/manifests/tempo-operator-webhook-service_v1_service.yaml, operators/tempo-operator/0.3.0/manifests/tempo-operator.clusterserviceversion.yaml, operators/tempo-operator/0.3.0/manifests/tempo.grafana.com_tempostacks.yaml, operators/tempo-operator/0.3.0/metadata/annotations.yaml, operators/tempo-operator/0.3.0/tests/scorecard/config.yaml
=> operator tempo-operator (0.3.0)

operators/gitlab-operator-kubernetes/0.22.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.22.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.22.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.22.2)

operators/verticadb-operator/1.11.2/manifests/vertica.com_eventtriggers.yaml, operators/verticadb-operator/1.11.2/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.11.2/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.11.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.11.2/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/verticadb-operator/1.11.2/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.11.2/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.11.2/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.11.2/metadata/annotations.yaml, operators/verticadb-operator/1.11.2/tests/scorecard/config.yaml
=> operator verticadb-operator (1.11.2)

operators/aqua/2022.4.13/bundle.Dockerfile, operators/aqua/2022.4.13/manifests/aqua-operator.v2022.4.13.clusterserviceversion.yaml, operators/aqua/2022.4.13/manifests/aquacloudconnector.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aqualightnings.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.13/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.13/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.13/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.13/metadata/annotations.yaml, operators/aqua/ci.yaml
=> operator [CI] aqua (2022.4.13)

operators/gitlab-operator-kubernetes/0.22.3/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.22.3/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.3/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.22.3/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.22.3)

operators/oci-ccm-operator/0.0.9/manifests/ccm.oraclecloud.com_ocicloudmanagers.yaml, operators/oci-ccm-operator/0.0.9/manifests/ccm.oraclecloud.com_ocicsidrivers.yaml, operators/oci-ccm-operator/0.0.9/manifests/oci-ccm-operator-controller-manager-metrics-service_v1_service.yaml, operators/oci-ccm-operator/0.0.9/manifests/oci-ccm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oci-ccm-operator/0.0.9/manifests/oci-ccm-operator.clusterserviceversion.yaml, operators/oci-ccm-operator/0.0.9/metadata/annotations.yaml, operators/oci-ccm-operator/0.0.9/tests/scorecard/config.yaml, operators/oci-ccm-operator/ci.yaml
=> operator [N] [CI] oci-ccm-operator (0.0.9)

operators/external-secrets-operator/0.8.6/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.6/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.6/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.6/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.6/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.6/metadata/annotations.yaml, operators/external-secrets-operator/0.8.6/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.6
=> operator external-secrets-operator (0.8.6)

operators/external-secrets-operator/0.9.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.2/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.2/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.2/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.2/metadata/annotations.yaml, operators/external-secrets-operator/0.9.2/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.2
=> operator external-secrets-operator (0.9.2)

operators/project-quay/3.9.0-nightly.20230812/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230812/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0-nightly.20230812/metadata/annotations.yaml
Add 3.9.0-nightly.20230812 to community operators
=> operator project-quay (3.9.0-nightly.20230812)

operators/project-quay/3.8.11/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.11/manifests/quayecosystems.crd.yaml, operators/project-quay/3.8.11/manifests/quayregistries.crd.yaml, operators/project-quay/3.8.11/metadata/annotations.yaml
Add 3.8.11 to community operators
=> operator project-quay (3.8.11)

operators/gitlab-operator-kubernetes/0.22.4/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.22.4/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.22.4/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.22.4/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.22.4)

operators/observability-operator/0.0.25/manifests/monitoring.rhobs_alertmanagerconfigs.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_alertmanagers.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_monitoringstacks.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_podmonitors.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_probes.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_prometheusagents.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_prometheuses.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_prometheusrules.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_scrapeconfigs.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_servicemonitors.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_thanosqueriers.yaml, operators/observability-operator/0.0.25/manifests/monitoring.rhobs_thanosrulers.yaml, operators/observability-operator/0.0.25/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml, operators/observability-operator/0.0.25/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml, operators/observability-operator/0.0.25/manifests/obo-prometheus-operator_v1_service.yaml, operators/observability-operator/0.0.25/manifests/observability-operator-alertmanager-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/observability-operator/0.0.25/manifests/observability-operator-prometheus-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/observability-operator/0.0.25/manifests/observability-operator-prometheus-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/observability-operator/0.0.25/manifests/observability-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/observability-operator/0.0.25/manifests/observability-operator.clusterserviceversion.yaml, operators/observability-operator/0.0.25/manifests/observability-operator_monitoring.coreos.com_v1_servicemonitor.yaml, operators/observability-operator/0.0.25/manifests/observability-operator_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/observability-operator/0.0.25/manifests/observability-operator_v1_service.yaml, operators/observability-operator/0.0.25/metadata/annotations.yaml, operators/observability-operator/0.0.25/tests/scorecard/config.yaml
=> operator observability-operator (0.0.25)

operators/sonataflow-operator/1.40.1/manifests/sonataflow-operator-builder-config_v1_configmap.yaml, operators/sonataflow-operator/1.40.1/manifests/sonataflow-operator-controller-manager-metrics-service_v1_service.yaml, operators/sonataflow-operator/1.40.1/manifests/sonataflow-operator-manager-config_v1_configmap.yaml, operators/sonataflow-operator/1.40.1/manifests/sonataflow-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sonataflow-operator/1.40.1/manifests/sonataflow-operator.clusterserviceversion.yaml, operators/sonataflow-operator/1.40.1/manifests/sonataflow.org_sonataflowbuilds.yaml, operators/sonataflow-operator/1.40.1/manifests/sonataflow.org_sonataflowplatforms.yaml, operators/sonataflow-operator/1.40.1/manifests/sonataflow.org_sonataflows.yaml, operators/sonataflow-operator/1.40.1/metadata/annotations.yaml, operators/sonataflow-operator/1.40.1/tests/scorecard/config.yaml, operators/sonataflow-operator/ci.yaml
=> operator [CI] sonataflow-operator (1.40.1)

operators/move2kube-operator/0.3.8/bundle.Dockerfile, operators/move2kube-operator/0.3.8/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml, operators/move2kube-operator/0.3.8/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/move2kube-operator/0.3.8/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, operators/move2kube-operator/0.3.8/manifests/move2kube-operator.clusterserviceversion.yaml, operators/move2kube-operator/0.3.8/manifests/move2kube.konveyor.io_move2kubes.yaml, operators/move2kube-operator/0.3.8/metadata/annotations.yaml, operators/move2kube-operator/0.3.8/tests/scorecard/config.yaml, operators/move2kube-operator/ci.yaml
* [ x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ x] Have you tested your Operator with all Custom Resource Definitions?
* [x ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x ] Have you considered whether you want to use [semantic versioning …
=> operator [N] [CI] move2kube-operator (0.3.8)

operators/project-quay/3.9.0/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.0/metadata/annotations.yaml
Add 3.10.0-nightly.20230815 to community operators
=> operator project-quay (3.9.0)

operators/external-secrets-operator/0.8.7/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.8.7/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.8.7/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.8.7/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.8.7/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.8.7/metadata/annotations.yaml, operators/external-secrets-operator/0.8.7/tests/scorecard/config.yaml
bump external-secrets-operator 0.8.7
=> operator external-secrets-operator (0.8.7)

operators/external-secrets-operator/0.9.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.3/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.3/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.3/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.3/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.3/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.3/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.3/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.3/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.3/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.3/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.3/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.3/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.3/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.3/metadata/annotations.yaml, operators/external-secrets-operator/0.9.3/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.3
=> operator external-secrets-operator (0.9.3)

operators/awx-operator/2.5.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.5.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.5.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.5.0/manifests/awx-operator.v2.5.0.clusterserviceversion.yaml, operators/awx-operator/2.5.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.5.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.5.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.5.0/metadata/annotations.yaml, operators/awx-operator/2.5.0/tests/scorecard/config.yaml
=> operator awx-operator (2.5.0)

operators/forklift-operator/ci.yaml
=> operator [CI] forklift-operator

operators/forklift-operator/2.5.0/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.5.0/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.5.0/metadata/annotations.yaml
=> operator forklift-operator (2.5.0)

operators/argocd-operator/ci.yaml
=> operator [CI] argocd-operator

operators/tempo-operator/0.4.0/bundle.Dockerfile, operators/tempo-operator/0.4.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, operators/tempo-operator/0.4.0/manifests/tempo-operator-manager-config_v1_configmap.yaml, operators/tempo-operator/0.4.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tempo-operator/0.4.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/tempo-operator/0.4.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/tempo-operator/0.4.0/manifests/tempo-operator-webhook-service_v1_service.yaml, operators/tempo-operator/0.4.0/manifests/tempo-operator.clusterserviceversion.yaml, operators/tempo-operator/0.4.0/manifests/tempo.grafana.com_tempostacks.yaml, operators/tempo-operator/0.4.0/metadata/annotations.yaml, operators/tempo-operator/0.4.0/tests/scorecard/config.yaml
=> operator tempo-operator (0.4.0)

operators/pulsar-resources-operator/0.4.0-rc/bundle.Dockerfile, operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator-manager-config_v1_configmap.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/pulsar-resources-operator.clusterserviceversion.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsarconnections.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsargeoreplications.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsarnamespaces.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsarpermissions.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsartenants.yaml, operators/pulsar-resources-operator/0.4.0-rc/manifests/resource.streamnative.io_pulsartopics.yaml, operators/pulsar-resources-operator/0.4.0-rc/metadata/annotations.yaml, operators/pulsar-resources-operator/0.4.0-rc/tests/scorecard/config.yaml
=> operator [N] pulsar-resources-operator (0.4.0-rc)

operators/dynatrace-operator/0.13.0/Dockerfile, operators/dynatrace-operator/0.13.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.13.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.13.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.13.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.13.0/metadata/annotations.yaml
=> operator dynatrace-operator (0.13.0)

operators/project-quay/3.10.0-nightly.20230818/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230818/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230818/metadata/annotations.yaml
Add 3.10.0-nightly.20230818 to community operators
=> operator project-quay (3.10.0-nightly.20230818)

operators/project-quay/3.10.0-nightly.20230819/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230819/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230819/metadata/annotations.yaml
Add 3.10.0-nightly.20230819 to community operators
=> operator project-quay (3.10.0-nightly.20230819)

operators/project-quay/3.10.0-nightly.20230821/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230821/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230821/metadata/annotations.yaml
Add 3.10.0-nightly.20230821 to community operators
=> operator project-quay (3.10.0-nightly.20230821)

operators/pelorus-operator/0.0.8/manifests/charts.pelorus.dora-metrics.io_peloruses.yaml, operators/pelorus-operator/0.0.8/manifests/pelorus-operator-controller-manager-metrics-service_v1_service.yaml, operators/pelorus-operator/0.0.8/manifests/pelorus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pelorus-operator/0.0.8/manifests/pelorus-operator.clusterserviceversion.yaml, operators/pelorus-operator/0.0.8/metadata/annotations.yaml, operators/pelorus-operator/0.0.8/metadata/properties.yaml, operators/pelorus-operator/0.0.8/tests/scorecard/config.yaml
This pull request was created automatically after merging new version of [Pelorus](https://github.com/dora-metrics/pelorus)
Please review it
- @etsauer
- @KevinMGranger
- @mateusoliveira43
- @mpryc
- @weshayutin
After review, comment `/unhold` in This PR to merge it.
=> operator pelorus-operator (0.0.8)

operators/project-quay/3.10.0-nightly.20230822/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230822/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230822/metadata/annotations.yaml
Add 3.10.0-nightly.20230822 to community operators
=> operator project-quay (3.10.0-nightly.20230822)

operators/windup-operator/0.0.20/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.20/manifests/windup.crd.yaml, operators/windup-operator/0.0.20/metadata/annotations.yaml
=> operator windup-operator (0.0.20)

operators/ack-route53resolver-controller/ci.yaml
=> operator [CI] ack-route53resolver-controller

operators/project-quay/3.10.0-nightly.20230823/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230823/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230823/metadata/annotations.yaml
Add 3.10.0-nightly.20230823 to community operators
=> operator project-quay (3.10.0-nightly.20230823)

operators/move2kube-operator/0.3.9/bundle.Dockerfile, operators/move2kube-operator/0.3.9/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml, operators/move2kube-operator/0.3.9/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/move2kube-operator/0.3.9/manifests/move2kube-operator.clusterserviceversion.yaml, operators/move2kube-operator/0.3.9/manifests/move2kube.konveyor.io_move2kubes.yaml, operators/move2kube-operator/0.3.9/metadata/annotations.yaml, operators/move2kube-operator/0.3.9/tests/scorecard/config.yaml
* [y] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [y] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [y] Have you tested your Operator with all Custom Resource Definitions?
* [y] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [y] Have you considered whether you want to use [semantic versioning …
=> operator move2kube-operator (0.3.9)

operators/kubernetes-imagepuller-operator/1.0.6/manifests/che.eclipse.org_kubernetesimagepullers.yaml, operators/kubernetes-imagepuller-operator/1.0.6/manifests/controller-manager-metrics-service_v1_service.yaml, operators/kubernetes-imagepuller-operator/1.0.6/manifests/kubernetes-imagepuller-operator.v1.0.6.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/1.0.6/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubernetes-imagepuller-operator/1.0.6/metadata/annotations.yaml, operators/kubernetes-imagepuller-operator/1.0.6/tests/scorecard/config.yaml
=> operator kubernetes-imagepuller-operator (1.0.6)

operators/project-quay/3.10.0-nightly.20230824/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230824/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230824/metadata/annotations.yaml
Add 3.10.0-nightly.20230824 to community operators
=> operator project-quay (3.10.0-nightly.20230824)

operators/mongodb-atlas-kubernetes/1.8.2/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.8.2/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/atlas.mongodb.com_atlasdatafederations.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.8.2/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.8.2/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.8.2/tests/scorecard/config.yaml
=> operator mongodb-atlas-kubernetes (1.8.2)

operators/external-secrets-operator/0.9.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.4/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.4/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.4/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.4/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.4/metadata/annotations.yaml, operators/external-secrets-operator/0.9.4/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.4
=> operator external-secrets-operator (0.9.4)

operators/forklift-operator/2.5.0/manifests/forklift-operator.clusterserviceversion.yaml
=> operator [O] forklift-operator (2.5.0)

operators/opendatahub-operator/1.9.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/1.9.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/1.9.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/1.9.0/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/1.9.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/1.9.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/1.9.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/1.9.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/1.9.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/1.9.0/metadata/annotations.yaml, operators/opendatahub-operator/1.9.0/tests/scorecard/config.yaml, operators/opendatahub-operator/2.1.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/2.1.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/2.1.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/2.1.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, operators/opendatahub-operator/2.1.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/2.1.0/metadata/annotations.yaml, operators/opendatahub-operator/2.1.0/tests/scorecard/config.yaml
=> operator [R] opendatahub-operator (1.9.0 2.1.0)

operators/gitlab-operator-kubernetes/0.23.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.23.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.23.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.23.0)

ci/pipeline-config-ocp.yaml
The 4.14 GA is coming and new 4.15 should be available.
JIRA: ISV-3704
--
=> Add v4.15-rc ocp index version

operators/patterns-operator/0.0.18/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.18/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.18/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.18/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.18/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.18/metadata/annotations.yaml, operators/patterns-operator/0.0.18/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.18)

operators/windup-operator/0.0.21/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.21/manifests/windup.crd.yaml, operators/windup-operator/0.0.21/metadata/annotations.yaml
=> operator windup-operator (0.0.21)

operators/opendatahub-operator/2.1.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/2.1.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/2.1.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/2.1.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, operators/opendatahub-operator/2.1.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/2.1.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/2.1.0/metadata/annotations.yaml, operators/opendatahub-operator/2.1.0/tests/scorecard/config.yaml
=> operator opendatahub-operator (2.1.0)

operators/patterns-operator/0.0.19/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.19/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.19/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.19/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.19/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.19/metadata/annotations.yaml, operators/patterns-operator/0.0.19/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.19)

operators/neuvector-community-operator/1.4.1/manifests/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.4.1/manifests/neuvector-operator.v1.4.1.clusterserviceversion.yaml, operators/neuvector-community-operator/1.4.1/metadata/annotations.yaml
=> operator neuvector-community-operator (1.4.1)

operators/codeflare-operator/0.2.0/manifests/codeflare-operator-manager-config_v1_configmap.yaml, operators/codeflare-operator/0.2.0/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/0.2.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/0.2.0/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/0.2.0/manifests/codeflare.codeflare.dev_instascales.yaml, operators/codeflare-operator/0.2.0/manifests/codeflare.codeflare.dev_mcads.yaml, operators/codeflare-operator/0.2.0/manifests/ibm.com_quotasubtrees.yaml, operators/codeflare-operator/0.2.0/manifests/mcad.ibm.com_appwrappers.yaml, operators/codeflare-operator/0.2.0/manifests/mcad.ibm.com_schedulingspecs.yaml, operators/codeflare-operator/0.2.0/metadata/annotations.yaml, operators/codeflare-operator/0.2.0/tests/scorecard/config.yaml
=> operator codeflare-operator (0.2.0)

operators/codeflare-operator/0.2.1/manifests/codeflare-operator-manager-config_v1_configmap.yaml, operators/codeflare-operator/0.2.1/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/0.2.1/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/0.2.1/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/0.2.1/manifests/codeflare.codeflare.dev_instascales.yaml, operators/codeflare-operator/0.2.1/manifests/codeflare.codeflare.dev_mcads.yaml, operators/codeflare-operator/0.2.1/manifests/ibm.com_quotasubtrees.yaml, operators/codeflare-operator/0.2.1/manifests/mcad.ibm.com_appwrappers.yaml, operators/codeflare-operator/0.2.1/manifests/mcad.ibm.com_schedulingspecs.yaml, operators/codeflare-operator/0.2.1/metadata/annotations.yaml, operators/codeflare-operator/0.2.1/tests/scorecard/config.yaml
=> operator codeflare-operator (0.2.1)

operators/opendatahub-operator/2.1.0/metadata/annotations.yaml
=> operator [O] opendatahub-operator (2.1.0)

operators/ack-networkfirewall-controller/ci.yaml
=> operator [CI] ack-networkfirewall-controller

operators/edp-keycloak-operator/1.17.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml, operators/edp-keycloak-operator/1.17.0/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/edp-keycloak-operator/1.17.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakclients.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealms.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, operators/edp-keycloak-operator/1.17.0/manifests/v1.edp.epam.com_keycloaks.yaml, operators/edp-keycloak-operator/1.17.0/metadata/annotations.yaml, operators/edp-keycloak-operator/1.17.0/tests/scorecard/config.yaml
=> operator edp-keycloak-operator (1.17.0)

operators/mariadb-operator/0.20.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.20.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.20.0/metadata/annotations.yaml, operators/mariadb-operator/0.20.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.20.0) to community operators
=> operator mariadb-operator (0.20.0)

operators/patterns-operator/0.0.20/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.20/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.20/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.20/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.20/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.20/metadata/annotations.yaml, operators/patterns-operator/0.0.20/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.20)

operators/gitlab-operator-kubernetes/0.23.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.23.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.23.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.23.1)

operators/jaeger/ci.yaml
=> operator [CI] jaeger

operators/edp-keycloak-operator/1.17.1/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml, operators/edp-keycloak-operator/1.17.1/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/edp-keycloak-operator/1.17.1/manifests/edp-keycloak-operator.clusterserviceversion.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_clusterkeycloaks.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakauthflows.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakclients.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealms.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, operators/edp-keycloak-operator/1.17.1/manifests/v1.edp.epam.com_keycloaks.yaml, operators/edp-keycloak-operator/1.17.1/metadata/annotations.yaml, operators/edp-keycloak-operator/1.17.1/tests/scorecard/config.yaml
=> operator edp-keycloak-operator (1.17.1)

operators/patterns-operator/0.0.21/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.21/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.21/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.21/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.21/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.21/metadata/annotations.yaml, operators/patterns-operator/0.0.21/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.21)

operators/camel-k/2.0.1/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/manifests/camel-k.v2.0.1.clusterserviceversion.yaml, operators/camel-k/2.0.1/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/manifests/pipes.camel.apache.org.crd.yaml, operators/camel-k/2.0.1/metadata/annotations.yaml, operators/camel-k/2.0.1/tests/scorecard/config.yaml
=> operator camel-k (2.0.1)

operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-beta.1/manifests/pulp-operator.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-beta.1/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-beta.1/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-beta.1/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-beta.1/metadata/annotations.yaml, operators/pulp-operator/1.0.0-beta.1/tests/scorecard/config.yaml
=> operator pulp-operator (1.0.0-beta.1)

operators/grafana-operator/5.4.0/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.4.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.4.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.4.0/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.4.0/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.4.0/metadata/annotations.yaml
=> operator grafana-operator (5.4.0)

operators/kiali/1.73.0/bundle.Dockerfile, operators/kiali/1.73.0/manifests/kiali.crd.yaml, operators/kiali/1.73.0/manifests/kiali.v1.73.0.clusterserviceversion.yaml, operators/kiali/1.73.0/metadata/annotations.yaml
=> operator kiali (1.73.0)

operators/cluster-relocation-operator/0.9.8/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.8/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.8/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.8/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.8/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.8/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.8)

operators/project-quay/3.9.1/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.1/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.1/metadata/annotations.yaml
Add 3.9.1 to community operators
=> operator project-quay (3.9.1)

operators/cass-operator-community/1.17.1/manifests/cass-operator-manager-config_v1_configmap.yaml, operators/cass-operator-community/1.17.1/manifests/cass-operator-webhook-service_v1_service.yaml, operators/cass-operator-community/1.17.1/manifests/cass-operator.clusterserviceversion.yaml, operators/cass-operator-community/1.17.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml, operators/cass-operator-community/1.17.1/manifests/control.k8ssandra.io_cassandratasks.yaml, operators/cass-operator-community/1.17.1/metadata/annotations.yaml, operators/cass-operator-community/1.17.1/tests/scorecard/config.yaml
=> operator cass-operator-community (1.17.1)

operators/yaks/0.15.1/manifests/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.15.1/manifests/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.15.1/manifests/yaks.v0.15.1.clusterserviceversion.yaml, operators/yaks/0.15.1/metadata/annotations.yaml
=> operator yaks (0.15.1)

operators/netobserv-operator/1.0.4/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/1.0.4/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/1.0.4/manifests/netobserv-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/netobserv-operator/1.0.4/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/1.0.4/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/netobserv-operator/1.0.4/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/netobserv-operator/1.0.4/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/1.0.4/manifests/netobserv-webhook-service_v1_service.yaml, operators/netobserv-operator/1.0.4/metadata/annotations.yaml
=> operator netobserv-operator (1.0.4)

operators/project-quay/3.10.0-nightly.20230912/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230912/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230912/metadata/annotations.yaml
Add 3.10.0-nightly.20230912 to community operators
=> operator project-quay (3.10.0-nightly.20230912)

operators/grafana-operator/5.4.1/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.4.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.4.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.4.1/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.4.1/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.4.1/metadata/annotations.yaml
=> operator grafana-operator (5.4.1)

operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml, operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml, operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml, operators/beegfs-csi-driver-operator/1.5.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml, operators/beegfs-csi-driver-operator/1.5.0/metadata/annotations.yaml, operators/beegfs-csi-driver-operator/1.5.0/tests/scorecard/config.yaml, operators/beegfs-csi-driver-operator/ci.yaml
=> operator [CI] beegfs-csi-driver-operator (1.5.0)

operators/project-quay/3.8.12/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.12/manifests/quayecosystems.crd.yaml, operators/project-quay/3.8.12/manifests/quayregistries.crd.yaml, operators/project-quay/3.8.12/metadata/annotations.yaml
Add 3.8.12 to community operators
=> operator project-quay (3.8.12)

operators/portworx-essentials/23.7.0/manifests/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/23.7.0/manifests/core_v1_storagenode_crd.yaml, operators/portworx-essentials/23.7.0/manifests/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/23.7.0/metadata/annotations.yaml
=> operator portworx-essentials (23.7.0)

operators/awx-operator/2.5.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.5.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.5.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.5.1/manifests/awx-operator.v2.5.1.clusterserviceversion.yaml, operators/awx-operator/2.5.1/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.5.1/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.5.1/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.5.1/metadata/annotations.yaml, operators/awx-operator/2.5.1/tests/scorecard/config.yaml
=> operator awx-operator (2.5.1)

operators/gitlab-operator-kubernetes/0.23.3/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.23.3/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.3/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.23.3/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.23.3)

operators/project-quay/3.10.0-nightly.20230913/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230913/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230913/metadata/annotations.yaml
Add 3.10.0-nightly.20230913 to community operators
=> operator project-quay (3.10.0-nightly.20230913)

operators/self-node-remediation/0.7.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation-webhook-service_v1_service.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation.clusterserviceversion.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml, operators/self-node-remediation/0.7.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, operators/self-node-remediation/0.7.0/metadata/annotations.yaml, operators/self-node-remediation/0.7.0/tests/scorecard/config.yaml
=> operator self-node-remediation (0.7.0)

operators/project-quay/3.10.0-nightly.20230914/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230914/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230914/metadata/annotations.yaml
Add 3.10.0-nightly.20230914 to community operators
=> operator project-quay (3.10.0-nightly.20230914)

operators/patterns-operator/0.0.22/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.22/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.22/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.22/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.22/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.22/metadata/annotations.yaml, operators/patterns-operator/0.0.22/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.22)

operators/project-quay/3.10.0-nightly.20230915/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230915/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230915/metadata/annotations.yaml
Add 3.10.0-nightly.20230915 to community operators
=> operator project-quay (3.10.0-nightly.20230915)

operators/koku-metrics-operator/3.0.0/Dockerfile, operators/koku-metrics-operator/3.0.0/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/3.0.0/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/3.0.0/metadata/annotations.yaml, operators/koku-metrics-operator/3.0.0/tests/scorecard/config.yaml, operators/koku-metrics-operator/ci.yaml
This pr adds koku-metrics-operator  v3.0.0 to the OpenShift Operator Hub.
--
=> operator [CI] koku-metrics-operator (3.0.0)

operators/group-sync-operator/0.0.27/Dockerfile, operators/group-sync-operator/0.0.27/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.27/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.27/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.27/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.27/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.27/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.27/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.27/metadata/annotations.yaml, operators/group-sync-operator/0.0.27/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.27)

operators/awx-operator/2.5.2/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.5.2/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.5.2/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.5.2/manifests/awx-operator.v2.5.2.clusterserviceversion.yaml, operators/awx-operator/2.5.2/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.5.2/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.5.2/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.5.2/metadata/annotations.yaml, operators/awx-operator/2.5.2/tests/scorecard/config.yaml
=> operator awx-operator (2.5.2)

operators/awx-operator/2.5.3/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.5.3/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.5.3/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.5.3/manifests/awx-operator.v2.5.3.clusterserviceversion.yaml, operators/awx-operator/2.5.3/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.5.3/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.5.3/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.5.3/metadata/annotations.yaml, operators/awx-operator/2.5.3/tests/scorecard/config.yaml
=> operator awx-operator (2.5.3)

operators/project-quay/3.10.0-nightly.20230916/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230916/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230916/metadata/annotations.yaml
Add 3.10.0-nightly.20230916 to community operators
=> operator project-quay (3.10.0-nightly.20230916)

operators/project-quay/3.10.0-nightly.20230917/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230917/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230917/metadata/annotations.yaml
Add 3.10.0-nightly.20230917 to community operators
=> operator project-quay (3.10.0-nightly.20230917)

operators/patterns-operator/0.0.24/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.24/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.24/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.24/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.24/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.24/metadata/annotations.yaml, operators/patterns-operator/0.0.24/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.24)

operators/project-quay/3.10.0-nightly.20230918/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230918/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230918/metadata/annotations.yaml
Add 3.10.0-nightly.20230918 to community operators
=> operator project-quay (3.10.0-nightly.20230918)

operators/falcon-operator/0.5.1/manifests/falcon-operator.clusterserviceversion.yaml, operators/falcon-operator/0.5.1/metadata/annotations.yaml, operators/falcon-operator/0.5.2/manifests/falcon-operator.clusterserviceversion.yaml, operators/falcon-operator/0.5.2/metadata/annotations.yaml, operators/falcon-operator/0.5.3/manifests/falcon-operator.clusterserviceversion.yaml, operators/falcon-operator/0.5.3/metadata/annotations.yaml, operators/falcon-operator/0.5.4/manifests/falcon-operator.clusterserviceversion.yaml, operators/falcon-operator/0.5.4/metadata/annotations.yaml, operators/falcon-operator/0.5.5/manifests/falcon-operator.clusterserviceversion.yaml, operators/falcon-operator/0.5.5/metadata/annotations.yaml, operators/falcon-operator/ci.yaml
=> operator [R] [CI] falcon-operator (0.5.1 0.5.2 0.5.3 0.5.4 0.5.5)

operators/falcon-operator/0.8.1/manifests/falcon-operator-container-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/falcon-operator/0.8.1/manifests/falcon-operator-controller-manager-metrics-service_v1_service.yaml, operators/falcon-operator/0.8.1/manifests/falcon-operator-falconcontainer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/falcon-operator/0.8.1/manifests/falcon-operator-manager-config_v1_configmap.yaml, operators/falcon-operator/0.8.1/manifests/falcon-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/falcon-operator/0.8.1/manifests/falcon-operator-node-sensor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/falcon-operator/0.8.1/manifests/falcon-operator.clusterserviceversion.yaml, operators/falcon-operator/0.8.1/manifests/falcon.crowdstrike.com_falconcontainers.yaml, operators/falcon-operator/0.8.1/manifests/falcon.crowdstrike.com_falconnodesensors.yaml, operators/falcon-operator/0.8.1/metadata/annotations.yaml, operators/falcon-operator/0.8.1/tests/scorecard/config.yaml
=> operator falcon-operator (0.8.1)

operators/project-quay/3.10.0-nightly.20230919/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230919/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230919/metadata/annotations.yaml
Add 3.10.0-nightly.20230919 to community operators
=> operator project-quay (3.10.0-nightly.20230919)

operators/pubsubplus-eventbroker-operator/1.0.1/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml, operators/pubsubplus-eventbroker-operator/1.0.1/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml, operators/pubsubplus-eventbroker-operator/1.0.1/metadata/annotations.yaml, operators/pubsubplus-eventbroker-operator/1.0.1/tests/scorecard/config.yaml
=> operator pubsubplus-eventbroker-operator (1.0.1)

operators/cluster-relocation-operator/0.9.9/manifests/cluster-relocation-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-relocation-operator/0.9.9/manifests/cluster-relocation-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-relocation-operator/0.9.9/manifests/cluster-relocation-operator.clusterserviceversion.yaml, operators/cluster-relocation-operator/0.9.9/manifests/rhsyseng.github.io_clusterrelocations.yaml, operators/cluster-relocation-operator/0.9.9/metadata/annotations.yaml, operators/cluster-relocation-operator/0.9.9/tests/scorecard/config.yaml
=> operator cluster-relocation-operator (0.9.9)

operators/project-quay/3.10.0-nightly.20230920/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230920/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230920/metadata/annotations.yaml
Add 3.10.0-nightly.20230920 to community operators
=> operator project-quay (3.10.0-nightly.20230920)

operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml, operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator-webhook-service_v1_service.yaml, operators/node-maintenance-operator/0.16.0/manifests/node-maintenance-operator.clusterserviceversion.yaml, operators/node-maintenance-operator/0.16.0/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml, operators/node-maintenance-operator/0.16.0/metadata/annotations.yaml, operators/node-maintenance-operator/0.16.0/tests/scorecard/config.yaml
Let NMO v0.16.0 be available on OCP and OKD from v4.11
--
=> operator node-maintenance-operator (0.16.0)

operators/kubecost/1.106.0/manifests/kubecost-operator.clusterserviceversion.yaml
Signed-off-by: chipzoller <chipzoller@gmail.com>
This PR bumps the memory limit of the controller and sets CRD displayName and description allowing convenient display on the Install Operator page within OperatorHub.
--
<sup>2</sup> For more …
=> operator [O] kubecost (1.106.0)

operators/codeflare-operator/1.0.0-rc.1/manifests/codeflare-operator-manager-edit-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/codeflare-operator/1.0.0-rc.1/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/1.0.0-rc.1/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/1.0.0-rc.1/manifests/quota.codeflare.dev_quotasubtrees.yaml, operators/codeflare-operator/1.0.0-rc.1/manifests/workload.codeflare.dev_appwrappers.yaml, operators/codeflare-operator/1.0.0-rc.1/manifests/workload.codeflare.dev_schedulingspecs.yaml, operators/codeflare-operator/1.0.0-rc.1/metadata/annotations.yaml, operators/codeflare-operator/1.0.0-rc.1/tests/scorecard/config.yaml
=> operator codeflare-operator (1.0.0-rc.1)

operators/forklift-operator/2.5.1/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.5.1/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.5.1/metadata/annotations.yaml
=> operator forklift-operator (2.5.1)

operators/kubecost/1.97.0/metadata/annotations.yaml, operators/kubecost/1.99.0/metadata/annotations.yaml
Signed-off-by: chipzoller <chipzoller@gmail.com>
This PR updates earlier versions of the Kubecost operator to standardize on the "alpha" channel in hopes of displaying semvers correctly on OperatorHub.
-- …
=> operator [R] kubecost (1.97.0 1.99.0)

operators/project-quay/3.10.0-nightly.20230921/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230921/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230921/metadata/annotations.yaml
Add 3.10.0-nightly.20230921 to community operators
=> operator project-quay (3.10.0-nightly.20230921)

operators/external-secrets-operator/0.9.5/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.5/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.5/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.5/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.5/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.5/metadata/annotations.yaml, operators/external-secrets-operator/0.9.5/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.5
=> operator external-secrets-operator (0.9.5)

operators/gitlab-operator-kubernetes/0.23.4/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.23.4/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.23.4/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.23.4/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.23.4)

operators/project-quay/3.10.0-nightly.20230922/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230922/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230922/metadata/annotations.yaml
Add 3.10.0-nightly.20230922 to community operators
=> operator project-quay (3.10.0-nightly.20230922)

operators/snapscheduler/3.3.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml, operators/snapscheduler/3.3.0/manifests/snapscheduler-manager-config_v1_configmap.yaml, operators/snapscheduler/3.3.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/snapscheduler/3.3.0/manifests/snapscheduler.backube_snapshotschedules.yaml, operators/snapscheduler/3.3.0/manifests/snapscheduler.clusterserviceversion.yaml, operators/snapscheduler/3.3.0/metadata/annotations.yaml, operators/snapscheduler/3.3.0/tests/scorecard/config.yaml
=> operator snapscheduler (3.3.0)

operators/move2kube-operator/0.3.10-rc.0/bundle.Dockerfile, operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml, operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml, operators/move2kube-operator/0.3.10-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml, operators/move2kube-operator/0.3.10-rc.0/metadata/annotations.yaml, operators/move2kube-operator/0.3.10-rc.0/tests/scorecard/config.yaml
* [y] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [y] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [y] Have you tested your Operator with all Custom Resource Definitions?
* [y] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [y] Have you considered whether you want to use [semantic versioning …
=> operator move2kube-operator (0.3.10-rc.0)

operators/project-quay/3.10.0-nightly.20230923/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230923/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230923/metadata/annotations.yaml
Add 3.10.0-nightly.20230923 to community operators
=> operator project-quay (3.10.0-nightly.20230923)

operators/move2kube-operator/0.3.10/bundle.Dockerfile, operators/move2kube-operator/0.3.10/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml, operators/move2kube-operator/0.3.10/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/move2kube-operator/0.3.10/manifests/move2kube-operator.clusterserviceversion.yaml, operators/move2kube-operator/0.3.10/manifests/move2kube.konveyor.io_move2kubes.yaml, operators/move2kube-operator/0.3.10/metadata/annotations.yaml, operators/move2kube-operator/0.3.10/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.10
=> operator move2kube-operator (0.3.10)

operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-controller-manager-metrics-service_v1_service.yaml, operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-node-remediation-console-plugin_v1_service.yaml, operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-operator.clusterserviceversion.yaml, operators/node-healthcheck-operator/0.6.0/manifests/node-healthcheck-webhook-service_v1_service.yaml, operators/node-healthcheck-operator/0.6.0/manifests/remediation.medik8s.io_nodehealthchecks.yaml, operators/node-healthcheck-operator/0.6.0/metadata/annotations.yaml, operators/node-healthcheck-operator/0.6.0/metadata/dependencies.yaml, operators/node-healthcheck-operator/0.6.0/tests/scorecard/config.yaml, operators/node-healthcheck-operator/ci.yaml
* [n/a] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
-- …
=> operator [CI] node-healthcheck-operator (0.6.0)

operators/project-quay/3.10.0-nightly.20230925/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230925/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230925/metadata/annotations.yaml
Add 3.10.0-nightly.20230925 to community operators
=> operator project-quay (3.10.0-nightly.20230925)

operators/project-quay/3.10.0-nightly.20230926/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230926/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230926/metadata/annotations.yaml
Add 3.10.0-nightly.20230926 to community operators
=> operator project-quay (3.10.0-nightly.20230926)

operators/gitlab-operator-kubernetes/0.24.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.24.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.24.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.24.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.24.0)

operators/opendatahub-operator/1.10.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/1.10.0/manifests/dashboard.opendatahub.io_acceleratorprofiles.yaml, operators/opendatahub-operator/1.10.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/1.10.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/1.10.0/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/1.10.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/1.10.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/1.10.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/1.10.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/1.10.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/1.10.0/metadata/annotations.yaml, operators/opendatahub-operator/1.10.0/tests/scorecard/config.yaml, operators/opendatahub-operator/2.2.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, operators/opendatahub-operator/2.2.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, operators/opendatahub-operator/2.2.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/2.2.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/2.2.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/2.2.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/2.2.0/metadata/annotations.yaml, operators/opendatahub-operator/2.2.0/tests/scorecard/config.yaml
=> operator [R] opendatahub-operator (1.10.0 2.2.0)

operators/project-quay/3.10.0-nightly.20230928/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230928/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230928/metadata/annotations.yaml
Add 3.10.0-nightly.20230928 to community operators
=> operator project-quay (3.10.0-nightly.20230928)

operators/dapr-kubernetes-operator/0.0.4/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml, operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_components.yaml, operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_configurations.yaml, operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_httpendpoints.yaml, operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_resiliencies.yaml, operators/dapr-kubernetes-operator/0.0.4/manifests/dapr.io_subscriptions.yaml, operators/dapr-kubernetes-operator/0.0.4/manifests/operator.dapr.io_daprcontrolplanes.yaml, operators/dapr-kubernetes-operator/0.0.4/metadata/annotations.yaml, operators/dapr-kubernetes-operator/0.0.4/tests/scorecard/config.yaml
=> operator dapr-kubernetes-operator (0.0.4)

operators/project-quay/3.10.0-nightly.20230929/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230929/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230929/metadata/annotations.yaml
Add 3.10.0-nightly.20230929 to community operators
=> operator project-quay (3.10.0-nightly.20230929)

operators/limitador-operator/0.6.0/bundle.Dockerfile, operators/limitador-operator/0.6.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml, operators/limitador-operator/0.6.0/manifests/limitador-operator-manager-config_v1_configmap.yaml, operators/limitador-operator/0.6.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/limitador-operator/0.6.0/manifests/limitador-operator.clusterserviceversion.yaml, operators/limitador-operator/0.6.0/manifests/limitador.kuadrant.io_limitadors.yaml, operators/limitador-operator/0.6.0/metadata/annotations.yaml, operators/limitador-operator/0.6.0/tests/scorecard/config.yaml
Signed-off-by: dd di cesare didi@posteo.net
--
=> operator limitador-operator (0.6.0)

operators/project-quay/3.9.2/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.2/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.2/metadata/annotations.yaml
Add 3.9.2 to community operators
=> operator project-quay (3.9.2)

operators/project-quay/3.10.0-nightly.20230930/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20230930/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20230930/metadata/annotations.yaml
Add 3.10.0-nightly.20230930 to community operators
=> operator project-quay (3.10.0-nightly.20230930)

operators/project-quay/3.10.0-nightly.20231002/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231002/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231002/metadata/annotations.yaml
Add 3.10.0-nightly.20231002 to community operators
=> operator project-quay (3.10.0-nightly.20231002)

operators/deployment-validation-operator/0.7.0/manifests/deploymentvalidationoperator-service.yaml, operators/deployment-validation-operator/0.7.0/manifests/deploymentvalidationoperator.0.7.0.clusterserviceversion.yaml, operators/deployment-validation-operator/0.7.0/metadata/annotations.yaml, operators/deployment-validation-operator/0.7.0/tests/scorecard/config.yaml
=> operator deployment-validation-operator (0.7.0)

operators/gitlab-operator-kubernetes/0.24.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.24.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.24.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.24.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.24.1)

operators/project-quay/3.10.0-nightly.20230913/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.0-nightly.20230711/manifests/quay-operator.clusterserviceversion.yaml
@dmage this should fix the issue causing the failure in #3372
=> operator [R] project-quay (3.10.0-nightly.20230913 3.9.0-nightly.20230711)

operators/kubecost/1.106.2/bundle.Dockerfile, operators/kubecost/1.106.2/manifests/charts.kubecost.com_costanalyzers.yaml, operators/kubecost/1.106.2/manifests/kubecost-operator-controller-manager-metrics-service_v1_service.yaml, operators/kubecost/1.106.2/manifests/kubecost-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubecost/1.106.2/manifests/kubecost-operator.clusterserviceversion.yaml, operators/kubecost/1.106.2/metadata/annotations.yaml, operators/kubecost/1.106.2/tests/scorecard/config.yaml
Adds/bumps Kubecost operator to 1.106.2
--
=> operator kubecost (1.106.2)

operators/project-quay/3.10.0-nightly.20231005/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231005/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231005/metadata/annotations.yaml
Add 3.10.0-nightly.20231005 to community operators
=> operator project-quay (3.10.0-nightly.20231005)

operators/project-quay/3.10.0-nightly.20231006/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231006/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231006/metadata/annotations.yaml
Add 3.10.0-nightly.20231006 to community operators
=> operator project-quay (3.10.0-nightly.20231006)

operators/project-quay/3.10.0-nightly.20231007/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231007/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231007/metadata/annotations.yaml
Add 3.10.0-nightly.20231007 to community operators
=> operator project-quay (3.10.0-nightly.20231007)

operators/project-quay/3.10.0-nightly.20231008/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231008/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231008/metadata/annotations.yaml
Add 3.10.0-nightly.20231008 to community operators
=> operator project-quay (3.10.0-nightly.20231008)

operators/kube-green/0.5.2/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.5.2/manifests/kube-green-manager-config_v1_configmap.yaml, operators/kube-green/0.5.2/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.5.2/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.5.2/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.5.2/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.5.2/metadata/annotations.yaml, operators/kube-green/0.5.2/tests/scorecard/config.yaml
upgrade kube-green to version (0.5.2)
=> operator kube-green (0.5.2)

operators/project-quay/3.10.0-nightly.20231009/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231009/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231009/metadata/annotations.yaml
Add 3.10.0-nightly.20231009 to community operators
=> operator project-quay (3.10.0-nightly.20231009)

operators/cluster-manager/0.12.0/manifests/cluster-manager.clusterserviceversion.yaml, operators/cluster-manager/0.12.0/manifests/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/0.12.0/metadata/annotations.yaml
=> operator cluster-manager (0.12.0)

operators/klusterlet/0.12.0/manifests/klusterlet.clusterserviceversion.yaml, operators/klusterlet/0.12.0/manifests/operator.open-cluster-management.io_klusterlets.yaml, operators/klusterlet/0.12.0/metadata/annotations.yaml
=> operator klusterlet (0.12.0)

operators/cluster-manager/0.12.0/manifests/cluster-manager.clusterserviceversion.yaml
=> operator [O] cluster-manager (0.12.0)

operators/klusterlet/0.12.0/manifests/klusterlet.clusterserviceversion.yaml
=> operator [O] klusterlet (0.12.0)

operators/project-quay/3.10.0-nightly.20231010/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231010/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231010/metadata/annotations.yaml
Add 3.10.0-nightly.20231010 to community operators
=> operator project-quay (3.10.0-nightly.20231010)

operators/opendatahub-operator/1.10.1/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/1.10.1/manifests/dashboard.opendatahub.io_acceleratorprofiles.yaml, operators/opendatahub-operator/1.10.1/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/1.10.1/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/1.10.1/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/1.10.1/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/1.10.1/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/1.10.1/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/1.10.1/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/1.10.1/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/1.10.1/metadata/annotations.yaml, operators/opendatahub-operator/1.10.1/tests/scorecard/config.yaml, operators/opendatahub-operator/2.2.1/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, operators/opendatahub-operator/2.2.1/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, operators/opendatahub-operator/2.2.1/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/2.2.1/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/2.2.1/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/2.2.1/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/2.2.1/metadata/annotations.yaml, operators/opendatahub-operator/2.2.1/tests/scorecard/config.yaml
Signed-off-By: Vaishnavi Hire <vhire@redhat.com>
--
=> operator [R] opendatahub-operator (1.10.1 2.2.1)

operators/ack-cloudwatchlogs-controller/ci.yaml
=> operator [CI] ack-cloudwatchlogs-controller

operators/project-quay/3.10.0-nightly.20231011/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231011/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231011/metadata/annotations.yaml
Add 3.10.0-nightly.20231011 to community operators
=> operator project-quay (3.10.0-nightly.20231011)

operators/aqua/2022.4.13/manifests/aqua-operator.v2022.4.13.clusterserviceversion.yaml
=> operator [O] aqua (2022.4.13)

operators/mariadb-operator/0.21.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.21.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.21.0/metadata/annotations.yaml, operators/mariadb-operator/0.21.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.21.0) to community operators
=> operator mariadb-operator (0.21.0)

operators/ndmspc-operator/0.3.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.3.3/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.3.3/metadata/annotations.yaml, operators/ndmspc-operator/0.3.3/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.3.3)

operators/project-quay/3.10.0-nightly.20231012/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231012/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231012/metadata/annotations.yaml
Add 3.10.0-nightly.20231012 to community operators
=> operator project-quay (3.10.0-nightly.20231012)

operators/codeflare-operator/1.0.0-rc.2/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/1.0.0-rc.2/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/1.0.0-rc.2/manifests/quota.codeflare.dev_quotasubtrees.yaml, operators/codeflare-operator/1.0.0-rc.2/manifests/workload.codeflare.dev_appwrappers.yaml, operators/codeflare-operator/1.0.0-rc.2/manifests/workload.codeflare.dev_schedulingspecs.yaml, operators/codeflare-operator/1.0.0-rc.2/metadata/annotations.yaml, operators/codeflare-operator/1.0.0-rc.2/tests/scorecard/config.yaml
=> operator codeflare-operator (1.0.0-rc.2)

operators/project-quay/3.10.0-nightly.20231013/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231013/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231013/metadata/annotations.yaml
Add 3.10.0-nightly.20231013 to community operators
=> operator project-quay (3.10.0-nightly.20231013)

operators/forklift-operator/2.5.2/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.5.2/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.5.2/metadata/annotations.yaml
=> operator forklift-operator (2.5.2)

operators/dapr-kubernetes-operator/0.0.5/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml, operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_components.yaml, operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_configurations.yaml, operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_httpendpoints.yaml, operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_resiliencies.yaml, operators/dapr-kubernetes-operator/0.0.5/manifests/dapr.io_subscriptions.yaml, operators/dapr-kubernetes-operator/0.0.5/manifests/operator.dapr.io_daprcontrolplanes.yaml, operators/dapr-kubernetes-operator/0.0.5/metadata/annotations.yaml, operators/dapr-kubernetes-operator/0.0.5/tests/scorecard/config.yaml
=> operator dapr-kubernetes-operator (0.0.5)

operators/mariadb-operator/0.22.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb-operator.clusterserviceversion.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_backups.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_connections.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_databases.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_grants.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_mariadbs.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_restores.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_sqljobs.yaml, operators/mariadb-operator/0.22.0/manifests/mariadb.mmontes.io_users.yaml, operators/mariadb-operator/0.22.0/metadata/annotations.yaml, operators/mariadb-operator/0.22.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.22.0) to community operators
=> operator mariadb-operator (0.22.0)

operators/ndmspc-operator/0.4.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.4.0/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.4.0/metadata/annotations.yaml, operators/ndmspc-operator/0.4.0/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.4.0)

operators/project-quay/3.10.0-nightly.20231014/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.10.0-nightly.20231014/manifests/quayregistries.crd.yaml, operators/project-quay/3.10.0-nightly.20231014/metadata/annotations.yaml
Add 3.10.0-nightly.20231014 to community operators
=> operator project-quay (3.10.0-nightly.20231014)

operators/windup-operator/0.0.22/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.22/manifests/windup.crd.yaml, operators/windup-operator/0.0.22/metadata/annotations.yaml
=> operator windup-operator (0.0.22)

operators/ndmspc-operator/0.5.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml, operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml, operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml, operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ndmspc-operator/0.5.0/manifests/ndmspc-operator.clusterserviceversion.yaml, operators/ndmspc-operator/0.5.0/metadata/annotations.yaml, operators/ndmspc-operator/0.5.0/tests/scorecard/config.yaml
=> operator ndmspc-operator (0.5.0)

operators/external-secrets-operator/0.9.6/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.6/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.6/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.6/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.6/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.6/metadata/annotations.yaml, operators/external-secrets-operator/0.9.6/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.6
=> operator external-secrets-operator (0.9.6)

operators/awx-operator/2.6.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.6.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.6.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.6.0/manifests/awx-operator.v2.6.0.clusterserviceversion.yaml, operators/awx-operator/2.6.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.6.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.6.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.6.0/metadata/annotations.yaml, operators/awx-operator/2.6.0/tests/scorecard/config.yaml
=> operator awx-operator (2.6.0)

operators/sap-data-intelligence-observer-operator/1.0.4/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml, operators/sap-data-intelligence-observer-operator/1.0.4/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-data-intelligence-observer-operator/1.0.4/manifests/observer-operator.clusterserviceversion.yaml, operators/sap-data-intelligence-observer-operator/1.0.4/manifests/sdi.sap-redhat.io_sdiobservers.yaml, operators/sap-data-intelligence-observer-operator/1.0.4/metadata/annotations.yaml
=> operator sap-data-intelligence-observer-operator (1.0.4)

operators/dynatrace-operator/0.14.0/Dockerfile, operators/dynatrace-operator/0.14.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml, operators/dynatrace-operator/0.14.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.14.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.14.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.14.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.14.0/manifests/dynatrace.com_edgeconnects.yaml, operators/dynatrace-operator/0.14.0/metadata/annotations.yaml
=> operator dynatrace-operator (0.14.0)

operators/patterns-operator/0.0.25/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.25/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.25/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.25/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.25/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.25/metadata/annotations.yaml, operators/patterns-operator/0.0.25/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.25)

operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-beta.2/manifests/pulp-operator.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-beta.2/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-beta.2/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-beta.2/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-beta.2/metadata/annotations.yaml, operators/pulp-operator/1.0.0-beta.2/tests/scorecard/config.yaml
=> operator pulp-operator (1.0.0-beta.2)

operators/project-quay/3.8.13/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.13/manifests/quayecosystems.crd.yaml, operators/project-quay/3.8.13/manifests/quayregistries.crd.yaml, operators/project-quay/3.8.13/metadata/annotations.yaml
Add 3.8.13 to community operators
=> operator project-quay (3.8.13)

operators/awx-operator/2.7.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.7.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.7.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.7.0/manifests/awx-operator.v2.7.0.clusterserviceversion.yaml, operators/awx-operator/2.7.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.7.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.7.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.7.0/metadata/annotations.yaml, operators/awx-operator/2.7.0/tests/scorecard/config.yaml
=> operator awx-operator (2.7.0)

operators/neuvector-community-operator/1.4.2/manifests/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.4.2/manifests/neuvector-operator.v1.4.2.clusterserviceversion.yaml, operators/neuvector-community-operator/1.4.2/metadata/annotations.yaml
=> operator neuvector-community-operator (1.4.2)

operators/mongodb-atlas-kubernetes/1.9.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.9.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.9.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.9.0/tests/scorecard/config.yaml
=> operator mongodb-atlas-kubernetes (1.9.0)

operators/project-quay/3.9.3/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.3/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.3/metadata/annotations.yaml
Add 3.9.3 to community operators
=> operator project-quay (3.9.3)

operators/microcks/1.8.0/manifests/microcks-operator.v1.8.0.clusterserviceversion.yaml, operators/microcks/1.8.0/manifests/microcksinstall.crd.yaml, operators/microcks/1.8.0/metadata/annotations.yaml
=> operator microcks (1.8.0)

operators/koku-metrics-operator/3.0.1/Dockerfile, operators/koku-metrics-operator/3.0.1/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/3.0.1/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/3.0.1/metadata/annotations.yaml, operators/koku-metrics-operator/3.0.1/tests/scorecard/config.yaml
=> operator koku-metrics-operator (3.0.1)

operators/sn-operator/ci.yaml
=> operator [CI] sn-operator

operators/patterns-operator/0.0.26/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.26/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.26/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.26/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.26/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.26/metadata/annotations.yaml, operators/patterns-operator/0.0.26/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.26)

operators/patterns-operator/0.0.27/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.27/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.27/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.27/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.27/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.27/metadata/annotations.yaml, operators/patterns-operator/0.0.27/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.27)

operators/codeflare-operator/1.0.0-rc.3/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/1.0.0-rc.3/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/1.0.0-rc.3/manifests/quota.codeflare.dev_quotasubtrees.yaml, operators/codeflare-operator/1.0.0-rc.3/manifests/workload.codeflare.dev_appwrappers.yaml, operators/codeflare-operator/1.0.0-rc.3/manifests/workload.codeflare.dev_schedulingspecs.yaml, operators/codeflare-operator/1.0.0-rc.3/metadata/annotations.yaml, operators/codeflare-operator/1.0.0-rc.3/tests/scorecard/config.yaml
=> operator codeflare-operator (1.0.0-rc.3)

operators/external-secrets-operator/0.9.7/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.7/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.7/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.7/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.7/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.7/metadata/annotations.yaml, operators/external-secrets-operator/0.9.7/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.7
=> operator external-secrets-operator (0.9.7)

operators/gitlab-operator-kubernetes/0.25.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml, operators/gitlab-operator-kubernetes/0.25.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.25.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.25.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.25.0)

operators/authorino-operator/0.9.0/bundle.Dockerfile, operators/authorino-operator/0.9.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.9.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.9.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.9.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.9.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.9.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml, operators/authorino-operator/0.9.0/manifests/authorino-operator-manager-config_v1_configmap.yaml, operators/authorino-operator/0.9.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.9.0/manifests/authorino-operator.clusterserviceversion.yaml, operators/authorino-operator/0.9.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.9.0/manifests/authorino-webhooks_v1_service.yaml, operators/authorino-operator/0.9.0/manifests/authorino.kuadrant.io_authconfigs.yaml, operators/authorino-operator/0.9.0/manifests/manager-config_v1_configmap.yaml, operators/authorino-operator/0.9.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml, operators/authorino-operator/0.9.0/metadata/annotations.yaml, operators/authorino-operator/0.9.0/tests/scorecard/config.yaml, operators/authorino-operator/ci.yaml
Signed-off-by: Adam Cattermole acatterm@redhat.com
--
=> operator [CI] authorino-operator (0.9.0)

operators/patterns-operator/0.0.28/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.28/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.28/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.28/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.28/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.28/metadata/annotations.yaml, operators/patterns-operator/0.0.28/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.28)

operators/codeflare-operator/1.0.0-rc.4/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/1.0.0-rc.4/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/1.0.0-rc.4/manifests/quota.codeflare.dev_quotasubtrees.yaml, operators/codeflare-operator/1.0.0-rc.4/manifests/workload.codeflare.dev_appwrappers.yaml, operators/codeflare-operator/1.0.0-rc.4/manifests/workload.codeflare.dev_schedulingspecs.yaml, operators/codeflare-operator/1.0.0-rc.4/metadata/annotations.yaml, operators/codeflare-operator/1.0.0-rc.4/tests/scorecard/config.yaml
=> operator codeflare-operator (1.0.0-rc.4)

operators/patterns-operator/0.0.29/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.29/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.29/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.29/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.29/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.29/metadata/annotations.yaml, operators/patterns-operator/0.0.29/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.29)

operators/dynatrace-operator/0.14.1/Dockerfile, operators/dynatrace-operator/0.14.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml, operators/dynatrace-operator/0.14.1/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.14.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.14.1/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.14.1/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.14.1/manifests/dynatrace.com_edgeconnects.yaml, operators/dynatrace-operator/0.14.1/metadata/annotations.yaml
=> operator dynatrace-operator (0.14.1)

operators/awx-operator/2.7.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.7.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.7.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.7.1/manifests/awx-operator.v2.7.1.clusterserviceversion.yaml, operators/awx-operator/2.7.1/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.7.1/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.7.1/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.7.1/metadata/annotations.yaml, operators/awx-operator/2.7.1/tests/scorecard/config.yaml
=> operator awx-operator (2.7.1)

operators/self-node-remediation/0.7.1/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation-manager-config_v1_configmap.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation-webhook-service_v1_service.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation.clusterserviceversion.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml, operators/self-node-remediation/0.7.1/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, operators/self-node-remediation/0.7.1/metadata/annotations.yaml, operators/self-node-remediation/0.7.1/tests/scorecard/config.yaml
=> operator self-node-remediation (0.7.1)

operators/loki-operator/0.5.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml, operators/loki-operator/0.5.0/manifests/loki-operator-manager-config_v1_configmap.yaml, operators/loki-operator/0.5.0/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/loki-operator/0.5.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/loki-operator/0.5.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/loki-operator/0.5.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/loki-operator/0.5.0/manifests/loki-operator-webhook-service_v1_service.yaml, operators/loki-operator/0.5.0/manifests/loki-operator.clusterserviceversion.yaml, operators/loki-operator/0.5.0/manifests/loki.grafana.com_alertingrules.yaml, operators/loki-operator/0.5.0/manifests/loki.grafana.com_lokistacks.yaml, operators/loki-operator/0.5.0/manifests/loki.grafana.com_recordingrules.yaml, operators/loki-operator/0.5.0/manifests/loki.grafana.com_rulerconfigs.yaml, operators/loki-operator/0.5.0/metadata/annotations.yaml, operators/loki-operator/0.5.0/tests/scorecard/config.yaml
=> operator loki-operator (0.5.0)

operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml, operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-manager-config_v1_configmap.yaml, operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator-webhook-service_v1_service.yaml, operators/eginnovations-operator/0.0.6/manifests/eginnovations-operator.clusterserviceversion.yaml, operators/eginnovations-operator/0.0.6/manifests/eginnovations.com_eguniversalagents.yaml, operators/eginnovations-operator/0.0.6/metadata/annotations.yaml, operators/eginnovations-operator/0.0.6/tests/scorecard/config.yaml
=> operator eginnovations-operator (0.0.6)

operators/patterns-operator/0.0.30/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.30/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.30/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.30/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.30/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.30/metadata/annotations.yaml, operators/patterns-operator/0.0.30/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.30)

operators/kuadrant-operator/0.4.0/bundle.Dockerfile, operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml, operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml, operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kuadrant-operator/0.4.0/manifests/kuadrant-operator.clusterserviceversion.yaml, operators/kuadrant-operator/0.4.0/manifests/kuadrant.io_authpolicies.yaml, operators/kuadrant-operator/0.4.0/manifests/kuadrant.io_kuadrants.yaml, operators/kuadrant-operator/0.4.0/manifests/kuadrant.io_ratelimitpolicies.yaml, operators/kuadrant-operator/0.4.0/metadata/annotations.yaml, operators/kuadrant-operator/0.4.0/metadata/dependencies.yaml, operators/kuadrant-operator/0.4.0/tests/scorecard/config.yaml
=> operator kuadrant-operator (0.4.0)

operators/patterns-operator/0.0.31/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.31/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.31/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.31/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.31/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.31/metadata/annotations.yaml, operators/patterns-operator/0.0.31/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.31)

operators/patterns-operator/0.0.32/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.32/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.32/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.32/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.32/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.32/metadata/annotations.yaml, operators/patterns-operator/0.0.32/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.32)

operators/tempo-operator/0.5.0/bundle.Dockerfile, operators/tempo-operator/0.5.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-manager-config_v1_configmap.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator-webhook-service_v1_service.yaml, operators/tempo-operator/0.5.0/manifests/tempo-operator.clusterserviceversion.yaml, operators/tempo-operator/0.5.0/manifests/tempo.grafana.com_tempostacks.yaml, operators/tempo-operator/0.5.0/metadata/annotations.yaml, operators/tempo-operator/0.5.0/tests/scorecard/config.yaml
=> operator tempo-operator (0.5.0)

operators/mongodb-atlas-kubernetes/1.9.1/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/atlas.mongodb.com_atlasteams.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.9.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.9.1/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.9.1/tests/scorecard/config.yaml
=> operator mongodb-atlas-kubernetes (1.9.1)

operators/external-secrets-operator/0.9.8/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.9.8/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.9.8/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.9.8/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.9.8/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.9.8/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.9.8/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.9.8/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.9.8/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.9.8/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.9.8/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.9.8/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.9.8/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml, operators/external-secrets-operator/0.9.8/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.9.8/metadata/annotations.yaml, operators/external-secrets-operator/0.9.8/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.8
=> operator external-secrets-operator (0.9.8)

operators/codeflare-operator/1.0.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/1.0.0/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/1.0.0/manifests/quota.codeflare.dev_quotasubtrees.yaml, operators/codeflare-operator/1.0.0/manifests/workload.codeflare.dev_appwrappers.yaml, operators/codeflare-operator/1.0.0/manifests/workload.codeflare.dev_schedulingspecs.yaml, operators/codeflare-operator/1.0.0/metadata/annotations.yaml, operators/codeflare-operator/1.0.0/tests/scorecard/config.yaml
=> operator codeflare-operator (1.0.0)

operators/opendatahub-operator/1.11.0/manifests/console.openshift.io_odhquickstarts.yaml, operators/opendatahub-operator/1.11.0/manifests/dashboard.opendatahub.io_acceleratorprofiles.yaml, operators/opendatahub-operator/1.11.0/manifests/dashboard.opendatahub.io_odhapplications.yaml, operators/opendatahub-operator/1.11.0/manifests/dashboard.opendatahub.io_odhdocuments.yaml, operators/opendatahub-operator/1.11.0/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml, operators/opendatahub-operator/1.11.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/1.11.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/1.11.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/1.11.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/1.11.0/manifests/opendatahub.io_odhdashboardconfigs.yaml, operators/opendatahub-operator/1.11.0/metadata/annotations.yaml, operators/opendatahub-operator/1.11.0/tests/scorecard/config.yaml, operators/opendatahub-operator/2.3.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, operators/opendatahub-operator/2.3.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, operators/opendatahub-operator/2.3.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/2.3.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/2.3.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/2.3.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/2.3.0/metadata/annotations.yaml, operators/opendatahub-operator/2.3.0/scorecard/config.yaml, operators/opendatahub-operator/2.3.0/tests/scorecard/config.yaml
this is the same PR  https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3547 as but with a fix on top of it
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-l …
=> operator [R] opendatahub-operator (1.11.0 2.3.0)

operators/gitlab-operator-kubernetes/0.25.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml, operators/gitlab-operator-kubernetes/0.25.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.25.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.25.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.25.1)

operators/project-quay/3.9.4/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.4/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.4/metadata/annotations.yaml
Add 3.9.4 to community operators
=> operator project-quay (3.9.4)

operators/grafana-operator/5.4.2/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.4.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.4.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.4.2/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.4.2/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.4.2/metadata/annotations.yaml
=> operator grafana-operator (5.4.2)

operators/flink-kubernetes-operator/ci.yaml
=> operator [CI] flink-kubernetes-operator

operators/ack-cloudfront-controller/ci.yaml
=> operator [CI] ack-cloudfront-controller

operators/opendatahub-operator/2.4.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, operators/opendatahub-operator/2.4.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, operators/opendatahub-operator/2.4.0/manifests/dscinitialization.opendatahub.io_featuretrackers.yaml, operators/opendatahub-operator/2.4.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml, operators/opendatahub-operator/2.4.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml, operators/opendatahub-operator/2.4.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opendatahub-operator/2.4.0/manifests/opendatahub-operator.clusterserviceversion.yaml, operators/opendatahub-operator/2.4.0/metadata/annotations.yaml, operators/opendatahub-operator/2.4.0/scorecard/config.yaml, operators/opendatahub-operator/2.4.0/tests/scorecard/config.yaml
ref: https://github.com/opendatahub-io/opendatahub-community/issues/138
--
=> operator opendatahub-operator (2.4.0)

operators/multi-nic-cni-operator/1.2.2/bundle.Dockerfile, operators/multi-nic-cni-operator/1.2.2/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multi-nic-cni-operator.clusterserviceversion.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multinic.fms.io_cidrs.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multinic.fms.io_configs.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multinic.fms.io_deviceclasses.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multinic.fms.io_hostinterfaces.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multinic.fms.io_ippools.yaml, operators/multi-nic-cni-operator/1.2.2/manifests/multinic.fms.io_multinicnetworks.yaml, operators/multi-nic-cni-operator/1.2.2/metadata/annotations.yaml, operators/multi-nic-cni-operator/1.2.2/tests/scorecard/config.yaml
=> operator multi-nic-cni-operator (1.2.2)

operators/rabbitmq-messaging-topology-operator/1.12.1/bundle.Dockerfile, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_bindings.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_exchanges.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_federations.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_permissions.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_policies.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_queues.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_schemareplications.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_shovels.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_superstreams.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_topicpermissions.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_users.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.com_vhosts.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-messaging-topology-operator/1.12.1/metadata/annotations.yaml
=> operator rabbitmq-messaging-topology-operator (1.12.1)

operators/kuadrant-operator/0.4.1/bundle.Dockerfile, operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml, operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml, operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kuadrant-operator/0.4.1/manifests/kuadrant-operator.clusterserviceversion.yaml, operators/kuadrant-operator/0.4.1/manifests/kuadrant.io_authpolicies.yaml, operators/kuadrant-operator/0.4.1/manifests/kuadrant.io_kuadrants.yaml, operators/kuadrant-operator/0.4.1/manifests/kuadrant.io_ratelimitpolicies.yaml, operators/kuadrant-operator/0.4.1/metadata/annotations.yaml, operators/kuadrant-operator/0.4.1/metadata/dependencies.yaml, operators/kuadrant-operator/0.4.1/tests/scorecard/config.yaml
=> operator kuadrant-operator (0.4.1)

operators/portworx-essentials/23.10.0/manifests/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/23.10.0/manifests/core_v1_storagenode_crd.yaml, operators/portworx-essentials/23.10.0/manifests/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/23.10.0/metadata/annotations.yaml
=> operator portworx-essentials (23.10.0)

operators/move2kube-operator/0.3.11/bundle.Dockerfile, operators/move2kube-operator/0.3.11/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml, operators/move2kube-operator/0.3.11/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/move2kube-operator/0.3.11/manifests/move2kube-operator.clusterserviceversion.yaml, operators/move2kube-operator/0.3.11/manifests/move2kube.konveyor.io_move2kubes.yaml, operators/move2kube-operator/0.3.11/metadata/annotations.yaml, operators/move2kube-operator/0.3.11/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.11
=> operator move2kube-operator (0.3.11)

operators/awx-operator/2.7.2/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.7.2/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.7.2/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.7.2/manifests/awx-operator.v2.7.2.clusterserviceversion.yaml, operators/awx-operator/2.7.2/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.7.2/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.7.2/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.7.2/metadata/annotations.yaml, operators/awx-operator/2.7.2/tests/scorecard/config.yaml
=> operator awx-operator (2.7.2)

operators/eclipse-che/7.77.0/manifests/eclipse-che.v7.77.0.clusterserviceversion.yaml, operators/eclipse-che/7.77.0/manifests/org.eclipse.che_checlusters.yaml, operators/eclipse-che/7.77.0/metadata/annotations.yaml, operators/eclipse-che/7.77.0/metadata/dependencies.yaml, operators/eclipse-che/ci.yaml
=> operator [CI] eclipse-che (7.77.0)

operators/yaks/0.17.0/manifests/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.17.0/manifests/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.17.0/manifests/yaks.v0.17.0.clusterserviceversion.yaml, operators/yaks/0.17.0/metadata/annotations.yaml, operators/yaks/0.17.0/tests/scorecard/config.yaml
=> operator yaks (0.17.0)

operators/external-secrets-operator/ci.yaml
=> operator [CI] external-secrets-operator

operators/aqua/2022.4.14/manifests/aqua-operator.v2022.4.14.clusterserviceversion.yaml, operators/aqua/2022.4.14/manifests/aquacloudconnector.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aqualightnings.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.14/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.14/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.14/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.14/metadata/annotations.yaml
=> operator aqua (2022.4.14)

operators/cluster-relocation-operator/ci.yaml
=> operator [CI] cluster-relocation-operator

operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-controller-manager-metrics-service_v1_service.yaml, operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-node-remediation-console-plugin_v1_service.yaml, operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-operator.clusterserviceversion.yaml, operators/node-healthcheck-operator/0.6.1/manifests/node-healthcheck-webhook-service_v1_service.yaml, operators/node-healthcheck-operator/0.6.1/manifests/remediation.medik8s.io_nodehealthchecks.yaml, operators/node-healthcheck-operator/0.6.1/metadata/annotations.yaml, operators/node-healthcheck-operator/0.6.1/metadata/dependencies.yaml, operators/node-healthcheck-operator/0.6.1/tests/scorecard/config.yaml
* [n/a] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
-- …
=> operator node-healthcheck-operator (0.6.1)

operators/edp-keycloak-operator/1.18.2/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml, operators/edp-keycloak-operator/1.18.2/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/edp-keycloak-operator/1.18.2/manifests/edp-keycloak-operator.clusterserviceversion.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_clusterkeycloaks.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakauthflows.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakclients.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealms.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, operators/edp-keycloak-operator/1.18.2/manifests/v1.edp.epam.com_keycloaks.yaml, operators/edp-keycloak-operator/1.18.2/metadata/annotations.yaml, operators/edp-keycloak-operator/1.18.2/tests/scorecard/config.yaml
=> operator edp-keycloak-operator (1.18.2)

operators/yaks/0.17.1/manifests/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.17.1/manifests/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.17.1/manifests/yaks.v0.17.1.clusterserviceversion.yaml, operators/yaks/0.17.1/metadata/annotations.yaml, operators/yaks/0.17.1/tests/scorecard/config.yaml
=> operator yaks (0.17.1)

operators/dynatrace-operator/0.14.2/Dockerfile, operators/dynatrace-operator/0.14.2/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml, operators/dynatrace-operator/0.14.2/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.14.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.14.2/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.14.2/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.14.2/manifests/dynatrace.com_edgeconnects.yaml, operators/dynatrace-operator/0.14.2/metadata/annotations.yaml
=> operator dynatrace-operator (0.14.2)

operators/deployment-validation-operator/0.7.3/manifests/deploymentvalidationoperator-service.yaml, operators/deployment-validation-operator/0.7.3/manifests/deploymentvalidationoperator.0.7.3.clusterserviceversion.yaml, operators/deployment-validation-operator/0.7.3/metadata/annotations.yaml, operators/deployment-validation-operator/0.7.3/tests/scorecard/config.yaml
=> operator deployment-validation-operator (0.7.3)

operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml, operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator-webhook-service_v1_service.yaml, operators/node-maintenance-operator/0.16.1/manifests/node-maintenance-operator.clusterserviceversion.yaml, operators/node-maintenance-operator/0.16.1/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml, operators/node-maintenance-operator/0.16.1/metadata/annotations.yaml, operators/node-maintenance-operator/0.16.1/tests/scorecard/config.yaml
Let NMO v0.16.1 be available on OCP and OKD from v4.11
--
=> operator node-maintenance-operator (0.16.1)

operators/registry-operator/0.1.3/bundle.Dockerfile, operators/registry-operator/0.1.3/manifests/registry-operator-controller-manager-metrics-service_v1_service.yaml, operators/registry-operator/0.1.3/manifests/registry-operator-manager-config_v1_configmap.yaml, operators/registry-operator/0.1.3/manifests/registry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/registry-operator/0.1.3/manifests/registry-operator-webhook-service_v1_service.yaml, operators/registry-operator/0.1.3/manifests/registry-operator.clusterserviceversion.yaml, operators/registry-operator/0.1.3/manifests/registry.devfile.io_clusterdevfileregistrieslists.yaml, operators/registry-operator/0.1.3/manifests/registry.devfile.io_devfileregistries.yaml, operators/registry-operator/0.1.3/manifests/registry.devfile.io_devfileregistrieslists.yaml, operators/registry-operator/0.1.3/metadata/annotations.yaml, operators/registry-operator/0.1.3/tests/scorecard/config.yaml
=> operator [N] registry-operator (0.1.3)

operators/gitlab-operator-kubernetes/0.25.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml, operators/gitlab-operator-kubernetes/0.25.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.25.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.25.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.25.2)

operators/codeflare-operator/1.0.1/manifests/codeflare-operator-manager-metrics_v1_service.yaml, operators/codeflare-operator/1.0.1/manifests/codeflare-operator.clusterserviceversion.yaml, operators/codeflare-operator/1.0.1/manifests/quota.codeflare.dev_quotasubtrees.yaml, operators/codeflare-operator/1.0.1/manifests/workload.codeflare.dev_appwrappers.yaml, operators/codeflare-operator/1.0.1/manifests/workload.codeflare.dev_schedulingspecs.yaml, operators/codeflare-operator/1.0.1/metadata/annotations.yaml, operators/codeflare-operator/1.0.1/tests/scorecard/config.yaml
=> operator codeflare-operator (1.0.1)

operators/ack-acmpca-controller/ci.yaml
=> operator [CI] ack-acmpca-controller

operators/ack-drs-controller/ci.yaml
=> operator [CI] ack-drs-controller

operators/neuvector-community-operator/1.4.3/manifests/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.4.3/manifests/neuvector-operator.v1.4.3.clusterserviceversion.yaml, operators/neuvector-community-operator/1.4.3/metadata/annotations.yaml
=> operator neuvector-community-operator (1.4.3)

operators/gitlab-operator-kubernetes/0.26.0/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml, operators/gitlab-operator-kubernetes/0.26.0/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.26.0/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.26.0/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.26.0)

operators/project-quay/3.9.5/manifests/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.9.5/manifests/quayregistries.crd.yaml, operators/project-quay/3.9.5/metadata/annotations.yaml
Add 3.9.5 to community operators
=> operator project-quay (3.9.5)

operators/camel-k/2.1.0/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/manifests/camel-k.v2.1.0.clusterserviceversion.yaml, operators/camel-k/2.1.0/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/manifests/pipes.camel.apache.org.crd.yaml, operators/camel-k/2.1.0/metadata/annotations.yaml, operators/camel-k/2.1.0/tests/scorecard/config.yaml
=> operator camel-k (2.1.0)

operators/patterns-operator/0.0.33/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.33/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.33/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.33/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.33/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.33/metadata/annotations.yaml, operators/patterns-operator/0.0.33/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.33)

operators/argocd-operator/0.8.0/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml, operators/argocd-operator/0.8.0/manifests/argocd-operator-manager-config_v1_configmap.yaml, operators/argocd-operator/0.8.0/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/argocd-operator/0.8.0/manifests/argocd-operator-webhook-service_v1_service.yaml, operators/argocd-operator/0.8.0/manifests/argocd-operator.v0.8.0.clusterserviceversion.yaml, operators/argocd-operator/0.8.0/manifests/argoproj.io_applications.yaml, operators/argocd-operator/0.8.0/manifests/argoproj.io_applicationsets.yaml, operators/argocd-operator/0.8.0/manifests/argoproj.io_appprojects.yaml, operators/argocd-operator/0.8.0/manifests/argoproj.io_argocdexports.yaml, operators/argocd-operator/0.8.0/manifests/argoproj.io_argocds.yaml, operators/argocd-operator/0.8.0/metadata/annotations.yaml
=> operator argocd-operator (0.8.0)

operators/namespace-configuration-operator/1.2.5/Dockerfile, operators/namespace-configuration-operator/1.2.5/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.2.5/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.2.5/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.2.5/manifests/namespace-configuration-operator-metrics-service_v1_service.yaml, operators/namespace-configuration-operator/1.2.5/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/namespace-configuration-operator/1.2.5/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/namespace-configuration-operator/1.2.5/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.2.5/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.2.5/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.2.5/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.2.5/metadata/annotations.yaml, operators/namespace-configuration-operator/1.2.5/tests/scorecard/config.yaml
=> operator namespace-configuration-operator (1.2.5)

operators/awx-operator/2.8.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/2.8.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/2.8.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/2.8.0/manifests/awx-operator.v2.8.0.clusterserviceversion.yaml, operators/awx-operator/2.8.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/2.8.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/2.8.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/2.8.0/metadata/annotations.yaml, operators/awx-operator/2.8.0/tests/scorecard/config.yaml
=> operator awx-operator (2.8.0)

operators/grafana-operator/5.5.0/manifests/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/5.5.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/5.5.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml, operators/grafana-operator/5.5.0/manifests/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanadashboards.yaml, operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanadatasources.yaml, operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanafolders.yaml, operators/grafana-operator/5.5.0/manifests/grafana.integreatly.org_grafanas.yaml, operators/grafana-operator/5.5.0/metadata/annotations.yaml
=> operator grafana-operator (5.5.0)

operators/namespace-configuration-operator/1.2.6/Dockerfile, operators/namespace-configuration-operator/1.2.6/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.2.6/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.2.6/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.2.6/manifests/namespace-configuration-operator-metrics-service_v1_service.yaml, operators/namespace-configuration-operator/1.2.6/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/namespace-configuration-operator/1.2.6/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/namespace-configuration-operator/1.2.6/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.2.6/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.2.6/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.2.6/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.2.6/metadata/annotations.yaml, operators/namespace-configuration-operator/1.2.6/tests/scorecard/config.yaml
=> operator namespace-configuration-operator (1.2.6)

operators/portworx-essentials/23.10.1/manifests/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/23.10.1/manifests/core_v1_storagenode_crd.yaml, operators/portworx-essentials/23.10.1/manifests/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/23.10.1/metadata/annotations.yaml
=> operator portworx-essentials (23.10.1)
