operators/kiali/1.37.0/bundle.Dockerfile
operators/kiali/1.37.0/manifests/kiali.crd.yaml
operators/kiali/1.37.0/manifests/kiali.v1.37.0.clusterserviceversion.yaml
operators/kiali/1.37.0/metadata/annotations.yaml

operators kiali (1.37.0)

---

operators/sap-commerce-operator/0.0.2/bundle.Dockerfile
operators/sap-commerce-operator/0.0.2/manifests/hybris.hybris.org_hybrisapps.yaml
operators/sap-commerce-operator/0.0.2/manifests/hybris.hybris.org_hybrisbases.yaml
operators/sap-commerce-operator/0.0.2/manifests/sap-commerce-operator-hybris-controller-manager-metrics-service_v1_service.yaml
operators/sap-commerce-operator/0.0.2/manifests/sap-commerce-operator-manager-config_v1_configmap.yaml
operators/sap-commerce-operator/0.0.2/manifests/sap-commerce-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/sap-commerce-operator/0.0.2/manifests/sap-commerce-operator.clusterserviceversion.yaml
operators/sap-commerce-operator/0.0.2/metadata/annotations.yaml
operators/sap-commerce-operator/ci.yaml

Signed-off-by: Marco Yeung <myeung@redhat.com>
--

operators [N] [CI] sap-commerce-operator (0.0.2)

---

operators/etcd/0.6.1/etcdclusters.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.0/etcdbackups.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.0/etcdclusters.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.0/etcdrestores.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.2-clusterwide/etcdbackups.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.2-clusterwide/etcdclusters.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.2-clusterwide/etcdrestores.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.2/etcdbackups.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.2/etcdclusters.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.2/etcdrestores.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.4-clusterwide/etcdbackups.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.4-clusterwide/etcdclusters.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.4-clusterwide/etcdrestores.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.4/etcdbackups.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.4/etcdclusters.etcd.database.coreos.com.crd.yaml
operators/etcd/0.9.4/etcdrestores.etcd.database.coreos.com.crd.yaml

Substitute https://github.com/operator-framework/community-operators/pull/4146, a simple description as follows,
This `apiextensions.k8s.io/v1beta1` has been deprecated in OCP 4.9(K8s 1.22) according to the [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22). It leads to the etcd operator failed to install on OCP 4.9, so this PR updates the related CRD.

operators [R] etcd (0.6.1 0.9.0 0.9.2 0.9.2-clusterwide 0.9.4 0.9.4-clusterwide)

---

operators/assisted-service-operator/0.0.7/assisted-service-operator.clusterserviceversion.yaml

**Description**
Fix invalid range config in the distribution 0.0.7 by replacing `olm.skipRange: '>=0.0.0 <0.0.7'` with `olm.skipRange: '>=0.0.1 <0.0.7'` which is a valid range for this package. Note that the version 0.0.0 does not exist.

operators [O] assisted-service-operator (0.0.7)

---

operators/cert-manager/1.4.0/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.4.1/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.4.2/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.4.3/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.4.4/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.5.3/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.5.4/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.6.0/manifests/cert-manager.clusterserviceversion.yaml
operators/cert-manager/1.6.1/manifests/cert-manager.clusterserviceversion.yaml

This causes the operator to be displayed in OperatorHub in the web console on architectures other than x86_64.
Please let me know if there is a different way to add these; I didn't see a CSV upstream.
/cc @wallrj

operators [R] cert-manager (1.4.0 1.4.1 1.4.2 1.4.3 1.4.4 1.5.3 1.5.4 1.6.0 1.6.1)

---

operators/rhoas-operator/0.9.2/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml
operators/rhoas-operator/0.9.2/manifests/rhoas-operator.cloudservicesrequests.crd.yaml
operators/rhoas-operator/0.9.2/manifests/rhoas-operator.clusterserviceversion.yaml
operators/rhoas-operator/0.9.2/manifests/rhoas-operator.kafkaconnections.crd.yaml
operators/rhoas-operator/0.9.2/manifests/rhoas-operator.serviceregistryconnections.crd.yaml
operators/rhoas-operator/0.9.2/manifests/service-binding.clusterrole.yaml
operators/rhoas-operator/0.9.2/metadata/annotations.yaml

operators rhoas-operator (0.9.2)

---

ci/pipeline-config-ocp.yaml

disable 4.10 sync to allow OCP version release development

disable 4.10 to allow OCP version release develop

---

operators/tf-operator/0.0.1-2011/metadata/annotations.yaml
operators/tf-operator/1.0.0/metadata/annotations.yaml

@ivanvtimofeev, bundle label from `annotations.yaml` (v4.6-v.4.8) is in conflict with olm.properties (max v4.6) from clusterserviceversion. Please let me know if it is better to set bundle label to `=v.46` or raise `olm.maxOpenShiftVersion` to `v4.8`.

operators [R] tf-operator (0.0.1-2011 1.0.0)

---

operators/ack-lambda-controller/0.0.8/bundle.Dockerfile
operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-controller.clusterserviceversion.yaml
operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-metrics-service_v1_service.yaml
operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-reader_rbac.authorization.k8s.io_v1_role.yaml
operators/ack-lambda-controller/0.0.8/manifests/ack-lambda-writer_rbac.authorization.k8s.io_v1_role.yaml
operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_aliases.yaml
operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_codesigningconfigs.yaml
operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_eventsourcemappings.yaml
operators/ack-lambda-controller/0.0.8/manifests/lambda.services.k8s.aws_functions.yaml
operators/ack-lambda-controller/0.0.8/metadata/annotations.yaml
operators/ack-lambda-controller/0.0.8/tests/scorecard/config.yaml

After the release of ACK [lambda-controller:v0.0.8](https://gallery.ecr.aws/aws-controllers-k8s/lambda-controller), the automation job failed to generate the PR for the OLM bundle.
So I am manually raising these PR by following the instructions mentioned in the issue [here](https://github.com/aws-controllers-k8s/community/issues/1164)
NOTE: `CreateContainerConfigError` is expected since `ACK controllers` have pre-installation steps to create resources in a cluster before the manager pod can come up.

operators ack-lambda-controller (0.0.8)

---

operators/tidb-operator/1.3.1/backups.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/backupschedules.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/dmclusters.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/restores.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/tidb-operator.v1.3.1.clusterserviceversion.yaml
operators/tidb-operator/1.3.1/tidbclusterautoscalers.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/tidbclusters.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/tidbinitializers.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/tidbmonitors.pingcap.com.crd.yaml
operators/tidb-operator/1.3.1/tidbngmonitorings.pingcap.com.crd.yaml
operators/tidb-operator/ci.yaml
operators/tidb-operator/tidb-operator.package.yaml

Signed-off-by: Shiori <sihao.yu@pingcap.com>
--

operators [CI] tidb-operator (1.3.1)

---

operators/deployment-validation-operator/0.2.2/manifests/deploymentvalidationoperator.0.2.2.clusterserviceversion.yaml
operators/deployment-validation-operator/0.2.2/metadata/annotations.yaml
operators/deployment-validation-operator/0.2.2/tests/scorecard/config.yaml
operators/deployment-validation-operator/ci.yaml

The Deployment Validation Operator (DVO) checks deployments and other resources against a curated collection of best practices. 
These best practices focus mainly on ensuring that the applications are fault-tolerant.
DVO will only monitor Kubernetes resources and will not modify them in any way. As an operator it is a continuously running version of the static analysis tool Kube-linter [https://github.com/stackrox/kube-linter]. It will report failed validations via Prometheus, which will allow users of this operator to create alerts based on its results. All the metrics are gauges that will report `1` if the best-practice has failed. The metric will always have three parameters: `name`, `namespace` and `kind`. 
This operator doesn't define any CRDs at the moment. It has been bootstrapped …

operators [N] [CI] deployment-validation-operator (0.2.2)

---

ci/pipeline-config-ocp.yaml

Disabling temporary 4.11 update due to cleanup

Disabling temporary 4.11 update due to cleanup

---

ci/pipeline-config-ocp.yaml

Enable 4.11 after cleanup

---

ci/pipeline-config-ocp.yaml

Pipeline uses the last supported ose image

Pipeline uses the last supported ose image

---

ci/pipeline-config-ocp.yaml

Enable v4.12 as cleaned out index

Enable v4.12 as cleaned out index

---

operators/annotationlab/3.4.0/metadata/annotations.yaml
operators/annotationlab/4.1.2/metadata/annotations.yaml
operators/annotationlab/4.2.0/metadata/annotations.yaml
operators/annotationlab/4.2.1/metadata/annotations.yaml
operators/annotationlab/4.3.0/metadata/annotations.yaml
operators/annotationlab/4.4.0/metadata/annotations.yaml
operators/annotationlab/4.4.1/metadata/annotations.yaml

Dear @becash143, @skattoju,
Recently, there were some problem detecting correctly deprecation of api for k8s v1.25 (ocp v4.12) and we modified your annotations to limit some version of your operator for ocp `<v4.12`. This PR should revert this change. Please verify if your versions are working on `v4.12`. Please approve this change to be merged.
**Sorry for the inconvenience.**
Community operators team
Signed-off-by: Martin Vala <mavala@redhat.com>

operator [R] annotationlab (3.4.0 4.1.2 4.2.0 4.2.1 4.3.0 4.4.0 4.4.1)

---

operators/apicast-community-operator/0.7.1/bundle.Dockerfile
operators/apicast-community-operator/0.7.1/manifests/apicast-operator-controller-manager-metrics-service_v1_service.yaml
operators/apicast-community-operator/0.7.1/manifests/apicast-operator.clusterserviceversion.yaml
operators/apicast-community-operator/0.7.1/manifests/apps.3scale.net_apicasts.yaml
operators/apicast-community-operator/0.7.1/metadata/annotations.yaml
operators/apicast-community-operator/0.7.1/tests/scorecard/config.yaml

operator apicast-community-operator (0.7.1)

---

operators/deployment-validation-operator/0.4.0/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.4.0/manifests/deploymentvalidationoperator.0.4.0.clusterserviceversion.yaml
operators/deployment-validation-operator/0.4.0/metadata/annotations.yaml
operators/deployment-validation-operator/0.4.0/tests/scorecard/config.yaml
operators/deployment-validation-operator/ci.yaml

operator [CI] deployment-validation-operator (0.4.0)

---

operators/observability-operator/0.0.22/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_alertmanagers.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_monitoringstacks.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_podmonitors.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_probes.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_prometheusagents.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_prometheuses.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_prometheusrules.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_scrapeconfigs.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_servicemonitors.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_thanosqueriers.yaml
operators/observability-operator/0.0.22/manifests/monitoring.rhobs_thanosrulers.yaml
operators/observability-operator/0.0.22/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
operators/observability-operator/0.0.22/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
operators/observability-operator/0.0.22/manifests/obo-prometheus-operator_v1_service.yaml
operators/observability-operator/0.0.22/manifests/observability-operator-alertmanager-rules_monitoring.coreos.com_v1_prometheusrule.yaml
operators/observability-operator/0.0.22/manifests/observability-operator-prometheus-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
operators/observability-operator/0.0.22/manifests/observability-operator-prometheus-rules_monitoring.coreos.com_v1_prometheusrule.yaml
operators/observability-operator/0.0.22/manifests/observability-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
operators/observability-operator/0.0.22/manifests/observability-operator.clusterserviceversion.yaml
operators/observability-operator/0.0.22/manifests/observability-operator_monitoring.coreos.com_v1_servicemonitor.yaml
operators/observability-operator/0.0.22/manifests/observability-operator_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/observability-operator/0.0.22/manifests/observability-operator_v1_service.yaml
operators/observability-operator/0.0.22/metadata/annotations.yaml
operators/observability-operator/0.0.22/tests/scorecard/config.yaml
operators/observability-operator/ci.yaml

This PR ships 0.0.22 version of observability-Operator. observability-operator provides the ability to create multiple monitoring-stacks on OpenShift without conflicting with the in-cluster monitoring.
-- …

operator [N] [CI] observability-operator (0.0.22)

---

operators/apicurio-registry/1.1.0-v2.4.12.final/bundle.Dockerfile
operators/apicurio-registry/1.1.0-v2.4.12.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
operators/apicurio-registry/1.1.0-v2.4.12.final/manifests/registry.apicur.io_apicurioregistries.yaml
operators/apicurio-registry/1.1.0-v2.4.12.final/metadata/annotations.yaml
operators/apicurio-registry/1.1.0-v2.4.12.final/tests/scorecard/config.yaml

operator apicurio-registry (1.1.0-v2.4.12.final)

---

operators/ndmspc-operator/0.6.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/ndmspc-operator/0.6.0/manifests/ndmspc-operator.clusterserviceversion.yaml
operators/ndmspc-operator/0.6.0/metadata/annotations.yaml
operators/ndmspc-operator/0.6.0/tests/scorecard/config.yaml

operator ndmspc-operator (0.6.0)

---

operators/external-secrets-operator/ci.yaml

This PR updates the maintainers list of External Secrets Operator
WRT: https://github.com/k8s-operatorhub/community-operators/pull/3482

operator [CI] external-secrets-operator

---

operators/konveyor-operator/ci.yaml

Just switching to use semver-mode.

operator [CI] konveyor-operator

---

operators/tempo-operator/0.6.0/bundle.Dockerfile
operators/tempo-operator/0.6.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator-webhook-service_v1_service.yaml
operators/tempo-operator/0.6.0/manifests/tempo-operator.clusterserviceversion.yaml
operators/tempo-operator/0.6.0/manifests/tempo.grafana.com_tempostacks.yaml
operators/tempo-operator/0.6.0/metadata/annotations.yaml
operators/tempo-operator/0.6.0/tests/scorecard/config.yaml

Release tempo-operator `0.6.0`.

operator tempo-operator (0.6.0)

---

operators/grafana-operator/5.6.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
operators/grafana-operator/5.6.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/grafana-operator/5.6.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
operators/grafana-operator/5.6.0/manifests/grafana-operator.clusterserviceversion.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanafolders.yaml
operators/grafana-operator/5.6.0/manifests/grafana.integreatly.org_grafanas.yaml
operators/grafana-operator/5.6.0/metadata/annotations.yaml

operator grafana-operator (5.6.0)

---

operators/gitlab-operator-kubernetes/0.26.2/manifests/apps.gitlab.com_gitlabs.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
operators/gitlab-operator-kubernetes/0.26.2/manifests/gitlab-webhook-service_v1_service.yaml
operators/gitlab-operator-kubernetes/0.26.2/metadata/annotations.yaml
operators/gitlab-operator-kubernetes/0.26.2/tests/scorecard/config.yaml

operator gitlab-operator-kubernetes (0.26.2)

---

.gitignore

Part of FBC onboarding is downloading OPM tool to bin/ - this PR is to avoid accidentally push this folder with changes.

Ignore FBC related directory

---

README.md

Fixed links and removed duplicity comparing to central documentation (additional [changes also there](https://github.com/redhat-openshift-ecosystem/operator-pipelines/pull/669)). 
JIRA: ISV-4897

[ISV-4897] update README.md

---

operators/deployment-validation-operator/0.7.8/manifests/deploymentvalidationoperator-service.yaml
operators/deployment-validation-operator/0.7.8/manifests/deploymentvalidationoperator.0.7.8.clusterserviceversion.yaml
operators/deployment-validation-operator/0.7.8/metadata/annotations.yaml
operators/deployment-validation-operator/0.7.8/tests/scorecard/config.yaml

deployment-validation-operator new-release v0.7.8
--

operator deployment-validation-operator (0.7.8)

---

docs/pull_request_template.md

PR fixes non-existent links in the PR template.
2nd [PR](https://github.com/redhat-openshift-ecosystem/operator-pipelines/pull/750) fixes broken link in operator-pipelines repo.
---
Closes [ISV-5341](https://issues.redhat.com/browse/ISV-5341)

[ISV-5341] fix broken links

---

config.yaml

Configure image registries allowed for bundle images in catalog. Relates to the new static check in pipeline [check_bundle_images_in_fbc](https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/main/docs/users/static_checks.md#check_bundle_images_in_fbc)
Closes ISV-5446

[ISV-5446] Configure allowed catalog bundle registries

---

operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_codeflares.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_dashboards.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_kserves.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_kueues.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_rays.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_trustyais.yaml
operators/opendatahub-operator/2.26.0/manifests/components.platform.opendatahub.io_workbenches.yaml
operators/opendatahub-operator/2.26.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
operators/opendatahub-operator/2.26.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
operators/opendatahub-operator/2.26.0/manifests/features.opendatahub.io_featuretrackers.yaml
operators/opendatahub-operator/2.26.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
operators/opendatahub-operator/2.26.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opendatahub-operator/2.26.0/manifests/opendatahub-operator.clusterserviceversion.yaml
operators/opendatahub-operator/2.26.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/opendatahub-operator/2.26.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
operators/opendatahub-operator/2.26.0/manifests/services.platform.opendatahub.io_auths.yaml
operators/opendatahub-operator/2.26.0/manifests/services.platform.opendatahub.io_monitorings.yaml
operators/opendatahub-operator/2.26.0/metadata/annotations.yaml
operators/opendatahub-operator/2.26.0/tests/scorecard/config.yaml

Signed-off-by: AjayJagan <ajaganat@redhat.com>
--

operator opendatahub-operator (2.26.0)

---

operators/hive-operator/ci.yaml

- Set fbc.version_promotion_strategy to always
- Minor update to squash the OCP releases to a single line for catalog_names

[Hive] Add fbc.version_promotion_strategy
