- operators/registry-operator/0.2.0/bundle.Dockerfile
- operators/registry-operator/0.2.0/manifests/registry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/registry-operator/0.2.0/manifests/registry-operator-manager-config_v1_configmap.yaml
- operators/registry-operator/0.2.0/manifests/registry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/registry-operator/0.2.0/manifests/registry-operator-webhook-service_v1_service.yaml
- operators/registry-operator/0.2.0/manifests/registry-operator.clusterserviceversion.yaml
- operators/registry-operator/0.2.0/manifests/registry.devfile.io_clusterdevfileregistrieslists.yaml
- operators/registry-operator/0.2.0/manifests/registry.devfile.io_devfileregistries.yaml
- operators/registry-operator/0.2.0/manifests/registry.devfile.io_devfileregistrieslists.yaml
- operators/registry-operator/0.2.0/metadata/annotations.yaml
- operators/registry-operator/0.2.0/tests/scorecard/config.yaml
- operators/registry-operator/ci.yaml
> operator [CI] registry-operator (0.2.0)

- ci/pipeline-config-ocp.yaml
jira task: [ISV-3957](https://issues.redhat.com/browse/ISV-3957)
--
> [ISV-3957] set comm-op-index 4.14 as blocking

- operators/kubecost/1.107.1/bundle.Dockerfile
- operators/kubecost/1.107.1/manifests/charts.kubecost.com_costanalyzers.yaml
- operators/kubecost/1.107.1/manifests/kubecost-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kubecost/1.107.1/manifests/kubecost-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubecost/1.107.1/manifests/kubecost-operator.clusterserviceversion.yaml
- operators/kubecost/1.107.1/metadata/annotations.yaml
- operators/kubecost/1.107.1/tests/scorecard/config.yaml
Signed-off-by: chipzoller <chipzoller@gmail.com>
--
> operator kubecost (1.107.1)

- operators/grafana-operator/5.5.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.5.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.5.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.5.2/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.5.2/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.5.2/metadata/annotations.yaml
> operator grafana-operator (5.5.2)

- operators/authorino-operator/0.10.0/bundle.Dockerfile
- operators/authorino-operator/0.10.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.10.0/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.10.0/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.10.0/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.10.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.10.0/metadata/annotations.yaml
- operators/authorino-operator/0.10.0/tests/scorecard/config.yaml
> operator authorino-operator (0.10.0)

- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_alertmanagers.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_monitoringstacks.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_podmonitors.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_probes.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_prometheusagents.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_prometheuses.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_prometheusrules.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_scrapeconfigs.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_servicemonitors.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_thanosqueriers.yaml
- operators/observability-operator/0.0.28/manifests/monitoring.rhobs_thanosrulers.yaml
- operators/observability-operator/0.0.28/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
- operators/observability-operator/0.0.28/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
- operators/observability-operator/0.0.28/manifests/obo-prometheus-operator_v1_service.yaml
- operators/observability-operator/0.0.28/manifests/observability-operator-alertmanager-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- operators/observability-operator/0.0.28/manifests/observability-operator-prometheus-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- operators/observability-operator/0.0.28/manifests/observability-operator-prometheus-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- operators/observability-operator/0.0.28/manifests/observability-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- operators/observability-operator/0.0.28/manifests/observability-operator.clusterserviceversion.yaml
- operators/observability-operator/0.0.28/manifests/observability-operator_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/observability-operator/0.0.28/manifests/observability-operator_v1_service.yaml
- operators/observability-operator/0.0.28/metadata/annotations.yaml
- operators/observability-operator/0.0.28/tests/scorecard/config.yaml
xref https://issues.redhat.com/browse/MON-3408
--
> operator observability-operator (0.0.28)

- operators/mariadb-operator/0.23.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_backups.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_connections.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_databases.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_grants.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_mariadbs.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_restores.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_sqljobs.yaml
- operators/mariadb-operator/0.23.0/manifests/mariadb.mmontes.io_users.yaml
- operators/mariadb-operator/0.23.0/metadata/annotations.yaml
- operators/mariadb-operator/0.23.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.23.0) to community operators
> operator mariadb-operator (0.23.0)

- operators/mariadb-operator/0.23.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_backups.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_connections.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_databases.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_grants.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_mariadbs.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_restores.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_sqljobs.yaml
- operators/mariadb-operator/0.23.1/manifests/mariadb.mmontes.io_users.yaml
- operators/mariadb-operator/0.23.1/metadata/annotations.yaml
- operators/mariadb-operator/0.23.1/tests/scorecard/config.yaml
Add operator mariadb-operator (0.23.1) to community operators
> operator mariadb-operator (0.23.1)

- operators/limitador-operator/0.7.0/bundle.Dockerfile
- operators/limitador-operator/0.7.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
- operators/limitador-operator/0.7.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
- operators/limitador-operator/0.7.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/limitador-operator/0.7.0/manifests/limitador-operator.clusterserviceversion.yaml
- operators/limitador-operator/0.7.0/manifests/limitador.kuadrant.io_limitadors.yaml
- operators/limitador-operator/0.7.0/metadata/annotations.yaml
- operators/limitador-operator/0.7.0/tests/scorecard/config.yaml
> operator limitador-operator (0.7.0)

- operators/windup-operator/0.0.24/manifests/windup-operator.clusterserviceversion.yaml
- operators/windup-operator/0.0.24/manifests/windup.crd.yaml
- operators/windup-operator/0.0.24/metadata/annotations.yaml
> operator windup-operator (0.0.24)

- operators/patterns-operator/0.0.34/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.34/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.34/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.34/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.34/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.34/metadata/annotations.yaml
- operators/patterns-operator/0.0.34/tests/scorecard/config.yaml
> operator patterns-operator (0.0.34)

- operators/koku-metrics-operator/3.1.0/Dockerfile
- operators/koku-metrics-operator/3.1.0/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- operators/koku-metrics-operator/3.1.0/manifests/koku-metrics-operator.clusterserviceversion.yaml
- operators/koku-metrics-operator/3.1.0/metadata/annotations.yaml
- operators/koku-metrics-operator/3.1.0/tests/scorecard/config.yaml
- operators/koku-metrics-operator/ci.yaml
> operator [CI] koku-metrics-operator (3.1.0)

- operators/ack-keyspaces-controller/ci.yaml
> operator [CI] ack-keyspaces-controller

- operators/kuadrant-operator/0.5.0/bundle.Dockerfile
- operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
- operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.5.0/manifests/kuadrant-operator.clusterserviceversion.yaml
- operators/kuadrant-operator/0.5.0/manifests/kuadrant.io_authpolicies.yaml
- operators/kuadrant-operator/0.5.0/manifests/kuadrant.io_kuadrants.yaml
- operators/kuadrant-operator/0.5.0/manifests/kuadrant.io_ratelimitpolicies.yaml
- operators/kuadrant-operator/0.5.0/metadata/annotations.yaml
- operators/kuadrant-operator/0.5.0/metadata/dependencies.yaml
- operators/kuadrant-operator/0.5.0/tests/scorecard/config.yaml
> operator kuadrant-operator (0.5.0)

- operators/patterns-operator/0.0.35/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.35/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.35/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.35/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.35/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.35/metadata/annotations.yaml
- operators/patterns-operator/0.0.35/tests/scorecard/config.yaml
> operator patterns-operator (0.0.35)

- config.yaml
The Collective members accounts will be responsible for review process of new bundles.
--
> Add reviewers for a new workflow pipeline

- operators/lbconfig-operator/0.4.1/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml
- operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml
- operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator-manager-config_v1_configmap.yaml
- operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/lbconfig-operator/0.4.1/manifests/lbconfig-operator.clusterserviceversion.yaml
- operators/lbconfig-operator/0.4.1/metadata/annotations.yaml
- operators/lbconfig-operator/0.4.1/tests/scorecard/config.yaml
- operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml
- operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml
- operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml
- operators/lbconfig-operator/0.4.1/tests/scorecard/kuttl/kuttl-test.yaml
> operator lbconfig-operator (0.4.1)

- operators/rabbitmq-cluster-operator/2.6.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.6.0/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/2.6.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.6.0/metadata/annotations.yaml
> operator rabbitmq-cluster-operator (2.6.0)

- operators/rabbitmq-messaging-topology-operator/1.12.2/bundle.Dockerfile
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_bindings.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_exchanges.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_federations.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_permissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_policies.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_queues.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_schemareplications.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_shovels.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_superstreams.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_topicpermissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_users.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.com_vhosts.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/manifests/rabbitmq.webhook-service.yaml
- operators/rabbitmq-messaging-topology-operator/1.12.2/metadata/annotations.yaml
> operator rabbitmq-messaging-topology-operator (1.12.2)

- operators/awx-operator/2.9.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.9.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.9.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.9.0/manifests/awx-operator.v2.9.0.clusterserviceversion.yaml
- operators/awx-operator/2.9.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.9.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.9.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.9.0/metadata/annotations.yaml
- operators/awx-operator/2.9.0/tests/scorecard/config.yaml
> operator awx-operator (2.9.0)

- operators/patterns-operator/0.0.36/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.36/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.36/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.36/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.36/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.36/metadata/annotations.yaml
- operators/patterns-operator/0.0.36/tests/scorecard/config.yaml
> operator patterns-operator (0.0.36)

- ci/pipeline-config-ocp.yaml
The 4.10 is end of life now and can be removed.
--
> Remove 4.10 ocp version

- operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexuses.yaml
- operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexusrepositories.yaml
- operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexusroles.yaml
- operators/nexus-operator/3.0.0/manifests/edp.epam.com_nexususers.yaml
- operators/nexus-operator/3.0.0/manifests/nexus-operator.clusterserviceversion.yaml
- operators/nexus-operator/3.0.0/metadata/annotations.yaml
- operators/nexus-operator/3.0.0/tests/scorecard/config.yaml
- operators/nexus-operator/ci.yaml
> operator [N] [CI] nexus-operator (3.0.0)

- operators/project-quay/3.10.1/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.1/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.1/metadata/annotations.yaml
Add 3.10.1 to community operators
> operator project-quay (3.10.1)

- operators/dynatrace-operator/0.15.0/Dockerfile
- operators/dynatrace-operator/0.15.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/0.15.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/0.15.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/0.15.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/0.15.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/0.15.0/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/0.15.0/metadata/annotations.yaml
> operator dynatrace-operator (0.15.0)

- operators/external-secrets-operator/0.9.10/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.10/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.10/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.10/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.10/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.10/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.10/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.10
> operator external-secrets-operator (0.9.10)

- .github/workflows/pr-label-command.yml
The workflow allows user to use comments in PR as a command for new pipeline.
--
> Add workflow for PR labels commands

- operators/operator-e2e/0.0.100/ci.yaml
- operators/operator-e2e/0.0.100/manifests/operator-e2e-controller-manager-metrics-service_v1_service.yaml
- operators/operator-e2e/0.0.100/manifests/operator-e2e-manager-config_v1_configmap.yaml
- operators/operator-e2e/0.0.100/manifests/operator-e2e-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/operator-e2e/0.0.100/manifests/operator-e2e.clusterserviceversion.yaml
- operators/operator-e2e/0.0.100/manifests/tools.opdev.io_demoresources.yaml
- operators/operator-e2e/0.0.100/metadata/annotations.yaml
- operators/operator-e2e/0.0.100/tests/scorecard/config.yaml
> operator operator-e2e (0.0.100)

- operators/kuadrant-operator/0.6.0/bundle.Dockerfile
- operators/kuadrant-operator/0.6.0/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant-operator-dnsrecord-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant-operator-dnsrecord-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant-operator.clusterserviceversion.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_authpolicies.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_dnshealthcheckprobes.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_dnspolicies.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_dnsrecords.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_kuadrants.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_managedzones.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_ratelimitpolicies.yaml
- operators/kuadrant-operator/0.6.0/manifests/kuadrant.io_tlspolicies.yaml
- operators/kuadrant-operator/0.6.0/metadata/annotations.yaml
- operators/kuadrant-operator/0.6.0/metadata/dependencies.yaml
- operators/kuadrant-operator/0.6.0/tests/scorecard/config.yaml
> operator kuadrant-operator (0.6.0)

- docs/contributing-via-pr.md
> [ISV-4207] Update contributing via PR doc

- operators/OWNERS
The owners file is no longer needed since OpenShift CI is no longer integrated with the repository.
--
> Remove OWNERS file from operators directory

- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.39.4/manifests/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.39.4/manifests/victoriametrics-operator.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.39.4/metadata/annotations.yaml
> operator victoriametrics-operator (0.39.4)

- operators/hawtio-operator/1.0.0/manifests/hawt.io_hawtios.yaml
- operators/hawtio-operator/1.0.0/manifests/hawtio-operator.clusterserviceversion.yaml
- operators/hawtio-operator/1.0.0/metadata/annotations.yaml
- operators/hawtio-operator/1.0.0/tests/scorecard/config.yaml
- operators/hawtio-operator/ci.yaml
> operator hawtio-operator (1.0.0)

- operators/flux/2.2.2/manifests/alert.crd.yaml
- operators/flux/2.2.2/manifests/bucket.crd.yaml
- operators/flux/2.2.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/2.2.2/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/2.2.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/2.2.2/manifests/flux-edit-flux-system.clusterrole.yaml
- operators/flux/2.2.2/manifests/flux-view-flux-system.clusterrole.yaml
- operators/flux/2.2.2/manifests/flux.v2.2.2.clusterserviceversion.yaml
- operators/flux/2.2.2/manifests/gitrepository.crd.yaml
- operators/flux/2.2.2/manifests/helmchart.crd.yaml
- operators/flux/2.2.2/manifests/helmrelease.crd.yaml
- operators/flux/2.2.2/manifests/helmrepository.crd.yaml
- operators/flux/2.2.2/manifests/imagepolicy.crd.yaml
- operators/flux/2.2.2/manifests/imagerepository.crd.yaml
- operators/flux/2.2.2/manifests/imageupdateautomation.crd.yaml
- operators/flux/2.2.2/manifests/kustomization.crd.yaml
- operators/flux/2.2.2/manifests/notification-controller.service.yaml
- operators/flux/2.2.2/manifests/ocirepository.crd.yaml
- operators/flux/2.2.2/manifests/provider.crd.yaml
- operators/flux/2.2.2/manifests/receiver.crd.yaml
- operators/flux/2.2.2/manifests/source-controller.service.yaml
- operators/flux/2.2.2/manifests/webhook-receiver.service.yaml
- operators/flux/2.2.2/metadata/annotations.yaml
> operator flux (2.2.2)

- operators/mariadb-operator/0.24.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_backups.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_connections.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_databases.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_grants.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_mariadbs.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_restores.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_sqljobs.yaml
- operators/mariadb-operator/0.24.0/manifests/mariadb.mmontes.io_users.yaml
- operators/mariadb-operator/0.24.0/metadata/annotations.yaml
- operators/mariadb-operator/0.24.0/tests/scorecard/config.yaml
Add operator mariadb-operator (0.24.0) to community operators
> operator mariadb-operator (0.24.0)

- operators/ack-organizations-controller/ci.yaml
> add ack-organizations-controller ci file

- operators/external-secrets-operator/0.9.11/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.11/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.11/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.11/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.11/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.11/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.11/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.11
> operator external-secrets-operator (0.9.11)

- operators/patterns-operator/0.0.38/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.38/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.38/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.38/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.38/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.38/metadata/annotations.yaml
- operators/patterns-operator/0.0.38/tests/scorecard/config.yaml
> operator patterns-operator (0.0.38)

- operators/patterns-operator/0.0.39/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.39/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.39/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.39/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.39/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.39/metadata/annotations.yaml
- operators/patterns-operator/0.0.39/tests/scorecard/config.yaml
> operator patterns-operator (0.0.39)

- config.yaml
The test config determines a list of operator regexes that matches operator that skips certain test.
First 2 exceptions are taken from previous pipeline config and these operators requires an external dependencies when installed on cluster.
JIRA: ISV-4382
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain …
> Add test config with operator exception

- operators/microcks/1.8.1/manifests/microcks-operator.v1.8.1.clusterserviceversion.yaml
- operators/microcks/1.8.1/manifests/microcksinstall.crd.yaml
- operators/microcks/1.8.1/metadata/annotations.yaml
> operator microcks (1.8.1)

- docs/pull_request_template.md
PR template can't properly render a markdown relative links and links point to 404 page. The absolute links work fine in PR and when accessing file directly.
JIRA: ISV-4375
-- …
> Replace relative links in PR template

- operators/verticadb-operator/2.0.0/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.0.0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.0.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.0.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.0.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.0.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.0.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.0.0/metadata/annotations.yaml
- operators/verticadb-operator/2.0.0/tests/scorecard/config.yaml
> operator verticadb-operator (2.0.0)

- operators/verticadb-operator/2.0.1/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.0.1/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.0.1/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.0.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.0.1/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.0.1/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.0.1/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.0.1/metadata/annotations.yaml
- operators/verticadb-operator/2.0.1/tests/scorecard/config.yaml
> operator verticadb-operator (2.0.1)

- .github/workflows/documentation.yaml
- README.md
- docs/README.md
- docs/operator-ci-yaml.md
- mkdocs.yml
Documentation is converted into html pages using mkdocs tool and published to Github pages. The doc is automatically generated on doc changes.
JIRA: ISV-4399
-- …
> Publish documentation to Github pages

- operators/patterns-operator/0.0.40/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.40/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.40/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.40/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.40/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.40/metadata/annotations.yaml
- operators/patterns-operator/0.0.40/tests/scorecard/config.yaml
> operator patterns-operator (0.0.40)

- operators/amd-gpu-operator/0.0.1/manifests/amd-gpu-operator-controller-manager-metrics-service_v1_service.yaml
- operators/amd-gpu-operator/0.0.1/manifests/amd-gpu-operator-manager-config_v1_configmap.yaml
- operators/amd-gpu-operator/0.0.1/manifests/amd-gpu-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/amd-gpu-operator/0.0.1/manifests/amd-gpu-operator.clusterserviceversion.yaml
- operators/amd-gpu-operator/0.0.1/manifests/amd.io_deviceconfigs.yaml
- operators/amd-gpu-operator/0.0.1/metadata/annotations.yaml
- operators/amd-gpu-operator/0.0.1/test/scorecard/config.yaml
- operators/amd-gpu-operator/ci.yaml
> operator amd-gpu-operator (0.0.1)

- operators/dell-csm-operator/1.4.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.4.0/manifests/dell-csm-operator.v1.4.0.clusterserviceversion.yaml
- operators/dell-csm-operator/1.4.0/metadata/annotations.yaml
- operators/dell-csm-operator/1.4.0/tests/scorecard/config.yaml
> operator dell-csm-operator (1.4.0)

- operators/tempo-operator/0.7.0/bundle.Dockerfile
- operators/tempo-operator/0.7.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.7.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.7.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.7.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.7.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.7.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.7.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.7.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.7.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.7.0/metadata/annotations.yaml
- operators/tempo-operator/0.7.0/tests/scorecard/config.yaml
Release tempo-operator `0.7.0`.
> operator tempo-operator (0.7.0)

- operators/kubernetes-imagepuller-operator/1.1.0/manifests/che.eclipse.org_kubernetesimagepullers.yaml
- operators/kubernetes-imagepuller-operator/1.1.0/manifests/kubernetes-image-puller-operator-manager-metrics-service_v1_service.yaml
- operators/kubernetes-imagepuller-operator/1.1.0/manifests/kubernetes-image-puller-operator-manager-service_v1_service.yaml
- operators/kubernetes-imagepuller-operator/1.1.0/manifests/kubernetes-image-puller-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubernetes-imagepuller-operator/1.1.0/manifests/kubernetes-imagepuller-operator.v1.1.0.clusterserviceversion.yaml
- operators/kubernetes-imagepuller-operator/1.1.0/metadata/annotations.yaml
- operators/kubernetes-imagepuller-operator/1.1.0/tests/scorecard/config.yaml
> operator kubernetes-imagepuller-operator (1.1.0)

- operators/deployment-validation-operator/0.7.4/manifests/deploymentvalidationoperator-service.yaml
- operators/deployment-validation-operator/0.7.4/manifests/deploymentvalidationoperator.0.7.4.clusterserviceversion.yaml
- operators/deployment-validation-operator/0.7.4/metadata/annotations.yaml
- operators/deployment-validation-operator/0.7.4/tests/scorecard/config.yaml
> operator deployment-validation-operator (0.7.4)

- operators/patterns-operator/0.0.41/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.41/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.41/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.41/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.41/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.41/metadata/annotations.yaml
- operators/patterns-operator/0.0.41/tests/scorecard/config.yaml
> operator patterns-operator (0.0.41)

- operators/project-quay/3.10.2/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.2/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.2/metadata/annotations.yaml
Add 3.10.2 to community operators
> operator project-quay (3.10.2)

- operators/amd-gpu-operator/0.0.2/manifests/amd-gpu-operator-controller-manager-metrics-service_v1_service.yaml
- operators/amd-gpu-operator/0.0.2/manifests/amd-gpu-operator-manager-config_v1_configmap.yaml
- operators/amd-gpu-operator/0.0.2/manifests/amd-gpu-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/amd-gpu-operator/0.0.2/manifests/amd-gpu-operator.clusterserviceversion.yaml
- operators/amd-gpu-operator/0.0.2/manifests/amd.io_deviceconfigs.yaml
- operators/amd-gpu-operator/0.0.2/metadata/annotations.yaml
- operators/amd-gpu-operator/0.0.2/test/scorecard/config.yaml
> operator amd-gpu-operator (0.0.2)

- operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/1.0.0-beta.4/manifests/pulp-operator.clusterserviceversion.yaml
- operators/pulp-operator/1.0.0-beta.4/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/1.0.0-beta.4/manifests/repo-manager.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/1.0.0-beta.4/manifests/repo-manager.pulpproject.org_pulps.yaml
- operators/pulp-operator/1.0.0-beta.4/metadata/annotations.yaml
- operators/pulp-operator/1.0.0-beta.4/tests/scorecard/config.yaml
> operator pulp-operator (1.0.0-beta.4)

- operators/project-quay/3.9.6/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.9.6/manifests/quayregistries.crd.yaml
- operators/project-quay/3.9.6/metadata/annotations.yaml
Add 3.9.6 to community operators
> operator project-quay (3.9.6)

- operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
- operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-manager-config_v1_configmap.yaml
- operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator-webhook-service_v1_service.yaml
- operators/eginnovations-operator/0.0.7/manifests/eginnovations-operator.clusterserviceversion.yaml
- operators/eginnovations-operator/0.0.7/manifests/eginnovations.com_eguniversalagents.yaml
- operators/eginnovations-operator/0.0.7/metadata/annotations.yaml
- operators/eginnovations-operator/0.0.7/tests/scorecard/config.yaml
> operator eginnovations-operator (0.0.7)

- operators/opentelemetry-operator/0.91.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opentelemetry-operator/0.91.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opentelemetry-operator/0.91.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml
- operators/opentelemetry-operator/0.91.0/manifests/opentelemetry-operator.clusterserviceversion.yaml
- operators/opentelemetry-operator/0.91.0/manifests/opentelemetry.io_instrumentations.yaml
- operators/opentelemetry-operator/0.91.0/manifests/opentelemetry.io_opampbridges.yaml
- operators/opentelemetry-operator/0.91.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml
- operators/opentelemetry-operator/0.91.0/metadata/annotations.yaml
- operators/opentelemetry-operator/0.91.0/tests/scorecard/config.yaml
Release opentelemetry-operator 0.91.0.
> operator opentelemetry-operator (0.91.0)

- operators/portworx-essentials/23.10.2/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/23.10.2/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/23.10.2/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/23.10.2/metadata/annotations.yaml
> operator portworx-essentials (23.10.2)

- operators/rabbitmq-cluster-operator/2.7.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.7.0/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/2.7.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.7.0/metadata/annotations.yaml
> operator rabbitmq-cluster-operator (2.7.0)

- operators/portworx-essentials/ci.yaml
> portworx-essentials: add authors to the ci.yaml

- operators/ndmspc-operator/0.7.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.7.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.7.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.7.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.7.2/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.7.2/metadata/annotations.yaml
- operators/ndmspc-operator/0.7.2/tests/scorecard/config.yaml
> operator ndmspc-operator (0.7.2)

- operators/amd-gpu-operator/0.0.3/manifests/amd-gpu-operator-controller-manager-metrics-service_v1_service.yaml
- operators/amd-gpu-operator/0.0.3/manifests/amd-gpu-operator-manager-config_v1_configmap.yaml
- operators/amd-gpu-operator/0.0.3/manifests/amd-gpu-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/amd-gpu-operator/0.0.3/manifests/amd-gpu-operator.clusterserviceversion.yaml
- operators/amd-gpu-operator/0.0.3/manifests/amd.io_deviceconfigs.yaml
- operators/amd-gpu-operator/0.0.3/metadata/annotations.yaml
- operators/amd-gpu-operator/0.0.3/test/scorecard/config.yaml
> operator amd-gpu-operator (0.0.3)

- operators/gitlab-operator-kubernetes/0.28.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.28.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.28.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.28.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.28.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.28.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.28.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.28.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.28.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.28.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.28.1)

- operators/gitlab-operator-kubernetes/0.27.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.27.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.27.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.27.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.27.0)

- operators/gitlab-operator-kubernetes/0.27.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.27.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.27.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.27.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.27.1)

- operators/gitlab-operator-kubernetes/0.28.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.28.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.28.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.28.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.28.0)

- operators/kuadrant-operator/0.6.1/bundle.Dockerfile
- operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-dnsrecord-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-dnsrecord-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant-operator.clusterserviceversion.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_authpolicies.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_dnshealthcheckprobes.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_dnspolicies.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_dnsrecords.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_kuadrants.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_managedzones.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_ratelimitpolicies.yaml
- operators/kuadrant-operator/0.6.1/manifests/kuadrant.io_tlspolicies.yaml
- operators/kuadrant-operator/0.6.1/metadata/annotations.yaml
- operators/kuadrant-operator/0.6.1/metadata/dependencies.yaml
- operators/kuadrant-operator/0.6.1/tests/scorecard/config.yaml
> operator kuadrant-operator (0.6.1)

- operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.clusterserviceversion.yaml
> removing replace line on first rabbitmq messaging operator version

- operators/rabbitmq-messaging-topology-operator/1.13.0/bundle.Dockerfile
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_bindings.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_exchanges.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_federations.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_operatorpolicies.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_permissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_policies.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_queues.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_schemareplications.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_shovels.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_superstreams.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_topicpermissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_users.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.com_vhosts.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/manifests/rabbitmq.webhook-service.yaml
- operators/rabbitmq-messaging-topology-operator/1.13.0/metadata/annotations.yaml
> operator rabbitmq-messaging-topology-operator (1.13.0)

- operators/awx-operator/2.10.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.10.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.10.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.10.0/manifests/awx-operator.v2.10.0.clusterserviceversion.yaml
- operators/awx-operator/2.10.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.10.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.10.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.10.0/metadata/annotations.yaml
- operators/awx-operator/2.10.0/tests/scorecard/config.yaml
> operator awx-operator (2.10.0)

- operators/awx-operator/2.11.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.11.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.11.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.11.0/manifests/awx-operator.v2.11.0.clusterserviceversion.yaml
- operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.11.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.11.0/metadata/annotations.yaml
- operators/awx-operator/2.11.0/tests/scorecard/config.yaml
> operator awx-operator (2.11.0)

- operators/cert-utils-operator/1.3.12/Dockerfile
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator-certificate-rule-alerts_monitoring.coreos.com_v1_prometheusrule.yaml
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator-controller-manager-metrics-service_v1_service.yaml
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator-manager-config_v1_configmap.yaml
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/cert-utils-operator/1.3.12/manifests/cert-utils-operator.clusterserviceversion.yaml
- operators/cert-utils-operator/1.3.12/metadata/annotations.yaml
- operators/cert-utils-operator/1.3.12/tests/scorecard/config.yaml
> operator cert-utils-operator (1.3.12)

- operators/grafana-operator/5.6.1/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.6.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.6.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.6.1/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.6.1/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.6.1/metadata/annotations.yaml
> operator grafana-operator (5.6.1)

- operators/tempo-operator/0.8.0/bundle.Dockerfile
- operators/tempo-operator/0.8.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.8.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.8.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.8.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.8.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.8.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.8.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.8.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.8.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.8.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.8.0/metadata/annotations.yaml
- operators/tempo-operator/0.8.0/tests/scorecard/config.yaml
Release tempo-operator `0.8.0`.
> operator tempo-operator (0.8.0)

- operators/skupper-operator/1.5.3/manifests/skupper-operator.v1.5.3.clusterserviceversion.yaml
- operators/skupper-operator/1.5.3/metadata/annotations.yaml
- operators/skupper-operator/ci.yaml
> operator skupper-operator (1.5.3)

- operators/windup-operator/0.0.25/manifests/windup-operator.clusterserviceversion.yaml
- operators/windup-operator/0.0.25/manifests/windup.crd.yaml
- operators/windup-operator/0.0.25/metadata/annotations.yaml
> operator windup-operator (0.0.25)

- operators/codeflare-operator/1.1.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.1.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.1.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.1.0/manifests/quota.codeflare.dev_quotasubtrees.yaml
- operators/codeflare-operator/1.1.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.1.0/manifests/workload.codeflare.dev_schedulingspecs.yaml
- operators/codeflare-operator/1.1.0/metadata/annotations.yaml
- operators/codeflare-operator/1.1.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.1.0)

- operators/edp-keycloak-operator/1.20.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/edp-keycloak-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakclients.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
- operators/edp-keycloak-operator/1.20.0/manifests/v1.edp.epam.com_keycloaks.yaml
- operators/edp-keycloak-operator/1.20.0/metadata/annotations.yaml
- operators/edp-keycloak-operator/1.20.0/tests/scorecard/config.yaml
> operator edp-keycloak-operator (1.20.0)

- operators/kaoto-operator/0.0.10/manifests/designer.kaoto.io_kaotoes.yaml
- operators/kaoto-operator/0.0.10/manifests/kaoto-operator.clusterserviceversion.yaml
- operators/kaoto-operator/0.0.10/metadata/annotations.yaml
- operators/kaoto-operator/0.0.10/tests/scorecard/config.yaml
> operator kaoto-operator (0.0.10)

- operators/kaoto-operator/0.0.11/manifests/designer.kaoto.io_kaotoes.yaml
- operators/kaoto-operator/0.0.11/manifests/kaoto-operator.clusterserviceversion.yaml
- operators/kaoto-operator/0.0.11/metadata/annotations.yaml
- operators/kaoto-operator/0.0.11/tests/scorecard/config.yaml
> operator kaoto-operator (0.0.11)

- operators/hawtio-operator/1.0.1/manifests/hawt.io_hawtios.yaml
- operators/hawtio-operator/1.0.1/manifests/hawtio-operator.v1.0.1.clusterserviceversion.yaml
- operators/hawtio-operator/1.0.1/metadata/annotations.yaml
- operators/hawtio-operator/1.0.1/tests/scorecard/config.yaml
> operator hawtio-operator (1.0.1)

- operators/patterns-operator/0.0.42/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.42/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.42/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.42/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.42/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.42/metadata/annotations.yaml
- operators/patterns-operator/0.0.42/tests/scorecard/config.yaml
> operator patterns-operator (0.0.42)

- operators/opendatahub-operator/2.7.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.7.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.7.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.7.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.7.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.7.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.7.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.7.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.7.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.7.0)

- operators/grafana-operator/5.6.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.6.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.6.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.6.2/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.6.2/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.6.2/metadata/annotations.yaml
> operator grafana-operator (5.6.2)

- operators/kaoto-operator/0.0.12/manifests/designer.kaoto.io_kaotoes.yaml
- operators/kaoto-operator/0.0.12/manifests/kaoto-operator.clusterserviceversion.yaml
- operators/kaoto-operator/0.0.12/metadata/annotations.yaml
- operators/kaoto-operator/0.0.12/tests/scorecard/config.yaml
> operator kaoto-operator (0.0.12)

- operators/portworx-essentials/23.10.3/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/23.10.3/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/23.10.3/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/23.10.3/metadata/annotations.yaml
> operator portworx-essentials (23.10.3)

- operators/external-secrets-operator/0.9.12/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.12/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.12/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.12/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.12/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.12/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.12/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.12
> operator external-secrets-operator (0.9.12)

- operators/grafana-operator/5.6.3/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.6.3/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.6.3/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.6.3/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.6.3/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.6.3/metadata/annotations.yaml
> operator grafana-operator (5.6.3)

- operators/gitlab-operator-kubernetes/0.28.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.28.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.28.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.28.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.28.2)

- operators/ndmspc-operator/0.9.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.9.0/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.9.0/metadata/annotations.yaml
- operators/ndmspc-operator/0.9.0/tests/scorecard/config.yaml
> operator ndmspc-operator (0.9.0)

- operators/forklift-operator/2.5.5/manifests/forklift-operator.clusterserviceversion.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_hooks.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_hosts.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_migrations.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_networkmaps.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_plans.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_providers.yaml
- operators/forklift-operator/2.5.5/manifests/forklift.konveyor.io_storagemaps.yaml
- operators/forklift-operator/2.5.5/metadata/annotations.yaml
> operator forklift-operator (2.5.5)

- operators/ack-efs-controller/ci.yaml
> add ack-efs-controller ci file

- operators/dns-operator/0.1.0/manifests/dns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/dns-operator/0.1.0/manifests/dns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dns-operator/0.1.0/manifests/dns-operator.clusterserviceversion.yaml
- operators/dns-operator/0.1.0/manifests/kuadrant.io_dnshealthcheckprobes.yaml
- operators/dns-operator/0.1.0/manifests/kuadrant.io_dnsrecords.yaml
- operators/dns-operator/0.1.0/manifests/kuadrant.io_managedzones.yaml
- operators/dns-operator/0.1.0/metadata/annotations.yaml
- operators/dns-operator/0.1.0/tests/scorecard/config.yaml
- operators/dns-operator/ci.yaml
> operator dns-operator (0.1.0)

- operators/awx-operator/2.12.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.12.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.12.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.12.0/manifests/awx-operator.v2.12.0.clusterserviceversion.yaml
- operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.12.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.12.0/metadata/annotations.yaml
- operators/awx-operator/2.12.0/tests/scorecard/config.yaml
operator awx-operator (2.12.0)
> operator awx-operator (2.12.0)

- operators/neuvector-community-operator/1.4.4/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.4.4/manifests/neuvector-operator.v1.4.4.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.4.4/metadata/annotations.yaml
> operator neuvector-community-operator (1.4.4)

- operators/external-secrets-operator/0.9.13/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.13/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.13/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.13/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.13/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.13/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.13/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.13
> operator external-secrets-operator (0.9.13)

- operators/verticadb-operator/2.0.2/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.0.2/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.0.2/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.0.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.0.2/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.0.2/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/2.0.2/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/2.0.2/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.0.2/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.0.2/metadata/annotations.yaml
- operators/verticadb-operator/2.0.2/tests/scorecard/config.yaml
> operator verticadb-operator (2.0.2)

- operators/gitlab-operator-kubernetes/0.29.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.29.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.29.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.29.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.29.0)

- operators/ack-elbv2-controller/ci.yaml
> add ack-elbv2-controller ci file

- operators/ack-ecs-controller/ci.yaml
> add ack-ecs-controller ci file

- operators/ack-documentdb-controller/ci.yaml
> add ack-documentdb-controller ci file

- operators/mongodb-atlas-kubernetes/2.1.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.1.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.1.0)

- operators/opentelemetry-operator/ci.yaml
--
This adds the opentelemetrybot and myself as approvers
> Update ci.yaml to include opentelemetrybot

- operators/opendatahub-operator/2.8.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.8.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.8.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.8.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.8.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.8.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.8.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.8.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.8.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.8.0)

- operators/codeflare-operator/1.2.0/manifests/codeflare-operator-clusterrole-admin_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.2.0/manifests/codeflare-operator-clusterrole-edit_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.2.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.2.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.2.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.2.0/manifests/quota.codeflare.dev_quotasubtrees.yaml
- operators/codeflare-operator/1.2.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.2.0/manifests/workload.codeflare.dev_schedulingspecs.yaml
- operators/codeflare-operator/1.2.0/metadata/annotations.yaml
- operators/codeflare-operator/1.2.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.2.0)

- operators/korrel8r/0.0.8/manifests/korrel8r-controller-manager-metrics-service_v1_service.yaml
- operators/korrel8r/0.0.8/manifests/korrel8r-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/korrel8r/0.0.8/manifests/korrel8r.clusterserviceversion.yaml
- operators/korrel8r/0.0.8/manifests/korrel8r.openshift.io_korrel8rs.yaml
- operators/korrel8r/0.0.8/metadata/annotations.yaml
- operators/korrel8r/0.0.8/tests/scorecard/config.yaml
- operators/korrel8r/ci.yaml
Request to create korrel8r operator
> operator korrel8r (0.0.8)

- docs/packaging-operator.md
> Remove deprecated update mode

- operators/forklift-operator/2.6.0/manifests/forklift-operator.clusterserviceversion.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_hooks.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_hosts.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_migrations.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_networkmaps.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_plans.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_providers.yaml
- operators/forklift-operator/2.6.0/manifests/forklift.konveyor.io_storagemaps.yaml
- operators/forklift-operator/2.6.0/metadata/annotations.yaml
> operator forklift-operator (2.6.0)

- operators/move2kube-operator/0.3.12/bundle.Dockerfile
- operators/move2kube-operator/0.3.12/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
- operators/move2kube-operator/0.3.12/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/move2kube-operator/0.3.12/manifests/move2kube-operator.clusterserviceversion.yaml
- operators/move2kube-operator/0.3.12/manifests/move2kube.konveyor.io_move2kubes.yaml
- operators/move2kube-operator/0.3.12/metadata/annotations.yaml
- operators/move2kube-operator/0.3.12/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.12
> operator move2kube-operator (0.3.12)

- operators/dell-csm-operator/1.4.2/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.4.2/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.4.2/manifests/dell-csm-operator.v1.4.2.clusterserviceversion.yaml
- operators/dell-csm-operator/1.4.2/metadata/annotations.yaml
- operators/dell-csm-operator/1.4.2/tests/scorecard/config.yaml
> operator dell-csm-operator (1.4.2)

- operators/gitlab-operator-kubernetes/0.29.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.29.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.29.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.29.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.29.1)

- operators/layer7-operator/1.0.5/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
- operators/layer7-operator/1.0.5/manifests/layer7-operator-manager-config_v1_configmap.yaml
- operators/layer7-operator/1.0.5/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/layer7-operator/1.0.5/manifests/layer7-operator-webhook-service_v1_service.yaml
- operators/layer7-operator/1.0.5/manifests/layer7-operator.clusterserviceversion.yaml
- operators/layer7-operator/1.0.5/manifests/security.brcmlabs.com_gateways.yaml
- operators/layer7-operator/1.0.5/manifests/security.brcmlabs.com_l7apis.yaml
- operators/layer7-operator/1.0.5/manifests/security.brcmlabs.com_l7portals.yaml
- operators/layer7-operator/1.0.5/manifests/security.brcmlabs.com_repositories.yaml
- operators/layer7-operator/1.0.5/metadata/annotations.yaml
- operators/layer7-operator/1.0.5/tests/scorecard/config.yaml
- operators/layer7-operator/ci.yaml
> operator layer7-operator (1.0.5)

- operators/skupper-operator/1.6.0/manifests/skupper-operator.v1.6.0.clusterserviceversion.yaml
- operators/skupper-operator/1.6.0/metadata/annotations.yaml
> operator skupper-operator (1.6.0)

- operators/project-quay/3.10.4/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.4/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.4/metadata/annotations.yaml
Add 3.10.4 to community operators
> operator project-quay (3.10.4)

- operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml
- operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml
- operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml
- operators/beegfs-csi-driver-operator/1.6.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml
- operators/beegfs-csi-driver-operator/1.6.0/metadata/annotations.yaml
- operators/beegfs-csi-driver-operator/1.6.0/tests/scorecard/config.yaml
> operator beegfs-csi-driver-operator (1.6.0)

- operators/koku-metrics-operator/3.2.0/Dockerfile
- operators/koku-metrics-operator/3.2.0/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- operators/koku-metrics-operator/3.2.0/manifests/koku-metrics-operator.clusterserviceversion.yaml
- operators/koku-metrics-operator/3.2.0/metadata/annotations.yaml
- operators/koku-metrics-operator/3.2.0/tests/scorecard/config.yaml
> operator koku-metrics-operator (3.2.0)

- operators/self-node-remediation/0.8.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation.clusterserviceversion.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
- operators/self-node-remediation/0.8.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
- operators/self-node-remediation/0.8.0/metadata/annotations.yaml
- operators/self-node-remediation/0.8.0/tests/scorecard/config.yaml
> operator self-node-remediation (0.8.0)

- operators/awx-operator/2.12.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.12.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.12.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.12.1/manifests/awx-operator.v2.12.1.clusterserviceversion.yaml
- operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.12.1/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.12.1/metadata/annotations.yaml
- operators/awx-operator/2.12.1/tests/scorecard/config.yaml
operator awx-operator (2.12.1)
> operator awx-operator (2.12.1)

- operators/awx-operator/2.12.2/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.12.2/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.12.2/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.12.2/manifests/awx-operator.v2.12.2.clusterserviceversion.yaml
- operators/awx-operator/2.12.2/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.12.2/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.12.2/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.12.2/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.12.2/metadata/annotations.yaml
- operators/awx-operator/2.12.2/tests/scorecard/config.yaml
Replaces: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4095
--
> operator awx-operator (2.12.2)

- operators/analytics-operator/0.1.0/manifests/analytics-operator-controller-manager-metrics-service_v1_service.yaml
- operators/analytics-operator/0.1.0/manifests/analytics-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/analytics-operator/0.1.0/manifests/analytics-operator.clusterserviceversion.yaml
- operators/analytics-operator/0.1.0/manifests/observability-analytics.redhat.com_anomalydata.yaml
- operators/analytics-operator/0.1.0/manifests/observability-analytics.redhat.com_anomalyengines.yaml
- operators/analytics-operator/0.1.0/metadata/annotations.yaml
- operators/analytics-operator/0.1.0/tests/scorecard/config.yaml
- operators/analytics-operator/ci.yaml
> operator analytics-operator (0.1.0)

- operators/gitlab-operator-kubernetes/0.29.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.29.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.29.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.29.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.29.2)

- operators/cluster-manager/0.13.0/manifests/cluster-manager.clusterserviceversion.yaml
- operators/cluster-manager/0.13.0/manifests/operator.open-cluster-management.io_clustermanagers.yaml
- operators/cluster-manager/0.13.0/metadata/annotations.yaml
> operator cluster-manager (0.13.0)

- operators/dell-csm-operator/1.4.3/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.4.3/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.4.3/manifests/dell-csm-operator.v1.4.3.clusterserviceversion.yaml
- operators/dell-csm-operator/1.4.3/metadata/annotations.yaml
- operators/dell-csm-operator/1.4.3/tests/scorecard/config.yaml
> operator dell-csm-operator (1.4.3)

- operators/klusterlet/0.13.0/manifests/klusterlet.clusterserviceversion.yaml
- operators/klusterlet/0.13.0/manifests/operator.open-cluster-management.io_klusterlets.yaml
- operators/klusterlet/0.13.0/metadata/annotations.yaml
> operator klusterlet (0.13.0)

- operators/verticadb-operator/2.1.0/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.1.0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.1.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.1.0/manifests/vertica.com_verticarestorepointsqueries.yaml
- operators/verticadb-operator/2.1.0/manifests/vertica.com_verticascrutinizers.yaml
- operators/verticadb-operator/2.1.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.1.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.1.0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/2.1.0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/2.1.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.1.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.1.0/metadata/annotations.yaml
- operators/verticadb-operator/2.1.0/tests/scorecard/config.yaml
> operator verticadb-operator (2.1.0)

- operators/aqua/2022.4.15/manifests/aqua-operator.v2022.4.15.clusterserviceversion.yaml
- operators/aqua/2022.4.15/manifests/aquacloudconnector.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquacsps.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquadatabases.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquaenforcers.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquagateways.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aqualightnings.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquascanners.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquaservers.operator.aquasec.com.crd.yaml
- operators/aqua/2022.4.15/manifests/aquastarboards.aquasecurity.github.io.crd.yaml
- operators/aqua/2022.4.15/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml
- operators/aqua/2022.4.15/manifests/configauditreports.aquasecurity.github.io.crd.yaml
- operators/aqua/2022.4.15/metadata/annotations.yaml
> operator aqua (2022.4.15)

- operators/ndmspc-operator/0.10.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.10.0/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.10.0/metadata/annotations.yaml
- operators/ndmspc-operator/0.10.0/tests/scorecard/config.yaml
> operator ndmspc-operator (0.10.0)

- operators/deployment-validation-operator/0.7.5/manifests/deploymentvalidationoperator-service.yaml
- operators/deployment-validation-operator/0.7.5/manifests/deploymentvalidationoperator.0.7.5.clusterserviceversion.yaml
- operators/deployment-validation-operator/0.7.5/metadata/annotations.yaml
- operators/deployment-validation-operator/0.7.5/tests/scorecard/config.yaml
> operator deployment-validation-operator (0.7.5)

- operators/ndmspc-operator/0.10.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.10.2/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.10.2/metadata/annotations.yaml
- operators/ndmspc-operator/0.10.2/tests/scorecard/config.yaml
> operator ndmspc-operator (0.10.2)

- operators/awx-operator/2.13.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.13.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.13.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.13.0/manifests/awx-operator.v2.13.0.clusterserviceversion.yaml
- operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.13.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.13.0/metadata/annotations.yaml
- operators/awx-operator/2.13.0/tests/scorecard/config.yaml
operator awx-operator (2.13.0)
> operator awx-operator (2.13.0)

- operators/grafana-operator/5.7.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.7.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.7.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.7.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.7.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.7.0/metadata/annotations.yaml
> operator grafana-operator (5.7.0)

- operators/apicurio-registry/1.1.1-v2.5.9.final/bundle.Dockerfile
- operators/apicurio-registry/1.1.1-v2.5.9.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
- operators/apicurio-registry/1.1.1-v2.5.9.final/manifests/registry.apicur.io_apicurioregistries.yaml
- operators/apicurio-registry/1.1.1-v2.5.9.final/metadata/annotations.yaml
- operators/apicurio-registry/1.1.1-v2.5.9.final/tests/scorecard/config.yaml
> operator apicurio-registry (1.1.1-v2.5.9.final)

- operators/authorino-operator/0.11.0/bundle.Dockerfile
- operators/authorino-operator/0.11.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-operator-manager-config_v1_configmap.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.0/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.11.0/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.11.0/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.11.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.11.0/metadata/annotations.yaml
- operators/authorino-operator/0.11.0/tests/scorecard/config.yaml
> operator authorino-operator (0.11.0)

- operators/awx-operator/2.13.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.13.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.13.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.13.1/manifests/awx-operator.v2.13.1.clusterserviceversion.yaml
- operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.13.1/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.13.1/metadata/annotations.yaml
- operators/awx-operator/2.13.1/tests/scorecard/config.yaml
operator awx-operator (2.13.1)
> operator awx-operator (2.13.1)

- operators/ndmspc-operator/0.11.1/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.11.1/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.11.1/metadata/annotations.yaml
- operators/ndmspc-operator/0.11.1/tests/scorecard/config.yaml
> operator ndmspc-operator (0.11.1)

- operators/ndmspc-operator/0.11.2/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.11.2/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.11.2/metadata/annotations.yaml
- operators/ndmspc-operator/0.11.2/tests/scorecard/config.yaml
> operator ndmspc-operator (0.11.2)

- operators/ndmspc-operator/0.11.3/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.11.3/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.11.3/metadata/annotations.yaml
- operators/ndmspc-operator/0.11.3/tests/scorecard/config.yaml
> operator ndmspc-operator (0.11.3)

- operators/authorino-operator/0.11.1/bundle.Dockerfile
- operators/authorino-operator/0.11.1/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-operator-manager-config_v1_configmap.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.11.1/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.11.1/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.11.1/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.11.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.11.1/metadata/annotations.yaml
- operators/authorino-operator/0.11.1/tests/scorecard/config.yaml
> operator authorino-operator (0.11.1)

- operators/forklift-operator/2.5.6/manifests/forklift-operator.clusterserviceversion.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_hooks.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_hosts.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_migrations.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_networkmaps.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_plans.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_providers.yaml
- operators/forklift-operator/2.5.6/manifests/forklift.konveyor.io_storagemaps.yaml
- operators/forklift-operator/2.5.6/metadata/annotations.yaml
> operator forklift-operator (2.5.6)

- operators/trident-operator/24.2.0/manifests/trident-operator.v24.2.0.clusterserviceversion.yaml
- operators/trident-operator/24.2.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
- operators/trident-operator/24.2.0/metadata/annotations.yaml
- operators/trident-operator/ci.yaml
> operator trident-operator (24.2.0)

- operators/kubecost/1.106.0/bundle.Dockerfile
- operators/kubecost/1.106.0/manifests/kubecost-operator.clusterserviceversion.yaml
- operators/kubecost/1.106.2/manifests/kubecost-operator.clusterserviceversion.yaml
- operators/kubecost/1.107.1/manifests/kubecost-operator.clusterserviceversion.yaml
The kubecost-operator was used by mistake and author is now asking to unify the name.
--
> Replace kubecost-operator with kubecost in recent operators

- operators/verticadb-operator/2.1.1/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.1.1/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.1.1/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.1.1/manifests/vertica.com_verticarestorepointsqueries.yaml
- operators/verticadb-operator/2.1.1/manifests/vertica.com_verticascrutinizers.yaml
- operators/verticadb-operator/2.1.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.1.1/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.1.1/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/2.1.1/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/2.1.1/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.1.1/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.1.1/metadata/annotations.yaml
- operators/verticadb-operator/2.1.1/tests/scorecard/config.yaml
> operator verticadb-operator (2.1.1)

- operators/percona-xtradb-cluster-operator/1.14.0/manifests/percona-xtradb-cluster-operator.v1.14.0.clusterserviceversion.yaml
- operators/percona-xtradb-cluster-operator/1.14.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.14.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.14.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.14.0/metadata/annotations.yaml
- operators/percona-xtradb-cluster-operator/ci.yaml
> operator percona-xtradb-cluster-operator (1.14.0)

- operators/portworx-essentials/23.10.4/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/23.10.4/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/23.10.4/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/23.10.4/metadata/annotations.yaml
> operator portworx-essentials (23.10.4)

- operators/assisted-service-operator/ci.yaml
> NO-ISSUE: Add my account as reviewer

- operators/assisted-service-operator/0.7.72/manifests/agent-install.openshift.io_agentclassifications.yaml
- operators/assisted-service-operator/0.7.72/manifests/agent-install.openshift.io_agents.yaml
- operators/assisted-service-operator/0.7.72/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
- operators/assisted-service-operator/0.7.72/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
- operators/assisted-service-operator/0.7.72/manifests/agent-install.openshift.io_infraenvs.yaml
- operators/assisted-service-operator/0.7.72/manifests/agent-install.openshift.io_nmstateconfigs.yaml
- operators/assisted-service-operator/0.7.72/manifests/assisted-service-operator.clusterserviceversion.yaml
- operators/assisted-service-operator/0.7.72/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- operators/assisted-service-operator/0.7.72/metadata/annotations.yaml
Fix for - https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4204
> operator assisted-service-operator (0.7.72)

- operators/opendatahub-operator/2.9.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.9.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.9.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.9.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.9.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.9.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.9.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.9.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.9.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.9.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.9.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.9.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.9.0)

- operators/ndmspc-operator/0.11.6/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.11.6/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.11.6/metadata/annotations.yaml
- operators/ndmspc-operator/0.11.6/tests/scorecard/config.yaml
> operator ndmspc-operator (0.11.6)

- operators/grafana-operator/5.8.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.8.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.8.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.8.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.8.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.8.0/metadata/annotations.yaml
- operators/grafana-operator/ci.yaml
This also updates the reviewers to the current maintainers of the Grafana Operator (cc @NissesSenap)
---
--
> operator grafana-operator (5.8.0)

- operators/mongodb-atlas-kubernetes/2.2.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.2.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.2.0)

- operators/move2kube-operator/0.3.13-rc.0/bundle.Dockerfile
- operators/move2kube-operator/0.3.13-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
- operators/move2kube-operator/0.3.13-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/move2kube-operator/0.3.13-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml
- operators/move2kube-operator/0.3.13-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml
- operators/move2kube-operator/0.3.13-rc.0/metadata/annotations.yaml
- operators/move2kube-operator/0.3.13-rc.0/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.13-rc.0
> operator move2kube-operator (0.3.13-rc.0)

- operators/multicluster-global-hub-operator/1.1.0/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.1.0/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.1.0/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.1.0)

- operators/multicluster-global-hub-operator/1.2.0-dev/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.2.0-dev/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.2.0-dev/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.2.0-dev)

- operators/gitlab-operator-kubernetes/0.30.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.30.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.30.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.30.0)

- operators/awx-operator/2.14.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.14.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.14.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.14.0/manifests/awx-operator.v2.14.0.clusterserviceversion.yaml
- operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.14.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.14.0/metadata/annotations.yaml
- operators/awx-operator/2.14.0/tests/scorecard/config.yaml
operator awx-operator (2.14.0)
> operator awx-operator (2.14.0)

- operators/datadog-operator/ci.yaml
update ci.yaml file for the `datadog-operator` operator: 
* Add our robot account to automate `datadog-operator` new release promotion.
* remove one user
--
> [datadog] update reviewers list

- operators/patterns-operator/0.0.43/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.43/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.43/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.43/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.43/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.43/metadata/annotations.yaml
- operators/patterns-operator/0.0.43/tests/scorecard/config.yaml
> operator patterns-operator (0.0.43)

- operators/group-sync-operator/0.0.28/Dockerfile
- operators/group-sync-operator/0.0.28/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.28/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.28/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.28/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.28/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.28/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.28/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.28/metadata/annotations.yaml
- operators/group-sync-operator/0.0.28/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.28)

- operators/loki-operator/ci.yaml
> loki-operator: add grafanabot to ci.yml

- operators/dell-csm-operator/1.4.4/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.4.4/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.4.4/manifests/dell-csm-operator.v1.4.4.clusterserviceversion.yaml
- operators/dell-csm-operator/1.4.4/metadata/annotations.yaml
- operators/dell-csm-operator/1.4.4/tests/scorecard
> operator dell-csm-operator (1.4.4)

- operators/argocd-operator/0.9.0/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- operators/argocd-operator/0.9.0/manifests/argocd-operator-manager-config_v1_configmap.yaml
- operators/argocd-operator/0.9.0/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/argocd-operator/0.9.0/manifests/argocd-operator-webhook-service_v1_service.yaml
- operators/argocd-operator/0.9.0/manifests/argocd-operator.v0.9.0.clusterserviceversion.yaml
- operators/argocd-operator/0.9.0/manifests/argoproj.io_applications.yaml
- operators/argocd-operator/0.9.0/manifests/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.9.0/manifests/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.9.0/manifests/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.9.0/manifests/argoproj.io_argocds.yaml
- operators/argocd-operator/0.9.0/metadata/annotations.yaml
> operator argocd-operator (0.9.0)

- operators/opendatahub-operator/2.10.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.10.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.10.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.10.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.10.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.10.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.10.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.10.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.10.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.10.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.10.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.10.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.10.0)

- operators/external-secrets-operator/0.9.14/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.14/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.14/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.14/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.14/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.14/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.14/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.14
> operator external-secrets-operator (0.9.14)

- operators/koku-metrics-operator/3.2.1/Dockerfile
- operators/koku-metrics-operator/3.2.1/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- operators/koku-metrics-operator/3.2.1/manifests/koku-metrics-operator.clusterserviceversion.yaml
- operators/koku-metrics-operator/3.2.1/metadata/annotations.yaml
- operators/koku-metrics-operator/3.2.1/tests/scorecard/config.yaml
> operator koku-metrics-operator (3.2.1)

- operators/dapr-kubernetes-operator/0.0.6/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
- operators/dapr-kubernetes-operator/0.0.6/manifests/operator.dapr.io_daprcontrolplanes.yaml
- operators/dapr-kubernetes-operator/0.0.6/manifests/operator.dapr.io_daprcruiscontrols.yaml
- operators/dapr-kubernetes-operator/0.0.6/manifests/operator.dapr.io_daprinstances.yaml
- operators/dapr-kubernetes-operator/0.0.6/metadata/annotations.yaml
- operators/dapr-kubernetes-operator/0.0.6/tests/scorecard/config.yaml
> operator dapr-kubernetes-operator (0.0.6)

- operators/rabbitmq-cluster-operator/2.8.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.8.0/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/2.8.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.8.0/metadata/annotations.yaml
> operator rabbitmq-cluster-operator (2.8.0)

- operators/sailoperator/ci.yaml
* [x ] Are you familiar with our [operator pipeline](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/community-operator-pipeline.md)?
* [x ] Have you tested your Operator with all Custom Resource Definitions [packaging](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md)?
* [x ] Have you tested your Operator in all supported [installation modes](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/operator-ci-yaml.md##Operator-versioning)?
* [x ] Have you considered whether you want to use [semantic versioning …
> Replace maistra-bot with openshift-service-mesh-bot

- operators/yaks/0.18.0/manifests/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.18.0/manifests/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.18.0/manifests/yaks.v0.18.0.clusterserviceversion.yaml
- operators/yaks/0.18.0/metadata/annotations.yaml
- operators/yaks/0.18.0/tests/scorecard/config.yaml
> operator yaks (0.18.0)

- operators/portworx-essentials/23.10.5/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/23.10.5/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/23.10.5/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/23.10.5/metadata/annotations.yaml
> operator portworx-essentials (23.10.5)

- operators/verticadb-operator/2.1.2/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.1.2/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.1.2/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.1.2/manifests/vertica.com_verticarestorepointsqueries.yaml
- operators/verticadb-operator/2.1.2/manifests/vertica.com_verticascrutinizers.yaml
- operators/verticadb-operator/2.1.2/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.1.2/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.1.2/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/2.1.2/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/2.1.2/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.1.2/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.1.2/metadata/annotations.yaml
- operators/verticadb-operator/2.1.2/tests/scorecard/config.yaml
> operator verticadb-operator (2.1.2)

- operators/dapr-kubernetes-operator/0.0.7/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
- operators/dapr-kubernetes-operator/0.0.7/manifests/operator.dapr.io_daprcontrolplanes.yaml
- operators/dapr-kubernetes-operator/0.0.7/manifests/operator.dapr.io_daprcruiscontrols.yaml
- operators/dapr-kubernetes-operator/0.0.7/manifests/operator.dapr.io_daprinstances.yaml
- operators/dapr-kubernetes-operator/0.0.7/metadata/annotations.yaml
- operators/dapr-kubernetes-operator/0.0.7/tests/scorecard/config.yaml
> operator dapr-kubernetes-operator (0.0.7)

- operators/codeflare-operator/1.3.1/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.3.1/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.3.1/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.3.1/metadata/annotations.yaml
- operators/codeflare-operator/1.3.1/tests/scorecard/config.yaml
> operator codeflare-operator (1.3.1)

- operators/argocd-operator/0.9.1/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- operators/argocd-operator/0.9.1/manifests/argocd-operator-manager-config_v1_configmap.yaml
- operators/argocd-operator/0.9.1/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/argocd-operator/0.9.1/manifests/argocd-operator-webhook-service_v1_service.yaml
- operators/argocd-operator/0.9.1/manifests/argocd-operator.v0.9.1.clusterserviceversion.yaml
- operators/argocd-operator/0.9.1/manifests/argoproj.io_applications.yaml
- operators/argocd-operator/0.9.1/manifests/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.9.1/manifests/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.9.1/manifests/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.9.1/manifests/argoproj.io_argocds.yaml
- operators/argocd-operator/0.9.1/metadata/annotations.yaml
> operator argocd-operator (0.9.1)

- operators/gitlab-operator-kubernetes/0.30.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.30.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.30.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.30.2)

- operators/dapr-kubernetes-operator/0.0.8/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
- operators/dapr-kubernetes-operator/0.0.8/manifests/operator.dapr.io_daprcontrolplanes.yaml
- operators/dapr-kubernetes-operator/0.0.8/manifests/operator.dapr.io_daprcruiscontrols.yaml
- operators/dapr-kubernetes-operator/0.0.8/manifests/operator.dapr.io_daprinstances.yaml
- operators/dapr-kubernetes-operator/0.0.8/metadata/annotations.yaml
- operators/dapr-kubernetes-operator/0.0.8/tests/scorecard/config.yaml
> operator dapr-kubernetes-operator (0.0.8)

- operators/gitlab-operator-kubernetes/0.30.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.30.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.30.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.30.1)

- operators/camel-k/2.3.0/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/camel-k.v2.3.0.clusterserviceversion.yaml
- operators/camel-k/2.3.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.3.0/metadata/annotations.yaml
- operators/camel-k/2.3.0/tests/scorecard/config.yaml
> operator camel-k (2.3.0)

- operators/yaks/0.19.0/manifests/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.19.0/manifests/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.19.0/manifests/yaks.v0.19.0.clusterserviceversion.yaml
- operators/yaks/0.19.0/metadata/annotations.yaml
- operators/yaks/0.19.0/tests/scorecard/config.yaml
> operator yaks (0.19.0)

- operators/awx-operator/2.15.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.15.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.15.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.15.0/manifests/awx-operator.v2.15.0.clusterserviceversion.yaml
- operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.15.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.15.0/metadata/annotations.yaml
- operators/awx-operator/2.15.0/tests/scorecard/config.yaml
operator awx-operator (2.15.0)
> operator awx-operator (2.15.0)

- operators/multi-nic-cni-operator/1.2.3/bundle.Dockerfile
- operators/multi-nic-cni-operator/1.2.3/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multinic.fms.io_cidrs.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multinic.fms.io_configs.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multinic.fms.io_deviceclasses.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multinic.fms.io_hostinterfaces.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multinic.fms.io_ippools.yaml
- operators/multi-nic-cni-operator/1.2.3/manifests/multinic.fms.io_multinicnetworks.yaml
- operators/multi-nic-cni-operator/1.2.3/metadata/annotations.yaml
- operators/multi-nic-cni-operator/1.2.3/tests/scorecard/config.yaml
> operator multi-nic-cni-operator (1.2.3)

- operators/patterns-operator/0.0.44/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.44/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.44/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.44/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.44/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.44/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.44/metadata/annotations.yaml
- operators/patterns-operator/0.0.44/tests/scorecard/config.yaml
> operator patterns-operator (0.0.44)

- operators/klusterlet/0.13.1/manifests/klusterlet.clusterserviceversion.yaml
- operators/klusterlet/0.13.1/manifests/operator.open-cluster-management.io_klusterlets.yaml
- operators/klusterlet/0.13.1/metadata/annotations.yaml
> operator klusterlet (0.13.1)

- operators/neuvector-community-operator/1.4.5/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.4.5/manifests/neuvector-operator.v1.4.5.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.4.5/metadata/annotations.yaml
> operator neuvector-community-operator (1.4.5)

- operators/gitlab-operator-kubernetes/0.30.3/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.30.3/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.30.3/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.30.3/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.30.3)

- operators/multi-nic-cni-operator/1.3.0/bundle.Dockerfile
- operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_cidrs.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_configs.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_deviceclasses.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_hostinterfaces.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_ippools.yaml
- operators/multi-nic-cni-operator/1.3.0/manifests/multinic.fms.io_multinicnetworks.yaml
- operators/multi-nic-cni-operator/1.3.0/metadata/annotations.yaml
- operators/multi-nic-cni-operator/1.3.0/tests/scorecard/config.yaml
> operator multi-nic-cni-operator (1.3.0)

- config.yaml
> Add test ignore for assisted-service-operator

- operators/eclipse-amlen-operator/1.0.2/bundle.Dockerfile
- operators/eclipse-amlen-operator/1.0.2/manifests/amlen-controller-manager-metrics-service_v1_service.yaml
- operators/eclipse-amlen-operator/1.0.2/manifests/amlen-manager-config_v1_configmap.yaml
- operators/eclipse-amlen-operator/1.0.2/manifests/amlen-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eclipse-amlen-operator/1.0.2/manifests/eclipse-amlen-operator.clusterserviceversion.yaml
- operators/eclipse-amlen-operator/1.0.2/manifests/eclipse.org_amlens.yaml
- operators/eclipse-amlen-operator/1.0.2/metadata/annotations.yaml
- operators/eclipse-amlen-operator/1.0.2/tests/scorecard/config.yaml
add support field and update operator image
--
> operator eclipse-amlen-operator (1.0.2)

- operators/mongodb-atlas-kubernetes/2.2.1/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.2.1/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.2.1)

- operators/cass-operator-community/1.19.1/manifests/cass-operator-manager-config_v1_configmap.yaml
- operators/cass-operator-community/1.19.1/manifests/cass-operator-webhook-service_v1_service.yaml
- operators/cass-operator-community/1.19.1/manifests/cass-operator.clusterserviceversion.yaml
- operators/cass-operator-community/1.19.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml
- operators/cass-operator-community/1.19.1/manifests/control.k8ssandra.io_cassandratasks.yaml
- operators/cass-operator-community/1.19.1/metadata/annotations.yaml
- operators/cass-operator-community/1.19.1/tests/scorecard/config.yaml
> operator cass-operator-community (1.19.1)

- operators/patterns-operator/0.0.45/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.45/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.45/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.45/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.45/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.45/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.45/metadata/annotations.yaml
- operators/patterns-operator/0.0.45/tests/scorecard/config.yaml
> operator patterns-operator (0.0.45)

- operators/codeflare-operator/1.4.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.4.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.4.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.4.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.4.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.4.0/metadata/annotations.yaml
- operators/codeflare-operator/1.4.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.4.0)

- operators/move2kube-operator/0.3.13/bundle.Dockerfile
- operators/move2kube-operator/0.3.13/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
- operators/move2kube-operator/0.3.13/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/move2kube-operator/0.3.13/manifests/move2kube-operator.clusterserviceversion.yaml
- operators/move2kube-operator/0.3.13/manifests/move2kube.konveyor.io_move2kubes.yaml
- operators/move2kube-operator/0.3.13/metadata/annotations.yaml
- operators/move2kube-operator/0.3.13/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.13
> operator move2kube-operator (0.3.13)

- operators/patterns-operator/0.0.46/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.46/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.46/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.46/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.46/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.46/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.46/metadata/annotations.yaml
- operators/patterns-operator/0.0.46/tests/scorecard/config.yaml
> operator patterns-operator (0.0.46)

- operators/gitlab-operator-kubernetes/0.31.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.31.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.31.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.31.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.31.0)

- operators/deployment-validation-operator/0.7.6/manifests/deploymentvalidationoperator-service.yaml
- operators/deployment-validation-operator/0.7.6/manifests/deploymentvalidationoperator.0.7.6.clusterserviceversion.yaml
- operators/deployment-validation-operator/0.7.6/metadata/annotations.yaml
- operators/deployment-validation-operator/0.7.6/tests/scorecard/config.yaml
> operator deployment-validation-operator (0.7.6)

- operators/project-quay/3.10.5/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.5/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.5/metadata/annotations.yaml
Add 3.10.5 to community operators
> operator project-quay (3.10.5)

- operators/opendatahub-operator/2.11.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.11.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.11.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.11.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.11.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.11.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.11.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.11.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.11.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.11.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.11.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.11.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.11.0)

- operators/ndmspc-operator/0.20240412.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.20240412.0/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.20240412.0/metadata/annotations.yaml
- operators/ndmspc-operator/0.20240412.0/tests/scorecard/config.yaml
> operator ndmspc-operator (0.20240412.0)

- operators/awx-operator/2.16.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.16.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.16.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.16.0/manifests/awx-operator.v2.16.0.clusterserviceversion.yaml
- operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.16.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.16.0/metadata/annotations.yaml
- operators/awx-operator/2.16.0/tests/scorecard/config.yaml
operator awx-operator (2.16.0)
> operator awx-operator (2.16.0)

- operators/opendatahub-operator/2.8.1/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.8.1/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.8.1/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.8.1/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.8.1/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.8.1/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.8.1/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.8.1/metadata/annotations.yaml
- operators/opendatahub-operator/2.8.1/tests/scorecard/config.yaml
> operator opendatahub-operator (2.8.1)

- operators/korrel8r/0.1.3/manifests/korrel8r-controller-manager-metrics-service_v1_service.yaml
- operators/korrel8r/0.1.3/manifests/korrel8r-default_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/korrel8r/0.1.3/manifests/korrel8r-instance_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/korrel8r/0.1.3/manifests/korrel8r-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/korrel8r/0.1.3/manifests/korrel8r.clusterserviceversion.yaml
- operators/korrel8r/0.1.3/manifests/korrel8r.openshift.io_korrel8rs.yaml
- operators/korrel8r/0.1.3/metadata/annotations.yaml
- operators/korrel8r/0.1.3/tests/scorecard/config.yaml
Signed-off-by: Alan Conway <aconway@redhat.com>
> operator korrel8r (0.1.3)

- operators/mongodb-atlas-kubernetes/2.2.2/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.2.2/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.2.2)

- operators/cluster-aas-operator/0.1.4/manifests/argo_cd_cluser_rb.yaml
- operators/cluster-aas-operator/0.1.4/manifests/argo_cd_cluster_role.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-repo-bridge.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator-webhook-service_v1_service.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster-aas-operator.clusterserviceversion.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster_templates_user_ct_role.yaml
- operators/cluster-aas-operator/0.1.4/manifests/cluster_templates_user_role.yaml
- operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
- operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml
- operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplates.yaml
- operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_clustertemplatesetup.yaml
- operators/cluster-aas-operator/0.1.4/manifests/clustertemplate.openshift.io_config.yaml
- operators/cluster-aas-operator/0.1.4/metadata/annotations.yaml
- operators/cluster-aas-operator/0.1.4/metadata/dependencies.yaml
- operators/cluster-aas-operator/0.1.4/tests/scorecard/config.yaml
> operator cluster-aas-operator (0.1.4)

- operators/patterns-operator/0.0.47/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.47/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.47/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.47/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.47/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.47/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.47/metadata/annotations.yaml
- operators/patterns-operator/0.0.47/tests/scorecard/config.yaml
> operator patterns-operator (0.0.47)

- operators/gitlab-operator-kubernetes/0.31.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/0.31.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/0.31.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/0.31.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (0.31.1)

- operators/patterns-operator/0.0.48/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.48/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.48/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.48/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.48/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.48/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.48/metadata/annotations.yaml
- operators/patterns-operator/0.0.48/tests/scorecard/config.yaml
> operator patterns-operator (0.0.48)

- operators/kaoto-operator/ci.yaml
> Added Kaoto-bot as reviewer for the Kaoto operator

- operators/external-secrets-operator/0.9.16/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.16/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.16/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.16/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.16/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.16/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.16/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.16
> operator external-secrets-operator (0.9.16)

- operators/awx-operator/2.16.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.16.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.16.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.16.1/manifests/awx-operator.v2.16.1.clusterserviceversion.yaml
- operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.16.1/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.16.1/metadata/annotations.yaml
- operators/awx-operator/2.16.1/tests/scorecard/config.yaml
operator awx-operator (2.16.1)
> operator awx-operator (2.16.1)

- operators/external-secrets-operator/0.9.17/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.17/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.17/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.17/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.17/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.17/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.17/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.17
> operator external-secrets-operator (0.9.17)

- operators/opendatahub-operator/2.11.1/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.11.1/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.11.1/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.11.1/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.11.1/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.11.1/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.11.1/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.11.1/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.11.1/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.11.1/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.11.1/metadata/annotations.yaml
- operators/opendatahub-operator/2.11.1/tests/scorecard/config.yaml
> operator opendatahub-operator (2.11.1)

- operators/patterns-operator/0.0.49/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.49/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.49/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.49/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.49/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.49/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.49/metadata/annotations.yaml
- operators/patterns-operator/0.0.49/tests/scorecard/config.yaml
> operator patterns-operator (0.0.49)

- operators/apicurio-registry/1.1.2-v2.5.11.final/bundle.Dockerfile
- operators/apicurio-registry/1.1.2-v2.5.11.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
- operators/apicurio-registry/1.1.2-v2.5.11.final/manifests/registry.apicur.io_apicurioregistries.yaml
- operators/apicurio-registry/1.1.2-v2.5.11.final/metadata/annotations.yaml
- operators/apicurio-registry/1.1.2-v2.5.11.final/tests/scorecard/config.yaml
> operator apicurio-registry (1.1.2-v2.5.11.final)

- operators/limitador-operator/0.8.0/bundle.Dockerfile
- operators/limitador-operator/0.8.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml
- operators/limitador-operator/0.8.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
- operators/limitador-operator/0.8.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/limitador-operator/0.8.0/manifests/limitador-operator.clusterserviceversion.yaml
- operators/limitador-operator/0.8.0/manifests/limitador.kuadrant.io_limitadors.yaml
- operators/limitador-operator/0.8.0/metadata/annotations.yaml
- operators/limitador-operator/0.8.0/tests/scorecard/config.yaml
> operator limitador-operator (0.8.0)

- operators/dns-operator/0.2.0/manifests/dns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/dns-operator/0.2.0/manifests/dns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dns-operator/0.2.0/manifests/dns-operator.clusterserviceversion.yaml
- operators/dns-operator/0.2.0/manifests/kuadrant.io_dnsrecords.yaml
- operators/dns-operator/0.2.0/manifests/kuadrant.io_managedzones.yaml
- operators/dns-operator/0.2.0/metadata/annotations.yaml
- operators/dns-operator/0.2.0/tests/scorecard/config.yaml
> operator dns-operator (0.2.0)

- operators/forklift-operator/2.6.1/manifests/forklift-operator.clusterserviceversion.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_hooks.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_hosts.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_migrations.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_networkmaps.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_plans.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_providers.yaml
- operators/forklift-operator/2.6.1/manifests/forklift.konveyor.io_storagemaps.yaml
- operators/forklift-operator/2.6.1/metadata/annotations.yaml
> operator forklift-operator (2.6.1)

- operators/camel-k/2.3.1/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/camel-k.v2.3.1.clusterserviceversion.yaml
- operators/camel-k/2.3.1/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.3.1/metadata/annotations.yaml
- operators/camel-k/2.3.1/tests/scorecard/config.yaml
> operator camel-k (2.3.1)

- operators/bpfman-operator/0.4.1/bundle.Dockerfile
- operators/bpfman-operator/0.4.1/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-config_v1_configmap.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-daemon_v1_serviceaccount.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-operator.clusterserviceversion.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_bpfprograms.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_fentryprograms.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_fexitprograms.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_kprobeprograms.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_tcprograms.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_tracepointprograms.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_uprobeprograms.yaml
- operators/bpfman-operator/0.4.1/manifests/bpfman.io_xdpprograms.yaml
- operators/bpfman-operator/0.4.1/metadata/annotations.yaml
- operators/bpfman-operator/0.4.1/metadata/dependencies.yaml
- operators/bpfman-operator/0.4.1/tests/scorecard/config.yaml
- operators/bpfman-operator/ci.yaml
Add the bpfman-operator for release 0.4.1
~~This takes over for the out of date bpfd
operator, which we'll remove.~~
Follow up from https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3778
Looks like I still can't remove the old operator :/ 
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo …
> operator bpfman-operator (0.4.1)

- operators/kuadrant-operator/0.7.1/bundle.Dockerfile
- operators/kuadrant-operator/0.7.1/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant-operator.clusterserviceversion.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant.io_authpolicies.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant.io_dnspolicies.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant.io_kuadrants.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant.io_ratelimitpolicies.yaml
- operators/kuadrant-operator/0.7.1/manifests/kuadrant.io_tlspolicies.yaml
- operators/kuadrant-operator/0.7.1/metadata/annotations.yaml
- operators/kuadrant-operator/0.7.1/metadata/dependencies.yaml
- operators/kuadrant-operator/0.7.1/tests/scorecard/config.yaml
- operators/kuadrant-operator/ci.yaml
> operator kuadrant-operator (0.7.1)

- operators/tempo-operator/0.10.0/bundle.Dockerfile
- operators/tempo-operator/0.10.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.10.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.10.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.10.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.10.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.10.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.10.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.10.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.10.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.10.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.10.0/metadata/annotations.yaml
- operators/tempo-operator/0.10.0/tests/scorecard/config.yaml
Release tempo-operator `0.10.0`.
> operator tempo-operator (0.10.0)

- operators/dynatrace-operator/1.1.0/Dockerfile
- operators/dynatrace-operator/1.1.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.1.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.1.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.1.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.1.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.1.0/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.1.0/metadata/annotations.yaml
> operator dynatrace-operator (1.1.0)

- operators/skupper-operator/1.7.0/manifests/skupper-operator.v1.7.0.clusterserviceversion.yaml
- operators/skupper-operator/1.7.0/metadata/annotations.yaml
> operator skupper-operator (1.7.0)

- operators/snapscheduler/3.4.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
- operators/snapscheduler/3.4.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
- operators/snapscheduler/3.4.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/snapscheduler/3.4.0/manifests/snapscheduler.backube_snapshotschedules.yaml
- operators/snapscheduler/3.4.0/manifests/snapscheduler.clusterserviceversion.yaml
- operators/snapscheduler/3.4.0/metadata/annotations.yaml
- operators/snapscheduler/3.4.0/tests/scorecard/config.yaml
> operator snapscheduler (3.4.0)

- operators/patch-operator/0.1.11/Dockerfile
- operators/patch-operator/0.1.11/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/patch-operator/0.1.11/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patch-operator/0.1.11/manifests/patch-operator-manager-config_v1_configmap.yaml
- operators/patch-operator/0.1.11/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patch-operator/0.1.11/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/patch-operator/0.1.11/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patch-operator/0.1.11/manifests/patch-operator-webhook-service_v1_service.yaml
- operators/patch-operator/0.1.11/manifests/patch-operator.clusterserviceversion.yaml
- operators/patch-operator/0.1.11/manifests/redhatcop.redhat.io_patches.yaml
- operators/patch-operator/0.1.11/metadata/annotations.yaml
- operators/patch-operator/0.1.11/tests/scorecard/config.yaml
> operator patch-operator (0.1.11)

- operators/external-secrets-operator/0.9.18/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.18/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.18/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.18/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.18/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.18/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.18/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.18
> operator external-secrets-operator (0.9.18)

- operators/codeflare-operator/1.4.1/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.4.1/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.4.1/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.4.1/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.4.1/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.4.1/metadata/annotations.yaml
- operators/codeflare-operator/1.4.1/tests/scorecard/config.yaml
> operator codeflare-operator (1.4.1)

- operators/gitwebhook-operator/0.1.2/Dockerfile
- operators/gitwebhook-operator/0.1.2/manifests/gitwebhook-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/gitwebhook-operator/0.1.2/manifests/gitwebhook-operator-controller-manager-metrics-service_v1_service.yaml
- operators/gitwebhook-operator/0.1.2/manifests/gitwebhook-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitwebhook-operator/0.1.2/manifests/gitwebhook-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/gitwebhook-operator/0.1.2/manifests/gitwebhook-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/gitwebhook-operator/0.1.2/manifests/gitwebhook-operator-webhook-service_v1_service.yaml
- operators/gitwebhook-operator/0.1.2/manifests/gitwebhook-operator.clusterserviceversion.yaml
- operators/gitwebhook-operator/0.1.2/manifests/redhatcop.redhat.io_gitwebhooks.yaml
- operators/gitwebhook-operator/0.1.2/metadata/annotations.yaml
- operators/gitwebhook-operator/0.1.2/tests/scorecard/config.yaml
> operator gitwebhook-operator (0.1.2)

- operators/verticadb-operator/ci.yaml
> Add more reviews for verticadb-operator

- operators/verticadb-operator/2.1.3/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.1.3/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.1.3/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.1.3/manifests/vertica.com_verticarestorepointsqueries.yaml
- operators/verticadb-operator/2.1.3/manifests/vertica.com_verticascrutinizers.yaml
- operators/verticadb-operator/2.1.3/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.1.3/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.1.3/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/2.1.3/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/2.1.3/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.1.3/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.1.3/metadata/annotations.yaml
- operators/verticadb-operator/2.1.3/tests/scorecard/config.yaml
> operator verticadb-operator (2.1.3)

- operators/sap-data-intelligence-observer-operator/1.0.5/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml
- operators/sap-data-intelligence-observer-operator/1.0.5/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/sap-data-intelligence-observer-operator/1.0.5/manifests/observer-operator.clusterserviceversion.yaml
- operators/sap-data-intelligence-observer-operator/1.0.5/manifests/sdi.sap-redhat.io_sdiobservers.yaml
- operators/sap-data-intelligence-observer-operator/1.0.5/metadata/annotations.yaml
> operator sap-data-intelligence-observer-operator (1.0.5)

- operators/opendatahub-operator/2.12.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.12.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.12.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.12.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.12.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.12.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.12.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.12.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.12.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.12.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.12.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.12.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.12.0)

- operators/flux/2.3.0/manifests/alert.crd.yaml
- operators/flux/2.3.0/manifests/bucket.crd.yaml
- operators/flux/2.3.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml
- operators/flux/2.3.0/manifests/crd-controller-flux-system.clusterrole.yaml
- operators/flux/2.3.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml
- operators/flux/2.3.0/manifests/flux-edit-flux-system.clusterrole.yaml
- operators/flux/2.3.0/manifests/flux-view-flux-system.clusterrole.yaml
- operators/flux/2.3.0/manifests/flux.v2.3.0.clusterserviceversion.yaml
- operators/flux/2.3.0/manifests/gitrepository.crd.yaml
- operators/flux/2.3.0/manifests/helmchart.crd.yaml
- operators/flux/2.3.0/manifests/helmrelease.crd.yaml
- operators/flux/2.3.0/manifests/helmrepository.crd.yaml
- operators/flux/2.3.0/manifests/imagepolicy.crd.yaml
- operators/flux/2.3.0/manifests/imagerepository.crd.yaml
- operators/flux/2.3.0/manifests/imageupdateautomation.crd.yaml
- operators/flux/2.3.0/manifests/kustomization.crd.yaml
- operators/flux/2.3.0/manifests/notification-controller.service.yaml
- operators/flux/2.3.0/manifests/ocirepository.crd.yaml
- operators/flux/2.3.0/manifests/provider.crd.yaml
- operators/flux/2.3.0/manifests/receiver.crd.yaml
- operators/flux/2.3.0/manifests/source-controller.service.yaml
- operators/flux/2.3.0/manifests/webhook-receiver.service.yaml
- operators/flux/2.3.0/metadata/annotations.yaml
> operator flux (2.3.0)

- operators/rabbitmq-messaging-topology-operator/1.14.1/bundle.Dockerfile
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_bindings.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_exchanges.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_federations.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_operatorpolicies.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_permissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_policies.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_queues.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_schemareplications.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_shovels.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_superstreams.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_topicpermissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_users.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.com_vhosts.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/manifests/rabbitmq.webhook-service.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.1/metadata/annotations.yaml
> operator rabbitmq-messaging-topology-operator (1.14.1)

- operators/rabbitmq-cluster-operator/2.9.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.9.0/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/2.9.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.9.0/metadata/annotations.yaml
> operator rabbitmq-cluster-operator (2.9.0)

- operators/multicluster-global-hub-operator/1.2.0-dev.20240516/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.2.0-dev.20240516/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.2.0-dev.20240516/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.2.0-dev.20240516)

- operators/edp-keycloak-operator/1.21.0/manifests/client-secret-policy-sample_v1_secret.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakclients.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
- operators/edp-keycloak-operator/1.21.0/manifests/v1.edp.epam.com_keycloaks.yaml
- operators/edp-keycloak-operator/1.21.0/metadata/annotations.yaml
- operators/edp-keycloak-operator/1.21.0/tests/scorecard/config.yaml
> operator edp-keycloak-operator (1.21.0)

- operators/eclipse-amlen-operator/1.1.0/bundle.Dockerfile
- operators/eclipse-amlen-operator/1.1.0/manifests/amlen-controller-manager-metrics-service_v1_service.yaml
- operators/eclipse-amlen-operator/1.1.0/manifests/amlen-manager-config_v1_configmap.yaml
- operators/eclipse-amlen-operator/1.1.0/manifests/amlen-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eclipse-amlen-operator/1.1.0/manifests/eclipse-amlen-operator.clusterserviceversion.yaml
- operators/eclipse-amlen-operator/1.1.0/manifests/eclipse.org_amlens.yaml
- operators/eclipse-amlen-operator/1.1.0/metadata/annotations.yaml
- operators/eclipse-amlen-operator/1.1.0/tests/scorecard/config.yaml
> operator eclipse-amlen-operator (1.1.0)

- operators/opendatahub-operator/2.12.1/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.12.1/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.12.1/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.12.1/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.12.1/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.12.1/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.12.1/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.12.1/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.12.1/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.12.1/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.12.1/metadata/annotations.yaml
- operators/opendatahub-operator/2.12.1/tests/scorecard/config.yaml
> operator opendatahub-operator (2.12.1)

- operators/forklift-operator/2.6.2/manifests/forklift-operator.clusterserviceversion.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_hooks.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_hosts.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_migrations.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_networkmaps.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_plans.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_providers.yaml
- operators/forklift-operator/2.6.2/manifests/forklift.konveyor.io_storagemaps.yaml
- operators/forklift-operator/2.6.2/metadata/annotations.yaml
- operators/forklift-operator/2.6.2/tests/scorecard/config.yaml
> operator forklift-operator (2.6.2)

- operators/kubecost/2.2.4/bundle.Dockerfile
- operators/kubecost/2.2.4/manifests/charts.kubecost.com_costanalyzers.yaml
- operators/kubecost/2.2.4/manifests/kubecost-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kubecost/2.2.4/manifests/kubecost-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kubecost/2.2.4/manifests/kubecost-operator.clusterserviceversion.yaml
- operators/kubecost/2.2.4/metadata/annotations.yaml
- operators/kubecost/2.2.4/tests/scorecard/config.yaml
Signed-off-by: chipzoller <chipzoller@gmail.com>
--
> operator kubecost (2.2.4)

- operators/layer7-operator/1.0.6/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
- operators/layer7-operator/1.0.6/manifests/layer7-operator-manager-config_v1_configmap.yaml
- operators/layer7-operator/1.0.6/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/layer7-operator/1.0.6/manifests/layer7-operator-webhook-service_v1_service.yaml
- operators/layer7-operator/1.0.6/manifests/layer7-operator.clusterserviceversion.yaml
- operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_gateways.yaml
- operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_l7apis.yaml
- operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_l7portals.yaml
- operators/layer7-operator/1.0.6/manifests/security.brcmlabs.com_repositories.yaml
- operators/layer7-operator/1.0.6/metadata/annotations.yaml
- operators/layer7-operator/1.0.6/tests/scorecard/config.yaml
> operator layer7-operator (1.0.6)

- operators/gitlab-operator-kubernetes/1.0.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.0.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.0.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.0.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.0.0)

- operators/awx-operator/2.17.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.17.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.17.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.17.0/manifests/awx-operator.v2.17.0.clusterserviceversion.yaml
- operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.17.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.17.0/metadata/annotations.yaml
- operators/awx-operator/2.17.0/tests/scorecard/config.yaml
operator awx-operator (2.17.0)
> operator awx-operator (2.17.0)

- operators/gitlab-operator-kubernetes/1.0.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.0.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.0.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.0.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.0.1)

- operators/codeflare-operator/1.4.2/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.4.2/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.4.2/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.4.2/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.4.2/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.4.2/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.4.2/metadata/annotations.yaml
- operators/codeflare-operator/1.4.2/tests/scorecard/config.yaml
> operator codeflare-operator (1.4.2)

- operators/hawtio-operator/1.1.0/manifests/hawt.io_hawtios.yaml
- operators/hawtio-operator/1.1.0/manifests/hawtio-operator.clusterserviceversion.yaml
- operators/hawtio-operator/1.1.0/metadata/annotations.yaml
- operators/hawtio-operator/1.1.0/tests/scorecard/config.yaml
> operator hawtio-operator (1.1.0)

- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-controller-manager-metrics-service_v1_service.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-manager-config_v1_configmap.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-labeller_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-labeller_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-labeller_v1_serviceaccount.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-metrics_rbac.authorization.k8s.io_v1_role.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-metrics_v1_service.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-node-metrics_v1_serviceaccount.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd-gpu-operator.clusterserviceversion.yaml
- operators/amd-gpu-operator/0.0.4/manifests/amd.io_deviceconfigs.yaml
- operators/amd-gpu-operator/0.0.4/metadata/annotations.yaml
- operators/amd-gpu-operator/0.0.4/test/scorecard/config.yaml
> operator amd-gpu-operator (0.0.4)

- operators/grafana-operator/5.9.2/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.9.2/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.9.2/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.9.2/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.9.2/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.9.2/metadata/annotations.yaml
> operator grafana-operator (5.9.2)

- operators/project-quay/3.11.1/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.1/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.1/metadata/annotations.yaml
Add 3.11.1 to community operators
> operator project-quay (3.11.1)

- operators/pelorus-operator/0.0.9/manifests/charts.pelorus.dora-metrics.io_peloruses.yaml
- operators/pelorus-operator/0.0.9/manifests/pelorus-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pelorus-operator/0.0.9/manifests/pelorus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pelorus-operator/0.0.9/manifests/pelorus-operator.clusterserviceversion.yaml
- operators/pelorus-operator/0.0.9/metadata/annotations.yaml
- operators/pelorus-operator/0.0.9/metadata/properties.yaml
- operators/pelorus-operator/0.0.9/tests/scorecard/config.yaml
This PR is do publish a new version of the Pelorus operator after merging a new version of [Pelorus](https://github.com/dora-metrics/pelorus)
Please review it
- @etsauer
- @KevinMGranger
- @mateusoliveira43
- @mpryc
- @weshayutin
After review, comment /unhold in This PR to merge it.
> operator pelorus-operator (0.0.9)

- operators/external-secrets-operator/0.9.19/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.19/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.19/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.19/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.19/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.19/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.19/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.19
> operator external-secrets-operator (0.9.19)

- operators/awx-operator/2.18.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.18.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.18.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.18.0/manifests/awx-operator.v2.18.0.clusterserviceversion.yaml
- operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.18.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.18.0/metadata/annotations.yaml
- operators/awx-operator/2.18.0/tests/scorecard/config.yaml
operator awx-operator (2.18.0)
> operator awx-operator (2.18.0)

- operators/camel-k/2.3.2/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/camel-k.v2.3.2.clusterserviceversion.yaml
- operators/camel-k/2.3.2/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.3.2/metadata/annotations.yaml
- operators/camel-k/2.3.2/tests/scorecard/config.yaml
> operator camel-k (2.3.2)

- operators/forklift-operator/2.5.7/manifests/forklift-operator.clusterserviceversion.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_hooks.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_hosts.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_migrations.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_networkmaps.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_plans.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_providers.yaml
- operators/forklift-operator/2.5.7/manifests/forklift.konveyor.io_storagemaps.yaml
- operators/forklift-operator/2.5.7/metadata/annotations.yaml
- operators/forklift-operator/2.5.7/tests/scorecard/config.yaml
> operator forklift-operator (2.5.7)

- operators/codeflare-operator/1.4.3/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.4.3/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.4.3/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.4.3/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.4.3/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.4.3/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.4.3/metadata/annotations.yaml
- operators/codeflare-operator/1.4.3/tests/scorecard/config.yaml
> operator codeflare-operator (1.4.3)

- operators/opendatahub-operator/2.13.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.13.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.13.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.13.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.13.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.13.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.13.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.13.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.13.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.13.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.13.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.13.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.13.0)

- operators/portworx-essentials/24.1.0/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/24.1.0/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/24.1.0/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/24.1.0/metadata/annotations.yaml
> operator portworx-essentials (24.1.0)

- operators/cluster-aas-operator/0.1.5/manifests/argo_cd_cluser_rb.yaml
- operators/cluster-aas-operator/0.1.5/manifests/argo_cd_cluster_role.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-repo-bridge.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator-webhook-service_v1_service.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster-aas-operator.clusterserviceversion.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster_templates_user_ct_role.yaml
- operators/cluster-aas-operator/0.1.5/manifests/cluster_templates_user_role.yaml
- operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
- operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml
- operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplates.yaml
- operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_clustertemplatesetup.yaml
- operators/cluster-aas-operator/0.1.5/manifests/clustertemplate.openshift.io_config.yaml
- operators/cluster-aas-operator/0.1.5/metadata/annotations.yaml
- operators/cluster-aas-operator/0.1.5/metadata/dependencies.yaml
- operators/cluster-aas-operator/0.1.5/tests/scorecard/config.yaml
> operator cluster-aas-operator (0.1.5)

- operators/patterns-operator/0.0.50/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.50/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.50/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.50/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.50/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.50/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.50/metadata/annotations.yaml
- operators/patterns-operator/0.0.50/tests/scorecard/config.yaml
> operator patterns-operator (0.0.50)

- operators/forklift-operator/2.6.3/manifests/forklift-operator.clusterserviceversion.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_hooks.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_hosts.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_migrations.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_networkmaps.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_openstackvolumepopulators.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_ovirtvolumepopulators.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_plans.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_providers.yaml
- operators/forklift-operator/2.6.3/manifests/forklift.konveyor.io_storagemaps.yaml
- operators/forklift-operator/2.6.3/metadata/annotations.yaml
- operators/forklift-operator/2.6.3/tests/scorecard/config.yaml
> operator forklift-operator (2.6.3)

- operators/rabbitmq-messaging-topology-operator/1.14.2/bundle.Dockerfile
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_bindings.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_exchanges.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_federations.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_operatorpolicies.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_permissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_policies.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_queues.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_schemareplications.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_shovels.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_superstreams.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_topicpermissions.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_users.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.com_vhosts.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/manifests/rabbitmq.webhook-service.yaml
- operators/rabbitmq-messaging-topology-operator/1.14.2/metadata/annotations.yaml
> operator rabbitmq-messaging-topology-operator (1.14.2)

- operators/yaks/0.19.2/manifests/instances.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.19.2/manifests/tests.yaks.citrusframework.org.crd.yaml
- operators/yaks/0.19.2/manifests/yaks.v0.19.2.clusterserviceversion.yaml
- operators/yaks/0.19.2/metadata/annotations.yaml
- operators/yaks/0.19.2/tests/scorecard/config.yaml
> operator yaks (0.19.2)

- operators/camel-k/2.3.3/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/camel-k.v2.3.3.clusterserviceversion.yaml
- operators/camel-k/2.3.3/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.3.3/metadata/annotations.yaml
- operators/camel-k/2.3.3/tests/scorecard/config.yaml
> operator camel-k (2.3.3)

- operators/argocd-operator/0.10.1/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- operators/argocd-operator/0.10.1/manifests/argocd-operator-manager-config_v1_configmap.yaml
- operators/argocd-operator/0.10.1/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/argocd-operator/0.10.1/manifests/argocd-operator-webhook-service_v1_service.yaml
- operators/argocd-operator/0.10.1/manifests/argocd-operator.v0.10.1.clusterserviceversion.yaml
- operators/argocd-operator/0.10.1/manifests/argoproj.io_applications.yaml
- operators/argocd-operator/0.10.1/manifests/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.10.1/manifests/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.10.1/manifests/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.10.1/manifests/argoproj.io_argocds.yaml
- operators/argocd-operator/0.10.1/manifests/argoproj.io_notificationsconfigurations.yaml
- operators/argocd-operator/0.10.1/metadata/annotations.yaml
> operator argocd-operator (0.10.1)

- operators/skupper-operator/1.7.1/manifests/skupper-operator.v1.7.1.clusterserviceversion.yaml
- operators/skupper-operator/1.7.1/metadata/annotations.yaml
> operator skupper-operator (1.7.1)

- operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil-operator-controller-manager-metrics-service_v1_service.yaml
- operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil-operator.clusterserviceversion.yaml
- operators/hyperfoil-bundle/0.26.0/manifests/hyperfoil.io_hyperfoils.yaml
- operators/hyperfoil-bundle/0.26.0/metadata/annotations.yaml
- operators/hyperfoil-bundle/0.26.0/tests/scorecard/config.yaml
> operator hyperfoil-bundle (0.26.0)

- operators/project-quay/3.10.6/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.6/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.6/metadata/annotations.yaml
Add 3.10.6 to community operators
> operator project-quay (3.10.6)

- operators/dynatrace-operator/1.1.1/Dockerfile
- operators/dynatrace-operator/1.1.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.1.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.1.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.1.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.1.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.1.1/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.1.1/metadata/annotations.yaml
> operator dynatrace-operator (1.1.1)

- operators/ncn-operator/0.0.1/manifests/cxl-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ncn-operator/0.0.1/manifests/cxl-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ncn-operator/0.0.1/manifests/cxl-operator.clusterserviceversion.yaml
- operators/ncn-operator/0.0.1/manifests/cxl.antline.com_cxls.yaml
- operators/ncn-operator/0.0.1/metadata/annotations.yaml
- operators/ncn-operator/ci.yaml
> operator ncn-operator (0.0.1)

- operators/patterns-operator/0.0.51/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.51/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.51/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.51/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.51/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.51/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.51/metadata/annotations.yaml
- operators/patterns-operator/0.0.51/tests/scorecard/config.yaml
> operator patterns-operator (0.0.51)

- operators/awx-operator/2.19.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.19.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.19.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.19.0/manifests/awx-operator.v2.19.0.clusterserviceversion.yaml
- operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.19.0/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.19.0/metadata/annotations.yaml
- operators/awx-operator/2.19.0/tests/scorecard/config.yaml
operator awx-operator (2.19.0)
> operator awx-operator (2.19.0)

- operators/koku-metrics-operator/3.3.0/Dockerfile
- operators/koku-metrics-operator/3.3.0/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- operators/koku-metrics-operator/3.3.0/manifests/koku-metrics-operator.clusterserviceversion.yaml
- operators/koku-metrics-operator/3.3.0/metadata/annotations.yaml
- operators/koku-metrics-operator/3.3.0/tests/scorecard/config.yaml
> operator koku-metrics-operator (3.3.0)

- operators/codeflare-operator/1.4.4/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.4.4/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.4.4/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.4.4/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.4.4/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.4.4/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.4.4/metadata/annotations.yaml
- operators/codeflare-operator/1.4.4/tests/scorecard/config.yaml
> operator codeflare-operator (1.4.4)

- operators/bpfman-operator/0.4.2/bundle.Dockerfile
- operators/bpfman-operator/0.4.2/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-config_v1_configmap.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-daemon_v1_serviceaccount.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-operator.clusterserviceversion.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_bpfprograms.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_fentryprograms.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_fexitprograms.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_kprobeprograms.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_tcprograms.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_tracepointprograms.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_uprobeprograms.yaml
- operators/bpfman-operator/0.4.2/manifests/bpfman.io_xdpprograms.yaml
- operators/bpfman-operator/0.4.2/metadata/annotations.yaml
- operators/bpfman-operator/0.4.2/metadata/dependencies.yaml
- operators/bpfman-operator/0.4.2/tests/scorecard/config.yaml
- operators/bpfman-operator/ci.yaml
Cut a 0.4.2 OLM release of the bpfman operator.
The main changes are updates to the clusterserviceversion.
--
> operator bpfman-operator (0.4.2)

- operators/dynatrace-operator/1.2.0/Dockerfile
- operators/dynatrace-operator/1.2.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.2.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.2.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.2.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.2.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.2.0/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.2.0/metadata/annotations.yaml
> operator dynatrace-operator (1.2.0)

- operators/patterns-operator/0.0.52/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.52/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.52/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.52/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.52/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.52/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.52/metadata/annotations.yaml
- operators/patterns-operator/0.0.52/tests/scorecard/config.yaml
> operator patterns-operator (0.0.52)

- operators/codeflare-operator/1.5.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.5.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.5.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.5.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.5.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.5.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.5.0/metadata/annotations.yaml
- operators/codeflare-operator/1.5.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.5.0)

- operators/opendatahub-operator/2.14.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.14.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.14.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.14.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.14.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.14.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.14.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.14.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.14.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.14.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.14.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.14.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.14.0)

- operators/gitlab-operator-kubernetes/1.1.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.1.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.1.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.1.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.1.1)

- operators/neuvector-community-operator/1.4.6/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.4.6/manifests/neuvector-operator.v1.4.6.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.4.6/metadata/annotations.yaml
> operator neuvector-community-operator (1.4.6)

- operators/awx-operator/2.19.1/manifests/awx-operator-awx-manager-config_v1_configmap.yaml
- operators/awx-operator/2.19.1/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml
- operators/awx-operator/2.19.1/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/awx-operator/2.19.1/manifests/awx-operator.v2.19.1.clusterserviceversion.yaml
- operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxbackups.yaml
- operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxmeshingresses.yaml
- operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxrestores.yaml
- operators/awx-operator/2.19.1/manifests/awx.ansible.com_awxs.yaml
- operators/awx-operator/2.19.1/metadata/annotations.yaml
- operators/awx-operator/2.19.1/tests/scorecard/config.yaml
operator awx-operator (2.19.1)
> operator awx-operator (2.19.1)

- operators/kuadrant-operator/0.7.2/bundle.Dockerfile
- operators/kuadrant-operator/0.7.2/manifests/kuadrant-operator-controller-manager-metrics-service_v1_service.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant-operator.clusterserviceversion.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant.io_authpolicies.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant.io_dnspolicies.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant.io_kuadrants.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant.io_ratelimitpolicies.yaml
- operators/kuadrant-operator/0.7.2/manifests/kuadrant.io_tlspolicies.yaml
- operators/kuadrant-operator/0.7.2/metadata/annotations.yaml
- operators/kuadrant-operator/0.7.2/metadata/dependencies.yaml
- operators/kuadrant-operator/0.7.2/tests/scorecard/config.yaml
> operator kuadrant-operator (0.7.2)

- operators/netobserv-operator/1.6.1-community/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/1.6.1-community/manifests/flows.netobserv.io_flowmetrics.yaml
- operators/netobserv-operator/1.6.1-community/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/1.6.1-community/manifests/netobserv-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/netobserv-operator/1.6.1-community/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/1.6.1-community/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/netobserv-operator/1.6.1-community/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/netobserv-operator/1.6.1-community/manifests/netobserv-operator.clusterserviceversion.yaml
- operators/netobserv-operator/1.6.1-community/manifests/netobserv-webhook-service_v1_service.yaml
- operators/netobserv-operator/1.6.1-community/metadata/annotations.yaml
> operator netobserv-operator (1.6.1-community)

- operators/tempo-operator/0.11.0/bundle.Dockerfile
- operators/tempo-operator/0.11.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.11.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.11.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.11.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.11.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.11.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.11.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.11.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.11.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.11.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.11.0/metadata/annotations.yaml
- operators/tempo-operator/0.11.0/tests/scorecard/config.yaml
Release tempo-operator `0.11.0`.
> operator tempo-operator (0.11.0)

- operators/external-secrets-operator/0.9.20/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.20/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.20/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.20/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.20/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.20/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.20/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.20
> operator external-secrets-operator (0.9.20)

- operators/multicluster-global-hub-operator/1.2.0/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.2.0/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.2.0/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.2.0)

- operators/tempo-operator/0.11.1/bundle.Dockerfile
- operators/tempo-operator/0.11.1/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.11.1/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.11.1/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.11.1/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.11.1/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.11.1/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.11.1/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.11.1/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.11.1/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.11.1/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.11.1/metadata/annotations.yaml
- operators/tempo-operator/0.11.1/tests/scorecard/config.yaml
Release tempo-operator `0.11.1`.
> operator tempo-operator (0.11.1)

- operators/shipwright-operator/0.13.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
- operators/shipwright-operator/0.13.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
- operators/shipwright-operator/0.13.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/shipwright-operator/0.13.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
- operators/shipwright-operator/0.13.0/manifests/shipwright-operator.clusterserviceversion.yaml
- operators/shipwright-operator/0.13.0/metadata/annotations.yaml
- operators/shipwright-operator/0.13.0/tests/scorecard/config.yaml
> operator shipwright-operator (0.13.0)

- operators/gitlab-operator-kubernetes/1.1.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.1.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.1.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.1.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.1.2)

- operators/project-quay/3.11.2/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.2/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.2/metadata/annotations.yaml
Add 3.11.2 to community operators
> operator project-quay (3.11.2)

- operators/mongodb-atlas-kubernetes/2.4.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.4.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.4.0)

- operators/trident-operator/24.6.0/manifests/trident-operator.v24.6.0.clusterserviceversion.yaml
- operators/trident-operator/24.6.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
- operators/trident-operator/24.6.0/metadata/annotations.yaml
- operators/trident-operator/ci.yaml
> operator trident-operator (24.6.0)

- operators/grafana-operator/5.10.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.10.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.10.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.10.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.10.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.10.0/metadata/annotations.yaml
> operator grafana-operator (5.10.0)

- operators/opendatahub-operator/2.15.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.15.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.15.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.15.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.15.0/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- operators/opendatahub-operator/2.15.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.15.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.15.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.15.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.15.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.15.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.15.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.15.0)

- operators/multicluster-global-hub-operator/1.2.1/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.2.1/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.2.1/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.2.1)

- operators/gitlab-operator-kubernetes/1.2.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.2.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.2.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.2.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.2.0)

- operators/dynatrace-operator/1.2.1/Dockerfile
- operators/dynatrace-operator/1.2.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.2.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.2.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.2.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.2.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.2.1/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.2.1/metadata/annotations.yaml
> operator dynatrace-operator (1.2.1)

- operators/multicluster-global-hub-operator/1.3.0-dev.20240724/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.3.0-dev.20240724/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.3.0-dev.20240724/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.3.0-dev.20240724)

- operators/argocd-operator/0.11.0/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- operators/argocd-operator/0.11.0/manifests/argocd-operator-manager-config_v1_configmap.yaml
- operators/argocd-operator/0.11.0/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/argocd-operator/0.11.0/manifests/argocd-operator-webhook-service_v1_service.yaml
- operators/argocd-operator/0.11.0/manifests/argocd-operator.v0.11.0.clusterserviceversion.yaml
- operators/argocd-operator/0.11.0/manifests/argoproj.io_applications.yaml
- operators/argocd-operator/0.11.0/manifests/argoproj.io_applicationsets.yaml
- operators/argocd-operator/0.11.0/manifests/argoproj.io_appprojects.yaml
- operators/argocd-operator/0.11.0/manifests/argoproj.io_argocdexports.yaml
- operators/argocd-operator/0.11.0/manifests/argoproj.io_argocds.yaml
- operators/argocd-operator/0.11.0/manifests/argoproj.io_notificationsconfigurations.yaml
- operators/argocd-operator/0.11.0/metadata/annotations.yaml
> operator argocd-operator (0.11.0)

- operators/move2kube-operator/0.3.14-rc.0/bundle.Dockerfile
- operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
- operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml
- operators/move2kube-operator/0.3.14-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml
- operators/move2kube-operator/0.3.14-rc.0/metadata/annotations.yaml
- operators/move2kube-operator/0.3.14-rc.0/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.14-rc.0
> operator move2kube-operator (0.3.14-rc.0)

- operators/portworx-essentials/24.1.1/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/24.1.1/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/24.1.1/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/24.1.1/metadata/annotations.yaml
> operator portworx-essentials (24.1.1)

- operators/self-node-remediation/0.9.0/manifests/self-node-remediation-controller-manager-metrics-service_v1_service.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation-manager-config_v1_configmap.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation-webhook-service_v1_service.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation.clusterserviceversion.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
- operators/self-node-remediation/0.9.0/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
- operators/self-node-remediation/0.9.0/metadata/annotations.yaml
- operators/self-node-remediation/0.9.0/tests/scorecard/config.yaml
> operator self-node-remediation (0.9.0)

- operators/group-sync-operator/0.0.29/Dockerfile
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/group-sync-operator/0.0.29/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.29/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.29/metadata/annotations.yaml
- operators/group-sync-operator/0.0.29/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.29)

- operators/group-sync-operator/0.0.30/Dockerfile
- operators/group-sync-operator/0.0.30/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.30/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.30/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.30/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.30/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.30/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.30/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.30/metadata/annotations.yaml
- operators/group-sync-operator/0.0.30/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.30)

- operators/gitlab-operator-kubernetes/1.2.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.2.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.2.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.2.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.2.1)

- operators/edp-keycloak-operator/1.22.0/manifests/client-secret-policy-sample_v1_secret.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakclients.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
- operators/edp-keycloak-operator/1.22.0/manifests/v1.edp.epam.com_keycloaks.yaml
- operators/edp-keycloak-operator/1.22.0/metadata/annotations.yaml
- operators/edp-keycloak-operator/1.22.0/tests/scorecard/config.yaml
> operator edp-keycloak-operator (1.22.0)

- operators/sap-data-intelligence-observer-operator/1.0.6/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml
- operators/sap-data-intelligence-observer-operator/1.0.6/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/sap-data-intelligence-observer-operator/1.0.6/manifests/observer-operator.clusterserviceversion.yaml
- operators/sap-data-intelligence-observer-operator/1.0.6/manifests/sdi.sap-redhat.io_sdiobservers.yaml
- operators/sap-data-intelligence-observer-operator/1.0.6/metadata/annotations.yaml
> operator sap-data-intelligence-observer-operator (1.0.6)

- operators/codeflare-operator/1.6.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.6.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.6.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.6.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.6.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.6.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.6.0/metadata/annotations.yaml
- operators/codeflare-operator/1.6.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.6.0)

- operators/project-quay/3.11.3/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.3/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.3/metadata/annotations.yaml
Add 3.11.3 to community operators
> operator project-quay (3.11.3)

- operators/external-secrets-operator/0.9.15-2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.9.15-2/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.9.15-2/metadata/annotations.yaml
- operators/external-secrets-operator/0.9.15-2/tests/scorecard/config.yaml
bump external-secrets-operator 0.9.15-2
> operator external-secrets-operator (0.9.15-2)

- operators/patch-operator/0.1.10/Dockerfile
- operators/patch-operator/0.1.10/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/patch-operator/0.1.10/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patch-operator/0.1.10/manifests/patch-operator-manager-config_v1_configmap.yaml
- operators/patch-operator/0.1.10/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patch-operator/0.1.10/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/patch-operator/0.1.10/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patch-operator/0.1.10/manifests/patch-operator-webhook-service_v1_service.yaml
- operators/patch-operator/0.1.10/manifests/patch-operator.clusterserviceversion.yaml
- operators/patch-operator/0.1.10/manifests/redhatcop.redhat.io_patches.yaml
- operators/patch-operator/0.1.10/metadata/annotations.yaml
- operators/patch-operator/0.1.10/tests/scorecard/config.yaml
> operator patch-operator (0.1.10)

- operators/sap-data-intelligence-observer-operator/1.0.7/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml
- operators/sap-data-intelligence-observer-operator/1.0.7/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/sap-data-intelligence-observer-operator/1.0.7/manifests/observer-operator.clusterserviceversion.yaml
- operators/sap-data-intelligence-observer-operator/1.0.7/manifests/sdi.sap-redhat.io_sdiobservers.yaml
- operators/sap-data-intelligence-observer-operator/1.0.7/metadata/annotations.yaml
> operator sap-data-intelligence-observer-operator (1.0.7)

- operators/grafana-operator/5.11.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.11.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.11.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.11.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.11.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.11.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.11.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.11.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.11.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.11.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.11.0/metadata/annotations.yaml
> operator grafana-operator (5.11.0)

- operators/mongodb-atlas-kubernetes/2.4.1/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.4.1/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.4.1)

- operators/pubsubplus-eventbroker-operator/1.1.1/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
- operators/pubsubplus-eventbroker-operator/1.1.1/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
- operators/pubsubplus-eventbroker-operator/1.1.1/metadata/annotations.yaml
- operators/pubsubplus-eventbroker-operator/1.1.1/tests/scorecard/config.yaml
> operator pubsubplus-eventbroker-operator (1.1.1)

- operators/sap-data-intelligence-observer-operator/1.0.8/manifests/observer-operator-controller-manager-metrics-service_v1_service.yaml
- operators/sap-data-intelligence-observer-operator/1.0.8/manifests/observer-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/sap-data-intelligence-observer-operator/1.0.8/manifests/observer-operator.clusterserviceversion.yaml
- operators/sap-data-intelligence-observer-operator/1.0.8/manifests/sdi.sap-redhat.io_sdiobservers.yaml
- operators/sap-data-intelligence-observer-operator/1.0.8/metadata/annotations.yaml
> operator sap-data-intelligence-observer-operator (1.0.8)

- operators/microcks/1.10.0/manifests/microcks-operator.v1.10.0.clusterserviceversion.yaml
- operators/microcks/1.10.0/manifests/microcksinstall.crd.yaml
- operators/microcks/1.10.0/metadata/annotations.yaml
> operator microcks (1.10.0)

- operators/external-secrets-operator/0.10.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.0/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.0/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.0/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.0/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.0
> operator external-secrets-operator (0.10.0)

- operators/camel-k/2.4.0/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/camel-k.v2.4.0.clusterserviceversion.yaml
- operators/camel-k/2.4.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.4.0/metadata/annotations.yaml
- operators/camel-k/2.4.0/tests/scorecard/config.yaml
> operator camel-k (2.4.0)

- operators/layer7-operator/1.0.7/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
- operators/layer7-operator/1.0.7/manifests/layer7-operator-manager-config_v1_configmap.yaml
- operators/layer7-operator/1.0.7/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/layer7-operator/1.0.7/manifests/layer7-operator-webhook-service_v1_service.yaml
- operators/layer7-operator/1.0.7/manifests/layer7-operator.clusterserviceversion.yaml
- operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_gateways.yaml
- operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_l7apis.yaml
- operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_l7portals.yaml
- operators/layer7-operator/1.0.7/manifests/security.brcmlabs.com_repositories.yaml
- operators/layer7-operator/1.0.7/metadata/annotations.yaml
- operators/layer7-operator/1.0.7/tests/scorecard/config.yaml
- operators/layer7-operator/ci.yaml
> operator layer7-operator (1.0.7)

- operators/grafana-operator/5.12.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.12.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.12.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.12.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.12.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.12.0/metadata/annotations.yaml
> operator grafana-operator (5.12.0)

- operators/dynatrace-operator/1.2.2/Dockerfile
- operators/dynatrace-operator/1.2.2/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.2.2/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.2.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.2.2/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.2.2/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.2.2/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.2.2/metadata/annotations.yaml
> operator dynatrace-operator (1.2.2)

- operators/bpfman-operator/0.5.0/bundle.Dockerfile
- operators/bpfman-operator/0.5.0/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-config_v1_configmap.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-daemon_v1_serviceaccount.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-operator.clusterserviceversion.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_bpfapplications.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_bpfprograms.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_fentryprograms.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_fexitprograms.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_kprobeprograms.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_tcprograms.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_tracepointprograms.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_uprobeprograms.yaml
- operators/bpfman-operator/0.5.0/manifests/bpfman.io_xdpprograms.yaml
- operators/bpfman-operator/0.5.0/metadata/annotations.yaml
- operators/bpfman-operator/0.5.0/metadata/dependencies.yaml
- operators/bpfman-operator/0.5.0/tests/scorecard/config.yaml
- operators/bpfman-operator/ci.yaml
Cut a 0.5.0 OLM release of the bpfman operator.
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
--
> operator bpfman-operator (0.5.0)

- operators/patterns-operator/0.0.53/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.53/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.53/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.53/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.53/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.53/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.53/metadata/annotations.yaml
- operators/patterns-operator/0.0.53/tests/scorecard/config.yaml
> operator patterns-operator (0.0.53)

- operators/koku-metrics-operator/3.3.1/Dockerfile
- operators/koku-metrics-operator/3.3.1/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- operators/koku-metrics-operator/3.3.1/manifests/koku-metrics-operator.clusterserviceversion.yaml
- operators/koku-metrics-operator/3.3.1/metadata/annotations.yaml
- operators/koku-metrics-operator/3.3.1/tests/scorecard/config.yaml
> operator koku-metrics-operator (3.3.1)

- operators/opendatahub-operator/2.16.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.16.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.16.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.16.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.16.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.16.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.16.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.16.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.16.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.16.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.16.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.16.0)

- operators/tempo-operator/0.12.0/bundle.Dockerfile
- operators/tempo-operator/0.12.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.12.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.12.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.12.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.12.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.12.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.12.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.12.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.12.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.12.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.12.0/metadata/annotations.yaml
- operators/tempo-operator/0.12.0/tests/scorecard/config.yaml
Release tempo-operator `0.12.0`.
> operator tempo-operator (0.12.0)

- operators/ack-wafv2-controller/ci.yaml
--
- Closes: aws-controllers-k8s/community#2127
> add ack-wafv2-controller ci file

- operators/ack-ses-controller/ci.yaml
> add ack-ses-controller ci file

- operators/ack-apigateway-controller/ci.yaml
> add ack-apigateway-controller ci file

- operators/verticadb-operator/2.2.0/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/2.2.0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/2.2.0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/2.2.0/manifests/vertica.com_verticareplicators.yaml
- operators/verticadb-operator/2.2.0/manifests/vertica.com_verticarestorepointsqueries.yaml
- operators/verticadb-operator/2.2.0/manifests/vertica.com_verticascrutinizers.yaml
- operators/verticadb-operator/2.2.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/2.2.0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/2.2.0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/2.2.0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/2.2.0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/2.2.0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/2.2.0/metadata/annotations.yaml
- operators/verticadb-operator/2.2.0/tests/scorecard/config.yaml
> operator verticadb-operator (2.2.0)

- operators/ack-athena-controller/ci.yaml
> add ack-athena-controller ci file

- operators/ack-cognitoidentity-controller/ci.yaml
> add ack-cognitoidentity-controller ci file

- operators/ack-ebs-controller/ci.yaml
> add ack-ebs-controller ci file

- operators/ack-recyclebin-controller/ci.yaml
> add ack-recyclebin-controller ci file

- operators/gitlab-operator-kubernetes/1.2.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.2.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.2.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.2.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.2.2)

- operators/codeflare-operator/1.7.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.7.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.7.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.7.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.7.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.7.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.7.0/metadata/annotations.yaml
- operators/codeflare-operator/1.7.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.7.0)

- operators/gitlab-operator-kubernetes/1.3.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.3.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.3.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.3.0)

- operators/dell-csm-operator/1.6.0/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.6.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.6.0/manifests/dell-csm-operator.v1.6.0.clusterserviceversion.yaml
- operators/dell-csm-operator/1.6.0/metadata/annotations.yaml
- operators/dell-csm-operator/1.6.0/tests/scorecard/config.yaml
> operator dell-csm-operator (1.6.0)

- operators/bpfman-operator/0.5.1/bundle.Dockerfile
- operators/bpfman-operator/0.5.1/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-config_v1_configmap.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-daemon_v1_serviceaccount.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-operator.clusterserviceversion.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_bpfapplications.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_bpfprograms.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_fentryprograms.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_fexitprograms.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_kprobeprograms.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_tcprograms.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_tracepointprograms.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_uprobeprograms.yaml
- operators/bpfman-operator/0.5.1/manifests/bpfman.io_xdpprograms.yaml
- operators/bpfman-operator/0.5.1/metadata/annotations.yaml
- operators/bpfman-operator/0.5.1/metadata/dependencies.yaml
- operators/bpfman-operator/0.5.1/tests/scorecard/config.yaml
> operator bpfman-operator (0.5.1)

- operators/datadog-operator/1.8.0/manifests/datadog-operator-webhook-service_v1_service.yaml
- operators/datadog-operator/1.8.0/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogagentprofiles.yaml
- operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogpodautoscalers.yaml
- operators/datadog-operator/1.8.0/manifests/datadoghq.com_datadogslos.yaml
- operators/datadog-operator/1.8.0/metadata/annotations.yaml
- operators/datadog-operator/1.8.0/tests/scorecard/config.yaml
> operator datadog-operator (1.8.0)

- operators/gitlab-operator-kubernetes/1.3.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.3.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.3.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.3.1)

- operators/project-quay/3.11.4/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.4/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.4/metadata/annotations.yaml
Add 3.11.4 to community operators
> operator project-quay (3.11.4)

- operators/project-quay/3.12.1/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.1/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.1/metadata/annotations.yaml
Add 3.12.1 to community operators
> operator project-quay (3.12.1)

- operators/patterns-operator/0.0.55/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.55/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.55/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.55/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.55/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.55/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.55/metadata/annotations.yaml
- operators/patterns-operator/0.0.55/tests/scorecard/config.yaml
> operator patterns-operator (0.0.55)

- operators/move2kube-operator/0.3.14/bundle.Dockerfile
- operators/move2kube-operator/0.3.14/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
- operators/move2kube-operator/0.3.14/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/move2kube-operator/0.3.14/manifests/move2kube-operator.clusterserviceversion.yaml
- operators/move2kube-operator/0.3.14/manifests/move2kube.konveyor.io_move2kubes.yaml
- operators/move2kube-operator/0.3.14/metadata/annotations.yaml
- operators/move2kube-operator/0.3.14/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.14
> operator move2kube-operator (0.3.14)

- operators/percona-xtradb-cluster-operator/1.15.0/manifests/percona-xtradb-cluster-operator.v1.15.0.clusterserviceversion.yaml
- operators/percona-xtradb-cluster-operator/1.15.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.15.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.15.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.15.0/metadata/annotations.yaml
> operator percona-xtradb-cluster-operator (1.15.0)

- operators/tempo-operator/0.13.0/bundle.Dockerfile
- operators/tempo-operator/0.13.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.13.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.13.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.13.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.13.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.13.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.13.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.13.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.13.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.13.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.13.0/metadata/annotations.yaml
- operators/tempo-operator/0.13.0/tests/scorecard/config.yaml
Release tempo-operator `0.13.0`.
> operator tempo-operator (0.13.0)

- operators/external-secrets-operator/0.10.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.1/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.1/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.1/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.1/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.1/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.1/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.1
> operator external-secrets-operator (0.10.1)

- operators/opendatahub-operator/2.17.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.17.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.17.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.17.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.17.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.17.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.17.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.17.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.17.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.17.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.17.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.17.0)

- operators/skupper-operator/1.8.0/manifests/skupper-operator.v1.8.0.clusterserviceversion.yaml
- operators/skupper-operator/1.8.0/metadata/annotations.yaml
> operator skupper-operator (1.8.0)

- operators/registry-operator/ci.yaml
> modify registry-operator ci file

- operators/external-secrets-operator/0.10.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.2/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.2/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.2/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.2/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.2/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.2/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.2
> operator external-secrets-operator (0.10.2)

- operators/susql-operator/0.0.26/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.26/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
- operators/susql-operator/0.0.26/manifests/susql-operator.clusterserviceversion.yaml
- operators/susql-operator/0.0.26/manifests/susql.ibm.com_labelgroups.yaml
- operators/susql-operator/0.0.26/metadata/annotations.yaml
- operators/susql-operator/0.0.26/tests/scorecard/config.yaml
- operators/susql-operator/ci.yaml
> operator susql-operator (0.0.26)

- operators/registry-operator/0.3.0/bundle.Dockerfile
- operators/registry-operator/0.3.0/manifests/registry-operator-controller-manager-metrics-service_v1_service.yaml
- operators/registry-operator/0.3.0/manifests/registry-operator-manager-config_v1_configmap.yaml
- operators/registry-operator/0.3.0/manifests/registry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/registry-operator/0.3.0/manifests/registry-operator-webhook-service_v1_service.yaml
- operators/registry-operator/0.3.0/manifests/registry-operator.clusterserviceversion.yaml
- operators/registry-operator/0.3.0/manifests/registry.devfile.io_clusterdevfileregistrieslists.yaml
- operators/registry-operator/0.3.0/manifests/registry.devfile.io_devfileregistries.yaml
- operators/registry-operator/0.3.0/manifests/registry.devfile.io_devfileregistrieslists.yaml
- operators/registry-operator/0.3.0/metadata/annotations.yaml
- operators/registry-operator/0.3.0/tests/scorecard/config.yaml
> operator registry-operator (0.3.0)

- operators/dapr-kubernetes-operator/0.0.9/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
- operators/dapr-kubernetes-operator/0.0.9/manifests/operator.dapr.io_daprcontrolplanes.yaml
- operators/dapr-kubernetes-operator/0.0.9/manifests/operator.dapr.io_daprcruiscontrols.yaml
- operators/dapr-kubernetes-operator/0.0.9/manifests/operator.dapr.io_daprinstances.yaml
- operators/dapr-kubernetes-operator/0.0.9/metadata/annotations.yaml
- operators/dapr-kubernetes-operator/0.0.9/tests/scorecard/config.yaml
> operator dapr-kubernetes-operator (0.0.9)

- operators/patterns-operator/ci.yaml
> chore: add darkdoc to reviewers

- operators/codeflare-operator/1.8.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.8.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.8.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.8.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.8.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.8.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.8.0/metadata/annotations.yaml
- operators/codeflare-operator/1.8.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.8.0)

- operators/susql-operator/0.0.28/bundle.Dockerfile
- operators/susql-operator/0.0.28/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.28/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
- operators/susql-operator/0.0.28/manifests/susql-operator.clusterserviceversion.yaml
- operators/susql-operator/0.0.28/manifests/susql.ibm.com_labelgroups.yaml
- operators/susql-operator/0.0.28/metadata/annotations.yaml
- operators/susql-operator/0.0.28/tests/scorecard/config.yaml
> operator susql-operator (0.0.28)

- operators/susql-operator/0.0.29/bundle.Dockerfile
- operators/susql-operator/0.0.29/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.29/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
- operators/susql-operator/0.0.29/manifests/susql-operator.clusterserviceversion.yaml
- operators/susql-operator/0.0.29/manifests/susql.ibm.com_labelgroups.yaml
- operators/susql-operator/0.0.29/metadata/annotations.yaml
- operators/susql-operator/0.0.29/tests/scorecard/config.yaml
> operator susql-operator (0.0.29)

- operators/grafana-operator/5.13.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.13.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.13.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.13.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.13.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.13.0/metadata/annotations.yaml
> operator grafana-operator (5.13.0)

- operators/gitlab-operator-kubernetes/1.3.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.3.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.2/metadata/annotations.yaml
> operator gitlab-operator-kubernetes (1.3.2)

- operators/susql-operator/0.0.30/Dockerfile
- operators/susql-operator/0.0.30/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.30/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
- operators/susql-operator/0.0.30/manifests/susql-operator.clusterserviceversion.yaml
- operators/susql-operator/0.0.30/manifests/susql.ibm.com_labelgroups.yaml
- operators/susql-operator/0.0.30/metadata/annotations.yaml
- operators/susql-operator/0.0.30/tests/scorecard/config.yaml
> operator susql-operator (0.0.30)

- operators/project-quay/3.12.2/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.2/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.2/metadata/annotations.yaml
Add 3.12.2 to community operators
> operator project-quay (3.12.2)

- operators/project-quay/3.11.5/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.5/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.5/metadata/annotations.yaml
Add 3.11.5 to community operators
> operator project-quay (3.11.5)

- operators/lbconfig-operator/0.5.0/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml
- operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml
- operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator-manager-config_v1_configmap.yaml
- operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/lbconfig-operator/0.5.0/manifests/lbconfig-operator.clusterserviceversion.yaml
- operators/lbconfig-operator/0.5.0/metadata/annotations.yaml
- operators/lbconfig-operator/0.5.0/tests/scorecard/config.yaml
- operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml
- operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml
- operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml
- operators/lbconfig-operator/0.5.0/tests/scorecard/kuttl/kuttl-test.yaml
> operator lbconfig-operator (0.5.0)

- operators/skupper-operator/1.8.1/manifests/skupper-operator.v1.8.1.clusterserviceversion.yaml
- operators/skupper-operator/1.8.1/metadata/annotations.yaml
> operator skupper-operator (1.8.1)

- operators/patterns-operator/0.0.56/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.56/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.56/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.56/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.56/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.56/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.56/metadata/annotations.yaml
- operators/patterns-operator/0.0.56/tests/scorecard/config.yaml
> operator patterns-operator (0.0.56)

- operators/external-secrets-operator/0.10.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.3/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.3/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_uuids.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.3/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.3/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.3/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.3/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.3
> operator external-secrets-operator (0.10.3)

- operators/pubsubplus-eventbroker-operator/1.2.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
- operators/pubsubplus-eventbroker-operator/1.2.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
- operators/pubsubplus-eventbroker-operator/1.2.0/metadata/annotations.yaml
- operators/pubsubplus-eventbroker-operator/1.2.0/tests/scorecard/config.yaml
> operator pubsubplus-eventbroker-operator (1.2.0)

- operators/apicurio-registry/1.1.3-v2.6.4.final/bundle.Dockerfile
- operators/apicurio-registry/1.1.3-v2.6.4.final/manifests/apicurio-registry-operator.clusterserviceversion.yaml
- operators/apicurio-registry/1.1.3-v2.6.4.final/manifests/registry.apicur.io_apicurioregistries.yaml
- operators/apicurio-registry/1.1.3-v2.6.4.final/metadata/annotations.yaml
- operators/apicurio-registry/1.1.3-v2.6.4.final/tests/scorecard/config.yaml
> operator apicurio-registry (1.1.3-v2.6.4.final)

- operators/opendatahub-operator/2.18.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.18.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.18.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.18.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.18.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.18.0/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.18.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.18.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.18.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.18.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.18.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.18.0)

- operators/opendatahub-operator/2.18.1/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.18.1/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.18.1/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.18.1/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.18.1/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.18.1/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.18.1/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.18.1/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.18.1/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.18.1/metadata/annotations.yaml
- operators/opendatahub-operator/2.18.1/tests/scorecard/config.yaml
> operator opendatahub-operator (2.18.1)

- operators/automotive-infra/0.0.1/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.1/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.1/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.1/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.1/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.1/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.1/manifests/automotive.sig.centos.org_cbs.yaml
- operators/automotive-infra/0.0.1/manifests/automotive.sig.centos.org_ibs.yaml
- operators/automotive-infra/0.0.1/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.1/metadata/annotations.yaml
- operators/automotive-infra/0.0.1/tests/scorecard/config.yaml
- operators/automotive-infra/ci.yaml
> operator automotive-infra (0.0.1)

- operators/gitlab-operator-kubernetes/1.3.3/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.3.3/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.3.3/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.3.3/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.3.3)

- operators/automotive-infra/0.0.2/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.2/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.2/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.2/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.2/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.2/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.2/manifests/automotive.sig.centos.org_cbs.yaml
- operators/automotive-infra/0.0.2/manifests/automotive.sig.centos.org_ibs.yaml
- operators/automotive-infra/0.0.2/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.2/metadata/annotations.yaml
- operators/automotive-infra/0.0.2/tests/scorecard/config.yaml
> operator automotive-infra (0.0.2)

- operators/gitlab-operator-kubernetes/1.4.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.4.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.4.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.4.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.4.0)

- .gitignore
> add .catalog_cache to git ignore

- operators/authorino-operator/0.12.0/bundle.Dockerfile
- operators/authorino-operator/0.12.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.12.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.12.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.12.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.12.0/manifests/authorino-operator-metrics_v1_service.yaml
- operators/authorino-operator/0.12.0/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.12.0/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.12.0/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.12.0/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.12.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.12.0/metadata/annotations.yaml
- operators/authorino-operator/0.12.0/tests/scorecard/config.yaml
> operator authorino-operator (0.12.0)

- operators/rabbitmq-cluster-operator/2.10.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.10.0/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/2.10.0/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.10.0/metadata/annotations.yaml
- operators/rabbitmq-cluster-operator/ci.yaml
> operator rabbitmq-cluster-operator (2.10.0)

- operators/dynatrace-operator/1.3.0/Dockerfile
- operators/dynatrace-operator/1.3.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.3.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.3.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.3.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.3.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.3.0/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.3.0/metadata/annotations.yaml
> operator dynatrace-operator (1.3.0)

- operators/limitador-operator/0.10.0/bundle.Dockerfile
- operators/limitador-operator/0.10.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
- operators/limitador-operator/0.10.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/limitador-operator/0.10.0/manifests/limitador-operator-metrics_v1_service.yaml
- operators/limitador-operator/0.10.0/manifests/limitador-operator.clusterserviceversion.yaml
- operators/limitador-operator/0.10.0/manifests/limitador.kuadrant.io_limitadors.yaml
- operators/limitador-operator/0.10.0/metadata/annotations.yaml
- operators/limitador-operator/0.10.0/tests/scorecard/config.yaml
- operators/limitador-operator/ci.yaml
> operator limitador-operator (0.10.0)

- operators/opendatahub-operator/2.18.2/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.18.2/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.18.2/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.18.2/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.18.2/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.18.2/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- operators/opendatahub-operator/2.18.2/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.18.2/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.18.2/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.18.2/metadata/annotations.yaml
- operators/opendatahub-operator/2.18.2/tests/scorecard/config.yaml
> operator opendatahub-operator (2.18.2)

- operators/gitlab-operator-kubernetes/1.4.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.4.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.4.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.4.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.4.1)

- operators/mariadb-operator/0.32.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.32.0/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.32.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.32.0/metadata/annotations.yaml
- operators/mariadb-operator/0.32.0/tests/scorecard/config.yaml
Added operator mariadb-operator (0.32.0)
> operator mariadb-operator (0.32.0)

- operators/codeflare-operator/1.9.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.9.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.9.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.9.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.9.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.9.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.9.0/metadata/annotations.yaml
- operators/codeflare-operator/1.9.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.9.0)

- operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator-metrics_v1_service.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant-operator.clusterserviceversion.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_authpolicies.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_dnspolicies.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_kuadrants.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_ratelimitpolicies.yaml
- operators/kuadrant-operator/0.10.0/manifests/kuadrant.io_tlspolicies.yaml
- operators/kuadrant-operator/0.10.0/metadata/annotations.yaml
- operators/kuadrant-operator/0.10.0/metadata/dependencies.yaml
- operators/kuadrant-operator/0.10.0/tests/scorecard/config.yaml
> operator kuadrant-operator (0.10.0)

- operators/mariadb-operator/0.33.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.33.0/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.33.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.33.0/metadata/annotations.yaml
- operators/mariadb-operator/0.33.0/tests/scorecard/config.yaml
Added operator mariadb-operator (0.33.0)
> operator mariadb-operator (0.33.0)

- operators/susql-operator/0.0.32/Dockerfile
- operators/susql-operator/0.0.32/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.32/manifests/susql-operator-susql-controller-manager-metrics-service_v1_service.yaml
- operators/susql-operator/0.0.32/manifests/susql-operator.clusterserviceversion.yaml
- operators/susql-operator/0.0.32/manifests/susql.ibm.com_labelgroups.yaml
- operators/susql-operator/0.0.32/metadata/annotations.yaml
- operators/susql-operator/0.0.32/tests/scorecard/config.yaml
> operator susql-operator (0.0.32)

- operators/automotive-infra/0.0.3/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.3/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.3/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.3/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.3/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.3/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.3/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.3/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.3/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.3/metadata/annotations.yaml
- operators/automotive-infra/0.0.3/tests/scorecard/config.yaml
> operator automotive-infra (0.0.3)

- operators/project-quay/3.11.6/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.6/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.6/metadata/annotations.yaml
Add 3.11.6 to community operators
> operator project-quay (3.11.6)

- operators/neuvector-community-operator/1.4.7/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.4.7/manifests/neuvector-operator.v1.4.7.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.4.7/metadata/annotations.yaml
> operator neuvector-community-operator (1.4.7)

- operators/limitador-operator/0.11.0/manifests/limitador-operator-manager-config_v1_configmap.yaml
- operators/limitador-operator/0.11.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/limitador-operator/0.11.0/manifests/limitador-operator-metrics_v1_service.yaml
- operators/limitador-operator/0.11.0/manifests/limitador-operator.clusterserviceversion.yaml
- operators/limitador-operator/0.11.0/manifests/limitador.kuadrant.io_limitadors.yaml
- operators/limitador-operator/0.11.0/metadata/annotations.yaml
- operators/limitador-operator/0.11.0/tests/scorecard/config.yaml
> operator limitador-operator (0.11.0)

- operators/authorino-operator/0.13.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.0/manifests/authorino-operator-metrics_v1_service.yaml
- operators/authorino-operator/0.13.0/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.13.0/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.13.0/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.13.0/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.13.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.13.0/metadata/annotations.yaml
- operators/authorino-operator/0.13.0/tests/scorecard/config.yaml
> operator authorino-operator (0.13.0)

- operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator-manager-config_v1_configmap.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator-metrics_v1_service.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant-operator.clusterserviceversion.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_authpolicies.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_dnspolicies.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_kuadrants.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_ratelimitpolicies.yaml
- operators/kuadrant-operator/0.11.0/manifests/kuadrant.io_tlspolicies.yaml
- operators/kuadrant-operator/0.11.0/metadata/annotations.yaml
- operators/kuadrant-operator/0.11.0/metadata/dependencies.yaml
- operators/kuadrant-operator/0.11.0/tests/scorecard/config.yaml
> operator kuadrant-operator (0.11.0)

- operators/project-quay/3.12.3/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.3/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.3/metadata/annotations.yaml
Add 3.12.3 to community operators
> operator project-quay (3.12.3)

- operators/neuvector-community-operator/1.4.8/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.4.8/manifests/neuvector-operator.v1.4.8.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.4.8/metadata/annotations.yaml
> operator neuvector-community-operator (1.4.8)

- operators/automotive-infra/0.0.4/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.4/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.4/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.4/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.4/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.4/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.4/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.4/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.4/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.4/metadata/annotations.yaml
- operators/automotive-infra/0.0.4/tests/scorecard/config.yaml
> operator automotive-infra (0.0.4)

- operators/mariadb-operator/0.34.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.34.0/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.34.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.34.0/metadata/annotations.yaml
- operators/mariadb-operator/0.34.0/tests/scorecard/config.yaml
Added operator mariadb-operator (0.34.0)
> operator mariadb-operator (0.34.0)

- operators/datadog-operator/1.9.0/manifests/datadog-operator-webhook-service_v1_service.yaml
- operators/datadog-operator/1.9.0/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogagentprofiles.yaml
- operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogdashboards.yaml
- operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogpodautoscalers.yaml
- operators/datadog-operator/1.9.0/manifests/datadoghq.com_datadogslos.yaml
- operators/datadog-operator/1.9.0/metadata/annotations.yaml
- operators/datadog-operator/1.9.0/tests/scorecard/config.yaml
> operator datadog-operator (1.9.0)

- operators/automotive-infra/0.0.5/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.5/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.5/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.5/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.5/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.5/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.5/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.5/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.5/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.5/metadata/annotations.yaml
- operators/automotive-infra/0.0.5/tests/scorecard/config.yaml
> operator automotive-infra (0.0.5)

- operators/automotive-infra/0.0.6/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.6/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.6/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.6/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.6/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.6/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.6/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.6/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.6/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.6/metadata/annotations.yaml
- operators/automotive-infra/0.0.6/tests/scorecard/config.yaml
> operator automotive-infra (0.0.6)

- operators/verticadb-operator/24.4.0-0/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticareplicators.yaml
- operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticarestorepointsqueries.yaml
- operators/verticadb-operator/24.4.0-0/manifests/vertica.com_verticascrutinizers.yaml
- operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/24.4.0-0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/24.4.0-0/metadata/annotations.yaml
- operators/verticadb-operator/24.4.0-0/tests/scorecard/config.yaml
> operator verticadb-operator (24.4.0-0)

- operators/gitlab-operator-kubernetes/1.4.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.4.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.4.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.4.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.4.2)

- operators/portworx-essentials/24.1.2/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/24.1.2/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/24.1.2/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/24.1.2/metadata/annotations.yaml
> operator portworx-essentials (24.1.2)

- operators/grafana-operator/5.14.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.14.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.14.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.14.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.14.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.14.0/metadata/annotations.yaml
> operator grafana-operator (5.14.0)

- operators/dynatrace-operator/1.3.1/Dockerfile
- operators/dynatrace-operator/1.3.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.3.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.3.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.3.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.3.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.3.1/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.3.1/metadata/annotations.yaml
> operator dynatrace-operator (1.3.1)

- operators/bpfman-operator/0.5.2/bundle.Dockerfile
- operators/bpfman-operator/0.5.2/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-config_v1_configmap.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-daemon_v1_serviceaccount.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-operator.clusterserviceversion.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_bpfapplications.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_bpfprograms.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_fentryprograms.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_fexitprograms.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_kprobeprograms.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_tcprograms.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_tracepointprograms.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_uprobeprograms.yaml
- operators/bpfman-operator/0.5.2/manifests/bpfman.io_xdpprograms.yaml
- operators/bpfman-operator/0.5.2/metadata/annotations.yaml
- operators/bpfman-operator/0.5.2/metadata/dependencies.yaml
- operators/bpfman-operator/0.5.2/tests/scorecard/config.yaml
The bpfman-operator v0.5.2 release is a patch release that adds support for
ppc64le and s390x, and contains several minor internal updates.
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capab …
> operator bpfman-operator (0.5.2)

- operators/opendatahub-operator/2.19.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.19.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.19.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.19.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.19.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.19.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.19.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.19.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.19.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.19.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.19.0)

- operators/dell-csm-operator/1.6.1/manifests/apexconnectivityclients.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.6.1/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.6.1/manifests/dell-csm-operator.v1.6.1.clusterserviceversion.yaml
- operators/dell-csm-operator/1.6.1/metadata/annotations.yaml
- operators/dell-csm-operator/1.6.1/tests/scorecard/config.yaml
> operator dell-csm-operator (1.6.1)

- operators/wandb-operator/1.0.0/bundle.Dockerfile
- operators/wandb-operator/1.0.0/manifests/apps.wandb.com_weightsandbiases.yaml
- operators/wandb-operator/1.0.0/manifests/wandb-operator-manager_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/wandb-operator/1.0.0/manifests/wandb-operator-manager_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/wandb-operator/1.0.0/manifests/wandb-operator.clusterserviceversion.yaml
- operators/wandb-operator/1.0.0/metadata/annotations.yaml
- operators/wandb-operator/1.0.0/tests/scorecard/config.yaml
- operators/wandb-operator/ci.yaml
> operator wandb-operator (1.0.0)

- operators/patterns-operator/0.0.57/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.57/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.57/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.57/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.57/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.57/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.57/metadata/annotations.yaml
- operators/patterns-operator/0.0.57/tests/scorecard/config.yaml
> operator patterns-operator (0.0.57)

- operators/bpfman-operator/0.5.4/bundle.Dockerfile
- operators/bpfman-operator/0.5.4/manifests/bpfman-agent-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-agent-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-bpfprogram-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-bpfprogram-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-config_v1_configmap.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-controller-manager-metrics-service_v1_service.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-daemon_v1_serviceaccount.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-operator.clusterserviceversion.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-privileged-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman-user_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_bpfapplications.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_bpfprograms.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_fentryprograms.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_fexitprograms.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_kprobeprograms.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_tcprograms.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_tracepointprograms.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_uprobeprograms.yaml
- operators/bpfman-operator/0.5.4/manifests/bpfman.io_xdpprograms.yaml
- operators/bpfman-operator/0.5.4/metadata/annotations.yaml
- operators/bpfman-operator/0.5.4/metadata/dependencies.yaml
- operators/bpfman-operator/0.5.4/tests/scorecard/config.yaml
bpfman-operator release v0.5.4
--
> operator bpfman-operator (0.5.4)

- operators/move2kube-operator/0.3.15-rc.0/bundle.Dockerfile
- operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
- operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube-operator.clusterserviceversion.yaml
- operators/move2kube-operator/0.3.15-rc.0/manifests/move2kube.konveyor.io_move2kubes.yaml
- operators/move2kube-operator/0.3.15-rc.0/metadata/annotations.yaml
- operators/move2kube-operator/0.3.15-rc.0/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.15-rc.0
> operator move2kube-operator (0.3.15-rc.0)

- operators/neuvector-community-operator/1.4.9/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.4.9/manifests/neuvector-operator.v1.4.9.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.4.9/metadata/annotations.yaml
> operator neuvector-community-operator (1.4.9)

- operators/codeflare-operator/1.10.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.10.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.10.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.10.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.10.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.10.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.10.0/metadata/annotations.yaml
- operators/codeflare-operator/1.10.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.10.0)

- operators/gitlab-operator-kubernetes/1.5.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.5.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.5.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.5.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.5.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.5.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.5.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.5.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.5.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.5.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.5.1)

- operators/patterns-operator/0.0.58/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.58/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.58/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.58/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.58/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.58/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.58/metadata/annotations.yaml
- operators/patterns-operator/0.0.58/tests/scorecard/config.yaml
> operator patterns-operator (0.0.58)

- operators/multicluster-global-hub-operator/1.3.0/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
- operators/multicluster-global-hub-operator/1.3.0/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.3.0/manifests/multicluster-global-hub-webhook_v1_service.yaml
- operators/multicluster-global-hub-operator/1.3.0/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.3.0/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.3.0)

- operators/mariadb-operator/0.35.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.35.0/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.35.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.35.0/metadata/annotations.yaml
- operators/mariadb-operator/0.35.0/tests/scorecard/config.yaml
Added operator mariadb-operator (0.35.0)
> operator mariadb-operator (0.35.0)

- operators/mariadb-operator/0.35.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.35.1/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.35.1/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.35.1/metadata/annotations.yaml
- operators/mariadb-operator/0.35.1/tests/scorecard/config.yaml
Added operator mariadb-operator (0.35.1)
> operator mariadb-operator (0.35.1)

- operators/mongodb-atlas-kubernetes/2.5.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.5.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.5.0)

- operators/patterns-operator/0.0.59/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.59/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.59/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.59/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.59/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.59/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.59/metadata/annotations.yaml
- operators/patterns-operator/0.0.59/tests/scorecard/config.yaml
> operator patterns-operator (0.0.59)

- operators/apicast-community-operator/0.8.0/bundle.Dockerfile
- operators/apicast-community-operator/0.8.0/manifests/apicast-operator-controller-manager-metrics-service_v1_service.yaml
- operators/apicast-community-operator/0.8.0/manifests/apicast-operator.clusterserviceversion.yaml
- operators/apicast-community-operator/0.8.0/manifests/apps.3scale.net_apicasts.yaml
- operators/apicast-community-operator/0.8.0/metadata/annotations.yaml
- operators/apicast-community-operator/0.8.0/tests/scorecard/config.yaml
- operators/apicast-community-operator/ci.yaml
> operator apicast-community-operator (0.8.0)

- operators/portworx-essentials/24.1.3/manifests/core_v1_storagecluster_crd.yaml
- operators/portworx-essentials/24.1.3/manifests/core_v1_storagenode_crd.yaml
- operators/portworx-essentials/24.1.3/manifests/portworxoperator.clusterserviceversion.yaml
- operators/portworx-essentials/24.1.3/metadata/annotations.yaml
> operator portworx-essentials (24.1.3)

- operators/opendatahub-operator/2.20.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.20.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.20.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.20.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.20.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.20.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.20.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.20.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.20.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.20.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.20.0)

- operators/tempo-operator/0.14.0/bundle.Dockerfile
- operators/tempo-operator/0.14.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.14.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.14.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.14.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.14.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.14.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.14.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.14.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.14.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.14.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.14.0/metadata/annotations.yaml
- operators/tempo-operator/0.14.0/tests/scorecard/config.yaml
Release tempo-operator `0.14.0`.
> operator tempo-operator (0.14.0)

- operators/external-secrets-operator/0.10.5/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.5/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.5/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_uuids.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.5/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.5/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.5/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.5/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.5
> operator external-secrets-operator (0.10.5)

- operators/external-secrets-operator/ci.yaml
> fix: username of skarlso is not lowercase

- operators/percona-server-mongodb-operator/1.17.0/manifests/percona-server-mongodb-operator.v1.17.0.clusterserviceversion.yaml
- operators/percona-server-mongodb-operator/1.17.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.17.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.17.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.17.0/metadata/annotations.yaml
> operator percona-server-mongodb-operator (1.17.0)

- operators/percona-xtradb-cluster-operator/1.15.1/manifests/percona-xtradb-cluster-operator.v1.15.1.clusterserviceversion.yaml
- operators/percona-xtradb-cluster-operator/1.15.1/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.15.1/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.15.1/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.15.1/metadata/annotations.yaml
- operators/percona-xtradb-cluster-operator/ci.yaml
> operator percona-xtradb-cluster-operator (1.15.1)

- operators/grafana-operator/5.15.1/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.15.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.15.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.15.1/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.15.1/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.15.1/metadata/annotations.yaml
> operator grafana-operator (5.15.1)

- operators/marin3r/0.12.3/manifests/marin3r-controller-manager-metrics-service_v1_service.yaml
- operators/marin3r/0.12.3/manifests/marin3r-manager-config_v1_configmap.yaml
- operators/marin3r/0.12.3/manifests/marin3r-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/marin3r/0.12.3/manifests/marin3r-webhook-service_v1_service.yaml
- operators/marin3r/0.12.3/manifests/marin3r.3scale.net_envoyconfigrevisions.yaml
- operators/marin3r/0.12.3/manifests/marin3r.3scale.net_envoyconfigs.yaml
- operators/marin3r/0.12.3/manifests/marin3r.clusterserviceversion.yaml
- operators/marin3r/0.12.3/manifests/operator.marin3r.3scale.net_discoveryservicecertificates.yaml
- operators/marin3r/0.12.3/manifests/operator.marin3r.3scale.net_discoveryservices.yaml
- operators/marin3r/0.12.3/manifests/operator.marin3r.3scale.net_envoydeployments.yaml
- operators/marin3r/0.12.3/metadata/annotations.yaml
- operators/marin3r/0.12.3/tests/scorecard/config.yaml
> operator marin3r (0.12.3)

- operators/camel-k/2.5.0/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/camel-k.v2.5.0.clusterserviceversion.yaml
- operators/camel-k/2.5.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.5.0/metadata/annotations.yaml
- operators/camel-k/2.5.0/tests/scorecard/config.yaml
> operator camel-k (2.5.0)

- operators/marin3r/0.13.1/manifests/marin3r-controller-manager-metrics-service_v1_service.yaml
- operators/marin3r/0.13.1/manifests/marin3r-manager-config_v1_configmap.yaml
- operators/marin3r/0.13.1/manifests/marin3r-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/marin3r/0.13.1/manifests/marin3r-webhook-service_v1_service.yaml
- operators/marin3r/0.13.1/manifests/marin3r.3scale.net_envoyconfigrevisions.yaml
- operators/marin3r/0.13.1/manifests/marin3r.3scale.net_envoyconfigs.yaml
- operators/marin3r/0.13.1/manifests/marin3r.clusterserviceversion.yaml
- operators/marin3r/0.13.1/manifests/operator.marin3r.3scale.net_discoveryservicecertificates.yaml
- operators/marin3r/0.13.1/manifests/operator.marin3r.3scale.net_discoveryservices.yaml
- operators/marin3r/0.13.1/manifests/operator.marin3r.3scale.net_envoydeployments.yaml
- operators/marin3r/0.13.1/metadata/annotations.yaml
- operators/marin3r/0.13.1/tests/scorecard/config.yaml
> operator marin3r (0.13.1)

- operators/trident-operator/24.10.0/manifests/trident-operator.v24.10.0.clusterserviceversion.yaml
- operators/trident-operator/24.10.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
- operators/trident-operator/24.10.0/metadata/annotations.yaml
> operator trident-operator (24.10.0)

- operators/project-quay/3.12.4/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.4/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.4/metadata/annotations.yaml
Add 3.12.4 to community operators
> operator project-quay (3.12.4)

- operators/project-quay/3.13.0/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.13.0/manifests/quayregistries.crd.yaml
- operators/project-quay/3.13.0/metadata/annotations.yaml
Add 3.13.0 to community operators
> operator project-quay (3.13.0)

- operators/skupper-operator/1.8.2/manifests/skupper-operator.v1.8.2.clusterserviceversion.yaml
- operators/skupper-operator/1.8.2/metadata/annotations.yaml
> operator skupper-operator (1.8.2)

- operators/gitlab-operator-kubernetes/1.6.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.6.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.6.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.6.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.6.0)

- operators/codeflare-operator/1.11.0/manifests/codeflare-operator-appwrapper-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.11.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.11.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.11.0/manifests/codeflare-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.11.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.11.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.11.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.11.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.11.0/metadata/annotations.yaml
- operators/codeflare-operator/1.11.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.11.0)

- operators/tempo-operator/0.14.1/bundle.Dockerfile
- operators/tempo-operator/0.14.1/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.14.1/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.14.1/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.14.1/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.14.1/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.14.1/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.14.1/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.14.1/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.14.1/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.14.1/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.14.1/metadata/annotations.yaml
- operators/tempo-operator/0.14.1/tests/scorecard/config.yaml
Release tempo-operator `0.14.1`.
> operator tempo-operator (0.14.1)

- operators/loki-operator/0.7.0/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-manager-config_v1_configmap.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator-webhook-service_v1_service.yaml
- operators/loki-operator/0.7.0/manifests/loki-operator.clusterserviceversion.yaml
- operators/loki-operator/0.7.0/manifests/loki.grafana.com_alertingrules.yaml
- operators/loki-operator/0.7.0/manifests/loki.grafana.com_lokistacks.yaml
- operators/loki-operator/0.7.0/manifests/loki.grafana.com_recordingrules.yaml
- operators/loki-operator/0.7.0/manifests/loki.grafana.com_rulerconfigs.yaml
- operators/loki-operator/0.7.0/metadata/annotations.yaml
- operators/loki-operator/0.7.0/tests/scorecard/config.yaml
- operators/loki-operator/ci.yaml
> operator loki-operator (0.7.0)

- operators/mariadb-operator/0.36.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.36.0/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.36.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.36.0/metadata/annotations.yaml
- operators/mariadb-operator/0.36.0/tests/scorecard/config.yaml
Added operator mariadb-operator (0.36.0)
> operator mariadb-operator (0.36.0)

- operators/kube-green/0.6.0/manifests/kube-green-aggregate-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.6.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
- operators/kube-green/0.6.0/manifests/kube-green-manager-config_v1_configmap.yaml
- operators/kube-green/0.6.0/manifests/kube-green-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.6.0/manifests/kube-green-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/kube-green/0.6.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.6.0/manifests/kube-green-webhook-service_v1_service.yaml
- operators/kube-green/0.6.0/manifests/kube-green.clusterserviceversion.yaml
- operators/kube-green/0.6.0/manifests/kube-green.com_sleepinfos.yaml
- operators/kube-green/0.6.0/metadata/annotations.yaml
- operators/kube-green/0.6.0/tests/scorecard/config.yaml
> operator kube-green (0.6.0)

- operators/loki-operator/0.7.1/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-manager-config_v1_configmap.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator-webhook-service_v1_service.yaml
- operators/loki-operator/0.7.1/manifests/loki-operator.clusterserviceversion.yaml
- operators/loki-operator/0.7.1/manifests/loki.grafana.com_alertingrules.yaml
- operators/loki-operator/0.7.1/manifests/loki.grafana.com_lokistacks.yaml
- operators/loki-operator/0.7.1/manifests/loki.grafana.com_recordingrules.yaml
- operators/loki-operator/0.7.1/manifests/loki.grafana.com_rulerconfigs.yaml
- operators/loki-operator/0.7.1/metadata/annotations.yaml
- operators/loki-operator/0.7.1/tests/scorecard/config.yaml
> operator loki-operator (0.7.1)

- operators/gitlab-operator-kubernetes/1.6.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.6.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.6.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.6.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.6.1)

- operators/dell-csm-operator/1.7.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.7.0/manifests/dell-csm-operator.v1.7.0.clusterserviceversion.yaml
- operators/dell-csm-operator/1.7.0/metadata/annotations.yaml
- operators/dell-csm-operator/1.7.0/tests/scorecard/config.yaml
> operator dell-csm-operator (1.7.0)

- operators/external-secrets-operator/0.10.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.4/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.4/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_uuids.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.4/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.4/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.4/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.4/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.4
> operator external-secrets-operator (0.10.4)

- operators/authorino-operator/0.13.1/bundle.Dockerfile
- operators/authorino-operator/0.13.1/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.1/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.1/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.1/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.13.1/manifests/authorino-operator-metrics_v1_service.yaml
- operators/authorino-operator/0.13.1/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.13.1/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.13.1/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.13.1/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.13.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.13.1/metadata/annotations.yaml
- operators/authorino-operator/0.13.1/tests/scorecard/config.yaml
> operator authorino-operator (0.13.1)

- operators/authorino-operator/0.14.0/bundle.Dockerfile
- operators/authorino-operator/0.14.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.14.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.14.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.14.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.14.0/manifests/authorino-operator-metrics_v1_service.yaml
- operators/authorino-operator/0.14.0/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.14.0/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.14.0/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.14.0/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.14.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.14.0/metadata/annotations.yaml
- operators/authorino-operator/0.14.0/tests/scorecard/config.yaml
> operator authorino-operator (0.14.0)

- operators/opendatahub-operator/2.21.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.21.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.21.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.21.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.21.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.21.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.21.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.21.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.21.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.21.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.21.0)

- operators/percona-server-mongodb-operator/1.18.0/manifests/percona-server-mongodb-operator.clusterserviceversion.yaml
- operators/percona-server-mongodb-operator/1.18.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.18.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.18.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.18.0/metadata/annotations.yaml
> operator percona-server-mongodb-operator (1.18.0)

- operators/project-quay/3.13.1/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.13.1/manifests/quayregistries.crd.yaml
- operators/project-quay/3.13.1/metadata/annotations.yaml
Add 3.13.1 to community operators
> operator project-quay (3.13.1)

- operators/external-secrets-operator/0.10.6/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.6/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.6/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.6/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.6/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.6/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.6/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_stssessiontokens.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_uuids.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.6/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.6/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.6/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.6/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.6
> operator external-secrets-operator (0.10.6)

- operators/external-secrets-operator/0.10.7/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.10.7/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.10.7/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_stssessiontokens.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_uuids.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.10.7/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.10.7/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.10.7/metadata/annotations.yaml
- operators/external-secrets-operator/0.10.7/tests/scorecard/config.yaml
bump external-secrets-operator 0.10.7
> operator external-secrets-operator (0.10.7)

- operators/odf-node-recovery-operator/0.0.1/manifests/odf-node-recovery-operator-controller-manager-metrics-service_v1_service.yaml
- operators/odf-node-recovery-operator/0.0.1/manifests/odf-node-recovery-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/odf-node-recovery-operator/0.0.1/manifests/odf-node-recovery-operator.clusterserviceversion.yaml
- operators/odf-node-recovery-operator/0.0.1/manifests/odf.openshift.io_noderecoveries.yaml
- operators/odf-node-recovery-operator/0.0.1/metadata/annotations.yaml
- operators/odf-node-recovery-operator/0.0.1/tests/scorecard/config.yaml
- operators/odf-node-recovery-operator/ci.yaml
> operator odf-node-recovery-operator (0.0.1)

- operators/authorino-operator/0.16.0/bundle.Dockerfile
- operators/authorino-operator/0.16.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.16.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.16.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.16.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/authorino-operator/0.16.0/manifests/authorino-operator-metrics_v1_service.yaml
- operators/authorino-operator/0.16.0/manifests/authorino-operator.clusterserviceversion.yaml
- operators/authorino-operator/0.16.0/manifests/authorino-webhooks_v1_service.yaml
- operators/authorino-operator/0.16.0/manifests/authorino.kuadrant.io_authconfigs.yaml
- operators/authorino-operator/0.16.0/manifests/manager-config_v1_configmap.yaml
- operators/authorino-operator/0.16.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml
- operators/authorino-operator/0.16.0/metadata/annotations.yaml
- operators/authorino-operator/0.16.0/tests/scorecard/config.yaml
> operator authorino-operator (0.16.0)

- operators/project-quay/3.12.5/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.5/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.5/metadata/annotations.yaml
Add 3.12.5 to community operators
> operator project-quay (3.12.5)

- operators/gitlab-operator-kubernetes/1.7.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.7.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.7.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.7.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.7.1)

- operators/codeflare-operator/1.12.0/manifests/codeflare-operator-appwrapper-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.12.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.12.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.12.0/manifests/codeflare-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.12.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.12.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.12.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.12.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.12.0/metadata/annotations.yaml
- operators/codeflare-operator/1.12.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.12.0)

- operators/tempo-operator/0.14.2/bundle.Dockerfile
- operators/tempo-operator/0.14.2/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.14.2/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.14.2/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.14.2/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.14.2/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.14.2/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.14.2/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.14.2/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.14.2/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.14.2/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.14.2/metadata/annotations.yaml
- operators/tempo-operator/0.14.2/tests/scorecard/config.yaml
Release tempo-operator `0.14.2`.
> operator tempo-operator (0.14.2)

- operators/apicurio-api-controller/0.0.1/bundle.Dockerfile
- operators/apicurio-api-controller/0.0.1/manifests/apicurio-api-controller.clusterserviceversion.yaml
- operators/apicurio-api-controller/0.0.1/manifests/registry.apicur.io_apicurioregistries3.yaml
- operators/apicurio-api-controller/0.0.1/metadata/annotations.yaml
- operators/apicurio-api-controller/ci.yaml
> operator apicurio-api-controller (0.0.1)

- operators/external-secrets-operator/0.11.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml
- operators/external-secrets-operator/0.11.0/manifests/external-secrets-operator.clusterserviceversion.yaml
- operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_clusterexternalsecrets.yaml
- operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_clustersecretstores.yaml
- operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_externalsecrets.yaml
- operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_pushsecrets.yaml
- operators/external-secrets-operator/0.11.0/manifests/external-secrets.io_secretstores.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_acraccesstokens.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_clustergenerators.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_fakes.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_gcraccesstokens.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_githubaccesstokens.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_passwords.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_stssessiontokens.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_uuids.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_vaultdynamicsecrets.yaml
- operators/external-secrets-operator/0.11.0/manifests/generators.external-secrets.io_webhooks.yaml
- operators/external-secrets-operator/0.11.0/manifests/operator.external-secrets.io_operatorconfigs.yaml
- operators/external-secrets-operator/0.11.0/metadata/annotations.yaml
- operators/external-secrets-operator/0.11.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.11.0
> operator external-secrets-operator (0.11.0)

- operators/koku-metrics-operator/3.3.2/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml
- operators/koku-metrics-operator/3.3.2/manifests/koku-metrics-operator.clusterserviceversion.yaml
- operators/koku-metrics-operator/3.3.2/metadata/annotations.yaml
- operators/koku-metrics-operator/3.3.2/tests/scorecard/config.yaml
> operator koku-metrics-operator (3.3.2)

- operators/neuvector-community-operator/1.5.0/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.5.0/manifests/neuvector-operator.v1.5.0.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.5.0/metadata/annotations.yaml
> operator neuvector-community-operator (1.5.0)

- operators/group-sync-operator/0.0.31/Dockerfile
- operators/group-sync-operator/0.0.31/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.31/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.31/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.31/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.31/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.31/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.31/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.31/metadata/annotations.yaml
- operators/group-sync-operator/0.0.31/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.31)

- operators/multi-nic-cni-operator/1.2.4/bundle.Dockerfile
- operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_cidrs.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_configs.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_deviceclasses.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_hostinterfaces.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_ippools.yaml
- operators/multi-nic-cni-operator/1.2.4/manifests/multinic.fms.io_multinicnetworks.yaml
- operators/multi-nic-cni-operator/1.2.4/metadata/annotations.yaml
- operators/multi-nic-cni-operator/1.2.4/tests/scorecard/config.yaml
> operator multi-nic-cni-operator (1.2.4)

- operators/odf-node-recovery-operator/0.0.2/manifests/odf-node-recovery-operator-controller-manager-metrics-service_v1_service.yaml
- operators/odf-node-recovery-operator/0.0.2/manifests/odf-node-recovery-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/odf-node-recovery-operator/0.0.2/manifests/odf-node-recovery-operator.clusterserviceversion.yaml
- operators/odf-node-recovery-operator/0.0.2/manifests/odf.openshift.io_noderecoveries.yaml
- operators/odf-node-recovery-operator/0.0.2/metadata/annotations.yaml
- operators/odf-node-recovery-operator/0.0.2/tests/scorecard/config.yaml
- operators/odf-node-recovery-operator/Makefile
> operator odf-node-recovery-operator (0.0.2)

- operators/gitlab-operator-kubernetes/ci.yaml
> Update GitLab Operator maintainers list

- operators/gitlab-operator-kubernetes/1.7.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.7.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.7.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.7.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.7.2)

- operators/dynatrace-operator/1.4.0/Dockerfile
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.4.0/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.4.0/manifests/install-config_v1_configmap.yaml
- operators/dynatrace-operator/1.4.0/metadata/annotations.yaml
> operator dynatrace-operator (1.4.0)

- operators/infinispan/2.4.6/manifests/infinispan-operator-manager-config_v1_configmap.yaml
- operators/infinispan/2.4.6/manifests/infinispan-operator.clusterserviceversion.yaml
- operators/infinispan/2.4.6/manifests/infinispan.org_backups.yaml
- operators/infinispan/2.4.6/manifests/infinispan.org_batches.yaml
- operators/infinispan/2.4.6/manifests/infinispan.org_caches.yaml
- operators/infinispan/2.4.6/manifests/infinispan.org_infinispans.yaml
- operators/infinispan/2.4.6/manifests/infinispan.org_restores.yaml
- operators/infinispan/2.4.6/metadata/annotations.yaml
- operators/infinispan/2.4.6/tests/scorecard/config.yaml
> operator infinispan (2.4.6)

- operators/patterns-operator/0.0.61/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operators/patterns-operator/0.0.61/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml
- operators/patterns-operator/0.0.61/manifests/patterns-operator-manager-config_v1_configmap.yaml
- operators/patterns-operator/0.0.61/manifests/patterns-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/patterns-operator/0.0.61/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/patterns-operator/0.0.61/manifests/patterns-operator.clusterserviceversion.yaml
- operators/patterns-operator/0.0.61/metadata/annotations.yaml
- operators/patterns-operator/0.0.61/tests/scorecard/config.yaml
> operator patterns-operator (0.0.61)

- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.22.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.22.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.22.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.22.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.22.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.22.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.22.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.22.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.22.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.22.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.22.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.22.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.22.0)

- operators/project-quay/3.10.7/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.7/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.7/metadata/annotations.yaml
Add 3.10.7 to community operators
> operator project-quay (3.10.7)

- operators/argocd-operator/ci.yaml
> chore: update owners [argocd-operator]

- operators/infinispan/2.4.8/manifests/infinispan-operator-manager-config_v1_configmap.yaml
- operators/infinispan/2.4.8/manifests/infinispan-operator.clusterserviceversion.yaml
- operators/infinispan/2.4.8/manifests/infinispan.org_backups.yaml
- operators/infinispan/2.4.8/manifests/infinispan.org_batches.yaml
- operators/infinispan/2.4.8/manifests/infinispan.org_caches.yaml
- operators/infinispan/2.4.8/manifests/infinispan.org_infinispans.yaml
- operators/infinispan/2.4.8/manifests/infinispan.org_restores.yaml
- operators/infinispan/2.4.8/metadata/annotations.yaml
- operators/infinispan/2.4.8/tests/scorecard/config.yaml
> operator infinispan (2.4.8)

- operators/project-quay/3.13.2/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.13.2/manifests/quayregistries.crd.yaml
- operators/project-quay/3.13.2/metadata/annotations.yaml
Add 3.13.2 to community operators
> operator project-quay (3.13.2)

- operators/project-quay/3.9.9/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.9.9/manifests/quayregistries.crd.yaml
- operators/project-quay/3.9.9/metadata/annotations.yaml
Add 3.9.9 to community operators
> operator project-quay (3.9.9)

- operators/project-quay/3.11.7/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.7/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.7/metadata/annotations.yaml
Add 3.11.7 to community operators
> operator project-quay (3.11.7)

- operators/percona-xtradb-cluster-operator/1.16.0/manifests/percona-xtradb-cluster-operator.v1.16.0.clusterserviceversion.yaml
- operators/percona-xtradb-cluster-operator/1.16.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.16.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.16.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.16.0/metadata/annotations.yaml
> operator percona-xtradb-cluster-operator (1.16.0)

- operators/gitlab-operator-kubernetes/1.8.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.8.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.8.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.8.0)

- operators/victoriametrics-operator/Makefile
- operators/victoriametrics-operator/catalog-templates/v4.12.yaml
- operators/victoriametrics-operator/catalog-templates/v4.13.yaml
- operators/victoriametrics-operator/catalog-templates/v4.14.yaml
- operators/victoriametrics-operator/catalog-templates/v4.15.yaml
- operators/victoriametrics-operator/catalog-templates/v4.16.yaml
- operators/victoriametrics-operator/ci.yaml
victoriametrics-operator migrate to FBC
> Catalog update [victoriametrics-operator] [v4.12,v4.14,v4.15,v4.16,v4.13]

- operators/project-quay/3.12.6/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.6/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.6/metadata/annotations.yaml
Add 3.12.6 to community operators
> operator project-quay (3.12.6)

- operators/verticadb-operator/25.1.0-0/manifests/vertica.com_eventtriggers.yaml
- operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticaautoscalers.yaml
- operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticadbs.yaml
- operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticareplicators.yaml
- operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticarestorepointsqueries.yaml
- operators/verticadb-operator/25.1.0-0/manifests/vertica.com_verticascrutinizers.yaml
- operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-manager-config_v1_configmap.yaml
- operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-metrics-service_v1_service.yaml
- operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-openshift-cluster-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-openshift-cluster-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator-webhook-service_v1_service.yaml
- operators/verticadb-operator/25.1.0-0/manifests/verticadb-operator.clusterserviceversion.yaml
- operators/verticadb-operator/25.1.0-0/metadata/annotations.yaml
- operators/verticadb-operator/25.1.0-0/tests/scorecard/config.yaml
- operators/verticadb-operator/ci.yaml
> operator verticadb-operator (25.1.0-0)

- operators/percona-xtradb-cluster-operator/1.16.1/manifests/percona-xtradb-cluster-operator.v1.16.1.clusterserviceversion.yaml
- operators/percona-xtradb-cluster-operator/1.16.1/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.16.1/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.16.1/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.16.1/metadata/annotations.yaml
> operator percona-xtradb-cluster-operator (1.16.1)

- operators/gitlab-operator-kubernetes/1.8.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.8.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.8.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.8.1)

- operators/layer7-operator/1.1.1/manifests/layer7-operator-controller-manager-metrics-service_v1_service.yaml
- operators/layer7-operator/1.1.1/manifests/layer7-operator-manager-config_v1_configmap.yaml
- operators/layer7-operator/1.1.1/manifests/layer7-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/layer7-operator/1.1.1/manifests/layer7-operator-webhook-service_v1_service.yaml
- operators/layer7-operator/1.1.1/manifests/layer7-operator.clusterserviceversion.yaml
- operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_gateways.yaml
- operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_l7apis.yaml
- operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_l7portals.yaml
- operators/layer7-operator/1.1.1/manifests/security.brcmlabs.com_repositories.yaml
- operators/layer7-operator/1.1.1/metadata/annotations.yaml
- operators/layer7-operator/1.1.1/tests/scorecard/config.yaml
> operator layer7-operator (1.1.1)

- operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusblobstores.yaml
- operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexuscleanuppolicies.yaml
- operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexuses.yaml
- operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusrepositories.yaml
- operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusroles.yaml
- operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexusscripts.yaml
- operators/nexus-operator/3.3.0/manifests/edp.epam.com_nexususers.yaml
- operators/nexus-operator/3.3.0/manifests/nexus-operator-webhook-service_v1_service.yaml
- operators/nexus-operator/3.3.0/manifests/nexus-operator.clusterserviceversion.yaml
- operators/nexus-operator/3.3.0/metadata/annotations.yaml
- operators/nexus-operator/3.3.0/tests/scorecard/config.yaml
> operator nexus-operator (3.3.0)

- operators/multi-nic-cni-operator/1.2.5/bundle.Dockerfile
- operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_cidrs.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_configs.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_deviceclasses.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_hostinterfaces.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_ippools.yaml
- operators/multi-nic-cni-operator/1.2.5/manifests/multinic.fms.io_multinicnetworks.yaml
- operators/multi-nic-cni-operator/1.2.5/metadata/annotations.yaml
- operators/multi-nic-cni-operator/1.2.5/tests/scorecard/config.yaml
> operator multi-nic-cni-operator (1.2.5)

- operators/shipwright-operator/0.14.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml
- operators/shipwright-operator/0.14.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml
- operators/shipwright-operator/0.14.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/shipwright-operator/0.14.0/manifests/shipwright-operator-metrics-service_v1_service.yaml
- operators/shipwright-operator/0.14.0/manifests/shipwright-operator.clusterserviceversion.yaml
- operators/shipwright-operator/0.14.0/metadata/annotations.yaml
- operators/shipwright-operator/0.14.0/tests/scorecard/config.yaml
> operator shipwright-operator (0.14.0)

- operators/gitlab-operator-kubernetes/1.8.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.8.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.8.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.8.2)

- operators/codeflare-operator/1.13.0/manifests/codeflare-operator-appwrapper-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.13.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.13.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.13.0/manifests/codeflare-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.13.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.13.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.13.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.13.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.13.0/metadata/annotations.yaml
- operators/codeflare-operator/1.13.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.13.0)

- operators/lbconfig-operator/0.5.1/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml
- operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml
- operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-externalloadbalancer-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-externalloadbalancer-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-manager-config_v1_configmap.yaml
- operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/lbconfig-operator/0.5.1/manifests/lbconfig-operator.clusterserviceversion.yaml
- operators/lbconfig-operator/0.5.1/metadata/annotations.yaml
- operators/lbconfig-operator/0.5.1/tests/scorecard/config.yaml
- operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml
- operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml
- operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml
- operators/lbconfig-operator/0.5.1/tests/scorecard/kuttl/kuttl-test.yaml
> operator lbconfig-operator (0.5.1)

- operators/infinispan/2.4.9/manifests/infinispan-operator-manager-config_v1_configmap.yaml
- operators/infinispan/2.4.9/manifests/infinispan-operator.clusterserviceversion.yaml
- operators/infinispan/2.4.9/manifests/infinispan.org_backups.yaml
- operators/infinispan/2.4.9/manifests/infinispan.org_batches.yaml
- operators/infinispan/2.4.9/manifests/infinispan.org_caches.yaml
- operators/infinispan/2.4.9/manifests/infinispan.org_infinispans.yaml
- operators/infinispan/2.4.9/manifests/infinispan.org_restores.yaml
- operators/infinispan/2.4.9/metadata/annotations.yaml
- operators/infinispan/2.4.9/tests/scorecard/config.yaml
> operator infinispan (2.4.9)

- operators/gitlab-operator-kubernetes/1.8.3/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.8.3/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.8.3/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.8.3/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.8.3)

- operators/grafana-operator/5.16.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.16.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.16.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.16.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
- operators/grafana-operator/5.16.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.16.0/metadata/annotations.yaml
> operator grafana-operator (5.16.0)

- operators/gitlab-operator-kubernetes/1.9.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.9.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.9.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.9.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.9.0)

- operators/kube-green/0.7.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml
- operators/kube-green/0.7.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/kube-green/0.7.0/manifests/kube-green-webhook-service_v1_service.yaml
- operators/kube-green/0.7.0/manifests/kube-green.clusterserviceversion.yaml
- operators/kube-green/0.7.0/manifests/kube-green.com_sleepinfos.yaml
- operators/kube-green/0.7.0/metadata/annotations.yaml
- operators/kube-green/0.7.0/tests/scorecard/config.yaml
> operator kube-green (0.7.0)

- operators/codeflare-operator/1.14.0/manifests/codeflare-operator-appwrapper-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.14.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.14.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.14.0/manifests/codeflare-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.14.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.14.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.14.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.14.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.14.0/metadata/annotations.yaml
- operators/codeflare-operator/1.14.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.14.0)

- operators/susql-operator/0.0.33/Dockerfile
- operators/susql-operator/0.0.33/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
- operators/susql-operator/0.0.33/manifests/susql-operator-labelgroup-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.33/manifests/susql-operator-labelgroup-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.33/manifests/susql-operator-metrics-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.33/manifests/susql-operator-metrics-auth-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/susql-operator/0.0.33/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.33/manifests/susql-operator.clusterserviceversion.yaml
- operators/susql-operator/0.0.33/manifests/susql.ibm.com_labelgroups.yaml
- operators/susql-operator/0.0.33/metadata/annotations.yaml
- operators/susql-operator/0.0.33/tests/scorecard/config.yaml
> operator susql-operator (0.0.33)

- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.23.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.23.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.23.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.23.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.23.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.23.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.23.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.23.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.23.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.23.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.23.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.23.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.23.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.23.0)

- operators/project-quay/3.13.3/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.13.3/manifests/quayregistries.crd.yaml
- operators/project-quay/3.13.3/metadata/annotations.yaml
Add 3.13.3 to community operators
> operator project-quay (3.13.3)

- operators/skupper-operator/1.8.3/manifests/skupper-operator.v1.8.3.clusterserviceversion.yaml
- operators/skupper-operator/1.8.3/metadata/annotations.yaml
> operator skupper-operator (1.8.3)

- operators/gitlab-operator-kubernetes/1.9.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.9.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.9.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.9.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.9.1)

- operators/rabbitmq-cluster-operator/2.12.1/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.12.1/manifests/crds.yaml
- operators/rabbitmq-cluster-operator/2.12.1/manifests/rabbitmq.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.12.1/metadata/annotations.yaml
> operator rabbitmq-cluster-operator (2.12.1)

- operators/pubsubplus-eventbroker-operator/1.1.2/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
- operators/pubsubplus-eventbroker-operator/1.1.2/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
- operators/pubsubplus-eventbroker-operator/1.1.2/metadata/annotations.yaml
- operators/pubsubplus-eventbroker-operator/1.1.2/tests/scorecard/config.yaml
> operator pubsubplus-eventbroker-operator (1.1.2)

- operators/mariadb-operator/0.37.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.37.0/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.37.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.37.0/metadata/annotations.yaml
- operators/mariadb-operator/0.37.0/tests/scorecard/config.yaml
Added operator mariadb-operator (0.37.0)
> operator mariadb-operator (0.37.0)

- operators/mariadb-operator/0.37.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.37.1/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.37.1/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.37.1/metadata/annotations.yaml
- operators/mariadb-operator/0.37.1/tests/scorecard/config.yaml
Added operator mariadb-operator (0.37.1)
> operator mariadb-operator (0.37.1)

- operators/ndmspc-operator/0.20250131.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.20250131.0/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.20250131.0/metadata/annotations.yaml
- operators/ndmspc-operator/0.20250131.0/tests/scorecard/config.yaml
- operators/ndmspc-operator/ci.yaml
> operator ndmspc-operator (0.20250131.0)

- operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml
- operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-eguniversalagent-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-eguniversalagent-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator-webhook-service_v1_service.yaml
- operators/eginnovations-operator/0.0.10/manifests/eginnovations-operator.clusterserviceversion.yaml
- operators/eginnovations-operator/0.0.10/manifests/eginnovations.com_eguniversalagents.yaml
- operators/eginnovations-operator/0.0.10/metadata/annotations.yaml
- operators/eginnovations-operator/0.0.10/tests/scorecard/config.yaml
> operator eginnovations-operator (0.0.10)

- operators/dell-csm-operator/1.8.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.8.0/manifests/dell-csm-operator.v1.8.0.clusterserviceversion.yaml
- operators/dell-csm-operator/1.8.0/metadata/annotations.yaml
- operators/dell-csm-operator/1.8.0/tests/scorecard/config.yaml
> operator dell-csm-operator (1.8.0)

- operators/percona-server-mongodb-operator/1.19.0/manifests/percona-server-mongodb-operator.clusterserviceversion.yaml
- operators/percona-server-mongodb-operator/1.19.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.19.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.19.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml
- operators/percona-server-mongodb-operator/1.19.0/metadata/annotations.yaml
> operator percona-server-mongodb-operator (1.19.0)

- operators/mongodb-atlas-kubernetes/2.7.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.7.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.7.0)

- operators/victoriametrics-operator/Makefile
- operators/victoriametrics-operator/ci.yaml
The operator rendering process has changed and a new mapping in the ci.yaml file determines a target location of the catalog. This update is based on recent change introduced in operator pipelines.
In case something is not clear please reach out repository maintainers.
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this …
> Catalog update [victoriametrics-operator] [v4.15,v4.14,v4.13,v4.12,v4.16]

- operators/project-quay/3.11.8/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.8/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.8/metadata/annotations.yaml
Add 3.11.8 to community operators
> operator project-quay (3.11.8)

- operators/edp-keycloak-operator/1.24.0/manifests/client-secret-authorization-sample_v1_secret.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/client-secret-policy-sample_v1_secret.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakclients.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
- operators/edp-keycloak-operator/1.24.0/manifests/v1.edp.epam.com_keycloaks.yaml
- operators/edp-keycloak-operator/1.24.0/metadata/annotations.yaml
- operators/edp-keycloak-operator/1.24.0/tests/scorecard/config.yaml
> operator edp-keycloak-operator (1.24.0)

- operators/project-quay/3.10.8/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.8/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.8/metadata/annotations.yaml
Add 3.10.8 to community operators
> operator project-quay (3.10.8)

- operators/dell-csm-operator/Makefile
- operators/hazelcast-platform-operator/Makefile
- operators/kiali/Makefile
- operators/odf-node-recovery-operator/Makefile
- operators/shipwright-operator/Makefile
- operators/trident-operator/Makefile
- operators/victoriametrics-operator/Makefile
There was a copy/paste bug that uses hardcoded operator name in Makefile. This commit fixes it.
--
> Fix Makefiles for fbc operator

- operators/camel-k/2.5.1/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/camel-k.v2.5.1.clusterserviceversion.yaml
- operators/camel-k/2.5.1/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/kameletbindings.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.5.1/metadata/annotations.yaml
- operators/camel-k/2.5.1/tests/scorecard/config.yaml
> operator camel-k (2.5.1)

- operators/ndmspc-operator/0.20250209.0/manifests/apps.ndmspc.io_ndmspcconfigs.yaml
- operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator-controller-manager-metrics-service_v1_service.yaml
- operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator-manager-config_v1_configmap.yaml
- operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/ndmspc-operator/0.20250209.0/manifests/ndmspc-operator.clusterserviceversion.yaml
- operators/ndmspc-operator/0.20250209.0/metadata/annotations.yaml
- operators/ndmspc-operator/0.20250209.0/metadata/dependency.yaml
- operators/ndmspc-operator/0.20250209.0/tests/scorecard/config.yaml
> operator ndmspc-operator (0.20250209.0)

- operators/datadog-operator/1.12.1/manifests/datadog-operator-webhook-service_v1_service.yaml
- operators/datadog-operator/1.12.1/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadogagentprofiles.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadogdashboards.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadoggenericresources.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadogpodautoscalers.yaml
- operators/datadog-operator/1.12.1/manifests/datadoghq.com_datadogslos.yaml
- operators/datadog-operator/1.12.1/metadata/annotations.yaml
- operators/datadog-operator/1.12.1/tests/scorecard/config.yaml
> operator datadog-operator (1.12.1)

- operators/gitlab-operator-kubernetes/1.9.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.9.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.9.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.9.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.9.2)

- operators/opendatahub-operator/ci.yaml
update reviewer list for opendatahub
----
--
> update: reviewer list

- operators/dynatrace-operator/1.4.1/Dockerfile
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.4.1/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.4.1/metadata/annotations.yaml
> operator dynatrace-operator (1.4.1)

- operators/codeflare-operator/1.15.0/manifests/codeflare-operator-appwrapper-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.15.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.15.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.15.0/manifests/codeflare-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.15.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.15.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.15.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.15.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.15.0/metadata/annotations.yaml
- operators/codeflare-operator/1.15.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.15.0)

- operators/mongodb-atlas-kubernetes/2.7.1/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlascustomroles.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.7.1/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.7.1)

- operators/camel-k/2.6.0/manifests/builds.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/manifests/camel-k.v2.6.0.clusterserviceversion.yaml
- operators/camel-k/2.6.0/manifests/camelcatalogs.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/manifests/integrationkits.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/manifests/integrationplatforms.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/manifests/integrationprofiles.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/manifests/integrations.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/manifests/kamelets.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/manifests/pipes.camel.apache.org.crd.yaml
- operators/camel-k/2.6.0/metadata/annotations.yaml
- operators/camel-k/2.6.0/tests/scorecard/config.yaml
> operator camel-k (2.6.0)

- operators/strimzi-kafka-operator/ci.yaml
Trivial PR to add @katheris as Strimzi operator reviewer.
> Added katheris as Strimzi operator reviewer

- operators/flux-operator/0.14.0/manifests/flux-operator.clusterserviceversion.yaml
- operators/flux-operator/0.14.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.14.0/manifests/fluxreports.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.14.0/manifests/resourcesetinputproviders.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.14.0/manifests/resourcesets.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.14.0/metadata/annotations.yaml
- operators/flux-operator/0.14.0/tests/scorecard/config.yaml
> operator flux-operator (0.14.0)

- operators/tempo-operator/0.15.0/bundle.Dockerfile
- operators/tempo-operator/0.15.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.15.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.15.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.15.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.15.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.15.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.15.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.15.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.15.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.15.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.15.0/metadata/annotations.yaml
- operators/tempo-operator/0.15.0/tests/scorecard/config.yaml
Release tempo-operator `0.15.0`.
> operator tempo-operator (0.15.0)

- operators/tempo-operator/0.15.1/bundle.Dockerfile
- operators/tempo-operator/0.15.1/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.15.1/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.15.1/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.15.1/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.15.1/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.15.1/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.15.1/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.15.1/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.15.1/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.15.1/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.15.1/metadata/annotations.yaml
- operators/tempo-operator/0.15.1/tests/scorecard/config.yaml
Release tempo-operator `0.15.1`.
> operator tempo-operator (0.15.1)

- operators/gitlab-operator-kubernetes/1.10.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.10.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.10.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.10.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.10.0)

- .github/workflows/stale_issues.yaml
Old PR will be marked as stale and closed if no activity in a past 37 days.
--
> Enable stale for pull requests

- operators/ndb-operator/1.6.0/bundle.Dockerfile
- operators/ndb-operator/1.6.0/manifests/mysql.oracle.com_ndbclusters.yaml
- operators/ndb-operator/1.6.0/manifests/ndb-operator-svc_v1_service.yaml
- operators/ndb-operator/1.6.0/manifests/ndb-operator-webhook-service_v1_service.yaml
- operators/ndb-operator/1.6.0/manifests/ndb-operator.clusterserviceversion.yaml
- operators/ndb-operator/1.6.0/metadata/annotations.yaml
- operators/ndb-operator/ci.yaml
> operator ndb-operator (1.6.0)

- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.25.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.25.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.25.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.25.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.25.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.25.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.25.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.25.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.25.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.25.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.25.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.25.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.25.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.25.0)

- operators/gitlab-operator-kubernetes/1.10.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.10.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.10.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.10.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.10.1)

- operators/multicluster-global-hub-operator/1.4.0-dev.20250302/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
- operators/multicluster-global-hub-operator/1.4.0-dev.20250302/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.4.0-dev.20250302/manifests/multicluster-global-hub-webhook_v1_service.yaml
- operators/multicluster-global-hub-operator/1.4.0-dev.20250302/manifests/operator.open-cluster-management.io_multiclusterglobalhubagents.yaml
- operators/multicluster-global-hub-operator/1.4.0-dev.20250302/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.4.0-dev.20250302/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.4.0-dev.20250302)

- operators/automotive-infra/0.0.7/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.7/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.7/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.7/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.7/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.7/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.7/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.7/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.7/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.7/metadata/annotations.yaml
- operators/automotive-infra/0.0.7/tests/scorecard/config.yaml
> operator automotive-infra (0.0.7)

- operators/tempo-operator/0.15.2/bundle.Dockerfile
- operators/tempo-operator/0.15.2/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.15.2/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.15.2/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.15.2/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.15.2/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.15.2/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.15.2/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.15.2/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.15.2/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.15.2/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.15.2/metadata/annotations.yaml
- operators/tempo-operator/0.15.2/tests/scorecard/config.yaml
Release tempo-operator `0.15.2`.
> operator tempo-operator (0.15.2)

- operators/automotive-infra/0.0.8/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.8/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.8/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.8/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.8/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.8/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.8/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.8/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.8/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.8/metadata/annotations.yaml
- operators/automotive-infra/0.0.8/tests/scorecard/config.yaml
> operator automotive-infra (0.0.8)

- operators/tempo-operator/0.15.3/bundle.Dockerfile
- operators/tempo-operator/0.15.3/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.15.3/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.15.3/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.15.3/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.15.3/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.15.3/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.15.3/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.15.3/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.15.3/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.15.3/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.15.3/metadata/annotations.yaml
- operators/tempo-operator/0.15.3/tests/scorecard/config.yaml
Release tempo-operator `0.15.3`.
> operator tempo-operator (0.15.3)

- operators/infinispan/2.4.11/manifests/infinispan-operator-manager-config_v1_configmap.yaml
- operators/infinispan/2.4.11/manifests/infinispan-operator.clusterserviceversion.yaml
- operators/infinispan/2.4.11/manifests/infinispan.org_backups.yaml
- operators/infinispan/2.4.11/manifests/infinispan.org_batches.yaml
- operators/infinispan/2.4.11/manifests/infinispan.org_caches.yaml
- operators/infinispan/2.4.11/manifests/infinispan.org_infinispans.yaml
- operators/infinispan/2.4.11/manifests/infinispan.org_restores.yaml
- operators/infinispan/2.4.11/metadata/annotations.yaml
- operators/infinispan/2.4.11/tests/scorecard/config.yaml
> operator infinispan (2.4.11)

- operators/project-quay/3.12.8/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.8/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.8/metadata/annotations.yaml
Add 3.12.8 to community operators
> operator project-quay (3.12.8)

- operators/project-quay/3.11.9/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.9/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.9/metadata/annotations.yaml
Add 3.11.9 to community operators
> operator project-quay (3.11.9)

- operators/project-quay/3.10.9/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.9/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.9/metadata/annotations.yaml
Add 3.10.9 to community operators
> operator project-quay (3.10.9)

- operators/shipwright-operator/0.15.2/manifests/operator.shipwright.io_shipwrightbuilds.yaml
- operators/shipwright-operator/0.15.2/manifests/shipwright-operator-manager-config_v1_configmap.yaml
- operators/shipwright-operator/0.15.2/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/shipwright-operator/0.15.2/manifests/shipwright-operator-metrics-service_v1_service.yaml
- operators/shipwright-operator/0.15.2/manifests/shipwright-operator.clusterserviceversion.yaml
- operators/shipwright-operator/0.15.2/metadata/annotations.yaml
- operators/shipwright-operator/0.15.2/tests/scorecard/config.yaml
> operator shipwright-operator (0.15.2)

- operators/mongodb-atlas-kubernetes/2.8.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.8.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.8.0)

- operators/trident-operator/24.10.1/manifests/trident-operator.v24.10.1.clusterserviceversion.yaml
- operators/trident-operator/24.10.1/manifests/trident.netapp.io_tridentconfigurators_crd.yaml
- operators/trident-operator/24.10.1/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
- operators/trident-operator/24.10.1/metadata/annotations.yaml
> operator trident-operator (24.10.1)

- operators/move2kube-operator/0.3.15/bundle.Dockerfile
- operators/move2kube-operator/0.3.15/manifests/move2kube-operator-controller-manager-metrics-service_v1_service.yaml
- operators/move2kube-operator/0.3.15/manifests/move2kube-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/move2kube-operator/0.3.15/manifests/move2kube-operator.clusterserviceversion.yaml
- operators/move2kube-operator/0.3.15/manifests/move2kube.konveyor.io_move2kubes.yaml
- operators/move2kube-operator/0.3.15/metadata/annotations.yaml
- operators/move2kube-operator/0.3.15/tests/scorecard/config.yaml
An automated PR to update move2kube-operator to v0.3.15
> operator move2kube-operator (0.3.15)

- operators/edp-keycloak-operator/1.25.0/manifests/client-secret-authorization-sample_v1_secret.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/client-secret-policy-sample_v1_secret.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/edp-keycloak-operator-manager-config_v1_configmap.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/edp-keycloak-operator.clusterserviceversion.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_clusterkeycloaks.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakauthflows.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakclients.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakclientscopes.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmroles.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealms.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloakrealmusers.yaml
- operators/edp-keycloak-operator/1.25.0/manifests/v1.edp.epam.com_keycloaks.yaml
- operators/edp-keycloak-operator/1.25.0/metadata/annotations.yaml
- operators/edp-keycloak-operator/1.25.0/tests/scorecard/config.yaml
> operator edp-keycloak-operator (1.25.0)

- operators/trident-operator/25.2.0/manifests/trident-operator.v25.2.0.clusterserviceversion.yaml
- operators/trident-operator/25.2.0/manifests/trident.netapp.io_tridentconfigurators_crd.yaml
- operators/trident-operator/25.2.0/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
- operators/trident-operator/25.2.0/metadata/annotations.yaml
> operator trident-operator (25.2.0)

- operators/grafana-operator/5.17.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.17.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.17.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.17.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanalibrarypanels.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanamutetimings.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafananotificationpolicyroutes.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
- operators/grafana-operator/5.17.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.17.0/metadata/annotations.yaml
> operator grafana-operator (5.17.0)

- operators/trident-operator/25.2.1/manifests/trident-operator.v25.2.1.clusterserviceversion.yaml
- operators/trident-operator/25.2.1/manifests/trident.netapp.io_tridentconfigurators_crd.yaml
- operators/trident-operator/25.2.1/manifests/trident.netapp.io_tridentorchestrators_crd.yaml
- operators/trident-operator/25.2.1/metadata/annotations.yaml
> operator trident-operator (25.2.1)

- operators/multicluster-global-hub-operator/1.4.0/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
- operators/multicluster-global-hub-operator/1.4.0/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
- operators/multicluster-global-hub-operator/1.4.0/manifests/multicluster-global-hub-webhook_v1_service.yaml
- operators/multicluster-global-hub-operator/1.4.0/manifests/operator.open-cluster-management.io_multiclusterglobalhubagents.yaml
- operators/multicluster-global-hub-operator/1.4.0/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
- operators/multicluster-global-hub-operator/1.4.0/metadata/annotations.yaml
> operator multicluster-global-hub-operator (1.4.0)

- operators/gitlab-operator-kubernetes/1.10.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.10.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.10.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.10.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.10.2)

- operators/project-quay/3.9.10/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.9.10/manifests/quayregistries.crd.yaml
- operators/project-quay/3.9.10/metadata/annotations.yaml
Add 3.9.10 to community operators
> operator project-quay (3.9.10)

- operators/cass-operator-community/1.23.1/manifests/cass-operator-manager-config_v1_configmap.yaml
- operators/cass-operator-community/1.23.1/manifests/cass-operator-webhook-service_v1_service.yaml
- operators/cass-operator-community/1.23.1/manifests/cass-operator.clusterserviceversion.yaml
- operators/cass-operator-community/1.23.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml
- operators/cass-operator-community/1.23.1/manifests/control.k8ssandra.io_cassandratasks.yaml
- operators/cass-operator-community/1.23.1/metadata/annotations.yaml
- operators/cass-operator-community/1.23.1/tests/scorecard/config.yaml
> operator cass-operator-community (1.23.1)

- operators/automotive-infra/0.0.9/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.9/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.9/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.9/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.9/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.9/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.9/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.9/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.9/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.9/metadata/annotations.yaml
- operators/automotive-infra/0.0.9/tests/scorecard/config.yaml
> operator automotive-infra (0.0.9)

- operators/loki-operator/0.8.0/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-manager-config_v1_configmap.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator-webhook-service_v1_service.yaml
- operators/loki-operator/0.8.0/manifests/loki-operator.clusterserviceversion.yaml
- operators/loki-operator/0.8.0/manifests/loki.grafana.com_alertingrules.yaml
- operators/loki-operator/0.8.0/manifests/loki.grafana.com_lokistacks.yaml
- operators/loki-operator/0.8.0/manifests/loki.grafana.com_recordingrules.yaml
- operators/loki-operator/0.8.0/manifests/loki.grafana.com_rulerconfigs.yaml
- operators/loki-operator/0.8.0/metadata/annotations.yaml
- operators/loki-operator/0.8.0/tests/scorecard/config.yaml
> operator loki-operator (0.8.0)

- operators/victoriametrics-operator/catalog-templates/v4.12.yaml
- operators/victoriametrics-operator/catalog-templates/v4.13.yaml
- operators/victoriametrics-operator/catalog-templates/v4.14.yaml
- operators/victoriametrics-operator/catalog-templates/v4.15.yaml
- operators/victoriametrics-operator/catalog-templates/v4.16.yaml
- operators/victoriametrics-operator/catalog-templates/v4.17.yaml
- operators/victoriametrics-operator/catalog-templates/v4.18.yaml
victoriametrics-operator: synced catalog
> Catalog update [victoriametrics-operator] [v4.17,v4.18,v4.12,v4.15,v4.14,v4.13,v4.16]

- operators/datadog-operator/1.13.0/manifests/datadog-operator-webhook-service_v1_service.yaml
- operators/datadog-operator/1.13.0/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadogagentprofiles.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadogdashboards.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadoggenericresources.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadogpodautoscalers.yaml
- operators/datadog-operator/1.13.0/manifests/datadoghq.com_datadogslos.yaml
- operators/datadog-operator/1.13.0/metadata/annotations.yaml
- operators/datadog-operator/1.13.0/tests/scorecard/config.yaml
> operator datadog-operator (1.13.0)

- operators/cass-operator-community/1.23.2/manifests/cass-operator-manager-config_v1_configmap.yaml
- operators/cass-operator-community/1.23.2/manifests/cass-operator-webhook-service_v1_service.yaml
- operators/cass-operator-community/1.23.2/manifests/cass-operator.clusterserviceversion.yaml
- operators/cass-operator-community/1.23.2/manifests/cassandra.datastax.com_cassandradatacenters.yaml
- operators/cass-operator-community/1.23.2/manifests/control.k8ssandra.io_cassandratasks.yaml
- operators/cass-operator-community/1.23.2/metadata/annotations.yaml
- operators/cass-operator-community/1.23.2/tests/scorecard/config.yaml
> operator cass-operator-community (1.23.2)

- operators/multi-nic-cni-operator/1.2.6/bundle.Dockerfile
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multinic.fms.io_cidrs.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multinic.fms.io_configs.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multinic.fms.io_deviceclasses.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multinic.fms.io_hostinterfaces.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multinic.fms.io_ippools.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multinic.fms.io_multinicnetworks.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/metadata/annotations.yaml
- operators/multi-nic-cni-operator/1.2.6/bundle/tests/scorecard/config.yaml
- operators/multi-nic-cni-operator/Makefile
> Add push-bundle option to publish new release

- operators/multi-nic-cni-operator/1.2.6/bundle/manifests/multi-nic-cni-operator.clusterserviceversion.yaml
- operators/multi-nic-cni-operator/1.2.6/release-config.yaml
- operators/multi-nic-cni-operator/Makefile
- operators/multi-nic-cni-operator/version-info.mk
> auto-release to the OCP catalogs in the FBC mode

- operators/multi-nic-cni-operator/1.2.6/release-config.yaml
- operators/multi-nic-cni-operator/Makefile
> add ocp version 4.18 support

- operators/gitlab-operator-kubernetes/1.11.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.11.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.11.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.11.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.11.0)

- operators/odf-node-recovery-operator/1.0.0/manifests/odf-node-recovery-operator-controller-manager-metrics-service_v1_service.yaml
- operators/odf-node-recovery-operator/1.0.0/manifests/odf-node-recovery-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/odf-node-recovery-operator/1.0.0/manifests/odf-node-recovery-operator.clusterserviceversion.yaml
- operators/odf-node-recovery-operator/1.0.0/manifests/odf.openshift.io_noderecoveries.yaml
- operators/odf-node-recovery-operator/1.0.0/metadata/annotations.yaml
- operators/odf-node-recovery-operator/1.0.0/tests/scorecard/config.yaml
- operators/odf-node-recovery-operator/ci.yaml
> operator odf-node-recovery-operator (1.0.0)

- operators/mariadb-operator/0.38.0/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.38.0/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.38.0/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.38.0/metadata/annotations.yaml
- operators/mariadb-operator/0.38.0/tests/scorecard/config.yaml
Added operator mariadb-operator (0.38.0)
> operator mariadb-operator (0.38.0)

- operators/gitlab-operator-kubernetes/1.11.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.11.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.11.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.11.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.11.1)

- operators/neuvector-community-operator/1.5.2/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.5.2/manifests/neuvector-operator.v1.5.2.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.5.2/metadata/annotations.yaml
> operator neuvector-community-operator (1.5.2)

- operators/automotive-infra/0.0.10/manifests/automotive-infra-controller-manager-metrics-service_v1_service.yaml
- operators/automotive-infra/0.0.10/manifests/automotive-infra-manager-config_v1_configmap.yaml
- operators/automotive-infra/0.0.10/manifests/automotive-infra-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.10/manifests/automotive-infra-operatorconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.10/manifests/automotive-infra-operatorconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/automotive-infra/0.0.10/manifests/automotive-infra.clusterserviceversion.yaml
- operators/automotive-infra/0.0.10/manifests/automotive.sig.centos.org_containerbuilds.yaml
- operators/automotive-infra/0.0.10/manifests/automotive.sig.centos.org_imagebuilds.yaml
- operators/automotive-infra/0.0.10/manifests/automotive.sig.centos.org_operatorconfigs.yaml
- operators/automotive-infra/0.0.10/manifests/jumpstarter.dev_clients.yaml
- operators/automotive-infra/0.0.10/manifests/jumpstarter.dev_exporteraccesspolicies.yaml
- operators/automotive-infra/0.0.10/manifests/jumpstarter.dev_exporters.yaml
- operators/automotive-infra/0.0.10/manifests/jumpstarter.dev_leases.yaml
- operators/automotive-infra/0.0.10/metadata/annotations.yaml
- operators/automotive-infra/0.0.10/tests/scorecard/config.yaml
> operator automotive-infra (0.0.10)

- operators/ndb-operator/1.6.2/bundle.Dockerfile
- operators/ndb-operator/1.6.2/manifests/mysql.oracle.com_ndbclusters.yaml
- operators/ndb-operator/1.6.2/manifests/ndb-operator-svc_v1_service.yaml
- operators/ndb-operator/1.6.2/manifests/ndb-operator-webhook-service_v1_service.yaml
- operators/ndb-operator/1.6.2/manifests/ndb-operator.clusterserviceversion.yaml
- operators/ndb-operator/1.6.2/metadata/annotations.yaml
> operator ndb-operator (1.6.2)

- operators/gitlab-operator-kubernetes/1.11.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.11.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.11.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.11.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.11.2)

- operators/victoriametrics-operator/0.55.0/manifests/operator-metrics-service_v1_service.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vlogs.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmagents.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmalertmanagerconfigs.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmalertmanagers.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmalerts.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmauths.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmclusters.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmnodescrapes.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmpodscrapes.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmprobes.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmrules.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmscrapeconfigs.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmservicescrapes.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmsingles.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmstaticscrapes.yaml
- operators/victoriametrics-operator/0.55.0/manifests/operator.victoriametrics.com_vmusers.yaml
- operators/victoriametrics-operator/0.55.0/manifests/victoriametrics-operator.clusterserviceversion.yaml
- operators/victoriametrics-operator/0.55.0/manifests/webhook-service_v1_service.yaml
- operators/victoriametrics-operator/0.55.0/metadata/annotations.yaml
- operators/victoriametrics-operator/0.55.0/tests/scorecard/config.yaml
- operators/victoriametrics-operator/catalog-templates/v4.12.yaml
- operators/victoriametrics-operator/catalog-templates/v4.13.yaml
- operators/victoriametrics-operator/catalog-templates/v4.14.yaml
- operators/victoriametrics-operator/catalog-templates/v4.15.yaml
- operators/victoriametrics-operator/catalog-templates/v4.16.yaml
- operators/victoriametrics-operator/catalog-templates/v4.17.yaml
- operators/victoriametrics-operator/catalog-templates/v4.18.yaml
victoriametrics operator v0.55.0
> operator victoriametrics-operator (0.55.0)

- operators/project-quay/3.14.0/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.14.0/manifests/quayregistries.crd.yaml
- operators/project-quay/3.14.0/metadata/annotations.yaml
Add 3.14.0 to community operators
> operator project-quay (3.14.0)

- operators/dynatrace-operator/1.4.2/Dockerfile
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.4.2/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.4.2/metadata/annotations.yaml
> operator dynatrace-operator (1.4.2)

- operators/dell-csm-operator/1.8.1/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.8.1/manifests/dell-csm-operator.v1.8.1.clusterserviceversion.yaml
- operators/dell-csm-operator/1.8.1/metadata/annotations.yaml
- operators/dell-csm-operator/1.8.1/tests/scorecard/config.yaml
- operators/dell-csm-operator/ci.yaml
This is a patch to dell-csm-operator 1.8.0. One of the images is updated along with the updated Operator image.
--
> operator dell-csm-operator (1.8.1)

- operators/skupper-operator/1.9.0/manifests/skupper-operator.v1.9.0.clusterserviceversion.yaml
- operators/skupper-operator/1.9.0/metadata/annotations.yaml
> operator skupper-operator (1.9.0)

- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.27.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.27.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.27.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.27.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.27.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.27.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.27.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.27.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.27.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.27.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.27.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.27.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.27.0/tests/scorecard/config.yaml
Signed-off-by: AjayJagan <ajaganat@redhat.com>
--
> operator opendatahub-operator (2.27.0)

- operators/grafana-operator/5.17.1/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.17.1/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.17.1/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.17.1/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanalibrarypanels.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanamutetimings.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafananotificationpolicyroutes.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
- operators/grafana-operator/5.17.1/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.17.1/metadata/annotations.yaml
> operator grafana-operator (5.17.1)

- operators/mariadb-operator/0.38.1/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/0.38.1/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/0.38.1/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/0.38.1/metadata/annotations.yaml
- operators/mariadb-operator/0.38.1/tests/scorecard/config.yaml
Added operator mariadb-operator (0.38.1)
> operator mariadb-operator (0.38.1)

- operators/percona-xtradb-cluster-operator/1.17.0/manifests/percona-xtradb-cluster-operator.v1.17.0.clusterserviceversion.yaml
- operators/percona-xtradb-cluster-operator/1.17.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.17.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.17.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml
- operators/percona-xtradb-cluster-operator/1.17.0/metadata/annotations.yaml
> operator percona-xtradb-cluster-operator (1.17.0)

- operators/infinispan/2.4.12/manifests/infinispan-operator-manager-config_v1_configmap.yaml
- operators/infinispan/2.4.12/manifests/infinispan-operator.clusterserviceversion.yaml
- operators/infinispan/2.4.12/manifests/infinispan.org_backups.yaml
- operators/infinispan/2.4.12/manifests/infinispan.org_batches.yaml
- operators/infinispan/2.4.12/manifests/infinispan.org_caches.yaml
- operators/infinispan/2.4.12/manifests/infinispan.org_infinispans.yaml
- operators/infinispan/2.4.12/manifests/infinispan.org_restores.yaml
- operators/infinispan/2.4.12/metadata/annotations.yaml
- operators/infinispan/2.4.12/tests/scorecard/config.yaml
> operator infinispan (2.4.12)

- operators/gitlab-operator-kubernetes/1.12.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.12.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.12.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.12.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.12.0)

- operators/nexus-operator/3.4.0/manifests/edp.epam.com_nexusblobstores.yaml
- operators/nexus-operator/3.4.0/manifests/edp.epam.com_nexuscleanuppolicies.yaml
- operators/nexus-operator/3.4.0/manifests/edp.epam.com_nexuses.yaml
- operators/nexus-operator/3.4.0/manifests/edp.epam.com_nexusrepositories.yaml
- operators/nexus-operator/3.4.0/manifests/edp.epam.com_nexusroles.yaml
- operators/nexus-operator/3.4.0/manifests/edp.epam.com_nexusscripts.yaml
- operators/nexus-operator/3.4.0/manifests/edp.epam.com_nexususers.yaml
- operators/nexus-operator/3.4.0/manifests/nexus-operator-controller-manager-metrics-service_v1_service.yaml
- operators/nexus-operator/3.4.0/manifests/nexus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/nexus-operator/3.4.0/manifests/nexus-operator-webhook-service_v1_service.yaml
- operators/nexus-operator/3.4.0/manifests/nexus-operator.clusterserviceversion.yaml
- operators/nexus-operator/3.4.0/metadata/annotations.yaml
- operators/nexus-operator/3.4.0/tests/scorecard/config.yaml
> operator nexus-operator (3.4.0)

- operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonargroups.yaml
- operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarpermissiontemplates.yaml
- operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarqualitygates.yaml
- operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarqualityprofiles.yaml
- operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonars.yaml
- operators/sonar-operator/3.2.0/manifests/edp.epam.com_sonarusers.yaml
- operators/sonar-operator/3.2.0/manifests/sonar-operator.clusterserviceversion.yaml
- operators/sonar-operator/3.2.0/metadata/annotations.yaml
- operators/sonar-operator/3.2.0/tests/scorecard/config.yaml
> operator sonar-operator (3.2.0)

- operators/gitlab-operator-kubernetes/1.12.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.12.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.12.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.12.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.12.1)

- operators/pulp-operator/1.0.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/1.0.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/1.0.0/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/pulp-operator/1.0.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/1.0.0/manifests/pulp-operator.clusterserviceversion.yaml
- operators/pulp-operator/1.0.0/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/1.0.0/manifests/repo-manager.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/1.0.0/manifests/repo-manager.pulpproject.org_pulps.yaml
- operators/pulp-operator/1.0.0/manifests/settings_v1_configmap.yaml
- operators/pulp-operator/1.0.0/metadata/annotations.yaml
- operators/pulp-operator/1.0.0/tests/scorecard/config.yaml
> operator pulp-operator (1.0.0)

- operators/project-quay/3.12.9/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.9/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.9/metadata/annotations.yaml
Add 3.12.9 to community operators
> operator project-quay (3.12.9)

- operators/dynatrace-operator/1.5.1/Dockerfile
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-edgeconnect_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_role.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-controller_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-extensions-prometheus_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-logmonitoring_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-logmonitoring_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-node-config-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-opentelemetry-collector_v1_serviceaccount.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-telemetry-ingest_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-telemetry-ingest_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.5.1/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.5.1/metadata/annotations.yaml
> operator dynatrace-operator (1.5.1)

- operators/project-quay/3.11.10/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.10/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.10/metadata/annotations.yaml
Add 3.11.10 to community operators
> operator project-quay (3.11.10)

- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.28.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.28.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.28.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.28.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.28.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.28.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.28.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.28.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.28.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.28.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.28.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.28.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.28.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.28.0)

- operators/project-quay/3.9.11/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.9.11/manifests/quayregistries.crd.yaml
- operators/project-quay/3.9.11/metadata/annotations.yaml
Add 3.9.11 to community operators
> operator project-quay (3.9.11)

- operators/apicurio-registry-3/3.0.7/bundle.Dockerfile
- operators/apicurio-registry-3/3.0.7/manifests/apicurio-registry-3.clusterserviceversion.yaml
- operators/apicurio-registry-3/3.0.7/manifests/registry.apicur.io_apicurioregistries3.yaml
- operators/apicurio-registry-3/3.0.7/metadata/annotations.yaml
- operators/apicurio-registry-3/ci.yaml
> operator apicurio-registry-3 (3.0.7)

- operators/deployment-validation-operator/0.7.9/manifests/deploymentvalidationoperator-service.yaml
- operators/deployment-validation-operator/0.7.9/manifests/deploymentvalidationoperator.0.7.9.clusterserviceversion.yaml
- operators/deployment-validation-operator/0.7.9/metadata/annotations.yaml
- operators/deployment-validation-operator/0.7.9/tests/scorecard/config.yaml
Signed-off-by: Isaac <ijimeno@redhat.com>
deployment-validation-operator new-release v0.7.9
--
> operator deployment-validation-operator (0.7.9)

- operators/pubsubplus-eventbroker-operator/1.3.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
- operators/pubsubplus-eventbroker-operator/1.3.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
- operators/pubsubplus-eventbroker-operator/1.3.0/metadata/annotations.yaml
- operators/pubsubplus-eventbroker-operator/1.3.0/tests/scorecard/config.yaml
> operator pubsubplus-eventbroker-operator (1.3.0)

- operators/gitlab-operator-kubernetes/1.12.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/1.12.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/1.12.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/1.12.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (1.12.2)

- operators/project-quay/3.10.10/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.10/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.10/metadata/annotations.yaml
Add 3.10.10 to community operators
> operator project-quay (3.10.10)

- operators/hawtio-operator/1.2.0/manifests/hawt.io_hawtios.yaml
- operators/hawtio-operator/1.2.0/manifests/hawtio-operator.clusterserviceversion.yaml
- operators/hawtio-operator/1.2.0/metadata/annotations.yaml
- operators/hawtio-operator/1.2.0/tests/scorecard/config.yaml
> operator hawtio-operator (1.2.0)

- operators/skupper-operator/1.9.1/manifests/skupper-operator.v1.9.1.clusterserviceversion.yaml
- operators/skupper-operator/1.9.1/metadata/annotations.yaml
> operator skupper-operator (1.9.1)

- operators/coherence-operator/3.5.0/manifests/coherence-operator-coherence-webhook-server-cert_v1_secret.yaml
- operators/coherence-operator/3.5.0/manifests/coherence-operator-metrics-service_v1_service.yaml
- operators/coherence-operator/3.5.0/manifests/coherence-operator-rest_v1_service.yaml
- operators/coherence-operator/3.5.0/manifests/coherence-operator-webhook_v1_service.yaml
- operators/coherence-operator/3.5.0/manifests/coherence-operator.clusterserviceversion.yaml
- operators/coherence-operator/3.5.0/manifests/coherence.oracle.com_coherence.yaml
- operators/coherence-operator/3.5.0/manifests/coherence.oracle.com_coherencejob.yaml
- operators/coherence-operator/3.5.0/metadata/annotations.yaml
- operators/coherence-operator/3.5.0/release-config.yaml
- operators/coherence-operator/3.5.0/tests/scorecard/config.yaml
* [x ] Add more than one operator bundle per PR
* [x ] Modify any operator
* [x ] Rename an operator
* [x ] Modify any files outside the above-mentioned folders
* [ x] Contain more than one commit. **Please squash your commits.**
1. [ x] Description of the managed Application and where to find more information
2. [x ] Features and capabilities of your Operator and how to use it
3. [x ] Any manual steps about potential pre-requisites for using your Operator
* [ x] Human-readable name and 1-liner description about your Operator
* [ x] Valid [category](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories) name <sup>1</sup>
* [ x] One of …
> operator coherence-operator (3.5.0)

- operators/snapscheduler/3.5.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
- operators/snapscheduler/3.5.0/manifests/snapscheduler-manager-config_v1_configmap.yaml
- operators/snapscheduler/3.5.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/snapscheduler/3.5.0/manifests/snapscheduler.backube_snapshotschedules.yaml
- operators/snapscheduler/3.5.0/manifests/snapscheduler.clusterserviceversion.yaml
- operators/snapscheduler/3.5.0/metadata/annotations.yaml
- operators/snapscheduler/3.5.0/tests/scorecard/config.yaml
> operator snapscheduler (3.5.0)

- operators/grafana-operator/5.18.0/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.18.0/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.18.0/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.18.0/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanalibrarypanels.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanamutetimings.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafananotificationpolicyroutes.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
- operators/grafana-operator/5.18.0/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.18.0/metadata/annotations.yaml
> operator grafana-operator (5.18.0)

- operators/opendatahub-operator/ci.yaml
This is a follow up PR to fix wrong catalog folder entries in the ci.yaml for opendatahub-operator.
previous PR: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/6634
-- …
> (fix): Add folder names with v for catalogs

- operators/project-quay/3.13.5/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.13.5/manifests/quayregistries.crd.yaml
- operators/project-quay/3.13.5/metadata/annotations.yaml
Add 3.13.5 to community operators
> operator project-quay (3.13.5)

- operators/project-quay/3.14.1/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.14.1/manifests/quayregistries.crd.yaml
- operators/project-quay/3.14.1/metadata/annotations.yaml
Add 3.14.1 to community operators
> operator project-quay (3.14.1)

- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.29.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.29.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.29.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.29.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.29.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.29.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.29.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.29.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.29.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.29.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.29.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.29.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.29.0/release-config.yaml
- operators/opendatahub-operator/2.29.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.29.0)

- operators/dell-csm-operator/1.9.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
- operators/dell-csm-operator/1.9.0/manifests/dell-csm-operator.v1.9.0.clusterserviceversion.yaml
- operators/dell-csm-operator/1.9.0/metadata/annotations.yaml
- operators/dell-csm-operator/1.9.0/tests/scorecard/config.yaml
> operator dell-csm-operator (1.9.0)

- operators/gitlab-operator-kubernetes/2.0.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/2.0.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.0.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/2.0.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (2.0.1)

- catalogs/v4.17/sailoperator/catalog.yaml
- catalogs/v4.18/sailoperator/catalog.yaml
- operators/sailoperator/Makefile
- operators/sailoperator/catalog-templates/basic.yaml
- operators/sailoperator/ci.yaml
This change is also cleaning old unused channels:
3.0-nightly
0.1-nightly
0.2-nightly
0.3-nightly
1.0-nightly
1.1-nightly
stable-0.2
3.0-dp1
1.26-nightly
--
> Catalog update [sailoperator] [v4.14,v4.15,v4.16,v4.17,v4.18]

- operators/apicurio-registry-3/3.0.8/bundle.Dockerfile
- operators/apicurio-registry-3/3.0.8/manifests/apicurio-registry-3.clusterserviceversion.yaml
- operators/apicurio-registry-3/3.0.8/manifests/registry.apicur.io_apicurioregistries3.yaml
- operators/apicurio-registry-3/3.0.8/metadata/annotations.yaml
> operator apicurio-registry-3 (3.0.8)

- operators/odf-node-recovery-operator/1.1.0/manifests/odf-node-recovery-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/odf-node-recovery-operator/1.1.0/manifests/odf-node-recovery-operator-controller-manager-metrics-service_v1_service.yaml
- operators/odf-node-recovery-operator/1.1.0/manifests/odf-node-recovery-operator-metrics-reader_v1_secret.yaml
- operators/odf-node-recovery-operator/1.1.0/manifests/odf-node-recovery-operator-noderecovery-admin-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/odf-node-recovery-operator/1.1.0/manifests/odf-node-recovery-operator-noderecovery-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/odf-node-recovery-operator/1.1.0/manifests/odf-node-recovery-operator-noderecovery-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/odf-node-recovery-operator/1.1.0/manifests/odf-node-recovery-operator.clusterserviceversion.yaml
- operators/odf-node-recovery-operator/1.1.0/manifests/odf.openshift.io_noderecoveries.yaml
- operators/odf-node-recovery-operator/1.1.0/metadata/annotations.yaml
- operators/odf-node-recovery-operator/1.1.0/tests/scorecard/config.yaml
- operators/odf-node-recovery-operator/catalog-templates/basic.yaml
- operators/odf-node-recovery-operator/ci.yaml
> operator odf-node-recovery-operator (1.1.0)

- operators/ack-bedrockagent-controller/0.0.2/bundle.Dockerfile
- operators/ack-bedrockagent-controller/0.0.2/manifests/ack-bedrockagent-controller.clusterserviceversion.yaml
- operators/ack-bedrockagent-controller/0.0.2/manifests/ack-bedrockagent-metrics-service_v1_service.yaml
- operators/ack-bedrockagent-controller/0.0.2/manifests/ack-bedrockagent-reader_rbac.authorization.k8s.io_v1_role.yaml
- operators/ack-bedrockagent-controller/0.0.2/manifests/ack-bedrockagent-writer_rbac.authorization.k8s.io_v1_role.yaml
- operators/ack-bedrockagent-controller/0.0.2/manifests/bedrockagent.services.k8s.aws_agents.yaml
- operators/ack-bedrockagent-controller/0.0.2/metadata/annotations.yaml
- operators/ack-bedrockagent-controller/0.0.2/tests/scorecard/config.yaml
> operator ack-bedrockagent-controller (0.0.2)

- operators/neuvector-community-operator/1.5.3/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.5.3/manifests/neuvector-operator.v1.5.3.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.5.3/metadata/annotations.yaml
> operator neuvector-community-operator (1.5.3)

- operators/apicurio-registry-3/3.0.9/bundle.Dockerfile
- operators/apicurio-registry-3/3.0.9/manifests/apicurio-registry-3.clusterserviceversion.yaml
- operators/apicurio-registry-3/3.0.9/manifests/registry.apicur.io_apicurioregistries3.yaml
- operators/apicurio-registry-3/3.0.9/metadata/annotations.yaml
> operator apicurio-registry-3 (3.0.9)

- operators/koku-metrics-operator/4.0.0/manifests/costmanagement-metrics-cfg.openshift.io_costmanagementmetricsconfigs.yaml
- operators/koku-metrics-operator/4.0.0/manifests/koku-metrics-operator.clusterserviceversion.yaml
- operators/koku-metrics-operator/4.0.0/metadata/annotations.yaml
- operators/koku-metrics-operator/4.0.0/release-config.yaml
- operators/koku-metrics-operator/4.0.0/tests/scorecard/config.yaml
- operators/koku-metrics-operator/ci.yaml
> operator koku-metrics-operator (4.0.0)

- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_llamastackoperators.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.30.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.30.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.30.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.30.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.30.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.30.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.30.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.30.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.30.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.30.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.30.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.30.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.30.0/release-config.yaml
- operators/opendatahub-operator/2.30.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.30.0)

- operators/project-quay/3.13.6/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.13.6/manifests/quayregistries.crd.yaml
- operators/project-quay/3.13.6/metadata/annotations.yaml
Add 3.13.6 to community operators
> operator project-quay (3.13.6)

- operators/codeflare-operator/1.16.0/manifests/codeflare-operator-appwrapper-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.16.0/manifests/codeflare-operator-manager-metrics_v1_service.yaml
- operators/codeflare-operator/1.16.0/manifests/codeflare-operator-stack-config_v1_configmap.yaml
- operators/codeflare-operator/1.16.0/manifests/codeflare-operator-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/codeflare-operator/1.16.0/manifests/codeflare-operator-webhook-server-cert_v1_secret.yaml
- operators/codeflare-operator/1.16.0/manifests/codeflare-operator-webhook-service_v1_service.yaml
- operators/codeflare-operator/1.16.0/manifests/codeflare-operator.clusterserviceversion.yaml
- operators/codeflare-operator/1.16.0/manifests/workload.codeflare.dev_appwrappers.yaml
- operators/codeflare-operator/1.16.0/metadata/annotations.yaml
- operators/codeflare-operator/1.16.0/tests/scorecard/config.yaml
> operator codeflare-operator (1.16.0)

- operators/dapr-kubernetes-operator/0.0.10/manifests/dapr-kubernetes-operator.clusterserviceversion.yaml
- operators/dapr-kubernetes-operator/0.0.10/manifests/operator.dapr.io_daprcontrolplanes.yaml
- operators/dapr-kubernetes-operator/0.0.10/manifests/operator.dapr.io_daprcruiscontrols.yaml
- operators/dapr-kubernetes-operator/0.0.10/manifests/operator.dapr.io_daprinstances.yaml
- operators/dapr-kubernetes-operator/0.0.10/metadata/annotations.yaml
- operators/dapr-kubernetes-operator/0.0.10/tests/scorecard/config.yaml
> operator dapr-kubernetes-operator (0.0.10)

- operators/gitlab-operator-kubernetes/2.1.0/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/2.1.0/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.1.0/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/2.1.0/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (2.1.0)

- operators/group-sync-operator/0.0.32/Dockerfile
- operators/group-sync-operator/0.0.32/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.32/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.32/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.32/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.32/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.32/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.32/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.32/metadata/annotations.yaml
- operators/group-sync-operator/0.0.32/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.32)

- operators/project-quay/3.10.11/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.11/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.11/metadata/annotations.yaml
Add 3.10.11 to community operators
> operator project-quay (3.10.11)

- operators/skupper-operator/1.9.2/manifests/skupper-operator.v1.9.2.clusterserviceversion.yaml
- operators/skupper-operator/1.9.2/metadata/annotations.yaml
- operators/skupper-operator/ci.yaml
> operator skupper-operator (1.9.2)

- operators/project-quay/3.9.12/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.9.12/manifests/quayregistries.crd.yaml
- operators/project-quay/3.9.12/metadata/annotations.yaml
Add 3.9.12 to community operators
> operator project-quay (3.9.12)

- operators/mongodb-atlas-kubernetes/2.9.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.9.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.9.0)

- operators/dell-csm-operator/catalog-templates/v4.14.yaml
- operators/dell-csm-operator/catalog-templates/v4.15.yaml
- operators/dell-csm-operator/catalog-templates/v4.16.yaml
- operators/dell-csm-operator/catalog-templates/v4.17.yaml
- operators/dell-csm-operator/catalog-templates/v4.18.yaml
> fbc changes to dell-csm-operator

- operators/coherence-operator/3.5.2/manifests/coherence-operator-coherence-webhook-server-cert_v1_secret.yaml
- operators/coherence-operator/3.5.2/manifests/coherence-operator-metrics-service_v1_service.yaml
- operators/coherence-operator/3.5.2/manifests/coherence-operator-rest_v1_service.yaml
- operators/coherence-operator/3.5.2/manifests/coherence-operator-webhook_v1_service.yaml
- operators/coherence-operator/3.5.2/manifests/coherence-operator.clusterserviceversion.yaml
- operators/coherence-operator/3.5.2/manifests/coherence.oracle.com_coherence.yaml
- operators/coherence-operator/3.5.2/manifests/coherence.oracle.com_coherencejob.yaml
- operators/coherence-operator/3.5.2/metadata/annotations.yaml
- operators/coherence-operator/3.5.2/release-config.yaml
- operators/coherence-operator/3.5.2/tests/scorecard/config.yaml
* [x ] Are you familiar with our [contribution guidelines](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/contributing-prerequisites/)?
* [x ] Are you familiar with our [operator pipeline](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/pipelines_overview/)?
* [x ] Have you tested your Operator with all Custom Resource Definitions [packaging](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)?
* [ x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ …
> operator coherence-operator (3.5.2)

- operators/mongodb-atlas-kubernetes/2.9.1/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlascustomroles.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.9.1/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.9.1)

- operators/susql-operator/0.0.35/Dockerfile
- operators/susql-operator/0.0.35/manifests/susql-operator-controller-manager-metrics-service_v1_service.yaml
- operators/susql-operator/0.0.35/manifests/susql-operator-labelgroup-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.35/manifests/susql-operator-labelgroup-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.35/manifests/susql-operator-metrics-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.35/manifests/susql-operator-metrics-auth-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/susql-operator/0.0.35/manifests/susql-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/susql-operator/0.0.35/manifests/susql-operator.clusterserviceversion.yaml
- operators/susql-operator/0.0.35/manifests/susql.ibm.com_labelgroups.yaml
- operators/susql-operator/0.0.35/metadata/annotations.yaml
- operators/susql-operator/0.0.35/tests/scorecard/config.yaml
> operator susql-operator (0.0.35)

- operators/group-sync-operator/0.0.33/Dockerfile
- operators/group-sync-operator/0.0.33/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.33/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.33/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.33/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.33/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.33/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.33/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.33/metadata/annotations.yaml
- operators/group-sync-operator/0.0.33/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.33)

- operators/netobserv-operator/1.6.3-community/manifests/flows.netobserv.io_flowcollectors.yaml
- operators/netobserv-operator/1.6.3-community/manifests/flows.netobserv.io_flowmetrics.yaml
- operators/netobserv-operator/1.6.3-community/manifests/netobserv-manager-config_v1_configmap.yaml
- operators/netobserv-operator/1.6.3-community/manifests/netobserv-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/netobserv-operator/1.6.3-community/manifests/netobserv-metrics-service_v1_service.yaml
- operators/netobserv-operator/1.6.3-community/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/netobserv-operator/1.6.3-community/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/netobserv-operator/1.6.3-community/manifests/netobserv-operator.clusterserviceversion.yaml
- operators/netobserv-operator/1.6.3-community/manifests/netobserv-webhook-service_v1_service.yaml
- operators/netobserv-operator/1.6.3-community/metadata/annotations.yaml
> operator netobserv-operator (1.6.3-community)

- operators/group-sync-operator/0.0.34/Dockerfile
- operators/group-sync-operator/0.0.34/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.34/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.34/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.34/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.34/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.34/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.34/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.34/metadata/annotations.yaml
- operators/group-sync-operator/0.0.34/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.34)

- operators/neuvector-community-operator/1.5.4/manifests/neuvector-operator.crd.yaml
- operators/neuvector-community-operator/1.5.4/manifests/neuvector-operator.v1.5.4.clusterserviceversion.yaml
- operators/neuvector-community-operator/1.5.4/metadata/annotations.yaml
> operator neuvector-community-operator (1.5.4)

- operators/project-quay/3.10.12/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.12/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.12/metadata/annotations.yaml
Add 3.10.12 to community operators
> operator project-quay (3.10.12)

- operators/project-quay/3.15.0/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.15.0/manifests/quayregistries.crd.yaml
- operators/project-quay/3.15.0/metadata/annotations.yaml
Add 3.15.0 to community operators
> operator project-quay (3.15.0)

- operators/project-quay/3.14.3/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.14.3/manifests/quayregistries.crd.yaml
- operators/project-quay/3.14.3/metadata/annotations.yaml
Add 3.14.3 to community operators
> operator project-quay (3.14.3)

- operators/dynatrace-operator/1.6.1/Dockerfile
- operators/dynatrace-operator/1.6.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.6.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.6.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.6.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.6.1/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.6.1/metadata/annotations.yaml
> operator dynatrace-operator (1.6.1)

- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_llamastackoperators.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.32.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.32.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.32.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.32.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.32.0/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
- operators/opendatahub-operator/2.32.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.32.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.32.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.32.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.32.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.32.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.32.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.32.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.32.0/release-config.yaml
- operators/opendatahub-operator/2.32.0/tests/scorecard/config.yaml
Signed-off-by: Ajay Jaganathan <36824134+AjayJagan@users.noreply.github.com>
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-ca …
> operator opendatahub-operator (2.32.0)

- operators/mariadb-operator/25.8.2/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_physicalbackups.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/25.8.2/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/25.8.2/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/25.8.2/metadata/annotations.yaml
- operators/mariadb-operator/25.8.2/tests/scorecard/config.yaml
Added operator mariadb-operator (25.8.2)
> operator mariadb-operator (25.8.2)

- operators/project-quay/3.12.11/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.12.11/manifests/quayregistries.crd.yaml
- operators/project-quay/3.12.11/metadata/annotations.yaml
Add 3.12.11 to community operators
> operator project-quay (3.12.11)

- operators/pubsubplus-eventbroker-operator/1.4.0/manifests/pubsubplus-eventbroker-operator.clusterserviceversion.yaml
- operators/pubsubplus-eventbroker-operator/1.4.0/manifests/pubsubplus.solace.com_pubsubpluseventbrokers.yaml
- operators/pubsubplus-eventbroker-operator/1.4.0/metadata/annotations.yaml
- operators/pubsubplus-eventbroker-operator/1.4.0/tests/scorecard/config.yaml
> operator pubsubplus-eventbroker-operator (1.4.0)

- operators/group-sync-operator/0.0.35/Dockerfile
- operators/group-sync-operator/0.0.35/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.35/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.35/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.35/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.35/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.35/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.35/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.35/metadata/annotations.yaml
- operators/group-sync-operator/0.0.35/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.35)

- operators/project-quay/3.11.12/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.11.12/manifests/quayregistries.crd.yaml
- operators/project-quay/3.11.12/metadata/annotations.yaml
Add 3.11.12 to community operators
> operator project-quay (3.11.12)

- operators/mariadb-operator/25.8.3/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_physicalbackups.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/25.8.3/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/25.8.3/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/25.8.3/metadata/annotations.yaml
- operators/mariadb-operator/25.8.3/tests/scorecard/config.yaml
Added operator mariadb-operator (25.8.3)
> operator mariadb-operator (25.8.3)

- operators/project-quay/3.10.13/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.10.13/manifests/quayregistries.crd.yaml
- operators/project-quay/3.10.13/metadata/annotations.yaml
Add 3.10.13 to community operators
> operator project-quay (3.10.13)

- operators/datadog-operator/1.17.0/manifests/datadog-operator-webhook-service_v1_service.yaml
- operators/datadog-operator/1.17.0/manifests/datadog-operator.clusterserviceversion.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogagentinternals.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogagentprofiles.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogagents.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogdashboards.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadoggenericresources.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogmetrics.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogmonitors.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogpodautoscalers.yaml
- operators/datadog-operator/1.17.0/manifests/datadoghq.com_datadogslos.yaml
- operators/datadog-operator/1.17.0/metadata/annotations.yaml
- operators/datadog-operator/ci.yaml
> operator datadog-operator (1.17.0)

- operators/nfs-provisioner-operator/0.0.8/manifests/cache.jhouse.com_nfsprovisioners.yaml
- operators/nfs-provisioner-operator/0.0.8/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml
- operators/nfs-provisioner-operator/0.0.8/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/nfs-provisioner-operator/0.0.8/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
- operators/nfs-provisioner-operator/0.0.8/metadata/annotations.yaml
- operators/nfs-provisioner-operator/0.0.8/tests/scorecard/config.yaml
> operator nfs-provisioner-operator (0.0.8)

- operators/rabbitmq-cluster-operator/2.16.0/bundle.Dockerfile
- operators/rabbitmq-cluster-operator/2.16.0/manifests/rabbitmq-cluster-operator.clusterserviceversion.yaml
- operators/rabbitmq-cluster-operator/2.16.0/manifests/rabbitmq.com_rabbitmqcluster.yaml
- operators/rabbitmq-cluster-operator/2.16.0/metadata/annotations.yaml
Update operator rabbitmq-cluster-operator (2.16.0)
> operator rabbitmq-cluster-operator (2.16.0)

- operators/group-sync-operator/0.0.36/Dockerfile
- operators/group-sync-operator/0.0.36/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operators/group-sync-operator/0.0.36/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml
- operators/group-sync-operator/0.0.36/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/group-sync-operator/0.0.36/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- operators/group-sync-operator/0.0.36/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/group-sync-operator/0.0.36/manifests/group-sync-operator.clusterserviceversion.yaml
- operators/group-sync-operator/0.0.36/manifests/redhatcop.redhat.io_groupsyncs.yaml
- operators/group-sync-operator/0.0.36/metadata/annotations.yaml
- operators/group-sync-operator/0.0.36/tests/scorecard/config.yaml
> operator group-sync-operator (0.0.36)

- operators/apicurio-registry-3/3.0.12/bundle.Dockerfile
- operators/apicurio-registry-3/3.0.12/manifests/apicurio-registry-3.clusterserviceversion.yaml
- operators/apicurio-registry-3/3.0.12/manifests/registry.apicur.io_apicurioregistries3.yaml
- operators/apicurio-registry-3/3.0.12/metadata/annotations.yaml
> operator apicurio-registry-3 (3.0.12)

- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_llamastackoperators.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.33.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.33.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.33.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.33.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.33.0/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
- operators/opendatahub-operator/2.33.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.33.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.33.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.33.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.33.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.33.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.33.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.33.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.33.0/release-config.yaml
- operators/opendatahub-operator/2.33.0/tests/scorecard/config.yaml
Signed-off-by: Ajay Jaganathan <36824134+AjayJagan@users.noreply.github.com>
--
<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-ca …
> operator opendatahub-operator (2.33.0)

- operators/gitlab-operator-kubernetes/2.2.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/2.2.3/metadata/annotations.yaml
> operator gitlab-operator-kubernetes (2.2.3)

- operators/grafana-operator/5.19.4/manifests/grafana-operator-manager-config_v1_configmap.yaml
- operators/grafana-operator/5.19.4/manifests/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/grafana-operator/5.19.4/manifests/grafana-operator-operator-metrics-service_v1_service.yaml
- operators/grafana-operator/5.19.4/manifests/grafana-operator.clusterserviceversion.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanaalertrulegroups.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanacontactpoints.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanadashboards.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanadatasources.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanafolders.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanalibrarypanels.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanamutetimings.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafananotificationpolicies.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafananotificationpolicyroutes.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafananotificationtemplates.yaml
- operators/grafana-operator/5.19.4/manifests/grafana.integreatly.org_grafanas.yaml
- operators/grafana-operator/5.19.4/metadata/annotations.yaml
> operator grafana-operator (5.19.4)

- operators/dynatrace-operator/1.6.2/Dockerfile
- operators/dynatrace-operator/1.6.2/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.6.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.6.2/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.6.2/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.6.2/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.6.2/metadata/annotations.yaml
> operator dynatrace-operator (1.6.2)

- catalogs/v4.12/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.13/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.14/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.15/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.16/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.17/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.18/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.19/multi-nic-cni-operator/catalog.yaml
- catalogs/v4.20/multi-nic-cni-operator/catalog.yaml
> Catalog update [multi-nic-cni-operator] [v4.12,v4.13,v4.14,v4.15,v4.16,v4.17,v4.18,v4.19,v4.20]

- operators/project-quay/3.13.8/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.13.8/manifests/quayregistries.crd.yaml
- operators/project-quay/3.13.8/metadata/annotations.yaml
Add 3.13.8 to community operators
> operator project-quay (3.13.8)

- operators/project-quay/3.9.15/manifests/quay-operator.clusterserviceversion.yaml
- operators/project-quay/3.9.15/manifests/quayregistries.crd.yaml
- operators/project-quay/3.9.15/metadata/annotations.yaml
Add 3.9.15 to community operators
> operator project-quay (3.9.15)

- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_codeflares.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_dashboards.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_feastoperators.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_kserves.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_kueues.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_llamastackoperators.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_modelregistries.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_rays.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_trainingoperators.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_trustyais.yaml
- operators/opendatahub-operator/2.34.0/manifests/components.platform.opendatahub.io_workbenches.yaml
- operators/opendatahub-operator/2.34.0/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- operators/opendatahub-operator/2.34.0/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- operators/opendatahub-operator/2.34.0/manifests/features.opendatahub.io_featuretrackers.yaml
- operators/opendatahub-operator/2.34.0/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
- operators/opendatahub-operator/2.34.0/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
- operators/opendatahub-operator/2.34.0/manifests/opendatahub-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.34.0/manifests/opendatahub-operator.clusterserviceversion.yaml
- operators/opendatahub-operator/2.34.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/opendatahub-operator/2.34.0/manifests/prometheus-k8s-viewer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/opendatahub-operator/2.34.0/manifests/services.platform.opendatahub.io_auths.yaml
- operators/opendatahub-operator/2.34.0/manifests/services.platform.opendatahub.io_monitorings.yaml
- operators/opendatahub-operator/2.34.0/manifests/services.platform.opendatahub.io_servicemeshes.yaml
- operators/opendatahub-operator/2.34.0/metadata/annotations.yaml
- operators/opendatahub-operator/2.34.0/release-config.yaml
- operators/opendatahub-operator/2.34.0/tests/scorecard/config.yaml
> operator opendatahub-operator (2.34.0)

- operators/apicurio-registry-3/3.0.14/bundle.Dockerfile
- operators/apicurio-registry-3/3.0.14/manifests/apicurio-registry-3.clusterserviceversion.yaml
- operators/apicurio-registry-3/3.0.14/manifests/registry.apicur.io_apicurioregistries3.yaml
- operators/apicurio-registry-3/3.0.14/metadata/annotations.yaml
> operator apicurio-registry-3 (3.0.14)

- operators/infinispan/2.4.17/bundle/manifests/infinispan-operator-manager-config_v1_configmap.yaml
- operators/infinispan/2.4.17/bundle/manifests/infinispan-operator.clusterserviceversion.yaml
- operators/infinispan/2.4.17/bundle/manifests/infinispan.org_backups.yaml
- operators/infinispan/2.4.17/bundle/manifests/infinispan.org_batches.yaml
- operators/infinispan/2.4.17/bundle/manifests/infinispan.org_caches.yaml
- operators/infinispan/2.4.17/bundle/manifests/infinispan.org_infinispans.yaml
- operators/infinispan/2.4.17/bundle/manifests/infinispan.org_restores.yaml
- operators/infinispan/2.4.17/bundle/metadata/annotations.yaml
- operators/infinispan/2.4.17/bundle/tests/scorecard/config.yaml
> operator infinispan (2.4.17)

- operators/alloydb-omni-operator/catalog-templates/basic.yaml
Signed-off-by: Manvi Gupta [guptamanvi@google.com](mailto:guptamanvi@google.com)
--
> Update the catalog template for AlloyDB Omni Operator

- operators/dynatrace-operator/1.7.0/Dockerfile
- operators/dynatrace-operator/1.7.0/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.7.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.7.0/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.7.0/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.7.0/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.7.0/metadata/annotations.yaml
> operator dynatrace-operator (1.7.0)

- operators/gitlab-operator-kubernetes/2.3.2/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/2.3.2/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.3.2/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/2.3.2/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (2.3.2)

- catalogs/v4.17/alloydb-omni-operator/catalog.yaml
- catalogs/v4.18/alloydb-omni-operator/catalog.yaml
- catalogs/v4.19/alloydb-omni-operator/catalog.yaml
- catalogs/v4.20/alloydb-omni-operator/catalog.yaml
> Catalog update [alloydb-omni-operator] [v4.12,v4.13,v4.14,v4.15,v4.16,v4.17,v4.18,v4.19,v4.20]

- operators/pulp-operator/1.1.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml
- operators/pulp-operator/1.1.0/manifests/pulp-operator-manager-config_v1_configmap.yaml
- operators/pulp-operator/1.1.0/manifests/pulp-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/pulp-operator/1.1.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/pulp-operator/1.1.0/manifests/pulp-operator.clusterserviceversion.yaml
- operators/pulp-operator/1.1.0/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
- operators/pulp-operator/1.1.0/manifests/repo-manager.pulpproject.org_pulprestores.yaml
- operators/pulp-operator/1.1.0/manifests/repo-manager.pulpproject.org_pulps.yaml
- operators/pulp-operator/1.1.0/manifests/settings_v1_configmap.yaml
- operators/pulp-operator/1.1.0/metadata/annotations.yaml
- operators/pulp-operator/1.1.0/tests/scorecard/config.yaml
> operator pulp-operator (1.1.0)

- operators/visionone-containersecurity/0.0.2/manifests/container-security.trendmicro.com_visiononecontainersecurities.yaml
- operators/visionone-containersecurity/0.0.2/manifests/visionone-containersecurity-controller-manager-metrics-service_v1_service.yaml
- operators/visionone-containersecurity/0.0.2/manifests/visionone-containersecurity-crd-admin-role-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/visionone-containersecurity/0.0.2/manifests/visionone-containersecurity-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/visionone-containersecurity/0.0.2/manifests/visionone-containersecurity-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/visionone-containersecurity/0.0.2/manifests/visionone-containersecurity-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/visionone-containersecurity/0.0.2/manifests/visionone-containersecurity.clusterserviceversion.yaml
- operators/visionone-containersecurity/0.0.2/metadata/annotations.yaml
- operators/visionone-containersecurity/0.0.2/release-config.yaml
- operators/visionone-containersecurity/0.0.2/tests/scorecard/config.yaml
> operator visionone-containersecurity (0.0.2)

- operators/mariadb-operator/25.8.4/manifests/helm.mariadb.mmontes.io_mariadboperators.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_backups.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_connections.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_databases.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_externalmariadbs.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_grants.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_mariadbs.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_maxscales.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_physicalbackups.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_restores.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_sqljobs.yaml
- operators/mariadb-operator/25.8.4/manifests/k8s.mariadb.com_users.yaml
- operators/mariadb-operator/25.8.4/manifests/mariadb-operator.clusterserviceversion.yaml
- operators/mariadb-operator/25.8.4/metadata/annotations.yaml
- operators/mariadb-operator/25.8.4/tests/scorecard/config.yaml
Added operator mariadb-operator (25.8.4)
> operator mariadb-operator (25.8.4)

- operators/dynatrace-operator/1.7.1/Dockerfile
- operators/dynatrace-operator/1.7.1/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.7.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.7.1/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.7.1/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.7.1/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.7.1/metadata/annotations.yaml
> operator dynatrace-operator (1.7.1)

- operators/apicurio-registry-3/3.0.15/bundle.Dockerfile
- operators/apicurio-registry-3/3.0.15/manifests/apicurio-registry-3.clusterserviceversion.yaml
- operators/apicurio-registry-3/3.0.15/manifests/registry.apicur.io_apicurioregistries3.yaml
- operators/apicurio-registry-3/3.0.15/metadata/annotations.yaml
> operator apicurio-registry-3 (3.0.15)

- operators/tempo-operator/0.18.0/bundle.Dockerfile
- operators/tempo-operator/0.18.0/manifests/tempo-operator-controller-manager-metrics-service_v1_service.yaml
- operators/tempo-operator/0.18.0/manifests/tempo-operator-manager-config_v1_configmap.yaml
- operators/tempo-operator/0.18.0/manifests/tempo-operator-manager-rolebinding-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/tempo-operator/0.18.0/manifests/tempo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/tempo-operator/0.18.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operators/tempo-operator/0.18.0/manifests/tempo-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operators/tempo-operator/0.18.0/manifests/tempo-operator-webhook-service_v1_service.yaml
- operators/tempo-operator/0.18.0/manifests/tempo-operator.clusterserviceversion.yaml
- operators/tempo-operator/0.18.0/manifests/tempo.grafana.com_tempomonolithics.yaml
- operators/tempo-operator/0.18.0/manifests/tempo.grafana.com_tempostacks.yaml
- operators/tempo-operator/0.18.0/metadata/annotations.yaml
- operators/tempo-operator/0.18.0/tests/scorecard/config.yaml
Release tempo-operator `0.18.0`.
> operator tempo-operator (0.18.0)

- operators/mongodb-atlas-kubernetes/2.11.0/bundle.Dockerfile
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasbackupcompliancepolicies.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlascustomroles.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasdatafederations.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasdeployments.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasfederatedauths.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasipaccesslists.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasnetworkcontainers.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasnetworkpeerings.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasorgsettings.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasprivateendpoints.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasprojects.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlassearchindexconfigs.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasstreamconnections.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasstreaminstances.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasteams.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/atlas.mongodb.com_atlasthirdpartyintegrations.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/metadata/annotations.yaml
- operators/mongodb-atlas-kubernetes/2.11.0/tests/scorecard/config.yaml
> operator mongodb-atlas-kubernetes (2.11.0)

- operators/dynatrace-operator/1.6.3/Dockerfile
- operators/dynatrace-operator/1.6.3/manifests/dynatrace-operator.clusterserviceversion.yaml
- operators/dynatrace-operator/1.6.3/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml
- operators/dynatrace-operator/1.6.3/manifests/dynatrace-webhook_v1_service.yaml
- operators/dynatrace-operator/1.6.3/manifests/dynatrace.com_dynakubes.yaml
- operators/dynatrace-operator/1.6.3/manifests/dynatrace.com_edgeconnects.yaml
- operators/dynatrace-operator/1.6.3/metadata/annotations.yaml
> operator dynatrace-operator (1.6.3)

- operators/gitlab-operator-kubernetes/2.4.1/manifests/apps.gitlab.com_gitlabs.yaml
- operators/gitlab-operator-kubernetes/2.4.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.4.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.4.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml
- operators/gitlab-operator-kubernetes/2.4.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/gitlab-operator-kubernetes/2.4.1/manifests/gitlab-prometheus-server_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operators/gitlab-operator-kubernetes/2.4.1/manifests/gitlab-prometheus-server_v1_serviceaccount.yaml
- operators/gitlab-operator-kubernetes/2.4.1/manifests/gitlab-webhook-service_v1_service.yaml
- operators/gitlab-operator-kubernetes/2.4.1/metadata/annotations.yaml
- operators/gitlab-operator-kubernetes/2.4.1/tests/scorecard/config.yaml
> operator gitlab-operator-kubernetes (2.4.1)

- operators/flux-operator/0.30.0/manifests/flux-operator.clusterserviceversion.yaml
- operators/flux-operator/0.30.0/manifests/flux-operator.service.yaml
- operators/flux-operator/0.30.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.30.0/manifests/fluxreports.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.30.0/manifests/resourcesetinputproviders.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.30.0/manifests/resourcesets.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.30.0/metadata/annotations.yaml
- operators/flux-operator/0.30.0/tests/scorecard/config.yaml
Part of: https://github.com/controlplaneio-fluxcd/distribution/issues/245
> operator flux-operator (0.30.0)

- operators/clusterpulse/0.1.0/manifests/charts.clusterpulse.io_clusterpulses.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse-clusterpulse-admin-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse-clusterpulse-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse-clusterpulse-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse-controller-manager-metrics-service_v1_service.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse.clusterserviceversion.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse.io_clusterconnections.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse.io_monitoraccesspolicies.yaml
- operators/clusterpulse/0.1.0/manifests/clusterpulse.io_registryconnections.yaml
- operators/clusterpulse/0.1.0/metadata/annotations.yaml
- operators/clusterpulse/0.1.0/release-config.yaml
- operators/clusterpulse/0.1.0/tests/scorecard/config.yaml
- operators/clusterpulse/Makefile
- operators/clusterpulse/catalog-templates/basic.yaml
- operators/clusterpulse/ci.yaml
> operator clusterpulse (0.1.0)

- operators/flux-operator/0.31.0/manifests/flux-operator.clusterserviceversion.yaml
- operators/flux-operator/0.31.0/manifests/flux-operator.service.yaml
- operators/flux-operator/0.31.0/manifests/fluxinstances.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.31.0/manifests/fluxreports.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.31.0/manifests/resourcesetinputproviders.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.31.0/manifests/resourcesets.fluxcd.controlplane.io.crd.yaml
- operators/flux-operator/0.31.0/metadata/annotations.yaml
- operators/flux-operator/0.31.0/tests/scorecard/config.yaml
> operator flux-operator (0.31.0)
