operators/strimzi-kafka-operator/0.20.0/strimzi-cluster-operator.v0.20.0.clusterserviceversion.yaml, operators/strimzi-kafka-operator/ci.yaml
=> operators [O] [CI] strimzi-kafka-operator (0.20.0)

operators/strimzi-kafka-operator/0.20.1/strimzi-cluster-operator.v0.20.1.clusterserviceversion.yaml, operators/strimzi-kafka-operator/ci.yaml
=> operators [CI] strimzi-kafka-operator (0.20.1)

README.md
=> doc: fix broken link in the README

operators/pulp-operator/0.3.0/bundle.Dockerfile, operators/pulp-operator/0.3.0/manifests/pulp-operator.v0.3.0.clusterserviceversion.yaml, operators/pulp-operator/0.3.0/manifests/pulp.pulpproject.org_pulpbackups_crd.yaml, operators/pulp-operator/0.3.0/manifests/pulp.pulpproject.org_pulprestores_crd.yaml, operators/pulp-operator/0.3.0/manifests/pulp.pulpproject.org_pulps_crd.yaml, operators/pulp-operator/0.3.0/metadata/annotations.yaml, operators/pulp-operator/ci.yaml
https://pulpproject.org/
https://pulp-operator.readthedocs.io/en/latest/
--
=> operators [N] [CI] pulp-operator (0.3.0)

operators/grafana-operator/3.10.3/grafana-operator.v3.10.3.clusterserviceversion.yaml, operators/grafana-operator/3.10.3/grafanadashboards.integreatly.org.crd.yaml, operators/grafana-operator/3.10.3/grafanadatasources.integreatly.org.crd.yaml, operators/grafana-operator/3.10.3/grafanas.integreatly.org.crd.yaml, operators/grafana-operator/grafana-operator.package.yaml
Signed-off-by: Peter Braun <pbraun@redhat.com>
=> operators grafana-operator (3.10.3)

operators/multicluster-operators-subscription/0.3.0/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.0/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.0/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.0/apps.open-cluster-management.io_gitopsclusters_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.0/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.0/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.0/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.0/multicluster-operators-subscription.v0.3.0.clusterserviceversion.yaml, operators/multicluster-operators-subscription/ci.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators [CI] multicluster-operators-subscription (0.3.0)

.github/workflows/operator_release.yaml, ci/pipeline-config.yaml
=> activate signature

.github/workflows/operator_release.yaml
=> signature 

operators/klusterlet/0.4.0/klusterlet.v0.4.0.clusterserviceversion.yaml, operators/klusterlet/0.4.0/operator.open-cluster-management.io_klusterlets.yaml, operators/klusterlet/ci.yaml, operators/klusterlet/klusterlet.package.yaml
=> operators [CI] klusterlet (0.4.0)

operators/cluster-manager/0.4.0/cluster-manager.v0.4.0.clusterserviceversion.yaml, operators/cluster-manager/0.4.0/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/ci.yaml, operators/cluster-manager/cluster-manger.package.yaml
=> operators [CI] cluster-manager (0.4.0)

operators/oadp-operator/0.2.5/manifests/backup.crd.yaml, operators/oadp-operator/0.2.5/manifests/backupstoragelocation.crd.yaml, operators/oadp-operator/0.2.5/manifests/deletebackuprequest.crd.yaml, operators/oadp-operator/0.2.5/manifests/downloadrequest.crd.yaml, operators/oadp-operator/0.2.5/manifests/oadp-operator.v0.2.5.clusterserviceversion.yaml, operators/oadp-operator/0.2.5/manifests/podvolumebackup.crd.yaml, operators/oadp-operator/0.2.5/manifests/podvolumerestore.crd.yaml, operators/oadp-operator/0.2.5/manifests/resticrepository.crd.yaml, operators/oadp-operator/0.2.5/manifests/restore.crd.yaml, operators/oadp-operator/0.2.5/manifests/schedule.crd.yaml, operators/oadp-operator/0.2.5/manifests/serverstatusrequest.crd.yaml, operators/oadp-operator/0.2.5/manifests/velero.crd.yaml, operators/oadp-operator/0.2.5/manifests/volumesnapshotlocation.crd.yaml, operators/oadp-operator/0.2.5/metadata/annotations.yaml
=> operators oadp-operator (0.2.5)

.github/workflows/operator_ci.yaml, .github/workflows/operator_release.yaml, ci/pipeline-config.yaml
automerge disabled due to issue with final architecture
=> automerge disabled

operators/special-resource-operator/4.8.0/Dockerfile, operators/special-resource-operator/4.8.0/manifests/special-resource-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/special-resource-operator/4.8.0/manifests/special-resource-controller-manager-metrics-service_v1_service.yaml, operators/special-resource-operator/4.8.0/manifests/special-resource-dependencies_v1_configmap.yaml, operators/special-resource-operator/4.8.0/manifests/special-resource-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/special-resource-operator/4.8.0/manifests/special-resource-operator.clusterserviceversion.yaml, operators/special-resource-operator/4.8.0/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/special-resource-operator/4.8.0/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/special-resource-operator/4.8.0/manifests/sro.openshift.io_specialresources.yaml, operators/special-resource-operator/4.8.0/metadata/annotations.yaml, operators/special-resource-operator/4.8.0/tests/scorecard/config.yaml
Signed-off-by: David Gray <dagray@redhat.com>
=> operators special-resource-operator (4.8.0)

.github/workflows/operator_ci.yaml, .github/workflows/operator_release.yaml, ci/pipeline-config.yaml
automerge enable
add signatures
monitoring
=> automerge enable

operators/crane-operator/1.4.6/manifests/backup.crd.yaml, operators/crane-operator/1.4.6/manifests/backupstoragelocation.crd.yaml, operators/crane-operator/1.4.6/manifests/crane-operator.v1.4.6.clusterserviceversion.yaml, operators/crane-operator/1.4.6/manifests/deletebackuprequest.crd.yaml, operators/crane-operator/1.4.6/manifests/downloadrequest.crd.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_directimagemigrations.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_directimagestreammigrations.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_directvolumemigrations.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_miganalytics.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_migclusters.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_mighooks.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_migmigrations.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_migplans.yaml, operators/crane-operator/1.4.6/manifests/migration.openshift.io_migstorages.yaml, operators/crane-operator/1.4.6/manifests/migrationcontroller.crd.yaml, operators/crane-operator/1.4.6/manifests/podvolumebackup.crd.yaml, operators/crane-operator/1.4.6/manifests/podvolumerestore.crd.yaml, operators/crane-operator/1.4.6/manifests/resticrepository.crd.yaml, operators/crane-operator/1.4.6/manifests/restore.crd.yaml, operators/crane-operator/1.4.6/manifests/schedule.crd.yaml, operators/crane-operator/1.4.6/manifests/serverstatusrequest.crd.yaml, operators/crane-operator/1.4.6/manifests/volumesnapshotlocation.crd.yaml, operators/crane-operator/1.4.6/metadata/annotations.yaml
=> operators crane-operator (1.4.6)

operators/eclipse-che/7.33.2/checlusters.org.eclipse.che.crd.yaml, operators/eclipse-che/7.33.2/eclipse-che.v7.33.2.clusterserviceversion.yaml, operators/eclipse-che/7.33.2/org.eclipse.che_chebackupserverconfigurations_crd.yaml, operators/eclipse-che/7.33.2/org.eclipse.che_checlusterbackups_crd.yaml, operators/eclipse-che/7.33.2/org.eclipse.che_checlusterrestores_crd.yaml, operators/eclipse-che/eclipse-che.package.yaml
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
--
=> operators eclipse-che (7.33.2)

operators/oadp-operator/0.2.6/manifests/backup.crd.yaml, operators/oadp-operator/0.2.6/manifests/backupstoragelocation.crd.yaml, operators/oadp-operator/0.2.6/manifests/deletebackuprequest.crd.yaml, operators/oadp-operator/0.2.6/manifests/downloadrequest.crd.yaml, operators/oadp-operator/0.2.6/manifests/oadp-operator.v0.2.6.clusterserviceversion.yaml, operators/oadp-operator/0.2.6/manifests/podvolumebackup.crd.yaml, operators/oadp-operator/0.2.6/manifests/podvolumerestore.crd.yaml, operators/oadp-operator/0.2.6/manifests/resticrepository.crd.yaml, operators/oadp-operator/0.2.6/manifests/restore.crd.yaml, operators/oadp-operator/0.2.6/manifests/schedule.crd.yaml, operators/oadp-operator/0.2.6/manifests/serverstatusrequest.crd.yaml, operators/oadp-operator/0.2.6/manifests/velero.crd.yaml, operators/oadp-operator/0.2.6/manifests/volumesnapshotlocation.crd.yaml, operators/oadp-operator/0.2.6/metadata/annotations.yaml
=> operators oadp-operator (0.2.6)

.github/workflows/operator_release.yaml
=> signature migrated

operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.17.1/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.17.1/victoriametrics-operator.0.17.1.clusterserviceversion.yaml, operators/victoriametrics-operator/0.17.1/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/victoriametrics-operator/0.17.1/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/victoriametrics-operator/0.17.1/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.17.1)

operators/crane-operator/1.5.0/manifests/backup.crd.yaml, operators/crane-operator/1.5.0/manifests/backupstoragelocation.crd.yaml, operators/crane-operator/1.5.0/manifests/crane-operator.v1.5.0.clusterserviceversion.yaml, operators/crane-operator/1.5.0/manifests/deletebackuprequest.crd.yaml, operators/crane-operator/1.5.0/manifests/downloadrequest.crd.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_directimagemigrations.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_directimagestreammigrations.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_directvolumemigrations.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_miganalytics.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_migclusters.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_mighooks.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_migmigrations.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_migplans.yaml, operators/crane-operator/1.5.0/manifests/migration.openshift.io_migstorages.yaml, operators/crane-operator/1.5.0/manifests/migrationcontroller.crd.yaml, operators/crane-operator/1.5.0/manifests/podvolumebackup.crd.yaml, operators/crane-operator/1.5.0/manifests/podvolumerestore.crd.yaml, operators/crane-operator/1.5.0/manifests/resticrepository.crd.yaml, operators/crane-operator/1.5.0/manifests/restore.crd.yaml, operators/crane-operator/1.5.0/manifests/schedule.crd.yaml, operators/crane-operator/1.5.0/manifests/serverstatusrequest.crd.yaml, operators/crane-operator/1.5.0/manifests/volumesnapshotlocation.crd.yaml, operators/crane-operator/1.5.0/metadata/annotations.yaml
=> operators crane-operator (1.5.0)

operators/openebs/2.10.0/openebs_v1alpha1_openebsinstalltemplate_crd.yaml, operators/openebs/2.10.0/openebsoperator.v2.10.0.clusterserviceversion.yaml, operators/openebs/openebs.package.yaml
=> operators openebs (2.10.0)

operators/community-kubevirt-hyperconverged/ci.yaml
Signed-off-by: orenc1 <ocohen@redhat.com>
--
=> Add hco-bot to HCO (kubevirt) authorized authors

operators/koku-metrics-operator/0.9.8/Dockerfile, operators/koku-metrics-operator/0.9.8/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/0.9.8/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/0.9.8/metadata/annotations.yaml
Signed-off-by: Ashley Aiken <aaiken@redhat.com>
--
=> operators koku-metrics-operator (0.9.8)

operators/multicluster-operators-subscription/0.3.1/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.1/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.1/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.1/apps.open-cluster-management.io_gitopsclusters_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.1/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.1/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.1/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.1/multicluster-operators-subscription.v0.3.1.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators multicluster-operators-subscription (0.3.1)

operators/pcc-operator/0.0.1/bundle.Dockerfile, operators/pcc-operator/0.0.1/manifests/consoledefenders.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.0.1/manifests/consoles.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.0.1/manifests/defenders.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.0.1/manifests/pcc-operator-controller-manager-metrics-service.service.yaml, operators/pcc-operator/0.0.1/manifests/pcc-operator-controller-manager.serviceaccount.yaml, operators/pcc-operator/0.0.1/manifests/pcc-operator-metrics-reader.clusterrole.yaml, operators/pcc-operator/0.0.1/manifests/pcc-operator.v0.0.1.clusterserviceversion.yaml, operators/pcc-operator/0.0.1/metadata/annotations.yaml, operators/pcc-operator/0.0.1/tests/scorecard/config.yaml, operators/pcc-operator/ci.yaml
Signed-off-by: Wyatt Gill <wgill@paloaltonetworks.com>
--
=> operators [N] [CI] pcc-operator (0.0.1)

README.md
=> documentation default path

operators/openshift-nfd-operator/4.5.0/nfd.v4.5.0.clusterserviceversion.yaml, operators/openshift-nfd-operator/4.6.0/nfd.v4.6.0.clusterserviceversion.yaml, operators/openshift-nfd-operator/4.7.0/nfd.v4.7.0.clusterserviceversion.yaml
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
--
=> operators [R] openshift-nfd-operator (4.5.0 4.6.0 4.7.0)

operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.17.2/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.17.2/victoriametrics-operator.0.17.2.clusterserviceversion.yaml, operators/victoriametrics-operator/0.17.2/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/victoriametrics-operator/0.17.2/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/victoriametrics-operator/0.17.2/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.17.2)

operators/infinispan/2.1.5/infinispan-operator.v2.1.5.clusterserviceversion.yaml, operators/infinispan/2.1.5/infinispan.org_backups_crd.yaml, operators/infinispan/2.1.5/infinispan.org_batches_crd.yaml, operators/infinispan/2.1.5/infinispan.org_caches_crd.yaml, operators/infinispan/2.1.5/infinispan.org_infinispans_crd.yaml, operators/infinispan/2.1.5/infinispan.org_restores_crd.yaml, operators/infinispan/ci.yaml, operators/infinispan/infinispan.package.yaml
Signed-off-by: Vittorio Rigamonti <vrigamon@redhat.com>
--
=> operators [CI] infinispan (2.1.5)

operators/portworx-essentials/1.5.0/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.5.0/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operators portworx-essentials (1.5.0)

operators/tagger/2.1.17/Containerfile, operators/tagger/2.1.17/manifests/docker-webhooks_v1_service.yaml, operators/tagger/2.1.17/manifests/metrics_v1_service.yaml, operators/tagger/2.1.17/manifests/mirror-registry-config_v1_secret.yaml, operators/tagger/2.1.17/manifests/mutating-webhooks_v1_service.yaml, operators/tagger/2.1.17/manifests/quay-webhooks_v1_service.yaml, operators/tagger/2.1.17/manifests/tagger.clusterserviceversion.yaml, operators/tagger/2.1.17/manifests/tagger.dev_tags.yaml, operators/tagger/2.1.17/manifests/tagger_v1_serviceaccount.yaml, operators/tagger/2.1.17/manifests/tagio-external_v1_service.yaml, operators/tagger/2.1.17/manifests/tagio_v1_service.yaml, operators/tagger/2.1.17/metadata/annotations.yaml, operators/tagger/ci.yaml
=> operators [N] [CI] tagger (2.1.17)

operators/portworx-essentials/ci.yaml
=> operators [CI] portworx-essentials

operators/snapscheduler/2.0.0/bundle.Dockerfile, operators/snapscheduler/2.0.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml, operators/snapscheduler/2.0.0/manifests/snapscheduler-controller-manager_v1_serviceaccount.yaml, operators/snapscheduler/2.0.0/manifests/snapscheduler-manager-config_v1_configmap.yaml, operators/snapscheduler/2.0.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/snapscheduler/2.0.0/manifests/snapscheduler.backube_snapshotschedules.yaml, operators/snapscheduler/2.0.0/manifests/snapscheduler.clusterserviceversion.yaml, operators/snapscheduler/2.0.0/metadata/annotations.yaml, operators/snapscheduler/2.0.0/tests/scorecard/config.yaml
=> operators snapscheduler (2.0.0)

operators/keda/2.4.0/manifests/keda-olm-operator_v1_serviceaccount.yaml, operators/keda/2.4.0/manifests/keda.sh_clustertriggerauthentications.yaml, operators/keda/2.4.0/manifests/keda.sh_kedacontrollers.yaml, operators/keda/2.4.0/manifests/keda.sh_scaledjobs.yaml, operators/keda/2.4.0/manifests/keda.sh_scaledobjects.yaml, operators/keda/2.4.0/manifests/keda.sh_triggerauthentications.yaml, operators/keda/2.4.0/manifests/keda.v2.4.0.clusterserviceversion.yaml, operators/keda/2.4.0/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
=> operators keda (2.4.0)

operators/flux/0.16.2/manifests/alert.crd.yaml, operators/flux/0.16.2/manifests/bucket.crd.yaml, operators/flux/0.16.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.16.2/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.16.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.16.2/manifests/flux.v0.16.2.clusterserviceversion.yaml, operators/flux/0.16.2/manifests/gitrepository.crd.yaml, operators/flux/0.16.2/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.16.2/manifests/helmchart.crd.yaml, operators/flux/0.16.2/manifests/helmrelease.crd.yaml, operators/flux/0.16.2/manifests/helmrepository.crd.yaml, operators/flux/0.16.2/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.16.2/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.16.2/manifests/imagepolicy.crd.yaml, operators/flux/0.16.2/manifests/imagerepository.crd.yaml, operators/flux/0.16.2/manifests/imageupdateautomation.crd.yaml, operators/flux/0.16.2/manifests/kustomization.crd.yaml, operators/flux/0.16.2/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.16.2/manifests/notification-controller.service.yaml, operators/flux/0.16.2/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.16.2/manifests/provider.crd.yaml, operators/flux/0.16.2/manifests/receiver.crd.yaml, operators/flux/0.16.2/manifests/source-controller.service.yaml, operators/flux/0.16.2/manifests/source-controller.serviceaccount.yaml, operators/flux/0.16.2/manifests/webhook-receiver.service.yaml, operators/flux/0.16.2/metadata/annotations.yaml
=> operators flux (0.16.2)

operators/mta-operator/ci.yaml
=> operators [CI] mta-operator

operators/kubernetes-imagepuller-operator/0.0.8/che.eclipse.org_kubernetesimagepullers_crd.yaml, operators/kubernetes-imagepuller-operator/0.0.8/kubernetes-imagepuller-operator.v0.0.8.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
--
=> operators kubernetes-imagepuller-operator (0.0.8)

operators/special-resource-operator/4.8.0/manifests/special-resource-operator.clusterserviceversion.yaml, operators/special-resource-operator/4.8.0/manifests/sro.openshift.io_specialresources.yaml
=> operators [O] special-resource-operator (4.8.0)

operators/kiali/1.38.1/bundle.Dockerfile, operators/kiali/1.38.1/manifests/kiali.crd.yaml, operators/kiali/1.38.1/manifests/kiali.v1.38.1.clusterserviceversion.yaml, operators/kiali/1.38.1/metadata/annotations.yaml
=> operators kiali (1.38.1)

operators/mta-operator/0.0.6/Dockerfile, operators/mta-operator/0.0.6/manifests/windup-operator.v0.0.6.clusterserviceversion.yaml, operators/mta-operator/0.0.6/manifests/windup.crd.yaml, operators/mta-operator/0.0.6/metadata/annotations.yaml
=> operators mta-operator (0.0.6)

operators/keycloak-operator/15.0.0/bundle.Dockerfile, operators/keycloak-operator/15.0.0/manifests/keycloak-operator.v15.0.0.clusterserviceversion.yaml, operators/keycloak-operator/15.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.0/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.0/metadata/annotations.yaml
Signed-off-by: Václav Muzikář <vmuzikar@redhat.com>
--
=> operators keycloak-operator (15.0.0)

operators/keycloak-operator/15.0.1/bundle.Dockerfile, operators/keycloak-operator/15.0.1/manifests/keycloak-operator.v15.0.1.clusterserviceversion.yaml, operators/keycloak-operator/15.0.1/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.1/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.1/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.1/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.1/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.1/metadata/annotations.yaml
Signed-off-by: Václav Muzikář <vmuzikar@redhat.com>
--
=> operators keycloak-operator (15.0.1)

operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-controller-manager-metrics-service_v1_service.yaml, operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-controller-manager_v1_serviceaccount.yaml, operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-machine-deletion-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-manager-config_v1_configmap.yaml, operators/machine-deletion-operator/0.0.1/manifests/machine-deletion-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/machine-deletion-operator/0.0.1/manifests/machine-deletion.clusterserviceversion.yaml, operators/machine-deletion-operator/0.0.1/manifests/machine-deletion.medik8s.io_machinedeletions.yaml, operators/machine-deletion-operator/0.0.1/manifests/machine-deletion.medik8s.io_machinedeletiontemplates.yaml, operators/machine-deletion-operator/0.0.1/metadata/annotations.yaml
Signed-off-by: Michael Shitrit <mshitrit@redhat.com>
--
=> operators [N] machine-deletion-operator (0.0.1)

operators/community-windows-machine-config-operator/3.0.0/manifests/community-windows-machine-config-operator.3.0.0.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/3.0.0/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/3.0.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/3.0.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/3.0.0/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/3.0.0/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/3.0.0/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/3.0.0/metadata/annotations.yaml
Signed-off-by: Sebastian Soto <ssoto@redhat.com>
--
=> operators community-windows-machine-config-operator (3.0.0)

operators/ember-csi-community-operator/0.9.5/ember-csi-operator.crd.yaml, operators/ember-csi-community-operator/0.9.5/ember-csi-operator.v0.9.5.clusterserviceversion.yaml, operators/ember-csi-community-operator/ember-csi-community-operator.package.yaml
=> operators ember-csi-community-operator (0.9.5)

operators/mongodb-atlas-kubernetes/0.6.1/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/0.6.1/manifests/atlas.mongodb.com_atlasclusters.yaml, operators/mongodb-atlas-kubernetes/0.6.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/0.6.1/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/0.6.1/manifests/mongodb-atlas-operator_v1_serviceaccount.yaml, operators/mongodb-atlas-kubernetes/0.6.1/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/0.6.1/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
=> operators mongodb-atlas-kubernetes (0.6.1)

operators/hazelcast-operator/0.3.7/hazelcast-operator.v0.3.7.clusterserviceversion.yaml, operators/hazelcast-operator/0.3.7/hazelcasts.hazelcast.com.crd.yaml, operators/hazelcast-operator/hazelcast-operator.package.yaml
Signed-off-by: devOpsHelm <devopshelm@hazelcast.com>
=> operators hazelcast-operator (0.3.7)

operators/namespace-configuration-operator/1.1.0/Dockerfile, operators/namespace-configuration-operator/1.1.0/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.1.0/manifests/namespace-configuration-operator-controller-manager-metrics_v1_service.yaml, operators/namespace-configuration-operator/1.1.0/manifests/namespace-configuration-operator-controller-manager_v1_serviceaccount.yaml, operators/namespace-configuration-operator/1.1.0/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.1.0/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.1.0/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.1.0/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.1.0/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.1.0/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.1.0/metadata/annotations.yaml, operators/namespace-configuration-operator/1.1.0/tests/scorecard/config.yaml
=> operators namespace-configuration-operator (1.1.0)

operators/egressip-ipam-operator/1.1.0/Dockerfile, operators/egressip-ipam-operator/1.1.0/manifests/egressip-ipam-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/egressip-ipam-operator/1.1.0/manifests/egressip-ipam-operator-controller-manager-metrics_v1_service.yaml, operators/egressip-ipam-operator/1.1.0/manifests/egressip-ipam-operator-controller-manager_v1_serviceaccount.yaml, operators/egressip-ipam-operator/1.1.0/manifests/egressip-ipam-operator-manager-config_v1_configmap.yaml, operators/egressip-ipam-operator/1.1.0/manifests/egressip-ipam-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/egressip-ipam-operator/1.1.0/manifests/egressip-ipam-operator.clusterserviceversion.yaml, operators/egressip-ipam-operator/1.1.0/manifests/redhatcop.redhat.io_egressipams.yaml, operators/egressip-ipam-operator/1.1.0/metadata/annotations.yaml, operators/egressip-ipam-operator/1.1.0/tests/scorecard/config.yaml
=> operators egressip-ipam-operator (1.1.0)

operators/resource-locker-operator/1.0.9/Dockerfile, operators/resource-locker-operator/1.0.9/manifests/redhatcop.redhat.io_resourcelockers.yaml, operators/resource-locker-operator/1.0.9/manifests/resource-locker-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/resource-locker-operator/1.0.9/manifests/resource-locker-operator-controller-manager-metrics_v1_service.yaml, operators/resource-locker-operator/1.0.9/manifests/resource-locker-operator-controller-manager_v1_serviceaccount.yaml, operators/resource-locker-operator/1.0.9/manifests/resource-locker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/resource-locker-operator/1.0.9/manifests/resource-locker-operator.clusterserviceversion.yaml, operators/resource-locker-operator/1.0.9/metadata/annotations.yaml, operators/resource-locker-operator/1.0.9/tests/scorecard/config.yaml
=> operators resource-locker-operator (1.0.9)

operators/cert-utils-operator/1.1.0/Dockerfile, operators/cert-utils-operator/1.1.0/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.1.0/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.1.0/manifests/cert-utils-operator-controller-manager_v1_serviceaccount.yaml, operators/cert-utils-operator/1.1.0/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.1.0/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.1.0/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.1.0/metadata/annotations.yaml, operators/cert-utils-operator/1.1.0/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.1.0)

operators/koku-metrics-operator/0.9.8/manifests/koku-metrics-operator.clusterserviceversion.yaml
=> operators [O] koku-metrics-operator (0.9.8)

operators/neuvector-community-operator/1.2.7/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.2.7/neuvector-operator.v1.2.7.clusterserviceversion.yaml, operators/neuvector-community-operator/ci.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
Signed-off-by: neuvector <sthangaraj@neuvector.com>
--
=> operators [CI] neuvector-community-operator (1.2.7)

operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-controller-manager_v1_serviceaccount.yaml, operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.33.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.33.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.33.0/metadata/annotations.yaml
=> operators opentelemetry-operator (0.33.0)

operators/kiali/1.39.0/bundle.Dockerfile, operators/kiali/1.39.0/manifests/kiali.crd.yaml, operators/kiali/1.39.0/manifests/kiali.v1.39.0.clusterserviceversion.yaml, operators/kiali/1.39.0/metadata/annotations.yaml
=> operators kiali (1.39.0)

operators/ember-csi-community-operator/0.9.6/ember-csi-operator.crd.yaml, operators/ember-csi-community-operator/0.9.6/ember-csi-operator.v0.9.6.clusterserviceversion.yaml, operators/ember-csi-community-operator/ember-csi-community-operator.package.yaml
=> operators ember-csi-community-operator (0.9.6)

operators/hive-operator/ci.yaml
Sync with current team members.
=> operators [CI] hive-operator

operators/keycloak-operator/15.0.2/bundle.Dockerfile, operators/keycloak-operator/15.0.2/manifests/keycloak-operator.v15.0.2.clusterserviceversion.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/15.0.2/metadata/annotations.yaml
Signed-off-by: Jonathan Vila <jvilalop@redhat.com>
--
=> Upgrade operator keycloak-operator (15.0.2)

operators/cluster-impairment-operator/1.0.1/manifests/apps.redhat.com_clusterimpairments.yaml, operators/cluster-impairment-operator/1.0.1/manifests/cluster-impairment-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-impairment-operator/1.0.1/manifests/cluster-impairment-operator-manager-config_v1_configmap.yaml, operators/cluster-impairment-operator/1.0.1/manifests/cluster-impairment-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-impairment-operator/1.0.1/manifests/cluster-impairment-operator.clusterserviceversion.yaml, operators/cluster-impairment-operator/1.0.1/manifests/network-access-sa_v1_serviceaccount.yaml, operators/cluster-impairment-operator/1.0.1/metadata/annotations.yaml, operators/cluster-impairment-operator/1.0.1/tests/scorecard/config.yaml, operators/cluster-impairment-operator/ci.yaml
Signed-off-by: Jared O'Connell <joconnel@redhat.com>
--
=> operators [N] [CI] cluster-impairment-operator (1.0.1)

operators/pcc-operator/0.1.0/bundle.Dockerfile, operators/pcc-operator/0.1.0/manifests/consoledefenders.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.1.0/manifests/consoles.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.1.0/manifests/defenders.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.1.0/manifests/pcc-operator.v0.1.0.clusterserviceversion.yaml, operators/pcc-operator/0.1.0/metadata/annotations.yaml, operators/pcc-operator/0.1.0/tests/scorecard/config.yaml
Signed-off-by: Wyatt Gill <wgill@paloaltonetworks.com>
--
=> operators pcc-operator (0.1.0)

operators/cluster-impairment-operator/1.0.2/manifests/apps.redhat.com_clusterimpairments.yaml, operators/cluster-impairment-operator/1.0.2/manifests/cluster-impairment-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-impairment-operator/1.0.2/manifests/cluster-impairment-operator-manager-config_v1_configmap.yaml, operators/cluster-impairment-operator/1.0.2/manifests/cluster-impairment-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-impairment-operator/1.0.2/manifests/cluster-impairment-operator.clusterserviceversion.yaml, operators/cluster-impairment-operator/1.0.2/manifests/network-access-sa_v1_serviceaccount.yaml, operators/cluster-impairment-operator/1.0.2/metadata/annotations.yaml, operators/cluster-impairment-operator/1.0.2/tests/scorecard/config.yaml
Attempt to fix namespace bug
Signed-off-by: Jared O'Connell <joconnel@redhat.com>
--
=> operators cluster-impairment-operator (1.0.2)

operators/sap-commerce-operator/0.0.3/bundle.Dockerfile, operators/sap-commerce-operator/0.0.3/manifests/hybris.hybris.org_hybrisapps.yaml, operators/sap-commerce-operator/0.0.3/manifests/hybris.hybris.org_hybrisbases.yaml, operators/sap-commerce-operator/0.0.3/manifests/sap-commerce-operator-hybris-controller-manager-metrics-service_v1_service.yaml, operators/sap-commerce-operator/0.0.3/manifests/sap-commerce-operator-manager-config_v1_configmap.yaml, operators/sap-commerce-operator/0.0.3/manifests/sap-commerce-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-commerce-operator/0.0.3/manifests/sap-commerce-operator.clusterserviceversion.yaml, operators/sap-commerce-operator/0.0.3/metadata/annotations.yaml
Signed-off-by: Marco Yeung <myeung@redhat.com>
--
=> operators sap-commerce-operator (0.0.3)

operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.18.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.18.0/victoriametrics-operator.0.18.0.clusterserviceversion.yaml, operators/victoriametrics-operator/0.18.0/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/victoriametrics-operator/0.18.0/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/victoriametrics-operator/0.18.0/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.18.0)

operators/resource-locker-operator/1.1.0/Dockerfile, operators/resource-locker-operator/1.1.0/manifests/redhatcop.redhat.io_resourcelockers.yaml, operators/resource-locker-operator/1.1.0/manifests/resource-locker-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/resource-locker-operator/1.1.0/manifests/resource-locker-operator-controller-manager-metrics_v1_service.yaml, operators/resource-locker-operator/1.1.0/manifests/resource-locker-operator-controller-manager_v1_serviceaccount.yaml, operators/resource-locker-operator/1.1.0/manifests/resource-locker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/resource-locker-operator/1.1.0/manifests/resource-locker-operator.clusterserviceversion.yaml, operators/resource-locker-operator/1.1.0/metadata/annotations.yaml, operators/resource-locker-operator/1.1.0/tests/scorecard/config.yaml
=> operators resource-locker-operator (1.1.0)

operators/namespace-configuration-operator/1.2.0/Dockerfile, operators/namespace-configuration-operator/1.2.0/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.2.0/manifests/namespace-configuration-operator-controller-manager-metrics_v1_service.yaml, operators/namespace-configuration-operator/1.2.0/manifests/namespace-configuration-operator-controller-manager_v1_serviceaccount.yaml, operators/namespace-configuration-operator/1.2.0/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.2.0/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.2.0/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.2.0/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.2.0/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.2.0/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.2.0/metadata/annotations.yaml, operators/namespace-configuration-operator/1.2.0/tests/scorecard/config.yaml
=> operators namespace-configuration-operator (1.2.0)

operators/egressip-ipam-operator/1.2.0/Dockerfile, operators/egressip-ipam-operator/1.2.0/manifests/egressip-ipam-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/egressip-ipam-operator/1.2.0/manifests/egressip-ipam-operator-controller-manager-metrics_v1_service.yaml, operators/egressip-ipam-operator/1.2.0/manifests/egressip-ipam-operator-controller-manager_v1_serviceaccount.yaml, operators/egressip-ipam-operator/1.2.0/manifests/egressip-ipam-operator-manager-config_v1_configmap.yaml, operators/egressip-ipam-operator/1.2.0/manifests/egressip-ipam-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/egressip-ipam-operator/1.2.0/manifests/egressip-ipam-operator.clusterserviceversion.yaml, operators/egressip-ipam-operator/1.2.0/manifests/redhatcop.redhat.io_egressipams.yaml, operators/egressip-ipam-operator/1.2.0/metadata/annotations.yaml, operators/egressip-ipam-operator/1.2.0/tests/scorecard/config.yaml
=> operators egressip-ipam-operator (1.2.0)

operators/volume-expander-operator/0.3.0/Dockerfile, operators/volume-expander-operator/0.3.0/manifests/volume-expander-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/volume-expander-operator/0.3.0/manifests/volume-expander-operator-controller-manager-metrics_v1_service.yaml, operators/volume-expander-operator/0.3.0/manifests/volume-expander-operator-controller-manager_v1_serviceaccount.yaml, operators/volume-expander-operator/0.3.0/manifests/volume-expander-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/volume-expander-operator/0.3.0/manifests/volume-expander-operator.clusterserviceversion.yaml, operators/volume-expander-operator/0.3.0/metadata/annotations.yaml, operators/volume-expander-operator/0.3.0/tests/scorecard/config.yaml
=> operators volume-expander-operator (0.3.0)

operators/ibmcloud-operator/ci.yaml
Add myself and my teammates for approved reviews on our operator.
For reference, here's a previous release PR we merged in the old repos:
* https://github.com/operator-framework/community-operators/pull/2379
* https://github.com/operator-framework/community-operators/pull/2398
Signed-off-by: John Starich <johnstarich@johnstarich.com>
--
<sup>1</sup> If you feel your Operator does not fit any …
=> operators [CI] ibmcloud-operator

operators/cert-utils-operator/1.2.0/Dockerfile, operators/cert-utils-operator/1.2.0/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.2.0/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.2.0/manifests/cert-utils-operator-controller-manager_v1_serviceaccount.yaml, operators/cert-utils-operator/1.2.0/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.2.0/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.2.0/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.2.0/metadata/annotations.yaml, operators/cert-utils-operator/1.2.0/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.2.0)

operators/cert-utils-operator/1.3.0/Dockerfile, operators/cert-utils-operator/1.3.0/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.0/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.3.0/manifests/cert-utils-operator-controller-manager_v1_serviceaccount.yaml, operators/cert-utils-operator/1.3.0/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.0/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.0/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.0/metadata/annotations.yaml, operators/cert-utils-operator/1.3.0/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.0)

operators/ibmcloud-operator/1.0.10/apiextensions.k8s.io_v1beta1_customresourcedefinition_bindings.ibmcloud.ibm.com.yaml, operators/ibmcloud-operator/1.0.10/apiextensions.k8s.io_v1beta1_customresourcedefinition_services.ibmcloud.ibm.com.yaml, operators/ibmcloud-operator/1.0.10/ibmcloud_operator.v1.0.10.clusterserviceversion.yaml, operators/ibmcloud-operator/ibmcloud-operator.package.yaml
Automated release of IBM Cloud Operator v1.0.10.
=> operators ibmcloud-operator (1.0.10)

operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_hooks.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_hosts.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_migrations.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_networkmaps.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_plans.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_providers.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_provisioners.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/forklift.konveyor.io_storagemaps.yaml, operators/konveyor-forklift-operator/2.1.0/manifests/konveyor-forklift-operator.v2.1.0.clusterserviceversion.yaml, operators/konveyor-forklift-operator/2.1.0/metadata/annotations.yaml
=> operators konveyor-forklift-operator (2.1.0)

operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.18.1/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.18.1/victoriametrics-operator.0.18.1.clusterserviceversion.yaml, operators/victoriametrics-operator/0.18.1/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/victoriametrics-operator/0.18.1/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/victoriametrics-operator/0.18.1/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.18.1)

operators/kubernetes-imagepuller-operator/0.0.9/che.eclipse.org_kubernetesimagepullers_crd.yaml, operators/kubernetes-imagepuller-operator/0.0.9/kubernetes-imagepuller-operator.v0.0.9.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
--
=> operators kubernetes-imagepuller-operator (0.0.9)

operators/mta-operator/0.0.7/Dockerfile, operators/mta-operator/0.0.7/manifests/windup-operator.v0.0.7.clusterserviceversion.yaml, operators/mta-operator/0.0.7/manifests/windup.crd.yaml, operators/mta-operator/0.0.7/metadata/annotations.yaml
=> operators mta-operator (0.0.7)

operators/sap-commerce-operator/0.0.4/manifests/hybris.hybris.org_hybrisapps.yaml, operators/sap-commerce-operator/0.0.4/manifests/hybris.hybris.org_hybrisbases.yaml, operators/sap-commerce-operator/0.0.4/manifests/sap-commerce-operator-hybris-controller-manager-metrics-service_v1_service.yaml, operators/sap-commerce-operator/0.0.4/manifests/sap-commerce-operator-manager-config_v1_configmap.yaml, operators/sap-commerce-operator/0.0.4/manifests/sap-commerce-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/sap-commerce-operator/0.0.4/manifests/sap-commerce-operator.clusterserviceversion.yaml, operators/sap-commerce-operator/0.0.4/metadata/annotations.yaml
Signed-off-by: Marco Yeung <myeung@redhat.com>
* [ x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ x] Have you tested an update to your Operator when deployed via OLM?
* [ x] Is your submission …
=> operators sap-commerce-operator (0.0.4)

operators/ibm-spectrum-scale-csi-operator/2.3.0/csiscaleoperators.csi.ibm.com.crd.yaml, operators/ibm-spectrum-scale-csi-operator/2.3.0/ibm-spectrum-scale-csi-operator.v2.3.0.clusterserviceversion.yaml, operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
=> operators ibm-spectrum-scale-csi-operator (2.3.0)

operators/group-sync-operator/0.0.13/Dockerfile, operators/group-sync-operator/0.0.13/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.13/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.13/manifests/group-sync-operator-controller-manager_v1_serviceaccount.yaml, operators/group-sync-operator/0.0.13/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.13/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.13/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.13/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.13/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.13/metadata/annotations.yaml, operators/group-sync-operator/0.0.13/tests/scorecard/config.yaml
=> operators group-sync-operator (0.0.13)

operators/ibmcloud-operator/1.0.11/apiextensions.k8s.io_v1beta1_customresourcedefinition_bindings.ibmcloud.ibm.com.yaml, operators/ibmcloud-operator/1.0.11/apiextensions.k8s.io_v1beta1_customresourcedefinition_services.ibmcloud.ibm.com.yaml, operators/ibmcloud-operator/1.0.11/ibmcloud_operator.v1.0.11.clusterserviceversion.yaml, operators/ibmcloud-operator/ibmcloud-operator.package.yaml
Automated release of IBM Cloud Operator v1.0.11.
=> operators ibmcloud-operator (1.0.11)

operators/redis-operator/0.8.0/manifests/redis-operator.v0.8.0.clusterserviceversion.yaml, operators/redis-operator/0.8.0/manifests/redis.redis.redis.opstreelabs.in.crd.yaml, operators/redis-operator/0.8.0/manifests/redisclusters.redis.redis.opstreelabs.in.crd.yaml, operators/redis-operator/0.8.0/metadata/annotations.yaml
Signed-off-by: iamabhishek-dubey <abhishekbhardwaj510@gmail.com>
--
=> operators redis-operator (0.8.0)

operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.18.2/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.18.2/victoriametrics-operator.0.18.2.clusterserviceversion.yaml, operators/victoriametrics-operator/0.18.2/vm-operator-vm-operator-psp-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/victoriametrics-operator/0.18.2/vm-operator-vm-operator-psp-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/victoriametrics-operator/0.18.2/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.18.2)

operators/etcd/0.6.1/etcdoperator.v0.6.1.clusterserviceversion.yaml, operators/etcd/0.9.0/etcdoperator.v0.9.0.clusterserviceversion.yaml, operators/etcd/0.9.2-clusterwide/etcdoperator.v0.9.2-clusterwide.clusterserviceversion.yaml, operators/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml, operators/etcd/0.9.4-clusterwide/etcdoperator.v0.9.4-clusterwide.clusterserviceversion.yaml, operators/etcd/0.9.4/etcdoperator.v0.9.4.clusterserviceversion.yaml
Fix #193  remove the `olm.maxOpenShiftVersion=4.8` since this etcd opeataor's CRDs already use the `v1` version. 
--
=> operators [R] etcd (0.6.1 0.9.0 0.9.2 0.9.2-clusterwide 0.9.4 0.9.4-clusterwide)

operators/hyperfoil-bundle/0.15.0/hyperfoil-operator.v0.15.0.clusterserviceversion.yaml, operators/hyperfoil-bundle/0.15.0/hyperfoil.io_hyperfoils_crd.yaml, operators/hyperfoil-bundle/hyperfoil-bundle.package.yaml
=> operators hyperfoil-bundle (0.15.0)

operators/assisted-service-operator/0.1.0/agent-install.openshift.io_agents.yaml, operators/assisted-service-operator/0.1.0/agent-install.openshift.io_agentserviceconfigs.yaml, operators/assisted-service-operator/0.1.0/agent-install.openshift.io_infraenvs.yaml, operators/assisted-service-operator/0.1.0/agent-install.openshift.io_nmstateconfigs.yaml, operators/assisted-service-operator/0.1.0/assisted-service-operator.clusterserviceversion.yaml, operators/assisted-service-operator/0.1.0/extensions.hive.openshift.io_agentclusterinstalls.yaml, operators/assisted-service-operator/assisted-service.package.yaml
=> operators assisted-service-operator (0.1.0)

operators/crane-operator/1.5.1/manifests/backup.crd.yaml, operators/crane-operator/1.5.1/manifests/backupstoragelocation.crd.yaml, operators/crane-operator/1.5.1/manifests/crane-operator.v1.5.1.clusterserviceversion.yaml, operators/crane-operator/1.5.1/manifests/deletebackuprequest.crd.yaml, operators/crane-operator/1.5.1/manifests/downloadrequest.crd.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_directimagemigrations.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_directimagestreammigrations.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_directvolumemigrations.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_miganalytics.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_migclusters.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_mighooks.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_migmigrations.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_migplans.yaml, operators/crane-operator/1.5.1/manifests/migration.openshift.io_migstorages.yaml, operators/crane-operator/1.5.1/manifests/migrationcontroller.crd.yaml, operators/crane-operator/1.5.1/manifests/podvolumebackup.crd.yaml, operators/crane-operator/1.5.1/manifests/podvolumerestore.crd.yaml, operators/crane-operator/1.5.1/manifests/resticrepository.crd.yaml, operators/crane-operator/1.5.1/manifests/restore.crd.yaml, operators/crane-operator/1.5.1/manifests/schedule.crd.yaml, operators/crane-operator/1.5.1/manifests/serverstatusrequest.crd.yaml, operators/crane-operator/1.5.1/manifests/volumesnapshotlocation.crd.yaml, operators/crane-operator/1.5.1/metadata/annotations.yaml
=> operators crane-operator (1.5.1)

operators/datatrucker-operator/1.3.0/bundle.Dockerfile, operators/datatrucker-operator/1.3.0/manifests/datatrucker-operator-controller-manager-metrics-service_v1_service.yaml, operators/datatrucker-operator/1.3.0/manifests/datatrucker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/datatrucker-operator/1.3.0/manifests/datatrucker-operator.clusterserviceversion.yaml, operators/datatrucker-operator/1.3.0/manifests/datatrucker.datatrucker.io_datatruckerconfigs.yaml, operators/datatrucker-operator/1.3.0/manifests/datatrucker.datatrucker.io_datatruckerflows.yaml, operators/datatrucker-operator/1.3.0/metadata/annotations.yaml, operators/datatrucker-operator/1.3.0/tests/scorecard/config.yaml, operators/datatrucker-operator/1.3.1/bundle.Dockerfile, operators/datatrucker-operator/1.3.1/manifests/datatrucker-operator-controller-manager-metrics-service_v1_service.yaml, operators/datatrucker-operator/1.3.1/manifests/datatrucker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/datatrucker-operator/1.3.1/manifests/datatrucker-operator.clusterserviceversion.yaml, operators/datatrucker-operator/1.3.1/manifests/datatrucker.datatrucker.io_datatruckerconfigs.yaml, operators/datatrucker-operator/1.3.1/manifests/datatrucker.datatrucker.io_datatruckerflows.yaml, operators/datatrucker-operator/1.3.1/metadata/annotations.yaml, operators/datatrucker-operator/1.3.1/tests/scorecard/config.yaml, operators/datatrucker-operator/ci.yaml
* [ yes ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ yes ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ yes ] Have you tested your Operator with all Custom Resource Definitions?
* [yes  ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ yes  Have you considered whether you want use [semantic versioning …
=> operators [R] [CI] datatrucker-operator (1.3.0 1.3.1)

operators/camel-k/1.6.0/builds.camel.apache.org.crd.yaml, operators/camel-k/1.6.0/camel-k.v1.6.0.clusterserviceversion.yaml, operators/camel-k/1.6.0/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.6.0/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.6.0/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.6.0/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.6.0/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.6.0/kamelets.camel.apache.org.crd.yaml, operators/camel-k/camel-k.package.yaml
Signed-off-by: nicolaferraro <ni.ferraro@gmail.com>
--
=> operators camel-k (1.6.0)

operators/multicluster-operators-subscription/0.3.1/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.2/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.2/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.2/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.2/apps.open-cluster-management.io_gitopsclusters_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.2/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.2/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.2/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.2/multicluster-operators-subscription.v0.3.2.clusterserviceversion.yaml, operators/multicluster-operators-subscription/ci.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
Signed-off-by: Roke Jung <roke@redhat.com>
--
=> operators [R] [CI] multicluster-operators-subscription (0.3.2)

operators/crane-operator/1.4.7/manifests/backup.crd.yaml, operators/crane-operator/1.4.7/manifests/backupstoragelocation.crd.yaml, operators/crane-operator/1.4.7/manifests/crane-operator.v1.4.7.clusterserviceversion.yaml, operators/crane-operator/1.4.7/manifests/deletebackuprequest.crd.yaml, operators/crane-operator/1.4.7/manifests/downloadrequest.crd.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_directimagemigrations.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_directimagestreammigrations.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_directvolumemigrations.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_miganalytics.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_migclusters.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_mighooks.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_migmigrations.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_migplans.yaml, operators/crane-operator/1.4.7/manifests/migration.openshift.io_migstorages.yaml, operators/crane-operator/1.4.7/manifests/migrationcontroller.crd.yaml, operators/crane-operator/1.4.7/manifests/podvolumebackup.crd.yaml, operators/crane-operator/1.4.7/manifests/podvolumerestore.crd.yaml, operators/crane-operator/1.4.7/manifests/resticrepository.crd.yaml, operators/crane-operator/1.4.7/manifests/restore.crd.yaml, operators/crane-operator/1.4.7/manifests/schedule.crd.yaml, operators/crane-operator/1.4.7/manifests/serverstatusrequest.crd.yaml, operators/crane-operator/1.4.7/manifests/volumesnapshotlocation.crd.yaml, operators/crane-operator/1.4.7/metadata/annotations.yaml
=> operators crane-operator (1.4.7)

operators/snyk-operator/ci.yaml
Signed-off-by: Ivan Stanev <istanev93@gmail.com>
--
=> operators [CI] snyk-operator

operators/portworx-essentials/1.5.1/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.5.1/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.5.1/portworxoperator.v1.5.1.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operators portworx-essentials (1.5.1)

operators/cluster-impairment-operator/1.0.3/manifests/apps.redhat.com_clusterimpairments.yaml, operators/cluster-impairment-operator/1.0.3/manifests/cluster-impairment-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-impairment-operator/1.0.3/manifests/cluster-impairment-operator-manager-config_v1_configmap.yaml, operators/cluster-impairment-operator/1.0.3/manifests/cluster-impairment-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-impairment-operator/1.0.3/manifests/cluster-impairment-operator.clusterserviceversion.yaml, operators/cluster-impairment-operator/1.0.3/manifests/network-access-sa_v1_serviceaccount.yaml, operators/cluster-impairment-operator/1.0.3/metadata/annotations.yaml, operators/cluster-impairment-operator/1.0.3/tests/scorecard/config.yaml
Signed-off-by: Jared O'Connell <joconnel@redhat.com>
* [] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
-- …
=> operators cluster-impairment-operator (1.0.3)

operators/datatrucker-operator/1.3.2/bundle.Dockerfile, operators/datatrucker-operator/1.3.2/manifests/datatrucker-operator-controller-manager-metrics-service_v1_service.yaml, operators/datatrucker-operator/1.3.2/manifests/datatrucker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/datatrucker-operator/1.3.2/manifests/datatrucker-operator.clusterserviceversion.yaml, operators/datatrucker-operator/1.3.2/manifests/datatrucker.datatrucker.io_datatruckerconfigs.yaml, operators/datatrucker-operator/1.3.2/manifests/datatrucker.datatrucker.io_datatruckerflows.yaml, operators/datatrucker-operator/1.3.2/metadata/annotations.yaml, operators/datatrucker-operator/1.3.2/tests/scorecard/config.yaml, operators/datatrucker-operator/ci.yaml
Signed-off-by: Gaurav Shankar <gauravshankar.can@gmail.com>
* [ Yes] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [Yes ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ Yes] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [Yes ] Have you tested an update to your Operator when deployed via OLM?
* [Yes …
=> operators [CI] datatrucker-operator (1.3.2)

operators/community-windows-machine-config-operator/3.1.0/manifests/community-windows-machine-config-operator.3.1.0.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/3.1.0/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/3.1.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/3.1.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/3.1.0/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/3.1.0/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/3.1.0/manifests/windows-machine-config-operator_v1_serviceaccount.yaml, operators/community-windows-machine-config-operator/3.1.0/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/3.1.0/metadata/annotations.yaml
Signed-off-by: Sebastian Soto <ssoto@redhat.com>
--
=> operators community-windows-machine-config-operator (3.1.0)

operators/hyperfoil-bundle/0.15.1/hyperfoil-operator-controller-manager-metrics-service_v1_service.yaml, operators/hyperfoil-bundle/0.15.1/hyperfoil-operator-manager-config_v1_configmap.yaml, operators/hyperfoil-bundle/0.15.1/hyperfoil-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/hyperfoil-bundle/0.15.1/hyperfoil-operator.clusterserviceversion.yaml, operators/hyperfoil-bundle/0.15.1/hyperfoil.io_hyperfoils.yaml, operators/hyperfoil-bundle/hyperfoil-bundle.package.yaml
=> operators hyperfoil-bundle (0.15.1)

operators/hyperfoil-bundle/ci.yaml
=> operators [CI] hyperfoil-bundle

operators/special-resource-operator/4.8.1/Dockerfile, operators/special-resource-operator/4.8.1/manifests/special-resource-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/special-resource-operator/4.8.1/manifests/special-resource-controller-manager-metrics-service_v1_service.yaml, operators/special-resource-operator/4.8.1/manifests/special-resource-dependencies_v1_configmap.yaml, operators/special-resource-operator/4.8.1/manifests/special-resource-lifecycle_v1_configmap.yaml, operators/special-resource-operator/4.8.1/manifests/special-resource-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/special-resource-operator/4.8.1/manifests/special-resource-operator.clusterserviceversion.yaml, operators/special-resource-operator/4.8.1/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/special-resource-operator/4.8.1/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/special-resource-operator/4.8.1/manifests/sro.openshift.io_specialresources.yaml, operators/special-resource-operator/4.8.1/metadata/annotations.yaml, operators/special-resource-operator/4.8.1/tests/scorecard/config.yaml
* [] Have you tested an update to your Operator when deployed via OLM?
=> operators special-resource-operator (4.8.1)

operators/flux/0.17.1/manifests/alert.crd.yaml, operators/flux/0.17.1/manifests/bucket.crd.yaml, operators/flux/0.17.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.17.1/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.17.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.17.1/manifests/flux.v0.17.1.clusterserviceversion.yaml, operators/flux/0.17.1/manifests/gitrepository.crd.yaml, operators/flux/0.17.1/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.17.1/manifests/helmchart.crd.yaml, operators/flux/0.17.1/manifests/helmrelease.crd.yaml, operators/flux/0.17.1/manifests/helmrepository.crd.yaml, operators/flux/0.17.1/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.17.1/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.17.1/manifests/imagepolicy.crd.yaml, operators/flux/0.17.1/manifests/imagerepository.crd.yaml, operators/flux/0.17.1/manifests/imageupdateautomation.crd.yaml, operators/flux/0.17.1/manifests/kustomization.crd.yaml, operators/flux/0.17.1/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.17.1/manifests/notification-controller.service.yaml, operators/flux/0.17.1/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.17.1/manifests/provider.crd.yaml, operators/flux/0.17.1/manifests/receiver.crd.yaml, operators/flux/0.17.1/manifests/source-controller.service.yaml, operators/flux/0.17.1/manifests/source-controller.serviceaccount.yaml, operators/flux/0.17.1/manifests/webhook-receiver.service.yaml, operators/flux/0.17.1/metadata/annotations.yaml
3. [ x Any manual steps about potential pre-requisites for using your Operator
--
=> operators flux (0.17.1)

operators/universal-crossplane/1.3.1-up.1/manifests/universal-crossplane.1.3.1-up.1.clusterserviceversion.yaml
We accidentally left these in the `ClusterServiceVersion` and it [broke](https://github.com/upbound/universal-crossplane/issues/172#issuecomment-920148777) some users. This PR reverts security contexts back to their original value in the earlier releases.
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your …
=> operators [O] universal-crossplane (1.3.1-up.1)

operators/rhoas-operator/0.7.9/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.7.9/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.7.9/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.7.9/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.7.9/metadata/annotations.yaml
=> operators rhoas-operator (0.7.9)

operators/gitops-primer/0.0.1/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.1/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.1/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.1/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.1/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.1/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.1/metadata/annotations.yaml, operators/gitops-primer/0.0.1/tests/scorecard/config.yaml, operators/gitops-primer/ci.yaml
=> operators [N] [CI] gitops-primer (0.0.1)

operators/gitops-primer/0.0.1/manifests/gitops-primer.clusterserviceversion.yaml
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
=> operators [N] gitops-primer (0.0.1)

operators/rhoas-operator/0.7.10/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.7.10/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.7.10/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.7.10/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.7.10/manifests/service-binding.clusterrole.yaml, operators/rhoas-operator/0.7.10/metadata/annotations.yaml
=> operators rhoas-operator (0.7.10)

operators/multicluster-operators-subscription/0.3.3/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.3/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.3/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.3/apps.open-cluster-management.io_gitopsclusters_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.3/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.3/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.3/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.3/multicluster-operators-subscription.v0.3.2.clusterserviceversion.yaml, operators/multicluster-operators-subscription/0.3.3/multicluster-operators-subscription.v0.3.3.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
Signed-off-by: Joshua Packer <jpacker@redhat.com>
--
=> operators multicluster-operators-subscription (0.3.3)

operators/cluster-impairment-operator/1.0.4/manifests/apps.redhat.com_clusterimpairments.yaml, operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator-manager-config_v1_configmap.yaml, operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-impairment-operator/1.0.4/manifests/cluster-impairment-operator.clusterserviceversion.yaml, operators/cluster-impairment-operator/1.0.4/manifests/network-access-sa_v1_serviceaccount.yaml, operators/cluster-impairment-operator/1.0.4/metadata/annotations.yaml, operators/cluster-impairment-operator/1.0.4/tests/scorecard/config.yaml
Signed-off-by: Jared O'Connell <joconnel@redhat.com>
--
=> operators cluster-impairment-operator (1.0.4)

operators/assisted-service-operator/0.1.0/assisted-service-operator.clusterserviceversion.yaml
=> operators [O] assisted-service-operator (0.1.0)

operators/multicluster-operators-subscription/0.3.4/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.4/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.4/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.4/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.4/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.4/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.4/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.4/multicluster-operators-subscription.v0.3.4.clusterserviceversion.yaml, operators/multicluster-operators-subscription/ci.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
Signed-off-by: Roke Jung <roke@redhat.com>
--
=> operators [CI] multicluster-operators-subscription (0.3.4)

operators/portworx-essentials/1.5.2/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.5.2/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.5.2/portworxoperator.v1.5.2.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operators portworx-essentials (1.5.2)

operators/assisted-service-operator/0.0.4/assisted-service-operator.clusterserviceversion.yaml, operators/assisted-service-operator/0.0.5/assisted-service-operator.clusterserviceversion.yaml, operators/assisted-service-operator/0.0.6/assisted-service-operator.clusterserviceversion.yaml, operators/assisted-service-operator/0.0.7/assisted-service-operator.clusterserviceversion.yaml
Newer versions were not marking older ones as replaced (since 0.0.4)
Signed-off-by: Flavio Percoco <flavio@redhat.com>
=> operators [R] assisted-service-operator (0.0.4 0.0.5 0.0.6 0.0.7)

operators/assisted-service-operator/0.0.7/assisted-service-operator.clusterserviceversion.yaml
=> operators [O] [R] assisted-service-operator (0.0.7)

operators/kiali/1.40.1/bundle.Dockerfile, operators/kiali/1.40.1/manifests/kiali.crd.yaml, operators/kiali/1.40.1/manifests/kiali.v1.40.1.clusterserviceversion.yaml, operators/kiali/1.40.1/metadata/annotations.yaml
=> operators kiali (1.40.1)

operators/oadp-operator/0.2.3/metadata/annotations.yaml, operators/oadp-operator/0.2.5/metadata/annotations.yaml, operators/oadp-operator/0.2.6/metadata/annotations.yaml
Signed-off-by: Martin Vala <mavala@redhat.com>
=> Fix annotations spaces

operators/assisted-service-operator/0.0.7/assisted-service-operator.clusterserviceversion.yaml
=> operators [O] assisted-service-operator (0.0.7)

operators/assisted-service-operator/0.0.8/agent-install.openshift.io_agents.yaml, operators/assisted-service-operator/0.0.8/agent-install.openshift.io_agentserviceconfigs.yaml, operators/assisted-service-operator/0.0.8/agent-install.openshift.io_infraenvs.yaml, operators/assisted-service-operator/0.0.8/agent-install.openshift.io_nmstateconfigs.yaml, operators/assisted-service-operator/0.0.8/assisted-service-operator.clusterserviceversion.yaml, operators/assisted-service-operator/0.0.8/extensions.hive.openshift.io_agentclusterinstalls.yaml, operators/assisted-service-operator/assisted-service.package.yaml
=> operators assisted-service-operator (0.0.8)

operators/flux/0.17.2/manifests/alert.crd.yaml, operators/flux/0.17.2/manifests/bucket.crd.yaml, operators/flux/0.17.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.17.2/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.17.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.17.2/manifests/flux.v0.17.2.clusterserviceversion.yaml, operators/flux/0.17.2/manifests/gitrepository.crd.yaml, operators/flux/0.17.2/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.17.2/manifests/helmchart.crd.yaml, operators/flux/0.17.2/manifests/helmrelease.crd.yaml, operators/flux/0.17.2/manifests/helmrepository.crd.yaml, operators/flux/0.17.2/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.17.2/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.17.2/manifests/imagepolicy.crd.yaml, operators/flux/0.17.2/manifests/imagerepository.crd.yaml, operators/flux/0.17.2/manifests/imageupdateautomation.crd.yaml, operators/flux/0.17.2/manifests/kustomization.crd.yaml, operators/flux/0.17.2/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.17.2/manifests/notification-controller.service.yaml, operators/flux/0.17.2/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.17.2/manifests/provider.crd.yaml, operators/flux/0.17.2/manifests/receiver.crd.yaml, operators/flux/0.17.2/manifests/source-controller.service.yaml, operators/flux/0.17.2/manifests/source-controller.serviceaccount.yaml, operators/flux/0.17.2/manifests/webhook-receiver.service.yaml, operators/flux/0.17.2/metadata/annotations.yaml
=> operators flux (0.17.2)

operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.19.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.19.0/victoriametrics-operator.0.19.0.clusterserviceversion.yaml, operators/victoriametrics-operator/0.19.0/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/ci.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators [CI] victoriametrics-operator (0.19.0)

operators/oadp-operator/0.3.0/manifests/backup.crd.yaml, operators/oadp-operator/0.3.0/manifests/backupstoragelocation.crd.yaml, operators/oadp-operator/0.3.0/manifests/deletebackuprequest.crd.yaml, operators/oadp-operator/0.3.0/manifests/downloadrequest.crd.yaml, operators/oadp-operator/0.3.0/manifests/oadp-operator.v0.3.0.clusterserviceversion.yaml, operators/oadp-operator/0.3.0/manifests/podvolumebackup.crd.yaml, operators/oadp-operator/0.3.0/manifests/podvolumerestore.crd.yaml, operators/oadp-operator/0.3.0/manifests/resticrepository.crd.yaml, operators/oadp-operator/0.3.0/manifests/restore.crd.yaml, operators/oadp-operator/0.3.0/manifests/schedule.crd.yaml, operators/oadp-operator/0.3.0/manifests/serverstatusrequest.crd.yaml, operators/oadp-operator/0.3.0/manifests/veleroes.crd.yaml, operators/oadp-operator/0.3.0/manifests/volumesnapshotlocation.crd.yaml, operators/oadp-operator/0.3.0/metadata/annotations.yaml
=> operators oadp-operator (0.3.0)

operators/nfs-provisioner-operator/0.0.2/Dockerfile, operators/nfs-provisioner-operator/0.0.2/manifests/cache.jhouse.com_nfsprovisioners.yaml, operators/nfs-provisioner-operator/0.0.2/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml, operators/nfs-provisioner-operator/0.0.2/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.2/manifests/nfs-provisioner-operator.clusterserviceversion.yaml, operators/nfs-provisioner-operator/0.0.2/metadata/annotations.yaml, operators/nfs-provisioner-operator/0.0.2/tests/scorecard/config.yaml, operators/nfs-provisioner-operator/ci.yaml
Signed-off-by: Jooho Lee <ljhiyh@gmail.com>
* [V] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [V] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [V] Have you tested your Operator with all Custom Resource Definitions?
* [V] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [V] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/do …
=> operators [N] [CI] nfs-provisioner-operator (0.0.2)

operators/nfs-provisioner-operator/0.0.3/Dockerfile, operators/nfs-provisioner-operator/0.0.3/manifests/cache.jhouse.com_nfsprovisioners.yaml, operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml, operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.3/manifests/nfs-provisioner-operator.clusterserviceversion.yaml, operators/nfs-provisioner-operator/0.0.3/metadata/annotations.yaml, operators/nfs-provisioner-operator/0.0.3/tests/scorecard/config.yaml
Signed-off-by: Jooho Lee <ljhiyh@gmail.com>
* [V] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [V] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [V] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [V] Have you tested an update to your Operator when deployed via OLM?
* [V] Is your submission …
=> operators nfs-provisioner-operator (0.0.3)

operators/multicluster-operators-subscription/0.3.5/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.5/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.5/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.5/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.5/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.5/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.5/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.5/multicluster-operators-subscription.v0.3.5.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators multicluster-operators-subscription (0.3.5)

operators/crane-operator/1.6.0/manifests/backup.crd.yaml, operators/crane-operator/1.6.0/manifests/backupstoragelocation.crd.yaml, operators/crane-operator/1.6.0/manifests/crane-operator.v1.6.0.clusterserviceversion.yaml, operators/crane-operator/1.6.0/manifests/deletebackuprequest.crd.yaml, operators/crane-operator/1.6.0/manifests/downloadrequest.crd.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_directimagemigrations.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_directimagestreammigrations.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_directvolumemigrations.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_miganalytics.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_migclusters.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_mighooks.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_migmigrations.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_migplans.yaml, operators/crane-operator/1.6.0/manifests/migration.openshift.io_migstorages.yaml, operators/crane-operator/1.6.0/manifests/migrationcontroller.crd.yaml, operators/crane-operator/1.6.0/manifests/podvolumebackup.crd.yaml, operators/crane-operator/1.6.0/manifests/podvolumerestore.crd.yaml, operators/crane-operator/1.6.0/manifests/resticrepository.crd.yaml, operators/crane-operator/1.6.0/manifests/restore.crd.yaml, operators/crane-operator/1.6.0/manifests/schedule.crd.yaml, operators/crane-operator/1.6.0/manifests/serverstatusrequest.crd.yaml, operators/crane-operator/1.6.0/manifests/volumesnapshotlocation.crd.yaml, operators/crane-operator/1.6.0/metadata/annotations.yaml
=> operators crane-operator (1.6.0)

operators/multicluster-operators-subscription/0.3.6/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.6/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.6/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.6/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.6/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.6/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.6/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.6/multicluster-operators-subscription.v0.3.6.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators multicluster-operators-subscription (0.3.6)

operators/hawtio-operator/0.4.0/hawtio-operator.v0.4.0.clusterserviceversion.yaml, operators/hawtio-operator/0.4.0/hawtios.hawt.io.crd.yaml, operators/hawtio-operator/ci.yaml, operators/hawtio-operator/hawtio-operator.package.yaml
* -> The [test suite](https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-test-suite/) doesn't run on my Fedora 34 + Podman env
--
=> operators [CI] hawtio-operator (0.4.0)

operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.19.1/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.19.1/victoriametrics-operator.0.19.1.clusterserviceversion.yaml, operators/victoriametrics-operator/0.19.1/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.19.1)

operators/kiali/1.41.0/bundle.Dockerfile, operators/kiali/1.41.0/manifests/kiali.crd.yaml, operators/kiali/1.41.0/manifests/kiali.v1.41.0.clusterserviceversion.yaml, operators/kiali/1.41.0/metadata/annotations.yaml
=> operators kiali (1.41.0)

operators/oadp-operator/0.3.0/manifests/oadp-operator.v0.3.0.clusterserviceversion.yaml
=> operators [O] oadp-operator (0.3.0)

operators/microcks/1.4.1/microcks-operator.v1.4.1.clusterserviceversion.yaml, operators/microcks/1.4.1/microcksinstall.crd.yaml, operators/microcks/ci.yaml, operators/microcks/microcks.package.yaml
=> operators [CI] microcks (1.4.1)

operators/flux/0.18.1/manifests/alert.crd.yaml, operators/flux/0.18.1/manifests/bucket.crd.yaml, operators/flux/0.18.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.18.1/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.18.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.18.1/manifests/flux.v0.18.1.clusterserviceversion.yaml, operators/flux/0.18.1/manifests/gitrepository.crd.yaml, operators/flux/0.18.1/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.18.1/manifests/helmchart.crd.yaml, operators/flux/0.18.1/manifests/helmrelease.crd.yaml, operators/flux/0.18.1/manifests/helmrepository.crd.yaml, operators/flux/0.18.1/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.18.1/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.18.1/manifests/imagepolicy.crd.yaml, operators/flux/0.18.1/manifests/imagerepository.crd.yaml, operators/flux/0.18.1/manifests/imageupdateautomation.crd.yaml, operators/flux/0.18.1/manifests/kustomization.crd.yaml, operators/flux/0.18.1/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.18.1/manifests/notification-controller.service.yaml, operators/flux/0.18.1/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.18.1/manifests/provider.crd.yaml, operators/flux/0.18.1/manifests/receiver.crd.yaml, operators/flux/0.18.1/manifests/source-controller.service.yaml, operators/flux/0.18.1/manifests/source-controller.serviceaccount.yaml, operators/flux/0.18.1/manifests/webhook-receiver.service.yaml, operators/flux/0.18.1/metadata/annotations.yaml
=> operators flux (0.18.1)

operators/integrity-shield-operator/0.3.0/manifests/apis.integrityshield.io_integrityshields.yaml, operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-controller-manager-metrics-service_v1_service.yaml, operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-controller-manager_v1_serviceaccount.yaml, operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-manager-config_v1_configmap.yaml, operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/integrity-shield-operator/0.3.0/manifests/integrity-shield-operator.clusterserviceversion.yaml, operators/integrity-shield-operator/0.3.0/metadata/annotations.yaml, operators/integrity-shield-operator/0.3.0/tests/scorecard/config.yaml
Signed-off-by: Ruriko Kudo <rurikudo@ibm.com>
Co-authored-by: Kugamoorthy Gajananan <gajan@jp.ibm.com>
--
=> operators integrity-shield-operator (0.3.0)

operators/aqua/6.5.0/aqua-operator.v6.5.0.clusterserviceversion.yaml, operators/aqua/6.5.0/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/aqua-operator.package.yaml, operators/aqua/ci.yaml
=> operators [CI] aqua (6.5.0)

operators/assisted-service-operator/ci.yaml
I did the last release and I might need to do it again. It would be
easier if I'm on the reviewers list.
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>
-- …
=> operators [CI] assisted-service-operator

operators/flux/0.20.0/manifests/alert.crd.yaml, operators/flux/0.20.0/manifests/bucket.crd.yaml, operators/flux/0.20.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.20.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.20.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.20.0/manifests/flux.v0.20.0.clusterserviceversion.yaml, operators/flux/0.20.0/manifests/gitrepository.crd.yaml, operators/flux/0.20.0/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.20.0/manifests/helmchart.crd.yaml, operators/flux/0.20.0/manifests/helmrelease.crd.yaml, operators/flux/0.20.0/manifests/helmrepository.crd.yaml, operators/flux/0.20.0/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.20.0/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.20.0/manifests/imagepolicy.crd.yaml, operators/flux/0.20.0/manifests/imagerepository.crd.yaml, operators/flux/0.20.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.20.0/manifests/kustomization.crd.yaml, operators/flux/0.20.0/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.20.0/manifests/notification-controller.service.yaml, operators/flux/0.20.0/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.20.0/manifests/provider.crd.yaml, operators/flux/0.20.0/manifests/receiver.crd.yaml, operators/flux/0.20.0/manifests/source-controller.service.yaml, operators/flux/0.20.0/manifests/source-controller.serviceaccount.yaml, operators/flux/0.20.0/manifests/webhook-receiver.service.yaml, operators/flux/0.20.0/metadata/annotations.yaml
=> operators flux (0.20.0)

operators/flux/0.20.1/manifests/alert.crd.yaml, operators/flux/0.20.1/manifests/bucket.crd.yaml, operators/flux/0.20.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.20.1/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.20.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.20.1/manifests/flux.v0.20.1.clusterserviceversion.yaml, operators/flux/0.20.1/manifests/gitrepository.crd.yaml, operators/flux/0.20.1/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.20.1/manifests/helmchart.crd.yaml, operators/flux/0.20.1/manifests/helmrelease.crd.yaml, operators/flux/0.20.1/manifests/helmrepository.crd.yaml, operators/flux/0.20.1/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.20.1/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.20.1/manifests/imagepolicy.crd.yaml, operators/flux/0.20.1/manifests/imagerepository.crd.yaml, operators/flux/0.20.1/manifests/imageupdateautomation.crd.yaml, operators/flux/0.20.1/manifests/kustomization.crd.yaml, operators/flux/0.20.1/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.20.1/manifests/notification-controller.service.yaml, operators/flux/0.20.1/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.20.1/manifests/provider.crd.yaml, operators/flux/0.20.1/manifests/receiver.crd.yaml, operators/flux/0.20.1/manifests/source-controller.service.yaml, operators/flux/0.20.1/manifests/source-controller.serviceaccount.yaml, operators/flux/0.20.1/manifests/webhook-receiver.service.yaml, operators/flux/0.20.1/metadata/annotations.yaml
=> operators flux (0.20.1)

operators/flux/0.21.0/manifests/alert.crd.yaml, operators/flux/0.21.0/manifests/bucket.crd.yaml, operators/flux/0.21.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.21.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.21.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.21.0/manifests/flux.v0.21.0.clusterserviceversion.yaml, operators/flux/0.21.0/manifests/gitrepository.crd.yaml, operators/flux/0.21.0/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.21.0/manifests/helmchart.crd.yaml, operators/flux/0.21.0/manifests/helmrelease.crd.yaml, operators/flux/0.21.0/manifests/helmrepository.crd.yaml, operators/flux/0.21.0/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.21.0/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.21.0/manifests/imagepolicy.crd.yaml, operators/flux/0.21.0/manifests/imagerepository.crd.yaml, operators/flux/0.21.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.21.0/manifests/kustomization.crd.yaml, operators/flux/0.21.0/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.21.0/manifests/notification-controller.service.yaml, operators/flux/0.21.0/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.21.0/manifests/provider.crd.yaml, operators/flux/0.21.0/manifests/receiver.crd.yaml, operators/flux/0.21.0/manifests/source-controller.service.yaml, operators/flux/0.21.0/manifests/source-controller.serviceaccount.yaml, operators/flux/0.21.0/manifests/webhook-receiver.service.yaml, operators/flux/0.21.0/metadata/annotations.yaml
=> operators flux (0.21.0)

operators/ibm-security-verify-access-operator/ci.yaml
…operator.
Signed-off-by: SCOTT A. EXTON <scotte@au1.ibm.com>
--
=> operators [CI] ibm-security-verify-access-operator

operators/opendatahub-operator/1.1.1/manifests/kfdef.apps.kubeflow.org.crd.yaml, operators/opendatahub-operator/1.1.1/manifests/opendatahub-operator.v1.1.1.clusterserviceversion.yaml, operators/opendatahub-operator/1.1.1/metadata/annotations.yaml
=> operators opendatahub-operator (1.1.1)

operators/rhoas-operator/0.9.1/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.9.1/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.9.1/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.9.1/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.9.1/manifests/rhoas-operator.serviceregistryconnections.crd.yaml, operators/rhoas-operator/0.9.1/manifests/service-binding.clusterrole.yaml, operators/rhoas-operator/0.9.1/metadata/annotations.yaml
=> operators rhoas-operator (0.9.1)

operators/snyk-operator/1.70.1/snyk-operator.v1.70.1.clusterserviceversion.yaml, operators/snyk-operator/1.70.1/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.70.1)

operators/pulp-operator/0.5.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.5.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.5.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.5.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.5.0/manifests/pulp-operator.v0.5.0.clusterserviceversion.yaml, operators/pulp-operator/0.5.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.5.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.5.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.5.0/metadata/annotations.yaml, operators/pulp-operator/0.5.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.5.0)

operators/oadp-operator/0.4.1/manifests/backup.crd.yaml, operators/oadp-operator/0.4.1/manifests/backupstoragelocation.crd.yaml, operators/oadp-operator/0.4.1/manifests/deletebackuprequest.crd.yaml, operators/oadp-operator/0.4.1/manifests/downloadrequest.crd.yaml, operators/oadp-operator/0.4.1/manifests/oadp-operator.v0.4.1.clusterserviceversion.yaml, operators/oadp-operator/0.4.1/manifests/podvolumebackup.crd.yaml, operators/oadp-operator/0.4.1/manifests/podvolumerestore.crd.yaml, operators/oadp-operator/0.4.1/manifests/resticrepository.crd.yaml, operators/oadp-operator/0.4.1/manifests/restore.crd.yaml, operators/oadp-operator/0.4.1/manifests/schedule.crd.yaml, operators/oadp-operator/0.4.1/manifests/serverstatusrequest.crd.yaml, operators/oadp-operator/0.4.1/manifests/veleroes.crd.yaml, operators/oadp-operator/0.4.1/manifests/volumesnapshotlocation.crd.yaml, operators/oadp-operator/0.4.1/metadata/annotations.yaml
Signed-off-by: eemcmullan <eemcmullan92@gmail.com>
--
=> operators oadp-operator (0.4.1)

operators/snyk-operator/1.70.4/snyk-operator.v1.70.4.clusterserviceversion.yaml, operators/snyk-operator/1.70.4/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.70.4)

operators/flux/0.22.0/manifests/alert.crd.yaml, operators/flux/0.22.0/manifests/bucket.crd.yaml, operators/flux/0.22.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.22.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.22.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.22.0/manifests/flux.v0.22.0.clusterserviceversion.yaml, operators/flux/0.22.0/manifests/gitrepository.crd.yaml, operators/flux/0.22.0/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.22.0/manifests/helmchart.crd.yaml, operators/flux/0.22.0/manifests/helmrelease.crd.yaml, operators/flux/0.22.0/manifests/helmrepository.crd.yaml, operators/flux/0.22.0/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.22.0/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.22.0/manifests/imagepolicy.crd.yaml, operators/flux/0.22.0/manifests/imagerepository.crd.yaml, operators/flux/0.22.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.22.0/manifests/kustomization.crd.yaml, operators/flux/0.22.0/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.22.0/manifests/notification-controller.service.yaml, operators/flux/0.22.0/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.22.0/manifests/provider.crd.yaml, operators/flux/0.22.0/manifests/receiver.crd.yaml, operators/flux/0.22.0/manifests/source-controller.service.yaml, operators/flux/0.22.0/manifests/source-controller.serviceaccount.yaml, operators/flux/0.22.0/manifests/webhook-receiver.service.yaml, operators/flux/0.22.0/metadata/annotations.yaml
=> operators flux (0.22.0)

operators/crane-operator/1.6.2/manifests/backup.crd.yaml, operators/crane-operator/1.6.2/manifests/backupstoragelocation.crd.yaml, operators/crane-operator/1.6.2/manifests/crane-operator.v1.6.2.clusterserviceversion.yaml, operators/crane-operator/1.6.2/manifests/deletebackuprequest.crd.yaml, operators/crane-operator/1.6.2/manifests/downloadrequest.crd.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_directimagemigrations.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_directimagestreammigrations.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_directvolumemigrationprogresses.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_directvolumemigrations.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_miganalytics.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_migclusters.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_mighooks.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_migmigrations.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_migplans.yaml, operators/crane-operator/1.6.2/manifests/migration.openshift.io_migstorages.yaml, operators/crane-operator/1.6.2/manifests/migrationcontroller.crd.yaml, operators/crane-operator/1.6.2/manifests/podvolumebackup.crd.yaml, operators/crane-operator/1.6.2/manifests/podvolumerestore.crd.yaml, operators/crane-operator/1.6.2/manifests/resticrepository.crd.yaml, operators/crane-operator/1.6.2/manifests/restore.crd.yaml, operators/crane-operator/1.6.2/manifests/schedule.crd.yaml, operators/crane-operator/1.6.2/manifests/serverstatusrequest.crd.yaml, operators/crane-operator/1.6.2/manifests/volumesnapshotlocation.crd.yaml, operators/crane-operator/1.6.2/metadata/annotations.yaml
=> operators crane-operator (1.6.2)

operators/oadp-operator/0.4.2/manifests/backup.crd.yaml, operators/oadp-operator/0.4.2/manifests/backupstoragelocation.crd.yaml, operators/oadp-operator/0.4.2/manifests/deletebackuprequest.crd.yaml, operators/oadp-operator/0.4.2/manifests/downloadrequest.crd.yaml, operators/oadp-operator/0.4.2/manifests/oadp-operator.v0.4.2.clusterserviceversion.yaml, operators/oadp-operator/0.4.2/manifests/podvolumebackup.crd.yaml, operators/oadp-operator/0.4.2/manifests/podvolumerestore.crd.yaml, operators/oadp-operator/0.4.2/manifests/resticrepository.crd.yaml, operators/oadp-operator/0.4.2/manifests/restore.crd.yaml, operators/oadp-operator/0.4.2/manifests/schedule.crd.yaml, operators/oadp-operator/0.4.2/manifests/serverstatusrequest.crd.yaml, operators/oadp-operator/0.4.2/manifests/veleroes.crd.yaml, operators/oadp-operator/0.4.2/manifests/volumesnapshotlocation.crd.yaml, operators/oadp-operator/0.4.2/metadata/annotations.yaml, operators/oadp-operator/ci.yaml
=> operators [CI] oadp-operator (0.4.2)

operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.38.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.38.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.38.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.38.0/metadata/annotations.yaml
This commit is based on
https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.38.0
but incorporates the fixed CRD from
https://github.com/open-telemetry/opentelemetry-operator/pull/521
needed to work on OpenShift 4.9.
Signed-off-by: Robert Kukura <rkukura@redhat.com>
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue …
=> operators opentelemetry-operator (0.38.0)

operators/camel-k/1.6.1/builds.camel.apache.org.crd.yaml, operators/camel-k/1.6.1/camel-k.v1.6.1.clusterserviceversion.yaml, operators/camel-k/1.6.1/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.6.1/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.6.1/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.6.1/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.6.1/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.6.1/kamelets.camel.apache.org.crd.yaml, operators/camel-k/camel-k.package.yaml, operators/camel-k/ci.yaml
Signed-off-by: nicolaferraro <ni.ferraro@gmail.com>
--
=> operators [CI] camel-k (1.6.1)

operators/flux/0.22.1/manifests/alert.crd.yaml, operators/flux/0.22.1/manifests/bucket.crd.yaml, operators/flux/0.22.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.22.1/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.22.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.22.1/manifests/flux.v0.22.1.clusterserviceversion.yaml, operators/flux/0.22.1/manifests/gitrepository.crd.yaml, operators/flux/0.22.1/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.22.1/manifests/helmchart.crd.yaml, operators/flux/0.22.1/manifests/helmrelease.crd.yaml, operators/flux/0.22.1/manifests/helmrepository.crd.yaml, operators/flux/0.22.1/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.22.1/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.22.1/manifests/imagepolicy.crd.yaml, operators/flux/0.22.1/manifests/imagerepository.crd.yaml, operators/flux/0.22.1/manifests/imageupdateautomation.crd.yaml, operators/flux/0.22.1/manifests/kustomization.crd.yaml, operators/flux/0.22.1/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.22.1/manifests/notification-controller.service.yaml, operators/flux/0.22.1/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.22.1/manifests/provider.crd.yaml, operators/flux/0.22.1/manifests/receiver.crd.yaml, operators/flux/0.22.1/manifests/source-controller.service.yaml, operators/flux/0.22.1/manifests/source-controller.serviceaccount.yaml, operators/flux/0.22.1/manifests/webhook-receiver.service.yaml, operators/flux/0.22.1/metadata/annotations.yaml
=> operators flux (0.22.1)

operators/yaks/0.6.0/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.6.0/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.6.0/yaks.v0.6.0.clusterserviceversion.yaml, operators/yaks/ci.yaml, operators/yaks/yaks.package.yaml
=> operators [CI] yaks (0.6.0)

operators/flux/0.23.0/manifests/alert.crd.yaml, operators/flux/0.23.0/manifests/bucket.crd.yaml, operators/flux/0.23.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.23.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.23.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.23.0/manifests/flux.v0.23.0.clusterserviceversion.yaml, operators/flux/0.23.0/manifests/gitrepository.crd.yaml, operators/flux/0.23.0/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.23.0/manifests/helmchart.crd.yaml, operators/flux/0.23.0/manifests/helmrelease.crd.yaml, operators/flux/0.23.0/manifests/helmrepository.crd.yaml, operators/flux/0.23.0/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.23.0/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.23.0/manifests/imagepolicy.crd.yaml, operators/flux/0.23.0/manifests/imagerepository.crd.yaml, operators/flux/0.23.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.23.0/manifests/kustomization.crd.yaml, operators/flux/0.23.0/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.23.0/manifests/notification-controller.service.yaml, operators/flux/0.23.0/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.23.0/manifests/provider.crd.yaml, operators/flux/0.23.0/manifests/receiver.crd.yaml, operators/flux/0.23.0/manifests/source-controller.service.yaml, operators/flux/0.23.0/manifests/source-controller.serviceaccount.yaml, operators/flux/0.23.0/manifests/webhook-receiver.service.yaml, operators/flux/0.23.0/metadata/annotations.yaml
=> operators flux (0.23.0)

operators/camel-k/ci.yaml
Signed-off-by: nicolaferraro <ni.ferraro@gmail.com>
This is to speed-up releases by setting the reviewers for the Camel K operator.
cc: @astefanutti, @squakez
=> operators [CI] camel-k

operators/resource-locker-operator/1.1.1/Dockerfile, operators/resource-locker-operator/1.1.1/manifests/redhatcop.redhat.io_resourcelockers.yaml, operators/resource-locker-operator/1.1.1/manifests/resource-locker-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/resource-locker-operator/1.1.1/manifests/resource-locker-operator-controller-manager-metrics_v1_service.yaml, operators/resource-locker-operator/1.1.1/manifests/resource-locker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/resource-locker-operator/1.1.1/manifests/resource-locker-operator.clusterserviceversion.yaml, operators/resource-locker-operator/1.1.1/metadata/annotations.yaml, operators/resource-locker-operator/1.1.1/tests/scorecard/config.yaml
=> operators resource-locker-operator (1.1.1)

operators/kiali/1.43.0/bundle.Dockerfile, operators/kiali/1.43.0/manifests/kiali.crd.yaml, operators/kiali/1.43.0/manifests/kiali.v1.43.0.clusterserviceversion.yaml, operators/kiali/1.43.0/metadata/annotations.yaml
=> operators kiali (1.43.0)

operators/neuvector-community-operator/1.2.9/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.2.9/neuvector-operator.v1.2.9.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operators neuvector-community-operator (1.2.9)

operators/special-resource-operator/4.8.1/manifests/special-resource-operator.clusterserviceversion.yaml, operators/special-resource-operator/4.8.2/manifests/special-resource-operator.clusterserviceversion.yaml, operators/special-resource-operator/4.9.0/manifests/special-resource-operator.clusterserviceversion.yaml
Backport of https://github.com/openshift-psap/special-resource-operator/pull/141
=> operators [R] special-resource-operator (4.8.1 4.8.2 4.9.0)

operators/volume-expander-operator/0.3.1/Dockerfile, operators/volume-expander-operator/0.3.1/manifests/volume-expander-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/volume-expander-operator/0.3.1/manifests/volume-expander-operator-controller-manager-metrics_v1_service.yaml, operators/volume-expander-operator/0.3.1/manifests/volume-expander-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/volume-expander-operator/0.3.1/manifests/volume-expander-operator.clusterserviceversion.yaml, operators/volume-expander-operator/0.3.1/metadata/annotations.yaml, operators/volume-expander-operator/0.3.1/tests/scorecard/config.yaml
=> operators volume-expander-operator (0.3.1)

operators/namespace-configuration-operator/1.2.1/Dockerfile, operators/namespace-configuration-operator/1.2.1/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.2.1/manifests/namespace-configuration-operator-controller-manager-metrics_v1_service.yaml, operators/namespace-configuration-operator/1.2.1/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.2.1/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.2.1/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.2.1/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.2.1/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.2.1/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.2.1/metadata/annotations.yaml, operators/namespace-configuration-operator/1.2.1/tests/scorecard/config.yaml
=> operators namespace-configuration-operator (1.2.1)

operators/egressip-ipam-operator/1.2.1/Dockerfile, operators/egressip-ipam-operator/1.2.1/manifests/egressip-ipam-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/egressip-ipam-operator/1.2.1/manifests/egressip-ipam-operator-controller-manager-metrics_v1_service.yaml, operators/egressip-ipam-operator/1.2.1/manifests/egressip-ipam-operator-manager-config_v1_configmap.yaml, operators/egressip-ipam-operator/1.2.1/manifests/egressip-ipam-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/egressip-ipam-operator/1.2.1/manifests/egressip-ipam-operator.clusterserviceversion.yaml, operators/egressip-ipam-operator/1.2.1/manifests/redhatcop.redhat.io_egressipams.yaml, operators/egressip-ipam-operator/1.2.1/metadata/annotations.yaml, operators/egressip-ipam-operator/1.2.1/tests/scorecard/config.yaml
=> operators egressip-ipam-operator (1.2.1)

operators/cert-utils-operator/1.3.1/Dockerfile, operators/cert-utils-operator/1.3.1/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.1/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.3.1/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.1/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.1/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.1/metadata/annotations.yaml, operators/cert-utils-operator/1.3.1/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.1)

operators/ack-s3-controller/0.0.7/bundle.Dockerfile, operators/ack-s3-controller/0.0.7/manifests/ack-s3-controller.clusterserviceversion.yaml, operators/ack-s3-controller/0.0.7/manifests/ack-s3-metrics-service_v1_service.yaml, operators/ack-s3-controller/0.0.7/manifests/ack-s3-reader_rbac.authorization.k8s.io_v1_role.yaml, operators/ack-s3-controller/0.0.7/manifests/ack-s3-writer_rbac.authorization.k8s.io_v1_role.yaml, operators/ack-s3-controller/0.0.7/manifests/s3.services.k8s.aws_buckets.yaml, operators/ack-s3-controller/0.0.7/metadata/annotations.yaml, operators/ack-s3-controller/0.0.7/tests/scorecard/config.yaml, operators/ack-s3-controller/ci.yaml
=> operators [N] [CI] ack-s3-controller (0.0.7)

operators/pcc-operator/0.2.0/bundle.Dockerfile, operators/pcc-operator/0.2.0/manifests/consoledefenders.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.2.0/manifests/consoles.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.2.0/manifests/defenders.pcc.paloaltonetworks.com.crd.yaml, operators/pcc-operator/0.2.0/manifests/pcc-operator.v0.2.0.clusterserviceversion.yaml, operators/pcc-operator/0.2.0/metadata/annotations.yaml, operators/pcc-operator/0.2.0/tests/scorecard/config.yaml
Signed-off-by: Wyatt Gill <wgill@paloaltonetworks.com>
--
=> operators pcc-operator (0.2.0)

operators/camel-k/1.7.0/builds.camel.apache.org.crd.yaml, operators/camel-k/1.7.0/camel-k.v1.7.0.clusterserviceversion.yaml, operators/camel-k/1.7.0/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.7.0/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.7.0/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.7.0/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.7.0/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.7.0/kamelets.camel.apache.org.crd.yaml, operators/camel-k/camel-k.package.yaml
Signed-off-by: nicolaferraro <ni.ferraro@gmail.com>
--
=> operators camel-k (1.7.0)

operators/tackle-operator/1.1.0/Dockerfile, operators/tackle-operator/1.1.0/manifests/tackle-operator.v1.1.0.clusterserviceversion.yaml, operators/tackle-operator/1.1.0/manifests/tackle.crd.yaml, operators/tackle-operator/1.1.0/metadata/annotations.yaml
=> operators tackle-operator (1.1.0)

operators/snyk-operator/1.72.0/snyk-operator.v1.72.0.clusterserviceversion.yaml, operators/snyk-operator/1.72.0/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.72.0)

operators/vault-config-operator/0.1.1/Dockerfile, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_authenginemounts.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_databasesecretengineconfigs.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_databasesecretengineroles.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_kubernetesauthengineroles.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_passwordpolicies.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_policies.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_randomsecrets.yaml, operators/vault-config-operator/0.1.1/manifests/redhatcop.redhat.io_secretenginemounts.yaml, operators/vault-config-operator/0.1.1/manifests/vault-config-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/vault-config-operator/0.1.1/manifests/vault-config-operator-controller-manager-metrics-service_v1_service.yaml, operators/vault-config-operator/0.1.1/manifests/vault-config-operator-manager-config_v1_configmap.yaml, operators/vault-config-operator/0.1.1/manifests/vault-config-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/vault-config-operator/0.1.1/manifests/vault-config-operator-webhook-service_v1_service.yaml, operators/vault-config-operator/0.1.1/manifests/vault-config-operator.clusterserviceversion.yaml, operators/vault-config-operator/0.1.1/metadata/annotations.yaml, operators/vault-config-operator/0.1.1/tests/scorecard/config.yaml
=> operators vault-config-operator (0.1.1)

operators/datadog-operator/0.7.2/datadog-operator.clusterserviceversion.yaml, operators/datadog-operator/0.7.2/datadoghq.com_datadogagents.yaml, operators/datadog-operator/0.7.2/datadoghq.com_datadogmetrics.yaml, operators/datadog-operator/0.7.2/datadoghq.com_datadogmonitors.yaml, operators/datadog-operator/datadog-operator.package.yaml
Signed-off-by: Vincent Boulineau <vincent.boulineau@datadoghq.com>
--
=> operators datadog-operator (0.7.2)

operators/kubernetes-imagepuller-operator/0.1.0/che.eclipse.org_kubernetesimagepullers_crd.yaml, operators/kubernetes-imagepuller-operator/0.1.0/controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/kubernetes-imagepuller-operator/0.1.0/controller-manager-metrics-service_v1_service.yaml, operators/kubernetes-imagepuller-operator/0.1.0/kubernetes-image-puller-operator_v1_serviceaccount.yaml, operators/kubernetes-imagepuller-operator/0.1.0/kubernetes-imagepuller-operator.v0.1.0.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/0.1.0/manager-config_v1_configmap.yaml, operators/kubernetes-imagepuller-operator/0.1.0/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubernetes-imagepuller-operator/ci.yaml, operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
--
=> kubernetes-imagepuller-operator (0.1.0)

operators/victoriametrics-operator/0.20.1/victoriametrics-operator.0.20.1.clusterserviceversion.yaml
Backport of https://github.com/VictoriaMetrics/operator/pull/382
=> operators [O] victoriametrics-operator (0.20.1)

operators/snyk-operator/1.73.0/snyk-operator.v1.73.0.clusterserviceversion.yaml, operators/snyk-operator/1.73.0/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.73.0)

operators/portworx-essentials/1.6.1/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.6.1/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.6.1/portworxoperator.v1.6.1.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operators portworx-essentials (1.6.1)

operators/rhoas-operator/0.9.3/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.9.3/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.9.3/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.9.3/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.9.3/manifests/rhoas-operator.serviceregistryconnections.crd.yaml, operators/rhoas-operator/0.9.3/manifests/service-binding.clusterrole.yaml, operators/rhoas-operator/0.9.3/metadata/annotations.yaml
=> operators rhoas-operator (0.9.3)

operators/multicluster-operators-subscription/0.3.7/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.7/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.7/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.7/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.7/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.7/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.7/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.7/multicluster-operators-subscription.v0.3.7.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators multicluster-operators-subscription (0.3.7)

operators/oadp-operator/0.5.0/manifests/dpa-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.0/manifests/dpa-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.0/manifests/oadp-operator.clusterserviceversion.yaml, operators/oadp-operator/0.5.0/manifests/oadp.openshift.io_cloudstorages.yaml, operators/oadp-operator/0.5.0/manifests/oadp.openshift.io_dataprotectionapplications.yaml, operators/oadp-operator/0.5.0/manifests/openshift-adp-controller-manager-metrics-service_v1_service.yaml, operators/oadp-operator/0.5.0/manifests/openshift-adp-manager-config_v1_configmap.yaml, operators/oadp-operator/0.5.0/manifests/openshift-adp-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.0/manifests/velero-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.0/manifests/velero-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_backups.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_backupstoragelocations.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_deletebackuprequests.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_downloadrequests.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_podvolumebackups.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_podvolumerestores.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_resticrepositories.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_restores.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_schedules.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_serverstatusrequests.yaml, operators/oadp-operator/0.5.0/manifests/velero.io_volumesnapshotlocations.yaml, operators/oadp-operator/0.5.0/manifests/velero_v1_serviceaccount.yaml, operators/oadp-operator/0.5.0/metadata/annotations.yaml
=> operators oadp-operator (0.5.0)

operators/argocd-operator/0.1.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml, operators/argocd-operator/0.1.0/argocd-operator-manager-config_v1_configmap.yaml, operators/argocd-operator/0.1.0/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/argocd-operator/0.1.0/argocd-operator.v0.1.0.clusterserviceversion.yaml, operators/argocd-operator/0.1.0/argoproj.io_applications.yaml, operators/argocd-operator/0.1.0/argoproj.io_applicationsets.yaml, operators/argocd-operator/0.1.0/argoproj.io_appprojects.yaml, operators/argocd-operator/0.1.0/argoproj.io_argocdexports.yaml, operators/argocd-operator/0.1.0/argoproj.io_argocds.yaml, operators/argocd-operator/argocd-operator.package.yaml, operators/argocd-operator/ci.yaml
Signed-off-by: John Pitman <jpitman@redhat.com>
--
=> operators [CI] argocd-operator (0.1.0)

operators/keda/2.5.0/manifests/keda.sh_clustertriggerauthentications.yaml, operators/keda/2.5.0/manifests/keda.sh_kedacontrollers.yaml, operators/keda/2.5.0/manifests/keda.sh_scaledjobs.yaml, operators/keda/2.5.0/manifests/keda.sh_scaledobjects.yaml, operators/keda/2.5.0/manifests/keda.sh_triggerauthentications.yaml, operators/keda/2.5.0/manifests/keda.v2.5.0.clusterserviceversion.yaml, operators/keda/2.5.0/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
=> operators keda (2.5.0)

operators/grafana-operator/4.0.2/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.0.2/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.0.2/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.0.2/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.0.2/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.0.2/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.0.2/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.0.2/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operators grafana-operator (4.0.2)

operators/vault-config-operator/0.1.2/Dockerfile, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_authenginemounts.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_databasesecretengineconfigs.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_databasesecretengineroles.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_kubernetesauthengineroles.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_passwordpolicies.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_policies.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_randomsecrets.yaml, operators/vault-config-operator/0.1.2/manifests/redhatcop.redhat.io_secretenginemounts.yaml, operators/vault-config-operator/0.1.2/manifests/vault-config-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/vault-config-operator/0.1.2/manifests/vault-config-operator-controller-manager-metrics-service_v1_service.yaml, operators/vault-config-operator/0.1.2/manifests/vault-config-operator-manager-config_v1_configmap.yaml, operators/vault-config-operator/0.1.2/manifests/vault-config-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/vault-config-operator/0.1.2/manifests/vault-config-operator-webhook-service_v1_service.yaml, operators/vault-config-operator/0.1.2/manifests/vault-config-operator.clusterserviceversion.yaml, operators/vault-config-operator/0.1.2/metadata/annotations.yaml, operators/vault-config-operator/0.1.2/tests/scorecard/config.yaml
=> operators vault-config-operator (0.1.2)

operators/ember-csi-community-operator/0.9.7/ember-csi-operator.crd.yaml, operators/ember-csi-community-operator/0.9.7/ember-csi-operator.v0.9.7.clusterserviceversion.yaml, operators/ember-csi-community-operator/ember-csi-community-operator.package.yaml
=> operators ember-csi-community-operator (0.9.7)

operators/resource-locker-operator/1.1.2/Dockerfile, operators/resource-locker-operator/1.1.2/manifests/redhatcop.redhat.io_resourcelockers.yaml, operators/resource-locker-operator/1.1.2/manifests/resource-locker-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/resource-locker-operator/1.1.2/manifests/resource-locker-operator-controller-manager-metrics_v1_service.yaml, operators/resource-locker-operator/1.1.2/manifests/resource-locker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/resource-locker-operator/1.1.2/manifests/resource-locker-operator.clusterserviceversion.yaml, operators/resource-locker-operator/1.1.2/metadata/annotations.yaml, operators/resource-locker-operator/1.1.2/tests/scorecard/config.yaml
=> operators resource-locker-operator (1.1.2)

operators/ember-csi-community-operator/0.9.8/ember-csi-operator.crd.yaml, operators/ember-csi-community-operator/0.9.8/ember-csi-operator.v0.9.8.clusterserviceversion.yaml, operators/ember-csi-community-operator/ember-csi-community-operator.package.yaml
=> operators ember-csi-community-operator (0.9.8)

operators/ack-apigatewayv2-controller/ci.yaml, operators/ack-dynamodb-controller/ci.yaml, operators/ack-ecr-controller/ci.yaml, operators/ack-elasticache-controller/ci.yaml, operators/ack-mq-controller/ci.yaml, operators/ack-opensearchservice-controller/ci.yaml, operators/ack-rds-controller/ci.yaml, operators/ack-sagemaker-controller/ci.yaml
=> operators [CI] ack-apigatewayv2-controller

operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.21.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.21.0/victoriametrics-operator.0.21.0.clusterserviceversion.yaml, operators/victoriametrics-operator/0.21.0/vm-operator-vm-operator_v1_serviceaccount.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.21.0)

operators/resource-locker-operator/1.1.3/Dockerfile, operators/resource-locker-operator/1.1.3/manifests/redhatcop.redhat.io_resourcelockers.yaml, operators/resource-locker-operator/1.1.3/manifests/resource-locker-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/resource-locker-operator/1.1.3/manifests/resource-locker-operator-controller-manager-metrics_v1_service.yaml, operators/resource-locker-operator/1.1.3/manifests/resource-locker-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/resource-locker-operator/1.1.3/manifests/resource-locker-operator.clusterserviceversion.yaml, operators/resource-locker-operator/1.1.3/metadata/annotations.yaml, operators/resource-locker-operator/1.1.3/tests/scorecard/config.yaml
=> operators resource-locker-operator (1.1.3)

operators/flux/0.24.0/manifests/alert.crd.yaml, operators/flux/0.24.0/manifests/bucket.crd.yaml, operators/flux/0.24.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.24.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.24.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.24.0/manifests/flux.v0.24.0.clusterserviceversion.yaml, operators/flux/0.24.0/manifests/gitrepository.crd.yaml, operators/flux/0.24.0/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.24.0/manifests/helmchart.crd.yaml, operators/flux/0.24.0/manifests/helmrelease.crd.yaml, operators/flux/0.24.0/manifests/helmrepository.crd.yaml, operators/flux/0.24.0/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.24.0/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.24.0/manifests/imagepolicy.crd.yaml, operators/flux/0.24.0/manifests/imagerepository.crd.yaml, operators/flux/0.24.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.24.0/manifests/kustomization.crd.yaml, operators/flux/0.24.0/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.24.0/manifests/notification-controller.service.yaml, operators/flux/0.24.0/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.24.0/manifests/provider.crd.yaml, operators/flux/0.24.0/manifests/receiver.crd.yaml, operators/flux/0.24.0/manifests/source-controller.service.yaml, operators/flux/0.24.0/manifests/source-controller.serviceaccount.yaml, operators/flux/0.24.0/manifests/webhook-receiver.service.yaml, operators/flux/0.24.0/metadata/annotations.yaml
=> operators flux (0.24.0)

operators/kubeturbo/8.3.3/kubeturbo-operator.v8.3.3.clusterserviceversion.yaml
=> operators [O] kubeturbo (8.3.3)

operators/grafana-operator/4.1.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.1.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.1.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.1.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.1.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.1.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.1.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.1.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operators grafana-operator (4.1.0)

operators/oadp-operator/0.5.1/manifests/dpa-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.1/manifests/dpa-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.1/manifests/oadp-operator.clusterserviceversion.yaml, operators/oadp-operator/0.5.1/manifests/oadp.openshift.io_cloudstorages.yaml, operators/oadp-operator/0.5.1/manifests/oadp.openshift.io_dataprotectionapplications.yaml, operators/oadp-operator/0.5.1/manifests/openshift-adp-controller-manager-metrics-service_v1_service.yaml, operators/oadp-operator/0.5.1/manifests/openshift-adp-manager-config_v1_configmap.yaml, operators/oadp-operator/0.5.1/manifests/openshift-adp-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_backups.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_backupstoragelocations.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_deletebackuprequests.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_downloadrequests.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_podvolumebackups.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_podvolumerestores.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_resticrepositories.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_restores.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_schedules.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_serverstatusrequests.yaml, operators/oadp-operator/0.5.1/manifests/velero.io_volumesnapshotlocations.yaml, operators/oadp-operator/0.5.1/metadata/annotations.yaml
=> operators oadp-operator (0.5.1)

operators/postgresql/5.0.2/metadata/annotations.yaml, operators/postgresql/5.0.3/metadata/annotations.yaml, operators/postgresql/5.0.4/metadata/annotations.yaml
=> operators [R] postgresql (5.0.2 5.0.3 5.0.4)

operators/cert-utils-operator/1.3.2/Dockerfile, operators/cert-utils-operator/1.3.2/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.2/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.3.2/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.2/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.2/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.2/metadata/annotations.yaml, operators/cert-utils-operator/1.3.2/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.2)

operators/namespace-configuration-operator/1.2.2/Dockerfile, operators/namespace-configuration-operator/1.2.2/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.2.2/manifests/namespace-configuration-operator-controller-manager-metrics_v1_service.yaml, operators/namespace-configuration-operator/1.2.2/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.2.2/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.2.2/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.2.2/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.2.2/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.2.2/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.2.2/metadata/annotations.yaml, operators/namespace-configuration-operator/1.2.2/tests/scorecard/config.yaml
=> operators namespace-configuration-operator (1.2.2)

operators/egressip-ipam-operator/1.2.2/Dockerfile, operators/egressip-ipam-operator/1.2.2/manifests/egressip-ipam-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/egressip-ipam-operator/1.2.2/manifests/egressip-ipam-operator-controller-manager-metrics_v1_service.yaml, operators/egressip-ipam-operator/1.2.2/manifests/egressip-ipam-operator-manager-config_v1_configmap.yaml, operators/egressip-ipam-operator/1.2.2/manifests/egressip-ipam-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/egressip-ipam-operator/1.2.2/manifests/egressip-ipam-operator.clusterserviceversion.yaml, operators/egressip-ipam-operator/1.2.2/manifests/redhatcop.redhat.io_egressipams.yaml, operators/egressip-ipam-operator/1.2.2/metadata/annotations.yaml, operators/egressip-ipam-operator/1.2.2/tests/scorecard/config.yaml
=> operators egressip-ipam-operator (1.2.2)

operators/volume-expander-operator/0.3.2/Dockerfile, operators/volume-expander-operator/0.3.2/manifests/volume-expander-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/volume-expander-operator/0.3.2/manifests/volume-expander-operator-controller-manager-metrics_v1_service.yaml, operators/volume-expander-operator/0.3.2/manifests/volume-expander-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/volume-expander-operator/0.3.2/manifests/volume-expander-operator.clusterserviceversion.yaml, operators/volume-expander-operator/0.3.2/metadata/annotations.yaml, operators/volume-expander-operator/0.3.2/tests/scorecard/config.yaml
=> operators volume-expander-operator (0.3.2)

operators/dell-csi-operator/1.6.0/csiisilons.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.6.0/csipowermaxes.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.6.0/csipowermaxrevproxies.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.6.0/csipowerstores.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.6.0/csiunities.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.6.0/csivxflexoses.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.6.0/dell-csi-operator.v1.6.0.clusterserviceversion.yaml, operators/dell-csi-operator/dell-csi-operator.package.yaml
=> operators dell-csi-operator (1.6.0)

operators/kiali/1.44.0/bundle.Dockerfile, operators/kiali/1.44.0/manifests/kiali.crd.yaml, operators/kiali/1.44.0/manifests/kiali.v1.44.0.clusterserviceversion.yaml, operators/kiali/1.44.0/metadata/annotations.yaml
=> operators kiali (1.44.0)

operators/pulp-operator/0.6.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.6.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.6.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.6.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.6.0/manifests/pulp-operator.v0.6.0.clusterserviceversion.yaml, operators/pulp-operator/0.6.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.6.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.6.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.6.0/metadata/annotations.yaml, operators/pulp-operator/0.6.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.6.0)

operators/community-windows-machine-config-operator/3.1.1/manifests/community-windows-machine-config-operator.3.1.1.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/3.1.1/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/3.1.1/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/3.1.1/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/3.1.1/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/3.1.1/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/3.1.1/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/3.1.1/metadata/annotations.yaml
=> operators community-windows-machine-config-operator (3.1.1)

operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.40.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.40.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.40.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.40.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.40.0/tests/scorecard/config.yaml
Signed-off-by: Yuri Sa <ysa@redhat.com>
--
=> operators opentelemetry-operator (0.40.0)

operators/pulp-operator/0.6.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.6.1/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.6.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.6.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.6.1/manifests/pulp-operator.v0.6.1.clusterserviceversion.yaml, operators/pulp-operator/0.6.1/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.6.1/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.6.1/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.6.1/metadata/annotations.yaml, operators/pulp-operator/0.6.1/tests/scorecard/config.yaml
=> operators pulp-operator (0.6.1)

operators/koku-metrics-operator/1.1.1/Dockerfile, operators/koku-metrics-operator/1.1.1/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.1/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.1/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.1/tests/scorecard/config.yaml
=> operators koku-metrics-operator (1.1.1)

operators/ibm-spectrum-scale-csi-operator/2.4.0/csiscaleoperators.csi.ibm.com.crd.yaml, operators/ibm-spectrum-scale-csi-operator/2.4.0/ibm-spectrum-scale-csi-operator.v2.4.0.clusterserviceversion.yaml, operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
=> operators ibm-spectrum-scale-csi-operator (2.4.0)

operators/rhoas-operator/0.9.5/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.9.5/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.9.5/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.9.5/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.9.5/manifests/rhoas-operator.serviceregistryconnections.crd.yaml, operators/rhoas-operator/0.9.5/manifests/service-binding.clusterrole.yaml, operators/rhoas-operator/0.9.5/metadata/annotations.yaml
=> operators rhoas-operator (0.9.5)

operators/flux/0.24.1/manifests/alert.crd.yaml, operators/flux/0.24.1/manifests/bucket.crd.yaml, operators/flux/0.24.1/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.24.1/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.24.1/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.24.1/manifests/flux.v0.24.1.clusterserviceversion.yaml, operators/flux/0.24.1/manifests/gitrepository.crd.yaml, operators/flux/0.24.1/manifests/helm-controller.serviceaccount.yaml, operators/flux/0.24.1/manifests/helmchart.crd.yaml, operators/flux/0.24.1/manifests/helmrelease.crd.yaml, operators/flux/0.24.1/manifests/helmrepository.crd.yaml, operators/flux/0.24.1/manifests/image-automation-controller.serviceaccount.yaml, operators/flux/0.24.1/manifests/image-reflector-controller.serviceaccount.yaml, operators/flux/0.24.1/manifests/imagepolicy.crd.yaml, operators/flux/0.24.1/manifests/imagerepository.crd.yaml, operators/flux/0.24.1/manifests/imageupdateautomation.crd.yaml, operators/flux/0.24.1/manifests/kustomization.crd.yaml, operators/flux/0.24.1/manifests/kustomize-controller.serviceaccount.yaml, operators/flux/0.24.1/manifests/notification-controller.service.yaml, operators/flux/0.24.1/manifests/notification-controller.serviceaccount.yaml, operators/flux/0.24.1/manifests/provider.crd.yaml, operators/flux/0.24.1/manifests/receiver.crd.yaml, operators/flux/0.24.1/manifests/source-controller.service.yaml, operators/flux/0.24.1/manifests/source-controller.serviceaccount.yaml, operators/flux/0.24.1/manifests/webhook-receiver.service.yaml, operators/flux/0.24.1/metadata/annotations.yaml
=> operators flux (0.24.1)

operators/ack-iam-controller/ci.yaml
=> operators [CI] ack-iam-controller

operators/keycloak-operator/15.1.0/bundle.Dockerfile, operators/keycloak-operator/15.1.0/manifests/keycloak-operator.v15.1.0.clusterserviceversion.yaml, operators/keycloak-operator/15.1.0/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.0/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.0/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.0/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.0/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.0/metadata/annotations.yaml
=> operators keycloak-operator (15.1.0)

operators/yaks/0.7.0/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.7.0/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.7.0/yaks.v0.7.0.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operators yaks (0.7.0)

operators/multicluster-operators-subscription/0.3.8/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_subscriptionreports_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.8/apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.8/multicluster-operators-subscription.v0.3.8.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators multicluster-operators-subscription (0.3.8)

operators/mta-operator/0.0.8/Dockerfile, operators/mta-operator/0.0.8/manifests/windup-operator.v0.0.8.clusterserviceversion.yaml, operators/mta-operator/0.0.8/manifests/windup.crd.yaml, operators/mta-operator/0.0.8/metadata/annotations.yaml
=> operators mta-operator (0.0.8)

operators/grafana-operator/4.1.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.1.1/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.1.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.1.1/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.1.1/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.1.1/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.1.1/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.1.1/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operators grafana-operator (4.1.1)

operators/koku-metrics-operator/1.1.2/Dockerfile, operators/koku-metrics-operator/1.1.2/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.2/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.2/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.2/tests/scorecard/config.yaml
Signed-off-by: Michael Skarbek <mskarbek@redhat.com>
--
=> operators koku-metrics-operator (1.1.2)

operators/ack-applicationautoscaling-controller/ci.yaml, operators/ack-ec2-controller/ci.yaml, operators/ack-eks-controller/ci.yaml, operators/ack-kms-controller/ci.yaml, operators/ack-lambda-controller/ci.yaml, operators/ack-sfn-controller/ci.yaml, operators/ack-sns-controller/ci.yaml, operators/ack-sqs-controller/ci.yaml
=> operators [CI] ack-applicationautoscaling-controller

operators/authorino-operator/0.0.1/bundle.Dockerfile, operators/authorino-operator/0.0.1/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml, operators/authorino-operator/0.0.1/manifests/authorino-operator-manager-config_v1_configmap.yaml, operators/authorino-operator/0.0.1/manifests/authorino-operator.clusterserviceversion.yaml, operators/authorino-operator/0.0.1/manifests/authorino.3scale.net_authconfigs.yaml, operators/authorino-operator/0.0.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml, operators/authorino-operator/0.0.1/metadata/annotations.yaml, operators/authorino-operator/0.0.1/tests/scorecard/config.yaml, operators/authorino-operator/ci.yaml
Signed-off-by: Jose Silva <jmonteir@redhat.com>
--
=> operators [N] [CI] authorino-operator (0.0.1)

operators/keycloak-operator/15.1.1/bundle.Dockerfile, operators/keycloak-operator/15.1.1/manifests/keycloak-operator.v15.1.1.clusterserviceversion.yaml, operators/keycloak-operator/15.1.1/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.1/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.1/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.1/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.1/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/15.1.1/metadata/annotations.yaml
Signed-off-by: jonathan <jvilalop@redhat.com>
--
=> operators keycloak-operator (15.1.1)

operators/snapscheduler/2.1.0/bundle.Dockerfile, operators/snapscheduler/2.1.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml, operators/snapscheduler/2.1.0/manifests/snapscheduler-manager-config_v1_configmap.yaml, operators/snapscheduler/2.1.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/snapscheduler/2.1.0/manifests/snapscheduler.backube_snapshotschedules.yaml, operators/snapscheduler/2.1.0/manifests/snapscheduler.clusterserviceversion.yaml, operators/snapscheduler/2.1.0/metadata/annotations.yaml, operators/snapscheduler/2.1.0/tests/scorecard/config.yaml
=> operators snapscheduler (2.1.0)

operators/crane-operator/1.4.3/manifests/crane-operator.v1.4.3.clusterserviceversion.yaml, operators/crane-operator/1.4.4/manifests/crane-operator.v1.4.4.clusterserviceversion.yaml, operators/crane-operator/1.4.5/manifests/crane-operator.v1.4.5.clusterserviceversion.yaml, operators/crane-operator/1.4.6/manifests/crane-operator.v1.4.6.clusterserviceversion.yaml, operators/crane-operator/1.4.7/manifests/crane-operator.v1.4.7.clusterserviceversion.yaml, operators/crane-operator/1.6.0/manifests/crane-operator.v1.6.0.clusterserviceversion.yaml, operators/crane-operator/1.6.1/manifests/crane-operator.v1.6.1.clusterserviceversion.yaml, operators/crane-operator/1.6.2/manifests/crane-operator.v1.6.2.clusterserviceversion.yaml
=> operators [R] crane-operator (1.4.3 1.4.4 1.4.5 1.4.6 1.4.7 1.6.0 1.6.1 1.6.2)

operators/aws-efs-operator/0.0.7/aws-efs-operator.v0.0.7.clusterserviceversion.yaml, operators/aws-efs-operator/0.0.7/aws-efs.managed.openshift.io_sharedvolumes_crd.yaml, operators/aws-efs-operator/aws-efs-operator.package.yaml
=> operators aws-efs-operator (0.0.7)

operators/keycloak-operator/16.0.0/bundle.Dockerfile, operators/keycloak-operator/16.0.0/manifests/keycloak-operator.v16.0.0.clusterserviceversion.yaml, operators/keycloak-operator/16.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/16.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/16.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/16.0.0/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/16.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/16.0.0/metadata/annotations.yaml
=> operators keycloak-operator (16.0.0)

operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml, operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml, operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml, operators/beegfs-csi-driver-operator/1.2.1/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml, operators/beegfs-csi-driver-operator/1.2.1/metadata/annotations.yaml, operators/beegfs-csi-driver-operator/1.2.1/tests/scorecard/config.yaml, operators/beegfs-csi-driver-operator/ci.yaml
Signed-off-by: Eric Weber <eric.weber2@netapp.com>
--
=> operators [CI] beegfs-csi-driver-operator (1.2.1)

operators/pulp-operator/0.7.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.7.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.7.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.7.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.7.0/manifests/pulp-operator.v0.7.0.clusterserviceversion.yaml, operators/pulp-operator/0.7.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.7.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.7.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.7.0/metadata/annotations.yaml, operators/pulp-operator/0.7.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.7.0)

operators/aws-efs-operator/0.0.8/aws-efs-operator.v0.0.8.clusterserviceversion.yaml, operators/aws-efs-operator/0.0.8/aws-efs.managed.openshift.io_sharedvolumes_crd.yaml, operators/aws-efs-operator/aws-efs-operator.package.yaml
Signed-off-by: James Harrington <james@harrington.net.au>
--
=> operators aws-efs-operator (0.0.8)

operators/oadp-operator/0.5.3/manifests/dpa-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.3/manifests/dpa-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.3/manifests/oadp-operator.clusterserviceversion.yaml, operators/oadp-operator/0.5.3/manifests/oadp.openshift.io_cloudstorages.yaml, operators/oadp-operator/0.5.3/manifests/oadp.openshift.io_dataprotectionapplications.yaml, operators/oadp-operator/0.5.3/manifests/openshift-adp-controller-manager-metrics-service_v1_service.yaml, operators/oadp-operator/0.5.3/manifests/openshift-adp-manager-config_v1_configmap.yaml, operators/oadp-operator/0.5.3/manifests/openshift-adp-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_backups.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_backupstoragelocations.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_deletebackuprequests.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_downloadrequests.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_podvolumebackups.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_podvolumerestores.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_resticrepositories.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_restores.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_schedules.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_serverstatusrequests.yaml, operators/oadp-operator/0.5.3/manifests/velero.io_volumesnapshotlocations.yaml, operators/oadp-operator/0.5.3/metadata/annotations.yaml
Signed-off-by: dymurray <dymurray@redhat.com>
--
=> operators oadp-operator (0.5.3)

operators/neuvector-community-operator/1.3.0/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.0/neuvector-operator.v1.3.0.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
* [x ] Have you tested your Operator with all Custom Resource Definitions?
--
=> operators neuvector-community-operator (1.3.0)

operators/aws-efs-operator/0.0.6/aws-efs-operator.v0.0.6.clusterserviceversion.yaml
* [x Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
--
<sup>2</sup> For more …
=> operators [O] aws-efs-operator (0.0.6)

operators/patch-operator/0.0.1/Dockerfile, operators/patch-operator/0.0.1/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.0.1/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.0.1/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.0.1/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.0.1/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.0.1/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.0.1/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.0.1/metadata/annotations.yaml, operators/patch-operator/0.0.1/tests/scorecard/config.yaml, operators/patch-operator/ci.yaml
=> operators [N] [CI] patch-operator (0.0.1)

operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.41.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.41.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.41.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.41.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.41.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.41.0)

operators/patch-operator/0.1.0/Dockerfile, operators/patch-operator/0.1.0/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.0/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.0/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.0/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.0/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.0/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.0/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.0/metadata/annotations.yaml, operators/patch-operator/0.1.0/tests/scorecard/config.yaml
=> operators patch-operator (0.1.0)

operators/keycloak-operator/16.1.0/bundle.Dockerfile, operators/keycloak-operator/16.1.0/manifests/keycloak-operator.v16.1.0.clusterserviceversion.yaml, operators/keycloak-operator/16.1.0/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/16.1.0/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/16.1.0/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/16.1.0/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/16.1.0/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/16.1.0/metadata/annotations.yaml
Signed-off-by: jonathan <jvilalop@redhat.com>
--
=> operators keycloak-operator (16.1.0)

operators/external-secrets-operator/0.3.10/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.3.10/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.3.10/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.3.10/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.3.10/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.3.10/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.3.10/metadata/annotations.yaml, operators/external-secrets-operator/0.3.10/tests/scorecard/config.yaml, operators/external-secrets-operator/0.3.8/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.3.8/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.3.8/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.3.8/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.3.8/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.3.8/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.3.8/metadata/annotations.yaml, operators/external-secrets-operator/0.3.8/tests/scorecard/config.yaml, operators/external-secrets-operator/0.3.9/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.3.9/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.3.9/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.3.9/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.3.9/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.3.9/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.3.9/metadata/annotations.yaml, operators/external-secrets-operator/0.3.9/tests/scorecard/config.yaml, operators/external-secrets-operator/ci.yaml
I'm not sure if i can add multiple versions at once, i hope it passes CI. 
related issue in the operator repository: https://github.com/external-secrets/external-secrets/issues/493
--
=> operators [R] [CI] external-secrets-operator (0.3.10 0.3.8 0.3.9)

operators/grafana-operator/ci.yaml
=> operators [CI] grafana-operator

operators/external-secrets-operator/0.3.11/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.3.11/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.3.11/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.3.11/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.3.11/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.3.11/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.3.11/metadata/annotations.yaml, operators/external-secrets-operator/0.3.11/tests/scorecard/config.yaml
This PR contains the latest version of external-secrets v0.3.11.
=> operators external-secrets-operator (0.3.11)

operators/verticadb-operator/1.2.0/Dockerfile, operators/verticadb-operator/1.2.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.2.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.2.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.2.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.2.0/metadata/annotations.yaml, operators/verticadb-operator/1.2.0/tests/scorecard/config.yaml, operators/verticadb-operator/ci.yaml
Signed-off-by: Roy Paulin Nguetsop <roy.paulin@microfocus.com>
--
=> operators [N] [CI] verticadb-operator (1.2.0)

operators/oadp-operator/0.5.4/manifests/dpa-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.4/manifests/dpa-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.4/manifests/oadp-operator.clusterserviceversion.yaml, operators/oadp-operator/0.5.4/manifests/oadp.openshift.io_cloudstorages.yaml, operators/oadp-operator/0.5.4/manifests/oadp.openshift.io_dataprotectionapplications.yaml, operators/oadp-operator/0.5.4/manifests/openshift-adp-controller-manager-metrics-service_v1_service.yaml, operators/oadp-operator/0.5.4/manifests/openshift-adp-manager-config_v1_configmap.yaml, operators/oadp-operator/0.5.4/manifests/openshift-adp-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_backups.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_backupstoragelocations.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_deletebackuprequests.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_downloadrequests.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_podvolumebackups.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_podvolumerestores.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_resticrepositories.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_restores.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_schedules.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_serverstatusrequests.yaml, operators/oadp-operator/0.5.4/manifests/velero.io_volumesnapshotlocations.yaml, operators/oadp-operator/0.5.4/metadata/annotations.yaml
=> operators oadp-operator (0.5.4)

operators/postgresql/ci.yaml
=> operators [CI] postgresql

operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.22.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.22.0/victoriametrics-operator.0.22.0.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.22.0)

operators/silicom-sts-operator/0.0.1/bundle.Dockerfile, operators/silicom-sts-operator/0.0.1/manifests/silicom-sts-operator.clusterserviceversion.yaml, operators/silicom-sts-operator/0.0.1/manifests/sts-controller-manager-metrics-service_v1_service.yaml, operators/silicom-sts-operator/0.0.1/manifests/sts-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/silicom-sts-operator/0.0.1/manifests/sts.silicom.com_stsconfigs.yaml, operators/silicom-sts-operator/0.0.1/manifests/sts.silicom.com_stsnodes.yaml, operators/silicom-sts-operator/0.0.1/manifests/sts.silicom.com_stsoperatorconfigs.yaml, operators/silicom-sts-operator/0.0.1/metadata/annotations.yaml, operators/silicom-sts-operator/0.0.1/metadata/dependencies.yaml, operators/silicom-sts-operator/0.0.1/tests/scorecard/config.yaml, operators/silicom-sts-operator/ci.yaml
=> operators [N] [CI] silicom-sts-operator (0.0.1)

operators/syndesis/1.13.0/Dockerfile, operators/syndesis/1.13.0/manifests/syndesis-auth-delegator_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/syndesis/1.13.0/manifests/syndesis-server-kafka_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/syndesis/1.13.0/manifests/syndesis.clusterserviceversion.yaml, operators/syndesis/1.13.0/manifests/syndesis.io_syndesises.yaml, operators/syndesis/1.13.0/metadata/annotations.yaml, operators/syndesis/1.13.0/tests/scorecard/config.yaml
=> operators syndesis (1.13.0)

operators/eclipse-che/7.42.0/manifests/eclipse-che.v7.42.0.clusterserviceversion.yaml
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
Update CheCluster sample by adding `spec.devWorkspace.enable: true`
--
=> operators [O] eclipse-che (7.42.0)

operators/gitops-primer/0.0.2/manifests/gitops-primer.clusterserviceversion.yaml
=> operators [O] gitops-primer (0.0.2)

operators/oadp-operator/0.5.5/manifests/dpa-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.5/manifests/dpa-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.5/manifests/oadp-operator.clusterserviceversion.yaml, operators/oadp-operator/0.5.5/manifests/oadp.openshift.io_cloudstorages.yaml, operators/oadp-operator/0.5.5/manifests/oadp.openshift.io_dataprotectionapplications.yaml, operators/oadp-operator/0.5.5/manifests/openshift-adp-controller-manager-metrics-service_v1_service.yaml, operators/oadp-operator/0.5.5/manifests/openshift-adp-manager-config_v1_configmap.yaml, operators/oadp-operator/0.5.5/manifests/openshift-adp-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_backups.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_backupstoragelocations.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_deletebackuprequests.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_downloadrequests.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_podvolumebackups.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_podvolumerestores.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_resticrepositories.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_restores.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_schedules.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_serverstatusrequests.yaml, operators/oadp-operator/0.5.5/manifests/velero.io_volumesnapshotlocations.yaml, operators/oadp-operator/0.5.5/metadata/annotations.yaml
Signed-off-by: dymurray <dymurray@redhat.com>
--
=> operators oadp-operator (0.5.5)

operators/microcks/1.5.0/microcks-operator.v1.5.0.clusterserviceversion.yaml, operators/microcks/1.5.0/microcksinstall.crd.yaml, operators/microcks/microcks.package.yaml
=> operators microcks (1.5.0)

operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.42.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.42.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.42.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.42.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.42.0/tests/scorecard/config.yaml
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
This is basically a copy of https://github.com/open-telemetry/opentelemetry-operator/tree/v0.42.0/bundle
* [] Have you tested your Operator with all Custom Resource Definitions?
-- …
=> operators opentelemetry-operator (0.42.0)

operators/snyk-operator/1.80.0/snyk-operator.v1.80.0.clusterserviceversion.yaml, operators/snyk-operator/1.80.0/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.80.0)

operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_hooks.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_hosts.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_migrations.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_networkmaps.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_plans.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_providers.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_provisioners.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/forklift.konveyor.io_storagemaps.yaml, operators/konveyor-forklift-operator/2.2.0/manifests/konveyor-forklift-operator.v2.2.0.clusterserviceversion.yaml, operators/konveyor-forklift-operator/2.2.0/metadata/annotations.yaml
=> operators konveyor-forklift-operator (2.2.0)

operators/flux/0.25.2/manifests/alert.crd.yaml, operators/flux/0.25.2/manifests/bucket.crd.yaml, operators/flux/0.25.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.25.2/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.25.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.25.2/manifests/flux.v0.25.2.clusterserviceversion.yaml, operators/flux/0.25.2/manifests/gitrepository.crd.yaml, operators/flux/0.25.2/manifests/helmchart.crd.yaml, operators/flux/0.25.2/manifests/helmrelease.crd.yaml, operators/flux/0.25.2/manifests/helmrepository.crd.yaml, operators/flux/0.25.2/manifests/imagepolicy.crd.yaml, operators/flux/0.25.2/manifests/imagerepository.crd.yaml, operators/flux/0.25.2/manifests/imageupdateautomation.crd.yaml, operators/flux/0.25.2/manifests/kustomization.crd.yaml, operators/flux/0.25.2/manifests/notification-controller.service.yaml, operators/flux/0.25.2/manifests/provider.crd.yaml, operators/flux/0.25.2/manifests/receiver.crd.yaml, operators/flux/0.25.2/manifests/source-controller.service.yaml, operators/flux/0.25.2/manifests/webhook-receiver.service.yaml, operators/flux/0.25.2/metadata/annotations.yaml
=> operators flux (0.25.2)

operators/yaks/0.8.0/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.8.0/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.8.0/yaks.v0.8.0.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operators yaks (0.8.0)

operators/koku-metrics-operator/1.1.3/Dockerfile, operators/koku-metrics-operator/1.1.3/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.3/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.3/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.3/tests/scorecard/config.yaml
Signed-off-by: Michael Skarbek <mskarbek@redhat.com>
--
=> operators koku-metrics-operator (1.1.3)

operators/gitops-primer/0.0.3/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.3/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.3/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.3/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.3/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.3/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.3/metadata/annotations.yaml, operators/gitops-primer/0.0.3/tests/scorecard/config.yaml
* [] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [] Have you tested your Operator with all Custom Resource Definitions?
* [] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [] Have you considered whether you want use [semantic versioning …
=> operators gitops-primer (0.0.3)

operators/ember-csi-community-operator/0.9.9/ember-csi-operator.crd.yaml, operators/ember-csi-community-operator/0.9.9/ember-csi-operator.v0.9.9.clusterserviceversion.yaml, operators/ember-csi-community-operator/ember-csi-community-operator.package.yaml
=> operators ember-csi-community-operator (0.9.9)

operators/percona-server-mongodb-operator/1.11.0/percona-server-mongodb-operator.v1.11.0.clusterserviceversion.yaml, operators/percona-server-mongodb-operator/1.11.0/perconaservermongodbbackups.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.11.0/perconaservermongodbrestores.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.11.0/perconaservermongodbs.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/percona-server-mongodb-operator.package.yaml
Signed-off-by: cap1984 <ivan.pylypenko@percona.com>
--
=> operators percona-server-mongodb-operator (1.11.0)

operators/percona-xtradb-cluster-operator/1.10.0/percona-xtradb-cluster-operator.v1.10.0.clusterserviceversion.yaml, operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbbackups.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/1.10.0/perconaxtradbclusters.pxc.percona.com.crd.yaml, operators/percona-xtradb-cluster-operator/percona-xtradb-cluster-operator.package.yaml
Signed-off-by: cap1984 <ivan.pylypenko@percona.com>
--
=> operators percona-xtradb-cluster-operator (1.10.0)

operators/flux/0.25.3/manifests/alert.crd.yaml, operators/flux/0.25.3/manifests/bucket.crd.yaml, operators/flux/0.25.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.25.3/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.25.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.25.3/manifests/flux.v0.25.3.clusterserviceversion.yaml, operators/flux/0.25.3/manifests/gitrepository.crd.yaml, operators/flux/0.25.3/manifests/helmchart.crd.yaml, operators/flux/0.25.3/manifests/helmrelease.crd.yaml, operators/flux/0.25.3/manifests/helmrepository.crd.yaml, operators/flux/0.25.3/manifests/imagepolicy.crd.yaml, operators/flux/0.25.3/manifests/imagerepository.crd.yaml, operators/flux/0.25.3/manifests/imageupdateautomation.crd.yaml, operators/flux/0.25.3/manifests/kustomization.crd.yaml, operators/flux/0.25.3/manifests/notification-controller.service.yaml, operators/flux/0.25.3/manifests/provider.crd.yaml, operators/flux/0.25.3/manifests/receiver.crd.yaml, operators/flux/0.25.3/manifests/source-controller.service.yaml, operators/flux/0.25.3/manifests/webhook-receiver.service.yaml, operators/flux/0.25.3/metadata/annotations.yaml
=> operators flux (0.25.3)

operators/gitops-primer/0.0.4/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.4/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.4/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.4/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.4/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.4/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.4/metadata/annotations.yaml, operators/gitops-primer/0.0.4/tests/scorecard/config.yaml
Signed-off-by: Ryan Cook <rcook@redhat.com>
--
=> operators gitops-primer (0.0.4)

operators/gitops-primer/0.0.5/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.5/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.5/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.5/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.5/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.5/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.5/metadata/annotations.yaml, operators/gitops-primer/0.0.5/tests/scorecard/config.yaml
=> operators gitops-primer (0.0.5)

operators/klusterlet/0.6.0/klusterlet.v0.6.0.clusterserviceversion.yaml, operators/klusterlet/0.6.0/operator.open-cluster-management.io_klusterlets.yaml, operators/klusterlet/klusterlet.package.yaml
=> operators klusterlet (0.6.0)

operators/cluster-manager/0.6.0/cluster-manager.v0.6.0.clusterserviceversion.yaml, operators/cluster-manager/0.6.0/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/cluster-manger.package.yaml
=> operators cluster-manager (0.6.0)

operators/openshift-nfd-operator/4.8.0/manifests/nfd.v4.8.0.clusterserviceversion.yaml, operators/openshift-nfd-operator/4.9.0/manifests/controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml, operators/openshift-nfd-operator/4.9.0/manifests/controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd-controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd-controller-manager-metrics-service_v1_service.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd-manager-config_v1_configmap.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml, operators/openshift-nfd-operator/4.9.0/manifests/nfd.v.4.9.0.clusterserviceversion.yaml, operators/openshift-nfd-operator/4.9.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/openshift-nfd-operator/4.9.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/openshift-nfd-operator/4.9.0/metadata/annotations.yaml, operators/openshift-nfd-operator/4.9.0/tests/scorecard/config.yaml, operators/openshift-nfd-operator/ci.yaml
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
--
=> operators [R] [CI] openshift-nfd-operator (4.8.0 4.9.0)

operators/kube-green/0.3.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.3.0/manifests/kube-green-manager-config_v1_configmap.yaml, operators/kube-green/0.3.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.3.0/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.3.0/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.3.0/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.3.0/metadata/annotations.yaml, operators/kube-green/0.3.0/tests/scorecard/config.yaml, operators/kube-green/ci.yaml
Signed-off-by: Davide Bianchi <bianchidavide12@gmail.com>
--
=> operators [N] [CI] kube-green (0.3.0)

operators/community-windows-machine-config-operator/4.0.1/manifests/community-windows-machine-config-operator.4.0.1.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/4.0.1/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/4.0.1/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/4.0.1/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/4.0.1/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/4.0.1/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/4.0.1/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/4.0.1/metadata/annotations.yaml
Signed off by: Alina Ryan <aliryan@redhat.com>
--
=> operators community-windows-machine-config-operator (4.0.1)

operators/egressip-ipam-operator/1.2.3/Dockerfile, operators/egressip-ipam-operator/1.2.3/manifests/egressip-ipam-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/egressip-ipam-operator/1.2.3/manifests/egressip-ipam-operator-controller-manager-metrics_v1_service.yaml, operators/egressip-ipam-operator/1.2.3/manifests/egressip-ipam-operator-manager-config_v1_configmap.yaml, operators/egressip-ipam-operator/1.2.3/manifests/egressip-ipam-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/egressip-ipam-operator/1.2.3/manifests/egressip-ipam-operator.clusterserviceversion.yaml, operators/egressip-ipam-operator/1.2.3/manifests/redhatcop.redhat.io_egressipams.yaml, operators/egressip-ipam-operator/1.2.3/metadata/annotations.yaml, operators/egressip-ipam-operator/1.2.3/tests/scorecard/config.yaml
=> operators egressip-ipam-operator (1.2.3)

operators/cert-utils-operator/1.3.3/Dockerfile, operators/cert-utils-operator/1.3.3/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.3/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.3.3/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.3/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.3/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.3/metadata/annotations.yaml, operators/cert-utils-operator/1.3.3/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.3)

operators/silicom-sts-operator/0.0.1/manifests/silicom-sts-operator.clusterserviceversion.yaml, operators/silicom-sts-operator/0.0.1/manifests/sts.silicom.com_stsconfigs.yaml, operators/silicom-sts-operator/0.0.1/manifests/sts.silicom.com_stsoperatorconfigs.yaml, operators/silicom-sts-operator/0.0.1/metadata/annotations.yaml
=> operators [N] silicom-sts-operator (0.0.1)

operators/camel-k/1.8.0/builds.camel.apache.org.crd.yaml, operators/camel-k/1.8.0/camel-k.v1.8.0.clusterserviceversion.yaml, operators/camel-k/1.8.0/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.8.0/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.8.0/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.8.0/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.8.0/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.8.0/kamelets.camel.apache.org.crd.yaml, operators/camel-k/camel-k.package.yaml
=> operators camel-k (1.8.0)

ci/pipeline-config-ocp.yaml
=> 4.10 activated

operators/kiali/1.45.0/bundle.Dockerfile, operators/kiali/1.45.0/manifests/kiali.crd.yaml, operators/kiali/1.45.0/manifests/kiali.v1.45.0.clusterserviceversion.yaml, operators/kiali/1.45.0/metadata/annotations.yaml
=> operators kiali (1.45.0)

operators/argocd-operator/0.2.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml, operators/argocd-operator/0.2.0/argocd-operator-manager-config_v1_configmap.yaml, operators/argocd-operator/0.2.0/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/argocd-operator/0.2.0/argocd-operator.v0.2.0.clusterserviceversion.yaml, operators/argocd-operator/0.2.0/argoproj.io_applications.yaml, operators/argocd-operator/0.2.0/argoproj.io_applicationsets.yaml, operators/argocd-operator/0.2.0/argoproj.io_appprojects.yaml, operators/argocd-operator/0.2.0/argoproj.io_argocdexports.yaml, operators/argocd-operator/0.2.0/argoproj.io_argocds.yaml, operators/argocd-operator/argocd-operator.package.yaml
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>
--
=> operators argocd-operator (0.2.0)

operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.22.1/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.22.1/victoriametrics-operator.0.22.1.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.22.1)

operators/koku-metrics-operator/1.1.4/Dockerfile, operators/koku-metrics-operator/1.1.4/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.4/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.4/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.4/tests/scorecard/config.yaml
=> operators koku-metrics-operator (1.1.4)

operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion-operator-manager-config_v1_configmap.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion-operator.clusterserviceversion.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomeventbridges.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomeventdriveningestions.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicominstancebindings.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomstudybindings.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dicomwebingestionservices.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dimseingestionservices.yaml, operators/alvearie-imaging-ingestion/0.0.3/manifests/imaging-ingestion.alvearie.org_dimseproxies.yaml, operators/alvearie-imaging-ingestion/0.0.3/metadata/annotations.yaml, operators/alvearie-imaging-ingestion/0.0.3/tests/scorecard/config.yaml
Signed-off-by: Jeesmon Jacob <jjacob@us.ibm.com>
--
=> operators alvearie-imaging-ingestion (0.0.3)

operators/oadp-operator/0.5.6/manifests/dpa-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.6/manifests/dpa-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.6/manifests/oadp-operator.clusterserviceversion.yaml, operators/oadp-operator/0.5.6/manifests/oadp.openshift.io_cloudstorages.yaml, operators/oadp-operator/0.5.6/manifests/oadp.openshift.io_dataprotectionapplications.yaml, operators/oadp-operator/0.5.6/manifests/openshift-adp-controller-manager-metrics-service_v1_service.yaml, operators/oadp-operator/0.5.6/manifests/openshift-adp-manager-config_v1_configmap.yaml, operators/oadp-operator/0.5.6/manifests/openshift-adp-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_backups.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_backupstoragelocations.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_deletebackuprequests.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_downloadrequests.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_podvolumebackups.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_podvolumerestores.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_resticrepositories.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_restores.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_schedules.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_serverstatusrequests.yaml, operators/oadp-operator/0.5.6/manifests/velero.io_volumesnapshotlocations.yaml, operators/oadp-operator/0.5.6/metadata/annotations.yaml
=> operators oadp-operator (0.5.6)

operators/neuvector-community-operator/1.3.1/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.1/neuvector-operator.v1.3.1.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operators neuvector-community-operator (1.3.1)

operators/integrity-shield-operator/0.3.2/manifests/apis.integrityshield.io_integrityshields.yaml, operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator-controller-manager-metrics-service_v1_service.yaml, operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator-controller-manager_v1_serviceaccount.yaml, operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator-manager-config_v1_configmap.yaml, operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/integrity-shield-operator/0.3.2/manifests/integrity-shield-operator.clusterserviceversion.yaml, operators/integrity-shield-operator/0.3.2/metadata/annotations.yaml, operators/integrity-shield-operator/0.3.2/tests/scorecard/config.yaml
Signed-off-by: Ruriko Kudo <rurikudo@ibm.com>
--
=> operators integrity-shield-operator (0.3.2)

operators/eventing-kogito/1.1.0/manifests/config-logging_v1_configmap.yaml, operators/eventing-kogito/1.1.0/manifests/config-observability_v1_configmap.yaml, operators/eventing-kogito/1.1.0/manifests/eventing-kogito.clusterserviceversion.yaml, operators/eventing-kogito/1.1.0/manifests/kogito-source-controller-manager_v1_service.yaml, operators/eventing-kogito/1.1.0/manifests/kogito-source-observer_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/eventing-kogito/1.1.0/manifests/kogito.knative.dev_kogitosources.yaml, operators/eventing-kogito/1.1.0/metadata/annotations.yaml, operators/eventing-kogito/1.1.0/metadata/dependencies.yaml, operators/eventing-kogito/1.1.0/tests/scorecard/config.yaml, operators/eventing-kogito/ci.yaml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
* [ x Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ x Human readable name and 1-liner description about your Operator
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this …
=> operators [N] [CI] eventing-kogito (1.1.0)

operators/marin3r/0.10.0/bundle.Dockerfile, operators/marin3r/0.10.0/manifests/marin3r-controller-manager-metrics-service_v1_service.yaml, operators/marin3r/0.10.0/manifests/marin3r-manager-config_v1_configmap.yaml, operators/marin3r/0.10.0/manifests/marin3r-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/marin3r/0.10.0/manifests/marin3r-webhook-service_v1_service.yaml, operators/marin3r/0.10.0/manifests/marin3r.3scale.net_envoyconfigrevisions.yaml, operators/marin3r/0.10.0/manifests/marin3r.3scale.net_envoyconfigs.yaml, operators/marin3r/0.10.0/manifests/marin3r.clusterserviceversion.yaml, operators/marin3r/0.10.0/manifests/operator.marin3r.3scale.net_discoveryservicecertificates.yaml, operators/marin3r/0.10.0/manifests/operator.marin3r.3scale.net_discoveryservices.yaml, operators/marin3r/0.10.0/manifests/operator.marin3r.3scale.net_envoydeployments.yaml, operators/marin3r/0.10.0/metadata/annotations.yaml, operators/marin3r/0.10.0/tests/scorecard/config.yaml, operators/marin3r/ci.yaml
Signed-off-by: Roi Vazquez <roivazquez@gmail.com>
--
=> operators [N] [CI] marin3r (0.10.0)

operators/rhoas-operator/0.9.6/manifests/rhoas-operator.cloudserviceaccountrequest.crd.yaml, operators/rhoas-operator/0.9.6/manifests/rhoas-operator.cloudservicesrequests.crd.yaml, operators/rhoas-operator/0.9.6/manifests/rhoas-operator.clusterserviceversion.yaml, operators/rhoas-operator/0.9.6/manifests/rhoas-operator.kafkaconnections.crd.yaml, operators/rhoas-operator/0.9.6/manifests/rhoas-operator.serviceregistryconnections.crd.yaml, operators/rhoas-operator/0.9.6/manifests/service-binding.clusterrole.yaml, operators/rhoas-operator/0.9.6/metadata/annotations.yaml
Signed-off-by: Summers Pittman <secondsun@gmail.com>
--
=> operators rhoas-operator (0.9.6)

operators/patch-operator/0.1.1/Dockerfile, operators/patch-operator/0.1.1/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.1/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.1/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.1/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.1/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.1/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.1/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.1/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.1/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.1/metadata/annotations.yaml, operators/patch-operator/0.1.1/tests/scorecard/config.yaml
=> operators patch-operator (0.1.1)

operators/vault-config-operator/0.2.0/Dockerfile, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_authenginemounts.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_databasesecretengineconfigs.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_databasesecretengineroles.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_githubsecretengineconfigs.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_githubsecretengineroles.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_kubernetesauthengineroles.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_passwordpolicies.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_policies.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_rabbitmqsecretengineconfigs.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_rabbitmqsecretengineroles.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_randomsecrets.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_secretenginemounts.yaml, operators/vault-config-operator/0.2.0/manifests/redhatcop.redhat.io_vaultsecrets.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator-controller-manager-metrics-service_v1_service.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator-manager-config_v1_configmap.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator-webhook-service_v1_service.yaml, operators/vault-config-operator/0.2.0/manifests/vault-config-operator.clusterserviceversion.yaml, operators/vault-config-operator/0.2.0/metadata/annotations.yaml, operators/vault-config-operator/0.2.0/tests/scorecard/config.yaml
=> operators vault-config-operator (0.2.0)

operators/fossul-operator/0.1.0/bundle.Dockerfile, operators/fossul-operator/0.1.0/manifests/fossul-operator.v0.1.0.clusterserviceversion.yaml, operators/fossul-operator/0.1.0/manifests/fossul.io_backupconfigs.yaml, operators/fossul-operator/0.1.0/manifests/fossul.io_backups.yaml, operators/fossul-operator/0.1.0/manifests/fossul.io_backupschedules.yaml, operators/fossul-operator/0.1.0/manifests/fossul.io_fossuls.yaml, operators/fossul-operator/0.1.0/manifests/fossul.io_restores.yaml, operators/fossul-operator/0.1.0/metadata/annotations.yaml, operators/fossul-operator/ci.yaml
Signed-off-by: ktenzer <ktenzer@redhat.com>
--
=> operators [N] [CI] fossul-operator (0.1.0)

operators/group-sync-operator/0.0.15/Dockerfile, operators/group-sync-operator/0.0.15/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.15/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.15/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.15/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.15/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.15/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.15/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.15/metadata/annotations.yaml, operators/group-sync-operator/0.0.15/tests/scorecard/config.yaml, operators/group-sync-operator/ci.yaml
=> operators [CI] group-sync-operator (0.0.15)

operators/sosivio/1.2.0/manifests/sosivio-operator.clusterserviceversion.yaml, operators/sosivio/1.2.0/manifests/sosivio.crd.yaml, operators/sosivio/1.2.0/metadata/annotations.yaml, operators/sosivio/ci.yaml
=> operators [N] [CI] sosivio (1.2.0)

operators/silicom-sts-operator/0.0.2/bundle.Dockerfile, operators/silicom-sts-operator/0.0.2/manifests/silicom-sts-operator.clusterserviceversion.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-controller-manager-metrics-service_v1_service.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-plugin_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-plugin_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-plugin_rbac.authorization.k8s.io_v1_role.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-plugin_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-plugin_v1_serviceaccount.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-tsync_rbac.authorization.k8s.io_v1_role.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-tsync_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts-tsync_v1_serviceaccount.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts.silicom.com_stsconfigs.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts.silicom.com_stsnodes.yaml, operators/silicom-sts-operator/0.0.2/manifests/sts.silicom.com_stsoperatorconfigs.yaml, operators/silicom-sts-operator/0.0.2/metadata/annotations.yaml, operators/silicom-sts-operator/0.0.2/tests/scorecard/config.yaml
=> operators silicom-sts-operator (0.0.2)

operators/eventing-kogito/1.2.0/manifests/config-logging_v1_configmap.yaml, operators/eventing-kogito/1.2.0/manifests/config-observability_v1_configmap.yaml, operators/eventing-kogito/1.2.0/manifests/eventing-kogito.clusterserviceversion.yaml, operators/eventing-kogito/1.2.0/manifests/kogito-source-controller-manager_v1_service.yaml, operators/eventing-kogito/1.2.0/manifests/kogito-source-observer_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/eventing-kogito/1.2.0/manifests/kogito.knative.dev_kogitosources.yaml, operators/eventing-kogito/1.2.0/metadata/annotations.yaml, operators/eventing-kogito/1.2.0/metadata/dependencies.yaml, operators/eventing-kogito/1.2.0/tests/scorecard/config.yaml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
--
=> operators eventing-kogito (1.2.0)

operators/fossul-operator/0.2.0/bundle.Dockerfile, operators/fossul-operator/0.2.0/manifests/fossul-operator.v0.2.0.clusterserviceversion.yaml, operators/fossul-operator/0.2.0/manifests/fossul.io_backupconfigs.yaml, operators/fossul-operator/0.2.0/manifests/fossul.io_backups.yaml, operators/fossul-operator/0.2.0/manifests/fossul.io_backupschedules.yaml, operators/fossul-operator/0.2.0/manifests/fossul.io_fossuls.yaml, operators/fossul-operator/0.2.0/manifests/fossul.io_restores.yaml, operators/fossul-operator/0.2.0/metadata/annotations.yaml
=> operators fossul-operator (0.2.0)

operators/keda/2.6.0/manifests/keda.sh_clustertriggerauthentications.yaml, operators/keda/2.6.0/manifests/keda.sh_kedacontrollers.yaml, operators/keda/2.6.0/manifests/keda.sh_scaledjobs.yaml, operators/keda/2.6.0/manifests/keda.sh_scaledobjects.yaml, operators/keda/2.6.0/manifests/keda.sh_triggerauthentications.yaml, operators/keda/2.6.0/manifests/keda.v2.6.0.clusterserviceversion.yaml, operators/keda/2.6.0/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
=> operators keda (2.6.0)

operators/portworx-essentials/1.7.0/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.7.0/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.7.0/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
Signed-off-by: HaibinMichaelXie <hxie@purestorage.com>
--
=> operators portworx-essentials (1.7.0)

operators/snyk-operator/1.81.1/snyk-operator.v1.81.1.clusterserviceversion.yaml, operators/snyk-operator/1.81.1/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.81.1)

operators/silicom-sts-operator/0.0.3/bundle.Dockerfile, operators/silicom-sts-operator/0.0.3/manifests/silicom-sts-operator.clusterserviceversion.yaml, operators/silicom-sts-operator/0.0.3/manifests/sts-controller-manager-metrics-service_v1_service.yaml, operators/silicom-sts-operator/0.0.3/manifests/sts-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/silicom-sts-operator/0.0.3/manifests/sts.silicom.com_stsconfigs.yaml, operators/silicom-sts-operator/0.0.3/manifests/sts.silicom.com_stsnodes.yaml, operators/silicom-sts-operator/0.0.3/manifests/sts.silicom.com_stsoperatorconfigs.yaml, operators/silicom-sts-operator/0.0.3/metadata/annotations.yaml, operators/silicom-sts-operator/0.0.3/tests/scorecard/config.yaml
=> operators silicom-sts-operator (0.0.3)

operators/flux/0.26.0/manifests/alert.crd.yaml, operators/flux/0.26.0/manifests/bucket.crd.yaml, operators/flux/0.26.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.26.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.26.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.26.0/manifests/flux.v0.26.0.clusterserviceversion.yaml, operators/flux/0.26.0/manifests/gitrepository.crd.yaml, operators/flux/0.26.0/manifests/helmchart.crd.yaml, operators/flux/0.26.0/manifests/helmrelease.crd.yaml, operators/flux/0.26.0/manifests/helmrepository.crd.yaml, operators/flux/0.26.0/manifests/imagepolicy.crd.yaml, operators/flux/0.26.0/manifests/imagerepository.crd.yaml, operators/flux/0.26.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.26.0/manifests/kustomization.crd.yaml, operators/flux/0.26.0/manifests/notification-controller.service.yaml, operators/flux/0.26.0/manifests/provider.crd.yaml, operators/flux/0.26.0/manifests/receiver.crd.yaml, operators/flux/0.26.0/manifests/source-controller.service.yaml, operators/flux/0.26.0/manifests/webhook-receiver.service.yaml, operators/flux/0.26.0/metadata/annotations.yaml
=> operators flux (0.26.0)

operators/apicurito/1.0.2/Dockerfile, operators/apicurito/1.0.2/manifests/apicur.io_apicuritoes.yaml, operators/apicurito/1.0.2/manifests/apicurito-operator-installer_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/apicurito/1.0.2/manifests/apicurito.clusterserviceversion.yaml, operators/apicurito/1.0.2/metadata/annotations.yaml, operators/apicurito/1.0.2/tests/scorecard/config.yaml
Signed-off-by: phantomjinx <p.g.richardson@phantomjinx.co.uk>
--
=> operators apicurito (1.0.2)

operators/apicurito/1.0.3/Dockerfile, operators/apicurito/1.0.3/manifests/apicur.io_apicuritoes.yaml, operators/apicurito/1.0.3/manifests/apicurito-operator-installer_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/apicurito/1.0.3/manifests/apicurito.clusterserviceversion.yaml, operators/apicurito/1.0.3/metadata/annotations.yaml, operators/apicurito/1.0.3/tests/scorecard/config.yaml
Signed-off-by: phantomjinx <p.g.richardson@phantomjinx.co.uk>
--
=> operators apicurito (1.0.3)

operators/opendatahub-operator/1.1.2/manifests/kfdef.apps.kubeflow.org.crd.yaml, operators/opendatahub-operator/1.1.2/manifests/opendatahub-operator.v1.1.2.clusterserviceversion.yaml, operators/opendatahub-operator/1.1.2/metadata/annotations.yaml
=> operators opendatahub-operator (1.1.2)

operators/volume-expander-operator/0.3.3/Dockerfile, operators/volume-expander-operator/0.3.3/manifests/volume-expander-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/volume-expander-operator/0.3.3/manifests/volume-expander-operator-controller-manager-metrics_v1_service.yaml, operators/volume-expander-operator/0.3.3/manifests/volume-expander-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/volume-expander-operator/0.3.3/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/volume-expander-operator/0.3.3/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/volume-expander-operator/0.3.3/manifests/volume-expander-operator.clusterserviceversion.yaml, operators/volume-expander-operator/0.3.3/metadata/annotations.yaml, operators/volume-expander-operator/0.3.3/tests/scorecard/config.yaml
=> operators volume-expander-operator (0.3.3)

operators/fossul-operator/0.3.0/bundle.Dockerfile, operators/fossul-operator/0.3.0/manifests/fossul-operator.v0.3.0.clusterserviceversion.yaml, operators/fossul-operator/0.3.0/manifests/fossul.io_backupconfigs.yaml, operators/fossul-operator/0.3.0/manifests/fossul.io_backups.yaml, operators/fossul-operator/0.3.0/manifests/fossul.io_backupschedules.yaml, operators/fossul-operator/0.3.0/manifests/fossul.io_fossuls.yaml, operators/fossul-operator/0.3.0/manifests/fossul.io_restores.yaml, operators/fossul-operator/0.3.0/metadata/annotations.yaml
Signed-off-by: ktenzer <ktenzer@redhat.com>
--
=> operators fossul-operator (0.3.0)

operators/infinispan/2.1.3/manifests/infinispan-operator.v2.1.3.clusterserviceversion.yaml, operators/pulp-operator/0.3.0/manifests/pulp-operator.v0.3.0.clusterserviceversion.yaml, operators/pulp-operator/0.4.0/manifests/pulp-operator.v0.4.0.clusterserviceversion.yaml, operators/tf-operator/1.0.0/manifests/tf-operator.v1.0.0.clusterserviceversion.yaml
Signed-off-by: Martin Vala <mavala@redhat.com>
Dear @ivanvtimofeev, @chambridge, @dkliban, @fao89, @mdellweg, @mikedep333, @rooftopcellist, @spredzy, @rigazilla, @ryanemerson,
This PR is fixing json objects in `alm-examples`
=> Fixing json format in alm-examples

operators/patterns-operator/0.0.1/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.1/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.1/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.1/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.1/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.1/metadata/annotations.yaml, operators/patterns-operator/0.0.1/tests/scorecard/config.yaml
Signed-off-by: Andrew Beekhof <andrew@beekhof.net>
* [ x ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ x ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ x ] Have you tested your Operator with all Custom Resource Definitions?
* [ x ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ x ] Have you considered whether …
=> operators [N] patterns-operator (0.0.1)

operators/keda/2.6.1/manifests/keda.sh_clustertriggerauthentications.yaml, operators/keda/2.6.1/manifests/keda.sh_kedacontrollers.yaml, operators/keda/2.6.1/manifests/keda.sh_scaledjobs.yaml, operators/keda/2.6.1/manifests/keda.sh_scaledobjects.yaml, operators/keda/2.6.1/manifests/keda.sh_triggerauthentications.yaml, operators/keda/2.6.1/manifests/keda.v2.6.1.clusterserviceversion.yaml, operators/keda/2.6.1/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
--
=> operators keda (2.6.1)

operators/vault-config-operator/0.3.0/Dockerfile, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_authenginemounts.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_databasesecretengineconfigs.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_databasesecretengineroles.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_githubsecretengineconfigs.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_githubsecretengineroles.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_kubernetesauthengineroles.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_passwordpolicies.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_pkisecretengineconfigs.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_pkisecretengineroles.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_policies.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_rabbitmqsecretengineconfigs.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_rabbitmqsecretengineroles.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_randomsecrets.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_secretenginemounts.yaml, operators/vault-config-operator/0.3.0/manifests/redhatcop.redhat.io_vaultsecrets.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator-controller-manager-metrics-service_v1_service.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator-manager-config_v1_configmap.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator-webhook-service_v1_service.yaml, operators/vault-config-operator/0.3.0/manifests/vault-config-operator.clusterserviceversion.yaml, operators/vault-config-operator/0.3.0/metadata/annotations.yaml, operators/vault-config-operator/0.3.0/tests/scorecard/config.yaml
=> operators vault-config-operator (0.3.0)

operators/patterns-operator/0.0.2/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.2/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.2/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.2/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.2/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.2/metadata/annotations.yaml, operators/patterns-operator/0.0.2/tests/scorecard/config.yaml
Signed-off-by: Andrew Beekhof <andrew@beekhof.net>
* [ x ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ x ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ x ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ x ] Have you tested an update to your Operator when deployed via OLM?
* [ x ] Is your …
=> operators patterns-operator (0.0.2)

operators/cert-utils-operator/1.3.4/Dockerfile, operators/cert-utils-operator/1.3.4/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.4/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.3.4/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.4/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.4/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.4/metadata/annotations.yaml, operators/cert-utils-operator/1.3.4/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.4)

operators/volume-expander-operator/0.3.4/Dockerfile, operators/volume-expander-operator/0.3.4/manifests/volume-expander-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/volume-expander-operator/0.3.4/manifests/volume-expander-operator-controller-manager-metrics_v1_service.yaml, operators/volume-expander-operator/0.3.4/manifests/volume-expander-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/volume-expander-operator/0.3.4/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/volume-expander-operator/0.3.4/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/volume-expander-operator/0.3.4/manifests/volume-expander-operator.clusterserviceversion.yaml, operators/volume-expander-operator/0.3.4/metadata/annotations.yaml, operators/volume-expander-operator/0.3.4/tests/scorecard/config.yaml
=> operators volume-expander-operator (0.3.4)

operators/netobserv-operator/0.1.0/manifests/network-observability-operator.clusterserviceversion.yaml
=> operators [N] netobserv-operator (0.1.0)

operators/external-secrets-operator/0.4.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.4.2/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.4.2/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.4.2/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.4.2/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.4.2/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.4.2/metadata/annotations.yaml, operators/external-secrets-operator/0.4.2/tests/scorecard/config.yaml
bump external secrets version to v0.4.2
Signed-off-by: Gustavo Carvalho <gusfcarvalho@gmail.com>
=> operators external-secrets-operator (0.4.2)

operators/keycloak-operator/17.0.0/bundle.Dockerfile, operators/keycloak-operator/17.0.0/manifests/keycloak-operator.v17.0.0.clusterserviceversion.yaml, operators/keycloak-operator/17.0.0/manifests/keycloakbackups.keycloak.org.crd.yaml, operators/keycloak-operator/17.0.0/manifests/keycloakclients.keycloak.org.crd.yaml, operators/keycloak-operator/17.0.0/manifests/keycloakrealms.keycloak.org.crd.yaml, operators/keycloak-operator/17.0.0/manifests/keycloaks.keycloak.org.crd.yaml, operators/keycloak-operator/17.0.0/manifests/keycloakusers.keycloak.org.crd.yaml, operators/keycloak-operator/17.0.0/metadata/annotations.yaml
Signed-off-by: Jonathan Vila <jvilalop@redhat.com>
* [X ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [X ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [X ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [X ] Have you tested an update to your Operator when deployed via OLM?
* [X ] Is your …
=> operators keycloak-operator (17.0.0)

operators/cert-utils-operator/1.3.5/Dockerfile, operators/cert-utils-operator/1.3.5/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.5/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.3.5/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.5/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.5/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.5/metadata/annotations.yaml, operators/cert-utils-operator/1.3.5/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.5)

operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.43.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.43.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.43.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.43.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.43.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.43.0)

operators/vault-config-operator/0.3.1/Dockerfile, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_authenginemounts.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_databasesecretengineconfigs.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_databasesecretengineroles.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_githubsecretengineconfigs.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_githubsecretengineroles.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_kubernetesauthengineroles.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_passwordpolicies.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_pkisecretengineconfigs.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_pkisecretengineroles.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_policies.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_rabbitmqsecretengineconfigs.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_rabbitmqsecretengineroles.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_randomsecrets.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_secretenginemounts.yaml, operators/vault-config-operator/0.3.1/manifests/redhatcop.redhat.io_vaultsecrets.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator-controller-manager-metrics-service_v1_service.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator-manager-config_v1_configmap.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator-webhook-service_v1_service.yaml, operators/vault-config-operator/0.3.1/manifests/vault-config-operator.clusterserviceversion.yaml, operators/vault-config-operator/0.3.1/metadata/annotations.yaml, operators/vault-config-operator/0.3.1/tests/scorecard/config.yaml
=> operators vault-config-operator (0.3.1)

operators/fossul-operator/0.4.0/bundle.Dockerfile, operators/fossul-operator/0.4.0/manifests/fossul-operator.v0.4.0.clusterserviceversion.yaml, operators/fossul-operator/0.4.0/manifests/fossul.io_backupconfigs.yaml, operators/fossul-operator/0.4.0/manifests/fossul.io_backups.yaml, operators/fossul-operator/0.4.0/manifests/fossul.io_backupschedules.yaml, operators/fossul-operator/0.4.0/manifests/fossul.io_fossuls.yaml, operators/fossul-operator/0.4.0/manifests/fossul.io_restores.yaml, operators/fossul-operator/0.4.0/metadata/annotations.yaml
=> operators fossul-operator (0.4.0)

operators/project-quay/3.6.2/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.6.2/quayecosystems.crd.yaml, operators/project-quay/3.6.2/quayregistries.crd.yaml, operators/project-quay/ci.yaml, operators/project-quay/project-quay.package.yaml
Adds Quay, direct copy of recent PR in community operatorhub: https://github.com/k8s-operatorhub/community-operators/pull/781
Signed-off-by: Dave O'Connor [doconnor@redhat.com](mailto:doconnor@redhat.com)
-- …
=> operators [N] [CI] project-quay (3.6.2)

operators/external-secrets-operator/0.4.3/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.4.3/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.4.3/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.4.3/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.4.3/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.4.3/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.4.3/metadata/annotations.yaml, operators/external-secrets-operator/0.4.3/tests/scorecard/config.yaml
bumping external-secrets version to 0.4.3
Signed-off-by: Gustavo Carvalho <gusfcarvalho@gmail.com>
=> operators external-secrets-operator (0.4.3)

operators/fossul-operator/0.5.0/bundle.Dockerfile, operators/fossul-operator/0.5.0/manifests/fossul-operator.v0.5.0.clusterserviceversion.yaml, operators/fossul-operator/0.5.0/manifests/fossul.io_backupconfigs.yaml, operators/fossul-operator/0.5.0/manifests/fossul.io_backups.yaml, operators/fossul-operator/0.5.0/manifests/fossul.io_backupschedules.yaml, operators/fossul-operator/0.5.0/manifests/fossul.io_fossuls.yaml, operators/fossul-operator/0.5.0/manifests/fossul.io_restores.yaml, operators/fossul-operator/0.5.0/metadata/annotations.yaml
Signed-off-by: ktenzer <ktenzer@redhat.com>
--
=> operators fossul-operator (0.5.0)

operators/opentelemetry-operator/ci.yaml
Signed-off-by: VineethReddy02 <VineethReddy02>
--
=> operators [CI] opentelemetry-operator

operators/flux/0.27.0/manifests/alert.crd.yaml, operators/flux/0.27.0/manifests/bucket.crd.yaml, operators/flux/0.27.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.27.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.27.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.27.0/manifests/flux.v0.27.0.clusterserviceversion.yaml, operators/flux/0.27.0/manifests/gitrepository.crd.yaml, operators/flux/0.27.0/manifests/helmchart.crd.yaml, operators/flux/0.27.0/manifests/helmrelease.crd.yaml, operators/flux/0.27.0/manifests/helmrepository.crd.yaml, operators/flux/0.27.0/manifests/imagepolicy.crd.yaml, operators/flux/0.27.0/manifests/imagerepository.crd.yaml, operators/flux/0.27.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.27.0/manifests/kustomization.crd.yaml, operators/flux/0.27.0/manifests/notification-controller.service.yaml, operators/flux/0.27.0/manifests/provider.crd.yaml, operators/flux/0.27.0/manifests/receiver.crd.yaml, operators/flux/0.27.0/manifests/source-controller.service.yaml, operators/flux/0.27.0/manifests/webhook-receiver.service.yaml, operators/flux/0.27.0/metadata/annotations.yaml
=> operators flux (0.27.0)

operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.23.3/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.23.3/victoriametrics-operator.0.23.3.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.23.3)

operators/group-sync-operator/0.0.16/Dockerfile, operators/group-sync-operator/0.0.16/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.16/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.16/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.16/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.16/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.16/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.16/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.16/metadata/annotations.yaml, operators/group-sync-operator/0.0.16/tests/scorecard/config.yaml
=> operators group-sync-operator (0.0.16)

operators/grafana-operator/4.2.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.2.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.2.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.2.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.2.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.2.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.2.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.2.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operators grafana-operator (4.2.0)

operators/gitlab-runner-operator/1.6.0/bundle.Dockerfile, operators/gitlab-runner-operator/1.6.0/manifests/apps.gitlab.com_runners.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml, operators/gitlab-runner-operator/1.6.0/manifests/gitlab-runner-webhook-service_v1_service.yaml, operators/gitlab-runner-operator/1.6.0/metadata/annotations.yaml, operators/gitlab-runner-operator/1.6.0/tests/scorecard/config.yaml, operators/gitlab-runner-operator/ci.yaml
=> operators [CI] gitlab-runner-operator (1.6.0)

operators/gitops-primer/0.0.6/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.6/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.6/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.6/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.6/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.6/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.6/metadata/annotations.yaml, operators/gitops-primer/0.0.6/tests/scorecard/config.yaml
=> operators gitops-primer (0.0.6)

operators/fpga-dfl-operator/0.0.1/bundle.Dockerfile, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-controller-manager-metrics-service_v1_service.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-fpgadflconfig-editor-role_rbac.authorization.k8s.io_v1_role.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-fpgadflconfig-viewer-role_rbac.authorization.k8s.io_v1_role.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-fpgadfloperator-editor-role_rbac.authorization.k8s.io_v1_role.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-fpgadfloperator-viewer-role_rbac.authorization.k8s.io_v1_role.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga-dfl-operator.clusterserviceversion.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga.silicom.dk_fpgadflclusters.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga.silicom.dk_fpgadflnodes.yaml, operators/fpga-dfl-operator/0.0.1/manifests/fpga.silicom.dk_fpgadfloperators.yaml, operators/fpga-dfl-operator/0.0.1/metadata/annotations.yaml, operators/fpga-dfl-operator/0.0.1/tests/scorecard/config.yaml
=> operators [N] fpga-dfl-operator (0.0.1)

operators/flux/0.27.2/manifests/alert.crd.yaml, operators/flux/0.27.2/manifests/bucket.crd.yaml, operators/flux/0.27.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.27.2/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.27.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.27.2/manifests/flux.v0.27.2.clusterserviceversion.yaml, operators/flux/0.27.2/manifests/gitrepository.crd.yaml, operators/flux/0.27.2/manifests/helmchart.crd.yaml, operators/flux/0.27.2/manifests/helmrelease.crd.yaml, operators/flux/0.27.2/manifests/helmrepository.crd.yaml, operators/flux/0.27.2/manifests/imagepolicy.crd.yaml, operators/flux/0.27.2/manifests/imagerepository.crd.yaml, operators/flux/0.27.2/manifests/imageupdateautomation.crd.yaml, operators/flux/0.27.2/manifests/kustomization.crd.yaml, operators/flux/0.27.2/manifests/notification-controller.service.yaml, operators/flux/0.27.2/manifests/provider.crd.yaml, operators/flux/0.27.2/manifests/receiver.crd.yaml, operators/flux/0.27.2/manifests/source-controller.service.yaml, operators/flux/0.27.2/manifests/webhook-receiver.service.yaml, operators/flux/0.27.2/metadata/annotations.yaml
=> operators flux (0.27.2)

operators/verticadb-operator/1.3.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.3.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.3.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.3.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.3.0/metadata/annotations.yaml, operators/verticadb-operator/1.3.0/tests/scorecard/config.yaml
=> operators verticadb-operator (1.3.0)

operators/neuvector-community-operator/1.3.2/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.2/neuvector-operator.v1.3.2.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operators neuvector-community-operator (1.3.2)

operators/tf-controller/0.9.0-rc.3/manifests/terraform.crd.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-cluster-reconciler.clusterrolebinding.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-controller.v0.9.0-rc.3.clusterserviceversion.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-leader-election-role.role.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-leader-election-rolebinding.rolebinding.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-manager-role.clusterrole.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-manager-rolebinding.clusterrolebinding.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-runner-role.clusterrole.yaml, operators/tf-controller/0.9.0-rc.3/manifests/tf-runner-rolebinding.clusterrolebinding.yaml, operators/tf-controller/0.9.0-rc.3/metadata/annotations.yaml, operators/tf-controller/ci.yaml
=> operators [N] [CI] tf-controller (0.9.0-rc.3)

operators/opentelemetry-operator/0.45.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.45.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.45.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.45.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.45.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.45.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.45.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.45.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.45.0)

operators/argocd-operator/0.2.1/argocd-operator-controller-manager-metrics-service_v1_service.yaml, operators/argocd-operator/0.2.1/argocd-operator-manager-config_v1_configmap.yaml, operators/argocd-operator/0.2.1/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/argocd-operator/0.2.1/argocd-operator.v0.2.1.clusterserviceversion.yaml, operators/argocd-operator/0.2.1/argoproj.io_applications.yaml, operators/argocd-operator/0.2.1/argoproj.io_applicationsets.yaml, operators/argocd-operator/0.2.1/argoproj.io_appprojects.yaml, operators/argocd-operator/0.2.1/argoproj.io_argocdexports.yaml, operators/argocd-operator/0.2.1/argoproj.io_argocds.yaml, operators/argocd-operator/argocd-operator.package.yaml
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>
--
=> operators argocd-operator (0.2.1)

operators/camel-k/1.8.1/builds.camel.apache.org.crd.yaml, operators/camel-k/1.8.1/camel-k.v1.8.1.clusterserviceversion.yaml, operators/camel-k/1.8.1/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.8.1/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.8.1/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.8.1/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.8.1/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.8.1/kamelets.camel.apache.org.crd.yaml, operators/camel-k/camel-k.package.yaml, operators/camel-k/ci.yaml
=> operators [CI] camel-k (1.8.1)

operators/flux/0.27.3/manifests/alert.crd.yaml, operators/flux/0.27.3/manifests/bucket.crd.yaml, operators/flux/0.27.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.27.3/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.27.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.27.3/manifests/flux.v0.27.3.clusterserviceversion.yaml, operators/flux/0.27.3/manifests/gitrepository.crd.yaml, operators/flux/0.27.3/manifests/helmchart.crd.yaml, operators/flux/0.27.3/manifests/helmrelease.crd.yaml, operators/flux/0.27.3/manifests/helmrepository.crd.yaml, operators/flux/0.27.3/manifests/imagepolicy.crd.yaml, operators/flux/0.27.3/manifests/imagerepository.crd.yaml, operators/flux/0.27.3/manifests/imageupdateautomation.crd.yaml, operators/flux/0.27.3/manifests/kustomization.crd.yaml, operators/flux/0.27.3/manifests/notification-controller.service.yaml, operators/flux/0.27.3/manifests/provider.crd.yaml, operators/flux/0.27.3/manifests/receiver.crd.yaml, operators/flux/0.27.3/manifests/source-controller.service.yaml, operators/flux/0.27.3/manifests/webhook-receiver.service.yaml, operators/flux/0.27.3/metadata/annotations.yaml
=> operators flux (0.27.3)

operators/verticadb-operator/1.3.1/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.3.1/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.3.1/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.3.1/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.3.1/metadata/annotations.yaml, operators/verticadb-operator/1.3.1/tests/scorecard/config.yaml
Signed-off-by: Matt Spilchen <matt.spilchen@microfocus.com>
--
=> operators verticadb-operator (1.3.1)

operators/cert-utils-operator/1.3.8/Dockerfile, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator-certificate-rule-alerts_monitoring.coreos.com_v1_prometheusrule.yaml, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator-controller-manager-metrics_v1_service.yaml, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/cert-utils-operator/1.3.8/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.8/metadata/annotations.yaml, operators/cert-utils-operator/1.3.8/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.8)

operators/cass-operator-community/1.10.1/manifests/cass-operator-manager-config_v1_configmap.yaml, operators/cass-operator-community/1.10.1/manifests/cass-operator-webhook-service_v1_service.yaml, operators/cass-operator-community/1.10.1/manifests/cass-operator.clusterserviceversion.yaml, operators/cass-operator-community/1.10.1/manifests/cassandra.datastax.com_cassandradatacenters.yaml, operators/cass-operator-community/1.10.1/manifests/control.k8ssandra.io_cassandratasks.yaml, operators/cass-operator-community/1.10.1/metadata/annotations.yaml, operators/cass-operator-community/1.10.1/tests/scorecard/config.yaml, operators/cass-operator-community/ci.yaml
Signed-off-by: Michael Burman <michael.burman@datastax.com>
--
=> operators [N] [CI] cass-operator-community (1.10.1)

operators/kube-green/0.3.1/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.3.1/manifests/kube-green-manager-config_v1_configmap.yaml, operators/kube-green/0.3.1/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.3.1/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.3.1/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.3.1/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.3.1/metadata/annotations.yaml, operators/kube-green/0.3.1/tests/scorecard/config.yaml
Signed-off-by: Davide Bianchi <bianchidavide12@gmail.com>
--
=> operators kube-green (0.3.1)

operators/camel-k/1.8.2/builds.camel.apache.org.crd.yaml, operators/camel-k/1.8.2/camel-k.v1.8.2.clusterserviceversion.yaml, operators/camel-k/1.8.2/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.8.2/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.8.2/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.8.2/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.8.2/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.8.2/kamelets.camel.apache.org.crd.yaml, operators/camel-k/camel-k.package.yaml
=> operators camel-k (1.8.2)

operators/project-quay/3.7.0-rc.1/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.0-rc.1/quayecosystems.crd.yaml, operators/project-quay/3.7.0-rc.1/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.0-rc.1 to community operators
=> operators project-quay (3.7.0-rc.1)

operators/netobserv-operator/0.1.1/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/0.1.1/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/0.1.1/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/0.1.1/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/0.1.1/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/0.1.1/metadata/annotations.yaml
=> operators netobserv-operator (0.1.1)

operators/mongodb-atlas-kubernetes/0.8.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/0.8.0/manifests/atlas.mongodb.com_atlasclusters.yaml, operators/mongodb-atlas-kubernetes/0.8.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/0.8.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/0.8.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/0.8.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/0.8.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/0.8.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/0.8.0/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
=> operators mongodb-atlas-kubernetes (0.8.0)

operators/teiid/0.0.1/teiid.0.0.1.clusterserviceversion.yaml, operators/teiid/0.1.0/teiid.0.1.0.clusterserviceversion.yaml, operators/teiid/0.1.1/teiid.0.1.1.clusterserviceversion.yaml, operators/teiid/0.2.0/teiid.v0.2.0.clusterserviceversion.yaml, operators/teiid/ci.yaml
Signed-off-by: Martin Vala <mavala@redhat.com>
=> operators [R] [CI] teiid (0.0.1 0.1.0 0.1.1 0.2.0)

operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.44.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.44.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.44.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.44.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.44.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.44.0)

operators/mongodb-atlas-kubernetes/ci.yaml
=> operators [CI] mongodb-atlas-kubernetes

operators/silicom-sts-operator/0.0.4/bundle.Dockerfile, operators/silicom-sts-operator/0.0.4/manifests/silicom-sts-operator.clusterserviceversion.yaml, operators/silicom-sts-operator/0.0.4/manifests/sts-controller-manager-metrics-service_v1_service.yaml, operators/silicom-sts-operator/0.0.4/manifests/sts-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/silicom-sts-operator/0.0.4/manifests/sts.silicom.com_stsconfigs.yaml, operators/silicom-sts-operator/0.0.4/manifests/sts.silicom.com_stsnodes.yaml, operators/silicom-sts-operator/0.0.4/manifests/sts.silicom.com_stsoperatorconfigs.yaml, operators/silicom-sts-operator/0.0.4/metadata/annotations.yaml, operators/silicom-sts-operator/0.0.4/tests/scorecard/config.yaml
=> operators silicom-sts-operator (0.0.4)

operators/app-director-operator/0.0.1/Dockerfile, operators/app-director-operator/0.0.1/manifests/app-director-controller-manager-metrics-service_v1_service.yaml, operators/app-director-operator/0.0.1/manifests/app-director-manager-config_v1_configmap.yaml, operators/app-director-operator/0.0.1/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/app-director-operator/0.0.1/manifests/app-director-operator.clusterserviceversion.yaml, operators/app-director-operator/0.0.1/manifests/appdirector.randoli.ca_clusterwideguvnors.yaml, operators/app-director-operator/0.0.1/manifests/appdirector.randoli.ca_guvnors.yaml, operators/app-director-operator/0.0.1/metadata/annotations.yaml, operators/app-director-operator/0.0.1/tests/scorecard/config.yaml, operators/app-director-operator/ci.yaml
Signed-off-by: Rosa Lopes <josue.lopes@randoli.ca>
--
=> operators [N] [CI] app-director-operator (0.0.1)

operators/snyk-operator/1.85.2/snyk-operator.v1.85.2.clusterserviceversion.yaml, operators/snyk-operator/1.85.2/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.85.2)

operators/project-quay/3.7.0-rc.2/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.0-rc.2/quayecosystems.crd.yaml, operators/project-quay/3.7.0-rc.2/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.0-rc.2 to community operators
=> operators project-quay (3.7.0-rc.2)

operators/seldon-operator/1.13.1/manifests/machinelearning.seldon.io_seldondeployments.yaml, operators/seldon-operator/1.13.1/manifests/seldon-operator.clusterserviceversion.yaml, operators/seldon-operator/1.13.1/metadata/annotations.yaml, operators/seldon-operator/1.13.1/tests/scorecard/config.yaml, operators/seldon-operator/ci.yaml
Update Seldon Operator to 1.13.1
=> operators [CI] seldon-operator (1.13.1)

operators/pulp-operator/0.8.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.8.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.8.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.8.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.8.0/manifests/pulp-operator.v0.8.0.clusterserviceversion.yaml, operators/pulp-operator/0.8.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.8.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.8.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.8.0/metadata/annotations.yaml, operators/pulp-operator/0.8.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.8.0)

operators/opentelemetry-operator/0.46.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.46.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.46.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.46.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.46.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.46.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.46.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.46.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.46.0)

operators/ibmcloud-operator/1.1.0/apiextensions.k8s.io_v1_customresourcedefinition_bindings.ibmcloud.ibm.com.yaml, operators/ibmcloud-operator/1.1.0/apiextensions.k8s.io_v1_customresourcedefinition_services.ibmcloud.ibm.com.yaml, operators/ibmcloud-operator/1.1.0/ibmcloud_operator.v1.1.0.clusterserviceversion.yaml, operators/ibmcloud-operator/ibmcloud-operator.package.yaml
Automated release of IBM Cloud Operator v1.1.0.
=> operators ibmcloud-operator (1.1.0)

operators/flux/0.27.4/manifests/alert.crd.yaml, operators/flux/0.27.4/manifests/bucket.crd.yaml, operators/flux/0.27.4/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.27.4/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.27.4/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.27.4/manifests/flux.v0.27.4.clusterserviceversion.yaml, operators/flux/0.27.4/manifests/gitrepository.crd.yaml, operators/flux/0.27.4/manifests/helmchart.crd.yaml, operators/flux/0.27.4/manifests/helmrelease.crd.yaml, operators/flux/0.27.4/manifests/helmrepository.crd.yaml, operators/flux/0.27.4/manifests/imagepolicy.crd.yaml, operators/flux/0.27.4/manifests/imagerepository.crd.yaml, operators/flux/0.27.4/manifests/imageupdateautomation.crd.yaml, operators/flux/0.27.4/manifests/kustomization.crd.yaml, operators/flux/0.27.4/manifests/notification-controller.service.yaml, operators/flux/0.27.4/manifests/provider.crd.yaml, operators/flux/0.27.4/manifests/receiver.crd.yaml, operators/flux/0.27.4/manifests/source-controller.service.yaml, operators/flux/0.27.4/manifests/webhook-receiver.service.yaml, operators/flux/0.27.4/metadata/annotations.yaml
=> operators flux (0.27.4)

operators/tf-controller/0.9.0-rc.8/manifests/terraform.crd.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-cluster-reconciler.clusterrolebinding.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-controller.v0.9.0-rc.8.clusterserviceversion.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-leader-election-role.role.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-leader-election-rolebinding.rolebinding.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-manager-role.clusterrole.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-manager-rolebinding.clusterrolebinding.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-runner-role.clusterrole.yaml, operators/tf-controller/0.9.0-rc.8/manifests/tf-runner-rolebinding.clusterrolebinding.yaml, operators/tf-controller/0.9.0-rc.8/metadata/annotations.yaml
=> operators tf-controller (0.9.0-rc.8)

operators/integrity-shield-operator/0.3.3/manifests/apis.integrityshield.io_integrityshields.yaml, operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator-controller-manager-metrics-service_v1_service.yaml, operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator-manager-config_v1_configmap.yaml, operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/integrity-shield-operator/0.3.3/manifests/integrity-shield-operator.clusterserviceversion.yaml, operators/integrity-shield-operator/0.3.3/metadata/annotations.yaml, operators/integrity-shield-operator/0.3.3/tests/scorecard/config.yaml
Signed-off-by: Ruriko Kudo <rurikudo@ibm.com>
--
=> operators integrity-shield-operator (0.3.3)

operators/dynatrace-operator/0.5.0/Dockerfile, operators/dynatrace-operator/0.5.0/manifests/dynatrace-activegate_v1_serviceaccount.yaml, operators/dynatrace-operator/0.5.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.5.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.5.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.5.0/metadata/annotations.yaml, operators/dynatrace-operator/ci.yaml
Signed-off-by: Michael Rynkiewicz <michael.rynkiewicz@dynatrace.com>
--
=> operators [N] [CI] dynatrace-operator (0.5.0)

operators/kiali/1.47.0/bundle.Dockerfile, operators/kiali/1.47.0/manifests/kiali.crd.yaml, operators/kiali/1.47.0/manifests/kiali.v1.47.0.clusterserviceversion.yaml, operators/kiali/1.47.0/metadata/annotations.yaml, operators/kiali/1.48.0/bundle.Dockerfile, operators/kiali/1.48.0/manifests/kiali.crd.yaml, operators/kiali/1.48.0/manifests/kiali.v1.48.0.clusterserviceversion.yaml, operators/kiali/1.48.0/metadata/annotations.yaml
=> operators [R] kiali (1.47.0 1.48.0)

operators/app-director-operator/0.0.2/Dockerfile, operators/app-director-operator/0.0.2/manifests/app-director-controller-manager-metrics-service_v1_service.yaml, operators/app-director-operator/0.0.2/manifests/app-director-manager-config_v1_configmap.yaml, operators/app-director-operator/0.0.2/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/app-director-operator/0.0.2/manifests/app-director-operator.clusterserviceversion.yaml, operators/app-director-operator/0.0.2/manifests/appdirector.randoli.ca_clusterwideguvnors.yaml, operators/app-director-operator/0.0.2/manifests/appdirector.randoli.ca_guvnors.yaml, operators/app-director-operator/0.0.2/metadata/annotations.yaml, operators/app-director-operator/0.0.2/tests/scorecard/config.yaml
Signed-off-by: Rosa Lopes <josue.lopes@randoli.ca>
=> operators [R] app-director-operator (0.0.1 0.0.2)

operators/gitlab-runner-operator/1.7.0/bundle.Dockerfile, operators/gitlab-runner-operator/1.7.0/manifests/apps.gitlab.com_runners.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml, operators/gitlab-runner-operator/1.7.0/manifests/gitlab-runner-webhook-service_v1_service.yaml, operators/gitlab-runner-operator/1.7.0/metadata/annotations.yaml, operators/gitlab-runner-operator/1.7.0/tests/scorecard/config.yaml
Signed-off-by: ggeorgiev_gitlab <ggeorgiev@gitlab.com>
--
=> operators [R] gitlab-runner-operator (1.7.0)

operators/project-quay/ci.yaml
* Initial addition of quay reviewers as requested per https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/932#issuecomment-1065117231
=> operators [CI] project-quay

operators/patterns-operator/0.0.3/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.3/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.3/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.3/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.3/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.3/metadata/annotations.yaml, operators/patterns-operator/0.0.3/tests/scorecard/config.yaml, operators/patterns-operator/ci.yaml
Signed-off-by: Andrew Beekhof <andrew@beekhof.net>
* [ x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ x] Have you tested an update to your Operator when deployed via OLM?
* [ x] Is your …
=> operators [CI] patterns-operator (0.0.3)

operators/flux/0.28.3/manifests/alert.crd.yaml, operators/flux/0.28.3/manifests/bucket.crd.yaml, operators/flux/0.28.3/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.28.3/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.28.3/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.28.3/manifests/flux.v0.28.3.clusterserviceversion.yaml, operators/flux/0.28.3/manifests/gitrepository.crd.yaml, operators/flux/0.28.3/manifests/helmchart.crd.yaml, operators/flux/0.28.3/manifests/helmrelease.crd.yaml, operators/flux/0.28.3/manifests/helmrepository.crd.yaml, operators/flux/0.28.3/manifests/imagepolicy.crd.yaml, operators/flux/0.28.3/manifests/imagerepository.crd.yaml, operators/flux/0.28.3/manifests/imageupdateautomation.crd.yaml, operators/flux/0.28.3/manifests/kustomization.crd.yaml, operators/flux/0.28.3/manifests/notification-controller.service.yaml, operators/flux/0.28.3/manifests/provider.crd.yaml, operators/flux/0.28.3/manifests/receiver.crd.yaml, operators/flux/0.28.3/manifests/source-controller.service.yaml, operators/flux/0.28.3/manifests/webhook-receiver.service.yaml, operators/flux/0.28.3/metadata/annotations.yaml
=> operators flux (0.28.3)

operators/klusterlet/0.7.0/klusterlet.v0.7.0.clusterserviceversion.yaml, operators/klusterlet/0.7.0/operator.open-cluster-management.io_klusterlets.yaml, operators/klusterlet/klusterlet.package.yaml
=> operators klusterlet (0.7.0)

operators/cluster-manager/0.7.0/cluster-manager.v0.7.0.clusterserviceversion.yaml, operators/cluster-manager/0.7.0/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/cluster-manger.package.yaml
=> operators cluster-manager (0.7.0)

operators/flux/0.28.4/manifests/alert.crd.yaml, operators/flux/0.28.4/manifests/bucket.crd.yaml, operators/flux/0.28.4/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.28.4/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.28.4/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.28.4/manifests/flux.v0.28.4.clusterserviceversion.yaml, operators/flux/0.28.4/manifests/gitrepository.crd.yaml, operators/flux/0.28.4/manifests/helmchart.crd.yaml, operators/flux/0.28.4/manifests/helmrelease.crd.yaml, operators/flux/0.28.4/manifests/helmrepository.crd.yaml, operators/flux/0.28.4/manifests/imagepolicy.crd.yaml, operators/flux/0.28.4/manifests/imagerepository.crd.yaml, operators/flux/0.28.4/manifests/imageupdateautomation.crd.yaml, operators/flux/0.28.4/manifests/kustomization.crd.yaml, operators/flux/0.28.4/manifests/notification-controller.service.yaml, operators/flux/0.28.4/manifests/provider.crd.yaml, operators/flux/0.28.4/manifests/receiver.crd.yaml, operators/flux/0.28.4/manifests/source-controller.service.yaml, operators/flux/0.28.4/manifests/webhook-receiver.service.yaml, operators/flux/0.28.4/metadata/annotations.yaml
=> operators flux (0.28.4)

operators/yaks/0.9.0/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.9.0/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.9.0/yaks.v0.9.0.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operators yaks (0.9.0)

operators/ibm-spectrum-scale-csi-operator/2.5.0/csiscaleoperators.csi.ibm.com.crd.yaml, operators/ibm-spectrum-scale-csi-operator/2.5.0/ibm-spectrum-scale-csi-operator.v2.5.0.clusterserviceversion.yaml, operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
=> operators ibm-spectrum-scale-csi-operator (2.5.0)

operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.47.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.47.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.47.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.47.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.47.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.47.0)

operators/dell-csi-operator/1.7.0/csiisilons.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.7.0/csipowermaxes.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.7.0/csipowermaxrevproxies.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.7.0/csipowerstores.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.7.0/csiunities.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.7.0/csivxflexoses.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.7.0/dell-csi-operator.v1.7.0.clusterserviceversion.yaml, operators/dell-csi-operator/dell-csi-operator.package.yaml
=> operators dell-csi-operator (1.7.0)

operators/multicluster-operators-subscription/0.3.9/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_subscriptionreports_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.3.9/apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.3.9/multicluster-operators-subscription.v0.3.9.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators multicluster-operators-subscription (0.3.9)

operators/snapscheduler/3.0.0/bundle.Dockerfile, operators/snapscheduler/3.0.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml, operators/snapscheduler/3.0.0/manifests/snapscheduler-manager-config_v1_configmap.yaml, operators/snapscheduler/3.0.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/snapscheduler/3.0.0/manifests/snapscheduler.backube_snapshotschedules.yaml, operators/snapscheduler/3.0.0/manifests/snapscheduler.clusterserviceversion.yaml, operators/snapscheduler/3.0.0/metadata/annotations.yaml, operators/snapscheduler/3.0.0/tests/scorecard/config.yaml
=> operators snapscheduler (3.0.0)

operators/fossul-operator/0.6.0/bundle.Dockerfile, operators/fossul-operator/0.6.0/manifests/fossul-operator.v0.6.0.clusterserviceversion.yaml, operators/fossul-operator/0.6.0/manifests/fossul.io_backupconfigs.yaml, operators/fossul-operator/0.6.0/manifests/fossul.io_backups.yaml, operators/fossul-operator/0.6.0/manifests/fossul.io_backupschedules.yaml, operators/fossul-operator/0.6.0/manifests/fossul.io_fossuls.yaml, operators/fossul-operator/0.6.0/manifests/fossul.io_restores.yaml, operators/fossul-operator/0.6.0/metadata/annotations.yaml
Signed-off-by: ktenzer <ktenzer@redhat.com>
--
=> operators fossul-operator (0.6.0)

operators/gitops-primer/0.0.7/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.7/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.7/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.7/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.7/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.7/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.7/metadata/annotations.yaml, operators/gitops-primer/0.0.7/tests/scorecard/config.yaml
=> operators gitops-primer (0.0.7)

operators/external-secrets-operator/0.5.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.5.0/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.5.0/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.5.0/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.5.0/metadata/annotations.yaml, operators/external-secrets-operator/0.5.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.0
=> operators external-secrets-operator (0.5.0)

operators/external-secrets-operator/0.5.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.5.1/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.5.1/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.5.1/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.5.1/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.5.1/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.5.1/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.5.1/metadata/annotations.yaml, operators/external-secrets-operator/0.5.1/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.1
=> operators external-secrets-operator (0.5.1)

operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.48.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.48.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.48.0)

operators/microcks/1.5.1/microcks-operator.v1.5.1.clusterserviceversion.yaml, operators/microcks/1.5.1/microcksinstall.crd.yaml, operators/microcks/microcks.package.yaml
=> operators microcks (1.5.1)

operators/dell-csm-operator/0.1.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml, operators/dell-csm-operator/0.1.0/manifests/dell-csm-operator.v0.1.0.clusterserviceversion.yaml, operators/dell-csm-operator/0.1.0/metadata/annotations.yaml, operators/dell-csm-operator/0.1.0/tests/scorecard/config.yaml, operators/dell-csm-operator/ci.yaml
=> operators [N] [CI] dell-csm-operator (0.1.0)

operators/kiali/1.49.0/bundle.Dockerfile, operators/kiali/1.49.0/manifests/kiali.crd.yaml, operators/kiali/1.49.0/manifests/kiali.v1.49.0.clusterserviceversion.yaml, operators/kiali/1.49.0/metadata/annotations.yaml
=> operators kiali (1.49.0)

operators/dynatrace-operator/0.5.1/Dockerfile, operators/dynatrace-operator/0.5.1/manifests/dynatrace-activegate_v1_serviceaccount.yaml, operators/dynatrace-operator/0.5.1/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.5.1/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.5.1/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.5.1/metadata/annotations.yaml
=> operators dynatrace-operator (0.5.1)

operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.24.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.24.0/victoriametrics-operator.0.24.0.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.24.0)

operators/project-quay/3.7.0-rc.1/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.0-rc.2/quay-operator.clusterserviceversion.yaml
* Resolves issue with missing clair tag
=> operators [R] project-quay (3.7.0-rc.1 3.7.0-rc.2)

operators/namespace-configuration-operator/1.2.3/Dockerfile, operators/namespace-configuration-operator/1.2.3/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.2.3/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.2.3/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.2.3/manifests/namespace-configuration-operator-metrics-service_v1_service.yaml, operators/namespace-configuration-operator/1.2.3/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/namespace-configuration-operator/1.2.3/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/namespace-configuration-operator/1.2.3/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.2.3/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.2.3/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.2.3/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.2.3/metadata/annotations.yaml, operators/namespace-configuration-operator/1.2.3/tests/scorecard/config.yaml
=> operators namespace-configuration-operator (1.2.3)

operators/vault-config-operator/0.4.1/Dockerfile, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_authenginemounts.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_databasesecretengineconfigs.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_databasesecretengineroles.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_githubsecretengineconfigs.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_githubsecretengineroles.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_kubernetesauthengineroles.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_passwordpolicies.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_pkisecretengineconfigs.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_pkisecretengineroles.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_policies.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_quaysecretengineconfigs.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_quaysecretengineroles.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_quaysecretenginestaticroles.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_rabbitmqsecretengineconfigs.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_rabbitmqsecretengineroles.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_randomsecrets.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_secretenginemounts.yaml, operators/vault-config-operator/0.4.1/manifests/redhatcop.redhat.io_vaultsecrets.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator-controller-manager-metrics-service_v1_service.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator-manager-config_v1_configmap.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator-webhook-service_v1_service.yaml, operators/vault-config-operator/0.4.1/manifests/vault-config-operator.clusterserviceversion.yaml, operators/vault-config-operator/0.4.1/metadata/annotations.yaml, operators/vault-config-operator/0.4.1/tests/scorecard/config.yaml
=> operators vault-config-operator (0.4.1)

operators/neuvector-community-operator/1.3.3/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.3/neuvector-operator.v1.3.3.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operators neuvector-community-operator (1.3.3)

operators/cert-utils-operator/1.3.9/Dockerfile, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator-certificate-rule-alerts_monitoring.coreos.com_v1_prometheusrule.yaml, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator-controller-manager-metrics-service_v1_service.yaml, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/cert-utils-operator/1.3.9/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.9/metadata/annotations.yaml, operators/cert-utils-operator/1.3.9/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.9)

operators/portworx-essentials/1.7.1/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.7.1/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.7.1/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operators portworx-essentials (1.7.1)

operators/portworx-essentials/1.8.0/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.8.0/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.8.0/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
=> operators portworx-essentials (1.8.0)

operators/gitlab-operator-kubernetes/0.6.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.6.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.6.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.6.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.6.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.6.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.6.1/tests/scorecard/config.yaml, operators/gitlab-operator-kubernetes/ci.yaml
=> operators [N] [CI] gitlab-operator-kubernetes (0.6.1)

operators/ack-memorydb-controller/ci.yaml
=> operators [CI] ack-memorydb-controller

operators/argocd-operator/0.3.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml, operators/argocd-operator/0.3.0/argocd-operator-manager-config_v1_configmap.yaml, operators/argocd-operator/0.3.0/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml, operators/argocd-operator/0.3.0/argoproj.io_applications.yaml, operators/argocd-operator/0.3.0/argoproj.io_applicationsets.yaml, operators/argocd-operator/0.3.0/argoproj.io_appprojects.yaml, operators/argocd-operator/0.3.0/argoproj.io_argocdexports.yaml, operators/argocd-operator/0.3.0/argoproj.io_argocds.yaml, operators/argocd-operator/argocd-operator.package.yaml
=> operators argocd-operator (0.3.0)

operators/yaks/0.10.0/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.10.0/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.10.0/yaks.v0.10.0.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operators yaks (0.10.0)

operators/gitlab-runner-operator/1.8.0/bundle.Dockerfile, operators/gitlab-runner-operator/1.8.0/manifests/apps.gitlab.com_runners.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml, operators/gitlab-runner-operator/1.8.0/manifests/gitlab-runner-webhook-service_v1_service.yaml, operators/gitlab-runner-operator/1.8.0/metadata/annotations.yaml, operators/gitlab-runner-operator/1.8.0/tests/scorecard/config.yaml
Signed-off-by: ggeorgiev_gitlab <ggeorgiev@gitlab.com>
--
=> operators gitlab-runner-operator (1.8.0)

operators/volume-expander-operator/0.3.5/Dockerfile, operators/volume-expander-operator/0.3.5/manifests/volume-expander-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/volume-expander-operator/0.3.5/manifests/volume-expander-operator-controller-manager-metrics_v1_service.yaml, operators/volume-expander-operator/0.3.5/manifests/volume-expander-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/volume-expander-operator/0.3.5/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/volume-expander-operator/0.3.5/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/volume-expander-operator/0.3.5/manifests/volume-expander-operator.clusterserviceversion.yaml, operators/volume-expander-operator/0.3.5/metadata/annotations.yaml, operators/volume-expander-operator/0.3.5/tests/scorecard/config.yaml
=> operators volume-expander-operator (0.3.5)

operators/camel-k/1.5.0/metadata/annotations.yaml, operators/camel-k/1.5.1/metadata/annotations.yaml, operators/camel-k/1.6.0/metadata/annotations.yaml, operators/camel-k/1.6.1/metadata/annotations.yaml, operators/camel-k/1.7.0/metadata/annotations.yaml, operators/camel-k/1.8.0/metadata/annotations.yaml, operators/camel-k/1.8.1/metadata/annotations.yaml, operators/camel-k/1.8.2/metadata/annotations.yaml, operators/camel-k/1.9.0/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.9.0/manifests/camel-k.v1.9.0.clusterserviceversion.yaml, operators/camel-k/1.9.0/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.9.0/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.9.0/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.9.0/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.9.0/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.9.0/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.9.0/metadata/annotations.yaml, operators/camel-k/1.9.0/tests/scorecard/config.yaml
=> operators [R] camel-k (1.5.0 1.5.1 1.6.0 1.6.1 1.7.0 1.8.0 1.8.1 1.8.2 1.9.0)

operators/group-sync-operator/0.0.18/Dockerfile, operators/group-sync-operator/0.0.18/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.18/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.18/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.18/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.18/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.18/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.18/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.18/metadata/annotations.yaml, operators/group-sync-operator/0.0.18/tests/scorecard/config.yaml
=> operators group-sync-operator (0.0.18)

operators/volume-expander-operator/0.3.5/manifests/volume-expander-operator.clusterserviceversion.yaml
=> operators [O] volume-expander-operator (0.3.5)

operators/snyk-operator/1.88.4/snyk-operator.v1.88.4.clusterserviceversion.yaml, operators/snyk-operator/1.88.4/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.88.4)

operators/silicom-sts-operator/0.0.5/bundle.Dockerfile, operators/silicom-sts-operator/0.0.5/manifests/silicom-sts-operator.clusterserviceversion.yaml, operators/silicom-sts-operator/0.0.5/manifests/sts-controller-manager-metrics-service_v1_service.yaml, operators/silicom-sts-operator/0.0.5/manifests/sts-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/silicom-sts-operator/0.0.5/manifests/sts.silicom.com_stsconfigs.yaml, operators/silicom-sts-operator/0.0.5/manifests/sts.silicom.com_stsnodes.yaml, operators/silicom-sts-operator/0.0.5/manifests/sts.silicom.com_stsoperatorconfigs.yaml, operators/silicom-sts-operator/0.0.5/metadata/annotations.yaml, operators/silicom-sts-operator/0.0.5/tests/scorecard/config.yaml
=> operators silicom-sts-operator (0.0.5)

operators/external-secrets-operator/0.5.2/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.5.2/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.5.2/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.5.2/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.5.2/metadata/annotations.yaml, operators/external-secrets-operator/0.5.2/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.2
=> operators external-secrets-operator (0.5.2)

operators/mta-operator/0.0.10/Dockerfile, operators/mta-operator/0.0.10/manifests/windup-operator.v0.0.10.clusterserviceversion.yaml, operators/mta-operator/0.0.10/manifests/windup.crd.yaml, operators/mta-operator/0.0.10/metadata/annotations.yaml
=> operators mta-operator (0.0.10)

operators/pulp-operator/0.9.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.9.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.9.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.9.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.9.0/manifests/pulp-operator.v0.9.0.clusterserviceversion.yaml, operators/pulp-operator/0.9.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.9.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.9.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.9.0/metadata/annotations.yaml, operators/pulp-operator/0.9.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.9.0)

operators/silicom-sts-operator/0.0.6/bundle.Dockerfile, operators/silicom-sts-operator/0.0.6/manifests/silicom-sts-operator.clusterserviceversion.yaml, operators/silicom-sts-operator/0.0.6/manifests/sts-controller-manager-metrics-service_v1_service.yaml, operators/silicom-sts-operator/0.0.6/manifests/sts-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/silicom-sts-operator/0.0.6/manifests/sts.silicom.com_stsconfigs.yaml, operators/silicom-sts-operator/0.0.6/manifests/sts.silicom.com_stsnodes.yaml, operators/silicom-sts-operator/0.0.6/manifests/sts.silicom.com_stsoperatorconfigs.yaml, operators/silicom-sts-operator/0.0.6/metadata/annotations.yaml, operators/silicom-sts-operator/0.0.6/tests/scorecard/config.yaml
=> operators silicom-sts-operator (0.0.6)

operators/project-quay/3.7.0-rc.3/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.0-rc.3/quayecosystems.crd.yaml, operators/project-quay/3.7.0-rc.3/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.0-rc.3 to community operators
=> operators project-quay (3.7.0-rc.3)

operators/shipwright-operator/0.9.0/manifests/operator.shipwright.io_shipwrightbuilds.yaml, operators/shipwright-operator/0.9.0/manifests/shipwright-operator-manager-config_v1_configmap.yaml, operators/shipwright-operator/0.9.0/manifests/shipwright-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/shipwright-operator/0.9.0/manifests/shipwright-operator-metrics-service_v1_service.yaml, operators/shipwright-operator/0.9.0/manifests/shipwright-operator.clusterserviceversion.yaml, operators/shipwright-operator/0.9.0/metadata/annotations.yaml, operators/shipwright-operator/0.9.0/tests/scorecard/config.yaml, operators/shipwright-operator/ci.yaml
Add Shipwright Operator to the Red Hat Community operators. This will
let OpenShift users install Shipwright. Installing Shipwright will also
install OpenShift Pipelines if it has not been installed already.
-- …
=> operators [N] [CI] shipwright-operator (0.9.0)

operators/grafana-operator/4.3.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.3.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.3.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.3.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.3.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.3.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.3.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.3.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
Signed-off-by: edvin norling <edvin.norling@gmail.com>
--
=> operators grafana-operator (4.3.0)

operators/silicom-sts-operator/0.0.6/manifests/silicom-sts-operator.clusterserviceversion.yaml
=> operators [O] silicom-sts-operator (0.0.6)

operators/postgresql/4.7.5/Dockerfile, operators/postgresql/4.7.5/manifests/pgclusters.crunchydata.com.crd.yaml, operators/postgresql/4.7.5/manifests/pgpolicies.crunchydata.com.crd.yaml, operators/postgresql/4.7.5/manifests/pgreplicas.crunchydata.com.crd.yaml, operators/postgresql/4.7.5/manifests/pgtasks.crunchydata.com.crd.yaml, operators/postgresql/4.7.5/manifests/postgresoperator.v4.7.5.clusterserviceversion.yaml, operators/postgresql/4.7.5/metadata/annotations.yaml
* [] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [] Have you tested your Operator with all Custom Resource Definitions?
* [] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [] Have you considered whether you want use [semantic versioning …
=> operators postgresql (4.7.5)

operators/node-maintenance-operator/0.12.1/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml, operators/node-maintenance-operator/0.12.1/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-maintenance-operator/0.12.1/manifests/node-maintenance-operator-webhook-service_v1_service.yaml, operators/node-maintenance-operator/0.12.1/manifests/node-maintenance-operator.clusterserviceversion.yaml, operators/node-maintenance-operator/0.12.1/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml, operators/node-maintenance-operator/0.12.1/metadata/annotations.yaml, operators/node-maintenance-operator/0.12.1/tests/scorecard/config.yaml, operators/node-maintenance-operator/ci.yaml
=> operators [N] [CI] node-maintenance-operator (0.12.1)

operators/kiali/1.50.0/bundle.Dockerfile, operators/kiali/1.50.0/manifests/kiali.crd.yaml, operators/kiali/1.50.0/manifests/kiali.v1.50.0.clusterserviceversion.yaml, operators/kiali/1.50.0/metadata/annotations.yaml
=> operators kiali (1.50.0)

operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.48.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.48.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.48.0/tests/scorecard/config.yaml, operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.49.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.49.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.49.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.49.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.49.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.49.0)

operators/percona-postgresql-operator/1.2.0/manifests/percona-postgresql-operator.v1.2.0.clusterserviceversion.yaml, operators/percona-postgresql-operator/1.2.0/manifests/perconapgclusters.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.2.0/manifests/pgclusters.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.2.0/manifests/pgpolicies.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.2.0/manifests/pgreplicas.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.2.0/manifests/pgtasks.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.2.0/metadata/annotations.yaml, operators/percona-postgresql-operator/ci.yaml
=> operators [N] [CI] percona-postgresql-operator (1.2.0)

operators/opendatahub-operator/ci.yaml
=> operators [CI] opendatahub-operator

operators/netobserv-operator/0.1.2/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/0.1.2/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/0.1.2/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/0.1.2/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/0.1.2/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/0.1.2/metadata/annotations.yaml
=> operators netobserv-operator (0.1.2)

operators/opendatahub-operator/1.2.0/manifests/kfdef.apps.kubeflow.org.crd.yaml, operators/opendatahub-operator/1.2.0/manifests/opendatahub-operator.v1.2.0.clusterserviceversion.yaml, operators/opendatahub-operator/1.2.0/metadata/annotations.yaml
=> operators opendatahub-operator (1.2.0)

operators/verticadb-operator/1.4.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.4.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.4.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.4.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.4.0/metadata/annotations.yaml, operators/verticadb-operator/1.4.0/tests/scorecard/config.yaml
Signed-off-by: Matt Spilchen <matt.spilchen@microfocus.com>
--
=> operators verticadb-operator (1.4.0)

operators/ibm-spectrum-scale-csi-operator/2.5.1/csiscaleoperators.csi.ibm.com.crd.yaml, operators/ibm-spectrum-scale-csi-operator/2.5.1/ibm-spectrum-scale-csi-operator.v2.5.1.clusterserviceversion.yaml, operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
=> operators ibm-spectrum-scale-csi-operator (2.5.1)

operators/volume-expander-operator/0.3.6/Dockerfile, operators/volume-expander-operator/0.3.6/manifests/volume-expander-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/volume-expander-operator/0.3.6/manifests/volume-expander-operator-controller-manager-metrics_v1_service.yaml, operators/volume-expander-operator/0.3.6/manifests/volume-expander-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/volume-expander-operator/0.3.6/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/volume-expander-operator/0.3.6/manifests/volume-expander-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/volume-expander-operator/0.3.6/manifests/volume-expander-operator.clusterserviceversion.yaml, operators/volume-expander-operator/0.3.6/metadata/annotations.yaml, operators/volume-expander-operator/0.3.6/tests/scorecard/config.yaml
=> operators volume-expander-operator (0.3.6)

operators/crane-operator/ci.yaml
=> operators [CI] crane-operator

operators/grafana-operator/4.4.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.4.1/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.4.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.4.1/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.4.1/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.4.1/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.4.1/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.4.1/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operators grafana-operator (4.4.1)

operators/ecr-secret-operator/0.3.1/manifests/ecr-secret-operator-controller-manager-metrics-service_v1_service.yaml, operators/ecr-secret-operator/0.3.1/manifests/ecr-secret-operator-manager-config_v1_configmap.yaml, operators/ecr-secret-operator/0.3.1/manifests/ecr-secret-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ecr-secret-operator/0.3.1/manifests/ecr-secret-operator.clusterserviceversion.yaml, operators/ecr-secret-operator/0.3.1/manifests/ecr-secret-sample_ecr.mobb.redhat.com_v1alpha1_secret.yaml, operators/ecr-secret-operator/0.3.1/manifests/ecr-secret_ecr.mobb.redhat.com_v1alpha1_secret.yaml, operators/ecr-secret-operator/0.3.1/manifests/ecr.mobb.redhat.com_secrets.yaml, operators/ecr-secret-operator/0.3.1/metadata/annotations.yaml, operators/ecr-secret-operator/0.3.1/tests/scorecard/config.yaml, operators/ecr-secret-operator/ci.yaml
Signed-off-by: Shaozhen Ding <shading@redhat.com>
--
=> operators [N] [CI] ecr-secret-operator (0.3.1)

operators/mongodb-atlas-kubernetes/0.8.1/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/0.8.1/manifests/atlas.mongodb.com_atlasclusters.yaml, operators/mongodb-atlas-kubernetes/0.8.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/0.8.1/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/0.8.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/0.8.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/0.8.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/0.8.1/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/0.8.1/tests/scorecard/config.yaml
Signed-off-by: Igor Karpukhin <karpukhinigor@gmail.com>
--
=> operators mongodb-atlas-kubernetes (0.8.1)

operators/app-director-operator/0.0.1/metadata/annotations.yaml, operators/app-director-operator/0.0.3/Dockerfile, operators/app-director-operator/0.0.3/manifests/app-director-controller-manager-metrics-service_v1_service.yaml, operators/app-director-operator/0.0.3/manifests/app-director-manager-config_v1_configmap.yaml, operators/app-director-operator/0.0.3/manifests/app-director-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/app-director-operator/0.0.3/manifests/app-director-operator.clusterserviceversion.yaml, operators/app-director-operator/0.0.3/manifests/appdirector.randoli.ca_clusterwideguvnors.yaml, operators/app-director-operator/0.0.3/manifests/appdirector.randoli.ca_guvnors.yaml, operators/app-director-operator/0.0.3/metadata/annotations.yaml, operators/app-director-operator/0.0.3/tests/scorecard/config.yaml, operators/app-director-operator/ci.yaml
Signed-off-by: Vanessa Rakoczy <vanessa.rakoczy@randoli.ca>
--
=> operators [R] [CI] app-director-operator (0.0.1 0.0.2 0.0.3)

operators/patch-operator/0.1.3/Dockerfile, operators/patch-operator/0.1.3/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.3/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.3/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.3/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.3/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.3/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.3/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.3/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.3/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.3/metadata/annotations.yaml, operators/patch-operator/0.1.3/tests/scorecard/config.yaml
=> operators patch-operator (0.1.3)

operators/patch-operator/0.1.4/Dockerfile, operators/patch-operator/0.1.4/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.4/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.4/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.4/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.4/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.4/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.4/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.4/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.4/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.4/metadata/annotations.yaml, operators/patch-operator/0.1.4/tests/scorecard/config.yaml
=> operators patch-operator (0.1.4)

operators/cert-utils-operator/1.3.10/Dockerfile, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator-certificate-rule-alerts_monitoring.coreos.com_v1_prometheusrule.yaml, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator-controller-manager-metrics-service_v1_service.yaml, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator-manager-config_v1_configmap.yaml, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/cert-utils-operator/1.3.10/manifests/cert-utils-operator.clusterserviceversion.yaml, operators/cert-utils-operator/1.3.10/metadata/annotations.yaml, operators/cert-utils-operator/1.3.10/tests/scorecard/config.yaml
=> operators cert-utils-operator (1.3.10)

operators/namespace-configuration-operator/1.2.4/Dockerfile, operators/namespace-configuration-operator/1.2.4/manifests/namespace-configuration-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/namespace-configuration-operator/1.2.4/manifests/namespace-configuration-operator-manager-config_v1_configmap.yaml, operators/namespace-configuration-operator/1.2.4/manifests/namespace-configuration-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/namespace-configuration-operator/1.2.4/manifests/namespace-configuration-operator-metrics-service_v1_service.yaml, operators/namespace-configuration-operator/1.2.4/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/namespace-configuration-operator/1.2.4/manifests/namespace-configuration-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/namespace-configuration-operator/1.2.4/manifests/namespace-configuration-operator.clusterserviceversion.yaml, operators/namespace-configuration-operator/1.2.4/manifests/redhatcop.redhat.io_groupconfigs.yaml, operators/namespace-configuration-operator/1.2.4/manifests/redhatcop.redhat.io_namespaceconfigs.yaml, operators/namespace-configuration-operator/1.2.4/manifests/redhatcop.redhat.io_userconfigs.yaml, operators/namespace-configuration-operator/1.2.4/metadata/annotations.yaml, operators/namespace-configuration-operator/1.2.4/tests/scorecard/config.yaml
=> operators namespace-configuration-operator (1.2.4)

operators/koku-metrics-operator/1.1.5/Dockerfile, operators/koku-metrics-operator/1.1.5/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.5/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.5/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.5/tests/scorecard/config.yaml
Signed-off-by: Corey Goodfred <cgoodfre@redhat.com>
--
=> operators koku-metrics-operator (1.1.5)

operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml, operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml, operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml, operators/beegfs-csi-driver-operator/1.2.2/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml, operators/beegfs-csi-driver-operator/1.2.2/metadata/annotations.yaml, operators/beegfs-csi-driver-operator/1.2.2/tests/scorecard/config.yaml
Signed-off-by: Eric Weber <eric.weber2@netapp.com>
--
=> operators beegfs-csi-driver-operator (1.2.2)

operators/multicluster-operators-subscription/0.4.0/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_subscriptionreports_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.0/apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.4.0/multicluster-operators-subscription.v0.4.0.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
Signed-off-by: Roke Jung <roke@redhat.com>
--
=> operators multicluster-operators-subscription (0.4.0)

operators/l5-operator/0.0.2/manifests/l5-operator.clusterserviceversion.yaml
=> operators [N] l5-operator (0.0.2)

operators/camel-k/1.9.1/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.9.1/manifests/camel-k.v1.9.1.clusterserviceversion.yaml, operators/camel-k/1.9.1/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.9.1/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.9.1/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.9.1/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.9.1/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.9.1/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.9.1/metadata/annotations.yaml, operators/camel-k/1.9.1/tests/scorecard/config.yaml
=> operators camel-k (1.9.1)

operators/pulp-operator/0.10.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.10.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.10.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.10.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.10.0/manifests/pulp-operator.v0.10.0.clusterserviceversion.yaml, operators/pulp-operator/0.10.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.10.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.10.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.10.0/metadata/annotations.yaml, operators/pulp-operator/0.10.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.10.0)

operators/cass-operator-community/1.10.4/manifests/cass-operator-manager-config_v1_configmap.yaml, operators/cass-operator-community/1.10.4/manifests/cass-operator-webhook-service_v1_service.yaml, operators/cass-operator-community/1.10.4/manifests/cass-operator.clusterserviceversion.yaml, operators/cass-operator-community/1.10.4/manifests/cassandra.datastax.com_cassandradatacenters.yaml, operators/cass-operator-community/1.10.4/manifests/control.k8ssandra.io_cassandratasks.yaml, operators/cass-operator-community/1.10.4/metadata/annotations.yaml, operators/cass-operator-community/1.10.4/tests/scorecard/config.yaml
Signed-off-by: Michael Burman <michael.burman@datastax.com>
--
=> operators cass-operator-community (1.10.4)

README.md
**Description**
add nit clarifications on the README
Signed-off-by: Camila Macedo <cmacedo@redhat.com>
Closes: https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/782
=> :book: add nit clarifications on the README

README.md
Signed-off-by: Camila Macedo <cmacedo@redhat.com>
: update readme with deprecations info accordingly
=> :book: update readme with deprecations info accordingly

operators/nfs-provisioner-operator/0.0.4/Dockerfile, operators/nfs-provisioner-operator/0.0.4/manifests/cache.jhouse.com_nfsprovisioners.yaml, operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml, operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.4/manifests/nfs-provisioner-operator.clusterserviceversion.yaml, operators/nfs-provisioner-operator/0.0.4/metadata/annotations.yaml, operators/nfs-provisioner-operator/0.0.4/tests/scorecard/config.yaml
=> operators nfs-provisioner-operator (0.0.4)

operators/neuvector-community-operator/1.3.4/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.4/neuvector-operator.v1.3.4.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operators neuvector-community-operator (1.3.4)

operators/microcks/1.5.2/microcks-operator.v1.5.2.clusterserviceversion.yaml, operators/microcks/1.5.2/microcksinstall.crd.yaml, operators/microcks/microcks.package.yaml
=> operators microcks (1.5.2)

operators/aqua/2022.4.1/manifests/aqua-operator.v2022.4.1.clusterserviceversion.yaml, operators/aqua/6.2.1/aqua-operator.v6.2.1.clusterserviceversion.yaml, operators/aqua/6.2.1/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/6.2.1/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/6.2.1/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.2.1/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/6.2.1/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.2.1/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/6.2.1/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aqua-operator.v6.5.0.clusterserviceversion.yaml, operators/aqua/6.5.0/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/6.5.0/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.5/manifests/aqua-operator.v6.5.5.clusterserviceversion.yaml, operators/aqua/6.5.5/metadata/annotations.yaml
=> operators [R] aqua (2022.4.1 6.2.1 6.5.0 6.5.5)

operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.25.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.25.0/victoriametrics-operator.0.25.0.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.25.0)

operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.25.1/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.25.1/victoriametrics-operator.0.25.1.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operators victoriametrics-operator (0.25.1)

operators/mongodb-atlas-kubernetes/1.0.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.0.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.0.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.0.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.0.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.0.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.0.0/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
=> operators mongodb-atlas-kubernetes (1.0.0)

operators/opentelemetry-operator/0.51.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.51.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.51.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.51.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.51.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.51.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.51.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.51.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.51.0)

operators/project-quay/3.7.0/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.0/quayecosystems.crd.yaml, operators/project-quay/3.7.0/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Signed-off-by: Dave O'Connor <doconnor@redhat.com>
--
=> operators project-quay (3.7.0)

operators/keda/2.7.1/manifests/keda.sh_clustertriggerauthentications.yaml, operators/keda/2.7.1/manifests/keda.sh_kedacontrollers.yaml, operators/keda/2.7.1/manifests/keda.sh_scaledjobs.yaml, operators/keda/2.7.1/manifests/keda.sh_scaledobjects.yaml, operators/keda/2.7.1/manifests/keda.sh_triggerauthentications.yaml, operators/keda/2.7.1/manifests/keda.v2.7.1.clusterserviceversion.yaml, operators/keda/2.7.1/metadata/annotations.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
--
=> operators keda (2.7.1)

operators/snyk-operator/1.90.1/snyk-operator.v1.90.1.clusterserviceversion.yaml, operators/snyk-operator/1.90.1/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.90.1)

operators/flux/0.30.2/manifests/alert.crd.yaml, operators/flux/0.30.2/manifests/bucket.crd.yaml, operators/flux/0.30.2/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.30.2/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.30.2/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.30.2/manifests/flux.v0.30.2.clusterserviceversion.yaml, operators/flux/0.30.2/manifests/gitrepository.crd.yaml, operators/flux/0.30.2/manifests/helmchart.crd.yaml, operators/flux/0.30.2/manifests/helmrelease.crd.yaml, operators/flux/0.30.2/manifests/helmrepository.crd.yaml, operators/flux/0.30.2/manifests/imagepolicy.crd.yaml, operators/flux/0.30.2/manifests/imagerepository.crd.yaml, operators/flux/0.30.2/manifests/imageupdateautomation.crd.yaml, operators/flux/0.30.2/manifests/kustomization.crd.yaml, operators/flux/0.30.2/manifests/notification-controller.service.yaml, operators/flux/0.30.2/manifests/provider.crd.yaml, operators/flux/0.30.2/manifests/receiver.crd.yaml, operators/flux/0.30.2/manifests/source-controller.service.yaml, operators/flux/0.30.2/manifests/webhook-receiver.service.yaml, operators/flux/0.30.2/metadata/annotations.yaml
=> operators flux (0.30.2)

operators/group-sync-operator/0.0.19/Dockerfile, operators/group-sync-operator/0.0.19/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.19/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.19/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.19/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.19/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.19/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.19/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.19/metadata/annotations.yaml, operators/group-sync-operator/0.0.19/tests/scorecard/config.yaml
=> operators group-sync-operator (0.0.19)

operators/kiali/1.51.0/bundle.Dockerfile, operators/kiali/1.51.0/manifests/kiali.crd.yaml, operators/kiali/1.51.0/manifests/kiali.v1.51.0.clusterserviceversion.yaml, operators/kiali/1.51.0/metadata/annotations.yaml
=> operators kiali (1.51.0)

operators/pulsar-operator/0.10.3/bundle.Dockerfile, operators/pulsar-operator/0.10.3/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar-operator.clusterserviceversion.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarbrokers.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarconnections.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarnamespaces.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarpermissions.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsarproxies.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsartenants.yaml, operators/pulsar-operator/0.10.3/manifests/pulsar.streamnative.io_pulsartopics.yaml, operators/pulsar-operator/0.10.3/metadata/annotations.yaml, operators/pulsar-operator/0.10.3/tests/scorecard/config.yaml
=> operators [N] pulsar-operator (0.10.3)

operators/bookkeeper-operator/0.10.3/bundle.Dockerfile, operators/bookkeeper-operator/0.10.3/manifests/bookkeeper-operator-controller-manager-metrics-service_v1_service.yaml, operators/bookkeeper-operator/0.10.3/manifests/bookkeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bookkeeper-operator/0.10.3/manifests/bookkeeper-operator.clusterserviceversion.yaml, operators/bookkeeper-operator/0.10.3/manifests/bookkeeper.streamnative.io_bookkeeperclusters.yaml, operators/bookkeeper-operator/0.10.3/metadata/annotations.yaml, operators/bookkeeper-operator/0.10.3/tests/scorecard/config.yaml
=> operators [N] bookkeeper-operator (0.10.3)

operators/zookeeper-operator/0.10.3/bundle.Dockerfile, operators/zookeeper-operator/0.10.3/manifests/zookeeper-operator-controller-manager-metrics-service_v1_service.yaml, operators/zookeeper-operator/0.10.3/manifests/zookeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/zookeeper-operator/0.10.3/manifests/zookeeper-operator.clusterserviceversion.yaml, operators/zookeeper-operator/0.10.3/manifests/zookeeper.streamnative.io_zookeeperclusters.yaml, operators/zookeeper-operator/0.10.3/metadata/annotations.yaml, operators/zookeeper-operator/0.10.3/tests/scorecard/config.yaml
=> operators [N] zookeeper-operator (0.10.3)

operators/external-secrets-operator/0.5.4/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.5.4/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.5.4/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.5.4/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.5.4/metadata/annotations.yaml, operators/external-secrets-operator/0.5.4/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.4
=> operators external-secrets-operator (0.5.4)

operators/gitlab-runner-operator/1.9.0/bundle.Dockerfile, operators/gitlab-runner-operator/1.9.0/manifests/apps.gitlab.com_runners.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml, operators/gitlab-runner-operator/1.9.0/manifests/gitlab-runner-webhook-service_v1_service.yaml, operators/gitlab-runner-operator/1.9.0/metadata/annotations.yaml, operators/gitlab-runner-operator/1.9.0/tests/scorecard/config.yaml
=> operators gitlab-runner-operator (1.9.0)

operators/external-secrets-operator/0.5.5/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.5.5/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.5.5/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.5.5/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.5.5/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.5.5/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.5.5/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.5.5/metadata/annotations.yaml, operators/external-secrets-operator/0.5.5/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.5
=> operators external-secrets-operator (0.5.5)

operators/zookeeper-operator/0.11.0/bundle.Dockerfile, operators/zookeeper-operator/0.11.0/manifests/zookeeper-operator-controller-manager-metrics-service_v1_service.yaml, operators/zookeeper-operator/0.11.0/manifests/zookeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/zookeeper-operator/0.11.0/manifests/zookeeper-operator.clusterserviceversion.yaml, operators/zookeeper-operator/0.11.0/manifests/zookeeper.streamnative.io_zookeeperclusters.yaml, operators/zookeeper-operator/0.11.0/metadata/annotations.yaml, operators/zookeeper-operator/0.11.0/tests/scorecard/config.yaml
=> operators zookeeper-operator (0.11.0)

operators/pulsar-operator/0.11.0/bundle.Dockerfile, operators/pulsar-operator/0.11.0/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar-operator.clusterserviceversion.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarbrokers.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarconnections.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarnamespaces.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarpermissions.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsarproxies.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsartenants.yaml, operators/pulsar-operator/0.11.0/manifests/pulsar.streamnative.io_pulsartopics.yaml, operators/pulsar-operator/0.11.0/metadata/annotations.yaml, operators/pulsar-operator/0.11.0/tests/scorecard/config.yaml
=> operators pulsar-operator (0.11.0)

operators/external-secrets-operator/0.5.6/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.5.6/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.5.6/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.5.6/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.5.6/metadata/annotations.yaml, operators/external-secrets-operator/0.5.6/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.6
=> operators external-secrets-operator (0.5.6)

operators/pulp-operator/0.11.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.11.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.11.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.11.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.11.0/manifests/pulp-operator.v0.11.0.clusterserviceversion.yaml, operators/pulp-operator/0.11.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.11.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.11.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.11.0/metadata/annotations.yaml, operators/pulp-operator/0.11.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.11.0)

operators/verticadb-operator/1.5.0/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.5.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.5.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.5.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/verticadb-operator/1.5.0/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.5.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.5.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.5.0/metadata/annotations.yaml, operators/verticadb-operator/1.5.0/tests/scorecard/config.yaml
Signed-off-by: Matt Spilchen <matt.spilchen@microfocus.com>
--
=> operators verticadb-operator (1.5.0)

operators/tackle-operator/ci.yaml
=> operators [CI] tackle-operator

operators/community-windows-machine-config-operator/5.1.0/manifests/community-windows-machine-config-operator.5.1.0.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/5.1.0/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/5.1.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/5.1.0/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/5.1.0/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/5.1.0/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/5.1.0/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/5.1.0/metadata/annotations.yaml
Signed-off-by: Alina Ryan aliryan@redhat.com
--
=> operators community-windows-machine-config-operator (5.1.0)

operators/community-windows-machine-config-operator/ci.yaml
Update WINC team members in WMCO ci.yaml 
Signed-off-by: selansen <esiva@redhat.com>
--
=> operators [CI] community-windows-machine-config-operator

operators/opentelemetry-operator/0.52.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.52.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.52.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.52.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.52.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.52.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.52.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.52.0/tests/scorecard/config.yaml
=> operators opentelemetry-operator (0.52.0)

operators/multicluster-operators-subscription/0.4.1/app.k8s.io_applications_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_channels_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_deployables_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_gitopsclusters_crd_v1beta1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_helmreleases_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_placementrules_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_subscriptionreports_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_subscriptions_crd_v1.yaml, operators/multicluster-operators-subscription/0.4.1/apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml, operators/multicluster-operators-subscription/0.4.1/multicluster-operators-subscription.v0.4.1.clusterserviceversion.yaml, operators/multicluster-operators-subscription/multicluster-operators-subscription.package.yaml
=> operators multicluster-operators-subscription (0.4.1)

operators/project-quay/3.7.1/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.1/quayecosystems.crd.yaml, operators/project-quay/3.7.1/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.1 to community operators
=> operators project-quay (3.7.1)

operators/pulp-operator/0.11.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.11.1/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.11.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.11.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.11.1/manifests/pulp-operator.v0.11.1.clusterserviceversion.yaml, operators/pulp-operator/0.11.1/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.11.1/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.11.1/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.11.1/metadata/annotations.yaml, operators/pulp-operator/0.11.1/tests/scorecard/config.yaml
=> operators pulp-operator (0.11.1)

operators/snyk-operator/1.92.0/snyk-operator.v1.92.0.clusterserviceversion.yaml, operators/snyk-operator/1.92.0/snykmonitors.charts.helm.k8s.io.crd.yaml, operators/snyk-operator/snyk-operator.package.yaml
=> operators snyk-operator (1.92.0)

operators/aqua/2022.4.2/bundle.Dockerfile, operators/aqua/2022.4.2/manifests/aqua-operator.v2022.4.2.clusterserviceversion.yaml, operators/aqua/2022.4.2/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.2/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.2/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.2/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.2/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.2/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.2/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.2/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.2/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.2/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.2/metadata/annotations.yaml
=> operators aqua (2022.4.2)

operators/aqua/6.5.6/bundle.Dockerfile, operators/aqua/6.5.6/manifests/aqua-operator.v6.5.6.clusterserviceversion.yaml, operators/aqua/6.5.6/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/6.5.6/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/6.5.6/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.6/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/6.5.6/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.6/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/6.5.6/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.6/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.6/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.6/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.6/metadata/annotations.yaml
=> operators aqua (6.5.6)

operators/tackle-operator/2.0.0/manifests/tackle-operator.clusterserviceversion.yaml, operators/tackle-operator/2.0.0/manifests/tackle.konveyor.io_addons.yaml, operators/tackle-operator/2.0.0/manifests/tackle.konveyor.io_tackles.yaml, operators/tackle-operator/2.0.0/metadata/annotations.yaml, operators/tackle-operator/ci.yaml
=> operators [CI] tackle-operator (2.0.0)

operators/ack-emrcontainers-controller/ci.yaml
=> operators [CI] ack-emrcontainers-controller

operators/pulp-operator/0.12.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.12.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.12.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.12.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.12.0/manifests/pulp-operator.v0.12.0.clusterserviceversion.yaml, operators/pulp-operator/0.12.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.12.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.12.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.12.0/metadata/annotations.yaml, operators/pulp-operator/0.12.0/tests/scorecard/config.yaml
=> operators pulp-operator (0.12.0)

operators/hazelcast-platform-operator/ci.yaml
=> operators [CI] hazelcast-platform-operator

operators/project-quay/3.7.2/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.2/quayecosystems.crd.yaml, operators/project-quay/3.7.2/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.2 to community operators
=> operators project-quay (3.7.2)

operators/portworx-essentials/1.8.1/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.8.1/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.8.1/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
Signed-off-by: Jiafeng Liao <jliao@purestorage.com>
--
=> operators portworx-essentials (1.8.1)

operators/dynatrace-operator/0.7.0/Dockerfile, operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.7.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.7.0/metadata/annotations.yaml
=> operators dynatrace-operator (0.7.0)

operators/ibm-spectrum-scale-csi-operator/2.6.0/csiscaleoperators.csi.ibm.com.crd.yaml, operators/ibm-spectrum-scale-csi-operator/2.6.0/ibm-spectrum-scale-csi-operator.v2.6.0.clusterserviceversion.yaml, operators/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
=> operator ibm-spectrum-scale-csi-operator (2.6.0)

operators/kubernetes-imagepuller-operator/1.0.1/che.eclipse.org_kubernetesimagepullers_crd.yaml, operators/kubernetes-imagepuller-operator/1.0.1/controller-manager-metrics-service_v1_service.yaml, operators/kubernetes-imagepuller-operator/1.0.1/kubernetes-imagepuller-operator.v1.0.1.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/1.0.1/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: David Kwon <dakwon@redhat.com>
--
=> operator kubernetes-imagepuller-operator (1.0.1)

operators/koku-metrics-operator/1.1.6/Dockerfile, operators/koku-metrics-operator/1.1.6/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.6/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.6/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.6/tests/scorecard/config.yaml
Signed-off-by: Michael Skarbek <mskarbek@redhat.com>
--
=> operator koku-metrics-operator (1.1.6)

operators/netobserv-operator/0.1.3/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/0.1.3/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/0.1.3/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/0.1.3/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/0.1.3/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/0.1.3/metadata/annotations.yaml
=> operator netobserv-operator (0.1.3)

operators/zookeeper-operator/0.11.5/bundle.Dockerfile, operators/zookeeper-operator/0.11.5/manifests/zookeeper-operator-controller-manager-metrics-service_v1_service.yaml, operators/zookeeper-operator/0.11.5/manifests/zookeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/zookeeper-operator/0.11.5/manifests/zookeeper-operator.clusterserviceversion.yaml, operators/zookeeper-operator/0.11.5/manifests/zookeeper.streamnative.io_zookeeperclusters.yaml, operators/zookeeper-operator/0.11.5/metadata/annotations.yaml, operators/zookeeper-operator/0.11.5/tests/scorecard/config.yaml
=> operator zookeeper-operator (0.11.5)

operators/pulsar-operator/0.11.5/bundle.Dockerfile, operators/pulsar-operator/0.11.5/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar-operator.clusterserviceversion.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsarbrokers.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsarconnections.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsarnamespaces.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsarpermissions.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsarproxies.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsartenants.yaml, operators/pulsar-operator/0.11.5/manifests/pulsar.streamnative.io_pulsartopics.yaml, operators/pulsar-operator/0.11.5/metadata/annotations.yaml, operators/pulsar-operator/0.11.5/tests/scorecard/config.yaml
=> operator pulsar-operator (0.11.5)

operators/verticadb-operator/1.6.0/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.6.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.6.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.6.0/manifests/verticadb-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/verticadb-operator/1.6.0/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.6.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.6.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.6.0/metadata/annotations.yaml, operators/verticadb-operator/1.6.0/tests/scorecard/config.yaml
Signed-off-by: Matt Spilchen <matt.spilchen@microfocus.com>
--
=> operator verticadb-operator (1.6.0)

operators/mongodb-atlas-kubernetes/1.1.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.1.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.1.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.1.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.1.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.1.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.1.0/tests/scorecard/config.yaml
Signed-off-by: Julien Benhaim <julien.benhaim@mongodb.com>
--
=> operator mongodb-atlas-kubernetes (1.1.0)

operators/strimzi-kafka-operator/0.29.0/strimzi-cluster-operator.v0.29.0.clusterserviceversion.yaml
Signed-off-by: Paolo Patierno <ppatierno@live.com>
--
=> operator [O] strimzi-kafka-operator (0.29.0)

operators/dell-csi-operator/1.8.0/csiisilons.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.8.0/csipowermaxes.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.8.0/csipowermaxrevproxies.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.8.0/csipowerstores.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.8.0/csiunities.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.8.0/csivxflexoses.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.8.0/dell-csi-operator.v1.8.0.clusterserviceversion.yaml, operators/dell-csi-operator/dell-csi-operator.package.yaml
=> operator dell-csi-operator (1.8.0)

operators/pulp-operator/0.13.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.13.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.13.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.13.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.13.0/manifests/pulp-operator.v0.13.0.clusterserviceversion.yaml, operators/pulp-operator/0.13.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.13.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.13.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.13.0/metadata/annotations.yaml, operators/pulp-operator/0.13.0/tests/scorecard/config.yaml
=> operator pulp-operator (0.13.0)

operators/patterns-operator/0.0.4/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.4/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.4/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.4/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.4/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.4/metadata/annotations.yaml, operators/patterns-operator/0.0.4/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.4)

operators/kiali/1.53.0/bundle.Dockerfile, operators/kiali/1.53.0/manifests/kiali.crd.yaml, operators/kiali/1.53.0/manifests/kiali.v1.53.0.clusterserviceversion.yaml, operators/kiali/1.53.0/metadata/annotations.yaml
=> operator kiali (1.53.0)

operators/project-quay/3.7.3/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.3/quayecosystems.crd.yaml, operators/project-quay/3.7.3/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.3 to community operators
=> operator project-quay (3.7.3)

operators/koku-metrics-operator/1.1.7/Dockerfile, operators/koku-metrics-operator/1.1.7/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.7/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.7/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.7/tests/scorecard/config.yaml
Signed-off-by: Michael Skarbek <mskarbek@redhat.com>
--
=> operator koku-metrics-operator (1.1.7)

operators/dynatrace-operator/0.7.1/Dockerfile, operators/dynatrace-operator/0.7.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.7.1/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.7.1/metadata/annotations.yaml
=> operator dynatrace-operator (0.7.1)

operators/sosivio/1.4.1/manifests/sosivio-operator.clusterserviceversion.yaml, operators/sosivio/1.4.1/manifests/sosivio.crd.yaml, operators/sosivio/1.4.1/metadata/annotations.yaml
Signed-off-by: Dan Arlowski <dan@sosiv.io>
--
=> operator sosivio (1.4.1)

operators/nfs-provisioner-operator/0.0.5/Dockerfile, operators/nfs-provisioner-operator/0.0.5/manifests/cache.jhouse.com_nfsprovisioners.yaml, operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml, operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.5/manifests/nfs-provisioner-operator.clusterserviceversion.yaml, operators/nfs-provisioner-operator/0.0.5/metadata/annotations.yaml, operators/nfs-provisioner-operator/0.0.5/tests/scorecard/config.yaml
* [] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [] Have you tested your Operator with all Custom Resource Definitions?
* [] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [] Have you considered whether you want use [semantic …
=> operator nfs-provisioner-operator (0.0.5)

operators/opentelemetry-operator/0.54.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.54.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.54.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.54.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.54.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.54.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.54.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.54.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.54.0)

operators/sosivio/1.4.1-1/manifests/sosivio-operator.clusterserviceversion.yaml, operators/sosivio/1.4.1-1/manifests/sosivio.crd.yaml, operators/sosivio/1.4.1-1/metadata/annotations.yaml
Signed-off-by: Dan Arlowski <dan@sosiv.io>
--
=> operator sosivio (1.4.1-1)

operators/dell-csm-operator/0.2.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml, operators/dell-csm-operator/0.2.0/manifests/dell-csm-operator.v0.2.0.clusterserviceversion.yaml, operators/dell-csm-operator/0.2.0/metadata/annotations.yaml, operators/dell-csm-operator/0.2.0/tests/scorecard/config.yaml
=> operator dell-csm-operator (0.2.0)

operators/grafana-operator/4.5.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.5.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.5.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.5.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.5.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.5.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.5.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.5.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.5.0)

operators/community-trivy-operator/2.1.1/manifests/namespace-scanners.trivy-operator.devopstales.io.crd.yaml, operators/community-trivy-operator/2.1.1/manifests/trivy-operator.service.yaml, operators/community-trivy-operator/2.1.1/manifests/trivy-operator.v2.1.1.clusterserviceversion.yaml, operators/community-trivy-operator/2.1.1/metadata/annotations.yaml, operators/community-trivy-operator/2.2.0/manifests/namespace-scanners.trivy-operator.devopstales.io.crd.yaml, operators/community-trivy-operator/2.2.0/manifests/trivy-operator.service.yaml, operators/community-trivy-operator/2.2.0/manifests/trivy-operator.v2.2.0.clusterserviceversion.yaml, operators/community-trivy-operator/2.2.0/metadata/annotations.yaml, operators/community-trivy-operator/2.3.0/manifests/namespace-scanners.trivy-operator.devopstales.io.crd.yaml, operators/community-trivy-operator/2.3.0/manifests/trivy-operator.service.yaml, operators/community-trivy-operator/2.3.0/manifests/trivy-operator.v2.3.0.clusterserviceversion.yaml, operators/community-trivy-operator/2.3.0/metadata/annotations.yaml, operators/community-trivy-operator/2.4.0/manifests/VulnerabilityReport.yaml, operators/community-trivy-operator/2.4.0/manifests/namespace-scanners.trivy-operator.devopstales.io.crd.yaml, operators/community-trivy-operator/2.4.0/manifests/trivy-operator.service.yaml, operators/community-trivy-operator/2.4.0/manifests/trivy-operator.v2.4.0.clusterserviceversion.yaml, operators/community-trivy-operator/2.4.0/metadata/annotations.yaml, operators/community-trivy-operator/ci.yaml
Signed-off-by: devopstales <42894256+devopstales@users.noreply.github.com>
--
=> operator [R] [CI] community-trivy-operator (2.1.1 2.2.0 2.3.0 2.4.0)

operators/opentelemetry-operator/ci.yaml
=> operator [CI] opentelemetry-operator

operators/dynatrace-operator/0.7.2/Dockerfile, operators/dynatrace-operator/0.7.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.7.2/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.7.2/metadata/annotations.yaml
=> operator dynatrace-operator (0.7.2)

operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.55.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.55.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.55.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.55.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.55.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.55.0)

operators/neuvector-community-operator/1.3.5/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.5/neuvector-operator.v1.3.5.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operator neuvector-community-operator (1.3.5)

operators/istio-workspace-operator/0.5.1/manifests/istio-workspace-operator.clusterserviceversion.yaml, operators/istio-workspace-operator/0.5.1/manifests/workspace.maistra.io_sessions.yaml, operators/istio-workspace-operator/0.5.1/metadata/annotations.yaml, operators/istio-workspace-operator/0.5.1/tests/scorecard/config.yaml
=> operator istio-workspace-operator (0.5.1)

operators/seldon-operator/1.13.1/metadata/annotations.yaml
Update seldon-operator to run on OpenShift 4.10
---
--
=> operator [O] seldon-operator (1.13.1)

operators/community-windows-machine-config-operator/5.1.2/manifests/community-windows-machine-config-operator.5.1.2.clusterserviceversion.yaml, operators/community-windows-machine-config-operator/5.1.2/manifests/manager-role_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/5.1.2/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/community-windows-machine-config-operator/5.1.2/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/community-windows-machine-config-operator/5.1.2/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml, operators/community-windows-machine-config-operator/5.1.2/manifests/windows-exporter_v1_service.yaml, operators/community-windows-machine-config-operator/5.1.2/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml, operators/community-windows-machine-config-operator/5.1.2/metadata/annotations.yaml
Signed-off-by: Alina Ryan <aliryan@redhat.com>
--
=> operator community-windows-machine-config-operator (5.1.2)

operators/project-quay/3.7.4/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.4/quayecosystems.crd.yaml, operators/project-quay/3.7.4/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.4 to community operators
=> operator project-quay (3.7.4)

operators/group-sync-operator/0.0.20/Dockerfile, operators/group-sync-operator/0.0.20/manifests/group-sync-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/group-sync-operator/0.0.20/manifests/group-sync-operator-controller-manager-metrics-service_v1_service.yaml, operators/group-sync-operator/0.0.20/manifests/group-sync-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/group-sync-operator/0.0.20/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/group-sync-operator/0.0.20/manifests/group-sync-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/group-sync-operator/0.0.20/manifests/group-sync-operator.clusterserviceversion.yaml, operators/group-sync-operator/0.0.20/manifests/redhatcop.redhat.io_groupsyncs.yaml, operators/group-sync-operator/0.0.20/metadata/annotations.yaml, operators/group-sync-operator/0.0.20/tests/scorecard/config.yaml
=> operator group-sync-operator (0.0.20)

operators/flux/0.31.4/manifests/alert.crd.yaml, operators/flux/0.31.4/manifests/bucket.crd.yaml, operators/flux/0.31.4/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.31.4/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.31.4/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.31.4/manifests/flux.v0.31.4.clusterserviceversion.yaml, operators/flux/0.31.4/manifests/gitrepository.crd.yaml, operators/flux/0.31.4/manifests/helmchart.crd.yaml, operators/flux/0.31.4/manifests/helmrelease.crd.yaml, operators/flux/0.31.4/manifests/helmrepository.crd.yaml, operators/flux/0.31.4/manifests/imagepolicy.crd.yaml, operators/flux/0.31.4/manifests/imagerepository.crd.yaml, operators/flux/0.31.4/manifests/imageupdateautomation.crd.yaml, operators/flux/0.31.4/manifests/kustomization.crd.yaml, operators/flux/0.31.4/manifests/notification-controller.service.yaml, operators/flux/0.31.4/manifests/provider.crd.yaml, operators/flux/0.31.4/manifests/receiver.crd.yaml, operators/flux/0.31.4/manifests/source-controller.service.yaml, operators/flux/0.31.4/manifests/webhook-receiver.service.yaml, operators/flux/0.31.4/metadata/annotations.yaml
=> operator flux (0.31.4)

operators/grafana-operator/4.5.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.5.1/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.5.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.5.1/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.5.1/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.5.1/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.5.1/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.5.1/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.5.1)

operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.26.0/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.26.0/victoriametrics-operator.0.26.0.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operator victoriametrics-operator (0.26.0)

operators/opendatahub-operator/1.3.0/manifests/kfdef.apps.kubeflow.org.crd.yaml, operators/opendatahub-operator/1.3.0/manifests/opendatahub-operator.v1.3.0.clusterserviceversion.yaml, operators/opendatahub-operator/1.3.0/metadata/annotations.yaml
=> operator opendatahub-operator (1.3.0)

operators/aqua/2022.4.3/bundle.Dockerfile, operators/aqua/2022.4.3/manifests/aqua-operator.v2022.4.2.clusterserviceversion.yaml, operators/aqua/2022.4.3/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.3/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.3/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.3/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.3/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.3/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.3/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.3/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.3/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.3/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.3/metadata/annotations.yaml, operators/aqua/ci.yaml
Signed-off-by: koppularajender <koppularajender18@gmail.com>
--
=> operator [CI] aqua (2022.4.3)

operators/egressip-ipam-operator/1.2.4/Dockerfile, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator-controller-manager-metrics_v1_service.yaml, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator-egressip-utilization_monitoring.coreos.com_v1_prometheusrule.yaml, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator-manager-config_v1_configmap.yaml, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator.clusterserviceversion.yaml, operators/egressip-ipam-operator/1.2.4/manifests/redhatcop.redhat.io_egressipams.yaml, operators/egressip-ipam-operator/1.2.4/metadata/annotations.yaml, operators/egressip-ipam-operator/1.2.4/tests/scorecard/config.yaml
=> operator egressip-ipam-operator (1.2.4)

operators/klusterlet/0.8.0/klusterlet.v0.8.0.clusterserviceversion.yaml, operators/klusterlet/0.8.0/operator.open-cluster-management.io_klusterlets.yaml, operators/klusterlet/klusterlet.package.yaml
=> operator klusterlet (0.8.0)

operators/cluster-manager/0.8.0/cluster-manager.v0.8.0.clusterserviceversion.yaml, operators/cluster-manager/0.8.0/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/cluster-manger.package.yaml
=> operator cluster-manager (0.8.0)

operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.26.2/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.26.2/victoriametrics-operator.0.26.2.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operator victoriametrics-operator (0.26.2)

operators/argocd-operator/0.4.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml, operators/argocd-operator/0.4.0/argocd-operator-manager-config_v1_configmap.yaml, operators/argocd-operator/0.4.0/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/argocd-operator/0.4.0/argocd-operator.v0.4.0.clusterserviceversion.yaml, operators/argocd-operator/0.4.0/argoproj.io_applications.yaml, operators/argocd-operator/0.4.0/argoproj.io_applicationsets.yaml, operators/argocd-operator/0.4.0/argoproj.io_appprojects.yaml, operators/argocd-operator/0.4.0/argoproj.io_argocdexports.yaml, operators/argocd-operator/0.4.0/argoproj.io_argocds.yaml, operators/argocd-operator/argocd-operator.package.yaml, operators/argocd-operator/ci.yaml
Signed-off-by: ishitasequeira [ishiseq29@gmail.com](mailto:ishiseq29@@gmail.com)
--
=> operator [CI] argocd-operator (0.4.0)

operators/aerospike-kubernetes-operator/2.1.0/bundle.Dockerfile, operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml, operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml, operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.1.0/manifests/aerospike-operator-webhook-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.1.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml, operators/aerospike-kubernetes-operator/2.1.0/metadata/annotations.yaml, operators/aerospike-kubernetes-operator/2.1.0/tests/scorecard/config.yaml, operators/aerospike-kubernetes-operator/ci.yaml
Release aerospike-kubernetes-operator 2.1.0
Signed-off-by: Ashish Shinde <ashish@aerospike.com>
--
=> operator [CI] aerospike-kubernetes-operator (2.1.0)

operators/gitops-primer/ci.yaml
=> operator [CI] gitops-primer

operators/patch-operator/0.1.6/Dockerfile, operators/patch-operator/0.1.6/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.6/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.6/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.6/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.6/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.6/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.6/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.6/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.6/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.6/metadata/annotations.yaml, operators/patch-operator/0.1.6/tests/scorecard/config.yaml
=> operator patch-operator (0.1.6)

operators/opentelemetry-operator/0.56.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.56.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.56.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.56.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.56.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.56.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.56.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.56.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.56.0)

operators/patch-operator/0.1.5/Dockerfile, operators/patch-operator/0.1.5/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.5/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.5/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.5/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.5/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.5/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.5/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.5/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.5/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.5/metadata/annotations.yaml, operators/patch-operator/0.1.5/tests/scorecard/config.yaml
=> operator patch-operator (0.1.5)

operators/sosivio/1.4.1-81/manifests/sosivio-operator.clusterserviceversion.yaml, operators/sosivio/1.4.1-81/manifests/sosivio.crd.yaml, operators/sosivio/1.4.1-81/metadata/annotations.yaml
Signed-off-by: Dan Arlowski <dan@sosiv.io>
--
=> operator sosivio (1.4.1-81)

operators/gitops-primer/0.0.9/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.9/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.9/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.9/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.9/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.9/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.9/metadata/annotations.yaml, operators/gitops-primer/0.0.9/tests/scorecard/config.yaml
=> operator gitops-primer (0.0.9)

operators/portworx-essentials/1.9.0/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.9.0/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.9.0/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/ci.yaml, operators/portworx-essentials/portworx.package.yaml
Signed-off-by: HaibinMichaelXie <hxie@purestorage.com>
--
=> operator [CI] portworx-essentials (1.9.0)

ci/pipeline-config-ocp.yaml
=> Gating on v4.1

operators/pulsar-operator/0.12.0/bundle.Dockerfile, operators/pulsar-operator/0.12.0/manifests/pulsar-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar-operator-pulsar-broker_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar-operator.clusterserviceversion.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarbrokers.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarconnections.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarnamespaces.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarpermissions.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsarproxies.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsartenants.yaml, operators/pulsar-operator/0.12.0/manifests/pulsar.streamnative.io_pulsartopics.yaml, operators/pulsar-operator/0.12.0/metadata/annotations.yaml, operators/pulsar-operator/0.12.0/tests/scorecard/config.yaml
=> operator pulsar-operator (0.12.0)

operators/seldon-operator/1.14.0/manifests/machinelearning.seldon.io_seldondeployments.yaml, operators/seldon-operator/1.14.0/manifests/seldon-operator.clusterserviceversion.yaml, operators/seldon-operator/1.14.0/metadata/annotations.yaml, operators/seldon-operator/1.14.0/tests/scorecard/config.yaml
=> operator seldon-operator (1.14.0)

operators/project-quay/3.7.5/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.5/quayecosystems.crd.yaml, operators/project-quay/3.7.5/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.5 to community operators
=> operator project-quay (3.7.5)

operators/neuvector-community-operator/1.3.6/neuvector-operator.crd.yaml, operators/neuvector-community-operator/1.3.6/neuvector-operator.v1.3.6.clusterserviceversion.yaml, operators/neuvector-community-operator/neuvector-operator.package.yaml
=> operator neuvector-community-operator (1.3.6)

operators/kiali/1.54.0/bundle.Dockerfile, operators/kiali/1.54.0/manifests/kiali.crd.yaml, operators/kiali/1.54.0/manifests/kiali.v1.54.0.clusterserviceversion.yaml, operators/kiali/1.54.0/metadata/annotations.yaml
=> operator kiali (1.54.0)

operators/external-secrets-operator/0.5.9/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.5.9/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.5.9/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.5.9/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.5.9/metadata/annotations.yaml, operators/external-secrets-operator/0.5.9/tests/scorecard/config.yaml
bump external-secrets-operator 0.5.9
=> operator external-secrets-operator (0.5.9)

operators/kubernetes-imagepuller-operator/1.0.2/che.eclipse.org_kubernetesimagepullers_crd.yaml, operators/kubernetes-imagepuller-operator/1.0.2/controller-manager-metrics-service_v1_service.yaml, operators/kubernetes-imagepuller-operator/1.0.2/kubernetes-imagepuller-operator.v1.0.2.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/1.0.2/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: David Kwon <dakwon@redhat.com>
--
=> operator kubernetes-imagepuller-operator (1.0.2)

operators/cockroachdb/ci.yaml
Signed-off-by: dmesser <dmesser@redhat.com>
=> operator [CI] cockroachdb

operators/gitops-primer/0.0.10/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.10/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.10/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.10/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.10/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.10/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.10/metadata/annotations.yaml, operators/gitops-primer/0.0.10/tests/scorecard/config.yaml
=> operator gitops-primer (0.0.10)

operators/seldon-operator/1.14.1/manifests/machinelearning.seldon.io_seldondeployments.yaml, operators/seldon-operator/1.14.1/manifests/seldon-operator.clusterserviceversion.yaml, operators/seldon-operator/1.14.1/metadata/annotations.yaml, operators/seldon-operator/1.14.1/tests/scorecard/config.yaml
=> operator seldon-operator (1.14.1)

operators/istio-workspace-operator/0.5.2/manifests/istio-workspace-operator.clusterserviceversion.yaml, operators/istio-workspace-operator/0.5.2/manifests/workspace.maistra.io_sessions.yaml, operators/istio-workspace-operator/0.5.2/metadata/annotations.yaml, operators/istio-workspace-operator/0.5.2/tests/scorecard/config.yaml
=> operator istio-workspace-operator (0.5.2)

operators/aqua/2022.4.3/manifests/aqua-operator.v2022.4.2.clusterserviceversion.yaml
=> operator [O] aqua (2022.4.3)

operators/opendatahub-operator/1.3.0/manifests/opendatahub-operator.v1.3.0.clusterserviceversion.yaml
=> operator [O] opendatahub-operator (1.3.0)

operators/patch-operator/0.1.7/Dockerfile, operators/patch-operator/0.1.7/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.7/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.7/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.7/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.7/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.7/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.7/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.7/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.7/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.7/metadata/annotations.yaml, operators/patch-operator/0.1.7/tests/scorecard/config.yaml
=> operator patch-operator (0.1.7)

operators/project-quay/3.7.6/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.6/quayecosystems.crd.yaml, operators/project-quay/3.7.6/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.6 to community operators
=> operator project-quay (3.7.6)

operators/project-quay/ci.yaml
* Updates Quay to add `quay-devel` as an approver
=> operator [CI] project-quay

operators/ack-prometheusservice-controller/ci.yaml
=> operator [CI] ack-prometheusservice-controller

operators/dynatrace-operator/0.8.0/Dockerfile, operators/dynatrace-operator/0.8.0/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.8.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.8.0/metadata/annotations.yaml
=> operator dynatrace-operator (0.8.0)

operators/percona-postgresql-operator/1.3.0/manifests/percona-postgresql-operator.v1.3.0.clusterserviceversion.yaml, operators/percona-postgresql-operator/1.3.0/manifests/perconapgclusters.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.3.0/manifests/pgclusters.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.3.0/manifests/pgpolicies.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.3.0/manifests/pgreplicas.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.3.0/manifests/pgtasks.pg.percona.com.crd.yaml, operators/percona-postgresql-operator/1.3.0/metadata/annotations.yaml
Signed-off-by: Ivan Pylypenko <ivan.pylypenko@percona.com>
--
=> operator percona-postgresql-operator (1.3.0)

operators/kiali/1.55.0/bundle.Dockerfile, operators/kiali/1.55.0/manifests/kiali.crd.yaml, operators/kiali/1.55.0/manifests/kiali.v1.55.0.clusterserviceversion.yaml, operators/kiali/1.55.0/metadata/annotations.yaml
=> operator kiali (1.55.0)

operators/grafana-operator/4.6.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.6.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.6.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.6.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.6.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.6.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.6.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.6.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.6.0)

operators/multicluster-global-hub-operator/0.5.0/multicluster-global-hub-operator.clusterserviceversion.yaml, operators/multicluster-global-hub-operator/0.5.0/operator.open-cluster-management.io_multiclusterglobalhubs.yaml, operators/multicluster-global-hub-operator/ci.yaml, operators/multicluster-global-hub-operator/multicluster-global-hub-operator.package.yaml
=> operator [N] [CI] multicluster-global-hub-operator (0.5.0)

operators/multicluster-global-hub-operator/0.5.0/multicluster-global-hub-operator.clusterserviceversion.yaml
=> operator [N] multicluster-global-hub-operator (0.5.0)

operators/lbconfig-operator/0.2.0/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml, operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml, operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator-manager-config_v1_configmap.yaml, operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/lbconfig-operator/0.2.0/manifests/lbconfig-operator.clusterserviceversion.yaml, operators/lbconfig-operator/0.2.0/metadata/annotations.yaml, operators/lbconfig-operator/0.2.0/tests/scorecard/config.yaml, operators/lbconfig-operator/ci.yaml
Signed-off-by: Carlos de Paula <me@carlosedp.com>
--
=> operator [N] [CI] lbconfig-operator (0.2.0)

operators/ecr-secret-operator/0.3.2/manifests/ecr-secret-operator-controller-manager-metrics-service_v1_service.yaml, operators/ecr-secret-operator/0.3.2/manifests/ecr-secret-operator-manager-config_v1_configmap.yaml, operators/ecr-secret-operator/0.3.2/manifests/ecr-secret-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ecr-secret-operator/0.3.2/manifests/ecr-secret-operator.clusterserviceversion.yaml, operators/ecr-secret-operator/0.3.2/manifests/ecr-secret-sample_ecr.mobb.redhat.com_v1alpha1_secret.yaml, operators/ecr-secret-operator/0.3.2/manifests/ecr-secret_ecr.mobb.redhat.com_v1alpha1_secret.yaml, operators/ecr-secret-operator/0.3.2/manifests/ecr.mobb.redhat.com_secrets.yaml, operators/ecr-secret-operator/0.3.2/metadata/annotations.yaml, operators/ecr-secret-operator/0.3.2/tests/scorecard/config.yaml
=> operator ecr-secret-operator (0.3.2)

operators/aqua/2022.4.4/bundle.Dockerfile, operators/aqua/2022.4.4/manifests/aqua-operator.v2022.4.4.clusterserviceversion.yaml, operators/aqua/2022.4.4/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.4/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.4/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.4/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.4/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.4/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.4/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.4/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.4/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.4/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.4/metadata/annotations.yaml
=> operator aqua (2022.4.4)

operators/node-maintenance-operator/0.13.0/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml, operators/node-maintenance-operator/0.13.0/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-maintenance-operator/0.13.0/manifests/node-maintenance-operator-webhook-service_v1_service.yaml, operators/node-maintenance-operator/0.13.0/manifests/node-maintenance-operator.clusterserviceversion.yaml, operators/node-maintenance-operator/0.13.0/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml, operators/node-maintenance-operator/0.13.0/metadata/annotations.yaml, operators/node-maintenance-operator/0.13.0/tests/scorecard/config.yaml
=> operator node-maintenance-operator (0.13.0)

operators/apicast-community-operator/0.5.1/bundle.Dockerfile, operators/apicast-community-operator/0.5.1/manifests/apicast-operator-controller-manager-metrics-service_v1_service.yaml, operators/apicast-community-operator/0.5.1/manifests/apicast-operator.clusterserviceversion.yaml, operators/apicast-community-operator/0.5.1/manifests/apps.3scale.net_apicasts.yaml, operators/apicast-community-operator/0.5.1/metadata/annotations.yaml, operators/apicast-community-operator/0.5.1/tests/scorecard/config.yaml
=> operator apicast-community-operator (0.5.1)

operators/apicast-community-operator/0.6.0/bundle.Dockerfile, operators/apicast-community-operator/0.6.0/manifests/apicast-operator-controller-manager-metrics-service_v1_service.yaml, operators/apicast-community-operator/0.6.0/manifests/apicast-operator.clusterserviceversion.yaml, operators/apicast-community-operator/0.6.0/manifests/apps.3scale.net_apicasts.yaml, operators/apicast-community-operator/0.6.0/metadata/annotations.yaml, operators/apicast-community-operator/0.6.0/tests/scorecard/config.yaml
=> operator apicast-community-operator (0.6.0)

operators/3scale-community-operator/0.8.2/bundle.Dockerfile, operators/3scale-community-operator/0.8.2/manifests/3scale-operator.clusterserviceversion.yaml, operators/3scale-community-operator/0.8.2/manifests/apps.3scale.net_apimanagerbackups.yaml, operators/3scale-community-operator/0.8.2/manifests/apps.3scale.net_apimanagerrestores.yaml, operators/3scale-community-operator/0.8.2/manifests/apps.3scale.net_apimanagers.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_activedocs.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_backends.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_custompolicydefinitions.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_developeraccounts.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_developerusers.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_openapis.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_products.yaml, operators/3scale-community-operator/0.8.2/manifests/capabilities.3scale.net_tenants.yaml, operators/3scale-community-operator/0.8.2/manifests/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/3scale-community-operator/0.8.2/manifests/threescale-operator-controller-manager-metrics-service_v1_service.yaml, operators/3scale-community-operator/0.8.2/metadata/annotations.yaml, operators/3scale-community-operator/0.8.2/tests/scorecard/config.yaml
=> operator 3scale-community-operator (0.8.2)

operators/kube-green/0.4.0/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.4.0/manifests/kube-green-manager-config_v1_configmap.yaml, operators/kube-green/0.4.0/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.4.0/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.4.0/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.4.0/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.4.0/metadata/annotations.yaml, operators/kube-green/0.4.0/tests/scorecard/config.yaml
Signed-off-by: Davide Bianchi <bianchidavide12@gmail.com>
--
=> operator kube-green (0.4.0)

operators/3scale-community-operator/0.9.0/bundle.Dockerfile, operators/3scale-community-operator/0.9.0/manifests/3scale-operator.clusterserviceversion.yaml, operators/3scale-community-operator/0.9.0/manifests/apps.3scale.net_apimanagerbackups.yaml, operators/3scale-community-operator/0.9.0/manifests/apps.3scale.net_apimanagerrestores.yaml, operators/3scale-community-operator/0.9.0/manifests/apps.3scale.net_apimanagers.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_activedocs.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_backends.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_custompolicydefinitions.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_developeraccounts.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_developerusers.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_openapis.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_products.yaml, operators/3scale-community-operator/0.9.0/manifests/capabilities.3scale.net_tenants.yaml, operators/3scale-community-operator/0.9.0/manifests/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/3scale-community-operator/0.9.0/manifests/threescale-operator-controller-manager-metrics-service_v1_service.yaml, operators/3scale-community-operator/0.9.0/metadata/annotations.yaml, operators/3scale-community-operator/0.9.0/tests/scorecard/config.yaml
=> operator 3scale-community-operator (0.9.0)

operators/limitador-operator/0.3.0/bundle.Dockerfile, operators/limitador-operator/0.3.0/manifests/limitador-operator-controller-manager-metrics-service_v1_service.yaml, operators/limitador-operator/0.3.0/manifests/limitador-operator-manager-config_v1_configmap.yaml, operators/limitador-operator/0.3.0/manifests/limitador-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/limitador-operator/0.3.0/manifests/limitador-operator.clusterserviceversion.yaml, operators/limitador-operator/0.3.0/manifests/limitador.kuadrant.io_limitadors.yaml, operators/limitador-operator/0.3.0/metadata/annotations.yaml, operators/limitador-operator/0.3.0/tests/scorecard/config.yaml, operators/limitador-operator/ci.yaml
=> operator [N] [CI] limitador-operator (0.3.0)

operators/seldon-operator/1.14.1/metadata/annotations.yaml
Update seldon-operator to run on OpenShift 4.11
This is analogous change to one in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1410
----
--
<sup>2</sup> For …
=> operator [O] seldon-operator (1.14.1)

operators/opentelemetry-operator/0.58.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.58.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.58.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.58.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.58.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.58.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.58.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.58.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.58.0)

operators/gitlab-operator-kubernetes/0.10.2/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.10.2/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.10.2/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.10.2/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.10.2)

operators/dynatrace-operator/0.8.1/Dockerfile, operators/dynatrace-operator/0.8.1/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.8.1/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.8.1/metadata/annotations.yaml
=> operator dynatrace-operator (0.8.1)

operators/node-healthcheck-operator/ci.yaml
This is an update the to the reviewer list - no actual code changes
=> operator [CI] node-healthcheck-operator

operators/node-healthcheck-operator/0.3.0/manifests/node-healthcheck-operator-controller-manager-metrics-service_v1_service.yaml, operators/node-healthcheck-operator/0.3.0/manifests/node-healthcheck-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/node-healthcheck-operator/0.3.0/manifests/node-healthcheck-operator.clusterserviceversion.yaml, operators/node-healthcheck-operator/0.3.0/manifests/remediation.medik8s.io_nodehealthchecks.yaml, operators/node-healthcheck-operator/0.3.0/metadata/annotations.yaml, operators/node-healthcheck-operator/0.3.0/metadata/dependencies.yaml, operators/node-healthcheck-operator/0.3.0/tests/scorecard/config.yaml, operators/node-healthcheck-operator/ci.yaml
Signed-off-by: oraz <oraz@redhat.com>
--
=> operator [CI] node-healthcheck-operator (0.3.0)

operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator-controller-manager-metrics-service_v1_service.yaml, operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator-manager-config_v1_configmap.yaml, operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs-csi-driver-operator.clusterserviceversion.yaml, operators/beegfs-csi-driver-operator/1.3.0/manifests/beegfs.csi.netapp.com_beegfsdrivers.yaml, operators/beegfs-csi-driver-operator/1.3.0/metadata/annotations.yaml, operators/beegfs-csi-driver-operator/1.3.0/tests/scorecard/config.yaml
Signed-off-by: Weber, Eric <Eric.Weber2@netapp.com>
--
=> operator beegfs-csi-driver-operator (1.3.0)

operators/mongodb-atlas-kubernetes/1.2.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.2.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.2.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.2.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.2.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.2.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.2.0/tests/scorecard/config.yaml
Signed-off-by: fabritsius <anton_fabritsius@epam.com>
--
=> operator mongodb-atlas-kubernetes (1.2.0)

operators/rabbitmq-cluster-operator/1.14.0/bundle.Dockerfile, operators/rabbitmq-cluster-operator/1.14.0/manifests/crds.yaml, operators/rabbitmq-cluster-operator/1.14.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-cluster-operator/1.14.0/metadata/annotations.yaml, operators/rabbitmq-cluster-operator/ci.yaml
Signed-off-by: Daniele Palaia <dpalaia@vmware.com>
--
=> operator [N] [CI] rabbitmq-cluster-operator (1.14.0)

operators/patch-operator/0.1.8/Dockerfile, operators/patch-operator/0.1.8/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.8/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.8/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.8/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.8/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.8/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.8/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.8/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.8/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.8/metadata/annotations.yaml, operators/patch-operator/0.1.8/tests/scorecard/config.yaml
=> operator patch-operator (0.1.8)

operators/rabbitmq-messaging-topology-operator/1.8.0/bundle.Dockerfile, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_bindings.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_exchanges.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_federations.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_permissions.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_policies.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_queues.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_schemareplications.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_shovels.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_superstreams.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_users.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.com_vhosts.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-messaging-topology-operator/1.8.0/metadata/annotations.yaml, operators/rabbitmq-messaging-topology-operator/ci.yaml
Signed-off-by: Daniele Palaia <dpalaia@vmware.com>
--
=> operator [N] [CI] rabbitmq-messaging-topology-operator (1.8.0)

operators/patterns-operator/0.0.5/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.5/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.5/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.5/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.5/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.5/metadata/annotations.yaml, operators/patterns-operator/0.0.5/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.5)

operators/dynatrace-operator/0.8.2/Dockerfile, operators/dynatrace-operator/0.8.2/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.8.2/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.8.2/metadata/annotations.yaml
=> operator dynatrace-operator (0.8.2)

operators/project-quay/3.7.7/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.7/quayecosystems.crd.yaml, operators/project-quay/3.7.7/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.7 to community operators
=> operator project-quay (3.7.7)

operators/rabbitmq-single-active-consumer-operator/0.2.2/bundle.Dockerfile, operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.com_superstreamconsumers.yaml, operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.config-map.yaml, operators/rabbitmq-single-active-consumer-operator/0.2.2/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-single-active-consumer-operator/0.2.2/metadata/annotations.yaml, operators/rabbitmq-single-active-consumer-operator/ci.yaml
Signed-off-by: Daniele Palaia <dpalaia@vmware.com>
--
=> operator [N] [CI] rabbitmq-single-active-consumer-operator (0.2.2)

operators/project-quay/3.8.0-rc.1/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.0-rc.1/quayecosystems.crd.yaml, operators/project-quay/3.8.0-rc.1/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
* Adds a new channel for testing out Quay 3.8.0
=> operator project-quay (3.8.0-rc.1)

operators/project-quay/3.8.0-rc.2/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.0-rc.2/quayecosystems.crd.yaml, operators/project-quay/3.8.0-rc.2/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.2 to community operators
=> operator project-quay (3.8.0-rc.2)

operators/camel-k/1.10.0/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.10.0/manifests/camel-k.v1.10.0.clusterserviceversion.yaml, operators/camel-k/1.10.0/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.10.0/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.10.0/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.10.0/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.10.0/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.10.0/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.10.0/metadata/annotations.yaml, operators/camel-k/1.10.0/tests/scorecard/config.yaml, operators/camel-k/1.8.0/metadata/annotations.yaml, operators/camel-k/1.8.1/metadata/annotations.yaml, operators/camel-k/1.8.2/metadata/annotations.yaml, operators/camel-k/1.9.1/metadata/annotations.yaml, operators/camel-k/1.9.2/metadata/annotations.yaml
=> operator [R] camel-k (1.10.0 1.8.0 1.8.1 1.8.2 1.9.0 1.9.1 1.9.2)

operators/patch-operator/0.1.9/Dockerfile, operators/patch-operator/0.1.9/manifests/patch-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operators/patch-operator/0.1.9/manifests/patch-operator-controller-manager-metrics-service_v1_service.yaml, operators/patch-operator/0.1.9/manifests/patch-operator-manager-config_v1_configmap.yaml, operators/patch-operator/0.1.9/manifests/patch-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patch-operator/0.1.9/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, operators/patch-operator/0.1.9/manifests/patch-operator-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/patch-operator/0.1.9/manifests/patch-operator-webhook-service_v1_service.yaml, operators/patch-operator/0.1.9/manifests/patch-operator.clusterserviceversion.yaml, operators/patch-operator/0.1.9/manifests/redhatcop.redhat.io_patches.yaml, operators/patch-operator/0.1.9/metadata/annotations.yaml, operators/patch-operator/0.1.9/tests/scorecard/config.yaml
=> operator patch-operator (0.1.9)

operators/authorino-operator/0.4.0/bundle.Dockerfile, operators/authorino-operator/0.4.0/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.0/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.0/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.0/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.0/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.0/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml, operators/authorino-operator/0.4.0/manifests/authorino-operator-manager-config_v1_configmap.yaml, operators/authorino-operator/0.4.0/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.0/manifests/authorino-operator.clusterserviceversion.yaml, operators/authorino-operator/0.4.0/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.0/manifests/authorino.kuadrant.io_authconfigs.yaml, operators/authorino-operator/0.4.0/manifests/manager-config_v1_configmap.yaml, operators/authorino-operator/0.4.0/manifests/operator.authorino.kuadrant.io_authorinos.yaml, operators/authorino-operator/0.4.0/metadata/annotations.yaml, operators/authorino-operator/0.4.0/tests/scorecard/config.yaml, operators/authorino-operator/ci.yaml
=> operator [CI] authorino-operator (0.4.0)

operators/authorino-operator/0.4.1/bundle.Dockerfile, operators/authorino-operator/0.4.1/manifests/authorino-authconfig-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.1/manifests/authorino-authconfig-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.1/manifests/authorino-manager-k8s-auth-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.1/manifests/authorino-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.1/manifests/authorino-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.1/manifests/authorino-operator-controller-manager-metrics-service_v1_service.yaml, operators/authorino-operator/0.4.1/manifests/authorino-operator-manager-config_v1_configmap.yaml, operators/authorino-operator/0.4.1/manifests/authorino-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.1/manifests/authorino-operator.clusterserviceversion.yaml, operators/authorino-operator/0.4.1/manifests/authorino-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/authorino-operator/0.4.1/manifests/authorino.kuadrant.io_authconfigs.yaml, operators/authorino-operator/0.4.1/manifests/manager-config_v1_configmap.yaml, operators/authorino-operator/0.4.1/manifests/operator.authorino.kuadrant.io_authorinos.yaml, operators/authorino-operator/0.4.1/metadata/annotations.yaml, operators/authorino-operator/0.4.1/tests/scorecard/config.yaml
=> operator authorino-operator (0.4.1)

operators/kiali/1.56.0/bundle.Dockerfile, operators/kiali/1.56.0/manifests/kiali.crd.yaml, operators/kiali/1.56.0/manifests/kiali.v1.56.0.clusterserviceversion.yaml, operators/kiali/1.56.0/metadata/annotations.yaml
=> operator kiali (1.56.0)

operators/tackle-operator/2.1.0/manifests/tackle-operator.clusterserviceversion.yaml, operators/tackle-operator/2.1.0/manifests/tackle.konveyor.io_addons.yaml, operators/tackle-operator/2.1.0/manifests/tackle.konveyor.io_tackles.yaml, operators/tackle-operator/2.1.0/metadata/annotations.yaml, operators/tackle-operator/ci.yaml
=> operator [CI] tackle-operator (2.1.0)

operators/forklift-operator/2.3.2/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.3.2/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.3.2/metadata/annotations.yaml
=> operator forklift-operator (2.3.2)

operators/opentelemetry-operator/0.59.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.59.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.59.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.59.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.59.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.59.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.59.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.59.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.59.0)

operators/portworx-essentials/1.9.1/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.9.1/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.9.1/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
Signed-off-by: Jiafeng Liao <jliao@purestorage.com>
--
=> operator portworx-essentials (1.9.1)

operators/gitlab-runner-operator/1.10.0/bundle.Dockerfile, operators/gitlab-runner-operator/1.10.0/manifests/apps.gitlab.com_runners.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-app-role_rbac.authorization.k8s.io_v1_role.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-app-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-operator.clusterserviceversion.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-sa_v1_serviceaccount.yaml, operators/gitlab-runner-operator/1.10.0/manifests/gitlab-runner-webhook-service_v1_service.yaml, operators/gitlab-runner-operator/1.10.0/metadata/annotations.yaml, operators/gitlab-runner-operator/1.10.0/tests/scorecard/config.yaml
=> operator gitlab-runner-operator (1.10.0)

operators/aerospike-kubernetes-operator/2.2.0/bundle.Dockerfile, operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml, operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-manager-config_v1_configmap.yaml, operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.2.0/manifests/aerospike-operator-webhook-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.2.0/manifests/asdb.aerospike.com_aerospikeclusters.yaml, operators/aerospike-kubernetes-operator/2.2.0/metadata/annotations.yaml, operators/aerospike-kubernetes-operator/2.2.0/tests/scorecard/config.yaml
Signed-off-by: Ashish Shinde <ashish@aerospike.com>
--
=> operator aerospike-kubernetes-operator (2.2.0)

operators/bookkeeper-operator/0.12.2/bundle.Dockerfile, operators/bookkeeper-operator/0.12.2/manifests/bookkeeper-operator-controller-manager-metrics-service_v1_service.yaml, operators/bookkeeper-operator/0.12.2/manifests/bookkeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/bookkeeper-operator/0.12.2/manifests/bookkeeper-operator.clusterserviceversion.yaml, operators/bookkeeper-operator/0.12.2/manifests/bookkeeper.streamnative.io_bookkeeperclusters.yaml, operators/bookkeeper-operator/0.12.2/metadata/annotations.yaml, operators/bookkeeper-operator/0.12.2/tests/scorecard/config.yaml
=> operator bookkeeper-operator (0.12.2)

operators/windup-operator/ci.yaml
Signed-off-by: carlosthe19916 <2582866+carlosthe19916@users.noreply.github.com>
--
=> operator [CI] windup-operator

operators/lbconfig-operator/0.4.0/manifests/lb.lbconfig.carlosedp.com_externalloadbalancers.yaml, operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator-controller-manager-metrics-service_v1_service.yaml, operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator-manager-config_v1_configmap.yaml, operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/lbconfig-operator/0.4.0/manifests/lbconfig-operator.clusterserviceversion.yaml, operators/lbconfig-operator/0.4.0/metadata/annotations.yaml, operators/lbconfig-operator/0.4.0/tests/scorecard/config.yaml, operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/create-externalloadbalancer/01-assert.yaml, operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/create-externalloadbalancer/10-create-elb.yaml, operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/create-externalloadbalancer/11-assert.yaml, operators/lbconfig-operator/0.4.0/tests/scorecard/kuttl/kuttl-test.yaml
Signed-off-by: Carlos de Paula <me@carlosedp.com>
--
=> operator lbconfig-operator (0.4.0)

operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.6.0-rc1/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.6.0-rc1/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.6.0-rc1/metadata/annotations.yaml, operators/external-secrets-operator/0.6.0-rc1/tests/scorecard/config.yaml
bump external-secrets-operator 0.6.0-rc1
=> operator external-secrets-operator (0.6.0-rc1)

operators/microcks/1.6.0/microcks-operator.v1.6.0.clusterserviceversion.yaml, operators/microcks/1.6.0/microcksinstall.crd.yaml, operators/microcks/microcks.package.yaml
=> operator microcks (1.6.0)

operators/ossmconsole/0.1.0/bundle.Dockerfile, operators/ossmconsole/0.1.0/manifests/ossmconsole.clusterserviceversion.yaml, operators/ossmconsole/0.1.0/manifests/ossmconsole.crd.yaml, operators/ossmconsole/0.1.0/metadata/annotations.yaml, operators/ossmconsole/ci.yaml
This is the initial version for the new dev preview release of the new OpenShift Service Mesh Console.
=> operator [N] [CI] ossmconsole (0.1.0)

operators/gitops-primer/0.0.11/manifests/gitops-primer-controller-manager-metrics-service_v1_service.yaml, operators/gitops-primer/0.0.11/manifests/gitops-primer-manager-config_v1_configmap.yaml, operators/gitops-primer/0.0.11/manifests/gitops-primer-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitops-primer/0.0.11/manifests/gitops-primer-webhook-service_v1_service.yaml, operators/gitops-primer/0.0.11/manifests/gitops-primer.clusterserviceversion.yaml, operators/gitops-primer/0.0.11/manifests/primer.gitops.io_exports.yaml, operators/gitops-primer/0.0.11/metadata/annotations.yaml, operators/gitops-primer/0.0.11/tests/scorecard/config.yaml
Signed-off-by: jaydipgabani <gabanijaydip@gmail.com>
--
=> operator gitops-primer (0.0.11)

operators/project-quay/3.8.0-rc.3/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.0-rc.3/quayecosystems.crd.yaml, operators/project-quay/3.8.0-rc.3/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.3 to community operators
=> operator project-quay (3.8.0-rc.3)

operators/project-quay/3.7.8/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.8/quayecosystems.crd.yaml, operators/project-quay/3.7.8/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.8 to community operators
=> operator project-quay (3.7.8)

operators/deployment-validation-operator/0.3.0/manifests/deploymentvalidationoperator-service.yaml, operators/deployment-validation-operator/0.3.0/manifests/deploymentvalidationoperator.0.2.2.clusterserviceversion.yaml, operators/deployment-validation-operator/0.3.0/manifests/deploymentvalidationoperator.0.3.0.clusterserviceversion.yaml, operators/deployment-validation-operator/0.3.0/metadata/annotations.yaml, operators/deployment-validation-operator/0.3.0/tests/scorecard/config.yaml
Updating DVO from 0.2.2 to 0.3.0
=> operator deployment-validation-operator (0.3.0)

operators/yaks/0.11.0/instances.yaks.citrusframework.org.crd.yaml, operators/yaks/0.11.0/tests.yaks.citrusframework.org.crd.yaml, operators/yaks/0.11.0/yaks.v0.11.0.clusterserviceversion.yaml, operators/yaks/yaks.package.yaml
=> operator yaks (0.11.0)

operators/multi-nic-cni-operator/1.0.2/bundle.Dockerfile, operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator-controller-manager-metrics-service_v1_service.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator-manager-config_v1_configmap.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multi-nic-cni-operator.clusterserviceversion.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_cidrs.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_configs.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_deviceclasses.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_hostinterfaces.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_ippools.yaml, operators/multi-nic-cni-operator/1.0.2/manifests/multinic.fms.io_multinicnetworks.yaml, operators/multi-nic-cni-operator/1.0.2/metadata/annotations.yaml, operators/multi-nic-cni-operator/1.0.2/tests/scorecard/config.yaml, operators/multi-nic-cni-operator/ci.yaml
Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
--
=> operator [N] [CI] multi-nic-cni-operator (1.0.2)

operators/verticadb-operator/1.7.0/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.7.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.7.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.7.0/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.7.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.7.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.7.0/metadata/annotations.yaml, operators/verticadb-operator/1.7.0/tests/scorecard/config.yaml
Signed-off-by: Matt Spilchen <matt.spilchen@vertica.com>
--
=> operator verticadb-operator (1.7.0)

operators/falcon-operator/0.5.5/manifests/falcon-operator-controller-manager-metrics-service_v1_service.yaml, operators/falcon-operator/0.5.5/manifests/falcon-operator-manager-config_v1_configmap.yaml, operators/falcon-operator/0.5.5/manifests/falcon-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/falcon-operator/0.5.5/manifests/falcon-operator.clusterserviceversion.yaml, operators/falcon-operator/0.5.5/manifests/falcon.crowdstrike.com_falconcontainers.yaml, operators/falcon-operator/0.5.5/manifests/falcon.crowdstrike.com_falconnodesensors.yaml, operators/falcon-operator/0.5.5/metadata/annotations.yaml, operators/falcon-operator/0.5.5/tests/scorecard/config.yaml
Signed-off-by: Simon Lukasik <simon.lukasik@crowdstrike.com>
--
=> operator falcon-operator (0.5.5)

operators/deployment-validation-operator/0.3.0/manifests/deploymentvalidationoperator.0.3.0.clusterserviceversion.yaml
=> operator [O] deployment-validation-operator (0.3.0)

operators/aqua/6.5.7/bundle.Dockerfile, operators/aqua/6.5.7/manifests/aqua-operator.v6.5.7.clusterserviceversion.yaml, operators/aqua/6.5.7/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/6.5.7/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/6.5.7/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.7/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/6.5.7/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.7/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/6.5.7/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/6.5.7/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.7/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.7/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/6.5.7/metadata/annotations.yaml
=> operator aqua (6.5.7)

operators/pulp-operator/0.14.0/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.14.0/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.14.0/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.14.0/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.14.0/manifests/pulp-operator.v0.14.0.clusterserviceversion.yaml, operators/pulp-operator/0.14.0/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.14.0/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.14.0/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.14.0/metadata/annotations.yaml, operators/pulp-operator/0.14.0/tests/scorecard/config.yaml, operators/pulp-operator/ci.yaml
=> operator [CI] pulp-operator (0.14.0)

operators/multicluster-global-hub-operator/0.6.0-dev/multicluster-global-hub-operator.clusterserviceversion.yaml, operators/multicluster-global-hub-operator/0.6.0-dev/operator.open-cluster-management.io_multiclusterglobalhubs.yaml, operators/multicluster-global-hub-operator/multicluster-global-hub-operator.package.yaml
=> operator multicluster-global-hub-operator (0.6.0-dev)

operators/rabbitmq-cluster-operator/2.0.0/bundle.Dockerfile, operators/rabbitmq-cluster-operator/2.0.0/manifests/crds.yaml, operators/rabbitmq-cluster-operator/2.0.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-cluster-operator/2.0.0/metadata/annotations.yaml
Signed-off-by: DanielePalaia <dpalaia@vmware.com>
--
=> operator rabbitmq-cluster-operator (2.0.0)

operators/project-quay/3.8.0-rc.4/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.0-rc.4/quayecosystems.crd.yaml, operators/project-quay/3.8.0-rc.4/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.4 to community operators
=> operator project-quay (3.8.0-rc.4)

operators/dynatrace-operator/0.9.0/Dockerfile, operators/dynatrace-operator/0.9.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.9.0/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.9.0/metadata/annotations.yaml
=> operator dynatrace-operator (0.9.0)

operators/aerospike-kubernetes-operator/2.2.1/bundle.Dockerfile, operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-kubernetes-operator-default-ns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-kubernetes-operator.clusterserviceversion.yaml, operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-controller-manager-metrics-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-manager-config_v1_configmap.yaml, operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/aerospike-kubernetes-operator/2.2.1/manifests/aerospike-operator-webhook-service_v1_service.yaml, operators/aerospike-kubernetes-operator/2.2.1/manifests/asdb.aerospike.com_aerospikeclusters.yaml, operators/aerospike-kubernetes-operator/2.2.1/metadata/annotations.yaml, operators/aerospike-kubernetes-operator/2.2.1/tests/scorecard/config.yaml
Signed-off-by: Ashish Shinde <ashish@aerospike.com>
--
=> operator aerospike-kubernetes-operator (2.2.1)

operators/cass-operator-community/1.13.0/manifests/cass-operator-manager-config_v1_configmap.yaml, operators/cass-operator-community/1.13.0/manifests/cass-operator-webhook-service_v1_service.yaml, operators/cass-operator-community/1.13.0/manifests/cass-operator.clusterserviceversion.yaml, operators/cass-operator-community/1.13.0/manifests/cassandra.datastax.com_cassandradatacenters.yaml, operators/cass-operator-community/1.13.0/manifests/control.k8ssandra.io_cassandratasks.yaml, operators/cass-operator-community/1.13.0/metadata/annotations.yaml, operators/cass-operator-community/1.13.0/tests/scorecard/config.yaml
Signed-off-by: Michael Burman <michael.burman@datastax.com>
--
=> operator cass-operator-community (1.13.0)

operators/dell-csi-operator/1.9.0/csiisilons.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.9.0/csipowermaxes.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.9.0/csipowermaxrevproxies.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.9.0/csipowerstores.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.9.0/csiunities.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.9.0/csivxflexoses.storage.dell.com.crd.yaml, operators/dell-csi-operator/1.9.0/dell-csi-operator.v1.9.0.clusterserviceversion.yaml, operators/dell-csi-operator/dell-csi-operator.package.yaml
=> operator dell-csi-operator (1.9.0)

operators/dell-csm-operator/0.3.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml, operators/dell-csm-operator/0.3.0/manifests/dell-csm-operator.v0.3.0.clusterserviceversion.yaml, operators/dell-csm-operator/0.3.0/metadata/annotations.yaml, operators/dell-csm-operator/0.3.0/tests/scorecard/config.yaml
=> operator dell-csm-operator (0.3.0)

operators/pulp-operator/0.14.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/0.14.1/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/0.14.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/0.14.1/manifests/pulp-operator-pulp-manager-config_v1_configmap.yaml, operators/pulp-operator/0.14.1/manifests/pulp-operator.v0.14.1.clusterserviceversion.yaml, operators/pulp-operator/0.14.1/manifests/pulp.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/0.14.1/manifests/pulp.pulpproject.org_pulprestores.yaml, operators/pulp-operator/0.14.1/manifests/pulp.pulpproject.org_pulps.yaml, operators/pulp-operator/0.14.1/metadata/annotations.yaml, operators/pulp-operator/0.14.1/tests/scorecard/config.yaml
=> operator pulp-operator (0.14.1)

operators/tackle-operator/2.1.1/manifests/tackle-operator.clusterserviceversion.yaml, operators/tackle-operator/2.1.1/manifests/tackle.konveyor.io_addons.yaml, operators/tackle-operator/2.1.1/manifests/tackle.konveyor.io_tackles.yaml, operators/tackle-operator/2.1.1/metadata/annotations.yaml
=> operator tackle-operator (2.1.1)

operators/percona-server-mongodb-operator/1.13.0/manifests/percona-server-mongodb-operator.v1.clusterserviceversion.yaml, operators/percona-server-mongodb-operator/1.13.0/manifests/perconaservermongodbbackups.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.13.0/manifests/perconaservermongodbrestores.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.13.0/manifests/perconaservermongodbs.psmdb.percona.com.crd.yaml, operators/percona-server-mongodb-operator/1.13.0/metadata/annotations.yaml
Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>
--
=> operator percona-server-mongodb-operator (1.13.0)

operators/kube-green/0.4.1/manifests/kube-green-controller-manager-metrics-service_v1_service.yaml, operators/kube-green/0.4.1/manifests/kube-green-manager-config_v1_configmap.yaml, operators/kube-green/0.4.1/manifests/kube-green-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kube-green/0.4.1/manifests/kube-green-webhook-service_v1_service.yaml, operators/kube-green/0.4.1/manifests/kube-green.clusterserviceversion.yaml, operators/kube-green/0.4.1/manifests/kube-green.com_sleepinfos.yaml, operators/kube-green/0.4.1/metadata/annotations.yaml, operators/kube-green/0.4.1/tests/scorecard/config.yaml
=> operator kube-green (0.4.1)

operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-controller-manager-metrics-service_v1_service.yaml, operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-manager-config_v1_configmap.yaml, operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator-webhook-service_v1_service.yaml, operators/eginnovations-operator/0.0.2/manifests/eginnovations-operator.clusterserviceversion.yaml, operators/eginnovations-operator/0.0.2/manifests/eginnovations.com_eguniversalagents.yaml, operators/eginnovations-operator/0.0.2/metadata/annotations.yaml, operators/eginnovations-operator/0.0.2/tests/scorecard/config.yaml, operators/eginnovations-operator/ci.yaml
Signed-off-by: Gaurav Singh <gauravsingh.r@eginnovations.com>
--
=> operator [CI] eginnovations-operator (0.0.2)

operators/grafana-operator/4.7.0/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.7.0/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.7.0/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.7.0/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.7.0/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.7.0/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.7.0/integreatly.org_grafanafolders.yaml, operators/grafana-operator/4.7.0/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.7.0/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.7.0)

operators/nfs-provisioner-operator/0.0.6/Dockerfile, operators/nfs-provisioner-operator/0.0.6/manifests/cache.jhouse.com_nfsprovisioners.yaml, operators/nfs-provisioner-operator/0.0.6/manifests/nfs-provisioner-operator-controller-manager-metrics-service_v1_service.yaml, operators/nfs-provisioner-operator/0.0.6/manifests/nfs-provisioner-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/nfs-provisioner-operator/0.0.6/manifests/nfs-provisioner-operator.clusterserviceversion.yaml, operators/nfs-provisioner-operator/0.0.6/metadata/annotations.yaml, operators/nfs-provisioner-operator/0.0.6/tests/scorecard/config.yaml
=> operator nfs-provisioner-operator (0.0.6)

operators/multicluster-global-hub-operator/0.6.0-dev/multicluster-global-hub-operator.clusterserviceversion.yaml
=> operator [O] multicluster-global-hub-operator (0.6.0-dev)

operators/external-secrets-operator/0.6.0/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.6.0/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.6.0/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.6.0/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.6.0/metadata/annotations.yaml, operators/external-secrets-operator/0.6.0/tests/scorecard/config.yaml
bump external-secrets-operator 0.6.0
=> operator external-secrets-operator (0.6.0)

operators/datadog-operator/0.8.2/manifests/datadog-operator.clusterserviceversion.yaml, operators/datadog-operator/0.8.2/manifests/datadoghq.com_datadogagents.yaml, operators/datadog-operator/0.8.2/manifests/datadoghq.com_datadogmetrics.yaml, operators/datadog-operator/0.8.2/manifests/datadoghq.com_datadogmonitors.yaml, operators/datadog-operator/0.8.2/metadata/annotations.yaml, operators/datadog-operator/0.8.2/tests/scorecard/config.yaml
Signed-off-by: Celene Chang <celene@datadoghq.com>
--
=> operator datadog-operator (0.8.2)

operators/koku-metrics-operator/1.1.8/Dockerfile, operators/koku-metrics-operator/1.1.8/manifests/koku-metrics-cfg.openshift.io_kokumetricsconfigs.yaml, operators/koku-metrics-operator/1.1.8/manifests/koku-metrics-operator.clusterserviceversion.yaml, operators/koku-metrics-operator/1.1.8/metadata/annotations.yaml, operators/koku-metrics-operator/1.1.8/tests/scorecard/config.yaml
Signed-off-by: maskarb <mskarbek@redhat.com>
--
=> operator koku-metrics-operator (1.1.8)

operators/snapscheduler/3.2.0/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml, operators/snapscheduler/3.2.0/manifests/snapscheduler-manager-config_v1_configmap.yaml, operators/snapscheduler/3.2.0/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/snapscheduler/3.2.0/manifests/snapscheduler.backube_snapshotschedules.yaml, operators/snapscheduler/3.2.0/manifests/snapscheduler.clusterserviceversion.yaml, operators/snapscheduler/3.2.0/metadata/annotations.yaml, operators/snapscheduler/3.2.0/tests/scorecard/config.yaml
=> operator snapscheduler (3.2.0)

operators/nfs-provisioner-operator/0.0.6/manifests/nfs-provisioner-operator.clusterserviceversion.yaml
=> operator [O] nfs-provisioner-operator (0.0.6)

operators/multicluster-global-hub-operator/0.5.0/multicluster-global-hub-operator.clusterserviceversion.yaml, operators/multicluster-global-hub-operator/0.6.0-dev/multicluster-global-hub-operator.clusterserviceversion.yaml
=> operator [R] multicluster-global-hub-operator (0.5.0 0.6.0-dev)

operators/ibm-security-verify-access-operator/22.10.0/manifests/ibm-security-verify-access-operator.clusterserviceversion.yaml, operators/ibm-security-verify-access-operator/22.10.0/manifests/ibm.com_ibmsecurityverifyaccesses.yaml, operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-controller-manager-metrics-service_v1_service.yaml, operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-controller-manager-snapshot-service_v1_service.yaml, operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-manager-config_v1_configmap.yaml, operators/ibm-security-verify-access-operator/22.10.0/manifests/verify-access-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/ibm-security-verify-access-operator/22.10.0/metadata/annotations.yaml, operators/ibm-security-verify-access-operator/22.10.0/tests/scorecard/config.yaml
Signed-off-by: asha <ashashiv@au1.ibm.com>
* [ x Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
-- …
=> operator ibm-security-verify-access-operator (22.10.0)

operators/annotationlab/3.4.0/bundle.Dockerfile, operators/annotationlab/3.4.0/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/3.4.0/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/3.4.0/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/3.4.0/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/3.4.0/metadata/annotations.yaml, operators/annotationlab/3.4.0/tests/scorecard/config.yaml, operators/annotationlab/ci.yaml
=> operator [N] [CI] annotationlab (3.4.0)

operators/aqua/2022.4.5/bundle.Dockerfile, operators/aqua/2022.4.5/manifests/aqua-operator.v2022.4.4.clusterserviceversion.yaml, operators/aqua/2022.4.5/manifests/aquacsps.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.5/manifests/aquadatabases.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.5/manifests/aquaenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.5/manifests/aquagateways.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.5/manifests/aquakubeenforcers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.5/manifests/aquascanners.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.5/manifests/aquaservers.operator.aquasec.com.crd.yaml, operators/aqua/2022.4.5/manifests/aquastarboards.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.5/manifests/clusterconfigauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.5/manifests/configauditreports.aquasecurity.github.io.crd.yaml, operators/aqua/2022.4.5/metadata/annotations.yaml
Signed-off-by: KoppulaRajender <koppularajender18@gmail.com>
--
=> operator aqua (2022.4.5)

operators/awx-operator/0.30.0/bundle.Dockerfile, operators/awx-operator/0.30.0/manifests/awx-operator-awx-manager-config_v1_configmap.yaml, operators/awx-operator/0.30.0/manifests/awx-operator-controller-manager-metrics-service_v1_service.yaml, operators/awx-operator/0.30.0/manifests/awx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/awx-operator/0.30.0/manifests/awx-operator.v0.30.0.clusterserviceversion.yaml, operators/awx-operator/0.30.0/manifests/awx.ansible.com_awxbackups.yaml, operators/awx-operator/0.30.0/manifests/awx.ansible.com_awxrestores.yaml, operators/awx-operator/0.30.0/manifests/awx.ansible.com_awxs.yaml, operators/awx-operator/0.30.0/metadata/annotations.yaml, operators/awx-operator/0.30.0/tests/scorecard/config.yaml, operators/awx-operator/ci.yaml
https://github.com/ansible/awx-operator
Here is the k8s-operatorhub/community-operators PR which merged recently: https://github.com/k8s-operatorhub/community-operators/pull/1822
--
=> operator [N] [CI] awx-operator (0.30.0)

operators/camel-k/1.10.1/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.10.1/manifests/camel-k.v1.10.1.clusterserviceversion.yaml, operators/camel-k/1.10.1/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.10.1/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.10.1/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.10.1/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.10.1/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.10.1/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.10.1/metadata/annotations.yaml, operators/camel-k/1.10.1/tests/scorecard/config.yaml
=> operator camel-k (1.10.1)

operators/project-quay/3.7.9/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.9/quayecosystems.crd.yaml, operators/project-quay/3.7.9/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.9 to community operators
=> operator project-quay (3.7.9)

operators/kubernetes-imagepuller-operator/1.0.3/che.eclipse.org_kubernetesimagepullers_crd.yaml, operators/kubernetes-imagepuller-operator/1.0.3/controller-manager-metrics-service_v1_service.yaml, operators/kubernetes-imagepuller-operator/1.0.3/kubernetes-imagepuller-operator.v1.0.3.clusterserviceversion.yaml, operators/kubernetes-imagepuller-operator/1.0.3/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml
Signed-off-by: David Kwon <dakwon@redhat.com>
--
=> operator kubernetes-imagepuller-operator (1.0.3)

operators/patterns-operator/0.0.6/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.6/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.6/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.6/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.6/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.6/metadata/annotations.yaml, operators/patterns-operator/0.0.6/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.6)

operators/kiali/1.57.0/bundle.Dockerfile, operators/kiali/1.57.0/manifests/kiali.crd.yaml, operators/kiali/1.57.0/manifests/kiali.v1.57.0.clusterserviceversion.yaml, operators/kiali/1.57.0/metadata/annotations.yaml, operators/kiali/1.58.0/bundle.Dockerfile, operators/kiali/1.58.0/manifests/kiali.crd.yaml, operators/kiali/1.58.0/manifests/kiali.v1.58.0.clusterserviceversion.yaml, operators/kiali/1.58.0/metadata/annotations.yaml
=> operator [R] kiali (1.57.0 1.58.0)

operators/camel-k/1.10.2/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.10.2/manifests/camel-k.v1.10.2.clusterserviceversion.yaml, operators/camel-k/1.10.2/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.10.2/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.10.2/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.10.2/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.10.2/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.10.2/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.10.2/metadata/annotations.yaml, operators/camel-k/1.10.2/tests/scorecard/config.yaml
=> operator camel-k (1.10.2)

operators/dynatrace-operator/0.9.1/Dockerfile, operators/dynatrace-operator/0.9.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-dynakube-oneagent-privileged_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-dynakube-oneagent-privileged_v1_serviceaccount.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-high-priority_scheduling.k8s.io_v1_priorityclass.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_role.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-oneagent-csi-driver_v1_serviceaccount.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-operator.clusterserviceversion.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-webhook_policy_v1_poddisruptionbudget.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace-webhook_v1_service.yaml, operators/dynatrace-operator/0.9.1/manifests/dynatrace.com_dynakubes.yaml, operators/dynatrace-operator/0.9.1/metadata/annotations.yaml
=> operator dynatrace-operator (0.9.1)

operators/opentelemetry-operator/0.61.0/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.61.0/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.61.0/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.61.0/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.61.0/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.61.0/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.61.0/metadata/annotations.yaml, operators/opentelemetry-operator/0.61.0/tests/scorecard/config.yaml
=> operator opentelemetry-operator (0.61.0)

operators/grafana-operator/4.7.1/grafana-operator-controller-manager-metrics-service_v1_service.yaml, operators/grafana-operator/4.7.1/grafana-operator-manager-config_v1_configmap.yaml, operators/grafana-operator/4.7.1/grafana-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/grafana-operator/4.7.1/grafana-operator.clusterserviceversion.yaml, operators/grafana-operator/4.7.1/integreatly.org_grafanadashboards.yaml, operators/grafana-operator/4.7.1/integreatly.org_grafanadatasources.yaml, operators/grafana-operator/4.7.1/integreatly.org_grafanafolders.yaml, operators/grafana-operator/4.7.1/integreatly.org_grafananotificationchannels.yaml, operators/grafana-operator/4.7.1/integreatly.org_grafanas.yaml, operators/grafana-operator/grafana-operator.package.yaml
=> operator grafana-operator (4.7.1)

operators/flux/0.35.0/manifests/alert.crd.yaml, operators/flux/0.35.0/manifests/bucket.crd.yaml, operators/flux/0.35.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.35.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.35.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.35.0/manifests/flux.v0.35.0.clusterserviceversion.yaml, operators/flux/0.35.0/manifests/gitrepository.crd.yaml, operators/flux/0.35.0/manifests/helmchart.crd.yaml, operators/flux/0.35.0/manifests/helmrelease.crd.yaml, operators/flux/0.35.0/manifests/helmrepository.crd.yaml, operators/flux/0.35.0/manifests/imagepolicy.crd.yaml, operators/flux/0.35.0/manifests/imagerepository.crd.yaml, operators/flux/0.35.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.35.0/manifests/kustomization.crd.yaml, operators/flux/0.35.0/manifests/notification-controller.service.yaml, operators/flux/0.35.0/manifests/ocirepository.crd.yaml, operators/flux/0.35.0/manifests/provider.crd.yaml, operators/flux/0.35.0/manifests/receiver.crd.yaml, operators/flux/0.35.0/manifests/source-controller.service.yaml, operators/flux/0.35.0/manifests/webhook-receiver.service.yaml, operators/flux/0.35.0/metadata/annotations.yaml
=> operator flux (0.35.0)

operators/flux/0.36.0/manifests/alert.crd.yaml, operators/flux/0.36.0/manifests/bucket.crd.yaml, operators/flux/0.36.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.36.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.36.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.36.0/manifests/flux.v0.36.0.clusterserviceversion.yaml, operators/flux/0.36.0/manifests/gitrepository.crd.yaml, operators/flux/0.36.0/manifests/helmchart.crd.yaml, operators/flux/0.36.0/manifests/helmrelease.crd.yaml, operators/flux/0.36.0/manifests/helmrepository.crd.yaml, operators/flux/0.36.0/manifests/imagepolicy.crd.yaml, operators/flux/0.36.0/manifests/imagerepository.crd.yaml, operators/flux/0.36.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.36.0/manifests/kustomization.crd.yaml, operators/flux/0.36.0/manifests/notification-controller.service.yaml, operators/flux/0.36.0/manifests/ocirepository.crd.yaml, operators/flux/0.36.0/manifests/provider.crd.yaml, operators/flux/0.36.0/manifests/receiver.crd.yaml, operators/flux/0.36.0/manifests/source-controller.service.yaml, operators/flux/0.36.0/manifests/webhook-receiver.service.yaml, operators/flux/0.36.0/metadata/annotations.yaml
=> operator flux (0.36.0)

operators/annotationlab/4.1.2/bundle.Dockerfile, operators/annotationlab/4.1.2/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.1.2/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.1.2/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.1.2/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.1.2/metadata/annotations.yaml, operators/annotationlab/4.1.2/tests/scorecard/config.yaml, operators/annotationlab/ci.yaml
=> operator [CI] annotationlab (4.1.2)

operators/portworx-essentials/1.10.0/core_v1_storagecluster_crd.yaml, operators/portworx-essentials/1.10.0/core_v1_storagenode_crd.yaml, operators/portworx-essentials/1.10.0/portworxoperator.clusterserviceversion.yaml, operators/portworx-essentials/portworx.package.yaml
Signed-off-by: Jiafeng Liao <jliao@purestorage.com>
--
=> operator portworx-essentials (1.10.0)

operators/netobserv-operator/0.2.0/manifests/flows.netobserv.io_flowcollectors.yaml, operators/netobserv-operator/0.2.0/manifests/netobserv-manager-config_v1_configmap.yaml, operators/netobserv-operator/0.2.0/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/netobserv-operator/0.2.0/manifests/netobserv-metrics-service_v1_service.yaml, operators/netobserv-operator/0.2.0/manifests/netobserv-operator.clusterserviceversion.yaml, operators/netobserv-operator/0.2.0/metadata/annotations.yaml
=> operator netobserv-operator (0.2.0)

ci/pipeline-config-ocp.yaml
Remove deprecated indexes for installation and release
=> Remove deprecated indexes for installation and rel

operators/mongodb-atlas-kubernetes/1.4.0/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.4.0/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.4.0/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.4.0/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.4.0/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.4.0/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.4.0/tests/scorecard/config.yaml
Signed-off-by: Timur_Akhmadiev <Timur_Akhmadiev@epam.com>
--
=> operator mongodb-atlas-kubernetes (1.4.0)

operators/gitlab-operator-kubernetes/0.13.1/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.13.1/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.13.1/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.13.1/tests/scorecard/config.yaml
=> operator gitlab-operator-kubernetes (0.13.1)

operators/mongodb-atlas-kubernetes/ci.yaml
Signed-off-by: Timur_Akhmadiev <Timur_Akhmadiev@epam.com>
--
=> operator [CI] mongodb-atlas-kubernetes

operators/opendatahub-operator/1.4.0/manifests/kfdef.apps.kubeflow.org.crd.yaml, operators/opendatahub-operator/1.4.0/manifests/opendatahub-operator.v1.4.0.clusterserviceversion.yaml, operators/opendatahub-operator/1.4.0/metadata/annotations.yaml, operators/opendatahub-operator/ci.yaml
=> operator [CI] opendatahub-operator (1.4.0)

operators/forklift-operator/2.3.3/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.3.3/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.3.3/metadata/annotations.yaml, operators/forklift-operator/ci.yaml
=> operator [CI] forklift-operator (2.3.3)

operators/external-secrets-operator/0.6.1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.6.1/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.6.1/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.6.1/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.6.1/metadata/annotations.yaml, operators/external-secrets-operator/0.6.1/tests/scorecard/config.yaml
bump external-secrets-operator 0.6.1
=> operator external-secrets-operator (0.6.1)

operators/cluster-manager/0.9.1/cluster-manager.clusterserviceversion.yaml, operators/cluster-manager/0.9.1/operator.open-cluster-management.io_clustermanagers.yaml, operators/cluster-manager/cluster-manger.package.yaml
=> operator cluster-manager (0.9.1)

operators/klusterlet/0.9.1/klusterlet.clusterserviceversion.yaml, operators/klusterlet/0.9.1/operator.open-cluster-management.io_klusterlets.yaml, operators/klusterlet/klusterlet.package.yaml
=> operator klusterlet (0.9.1)

operators/project-quay/3.8.0-rc.5/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.0-rc.5/quayecosystems.crd.yaml, operators/project-quay/3.8.0-rc.5/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.5 to community operators
=> operator project-quay (3.8.0-rc.5)

operators/project-quay/3.7.10/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.7.10/quayecosystems.crd.yaml, operators/project-quay/3.7.10/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.7.10 to community operators
=> operator project-quay (3.7.10)

operators/annotationlab/4.2.0/bundle.Dockerfile, operators/annotationlab/4.2.0/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.2.0/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.2.0/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.2.0/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.2.0/metadata/annotations.yaml, operators/annotationlab/4.2.0/tests/scorecard/config.yaml, operators/annotationlab/ci.yaml
Signed-off-by: Bikash Bhandari <bhandari@johnsnowlabs.com>
--
=> operator [CI] annotationlab (4.2.0)

operators/annotationlab/4.2.1/bundle.Dockerfile, operators/annotationlab/4.2.1/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.2.1/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.2.1/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.2.1/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.2.1/metadata/annotations.yaml, operators/annotationlab/4.2.1/tests/scorecard/config.yaml
=> operator annotationlab (4.2.1)

operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.1/manifests/pulp-operator.v1.0.0-alpha.1.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-alpha.1/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-alpha.1/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-alpha.1/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-alpha.1/metadata/annotations.yaml, operators/pulp-operator/1.0.0-alpha.1/tests/scorecard/config.yaml
=> operator [R] pulp-operator (0.14.1 1.0.0-alpha.1)

operators/windup-operator/0.0.11/manifests/windup-operator.clusterserviceversion.yaml, operators/windup-operator/0.0.11/manifests/windup.crd.yaml, operators/windup-operator/0.0.11/metadata/annotations.yaml
Signed-off-by: carlosthe19916 <2582866+carlosthe19916@users.noreply.github.com>
--
=> operator [N] windup-operator (0.0.11)

operators/mongodb-atlas-kubernetes/1.4.1/bundle.Dockerfile, operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml, operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasbackupschedules.yaml, operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml, operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasdeployments.yaml, operators/mongodb-atlas-kubernetes/1.4.1/manifests/atlas.mongodb.com_atlasprojects.yaml, operators/mongodb-atlas-kubernetes/1.4.1/manifests/mongodb-atlas-controller-manager-metrics-service_v1_service.yaml, operators/mongodb-atlas-kubernetes/1.4.1/manifests/mongodb-atlas-kubernetes.clusterserviceversion.yaml, operators/mongodb-atlas-kubernetes/1.4.1/manifests/mongodb-atlas-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/mongodb-atlas-kubernetes/1.4.1/metadata/annotations.yaml, operators/mongodb-atlas-kubernetes/1.4.1/tests/scorecard/config.yaml
Signed-off-by: Helder Santana <helder.santana@mongodb.com>
--
=> operator mongodb-atlas-kubernetes (1.4.1)

operators/patterns-operator/0.0.7/manifests/gitops.hybrid-cloud-patterns.io_patterns.yaml, operators/patterns-operator/0.0.7/manifests/patterns-operator-controller-manager-metrics-service_v1_service.yaml, operators/patterns-operator/0.0.7/manifests/patterns-operator-manager-config_v1_configmap.yaml, operators/patterns-operator/0.0.7/manifests/patterns-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/patterns-operator/0.0.7/manifests/patterns-operator.clusterserviceversion.yaml, operators/patterns-operator/0.0.7/metadata/annotations.yaml, operators/patterns-operator/0.0.7/tests/scorecard/config.yaml
=> operator patterns-operator (0.0.7)

operators/kiali/1.59.0/bundle.Dockerfile, operators/kiali/1.59.0/manifests/kiali.crd.yaml, operators/kiali/1.59.0/manifests/kiali.v1.59.0.clusterserviceversion.yaml, operators/kiali/1.59.0/metadata/annotations.yaml
=> operator kiali (1.59.0)

operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.2/manifests/pulp-operator.1.0.0-alpha.2.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-alpha.2/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-alpha.2/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-alpha.2/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-alpha.2/metadata/annotations.yaml, operators/pulp-operator/1.0.0-alpha.2/tests/scorecard/config.yaml
=> operator pulp-operator (1.0.0-alpha.2)

operators/kubecost/1.97.0/bundle.Dockerfile, operators/kubecost/1.97.0/ci.yaml, operators/kubecost/1.97.0/manifests/charts.kubecost.com_costanalyzers.yaml, operators/kubecost/1.97.0/manifests/kubecost-controller-manager-metrics-service_v1_service.yaml, operators/kubecost/1.97.0/manifests/kubecost-manager-config_v1_configmap.yaml, operators/kubecost/1.97.0/manifests/kubecost-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/kubecost/1.97.0/manifests/kubecost.clusterserviceversion.yaml, operators/kubecost/1.97.0/metadata/annotations.yaml, operators/kubecost/1.97.0/tests/scorecard/config.yaml
Add new Kubecost operator 1.97.0
=> operator [N] [CI] kubecost (1.97.0)

operators/gitlab-operator-kubernetes/0.13.3/manifests/apps.gitlab.com_gitlabs.yaml, operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-controller-manager-metrics-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-operator-kubernetes.clusterserviceversion.yaml, operators/gitlab-operator-kubernetes/0.13.3/manifests/gitlab-webhook-service_v1_service.yaml, operators/gitlab-operator-kubernetes/0.13.3/metadata/annotations.yaml, operators/gitlab-operator-kubernetes/0.13.3/tests/scorecard/config.yaml
=> operator [R] gitlab-operator-kubernetes (0.13.3)

operators/camel-k/1.10.3/manifests/builds.camel.apache.org.crd.yaml, operators/camel-k/1.10.3/manifests/camel-k.v1.10.3.clusterserviceversion.yaml, operators/camel-k/1.10.3/manifests/camelcatalogs.camel.apache.org.crd.yaml, operators/camel-k/1.10.3/manifests/integrationkits.camel.apache.org.crd.yaml, operators/camel-k/1.10.3/manifests/integrationplatforms.camel.apache.org.crd.yaml, operators/camel-k/1.10.3/manifests/integrations.camel.apache.org.crd.yaml, operators/camel-k/1.10.3/manifests/kameletbindings.camel.apache.org.crd.yaml, operators/camel-k/1.10.3/manifests/kamelets.camel.apache.org.crd.yaml, operators/camel-k/1.10.3/metadata/annotations.yaml, operators/camel-k/1.10.3/tests/scorecard/config.yaml
=> operator camel-k (1.10.3)

operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.0.1/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.0.1/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.0.1/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.0.1/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.0.1/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.0.1/metadata/annotations.yaml, operators/cluster-aas-operator/0.0.1/metadata/dependencies.yaml, operators/cluster-aas-operator/0.0.1/tests/scorecard/config.yaml, operators/cluster-aas-operator/ci.yaml
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--
=> operator [N] [CI] cluster-aas-operator (0.0.1)

operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmagents.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmalertmanagerconfigs.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmalertmanagers.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmalerts.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmauths.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmclusters.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmnodescrapes.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmpodscrapes.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmprobes.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmrules.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmservicescrapes.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmsingles.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmstaticscrapes.yaml, operators/victoriametrics-operator/0.29.1/operator.victoriametrics.com_vmusers.yaml, operators/victoriametrics-operator/0.29.1/victoriametrics-operator.0.29.1.clusterserviceversion.yaml, operators/victoriametrics-operator/victoriametrics-operator.package.yaml
=> operator victoriametrics-operator (0.29.1)

operators/pulp-operator/0.10.0/manifests/pulp-operator.v0.10.0.clusterserviceversion.yaml, operators/pulp-operator/0.10.1/manifests/pulp-operator.v0.10.1.clusterserviceversion.yaml, operators/pulp-operator/0.5.0/manifests/pulp-operator.v0.5.0.clusterserviceversion.yaml, operators/pulp-operator/0.6.0/manifests/pulp-operator.v0.6.0.clusterserviceversion.yaml, operators/pulp-operator/0.6.1/manifests/pulp-operator.v0.6.1.clusterserviceversion.yaml, operators/pulp-operator/0.7.0/manifests/pulp-operator.v0.7.0.clusterserviceversion.yaml, operators/pulp-operator/0.7.1/manifests/pulp-operator.v0.7.1.clusterserviceversion.yaml, operators/pulp-operator/0.8.0/manifests/pulp-operator.v0.8.0.clusterserviceversion.yaml, operators/pulp-operator/0.9.0/manifests/pulp-operator.v0.9.0.clusterserviceversion.yaml
=> operator [R] pulp-operator (0.10.0 0.10.1 0.5.0 0.6.0 0.6.1 0.7.0 0.7.1 0.8.0 0.9.0)

operators/istio-workspace-operator/0.5.3/manifests/istio-workspace-operator.clusterserviceversion.yaml, operators/istio-workspace-operator/0.5.3/manifests/workspace.maistra.io_sessions.yaml, operators/istio-workspace-operator/0.5.3/metadata/annotations.yaml, operators/istio-workspace-operator/0.5.3/tests/scorecard/config.yaml
=> operator istio-workspace-operator (0.5.3)

operators/ack-kinesis-controller/ci.yaml
- onboarding new ACK controller
=> operator [CI] ack-kinesis-controller

operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, operators/opentelemetry-operator/0.62.1/manifests/opentelemetry-operator.clusterserviceversion.yaml, operators/opentelemetry-operator/0.62.1/manifests/opentelemetry.io_instrumentations.yaml, operators/opentelemetry-operator/0.62.1/manifests/opentelemetry.io_opentelemetrycollectors.yaml, operators/opentelemetry-operator/0.62.1/metadata/annotations.yaml, operators/opentelemetry-operator/0.62.1/tests/scorecard/config.yaml
Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>
--
=> operator opentelemetry-operator (0.62.1)

operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.3/manifests/pulp-operator.1.0.0-alpha.3.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-alpha.3/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-alpha.3/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-alpha.3/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-alpha.3/metadata/annotations.yaml, operators/pulp-operator/1.0.0-alpha.3/tests/scorecard/config.yaml
=> operator pulp-operator (1.0.0-alpha.3)

operators/ossmconsole/0.3.0/bundle.Dockerfile, operators/ossmconsole/0.3.0/manifests/ossmconsole.clusterserviceversion.yaml, operators/ossmconsole/0.3.0/manifests/ossmconsole.crd.yaml, operators/ossmconsole/0.3.0/metadata/annotations.yaml
This also does a trivial change to remove some end of line spaces - these are causing some diff issues. I want to clean this up now.
=> operator [R] ossmconsole (0.2.0 0.3.0)

operators/verticadb-operator/1.8.0/manifests/vertica.com_verticaautoscalers.yaml, operators/verticadb-operator/1.8.0/manifests/vertica.com_verticadbs.yaml, operators/verticadb-operator/1.8.0/manifests/verticadb-operator-manager-config_v1_configmap.yaml, operators/verticadb-operator/1.8.0/manifests/verticadb-operator-metrics-service_v1_service.yaml, operators/verticadb-operator/1.8.0/manifests/verticadb-operator-webhook-service_v1_service.yaml, operators/verticadb-operator/1.8.0/manifests/verticadb-operator.clusterserviceversion.yaml, operators/verticadb-operator/1.8.0/metadata/annotations.yaml, operators/verticadb-operator/1.8.0/tests/scorecard/config.yaml
Signed-off-by: Matt Spilchen <matt.spilchen@vertica.com>
--
=> operator verticadb-operator (1.8.0)

operators/annotationlab/4.2.1/manifests/annotationlab.clusterserviceversion.yaml
Signed-off-by: Bikash Bhandari <bhandari@johnsnowlabs.com>
--
=> operator [O] annotationlab (4.2.1)

operators/flink-kubernetes-operator/1.0.1/manifests/flink-kubernetes-operator.clusterserviceversion.yaml, operators/flink-kubernetes-operator/1.1.0/manifests/flink-kubernetes-operator.clusterserviceversion.yaml, operators/flink-kubernetes-operator/1.2.0/manifests/flink-kubernetes-operator.clusterserviceversion.yaml
Signed-off-by: James Busche <jbusche@us.ibm.com>
--
=> operator [R] flink-kubernetes-operator (1.0.1 1.1.0 1.2.0)

operators/annotationlab/4.3.0/bundle.Dockerfile, operators/annotationlab/4.3.0/manifests/annotationlab-controller-manager-metrics-service_v1_service.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-manager-config_v1_configmap.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/annotationlab/4.3.0/manifests/annotationlab-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, operators/annotationlab/4.3.0/manifests/annotationlab.clusterserviceversion.yaml, operators/annotationlab/4.3.0/manifests/apps.johnsnowlabs.com_annotationlabs.yaml, operators/annotationlab/4.3.0/metadata/annotations.yaml, operators/annotationlab/4.3.0/tests/scorecard/config.yaml
=> operator annotationlab (4.3.0)

operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.0.2/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.0.2/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.0.2/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.0.2/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.0.2/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.0.2/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.0.2/metadata/annotations.yaml, operators/cluster-aas-operator/0.0.2/metadata/dependencies.yaml, operators/cluster-aas-operator/0.0.2/tests/scorecard/config.yaml
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--
=> operator cluster-aas-operator (0.0.2)

operators/flux/0.37.0/manifests/alert.crd.yaml, operators/flux/0.37.0/manifests/bucket.crd.yaml, operators/flux/0.37.0/manifests/cluster-reconciler-flux-system.clusterrolebinding.yaml, operators/flux/0.37.0/manifests/crd-controller-flux-system.clusterrole.yaml, operators/flux/0.37.0/manifests/crd-controller-flux-system.clusterrolebinding.yaml, operators/flux/0.37.0/manifests/flux.v0.37.0.clusterserviceversion.yaml, operators/flux/0.37.0/manifests/gitrepository.crd.yaml, operators/flux/0.37.0/manifests/helmchart.crd.yaml, operators/flux/0.37.0/manifests/helmrelease.crd.yaml, operators/flux/0.37.0/manifests/helmrepository.crd.yaml, operators/flux/0.37.0/manifests/imagepolicy.crd.yaml, operators/flux/0.37.0/manifests/imagerepository.crd.yaml, operators/flux/0.37.0/manifests/imageupdateautomation.crd.yaml, operators/flux/0.37.0/manifests/kustomization.crd.yaml, operators/flux/0.37.0/manifests/notification-controller.service.yaml, operators/flux/0.37.0/manifests/ocirepository.crd.yaml, operators/flux/0.37.0/manifests/provider.crd.yaml, operators/flux/0.37.0/manifests/receiver.crd.yaml, operators/flux/0.37.0/manifests/source-controller.service.yaml, operators/flux/0.37.0/manifests/webhook-receiver.service.yaml, operators/flux/0.37.0/metadata/annotations.yaml
=> operator flux (0.37.0)

operators/microcks/1.6.1/microcks-operator.v1.6.1.clusterserviceversion.yaml, operators/microcks/1.6.1/microcksinstall.crd.yaml, operators/microcks/microcks.package.yaml
=> operator microcks (1.6.1)

operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-controller-manager-metrics-service_v1_service.yaml, operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-manager-config_v1_configmap.yaml, operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator-webhook-service_v1_service.yaml, operators/cluster-aas-operator/0.0.3/manifests/cluster-aas-operator.clusterserviceversion.yaml, operators/cluster-aas-operator/0.0.3/manifests/cluster_templates_user_ct_role.yaml, operators/cluster-aas-operator/0.0.3/manifests/cluster_templates_user_role.yaml, operators/cluster-aas-operator/0.0.3/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml, operators/cluster-aas-operator/0.0.3/manifests/clustertemplate.openshift.io_clustertemplatequotas.yaml, operators/cluster-aas-operator/0.0.3/manifests/clustertemplate.openshift.io_clustertemplates.yaml, operators/cluster-aas-operator/0.0.3/metadata/annotations.yaml, operators/cluster-aas-operator/0.0.3/metadata/dependencies.yaml, operators/cluster-aas-operator/0.0.3/tests/scorecard/config.yaml
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
--
=> operator cluster-aas-operator (0.0.3)

operators/rabbitmq-messaging-topology-operator/1.10.0/bundle.Dockerfile, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.clusterserviceversion.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_bindings.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_exchanges.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_federations.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_permissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_policies.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_queues.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_schemareplications.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_shovels.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_superstreams.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_topicpermissions.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_users.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.com_vhosts.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/manifests/rabbitmq.webhook-service.yaml, operators/rabbitmq-messaging-topology-operator/1.10.0/metadata/annotations.yaml
Signed-off-by: DanielePalaia <dpalaia@vmware.com>
--
=> operator rabbitmq-messaging-topology-operator (1.10.0)

operators/eclipse-amlen-operator/0.0.1/bundle.Dockerfile, operators/eclipse-amlen-operator/0.0.1/manifests/amlen-controller-manager-metrics-service_v1_service.yaml, operators/eclipse-amlen-operator/0.0.1/manifests/amlen-manager-config_v1_configmap.yaml, operators/eclipse-amlen-operator/0.0.1/manifests/amlen-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/eclipse-amlen-operator/0.0.1/manifests/eclipse-amlen-operator.clusterserviceversion.yaml, operators/eclipse-amlen-operator/0.0.1/manifests/eclipse.org_amlens.yaml, operators/eclipse-amlen-operator/0.0.1/metadata/annotations.yaml, operators/eclipse-amlen-operator/0.0.1/tests/scorecard/config.yaml, operators/eclipse-amlen-operator/ci.yaml
=> operator [N] [CI] eclipse-amlen-operator (0.0.1)

operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-manager-config_v1_configmap.yaml, operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/pulp-operator/1.0.0-alpha.4/manifests/pulp-operator.1.0.0-alpha.4.clusterserviceversion.yaml, operators/pulp-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, operators/pulp-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulprestores.yaml, operators/pulp-operator/1.0.0-alpha.4/manifests/repo-manager.pulpproject.org_pulps.yaml, operators/pulp-operator/1.0.0-alpha.4/metadata/annotations.yaml, operators/pulp-operator/1.0.0-alpha.4/tests/scorecard/config.yaml
=> operator pulp-operator (1.0.0-alpha.4)

operators/project-quay/3.8.0-rc.7/quay-operator.clusterserviceversion.yaml, operators/project-quay/3.8.0-rc.7/quayecosystems.crd.yaml, operators/project-quay/3.8.0-rc.7/quayregistries.crd.yaml, operators/project-quay/project-quay.package.yaml
Add v3.8.0-rc.7 to community operators
=> operator project-quay (3.8.0-rc.7)

operators/forklift-operator/2.3.4/manifests/forklift-operator.clusterserviceversion.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_forkliftcontrollers.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_hooks.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_hosts.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_migrations.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_networkmaps.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_plans.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_providers.yaml, operators/forklift-operator/2.3.4/manifests/forklift.konveyor.io_storagemaps.yaml, operators/forklift-operator/2.3.4/metadata/annotations.yaml, operators/forklift-operator/ci.yaml
=> operator [CI] forklift-operator (2.3.4)

operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets-operator-manager-config_v1_configmap.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets-operator.clusterserviceversion.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_clusterexternalsecrets.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_clustersecretstores.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_externalsecrets.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_pushsecrets.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/external-secrets.io_secretstores.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_acraccesstokens.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_ecrauthorizationtokens.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_fakes.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_gcraccesstokens.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/generators.external-secrets.io_passwords.yaml, operators/external-secrets-operator/0.7.0-rc1/manifests/operator.external-secrets.io_operatorconfigs.yaml, operators/external-secrets-operator/0.7.0-rc1/metadata/annotations.yaml, operators/external-secrets-operator/0.7.0-rc1/tests/scorecard/config.yaml
bump external-secrets-operator 0.7.0-rc1
=> operator external-secrets-operator (0.7.0-rc1)
